# -*- coding: utf-8 -*-
"""Content for the 'SplitCam vs OBS / free OBS alternative' page, per language.

Each entry:
  title, desc, h1html, h1short, intro (HTML),
  table_h, col_sc, col_obs, rows = [(feature, splitcam_cell, obs_cell), ...],
  verdict_h, verdict (HTML), faq = [(q, a), ...]
The page is built by render_obs_vs() in build.py.
"""

OBS_VS = {
    "en": {
        "title": "SplitCam vs OBS — Free OBS Alternative for Cam Streaming",
        "desc": "SplitCam is a free, lightweight OBS alternative for cam streaming — built-in virtual camera, one-click multistreaming, beauty filters, no watermark. Compared side by side.",
        "h1html": 'SplitCam vs OBS — the free <span class="accent">OBS alternative</span>',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio is the powerhouse of live streaming — endlessly configurable and free. But for cam streaming most of that power is overkill, and the setup curve is steep. <strong style='color:var(--text)'>SplitCam</strong> is a lighter, free OBS alternative: a built-in virtual camera, one-click multistreaming and beauty filters out of the box, with the same custom RTMP that lets it broadcast to any cam platform. Here's how the two compare.",
        "table_h": "Side-by-side comparison",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Price", "Free, no watermark", "Free, open-source"),
            ("Learning curve", "Beginner-friendly", "Steep"),
            ("Virtual camera", "Built-in", "Built-in (recent versions)"),
            ("Multistreaming to many sites", "Built-in, one click", "Needs a plugin / relay"),
            ("Beauty filters & AI background", "Built-in", "Not native"),
            ("Cam-platform presets", "Yes (Streamate, VISIT-X…)", "Manual RTMP only"),
            ("Custom RTMP output", "Yes", "Yes"),
            ("System load", "Light", "Heavier"),
        ],
        "verdict_h": "Which should you pick?",
        "verdict": "Choose <strong style='color:var(--text)'>OBS</strong> if you want total control over complex scenes and don't mind the setup. Choose <strong style='color:var(--text)'>SplitCam</strong> if you want to be live in minutes — it has the cam essentials (virtual camera, multistream, beauty filters, platform presets) built in, and still gives you custom RTMP for any site.",
        "faq": [
            ("Is SplitCam a good OBS alternative?", "Yes — for cam streaming it covers the same core job (encode your camera and send it to a platform via RTMP) with a far gentler setup, plus built-in multistreaming and beauty filters that OBS needs plugins for."),
            ("Is SplitCam free like OBS?", "Yes. SplitCam is free with no watermark and no time limit, the same as OBS. Neither charges to stream."),
            ("Can SplitCam stream to multiple platforms at once like OBS with a plugin?", "Yes, and it's built in — no plugin or paid relay. Add each platform's RTMP key and go live to all of them with one click."),
            ("Does SplitCam work on the same sites as OBS?", "Yes — anything that accepts a custom RTMP stream key (Chaturbate, Stripchat, BongaCams, CAM4 and more) works with SplitCam, plus it has ready presets for several cam platforms."),
        ],
    },
    "ru": {
        "title": "SplitCam vs OBS — бесплатная альтернатива OBS для кам-стрима",
        "desc": "SplitCam — бесплатная лёгкая альтернатива OBS для кам-стриминга: встроенная виртуальная камера, мультистрим в один клик, бьюти-фильтры, без водяного знака. Сравнение бок о бок.",
        "h1html": 'SplitCam vs OBS — бесплатная <span class="accent">альтернатива OBS</span>',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio — тяжёлая артиллерия стриминга: бесконечно настраиваемый и бесплатный. Но для кам-стрима бо́льшая часть этой мощи избыточна, а порог входа высокий. <strong style='color:var(--text)'>SplitCam</strong> — лёгкая бесплатная альтернатива OBS: встроенная виртуальная камера, мультистрим в один клик и бьюти-фильтры из коробки, и тот же custom RTMP, чтобы вещать на любую кам-платформу. Вот как они сравниваются.",
        "table_h": "Сравнение бок о бок",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Цена", "Бесплатно, без водяного знака", "Бесплатно, open-source"),
            ("Порог входа", "Просто для новичка", "Высокий"),
            ("Виртуальная камера", "Встроена", "Встроена (в новых версиях)"),
            ("Мультистрим на много сайтов", "Встроен, один клик", "Нужен плагин / релей"),
            ("Бьюти-фильтры и AI-фон", "Встроены", "Нет нативно"),
            ("Пресеты кам-платформ", "Есть (Streamate, VISIT-X…)", "Только ручной RTMP"),
            ("Произвольный RTMP", "Да", "Да"),
            ("Нагрузка на систему", "Лёгкая", "Тяжелее"),
        ],
        "verdict_h": "Что выбрать?",
        "verdict": "Бери <strong style='color:var(--text)'>OBS</strong>, если нужен полный контроль над сложными сценами и не пугает настройка. Бери <strong style='color:var(--text)'>SplitCam</strong>, если хочешь выйти в эфир за минуты — в нём из коробки всё для кама (виртуальная камера, мультистрим, бьюти-фильтры, пресеты платформ), и при этом есть произвольный RTMP под любой сайт.",
        "faq": [
            ("SplitCam — хорошая альтернатива OBS?", "Да — для кам-стрима он закрывает ту же задачу (кодирует камеру и шлёт на платформу по RTMP) с куда более простой настройкой, плюс встроенные мультистрим и бьюти-фильтры, для которых OBS нужны плагины."),
            ("SplitCam бесплатный, как OBS?", "Да. SplitCam бесплатен, без водяного знака и без ограничения по времени — как и OBS. Оба не берут денег за эфир."),
            ("SplitCam умеет вещать на несколько платформ сразу, как OBS с плагином?", "Да, и это встроено — без плагина и платного релея. Добавь RTMP-ключ каждой платформы и выйди в эфир на все одним кликом."),
            ("SplitCam работает на тех же сайтах, что и OBS?", "Да — всё, что принимает произвольный RTMP-ключ (Chaturbate, Stripchat, BongaCams, CAM4 и др.), работает со SplitCam, плюс есть готовые пресеты для ряда кам-платформ."),
        ],
    },
    "es": {
        "title": "SplitCam vs OBS — alternativa gratuita a OBS para cam streaming",
        "desc": "SplitCam es una alternativa gratuita y ligera a OBS para cam streaming: cámara virtual integrada, multistreaming en un clic, filtros de belleza, sin marca de agua. Comparación lado a lado.",
        "h1html": 'SplitCam vs OBS — la <span class="accent">alternativa a OBS</span> gratuita',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio es la artillería pesada del streaming: infinitamente configurable y gratis. Pero para el cam streaming gran parte de ese poder sobra, y la curva de configuración es empinada. <strong style='color:var(--text)'>SplitCam</strong> es una alternativa a OBS más ligera y gratuita: cámara virtual integrada, multistreaming en un clic y filtros de belleza de fábrica, con el mismo RTMP personalizado para transmitir a cualquier plataforma cam. Así se comparan.",
        "table_h": "Comparación lado a lado",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Precio", "Gratis, sin marca de agua", "Gratis, código abierto"),
            ("Curva de aprendizaje", "Fácil para principiantes", "Empinada"),
            ("Cámara virtual", "Integrada", "Integrada (versiones recientes)"),
            ("Multistreaming a varios sitios", "Integrado, un clic", "Necesita plugin / relay"),
            ("Filtros de belleza y fondo IA", "Integrados", "No nativo"),
            ("Presets de plataformas cam", "Sí (Streamate, VISIT-X…)", "Solo RTMP manual"),
            ("RTMP personalizado", "Sí", "Sí"),
            ("Carga del sistema", "Ligera", "Más pesada"),
        ],
        "verdict_h": "¿Cuál elegir?",
        "verdict": "Elige <strong style='color:var(--text)'>OBS</strong> si quieres control total sobre escenas complejas y no te importa la configuración. Elige <strong style='color:var(--text)'>SplitCam</strong> si quieres estar en directo en minutos — trae lo esencial del cam (cámara virtual, multistream, filtros de belleza, presets de plataformas) integrado, y aun así te da RTMP personalizado para cualquier sitio.",
        "faq": [
            ("¿Es SplitCam una buena alternativa a OBS?", "Sí — para cam streaming cubre el mismo trabajo central (codificar tu cámara y enviarla a una plataforma vía RTMP) con una configuración mucho más sencilla, además de multistreaming y filtros de belleza integrados que en OBS requieren plugins."),
            ("¿Es SplitCam gratis como OBS?", "Sí. SplitCam es gratis, sin marca de agua y sin límite de tiempo, igual que OBS. Ninguno cobra por transmitir."),
            ("¿SplitCam puede transmitir a varias plataformas a la vez como OBS con un plugin?", "Sí, y viene integrado — sin plugin ni relay de pago. Añade la clave RTMP de cada plataforma y emite a todas con un clic."),
            ("¿SplitCam funciona en los mismos sitios que OBS?", "Sí — todo lo que acepte una clave RTMP personalizada (Chaturbate, Stripchat, BongaCams, CAM4 y más) funciona con SplitCam, y además tiene presets listos para varias plataformas cam."),
        ],
    },
    "de": {
        "title": "SplitCam vs OBS — kostenlose OBS-Alternative für Cam-Streaming",
        "desc": "SplitCam ist eine kostenlose, leichte OBS-Alternative für Cam-Streaming: eingebaute virtuelle Kamera, Multistreaming mit einem Klick, Beauty-Filter, kein Wasserzeichen. Direkter Vergleich.",
        "h1html": 'SplitCam vs OBS — die kostenlose <span class="accent">OBS-Alternative</span>',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio ist das Schwergewicht des Live-Streamings — endlos konfigurierbar und kostenlos. Aber fürs Cam-Streaming ist der Großteil dieser Power überdimensioniert, und die Einrichtungskurve ist steil. <strong style='color:var(--text)'>SplitCam</strong> ist eine leichtere, kostenlose OBS-Alternative: eingebaute virtuelle Kamera, Multistreaming mit einem Klick und Beauty-Filter ab Werk, mit demselben Custom-RTMP, um auf jede Cam-Plattform zu senden. So vergleichen sich beide.",
        "table_h": "Direkter Vergleich",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Preis", "Kostenlos, kein Wasserzeichen", "Kostenlos, Open Source"),
            ("Lernkurve", "Anfängerfreundlich", "Steil"),
            ("Virtuelle Kamera", "Eingebaut", "Eingebaut (neuere Versionen)"),
            ("Multistreaming auf viele Seiten", "Eingebaut, ein Klick", "Braucht Plugin / Relay"),
            ("Beauty-Filter & KI-Hintergrund", "Eingebaut", "Nicht nativ"),
            ("Cam-Plattform-Presets", "Ja (Streamate, VISIT-X…)", "Nur manuelles RTMP"),
            ("Custom-RTMP-Ausgabe", "Ja", "Ja"),
            ("Systemlast", "Leicht", "Schwerer"),
        ],
        "verdict_h": "Was solltest du wählen?",
        "verdict": "Wähle <strong style='color:var(--text)'>OBS</strong>, wenn du volle Kontrolle über komplexe Szenen willst und die Einrichtung nicht scheust. Wähle <strong style='color:var(--text)'>SplitCam</strong>, wenn du in Minuten live sein willst — es hat die Cam-Essentials (virtuelle Kamera, Multistream, Beauty-Filter, Plattform-Presets) eingebaut und gibt dir trotzdem Custom-RTMP für jede Seite.",
        "faq": [
            ("Ist SplitCam eine gute OBS-Alternative?", "Ja — fürs Cam-Streaming erledigt es dieselbe Kernaufgabe (deine Kamera kodieren und per RTMP an eine Plattform senden) mit deutlich einfacherer Einrichtung, plus eingebautes Multistreaming und Beauty-Filter, für die OBS Plugins braucht."),
            ("Ist SplitCam kostenlos wie OBS?", "Ja. SplitCam ist kostenlos, ohne Wasserzeichen und ohne Zeitlimit, genau wie OBS. Keines verlangt Geld fürs Streamen."),
            ("Kann SplitCam wie OBS mit Plugin auf mehrere Plattformen gleichzeitig senden?", "Ja, und es ist eingebaut — ohne Plugin oder bezahlten Relay. Füge den RTMP-Key jeder Plattform hinzu und gehe mit einem Klick auf allen live."),
            ("Funktioniert SplitCam auf denselben Seiten wie OBS?", "Ja — alles, was einen Custom-RTMP-Key akzeptiert (Chaturbate, Stripchat, BongaCams, CAM4 und mehr), funktioniert mit SplitCam, plus es hat fertige Presets für mehrere Cam-Plattformen."),
        ],
    },
    "fr": {
        "title": "SplitCam vs OBS — alternative gratuite à OBS pour le cam streaming",
        "desc": "SplitCam est une alternative gratuite et légère à OBS pour le cam streaming : caméra virtuelle intégrée, multistreaming en un clic, filtres beauté, sans filigrane. Comparaison côte à côte.",
        "h1html": 'SplitCam vs OBS — l\'<span class="accent">alternative à OBS</span> gratuite',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio est le poids lourd du live streaming — infiniment configurable et gratuit. Mais pour le cam streaming, l'essentiel de cette puissance est superflu, et la courbe de configuration est raide. <strong style='color:var(--text)'>SplitCam</strong> est une alternative à OBS plus légère et gratuite : caméra virtuelle intégrée, multistreaming en un clic et filtres beauté d'origine, avec le même RTMP personnalisé pour diffuser sur n'importe quelle plateforme cam. Voici la comparaison.",
        "table_h": "Comparaison côte à côte",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Prix", "Gratuit, sans filigrane", "Gratuit, open source"),
            ("Prise en main", "Facile pour débutants", "Raide"),
            ("Caméra virtuelle", "Intégrée", "Intégrée (versions récentes)"),
            ("Multistreaming vers plusieurs sites", "Intégré, un clic", "Nécessite plugin / relais"),
            ("Filtres beauté & fond IA", "Intégrés", "Pas en natif"),
            ("Presets de plateformes cam", "Oui (Streamate, VISIT-X…)", "RTMP manuel seulement"),
            ("Sortie RTMP personnalisée", "Oui", "Oui"),
            ("Charge système", "Légère", "Plus lourde"),
        ],
        "verdict_h": "Lequel choisir ?",
        "verdict": "Choisis <strong style='color:var(--text)'>OBS</strong> si tu veux un contrôle total sur des scènes complexes et que la configuration ne te rebute pas. Choisis <strong style='color:var(--text)'>SplitCam</strong> si tu veux être en direct en quelques minutes — il intègre l'essentiel du cam (caméra virtuelle, multistream, filtres beauté, presets de plateformes) et te donne quand même un RTMP personnalisé pour tout site.",
        "faq": [
            ("SplitCam est-il une bonne alternative à OBS ?", "Oui — pour le cam streaming, il fait le même travail de fond (encoder ta caméra et l'envoyer à une plateforme via RTMP) avec une configuration bien plus simple, plus le multistreaming et les filtres beauté intégrés pour lesquels OBS a besoin de plugins."),
            ("SplitCam est-il gratuit comme OBS ?", "Oui. SplitCam est gratuit, sans filigrane et sans limite de temps, comme OBS. Aucun ne fait payer la diffusion."),
            ("SplitCam peut-il diffuser sur plusieurs plateformes à la fois comme OBS avec un plugin ?", "Oui, et c'est intégré — sans plugin ni relais payant. Ajoute la clé RTMP de chaque plateforme et passe en direct sur toutes en un clic."),
            ("SplitCam fonctionne-t-il sur les mêmes sites qu'OBS ?", "Oui — tout ce qui accepte une clé RTMP personnalisée (Chaturbate, Stripchat, BongaCams, CAM4 et plus) marche avec SplitCam, et il a des presets prêts pour plusieurs plateformes cam."),
        ],
    },
    "it": {
        "title": "SplitCam vs OBS — alternativa gratuita a OBS per il cam streaming",
        "desc": "SplitCam è un'alternativa gratuita e leggera a OBS per il cam streaming: camera virtuale integrata, multistreaming con un clic, filtri beauty, senza filigrana. Confronto fianco a fianco.",
        "h1html": 'SplitCam vs OBS — l\'<span class="accent">alternativa a OBS</span> gratuita',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio è il peso massimo dello streaming — infinitamente configurabile e gratuito. Ma per il cam streaming gran parte di quella potenza è eccessiva, e la curva di configurazione è ripida. <strong style='color:var(--text)'>SplitCam</strong> è un'alternativa a OBS più leggera e gratuita: camera virtuale integrata, multistreaming con un clic e filtri beauty di serie, con lo stesso RTMP personalizzato per trasmettere su qualsiasi piattaforma cam. Ecco il confronto.",
        "table_h": "Confronto fianco a fianco",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Prezzo", "Gratis, senza filigrana", "Gratis, open source"),
            ("Curva di apprendimento", "Facile per principianti", "Ripida"),
            ("Camera virtuale", "Integrata", "Integrata (versioni recenti)"),
            ("Multistreaming su più siti", "Integrato, un clic", "Serve plugin / relay"),
            ("Filtri beauty e sfondo IA", "Integrati", "Non nativo"),
            ("Preset piattaforme cam", "Sì (Streamate, VISIT-X…)", "Solo RTMP manuale"),
            ("Uscita RTMP personalizzata", "Sì", "Sì"),
            ("Carico di sistema", "Leggero", "Più pesante"),
        ],
        "verdict_h": "Quale scegliere?",
        "verdict": "Scegli <strong style='color:var(--text)'>OBS</strong> se vuoi il controllo totale su scene complesse e non ti spaventa la configurazione. Scegli <strong style='color:var(--text)'>SplitCam</strong> se vuoi andare in diretta in pochi minuti — ha gli essenziali del cam (camera virtuale, multistream, filtri beauty, preset piattaforme) integrati, e ti dà comunque RTMP personalizzato per qualsiasi sito.",
        "faq": [
            ("SplitCam è una buona alternativa a OBS?", "Sì — per il cam streaming copre lo stesso lavoro di base (codificare la tua camera e inviarla a una piattaforma via RTMP) con una configurazione molto più semplice, più multistreaming e filtri beauty integrati per cui OBS ha bisogno di plugin."),
            ("SplitCam è gratis come OBS?", "Sì. SplitCam è gratis, senza filigrana e senza limite di tempo, proprio come OBS. Nessuno dei due fa pagare la trasmissione."),
            ("SplitCam può trasmettere su più piattaforme insieme come OBS con un plugin?", "Sì, ed è integrato — senza plugin né relay a pagamento. Aggiungi la chiave RTMP di ogni piattaforma e vai in diretta su tutte con un clic."),
            ("SplitCam funziona sugli stessi siti di OBS?", "Sì — tutto ciò che accetta una chiave RTMP personalizzata (Chaturbate, Stripchat, BongaCams, CAM4 e altro) funziona con SplitCam, e ha preset pronti per diverse piattaforme cam."),
        ],
    },
    "pt": {
        "title": "SplitCam vs OBS — alternativa grátis ao OBS pra cam streaming",
        "desc": "O SplitCam é uma alternativa grátis e leve ao OBS pra cam streaming: câmera virtual integrada, multistream num clique, filtros de beleza, sem marca d'água. Comparação lado a lado.",
        "h1html": 'SplitCam vs OBS — a <span class="accent">alternativa ao OBS</span> grátis',
        "h1short": "SplitCam vs OBS",
        "intro": "O OBS Studio é o peso-pesado do streaming — infinitamente configurável e grátis. Mas pro cam streaming boa parte desse poder é exagero, e a curva de configuração é íngreme. O <strong style='color:var(--text)'>SplitCam</strong> é uma alternativa ao OBS mais leve e grátis: câmera virtual integrada, multistream num clique e filtros de beleza de fábrica, com o mesmo RTMP personalizado pra transmitir em qualquer plataforma cam. Veja a comparação.",
        "table_h": "Comparação lado a lado",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Preço", "Grátis, sem marca d'água", "Grátis, código aberto"),
            ("Curva de aprendizado", "Fácil pra iniciantes", "Íngreme"),
            ("Câmera virtual", "Integrada", "Integrada (versões recentes)"),
            ("Multistream pra vários sites", "Integrado, um clique", "Precisa de plugin / relay"),
            ("Filtros de beleza e fundo IA", "Integrados", "Não nativo"),
            ("Presets de plataformas cam", "Sim (Streamate, VISIT-X…)", "Só RTMP manual"),
            ("Saída RTMP personalizada", "Sim", "Sim"),
            ("Carga no sistema", "Leve", "Mais pesada"),
        ],
        "verdict_h": "Qual escolher?",
        "verdict": "Escolha o <strong style='color:var(--text)'>OBS</strong> se quer controle total sobre cenas complexas e não se importa com a configuração. Escolha o <strong style='color:var(--text)'>SplitCam</strong> se quer entrar ao vivo em minutos — ele traz o essencial do cam (câmera virtual, multistream, filtros de beleza, presets de plataformas) integrado, e ainda te dá RTMP personalizado pra qualquer site.",
        "faq": [
            ("O SplitCam é uma boa alternativa ao OBS?", "Sim — pro cam streaming ele cobre o mesmo trabalho central (codificar sua câmera e mandar pra plataforma via RTMP) com configuração bem mais simples, além de multistream e filtros de beleza integrados que no OBS precisam de plugins."),
            ("O SplitCam é grátis como o OBS?", "Sim. O SplitCam é grátis, sem marca d'água e sem limite de tempo, igual ao OBS. Nenhum cobra pra transmitir."),
            ("O SplitCam transmite pra várias plataformas ao mesmo tempo como o OBS com plugin?", "Sim, e é integrado — sem plugin nem relay pago. Adicione a chave RTMP de cada plataforma e entre ao vivo em todas com um clique."),
            ("O SplitCam funciona nos mesmos sites que o OBS?", "Sim — tudo que aceita uma chave RTMP personalizada (Chaturbate, Stripchat, BongaCams, CAM4 e mais) funciona com o SplitCam, e ele tem presets prontos pra várias plataformas cam."),
        ],
    },
    "nl": {
        "title": "SplitCam vs OBS — gratis OBS-alternatief voor cam-streaming",
        "desc": "SplitCam is een gratis, licht OBS-alternatief voor cam-streaming: ingebouwde virtuele camera, multistreaming met één klik, beautyfilters, geen watermerk. Naast elkaar vergeleken.",
        "h1html": 'SplitCam vs OBS — het gratis <span class="accent">OBS-alternatief</span>',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio is het zwaargewicht van live streaming — eindeloos instelbaar en gratis. Maar voor cam-streaming is het grootste deel van die kracht overkill, en de instelcurve is steil. <strong style='color:var(--text)'>SplitCam</strong> is een lichter, gratis OBS-alternatief: ingebouwde virtuele camera, multistreaming met één klik en beautyfilters standaard, met dezelfde custom RTMP om naar elk camplatform te zenden. Zo verhouden ze zich.",
        "table_h": "Vergelijking naast elkaar",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Prijs", "Gratis, geen watermerk", "Gratis, open source"),
            ("Leercurve", "Beginnersvriendelijk", "Steil"),
            ("Virtuele camera", "Ingebouwd", "Ingebouwd (recente versies)"),
            ("Multistreaming naar veel sites", "Ingebouwd, één klik", "Plugin / relay nodig"),
            ("Beautyfilters & AI-achtergrond", "Ingebouwd", "Niet native"),
            ("Camplatform-presets", "Ja (Streamate, VISIT-X…)", "Alleen handmatig RTMP"),
            ("Custom RTMP-uitvoer", "Ja", "Ja"),
            ("Systeembelasting", "Licht", "Zwaarder"),
        ],
        "verdict_h": "Welke kies je?",
        "verdict": "Kies <strong style='color:var(--text)'>OBS</strong> als je volledige controle over complexe scènes wilt en de setup je niet afschrikt. Kies <strong style='color:var(--text)'>SplitCam</strong> als je binnen minuten live wilt — het heeft de cam-essentials (virtuele camera, multistream, beautyfilters, platform-presets) ingebouwd, en geeft je toch custom RTMP voor elke site.",
        "faq": [
            ("Is SplitCam een goed OBS-alternatief?", "Ja — voor cam-streaming doet het hetzelfde kernwerk (je camera coderen en via RTMP naar een platform sturen) met een veel eenvoudigere setup, plus ingebouwde multistreaming en beautyfilters waarvoor OBS plugins nodig heeft."),
            ("Is SplitCam gratis zoals OBS?", "Ja. SplitCam is gratis, zonder watermerk en zonder tijdslimiet, net als OBS. Geen van beide rekent voor het streamen."),
            ("Kan SplitCam naar meerdere platforms tegelijk streamen zoals OBS met een plugin?", "Ja, en het is ingebouwd — geen plugin of betaalde relay. Voeg de RTMP-key van elk platform toe en ga met één klik op alle live."),
            ("Werkt SplitCam op dezelfde sites als OBS?", "Ja — alles dat een custom RTMP-key accepteert (Chaturbate, Stripchat, BongaCams, CAM4 en meer) werkt met SplitCam, plus het heeft kant-en-klare presets voor meerdere camplatforms."),
        ],
    },
    "ro": {
        "title": "SplitCam vs OBS — alternativă gratuită la OBS pentru cam streaming",
        "desc": "SplitCam este o alternativă gratuită și ușoară la OBS pentru cam streaming: cameră virtuală integrată, multistreaming dintr-un clic, filtre beauty, fără filigran. Comparație alăturată.",
        "h1html": 'SplitCam vs OBS — <span class="accent">alternativa la OBS</span> gratuită',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio este greutatea grea a streamingului — infinit configurabil și gratuit. Dar pentru cam streaming mare parte din acea putere e exagerată, iar curba de configurare e abruptă. <strong style='color:var(--text)'>SplitCam</strong> este o alternativă la OBS mai ușoară și gratuită: cameră virtuală integrată, multistreaming dintr-un clic și filtre beauty din start, cu același RTMP personalizat pentru a transmite pe orice platformă cam. Iată comparația.",
        "table_h": "Comparație alăturată",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Preț", "Gratuit, fără filigran", "Gratuit, open source"),
            ("Curba de învățare", "Ușor pentru începători", "Abruptă"),
            ("Cameră virtuală", "Integrată", "Integrată (versiuni recente)"),
            ("Multistreaming pe mai multe site-uri", "Integrat, un clic", "Necesită plugin / relay"),
            ("Filtre beauty și fundal AI", "Integrate", "Nu nativ"),
            ("Presetări platforme cam", "Da (Streamate, VISIT-X…)", "Doar RTMP manual"),
            ("Ieșire RTMP personalizată", "Da", "Da"),
            ("Încărcare sistem", "Ușoară", "Mai mare"),
        ],
        "verdict_h": "Pe care să-l alegi?",
        "verdict": "Alege <strong style='color:var(--text)'>OBS</strong> dacă vrei control total asupra scenelor complexe și nu te deranjează configurarea. Alege <strong style='color:var(--text)'>SplitCam</strong> dacă vrei să fii live în câteva minute — are esențialul de cam (cameră virtuală, multistream, filtre beauty, presetări platforme) integrat și îți oferă totuși RTMP personalizat pentru orice site.",
        "faq": [
            ("Este SplitCam o alternativă bună la OBS?", "Da — pentru cam streaming acoperă aceeași sarcină de bază (codează camera și o trimite la o platformă prin RTMP) cu o configurare mult mai simplă, plus multistreaming și filtre beauty integrate pentru care OBS are nevoie de plugin-uri."),
            ("Este SplitCam gratuit ca OBS?", "Da. SplitCam este gratuit, fără filigran și fără limită de timp, la fel ca OBS. Niciunul nu percepe taxă pentru transmisiune."),
            ("Poate SplitCam transmite pe mai multe platforme simultan ca OBS cu plugin?", "Da, și e integrat — fără plugin sau relay plătit. Adaugă cheia RTMP a fiecărei platforme și intră live pe toate cu un clic."),
            ("Funcționează SplitCam pe aceleași site-uri ca OBS?", "Da — orice acceptă o cheie RTMP personalizată (Chaturbate, Stripchat, BongaCams, CAM4 și altele) funcționează cu SplitCam, plus are presetări gata pentru mai multe platforme cam."),
        ],
    },
    "bg": {
        "title": "SplitCam срещу OBS — безплатна алтернатива на OBS за кам стрийминг",
        "desc": "SplitCam е безплатна, лека алтернатива на OBS за кам стрийминг: вградена виртуална камера, мултистрийминг с един клик, бюти филтри, без воден знак. Сравнение едно до друго.",
        "h1html": 'SplitCam срещу OBS — безплатната <span class="accent">алтернатива на OBS</span>',
        "h1short": "SplitCam срещу OBS",
        "intro": "OBS Studio е тежката артилерия на стрийминга — безкрайно конфигуруем и безплатен. Но за кам стрийминг по-голямата част от тази мощ е излишна, а кривата на настройка е стръмна. <strong style='color:var(--text)'>SplitCam</strong> е по-лека, безплатна алтернатива на OBS: вградена виртуална камера, мултистрийминг с един клик и бюти филтри по подразбиране, със същия персонализиран RTMP за излъчване на всяка кам платформа. Ето как се сравняват.",
        "table_h": "Сравнение едно до друго",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Цена", "Безплатно, без воден знак", "Безплатно, отворен код"),
            ("Крива на учене", "Лесно за начинаещи", "Стръмна"),
            ("Виртуална камера", "Вградена", "Вградена (нови версии)"),
            ("Мултистрийминг към много сайтове", "Вграден, един клик", "Нужен плъгин / релей"),
            ("Бюти филтри и AI фон", "Вградени", "Не нативно"),
            ("Пресети за кам платформи", "Да (Streamate, VISIT-X…)", "Само ръчен RTMP"),
            ("Персонализиран RTMP изход", "Да", "Да"),
            ("Натоварване на системата", "Леко", "По-тежко"),
        ],
        "verdict_h": "Кое да избереш?",
        "verdict": "Избери <strong style='color:var(--text)'>OBS</strong>, ако искаш пълен контрол над сложни сцени и настройката не те плаши. Избери <strong style='color:var(--text)'>SplitCam</strong>, ако искаш да си в ефир за минути — има вграден кам essentials (виртуална камера, мултистрийм, бюти филтри, пресети за платформи) и пак ти дава персонализиран RTMP за всеки сайт.",
        "faq": [
            ("SplitCam добра алтернатива на OBS ли е?", "Да — за кам стрийминг покрива същата основна задача (кодира камерата и я праща към платформа през RTMP) с много по-проста настройка, плюс вградени мултистрийминг и бюти филтри, за които OBS се нуждае от плъгини."),
            ("SplitCam безплатен ли е като OBS?", "Да. SplitCam е безплатен, без воден знак и без времево ограничение, точно като OBS. Нито един не взима пари за излъчване."),
            ("Може ли SplitCam да излъчва на няколко платформи едновременно като OBS с плъгин?", "Да, и е вградено — без плъгин или платен релей. Добави RTMP ключа на всяка платформа и излез на живо на всички с един клик."),
            ("SplitCam работи ли на същите сайтове като OBS?", "Да — всичко, което приема персонализиран RTMP ключ (Chaturbate, Stripchat, BongaCams, CAM4 и др.), работи със SplitCam, плюс има готови пресети за няколко кам платформи."),
        ],
    },
    "hu": {
        "title": "SplitCam vs OBS — ingyenes OBS-alternatíva cam streaminghez",
        "desc": "A SplitCam ingyenes, könnyű OBS-alternatíva cam streaminghez: beépített virtuális kamera, egykattintásos multistreaming, szépségszűrők, vízjel nélkül. Egymás melletti összehasonlítás.",
        "h1html": 'SplitCam vs OBS — az ingyenes <span class="accent">OBS-alternatíva</span>',
        "h1short": "SplitCam vs OBS",
        "intro": "Az OBS Studio a streaming nehézsúlyú bajnoka — végtelenül konfigurálható és ingyenes. De cam streaminghez ennek a teljesítménynek a nagy része túlzás, és a beállítási görbe meredek. A <strong style='color:var(--text)'>SplitCam</strong> egy könnyebb, ingyenes OBS-alternatíva: beépített virtuális kamera, egykattintásos multistreaming és szépségszűrők alapból, ugyanazzal a custom RTMP-vel, amellyel bármely cam platformra adhatsz. Így hasonlítanak össze.",
        "table_h": "Egymás melletti összehasonlítás",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Ár", "Ingyenes, vízjel nélkül", "Ingyenes, nyílt forrású"),
            ("Tanulási görbe", "Kezdőbarát", "Meredek"),
            ("Virtuális kamera", "Beépített", "Beépített (újabb verziók)"),
            ("Multistreaming sok oldalra", "Beépített, egy kattintás", "Plugin / relay kell"),
            ("Szépségszűrők és AI háttér", "Beépített", "Nem natív"),
            ("Cam platform presetek", "Igen (Streamate, VISIT-X…)", "Csak kézi RTMP"),
            ("Egyedi RTMP kimenet", "Igen", "Igen"),
            ("Rendszerterhelés", "Könnyű", "Nehezebb"),
        ],
        "verdict_h": "Melyiket válaszd?",
        "verdict": "Válaszd az <strong style='color:var(--text)'>OBS</strong>-t, ha teljes kontrollt akarsz a komplex jelenetek felett, és nem zavar a beállítás. Válaszd a <strong style='color:var(--text)'>SplitCam</strong>-et, ha percek alatt élőben akarsz lenni — a cam alapokat (virtuális kamera, multistream, szépségszűrők, platform presetek) beépítve hozza, és így is ad egyedi RTMP-t bármely oldalra.",
        "faq": [
            ("Jó OBS-alternatíva a SplitCam?", "Igen — cam streaminghez ugyanazt az alapfeladatot látja el (kódolja a kamerádat és RTMP-n elküldi egy platformra) sokkal egyszerűbb beállítással, plusz beépített multistreaming és szépségszűrők, amikhez az OBS-nek pluginek kellenek."),
            ("Ingyenes a SplitCam, mint az OBS?", "Igen. A SplitCam ingyenes, vízjel nélkül és időkorlát nélkül, akárcsak az OBS. Egyik sem kér pénzt az adásért."),
            ("Tud a SplitCam egyszerre több platformra streamelni, mint az OBS pluginnel?", "Igen, és ez beépített — plugin vagy fizetős relay nélkül. Add hozzá minden platform RTMP kulcsát, és menj élőben mindegyiken egy kattintással."),
            ("Ugyanazokon az oldalakon működik a SplitCam, mint az OBS?", "Igen — bármi, ami elfogad egyedi RTMP kulcsot (Chaturbate, Stripchat, BongaCams, CAM4 és mások), működik a SplitCammel, plusz kész presetjei vannak több cam platformhoz."),
        ],
    },
    "el": {
        "title": "SplitCam vs OBS — δωρεάν εναλλακτική του OBS για cam streaming",
        "desc": "Το SplitCam είναι μια δωρεάν, ελαφριά εναλλακτική του OBS για cam streaming: ενσωματωμένη εικονική κάμερα, multistreaming με ένα κλικ, beauty φίλτρα, χωρίς υδατογράφημα. Σύγκριση δίπλα-δίπλα.",
        "h1html": 'SplitCam vs OBS — η δωρεάν <span class="accent">εναλλακτική του OBS</span>',
        "h1short": "SplitCam vs OBS",
        "intro": "Το OBS Studio είναι το βαρύ πυροβολικό του streaming — απείρως παραμετροποιήσιμο και δωρεάν. Αλλά για cam streaming το μεγαλύτερο μέρος αυτής της ισχύος είναι υπερβολικό, και η καμπύλη ρύθμισης απότομη. Το <strong style='color:var(--text)'>SplitCam</strong> είναι μια ελαφρύτερη, δωρεάν εναλλακτική του OBS: ενσωματωμένη εικονική κάμερα, multistreaming με ένα κλικ και beauty φίλτρα εξ ορισμού, με το ίδιο custom RTMP για μετάδοση σε οποιαδήποτε cam πλατφόρμα. Δείτε τη σύγκριση.",
        "table_h": "Σύγκριση δίπλα-δίπλα",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Τιμή", "Δωρεάν, χωρίς υδατογράφημα", "Δωρεάν, ανοιχτού κώδικα"),
            ("Καμπύλη εκμάθησης", "Φιλικό για αρχάριους", "Απότομη"),
            ("Εικονική κάμερα", "Ενσωματωμένη", "Ενσωματωμένη (πρόσφατες εκδόσεις)"),
            ("Multistreaming σε πολλά sites", "Ενσωματωμένο, ένα κλικ", "Χρειάζεται plugin / relay"),
            ("Beauty φίλτρα & AI φόντο", "Ενσωματωμένα", "Όχι εγγενώς"),
            ("Preset cam πλατφορμών", "Ναι (Streamate, VISIT-X…)", "Μόνο χειροκίνητο RTMP"),
            ("Custom RTMP έξοδος", "Ναι", "Ναι"),
            ("Φορτίο συστήματος", "Ελαφρύ", "Βαρύτερο"),
        ],
        "verdict_h": "Ποιο να διαλέξεις;",
        "verdict": "Διάλεξε <strong style='color:var(--text)'>OBS</strong> αν θες πλήρη έλεγχο σε σύνθετες σκηνές και δεν σε πειράζει η ρύθμιση. Διάλεξε <strong style='color:var(--text)'>SplitCam</strong> αν θες να είσαι live σε λεπτά — έχει τα cam βασικά (εικονική κάμερα, multistream, beauty φίλτρα, preset πλατφορμών) ενσωματωμένα, και σου δίνει και custom RTMP για κάθε site.",
        "faq": [
            ("Είναι το SplitCam καλή εναλλακτική του OBS;", "Ναι — για cam streaming καλύπτει την ίδια βασική δουλειά (κωδικοποιεί την κάμερα και τη στέλνει σε πλατφόρμα μέσω RTMP) με πολύ απλούστερη ρύθμιση, συν ενσωματωμένο multistreaming και beauty φίλτρα για τα οποία το OBS χρειάζεται plugins."),
            ("Είναι το SplitCam δωρεάν όπως το OBS;", "Ναι. Το SplitCam είναι δωρεάν, χωρίς υδατογράφημα και χωρίς χρονικό όριο, όπως το OBS. Κανένα δεν χρεώνει για τη μετάδοση."),
            ("Μπορεί το SplitCam να μεταδίδει σε πολλές πλατφόρμες ταυτόχρονα όπως το OBS με plugin;", "Ναι, και είναι ενσωματωμένο — χωρίς plugin ή πληρωμένο relay. Πρόσθεσε το RTMP key κάθε πλατφόρμας και βγες live σε όλες με ένα κλικ."),
            ("Λειτουργεί το SplitCam στα ίδια sites με το OBS;", "Ναι — οτιδήποτε δέχεται custom RTMP key (Chaturbate, Stripchat, BongaCams, CAM4 και άλλα) λειτουργεί με το SplitCam, και έχει έτοιμα preset για διάφορες cam πλατφόρμες."),
        ],
    },
    "fi": {
        "title": "SplitCam vs OBS — ilmainen OBS-vaihtoehto cam-striimaukseen",
        "desc": "SplitCam on ilmainen, kevyt OBS-vaihtoehto cam-striimaukseen: sisäänrakennettu virtuaalikamera, yhden klikkauksen multistreaming, beauty-suodattimet, ei vesileimaa. Vertailu rinnakkain.",
        "h1html": 'SplitCam vs OBS — ilmainen <span class="accent">OBS-vaihtoehto</span>',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio on striimauksen raskas sarja — loputtomasti säädettävä ja ilmainen. Mutta cam-striimaukseen suurin osa tästä tehosta on ylimitoitettu, ja asennuskäyrä on jyrkkä. <strong style='color:var(--text)'>SplitCam</strong> on kevyempi, ilmainen OBS-vaihtoehto: sisäänrakennettu virtuaalikamera, yhden klikkauksen multistreaming ja beauty-suodattimet valmiina, samalla custom RTMP:llä lähettääksesi mille tahansa cam-alustalle. Näin ne vertautuvat.",
        "table_h": "Vertailu rinnakkain",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Hinta", "Ilmainen, ei vesileimaa", "Ilmainen, avoin lähdekoodi"),
            ("Oppimiskäyrä", "Aloittelijaystävällinen", "Jyrkkä"),
            ("Virtuaalikamera", "Sisäänrakennettu", "Sisäänrakennettu (uudet versiot)"),
            ("Multistreaming monelle sivustolle", "Sisäänrakennettu, yksi klikkaus", "Tarvitsee liitännäisen / relayn"),
            ("Beauty-suodattimet ja AI-tausta", "Sisäänrakennettu", "Ei natiivisti"),
            ("Cam-alustojen esiasetukset", "Kyllä (Streamate, VISIT-X…)", "Vain manuaalinen RTMP"),
            ("Mukautettu RTMP-ulostulo", "Kyllä", "Kyllä"),
            ("Järjestelmäkuorma", "Kevyt", "Raskaampi"),
        ],
        "verdict_h": "Kumman valitset?",
        "verdict": "Valitse <strong style='color:var(--text)'>OBS</strong>, jos haluat täyden hallinnan monimutkaisista näkymistä etkä välitä asennuksesta. Valitse <strong style='color:var(--text)'>SplitCam</strong>, jos haluat olla livenä minuuteissa — siinä on cam-perusteet (virtuaalikamera, multistream, beauty-suodattimet, alustojen esiasetukset) sisäänrakennettuna, ja silti se antaa mukautetun RTMP:n mille tahansa sivustolle.",
        "faq": [
            ("Onko SplitCam hyvä OBS-vaihtoehto?", "Kyllä — cam-striimaukseen se kattaa saman ydintehtävän (koodaa kamerasi ja lähettää sen alustalle RTMP:llä) paljon helpommalla asennuksella, plus sisäänrakennettu multistreaming ja beauty-suodattimet, joihin OBS tarvitsee liitännäisiä."),
            ("Onko SplitCam ilmainen kuten OBS?", "Kyllä. SplitCam on ilmainen, ilman vesileimaa ja ilman aikarajaa, aivan kuten OBS. Kumpikaan ei veloita striimauksesta."),
            ("Voiko SplitCam striimata useille alustoille kerralla kuten OBS liitännäisellä?", "Kyllä, ja se on sisäänrakennettu — ei liitännäistä eikä maksullista relayta. Lisää kunkin alustan RTMP-avain ja mene livenä kaikille yhdellä klikkauksella."),
            ("Toimiiko SplitCam samoilla sivustoilla kuin OBS?", "Kyllä — kaikki, mikä hyväksyy mukautetun RTMP-avaimen (Chaturbate, Stripchat, BongaCams, CAM4 ja muut), toimii SplitCamilla, plus siinä on valmiit esiasetukset useille cam-alustoille."),
        ],
    },
    "da": {
        "title": "SplitCam vs OBS — gratis OBS-alternativ til cam-streaming",
        "desc": "SplitCam er et gratis, let OBS-alternativ til cam-streaming: indbygget virtuelt kamera, multistreaming med ét klik, beauty-filtre, intet vandmærke. Sammenligning side om side.",
        "h1html": 'SplitCam vs OBS — det gratis <span class="accent">OBS-alternativ</span>',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio er sværvægteren inden for streaming — uendeligt konfigurerbar og gratis. Men til cam-streaming er det meste af den kraft overkill, og opsætningskurven er stejl. <strong style='color:var(--text)'>SplitCam</strong> er et lettere, gratis OBS-alternativ: indbygget virtuelt kamera, multistreaming med ét klik og beauty-filtre fra start, med samme custom RTMP til at sende til enhver cam-platform. Sådan sammenlignes de.",
        "table_h": "Sammenligning side om side",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Pris", "Gratis, intet vandmærke", "Gratis, open source"),
            ("Læringskurve", "Begyndervenlig", "Stejl"),
            ("Virtuelt kamera", "Indbygget", "Indbygget (nyere versioner)"),
            ("Multistreaming til mange sites", "Indbygget, ét klik", "Kræver plugin / relay"),
            ("Beauty-filtre & AI-baggrund", "Indbygget", "Ikke nativt"),
            ("Cam-platform-presets", "Ja (Streamate, VISIT-X…)", "Kun manuel RTMP"),
            ("Custom RTMP-output", "Ja", "Ja"),
            ("Systembelastning", "Let", "Tungere"),
        ],
        "verdict_h": "Hvilken skal du vælge?",
        "verdict": "Vælg <strong style='color:var(--text)'>OBS</strong>, hvis du vil have total kontrol over komplekse scener og ikke har noget imod opsætningen. Vælg <strong style='color:var(--text)'>SplitCam</strong>, hvis du vil være live på minutter — det har cam-essentials (virtuelt kamera, multistream, beauty-filtre, platform-presets) indbygget og giver dig stadig custom RTMP til ethvert site.",
        "faq": [
            ("Er SplitCam et godt OBS-alternativ?", "Ja — til cam-streaming dækker det samme kerneopgave (kode dit kamera og sende det til en platform via RTMP) med en langt enklere opsætning, plus indbygget multistreaming og beauty-filtre, som OBS kræver plugins til."),
            ("Er SplitCam gratis som OBS?", "Ja. SplitCam er gratis, uden vandmærke og uden tidsbegrænsning, ligesom OBS. Ingen af dem opkræver betaling for at streame."),
            ("Kan SplitCam streame til flere platforme på én gang som OBS med et plugin?", "Ja, og det er indbygget — uden plugin eller betalt relay. Tilføj hver platforms RTMP-nøgle og gå live på dem alle med ét klik."),
            ("Virker SplitCam på de samme sites som OBS?", "Ja — alt der accepterer en custom RTMP-nøgle (Chaturbate, Stripchat, BongaCams, CAM4 og flere) virker med SplitCam, plus det har klar-til-brug presets til flere cam-platforme."),
        ],
    },
    "no": {
        "title": "SplitCam vs OBS — gratis OBS-alternativ for cam-strømming",
        "desc": "SplitCam er et gratis, lett OBS-alternativ for cam-strømming: innebygd virtuelt kamera, multistreaming med ett klikk, beauty-filtre, uten vannmerke. Sammenligning side om side.",
        "h1html": 'SplitCam vs OBS — det gratis <span class="accent">OBS-alternativet</span>',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio er tungvekteren innen strømming — uendelig konfigurerbar og gratis. Men for cam-strømming er det meste av den kraften overkill, og oppsettkurven er bratt. <strong style='color:var(--text)'>SplitCam</strong> er et lettere, gratis OBS-alternativ: innebygd virtuelt kamera, multistreaming med ett klikk og beauty-filtre fra start, med samme custom RTMP for å sende til enhver cam-plattform. Slik sammenlignes de.",
        "table_h": "Sammenligning side om side",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Pris", "Gratis, uten vannmerke", "Gratis, åpen kildekode"),
            ("Læringskurve", "Nybegynnervennlig", "Bratt"),
            ("Virtuelt kamera", "Innebygd", "Innebygd (nyere versjoner)"),
            ("Multistreaming til mange nettsteder", "Innebygd, ett klikk", "Krever plugin / relay"),
            ("Beauty-filtre & AI-bakgrunn", "Innebygd", "Ikke nativt"),
            ("Cam-plattform-presets", "Ja (Streamate, VISIT-X…)", "Kun manuell RTMP"),
            ("Custom RTMP-utgang", "Ja", "Ja"),
            ("Systembelastning", "Lett", "Tyngre"),
        ],
        "verdict_h": "Hvilken bør du velge?",
        "verdict": "Velg <strong style='color:var(--text)'>OBS</strong> hvis du vil ha total kontroll over komplekse scener og ikke har noe imot oppsettet. Velg <strong style='color:var(--text)'>SplitCam</strong> hvis du vil være live på minutter — det har cam-essensene (virtuelt kamera, multistream, beauty-filtre, plattform-presets) innebygd og gir deg likevel custom RTMP for ethvert nettsted.",
        "faq": [
            ("Er SplitCam et godt OBS-alternativ?", "Ja — for cam-strømming dekker det samme kjerneoppgaven (kode kameraet ditt og sende det til en plattform via RTMP) med et mye enklere oppsett, pluss innebygd multistreaming og beauty-filtre som OBS trenger plugins for."),
            ("Er SplitCam gratis som OBS?", "Ja. SplitCam er gratis, uten vannmerke og uten tidsgrense, akkurat som OBS. Ingen av dem tar betalt for å strømme."),
            ("Kan SplitCam strømme til flere plattformer samtidig som OBS med en plugin?", "Ja, og det er innebygd — uten plugin eller betalt relay. Legg til hver plattforms RTMP-nøkkel og gå live på alle med ett klikk."),
            ("Virker SplitCam på de samme nettstedene som OBS?", "Ja — alt som godtar en custom RTMP-nøkkel (Chaturbate, Stripchat, BongaCams, CAM4 og flere) virker med SplitCam, pluss det har ferdige presets for flere cam-plattformer."),
        ],
    },
    "sr": {
        "title": "SplitCam vs OBS — бесплатна алтернатива OBS-у за кам стриминг",
        "desc": "SplitCam је бесплатна, лака алтернатива OBS-у за кам стриминг: уграђена виртуелна камера, мултистриминг једним кликом, бјути филтери, без воденог жига. Поређење упоредо.",
        "h1html": 'SplitCam vs OBS — бесплатна <span class="accent">алтернатива OBS-у</span>',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio је тешка артиљерија стриминга — бескрајно подесив и бесплатан. Али за кам стриминг већина те моћи је претерана, а крива подешавања стрма. <strong style='color:var(--text)'>SplitCam</strong> је лакша, бесплатна алтернатива OBS-у: уграђена виртуелна камера, мултистриминг једним кликом и бјути филтери из кутије, са истим прилагођеним RTMP-ом за пренос на било коју кам платформу. Ево како се пореде.",
        "table_h": "Поређење упоредо",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Цена", "Бесплатно, без воденог жига", "Бесплатно, отворен код"),
            ("Крива учења", "Лако за почетнике", "Стрма"),
            ("Виртуелна камера", "Уграђена", "Уграђена (новије верзије)"),
            ("Мултистриминг на много сајтова", "Уграђен, један клик", "Треба плагин / релеј"),
            ("Бјути филтери и AI позадина", "Уграђени", "Не нативно"),
            ("Пресети кам платформи", "Да (Streamate, VISIT-X…)", "Само ручни RTMP"),
            ("Прилагођени RTMP излаз", "Да", "Да"),
            ("Оптерећење система", "Лако", "Теже"),
        ],
        "verdict_h": "Шта изабрати?",
        "verdict": "Изабери <strong style='color:var(--text)'>OBS</strong> ако желиш потпуну контролу над сложеним сценама и не смета ти подешавање. Изабери <strong style='color:var(--text)'>SplitCam</strong> ако желиш да будеш уживо за неколико минута — има уграђене кам основе (виртуелна камера, мултистрим, бјути филтери, пресети платформи) и опет ти даје прилагођени RTMP за било који сајт.",
        "faq": [
            ("Да ли је SplitCam добра алтернатива OBS-у?", "Да — за кам стриминг покрива исти основни посао (кодира камеру и шаље је платформи преко RTMP-а) са много једноставнијим подешавањем, плус уграђени мултистриминг и бјути филтери за које OBS-у требају плагини."),
            ("Да ли је SplitCam бесплатан као OBS?", "Да. SplitCam је бесплатан, без воденог жига и без временског ограничења, баш као OBS. Ниједан не наплаћује пренос."),
            ("Може ли SplitCam да преноси на више платформи одједном као OBS са плагином?", "Да, и уграђено је — без плагина или плаћеног релеја. Додај RTMP кључ сваке платформе и иди уживо на све једним кликом."),
            ("Да ли SplitCam ради на истим сајтовима као OBS?", "Да — све што прихвата прилагођени RTMP кључ (Chaturbate, Stripchat, BongaCams, CAM4 и др.) ради са SplitCam-ом, плус има готове пресете за неколико кам платформи."),
        ],
    },
    "hr": {
        "title": "SplitCam vs OBS — besplatna alternativa OBS-u za cam streaming",
        "desc": "SplitCam je besplatna, lagana alternativa OBS-u za cam streaming: ugrađena virtualna kamera, multistreaming jednim klikom, beauty filtri, bez vodenog žiga. Usporedba jedno uz drugo.",
        "h1html": 'SplitCam vs OBS — besplatna <span class="accent">alternativa OBS-u</span>',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio je teška artiljerija streaminga — beskrajno podesiv i besplatan. Ali za cam streaming većina te snage je pretjerana, a krivulja postavljanja strma. <strong style='color:var(--text)'>SplitCam</strong> je lakša, besplatna alternativa OBS-u: ugrađena virtualna kamera, multistreaming jednim klikom i beauty filtri od početka, s istim prilagođenim RTMP-om za prijenos na bilo koju cam platformu. Evo kako se uspoređuju.",
        "table_h": "Usporedba jedno uz drugo",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Cijena", "Besplatno, bez vodenog žiga", "Besplatno, otvoreni kod"),
            ("Krivulja učenja", "Lako za početnike", "Strma"),
            ("Virtualna kamera", "Ugrađena", "Ugrađena (novije verzije)"),
            ("Multistreaming na više stranica", "Ugrađen, jedan klik", "Treba plugin / relay"),
            ("Beauty filtri i AI pozadina", "Ugrađeni", "Ne nativno"),
            ("Presetovi cam platformi", "Da (Streamate, VISIT-X…)", "Samo ručni RTMP"),
            ("Prilagođeni RTMP izlaz", "Da", "Da"),
            ("Opterećenje sustava", "Lagano", "Teže"),
        ],
        "verdict_h": "Što odabrati?",
        "verdict": "Odaberi <strong style='color:var(--text)'>OBS</strong> ako želiš potpunu kontrolu nad složenim scenama i ne smeta ti postavljanje. Odaberi <strong style='color:var(--text)'>SplitCam</strong> ako želiš biti uživo za nekoliko minuta — ima ugrađene cam osnove (virtualna kamera, multistream, beauty filtri, presetovi platformi) i svejedno ti daje prilagođeni RTMP za bilo koju stranicu.",
        "faq": [
            ("Je li SplitCam dobra alternativa OBS-u?", "Da — za cam streaming pokriva isti osnovni posao (kodira kameru i šalje je platformi preko RTMP-a) s puno jednostavnijim postavljanjem, plus ugrađeni multistreaming i beauty filtri za koje OBS treba plugine."),
            ("Je li SplitCam besplatan kao OBS?", "Da. SplitCam je besplatan, bez vodenog žiga i bez vremenskog ograničenja, baš kao OBS. Nijedan ne naplaćuje prijenos."),
            ("Može li SplitCam prenositi na više platformi odjednom kao OBS s pluginom?", "Da, i ugrađeno je — bez plugina ili plaćenog relaya. Dodaj RTMP ključ svake platforme i idi uživo na sve jednim klikom."),
            ("Radi li SplitCam na istim stranicama kao OBS?", "Da — sve što prihvaća prilagođeni RTMP ključ (Chaturbate, Stripchat, BongaCams, CAM4 i više) radi sa SplitCamom, plus ima gotove presetove za nekoliko cam platformi."),
        ],
    },
    "zh": {
        "title": "SplitCam vs OBS — 免费的 OBS 替代品，用于 cam 直播",
        "desc": "SplitCam 是免费、轻量的 OBS 替代品，用于 cam 直播：内置虚拟摄像头、一键多平台直播、美颜滤镜、无水印。逐项对比。",
        "h1html": 'SplitCam vs OBS — 免费的 <span class="accent">OBS 替代品</span>',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio 是直播领域的重量级工具——可无限配置且免费。但对于 cam 直播，其大部分功能都过于强大，而且设置门槛很陡。<strong style='color:var(--text)'>SplitCam</strong> 是更轻量、免费的 OBS 替代品：内置虚拟摄像头、一键多平台直播和开箱即用的美颜滤镜，并提供相同的自定义 RTMP，可向任何 cam 平台直播。以下是两者的对比。",
        "table_h": "逐项对比",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("价格", "免费，无水印", "免费，开源"),
            ("学习曲线", "新手友好", "陡峭"),
            ("虚拟摄像头", "内置", "内置（较新版本）"),
            ("多平台同时直播", "内置，一键", "需要插件 / 中继"),
            ("美颜滤镜和 AI 背景", "内置", "非原生"),
            ("Cam 平台预设", "有（Streamate、VISIT-X…）", "仅手动 RTMP"),
            ("自定义 RTMP 输出", "有", "有"),
            ("系统占用", "轻", "较重"),
        ],
        "verdict_h": "该选哪个？",
        "verdict": "如果你想完全控制复杂场景且不介意配置，选 <strong style='color:var(--text)'>OBS</strong>。如果你想在几分钟内开播，选 <strong style='color:var(--text)'>SplitCam</strong>——它内置了 cam 直播必备功能（虚拟摄像头、多平台直播、美颜滤镜、平台预设），同时仍提供适用于任何网站的自定义 RTMP。",
        "faq": [
            ("SplitCam 是好的 OBS 替代品吗？", "是——对于 cam 直播，它完成相同的核心工作（编码您的摄像头并通过 RTMP 发送到平台），但配置简单得多，还内置了 OBS 需要插件才能实现的多平台直播和美颜滤镜。"),
            ("SplitCam 像 OBS 一样免费吗？", "是。SplitCam 免费、无水印、无时间限制，与 OBS 一样。两者都不收取直播费用。"),
            ("SplitCam 能像装了插件的 OBS 一样同时向多个平台直播吗？", "能，而且是内置的——无需插件或付费中继。添加每个平台的 RTMP 密钥，一键向所有平台开播。"),
            ("SplitCam 能在与 OBS 相同的网站上使用吗？", "能——任何接受自定义 RTMP 密钥的网站（Chaturbate、Stripchat、BongaCams、CAM4 等）都能配合 SplitCam，而且它为多个 cam 平台提供了现成预设。"),
        ],
    },
    "ja": {
        "title": "SplitCam vs OBS — cam配信向けの無料OBS代替",
        "desc": "SplitCamはcam配信向けの無料・軽量なOBS代替：内蔵バーチャルカメラ、ワンクリックのマルチ配信、ビューティーフィルター、透かしなし。項目別比較。",
        "h1html": 'SplitCam vs OBS — 無料の<span class="accent">OBS代替</span>',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studioは配信のヘビー級 — 無限に設定可能で無料です。しかしcam配信ではそのパワーの大半は過剰で、設定の学習曲線も急です。<strong style='color:var(--text)'>SplitCam</strong>はより軽量で無料のOBS代替：内蔵バーチャルカメラ、ワンクリックのマルチ配信、最初から使えるビューティーフィルター、そして任意のcamプラットフォームに配信できる同じカスタムRTMP。両者を比較します。",
        "table_h": "項目別比較",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("価格", "無料、透かしなし", "無料、オープンソース"),
            ("学習曲線", "初心者向け", "急"),
            ("バーチャルカメラ", "内蔵", "内蔵（新しいバージョン）"),
            ("複数サイトへのマルチ配信", "内蔵、ワンクリック", "プラグイン / リレーが必要"),
            ("ビューティーフィルターとAI背景", "内蔵", "ネイティブ非対応"),
            ("camプラットフォームのプリセット", "あり（Streamate、VISIT-X…）", "手動RTMPのみ"),
            ("カスタムRTMP出力", "あり", "あり"),
            ("システム負荷", "軽い", "重い"),
        ],
        "verdict_h": "どちらを選ぶ?",
        "verdict": "複雑なシーンを完全に制御したく、設定を気にしないなら<strong style='color:var(--text)'>OBS</strong>を選びましょう。数分でライブに行きたいなら<strong style='color:var(--text)'>SplitCam</strong> — cam配信の必須機能（バーチャルカメラ、マルチ配信、ビューティーフィルター、プラットフォームプリセット）が内蔵され、それでも任意のサイト向けのカスタムRTMPが使えます。",
        "faq": [
            ("SplitCamは良いOBS代替ですか?", "はい — cam配信では同じ中核作業（カメラをエンコードしRTMP経由でプラットフォームに送る）をはるかに簡単な設定でこなし、さらにOBSではプラグインが必要なマルチ配信とビューティーフィルターが内蔵されています。"),
            ("SplitCamはOBSのように無料ですか?", "はい。SplitCamは無料で、透かしなし、時間制限なし、OBSと同じです。どちらも配信に課金しません。"),
            ("SplitCamはプラグイン付きOBSのように複数プラットフォームに同時配信できますか?", "はい、しかも内蔵 — プラグインや有料リレー不要。各プラットフォームのRTMPキーを追加し、ワンクリックで全てにライブできます。"),
            ("SplitCamはOBSと同じサイトで動作しますか?", "はい — カスタムRTMPキーを受け付けるもの（Chaturbate、Stripchat、BongaCams、CAM4など）はSplitCamで動作し、さらに複数のcamプラットフォーム向けの既製プリセットがあります。"),
        ],
    },
    "ar": {
        "title": "SplitCam مقابل OBS — بديل OBS مجاني لبث cam",
        "desc": "SplitCam بديل OBS مجاني وخفيف لبث cam: كاميرا افتراضية مدمجة، بث متعدد بنقرة واحدة، فلاتر تجميل، بدون علامة مائية. مقارنة جنباً إلى جنب.",
        "h1html": 'SplitCam مقابل OBS — <span class="accent">بديل OBS</span> المجاني',
        "h1short": "SplitCam مقابل OBS",
        "intro": "OBS Studio هو ثقيل الوزن في البث — قابل للتهيئة بلا حدود ومجاني. لكن لبث cam، معظم تلك القوة مبالغ فيها، ومنحنى الإعداد حاد. <strong style='color:var(--text)'>SplitCam</strong> بديل OBS أخف وزناً ومجاني: كاميرا افتراضية مدمجة، بث متعدد بنقرة واحدة وفلاتر تجميل جاهزة، مع نفس RTMP المخصص للبث على أي منصة cam. إليك المقارنة.",
        "table_h": "مقارنة جنباً إلى جنب",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("السعر", "مجاني، بدون علامة مائية", "مجاني، مفتوح المصدر"),
            ("منحنى التعلم", "سهل للمبتدئين", "حاد"),
            ("كاميرا افتراضية", "مدمجة", "مدمجة (إصدارات حديثة)"),
            ("بث متعدد لمواقع كثيرة", "مدمج، نقرة واحدة", "يحتاج إضافة / مُرحِّل"),
            ("فلاتر تجميل وخلفية AI", "مدمجة", "ليست أصلية"),
            ("إعدادات مسبقة لمنصات cam", "نعم (Streamate، VISIT-X…)", "RTMP يدوي فقط"),
            ("مخرج RTMP مخصص", "نعم", "نعم"),
            ("حِمل النظام", "خفيف", "أثقل"),
        ],
        "verdict_h": "أيهما تختار؟",
        "verdict": "اختر <strong style='color:var(--text)'>OBS</strong> إذا أردت تحكماً كاملاً في المشاهد المعقدة ولا يزعجك الإعداد. اختر <strong style='color:var(--text)'>SplitCam</strong> إذا أردت أن تكون مباشراً في دقائق — فهو يحتوي على أساسيات cam (كاميرا افتراضية، بث متعدد، فلاتر تجميل، إعدادات مسبقة للمنصات) مدمجة، ويمنحك مع ذلك RTMP مخصصاً لأي موقع.",
        "faq": [
            ("هل SplitCam بديل جيد لـ OBS؟", "نعم — لبث cam يغطي نفس المهمة الأساسية (تشفير كاميرتك وإرسالها إلى منصة عبر RTMP) بإعداد أبسط بكثير، بالإضافة إلى بث متعدد وفلاتر تجميل مدمجة يحتاج OBS لها إضافات."),
            ("هل SplitCam مجاني مثل OBS؟", "نعم. SplitCam مجاني، بدون علامة مائية وبدون حد زمني، تماماً مثل OBS. لا يفرض أي منهما رسوماً للبث."),
            ("هل يمكن لـ SplitCam البث على منصات متعددة في وقت واحد مثل OBS مع إضافة؟", "نعم، وهو مدمج — بدون إضافة أو مُرحِّل مدفوع. أضف مفتاح RTMP لكل منصة وابدأ البث المباشر عليها جميعاً بنقرة واحدة."),
            ("هل يعمل SplitCam على نفس المواقع مثل OBS؟", "نعم — أي شيء يقبل مفتاح RTMP مخصص (Chaturbate، Stripchat، BongaCams، CAM4 وغيرها) يعمل مع SplitCam، بالإضافة إلى أن لديه إعدادات مسبقة جاهزة لعدة منصات cam."),
        ],
    },
    "th": {
        "title": "SplitCam vs OBS — ทางเลือกแทน OBS ฟรีสำหรับ cam streaming",
        "desc": "SplitCam คือทางเลือกแทน OBS ที่ฟรีและเบาสำหรับ cam streaming: กล้องเสมือนในตัว มัลติสตรีมคลิกเดียว ฟิลเตอร์ความงาม ไม่มีลายน้ำ เปรียบเทียบเคียงข้างกัน",
        "h1html": 'SplitCam vs OBS — <span class="accent">ทางเลือกแทน OBS</span> ฟรี',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio คือเครื่องมือรุ่นหนักของการสตรีม — ปรับแต่งได้ไม่จำกัดและฟรี แต่สำหรับ cam streaming พลังส่วนใหญ่นั้นเกินจำเป็น และเส้นโค้งการตั้งค่าก็ชัน <strong style='color:var(--text)'>SplitCam</strong> คือทางเลือกแทน OBS ที่เบากว่าและฟรี: กล้องเสมือนในตัว มัลติสตรีมคลิกเดียว และฟิลเตอร์ความงามพร้อมใช้ พร้อม RTMP กำหนดเองเดียวกันเพื่อถ่ายทอดไปยังแพลตฟอร์ม cam ใดก็ได้ นี่คือการเปรียบเทียบ",
        "table_h": "เปรียบเทียบเคียงข้างกัน",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("ราคา", "ฟรี ไม่มีลายน้ำ", "ฟรี โอเพนซอร์ส"),
            ("เส้นโค้งการเรียนรู้", "เป็นมิตรกับมือใหม่", "ชัน"),
            ("กล้องเสมือน", "ในตัว", "ในตัว (เวอร์ชันใหม่)"),
            ("มัลติสตรีมไปหลายไซต์", "ในตัว คลิกเดียว", "ต้องใช้ปลั๊กอิน / รีเลย์"),
            ("ฟิลเตอร์ความงามและพื้นหลัง AI", "ในตัว", "ไม่เนทีฟ"),
            ("พรีเซ็ตแพลตฟอร์ม cam", "มี (Streamate, VISIT-X…)", "RTMP แบบแมนนวลเท่านั้น"),
            ("เอาต์พุต RTMP กำหนดเอง", "มี", "มี"),
            ("ภาระระบบ", "เบา", "หนักกว่า"),
        ],
        "verdict_h": "ควรเลือกอันไหน?",
        "verdict": "เลือก <strong style='color:var(--text)'>OBS</strong> หากต้องการควบคุมฉากซับซ้อนเต็มที่และไม่รังเกียจการตั้งค่า เลือก <strong style='color:var(--text)'>SplitCam</strong> หากต้องการไลฟ์ภายในไม่กี่นาที — มีสิ่งจำเป็นสำหรับ cam (กล้องเสมือน มัลติสตรีม ฟิลเตอร์ความงาม พรีเซ็ตแพลตฟอร์ม) ในตัว และยังให้ RTMP กำหนดเองสำหรับทุกไซต์",
        "faq": [
            ("SplitCam เป็นทางเลือกแทน OBS ที่ดีไหม?", "ใช่ — สำหรับ cam streaming มันครอบคลุมงานหลักเดียวกัน (เข้ารหัสกล้องและส่งไปยังแพลตฟอร์มผ่าน RTMP) ด้วยการตั้งค่าที่ง่ายกว่ามาก พร้อมมัลติสตรีมและฟิลเตอร์ความงามในตัวที่ OBS ต้องใช้ปลั๊กอิน"),
            ("SplitCam ฟรีเหมือน OBS ไหม?", "ใช่ SplitCam ฟรี ไม่มีลายน้ำ และไม่จำกัดเวลา เหมือน OBS ทั้งคู่ไม่คิดค่าสตรีม"),
            ("SplitCam สตรีมไปหลายแพลตฟอร์มพร้อมกันได้เหมือน OBS ที่มีปลั๊กอินไหม?", "ได้ และเป็นในตัว — ไม่ต้องใช้ปลั๊กอินหรือรีเลย์แบบเสียเงิน เพิ่มคีย์ RTMP ของแต่ละแพลตฟอร์มแล้วไลฟ์ทั้งหมดด้วยคลิกเดียว"),
            ("SplitCam ใช้งานบนไซต์เดียวกับ OBS ได้ไหม?", "ได้ — ทุกอย่างที่รับคีย์ RTMP กำหนดเอง (Chaturbate, Stripchat, BongaCams, CAM4 และอื่นๆ) ใช้งานได้กับ SplitCam และยังมีพรีเซ็ตพร้อมใช้สำหรับหลายแพลตฟอร์ม cam"),
        ],
    },
    "sv": {
        "title": "SplitCam vs OBS — gratis OBS-alternativ för cam-streaming",
        "desc": "SplitCam är ett gratis, lättviktigt OBS-alternativ för cam-streaming — inbyggd virtuell kamera, multistream med ett klick, skönhetsfilter, ingen vattenstämpel. Jämförelse sida vid sida.",
        "h1html": 'SplitCam vs OBS — gratis <span class="accent">OBS-alternativ</span>',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio är livesändningens slägga — oändligt konfigurerbar och gratis. Men för cam-streaming är det mesta av den kraften överflödig och inställningskurvan brant. <strong style='color:var(--text)'>SplitCam</strong> är ett lättare, gratis OBS-alternativ: inbyggd virtuell kamera, multistream med ett klick och skönhetsfilter direkt ur lådan, med samma anpassade RTMP som låter dig sända till vilken cam-plattform som helst. Här är en jämförelse av de två.",
        "table_h": "Jämförelse sida vid sida",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Pris", "Gratis, ingen vattenstämpel", "Gratis, öppen källkod"),
            ("Inlärningskurva", "Nybörjarvänlig", "Brant"),
            ("Virtuell kamera", "Inbyggd", "Inbyggd (nyare versioner)"),
            ("Multistream till flera sajter", "Inbyggd, ett klick", "Kräver plugin / relay"),
            ("Skönhetsfilter & AI-bakgrund", "Inbyggda", "Inte inbyggt"),
            ("Cam-plattformspresets", "Ja (Streamate, VISIT-X…)", "Endast manuell RTMP"),
            ("Anpassad RTMP-utgång", "Ja", "Ja"),
            ("Systembelastning", "Lätt", "Tyngre"),
        ],
        "verdict_h": "Vad ska du välja?",
        "verdict": "Välj <strong style='color:var(--text)'>OBS</strong> om du vill ha full kontroll över komplexa scener och inte har något emot inställningen. Välj <strong style='color:var(--text)'>SplitCam</strong> om du vill vara live på några minuter — det har cam-grunderna inbyggda (virtuell kamera, multistream, skönhetsfilter, plattformspresets) och ger ändå anpassad RTMP för varje sajt.",
        "faq": [
            ("Är SplitCam ett bra OBS-alternativ?", "Ja — för cam-streaming gör det samma kärnjobb (kodar din kamera och skickar den via RTMP till plattformen) med mycket enklare inställning, plus inbyggd multistream och skönhetsfilter som OBS kräver plugins för."),
            ("Är SplitCam gratis som OBS?", "Ja. SplitCam är gratis, ingen vattenstämpel och ingen tidsgräns, precis som OBS. Ingen av dem tar betalt för sändning."),
            ("Kan SplitCam sända till flera plattformar samtidigt som OBS med en plugin?", "Ja, och det är inbyggt — inga plugins eller betald relay. Lägg till varje plattforms RTMP-nyckel och gå live på alla med ett klick."),
            ("Fungerar SplitCam med samma sajter som OBS?", "Ja — allt som tar emot en anpassad RTMP-streamnyckel (Chaturbate, Stripchat, BongaCams, CAM4 och fler) fungerar med SplitCam, plus att det har färdiga presets för många cam-plattformar."),
        ],
    },
    "sk": {
        "title": "SplitCam vs OBS — bezplatná alternatíva k OBS pre cam streaming",
        "desc": "SplitCam je bezplatná, ľahká alternatíva k OBS pre cam streaming — vstavaná virtuálna kamera, multistream jedným kliknutím, beauty filtre, bez vodoznaku. Porovnanie vedľa seba.",
        "h1html": 'SplitCam vs OBS — bezplatná <span class="accent">alternatíva k OBS</span>',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio je zbíjačka živého vysielania — nekonečne konfigurovateľná a zadarmo. Ale pre cam streaming je väčšina tej sily zbytočná a krivka nastavenia strmá. <strong style='color:var(--text)'>SplitCam</strong> je ľahšia, bezplatná alternatíva k OBS: vstavaná virtuálna kamera, multistream jedným kliknutím a beauty filtre rovno z krabice, s rovnakým vlastným RTMP, ktorý umožňuje vysielať na akúkoľvek cam platformu. Tu je porovnanie oboch.",
        "table_h": "Porovnanie vedľa seba",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Cena", "Zadarmo, bez vodoznaku", "Zadarmo, open source"),
            ("Krivka učenia", "Ústretový k začiatočníkom", "Strmá"),
            ("Virtuálna kamera", "Vstavaná", "Vstavaná (novšie verzie)"),
            ("Multistream na viac stránok", "Vstavaný, jedno kliknutie", "Vyžaduje plugin / relay"),
            ("Beauty filtre a AI pozadie", "Vstavané", "Natívne nie"),
            ("Presety cam platforiem", "Áno (Streamate, VISIT-X…)", "Len ručný RTMP"),
            ("Vlastný výstup RTMP", "Áno", "Áno"),
            ("Záťaž systému", "Ľahká", "Vyššia"),
        ],
        "verdict_h": "Čo si vybrať?",
        "verdict": "Vyberte <strong style='color:var(--text)'>OBS</strong>, ak chcete plnú kontrolu nad zložitými scénami a nevadí vám nastavenie. Vyberte <strong style='color:var(--text)'>SplitCam</strong>, ak chcete ísť naživo za pár minút — má vstavané základy cam (virtuálnu kameru, multistream, beauty filtre, presety platforiem) a aj tak dáva vlastný RTMP pre každú stránku.",
        "faq": [
            ("Je SplitCam dobrá alternatíva k OBS?", "Áno — pre cam streaming robí rovnakú základnú prácu (kóduje vašu kameru a posiela ju cez RTMP na platformu) s oveľa jednoduchším nastavením, plus má vstavaný multistream a beauty filtre, na ktoré OBS potrebuje pluginy."),
            ("Je SplitCam zadarmo ako OBS?", "Áno. SplitCam je zadarmo, bez vodoznaku a bez časového limitu, presne ako OBS. Ani jeden si neúčtuje za vysielanie."),
            ("Vie SplitCam vysielať na viac platforiem naraz ako OBS s pluginom?", "Áno, a je to vstavané — bez pluginov či plateného relay. Pridajte RTMP kľúč každej platformy a choďte naživo na všetky jedným kliknutím."),
            ("Funguje SplitCam s rovnakými stránkami ako OBS?", "Áno — čokoľvek, čo prijíma vlastný stream key RTMP (Chaturbate, Stripchat, BongaCams, CAM4 a ďalšie), funguje so SplitCam, plus má hotové presety pre mnoho cam platforiem."),
        ],
    },
    "cs": {
        "title": "SplitCam vs OBS — bezplatná alternativa k OBS pro cam streaming",
        "desc": "SplitCam je bezplatná, lehká alternativa k OBS pro cam streaming — vestavěná virtuální kamera, multistream jedním kliknutím, beauty filtry, bez vodoznaku. Srovnání vedle sebe.",
        "h1html": 'SplitCam vs OBS — bezplatná <span class="accent">alternativa k OBS</span>',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio je sbíječka živého vysílání — nekonečně konfigurovatelná a zdarma. Ale pro cam streaming je většina té síly zbytečná a křivka nastavení strmá. <strong style='color:var(--text)'>SplitCam</strong> je lehčí, bezplatná alternativa k OBS: vestavěná virtuální kamera, multistream jedním kliknutím a beauty filtry rovnou z krabice, se stejným vlastním RTMP, který umožňuje vysílat na jakoukoli cam platformu. Tady je srovnání obou.",
        "table_h": "Srovnání vedle sebe",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Cena", "Zdarma, bez vodoznaku", "Zdarma, open source"),
            ("Křivka učení", "Vstřícný k začátečníkům", "Strmá"),
            ("Virtuální kamera", "Vestavěná", "Vestavěná (novější verze)"),
            ("Multistream na více stránek", "Vestavěný, jedno kliknutí", "Vyžaduje plugin / relay"),
            ("Beauty filtry a AI pozadí", "Vestavěné", "Nativně ne"),
            ("Presety cam platforem", "Ano (Streamate, VISIT-X…)", "Jen ruční RTMP"),
            ("Vlastní výstup RTMP", "Ano", "Ano"),
            ("Zátěž systému", "Lehká", "Vyšší"),
        ],
        "verdict_h": "Co si vybrat?",
        "verdict": "Vyberte <strong style='color:var(--text)'>OBS</strong>, pokud chcete plnou kontrolu nad složitými scénami a nevadí vám nastavení. Vyberte <strong style='color:var(--text)'>SplitCam</strong>, pokud chcete jít živě za pár minut — má vestavěné základy cam (virtuální kameru, multistream, beauty filtry, presety platforem) a přesto dává vlastní RTMP pro každou stránku.",
        "faq": [
            ("Je SplitCam dobrá alternativa k OBS?", "Ano — pro cam streaming dělá stejnou základní práci (kóduje vaši kameru a posílá ji přes RTMP na platformu) s mnohem snazším nastavením, plus má vestavěný multistream a beauty filtry, na které OBS potřebuje pluginy."),
            ("Je SplitCam zdarma jako OBS?", "Ano. SplitCam je zdarma, bez vodoznaku a bez časového limitu, přesně jako OBS. Ani jeden si neúčtuje za vysílání."),
            ("Umí SplitCam vysílat na více platforem najednou jako OBS s pluginem?", "Ano, a je to vestavěné — bez pluginů či placeného relay. Přidejte RTMP klíč každé platformy a jděte živě na všechny jedním kliknutím."),
            ("Funguje SplitCam se stejnými stránkami jako OBS?", "Ano — cokoli, co přijímá vlastní stream key RTMP (Chaturbate, Stripchat, BongaCams, CAM4 a další), funguje se SplitCam, plus má hotové presety pro mnoho cam platforem."),
        ],
    },
    "uk": {
        "title": "SplitCam проти OBS — безкоштовна альтернатива OBS для кам-стримінгу",
        "desc": "SplitCam — безкоштовна, легка альтернатива OBS для кам-стримінгу — вбудована віртуальна камера, мультистрим одним кліком, beauty-фільтри, без водяного знака. Порівняння поруч.",
        "h1html": 'SplitCam проти OBS — безкоштовна <span class="accent">альтернатива OBS</span>',
        "h1short": "SplitCam проти OBS",
        "intro": "OBS Studio — відбійний молоток стримінгу наживо: нескінченно налаштовуваний і безкоштовний. Але для кам-стримінгу більшість цієї потужності зайва, а крива налаштування крута. <strong style='color:var(--text)'>SplitCam</strong> — легша безкоштовна альтернатива OBS: вбудована віртуальна камера, мультистрим одним кліком і beauty-фільтри з коробки, з тим самим кастомним RTMP, що дає транслювати на будь-яку кам-платформу. Ось порівняння обох.",
        "table_h": "Порівняння поруч",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Ціна", "Безкоштовний, без водяного знака", "Безкоштовний, відкритий код"),
            ("Крива навчання", "Дружній до новачків", "Крута"),
            ("Віртуальна камера", "Вбудована", "Вбудована (нові версії)"),
            ("Мультистрим на багато сайтів", "Вбудований, один клік", "Потрібен плагін / relay"),
            ("Beauty-фільтри й AI-фон", "Вбудовані", "Немає нативно"),
            ("Пресети кам-платформ", "Є (Streamate, VISIT-X…)", "Лише ручний RTMP"),
            ("Кастомний вивід RTMP", "Є", "Є"),
            ("Навантаження на систему", "Легке", "Важче"),
        ],
        "verdict_h": "Що вибрати?",
        "verdict": "Виберіть <strong style='color:var(--text)'>OBS</strong>, якщо хочете повного контролю над складними сценами й вас не лякає налаштування. Виберіть <strong style='color:var(--text)'>SplitCam</strong>, якщо хочете вийти наживо за кілька хвилин — він має вбудовані основи cam (віртуальну камеру, мультистрим, beauty-фільтри, пресети платформ) і все одно дає кастомний RTMP для кожного сайту.",
        "faq": [
            ("Чи хороша SplitCam альтернатива OBS?", "Так — для кам-стримінгу він робить ту саму базову роботу (кодує вашу камеру й надсилає через RTMP на платформу) зі значно простішим налаштуванням, плюс має вбудований мультистрим і beauty-фільтри, для яких OBS потребує плагінів."),
            ("Чи безкоштовний SplitCam, як OBS?", "Так. SplitCam безкоштовний, без водяного знака й без обмеження часу, точно як OBS. Жоден з них не бере плати за трансляцію."),
            ("Чи може SplitCam транслювати на кілька платформ одночасно, як OBS із плагіном?", "Так, і це вбудовано — без плагінів чи платного relay. Додайте ключ RTMP кожної платформи й вийдіть наживо на всіх одним кліком."),
            ("Чи працює SplitCam із тими ж сайтами, що й OBS?", "Так — усе, що приймає кастомний ключ трансляції RTMP (Chaturbate, Stripchat, BongaCams, CAM4 та інші), працює зі SplitCam, плюс він має готові пресети для багатьох кам-платформ."),
        ],
    },
    "ko": {
        "title": "SplitCam vs OBS — 캠 스트리밍을 위한 무료 OBS 대안",
        "desc": "SplitCam은 캠 스트리밍을 위한 무료·가벼운 OBS 대안입니다 — 내장 가상 카메라, 원클릭 멀티스트림, 뷰티 필터, 워터마크 없음. 나란히 비교.",
        "h1html": 'SplitCam vs OBS — 무료 <span class="accent">OBS 대안</span>',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio는 라이브 스트리밍의 큰 망치입니다 — 무한히 설정 가능하고 무료입니다. 하지만 캠 스트리밍에는 그 힘의 대부분이 과합니다 — 설정 곡선이 가파릅니다. <strong style='color:var(--text)'>SplitCam</strong>은 더 가벼운 무료 OBS 대안입니다: 내장 가상 카메라, 원클릭 멀티스트림, 바로 쓰는 뷰티 필터에 어떤 캠 플랫폼에든 방송할 수 있는 같은 커스텀 RTMP를 더합니다. 둘을 비교해 봅니다.",
        "table_h": "나란히 비교",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("가격", "무료, 워터마크 없음", "무료, 오픈소스"),
            ("학습 곡선", "초보자 친화적", "가파름"),
            ("가상 카메라", "내장", "내장(최신 버전)"),
            ("여러 사이트 멀티스트림", "내장, 원클릭", "플러그인 / 릴레이 필요"),
            ("뷰티 필터 & AI 배경", "내장", "기본 미지원"),
            ("캠 플랫폼 프리셋", "있음 (Streamate, VISIT-X…)", "수동 RTMP만"),
            ("커스텀 RTMP 출력", "있음", "있음"),
            ("시스템 부하", "가벼움", "더 무거움"),
        ],
        "verdict_h": "무엇을 골라야 할까?",
        "verdict": "복잡한 장면을 완전히 제어하고 싶고 설정이 번거롭지 않다면 <strong style='color:var(--text)'>OBS</strong>를 고르세요. 몇 분 안에 라이브하고 싶다면 <strong style='color:var(--text)'>SplitCam</strong>을 고르세요 — 캠 기본기(가상 카메라, 멀티스트림, 뷰티 필터, 플랫폼 프리셋)를 내장으로 제공하면서도 각 사이트용 커스텀 RTMP를 줍니다.",
        "faq": [
            ("SplitCam은 좋은 OBS 대안인가요?", "네 — 캠 스트리밍에서 같은 핵심 작업(카메라를 인코딩해 RTMP로 플랫폼에 전송)을 훨씬 쉬운 설정으로 하며 OBS는 플러그인이 필요한 멀티스트림과 뷰티 필터가 내장돼 있습니다."),
            ("SplitCam은 OBS처럼 무료인가요?", "네. SplitCam은 OBS와 똑같이 무료, 워터마크 없음, 시간 제한 없음입니다. 둘 다 방송에 요금을 받지 않습니다."),
            ("SplitCam도 플러그인 쓴 OBS처럼 여러 플랫폼에 동시 방송할 수 있나요?", "네, 그것도 내장으로 — 플러그인이나 유료 릴레이 없이. 각 플랫폼의 RTMP 키를 추가하고 한 번 클릭으로 모두 라이브하세요."),
            ("SplitCam은 OBS와 같은 사이트에서 작동하나요?", "네 — 커스텀 RTMP 스트림 키를 받는 모든 것(Chaturbate, Stripchat, BongaCams, CAM4 등)이 SplitCam과 작동하며, 많은 캠 플랫폼용 즉시 사용 프리셋도 있습니다."),
        ],
    },
    "pl": {
        "title": "SplitCam vs OBS — darmowa alternatywa dla OBS do cam streamingu",
        "desc": "SplitCam to darmowa, lekka alternatywa dla OBS do cam streamingu — wbudowana kamera wirtualna, multistream jednym kliknięciem, filtry upiększające, bez znaku wodnego. Porównanie obok siebie.",
        "h1html": 'SplitCam vs OBS — darmowa <span class="accent">alternatywa dla OBS</span>',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio to młot pneumatyczny streamingu na żywo — nieskończenie konfigurowalny i darmowy. Ale do cam streamingu większość tej mocy jest zbędna, a krzywa konfiguracji stroma. <strong style='color:var(--text)'>SplitCam</strong> to lżejsza, darmowa alternatywa dla OBS: wbudowana kamera wirtualna, multistream jednym kliknięciem i filtry upiększające od ręki, z tym samym niestandardowym RTMP, który pozwala nadawać na dowolnej platformie cam. Oto porównanie obu.",
        "table_h": "Porównanie obok siebie",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Cena", "Darmowy, bez znaku wodnego", "Darmowy, open source"),
            ("Krzywa nauki", "Przyjazny początkującym", "Stroma"),
            ("Kamera wirtualna", "Wbudowana", "Wbudowana (nowsze wersje)"),
            ("Multistream na wiele serwisów", "Wbudowany, jedno kliknięcie", "Wymaga pluginu / relay"),
            ("Filtry upiększające i tło AI", "Wbudowane", "Brak natywnie"),
            ("Presety platform cam", "Tak (Streamate, VISIT-X…)", "Tylko ręczny RTMP"),
            ("Niestandardowe wyjście RTMP", "Tak", "Tak"),
            ("Obciążenie systemu", "Lekkie", "Cięższe"),
        ],
        "verdict_h": "Co wybrać?",
        "verdict": "Wybierz <strong style='color:var(--text)'>OBS</strong>, jeśli chcesz pełnej kontroli nad złożonymi scenami i nie przeszkadza ci konfiguracja. Wybierz <strong style='color:var(--text)'>SplitCam</strong>, jeśli chcesz wejść na żywo w kilka minut — ma wbudowane podstawy cam (kamera wirtualna, multistream, filtry upiększające, presety platform) i wciąż daje niestandardowy RTMP dla każdego serwisu.",
        "faq": [
            ("Czy SplitCam to dobra alternatywa dla OBS?", "Tak — do cam streamingu robi tę samą podstawową robotę (koduje twoją kamerę i wysyła przez RTMP do platformy) przy znacznie łatwiejszej konfiguracji, plus ma wbudowany multistream i filtry upiększające, do których OBS wymaga pluginów."),
            ("Czy SplitCam jest darmowy jak OBS?", "Tak. SplitCam jest darmowy, bez znaku wodnego i bez limitu czasu, dokładnie jak OBS. Żaden z nich nie pobiera opłat za nadawanie."),
            ("Czy SplitCam potrafi nadawać na wiele platform naraz jak OBS z pluginem?", "Tak i jest to wbudowane — bez pluginów czy płatnego relay. Dodaj klucz RTMP każdej platformy i wejdź na żywo na wszystkich jednym kliknięciem."),
            ("Czy SplitCam działa z tymi samymi serwisami co OBS?", "Tak — wszystko, co przyjmuje niestandardowy klucz streamu RTMP (Chaturbate, Stripchat, BongaCams, CAM4 i więcej), działa ze SplitCam, plus ma gotowe presety dla wielu platform cam."),
        ],
    },
    "vi": {
        "title": "SplitCam vs OBS — phần mềm thay thế OBS miễn phí cho cam streaming",
        "desc": "SplitCam là lựa chọn thay thế OBS miễn phí, nhẹ cho cam streaming — camera ảo tích hợp, multistream một cú nhấp, bộ lọc làm đẹp, không watermark. So sánh song song.",
        "h1html": 'SplitCam vs OBS — <span class="accent">thay thế OBS</span> miễn phí',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio là cây búa tạ của live-streaming — cấu hình vô hạn và miễn phí. Nhưng với cam streaming, phần lớn sức mạnh đó là thừa và đường thiết lập thì dốc. <strong style='color:var(--text)'>SplitCam</strong> là lựa chọn thay thế OBS nhẹ hơn, miễn phí: camera ảo tích hợp, multistream một cú nhấp và bộ lọc làm đẹp sẵn dùng, với cùng RTMP tùy chỉnh cho phép bạn phát tới mọi nền tảng cam. Đây là so sánh hai bên.",
        "table_h": "So sánh song song",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Giá", "Miễn phí, không watermark", "Miễn phí, mã nguồn mở"),
            ("Độ khó học", "Thân thiện người mới", "Dốc"),
            ("Camera ảo", "Tích hợp", "Tích hợp (bản mới)"),
            ("Multistream tới nhiều site", "Tích hợp, một cú nhấp", "Cần plugin / relay"),
            ("Bộ lọc làm đẹp & nền AI", "Tích hợp", "Không có sẵn"),
            ("Preset nền tảng cam", "Có (Streamate, VISIT-X…)", "Chỉ RTMP thủ công"),
            ("Đầu ra RTMP tùy chỉnh", "Có", "Có"),
            ("Tải hệ thống", "Nhẹ", "Nặng hơn"),
        ],
        "verdict_h": "Nên chọn cái nào?",
        "verdict": "Chọn <strong style='color:var(--text)'>OBS</strong> nếu bạn muốn kiểm soát toàn diện các cảnh phức tạp và không ngại thiết lập. Chọn <strong style='color:var(--text)'>SplitCam</strong> nếu bạn muốn lên sóng trong vài phút — nó mang sẵn các thứ cơ bản của cam (camera ảo, multistream, bộ lọc làm đẹp, preset nền tảng) và vẫn cho RTMP tùy chỉnh cho từng site.",
        "faq": [
            ("SplitCam có phải lựa chọn thay thế OBS tốt không?", "Có — với cam streaming, nó làm cùng việc cốt lõi (mã hóa camera và gửi qua RTMP tới nền tảng) với thiết lập dễ hơn nhiều, cộng multistream và bộ lọc làm đẹp tích hợp mà OBS cần plugin mới có."),
            ("SplitCam có miễn phí như OBS không?", "Có. SplitCam miễn phí, không watermark và không giới hạn thời gian, y như OBS. Cả hai đều không tính phí phát sóng."),
            ("SplitCam có phát tới nhiều nền tảng cùng lúc như OBS với plugin không?", "Có, và là tích hợp — không plugin hay relay trả phí. Thêm khóa RTMP của từng nền tảng và lên sóng tất cả bằng một cú nhấp."),
            ("SplitCam có hoạt động với cùng các site như OBS không?", "Có — bất cứ thứ gì nhận stream key RTMP tùy chỉnh (Chaturbate, Stripchat, BongaCams, CAM4 và hơn nữa) đều hoạt động với SplitCam, cộng nó có preset sẵn dùng cho nhiều nền tảng cam."),
        ],
    },
    "id": {
        "title": "SplitCam vs OBS — alternatif OBS gratis untuk cam streaming",
        "desc": "SplitCam adalah alternatif OBS yang gratis dan ringan untuk cam streaming — kamera virtual bawaan, multistream satu klik, filter kecantikan, tanpa watermark. Perbandingan berdampingan.",
        "h1html": 'SplitCam vs OBS — <span class="accent">alternatif OBS</span> gratis',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio adalah palu godam live-streaming — bisa dikonfigurasi tanpa batas dan gratis. Tapi untuk cam streaming, sebagian besar kekuatan itu berlebihan dan kurva setup-nya curam. <strong style='color:var(--text)'>SplitCam</strong> adalah alternatif OBS yang lebih ringan dan gratis: kamera virtual bawaan, multistream satu klik, dan filter kecantikan langsung pakai, dengan RTMP kustom yang sama yang membiarkanmu siaran ke platform cam mana pun. Berikut perbandingannya.",
        "table_h": "Perbandingan berdampingan",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Harga", "Gratis, tanpa watermark", "Gratis, open source"),
            ("Kurva belajar", "Ramah pemula", "Curam"),
            ("Kamera virtual", "Bawaan", "Bawaan (versi baru)"),
            ("Multistream ke banyak situs", "Bawaan, satu klik", "Perlu plugin / relay"),
            ("Filter kecantikan & latar AI", "Bawaan", "Tidak native"),
            ("Preset platform cam", "Ya (Streamate, VISIT-X…)", "Hanya RTMP manual"),
            ("Output RTMP kustom", "Ya", "Ya"),
            ("Beban sistem", "Ringan", "Lebih berat"),
        ],
        "verdict_h": "Mana yang harus dipilih?",
        "verdict": "Pilih <strong style='color:var(--text)'>OBS</strong> kalau kamu ingin kontrol penuh atas scene kompleks dan tidak keberatan dengan setup-nya. Pilih <strong style='color:var(--text)'>SplitCam</strong> kalau kamu ingin live dalam hitungan menit — ia membawa dasar-dasar cam (kamera virtual, multistream, filter kecantikan, preset platform) secara bawaan dan tetap memberi RTMP kustom untuk tiap situs.",
        "faq": [
            ("Apakah SplitCam alternatif OBS yang bagus?", "Ya — untuk cam streaming ia melakukan tugas inti yang sama (meng-encode kameramu dan mengirimnya via RTMP ke platform) dengan setup yang jauh lebih mudah, ditambah multistream dan filter kecantikan bawaan yang butuh plugin di OBS."),
            ("Apakah SplitCam gratis seperti OBS?", "Ya. SplitCam gratis, tanpa watermark dan tanpa batas waktu, persis seperti OBS. Keduanya tidak mengenakan biaya untuk siaran."),
            ("Bisakah SplitCam siaran ke beberapa platform sekaligus seperti OBS dengan plugin?", "Ya, dan bawaan — tanpa plugin atau relay berbayar. Tambahkan kunci RTMP tiap platform dan live ke semua dengan satu klik."),
            ("Apakah SplitCam bekerja dengan situs yang sama seperti OBS?", "Ya — apa pun yang menerima stream key RTMP kustom (Chaturbate, Stripchat, BongaCams, CAM4, dan lainnya) bekerja dengan SplitCam, plus ia punya preset siap pakai untuk banyak platform cam."),
        ],
    },
    "tr": {
        "title": "SplitCam vs OBS — cam yayını için ücretsiz OBS alternatifi",
        "desc": "SplitCam, cam yayını için ücretsiz, hafif bir OBS alternatifidir — yerleşik sanal kamera, tek tıkla çoklu yayın, güzellik filtreleri, filigran yok. Yan yana karşılaştırma.",
        "h1html": 'SplitCam vs OBS — ücretsiz <span class="accent">OBS alternatifi</span>',
        "h1short": "SplitCam vs OBS",
        "intro": "OBS Studio, canlı yayının ağır topu — sonsuz yapılandırılabilir ve ücretsiz. Ama cam yayını için bu gücün çoğu fazlalık ve kurulum eğrisi dik. <strong style='color:var(--text)'>SplitCam</strong> daha hafif, ücretsiz bir OBS alternatifidir: yerleşik sanal kamera, tek tıkla çoklu yayın ve kutudan çıkan güzellik filtreleri, herhangi bir cam platformuna yayın yapmanı sağlayan aynı özel RTMP ile. İşte ikisinin karşılaştırması.",
        "table_h": "Yan yana karşılaştırma",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Fiyat", "Ücretsiz, filigran yok", "Ücretsiz, açık kaynak"),
            ("Öğrenme eğrisi", "Yeni başlayan dostu", "Dik"),
            ("Sanal kamera", "Yerleşik", "Yerleşik (yeni sürümler)"),
            ("Birçok siteye çoklu yayın", "Yerleşik, tek tık", "Eklenti / relay gerekir"),
            ("Güzellik filtreleri & AI arka plan", "Yerleşik", "Yerel değil"),
            ("Cam platform ön ayarları", "Var (Streamate, VISIT-X…)", "Sadece elle RTMP"),
            ("Özel RTMP çıkışı", "Var", "Var"),
            ("Sistem yükü", "Hafif", "Daha ağır"),
        ],
        "verdict_h": "Hangisini seçmelisin?",
        "verdict": "Karmaşık sahneler üzerinde tam kontrol istiyorsan ve kurulum seni rahatsız etmiyorsa <strong style='color:var(--text)'>OBS</strong>'i seç. Dakikalar içinde canlı olmak istiyorsan <strong style='color:var(--text)'>SplitCam</strong>'i seç — cam temellerini (sanal kamera, çoklu yayın, güzellik filtreleri, platform ön ayarları) yerleşik getirir ve yine de her site için özel RTMP verir.",
        "faq": [
            ("SplitCam iyi bir OBS alternatifi mi?", "Evet — cam yayını için aynı temel işi (kameranı kodlayıp RTMP ile platforma gönderme) çok daha kolay bir kurulumla yapar, ayrıca OBS'in eklenti gerektirdiği yerleşik çoklu yayın ve güzellik filtreleri vardır."),
            ("SplitCam OBS gibi ücretsiz mi?", "Evet. SplitCam ücretsiz, filigransız ve süre sınırsız, tıpkı OBS gibi. İkisi de yayın için ücret almaz."),
            ("SplitCam eklentili OBS gibi aynı anda birden fazla platforma yayın yapabilir mi?", "Evet ve yerleşik — eklenti veya ücretli relay yok. Her platformun RTMP anahtarını ekle ve hepsine tek tıkla canlıya geç."),
            ("SplitCam OBS ile aynı sitelerde çalışır mı?", "Evet — özel RTMP yayın anahtarı kabul eden her şey (Chaturbate, Stripchat, BongaCams, CAM4 ve daha fazlası) SplitCam ile çalışır, ayrıca birçok cam platformu için hazır ön ayarları vardır."),
        ],
    },
    "fil": {
        "title": "SplitCam vs OBS — libreng alternatibo sa OBS para sa cam streaming",
        "desc": "Ang SplitCam ay libre at magaan na alternatibo sa OBS para sa cam streaming: built-in na virtual camera, one-click multistreaming, beauty filters, walang watermark. Magkatabing paghahambing.",
        "h1html": 'SplitCam vs OBS — ang libreng <span class="accent">alternatibo sa OBS</span>',
        "h1short": "SplitCam vs OBS",
        "intro": "Ang OBS Studio ang heavyweight ng live streaming — walang-hanggang ma-configure at libre. Pero para sa cam streaming, sobra-sobra ang karamihan ng kapangyarihang iyon, at matarik ang setup curve. Ang <strong style='color:var(--text)'>SplitCam</strong> ay mas magaan, libreng alternatibo sa OBS: built-in na virtual camera, one-click multistreaming at beauty filters na agad gamit, na may parehong custom RTMP para mag-broadcast sa anumang cam platform. Narito ang paghahambing.",
        "table_h": "Magkatabing paghahambing",
        "col_sc": "SplitCam", "col_obs": "OBS Studio",
        "rows": [
            ("Presyo", "Libre, walang watermark", "Libre, open source"),
            ("Learning curve", "Pang-baguhan", "Matarik"),
            ("Virtual camera", "Built-in", "Built-in (bagong bersyon)"),
            ("Multistreaming sa maraming site", "Built-in, isang click", "Kailangan ng plugin / relay"),
            ("Beauty filters at AI background", "Built-in", "Hindi native"),
            ("Mga preset ng cam platform", "Oo (Streamate, VISIT-X…)", "Manual RTMP lang"),
            ("Custom RTMP output", "Oo", "Oo"),
            ("Load sa sistema", "Magaan", "Mas mabigat"),
        ],
        "verdict_h": "Alin ang dapat piliin?",
        "verdict": "Piliin ang <strong style='color:var(--text)'>OBS</strong> kung gusto mo ng ganap na kontrol sa mga kumplikadong scene at hindi ka nababahala sa setup. Piliin ang <strong style='color:var(--text)'>SplitCam</strong> kung gusto mong maging live sa loob ng ilang minuto — built-in na ang mga cam essentials (virtual camera, multistream, beauty filters, platform presets), at binibigyan ka pa rin ng custom RTMP para sa anumang site.",
        "faq": [
            ("Magandang alternatibo ba sa OBS ang SplitCam?", "Oo — para sa cam streaming, sinasaklaw nito ang parehong core na trabaho (i-encode ang camera at ipadala sa platform via RTMP) na may mas simpleng setup, plus built-in na multistreaming at beauty filters na kailangan ng plugin sa OBS."),
            ("Libre ba ang SplitCam tulad ng OBS?", "Oo. Ang SplitCam ay libre, walang watermark at walang time limit, tulad ng OBS. Walang sinisingil ang dalawa para mag-stream."),
            ("Kaya bang mag-stream ng SplitCam sa maraming platform nang sabay tulad ng OBS na may plugin?", "Oo, at built-in ito — walang plugin o bayad na relay. Idagdag ang RTMP key ng bawat platform at mag-live sa lahat nang isang click."),
            ("Gumagana ba ang SplitCam sa mga site na ginagamitan ng OBS?", "Oo — anumang tumatanggap ng custom RTMP key (Chaturbate, Stripchat, BongaCams, CAM4 at iba pa) ay gumagana sa SplitCam, plus may mga handa nang preset ito para sa ilang cam platform."),
        ],
    },
}
