# -*- coding: utf-8 -*-
"""Filipino/Tagalog (fil) content for cam-streaming-guides."""

_T_ETH = ("Gamitin ang wired connection", "Talo ng Ethernet ang Wi-Fi sa mahabang stream — ang naturang frame ay nawawalang tip. Maglagay ng cable papunta sa stream PC.")
_T_TEST = ("Gumawa muna ng private test", "Magpatakbo ng maikling test broadcast para suriin ang camera, audio, framing at overlays bago buksan ang room para sa publiko.")

def _p(slug, name, title, desc, kw, h1html, h1short, card, intro, quick, key_how, tips, faq, steps=None):
    d = {"slug": slug, "name": name, "title": title, "desc": desc, "kw": kw,
         "h1html": h1html, "h1short": h1short, "card": card, "intro": intro,
         "quick": quick, "key_how": key_how, "tips": tips, "faq": faq}
    if steps: d["steps"] = steps
    return d

PLATFORMS_FIL = [
    _p("chaturbate", "Chaturbate",
       "Mag-broadcast sa Chaturbate gamit ang SplitCam — Token & RTMP",
       "Mag-broadcast sa Chaturbate gamit ang libreng SplitCam — broadcast token, RTMP, multi-camera scenes at overlays. Walang watermark.",
       "chaturbate broadcast, chaturbate broadcast token, chaturbate rtmp obs, chaturbate external encoder, chaturbate live",
       'Paano mag-broadcast sa <span class="accent">Chaturbate</span> gamit ang SplitCam',
       "Chaturbate broadcast",
       "Token-based setup na may external encoder sa Chaturbate.",
       "Ang Chaturbate ay isa sa pinakamalaking cam platforms, itinayo sa token economy. Ang browser broadcaster ay flat single-camera tool — ang paglipat sa <strong style='color:var(--text)'>external encoder</strong> gamit ang libreng <strong style='color:var(--text)'>SplitCam</strong> ay nagbubukas ng multi-camera scenes, overlays at filters sa parehong token-based stream.",
       "Mag-broadcast sa Chaturbate gamit ang SplitCam: i-install ang SplitCam, buuin ang scene, sa Chaturbate buksan ang <em>Broadcast Yourself → My Broadcast</em>, kopyahin ang broadcast token, i-paste sa SplitCam, Go Live."
       "<ol><li>I-install ang SplitCam.</li><li>Idagdag ang camera + scene.</li><li>Kopyahin ang broadcast token mula sa Chaturbate.</li><li>I-paste sa SplitCam.</li><li>Pindutin ang Go Live.</li></ol>",
       "Sa Chaturbate i-click ang <strong>Broadcast Yourself</strong> para sa pahina ng <strong>My Broadcast</strong>, pagkatapos <strong>View RTMP/OBS broadcast information and stream key</strong>. Lumalabas ang key bilang iyong <strong>broadcast token</strong> — kopyahin ito. Tratuhin ito tulad ng password; hindi kailanman pampubliko.",
       [("Ang token ang susi", "Ginagamit ng Chaturbate ang broadcast token mo sa halip na generic stream key. Tratuhin tulad ng password at i-reset kung nag-leak."),
        ("Maraming espasyo", "Tumatanggap ang RTMP ingest ng Chaturbate ng hanggang 4K, 60 fps at mataas na bitrate — ang limitasyon ay ang upload mo, hindi ang platform. Keyframe bawat 2 segundo."),
        _T_ETH, _T_TEST],
       [("Pinapayagan ba ng Chaturbate ang OBS / external encoders?", "Oo — Opisyal na sinusuportahan ng Chaturbate ang external encoders na may sariling «How do I set up OBS?» na artikulo. I-activate sa pamamagitan ng «Use External Encoder to Broadcast» sa broadcast settings."),
        ("Saan ang Chaturbate stream key ko?", "Broadcast Yourself → My Broadcast → View RTMP/OBS broadcast information and stream key. Ang key ay ang broadcast token mo."),
        ("Anong bitrate para sa Chaturbate?", "3,500–6,000 Kbps sa 1080p ay sapat na. Ang ceiling ng Chaturbate ay mataas — ang aktwal na limitasyon ay ang upload mo; patakbuhin muna ang built-in speed test ng SplitCam."),
        ("Libre ba ang SplitCam para sa Chaturbate?", "Oo — ganap na libre, walang watermark at walang time limit: hindi kakain ng encoder ang kita mo sa tokens.")]),
    _p("cam4", "CAM4",
       "Mag-broadcast sa CAM4 gamit ang SplitCam — External Encoder",
       "Mag-broadcast sa CAM4 gamit ang libreng SplitCam — External Encoder, stream key, geo-blocking at overlays. Walang watermark.",
       "cam4 broadcast, cam4.com, cam4 external encoder, cam4 stream key, cam4 rtmp obs",
       'Paano mag-broadcast sa <span class="accent">CAM4</span> gamit ang SplitCam',
       "CAM4 broadcast",
       "External Encoder sa CAM4 na may geo-controls.",
       "Ang CAM4 ay global cam-and-earn platform na may built-in geo-controls — maaari mong itago ang broadcast sa mga piniling bansa. Ang pag-broadcast sa pamamagitan ng libreng <strong style='color:var(--text)'>SplitCam</strong> bilang external encoder ay nagbubukas ng scene switches at overlays na hindi ginagawa ng basic broadcaster.",
       "Mag-broadcast sa CAM4 gamit ang SplitCam: i-install ang SplitCam, buuin ang scene, sa CAM4 pumunta sa <em>Broadcast &amp; Earn Money → Start Broadcast → External Encoder</em>, Get Stream Key, i-paste sa SplitCam, Go Live."
       "<ol><li>I-install ang SplitCam.</li><li>Idagdag ang camera + scene.</li><li>Kunin ang stream key mula sa CAM4.</li><li>I-paste sa SplitCam.</li><li>Pindutin ang Go Live.</li></ol>",
       "Sa CAM4 i-click ang <strong>Broadcast</strong> → <strong>Broadcast &amp; Earn Money</strong> → <strong>Start Broadcast</strong>, pagkatapos <strong>External Encoder</strong> sa itaas. Punan ang birth date, gender at country, gamitin ang <strong>Get Stream Key</strong> at kopyahin. Isang green slider sa Stream Settings ng SplitCam ang nagkukumpirma ng koneksyon.",
       [("I-set ang geo-restrictions", "Pinapayagan ng CAM4 ang pagtatago ng broadcast sa mga partikular na bansa at rehiyon — i-configure sa panig ng CAM4 bago mag-go-live."),
        ("Bantayan ang green slider", "Ang setup ng CAM4 ay nagpapakita ng green slider sa Stream Settings ng SplitCam kapag tinanggap ang key — pula = i-check ang key."),
        ("Mas mababang bitrate kaysa sa karaniwan", "Nililimitahan ng CAM4 ingest ang video bitrate sa mga 3,000 Kbps — mas mababa kaysa sa karamihan ng cam sites. Huwag itulak ng mas mataas."),
        _T_ETH],
       [("Sinusuportahan ba ng CAM4 ang OBS / external encoders nang opisyal?", "Oo — may opisyal na OBS Guide ang CAM4 sa support site at inirerekomenda ang External Encoder para sa pinakamagandang karanasan. Gumagamit ang SplitCam ng parehong RTMP route."),
        ("Maaari ko bang i-geo-block ang CAM4 stream ko?", "Oo — may built-in na geo-restriction ang CAM4 para itago ang broadcast sa ilang bansa. I-set sa CAM4, hindi sa SplitCam."),
        ("Saan ang stream key ng CAM4?", "Broadcast → Broadcast & Earn Money → Start Broadcast → External Encoder → Get Stream Key."),
        ("Anong bitrate para sa CAM4?", "Mas mababa kaysa sa average — nililimitahan ng CAM4 ingest sa ~3,000 Kbps sa 30 fps na may 1-segundong keyframe. Inirerekomenda ng opisyal na talahanayan na huwag lumampas sa ~3,000.")]),
    _p("bongacams", "BongaCams",
       "Mag-broadcast sa BongaCams gamit ang SplitCam — External Encoder",
       "Mag-broadcast sa BongaCams gamit ang libreng SplitCam — External Encoder, multi-camera scenes, overlays at AI background. Walang watermark.",
       "bongacams, bongcams, bongacams broadcast, bongacams external encoder, bongacams rtmp obs",
       'Paano mag-broadcast sa <span class="accent">BongaCams</span> gamit ang SplitCam',
       "BongaCams broadcast",
       "External Encoder setup para sa BongaCams.",
       "Ang BongaCams ay global cam platform. Hindi laging activated ang external encoder broadcasting — kapag na-activate, pinapatakbo ng libreng <strong style='color:var(--text)'>SplitCam</strong> ang broadcast na may multi-camera scenes, overlays at AI background.",
       "Mag-broadcast sa BongaCams gamit ang SplitCam: i-install ang SplitCam, buuin ang scene, sa BongaCams pumunta sa <em>Options → Broadcast settings → Select Encoder → External Encoder</em>, kopyahin ang URL at key, i-paste sa SplitCam, Go Live."
       "<ol><li>I-install ang SplitCam.</li><li>Idagdag ang camera + scene.</li><li>Kunin ang URL at key mula sa BongaCams.</li><li>I-paste sa SplitCam.</li><li>Pindutin ang Go Live.</li></ol>",
       "Sa BongaCams buksan ang <strong>Options</strong> → <strong>Broadcast settings</strong> → <strong>Select Encoder</strong> → <strong>External Encoder</strong> at kopyahin ang server URL at stream key na ipinapakita. <strong>Kung wala ang External Encoder button</strong>, makipag-ugnayan sa BongaCams support at hilingin na i-enable ang external encoding sa account mo.",
       [("Walang External Encoder button? Support", "Ina-activate ng BongaCams ang external encoding bawat account — kung kulang ang opsyon sa Broadcast settings, ang support ay nag-aactivate."),
        ("Itugma ang resolution", "Inirerekomenda ng BongaCams na magkatugma ang resolution ng webcam at broadcast — halimbawa parehas 1280×720."),
        _T_ETH, _T_TEST],
       [("Bakit hindi lumalabas ang External Encoder button sa BongaCams?", "Hindi default active ang external encoding sa bawat account — makipag-ugnayan sa BongaCams support para i-activate, at lalabas ang button sa Broadcast settings."),
        ("Kailangan ko bang i-verify ang BongaCams account ko?", "Oo — ang broadcasting ay nangangailangan ng 18+, opisyal na ID para sa age verification at approval ng account bago mag-live."),
        ("Anong bitrate para sa BongaCams?", "Nililimitahan ng BongaCams RTMP ingest ang video bitrate sa mga 6,000 Kbps na may 2-segundong keyframe — 3,500–6,000 sa 1080p ang ideal zone; subukan muna ang upload."),
        ("Libre ba ang SplitCam para sa BongaCams?", "Oo — ganap na libre, walang watermark at walang time limit, kaya hindi nababawasan ng encoder ang kita mo sa tokens sa BongaCams.")]),
    _p("stripchat", "Stripchat",
       "Mag-broadcast sa Stripchat gamit ang SplitCam — Strip Cam Setup",
       "Mag-broadcast sa Stripchat — ang strip cam platform — gamit ang libreng SplitCam. External software, token key, scenes at overlays.",
       "strip cam, stripchat live stream, stripchat broadcast, stripchat external software, stripchat stream key, stripchat rtmp obs",
       'Paano mag-broadcast sa <span class="accent">Stripchat</span> gamit ang SplitCam',
       "Stripchat broadcast",
       "External software setup para sa Stripchat streams.",
       "Ang Stripchat ay malaking cam platform na may focus sa interactivity. Ang <em>external software</em> mode ay nagbibigay sa iyo ng token-based key — ilagay ito sa libreng <strong style='color:var(--text)'>SplitCam</strong> para mag-broadcast na may scenes, overlays at filters sa halip na flat camera.",
       "Mag-broadcast sa Stripchat gamit ang SplitCam: i-install ang SplitCam, buuin ang scene, sa Stripchat piliin ang <em>Switch to external software</em>, kopyahin ang stream key, i-paste sa SplitCam, Go Live."
       "<ol><li>I-install ang SplitCam.</li><li>Idagdag ang camera + scene.</li><li>Kunin ang stream key mula sa Stripchat.</li><li>I-paste sa SplitCam.</li><li>Pindutin ang Go Live.</li></ol>",
       "Sa Stripchat piliin ang <strong>Switch to external software</strong>, pagkatapos <strong>Show external software settings for the stream</strong>. Kopyahin ang stream key — ipinapakita ito ng Stripchat bilang token. Panatilihing pribado.",
       [("Itugma ang resolution sa site", "Babala ng Stripchat FAQ: kailangan eksaktong tumugma ang resolution sa software mo sa site, kung hindi ay pixelate ang video. I-set parehas."),
        ("Mag-ingat sa 2 Mbps minimum", "Inilista ng Stripchat ang 2 Mbps upload bilang minimum — at direktang sinabi na hindi sapat ito para sa OBS streaming o multistreaming. Tumira nang mas mataas."),
        ("Ang key ay token", "Ang stream key ng Stripchat ay token — kopyahin nang eksakto, huwag i-share, i-reset kung nag-leak."),
        _T_ETH],
       [("Inirerekomenda ba ng Stripchat ang OBS / external software?", "Oo — inirerekomenda ng opisyal na FAQ ng Stripchat ang external broadcast software tulad ng OBS «para makamit ang pinakamagandang quality ng video at audio». Pareho ang gana ng SplitCam."),
        ("Paano ilipat ang Stripchat sa external software?", "Sa Broadcast Center piliin ang Switch to External Broadcast Software (OBS), pagkatapos buksan ang external software settings para ilantad ang stream key (token)."),
        ("Anong bitrate para sa Stripchat?", "Tumatanggap ang RTMP ingest ng hanggang ~6,000 Kbps na may 2-segundong keyframe. 3,500–6,000 sa 1080p ang ideal — pero kailangan ito ay mas mataas sa 2 Mbps minimum, lalo na para sa OBS streaming."),
        ("Libre ba ang SplitCam para sa Stripchat?", "Oo — walang license fee, walang watermark, walang time limit: kahit ang mahabang interactive Stripchat shows ay walang gastos sa encoder side.")]),
    _p("onlyfans", "OnlyFans",
       "Mag-live sa OnlyFans gamit ang SplitCam — Authorization o Key",
       "Mag-live sa OnlyFans gamit ang libreng SplitCam — login sa pamamagitan ng authorization o OBS Key, multi-camera scenes, overlays. Walang watermark.",
       "onlyfans live, onlyfans live stream, onlyfans authorization splitcam, onlyfans obs key, onlyfans streaming software",
       'Paano mag-live sa <span class="accent">OnlyFans</span> gamit ang SplitCam',
       "Live OnlyFans",
       "Mag-authorize minsan o i-paste ang key — live sa OnlyFans.",
       "Ang OnlyFans live ay para sa mga subscribers mo. Kumokonekta ang SplitCam sa <strong style='color:var(--text)'>dalawang paraan</strong> — mag-log in minsan gamit ang OnlyFans account at automatic na kinukuha ng SplitCam ang stream key at pinapanatiling naka-sync, o i-paste ang OBS Key nang manu-mano. Sa parehong kaso ay mag-broadcast ka na may multi-camera scenes, overlays at filters.",
       "Mag-live sa OnlyFans gamit ang SplitCam: i-install ang SplitCam, buuin ang scene, buksan ang Stream Settings &rarr; Add Channel &rarr; OnlyFans at piliin ang <em>Authorization</em> — mag-log in gamit ang OnlyFans account, kinukuha ng SplitCam ang key automatically — at pindutin ang Go Live. Sa naka-connect na account maaaring baguhin ang OnlyFans stream parameters sa SplitCam, nang hindi binubuksan ang OnlyFans site.",
       "Sa OnlyFans: <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; section ng <strong>Other</strong>, kopyahin ang <strong>OBS Key</strong>. O gamitin ang <strong>Authorization</strong> option sa SplitCam para sa account login — automatic na kinukuha ang key at pinapanatiling naka-sync.",
       [("Authorization vs Stream Key", "Dalawang paraan ng pagkonekta: <strong>Authorization</strong> (mag-log in minsan, kinukuha at sync ang key — pinakamadaling ruta) o <strong>Stream Key</strong> (kopyahin ang OBS Key sa OnlyFans → Profile → Settings → Other at i-paste)."),
        ("Baguhin ang settings nang hindi umaalis sa SplitCam", "Sa authorization manatili ang account na connected, kaya nag-aadjust ng OnlyFans live parameters mula sa SplitCam sa panahon o pagkatapos ng broadcast — nang hindi dumadaan sa OnlyFans site."),
        ("Katamtamang bitrate", "Nililimitahan ng OnlyFans RTMP ingest ang video bitrate sa mga 2,500 Kbps — mas mahigpit kaysa sa karamihan ng cam sites. Tumira sa 720p–1080p sa ~2,000–2,500."),
        _T_ETH],
       [("Paano ko ikokonekta ang OnlyFans sa SplitCam?", "Sa dalawang paraan. <strong>Authorization</strong> — Stream Settings → Add Channel → OnlyFans → mag-log in gamit ang OnlyFans account at automatic na kinukuha ng SplitCam ang key. O <strong>Stream Key</strong> — kopyahin ang OBS Key sa OnlyFans → Profile → Settings → Other at i-paste."),
        ("Maaari ko bang baguhin ang OnlyFans live settings nang hindi binubuksan ang site?", "Oo — sa Authorization method ang SplitCam ay nananatiling connected sa OnlyFans account mo, kaya sync ang key at settings automatically."),
        ("Anong bitrate para sa OnlyFans?", "Katamtaman — nililimitahan ng OnlyFans RTMP ingest ang bitrate sa mga 2,500 Kbps, mas mahigpit kaysa sa ibang cam platforms. Tumira sa 720p–1080p sa paligid ng 2,000–2,500 Kbps."),
        ("Libre ba ang SplitCam para sa OnlyFans live?", "Oo — libre, walang watermark at walang time limit. Walang gastos sa encoder side.")],
       steps=[
           ("I-download at i-install ang SplitCam", "Ang SplitCam ay libreng live-streaming software para sa Windows at macOS — walang sign-up, walang card, walang watermark. Ito ang encoder na nagpapadala ng video mo sa OnlyFans."),
           ("I-set up ang camera at scene", "Buksan ang SplitCam at idagdag ang webcam. Buuin ang scene sa paraan na gusto mong makita ng mga viewers — overlays, text, pangalawang camera, beauty filters o AI background, lahat ay live na inilapat."),
           ("Koneksyon — Method 1: Authorization (Inirerekomenda)", "Sa SplitCam buksan ang <strong>Stream Settings</strong> &rarr; <strong>Add Channel</strong> &rarr; <strong>OnlyFans</strong> at piliin ang <strong>Authorization</strong>. Mag-log in gamit ang OnlyFans email at password. Kinokonekta ng SplitCam ang account mo, kinukuha ang stream key automatically at pinapanatiling naka-sync — at pinapayagan kang pamahalaan ang OnlyFans live parameters sa loob ng SplitCam, binabago sa panahon o pagkatapos ng broadcast nang hindi binubuksan ang OnlyFans site."),
           ("Koneksyon — Method 2: Stream Key (manual)", "Mas gusto mong hindi mag-log in? Gamitin ang key. Sa OnlyFans pumunta sa <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; section ng <strong>Other</strong> at kopyahin ang <strong>OBS Key</strong>. Sa SplitCam, Add Channel &rarr; OnlyFans, i-paste sa key field. Static ang key na ito — para baguhin ang settings mamaya bumalik sa OnlyFans site."),
           ("Go Live", "Anumang method, pindutin ang <strong>Go Live</strong> sa SplitCam. Sa Method 1 maaaring magpatuloy ang pag-aadjust ng OnlyFans parameters mula sa SplitCam in real time; sa Method 2 nananatili ang key tulad ng pagkaset."),
       ]),
    _p("camplace", "CamPlace",
       "Mag-broadcast sa CamPlace gamit ang SplitCam — Libreng gabay",
       "Mag-broadcast sa CamPlace gamit ang libreng SplitCam — external encoder, RTMP key, scenes at overlays. Hakbang-hakbang, walang watermark.",
       "camplace broadcast, camplace broadcasting software, camplace rtmp, camplace external encoder, camplace stream key",
       'Paano mag-broadcast sa <span class="accent">CamPlace</span> gamit ang SplitCam',
       "CamPlace broadcast",
       "External encoder setup para sa CamPlace streams.",
       "Ang CamPlace ay cam-streaming platform. Walang public OBS article, kaya ang <strong style='color:var(--text)'>video guide sa itaas</strong> ang sanggunian mo — kumokonekta ang libreng <strong style='color:var(--text)'>SplitCam</strong> sa pamamagitan ng standard RTMP at nagdaragdag ng scenes, overlays at AI background na hindi ginagawa ng basic camera.",
       "Mag-broadcast sa CamPlace gamit ang SplitCam: i-install ang SplitCam, buuin ang scene, i-activate ang external/RTMP broadcasting sa CamPlace, kopyahin ang server URL at stream key, i-paste sa SplitCam, Go Live. Sundan ang video para sa kasalukuyang ruta."
       "<ol><li>I-install ang SplitCam.</li><li>Idagdag ang camera + scene.</li><li>Kunin ang RTMP key mula sa CamPlace.</li><li>I-paste sa SplitCam.</li><li>Pindutin ang Go Live.</li></ol>",
       "Mag-log in sa CamPlace at buksan ang broadcasting settings. Lumipat sa external encoder / RTMP / OBS option para ilantad ang <strong>server URL</strong> at <strong>stream key</strong>, kopyahin pareho. Hindi naglalathala ang CamPlace ng opisyal na OBS documentation — ang <strong>video sa itaas</strong> ang pinaka-maaasahang hakbang-hakbang na ruta sa kasalukuyang interface.",
       [("Walang opisyal na OBS guide — gamitin ang video", "Walang public article ang CamPlace tungkol sa external encoders; ang video sa itaas ang sanggunian para sa kasalukuyang ruta."),
        ("Gumagana ang standard RTMP", "Bagama't hindi dokumentado, tinatanggap ng CamPlace ang standard RTMP server URL at key — kumokonekta ang SplitCam bilang custom RTMP destination."),
        _T_ETH, _T_TEST],
       [("May opisyal na OBS guide ba ang CamPlace?", "Walang nakitang public article tungkol sa external encoders. Tinatanggap ng CamPlace ang standard RTMP URL at key, kaya gumagana ang SplitCam — sundan ang video."),
        ("Sinusuportahan ba ng CamPlace ang external encoders?", "Oo — tinatanggap nito ang standard RTMP stream key, kaya kumokonekta ang SplitCam bilang custom RTMP destination."),
        ("Anong bitrate para sa CamPlace?", "Hindi naglalathala ang CamPlace ng opisyal na numero — gamitin ang 3,500–6,000 Kbps sa 1080p bilang safe range at hayaan ang speed test ng SplitCam na ayusin ang tunay mong ceiling."),
        ("Libre ba ang SplitCam para sa CamPlace?", "Oo — libre, walang watermark at walang time limit. Dahil hindi nagdadala ng sariling encoder ang CamPlace, gumagawa ng trabaho ang libreng RTMP tool.")]),
    _p("camsoda", "CamSoda",
       "CamSoda live gamit ang SplitCam — Libreng setup",
       "CamSoda live gamit ang libreng SplitCam — Use OBS Broadcaster, regional servers, scenes at overlays. Walang watermark.",
       "camsoda live, camsoda broadcast, camsoda obs broadcaster, camsoda rtmp obs, camsoda live broadcast",
       'Paano mag-broadcast sa <span class="accent">CamSoda</span> gamit ang SplitCam',
       "CamSoda broadcast",
       "Use OBS Broadcaster setup sa CamSoda.",
       "Ang CamSoda ay American cam platform na kilala sa interactive at hindi pangkaraniwang show formats. Opisyal nitong sinusuportahan ang OBS streaming — may <strong style='color:var(--text)'>Use OBS Broadcaster</strong> button sa Go Live page at opisyal na OBS guide sa CamSoda wiki. Pareho ang gana ng libreng <strong style='color:var(--text)'>SplitCam</strong>.",
       "Mag-broadcast sa CamSoda gamit ang SplitCam: i-install ang SplitCam, buuin ang scene, i-click ang Use OBS Broadcaster sa Go Live page ng CamSoda, kopyahin ang server URL at stream key, i-paste sa SplitCam, Go Live."
       "<ol><li>I-install ang SplitCam.</li><li>Idagdag ang camera + scene.</li><li>I-click ang Use OBS Broadcaster sa CamSoda.</li><li>I-paste ang server URL + key sa SplitCam.</li><li>Pindutin ang Go Live.</li></ol>",
       "Sa <strong>Go Live</strong> page ng CamSoda i-click ang <strong>Use OBS Broadcaster</strong>. Pinapakita ng CamSoda ang RTMP server URL at stream key — kopyahin pareho. Piliin ang regional server (North America, Europe, Asia atbp) na pinakamalapit sa iyo. May kumpletong OBS guide ang CamSoda wiki para sa mga detalye.",
       [("Mag-verify para sa tips", "Sa CamSoda kahit sino ay puwedeng mag-broadcast, pero para tumanggap ng tips kailangan kumpletuhin ang CamSoda verification process."),
        ("Piliin ang pinakamalapit na regional server", "Nag-aalok ang CamSoda ng regional ingest servers — ang pinakamalapit (NA / Europe / Asia / South America / Oceania) ay nagbabawas ng latency at dropped frames."),
        ("Ceiling sa 1080p / 30 fps", "Umaabot ang CamSoda ingest hanggang mga 1080p, 30 fps at ~6,000 Kbps — huwag itulak ng mas mataas."),
        _T_ETH],
       [("Sinusuportahan ba ng CamSoda ang OBS / external encoders?", "Oo — opisyal. May Use OBS Broadcaster button sa Go Live page at OBS guide sa CamSoda wiki, kaya gumagana ang SplitCam."),
        ("Kailangan ko bang i-verify ang sarili sa CamSoda?", "Para mag-broadcast, hindi. Para tumanggap ng tips, oo — kailangan muna ng CamSoda ang verification process."),
        ("Anong resolution ang sinusuportahan ng CamSoda?", "Hanggang 1920×1080 sa 30 fps, mga 6,000 Kbps maximum sa RTMP ingest."),
        ("Libre ba ang SplitCam para sa CamSoda?", "Oo — libre, walang watermark at walang time limit. Gumagana sa libreng Use OBS Broadcaster mode ng CamSoda, kaya ang buong chain ay walang gastos.")]),
    _p("streamate", "Streamate",
       "Mag-broadcast sa Streamate gamit ang SplitCam — Integrated channel",
       "Mag-broadcast sa Streamate gamit ang libreng SplitCam — integrated channel, SM Connect key, scenes at overlays. Walang watermark.",
       "streamate, streamate sm connect, streamate broadcast, streamate broadcasting software, streamate rtmp",
       'Paano mag-broadcast sa <span class="accent">Streamate</span> gamit ang SplitCam',
       "Streamate broadcast",
       "Integrated channel ang Streamate sa SplitCam — mabilis na setup.",
       "Ang Streamate ay established cam platform — at isa ito sa mga <strong style='color:var(--text)'>pre-configured destinations sa SplitCam</strong>, sa channel list, kaya mas mabilis ang setup kaysa manual RTMP entry: pumili ng Streamate, i-paste ang key, tapos.",
       "Mag-broadcast sa Streamate gamit ang SplitCam: i-install ang SplitCam, buuin ang scene, sa Streamate gamitin ang <em>SM Connect → Start Show</em> at kopyahin ang key, pagkatapos sa SplitCam buksan ang <em>Stream Settings → Add Channel → Streamate</em> at i-paste."
       "<ol><li>I-install ang SplitCam.</li><li>Idagdag ang camera + scene.</li><li>Kunin ang Streamate key sa pamamagitan ng SM Connect.</li><li>Add Channel → Streamate sa SplitCam.</li><li>Pindutin ang Go Live.</li></ol>",
       "Sa Streamate buksan ang <strong>SM Connect</strong>, tanggapin ang terms, i-click ang <strong>Start Show</strong> sa kaliwa at isara ang window na nagbukas — pagkatapos kopyahin ang streaming key. Sa SplitCam buksan ang <strong>Stream Settings</strong> → <strong>Add Channel</strong>, piliin ang <strong>Streamate</strong> mula sa list at i-paste ang key. Isang green slider ang nagkukumpirma ng koneksyon.",
       [("Integrated ang Streamate", "Walang manual RTMP URL — may Streamate ang SplitCam sa Add Channel list; pumili lang at i-paste ang key."),
        ("Isara ang SM Connect popup", "Pagkatapos ng Start Show ay nagbubukas ang Streamate ng window — isara ito; para lang ilantad ang streaming key."),
        ("I-lock ang resolution sa 1080p", "Ang Video Resolution field sa SM Connect ay maaaring tahimik na tumalon sa 1440, na hindi naman talaga naidedeliver at tahimik na binababa ang quality mo — i-set manual sa 1080p. Normal ang bitrate na bumababa sa static image: adaptive ang Streamate stream."),
        _T_ETH, _T_TEST],
       [("Integrated ba ang Streamate sa SplitCam?", "Oo — lumalabas ang Streamate sa Add Channel list ng SplitCam; pumili sa halip na manu-manong type ng RTMP URL."),
        ("Saan ang Streamate streaming key?", "SM Connect → tanggapin ang terms → Start Show → isara ang popup → kopyahin ang key."),
        ("Anong bitrate para sa Streamate?", "Hindi nagset ng hard ceiling ang Streamate — gumagana ang 3,500–6,000 Kbps sa 1080p. Adaptive ang stream, kaya normal ang mas mababang bitrate sa static image, hindi bug."),
        ("Libre ba ang SplitCam para sa Streamate?", "Oo — libre, walang watermark at walang time limit; at dahil integrated channel ang Streamate sa SplitCam, walang separate encoder cost.")]),
    _p("streamray", "StreamRay",
       "Mag-broadcast sa StreamRay cam gamit ang SplitCam — Chat URL",
       "Mag-broadcast sa StreamRay cam gamit ang libreng SplitCam — URL na nai-post sa chat, OBS Broadcaster mode, scenes at overlays. Walang watermark.",
       "streamray, streamray cam, streamray broadcast, streamray obs broadcaster, streamray rtmp",
       'Paano mag-broadcast sa <span class="accent">StreamRay</span> gamit ang SplitCam',
       "StreamRay broadcast",
       "URL-in-chat external encoder setup para sa StreamRay.",
       "May hindi pangkaraniwang external encoder setup ang StreamRay — naghahatid ito ng stream URL sa <strong style='color:var(--text)'>chat window ng broadcast</strong> at hindi gumagamit ng separate stream key. Hinahawakan ng libreng <strong style='color:var(--text)'>SplitCam</strong> ang URL-only flow na ito.",
       "Mag-broadcast sa StreamRay gamit ang SplitCam: i-install ang SplitCam, buuin ang scene, sa StreamRay i-activate ang OBS Broadcaster, kopyahin ang stream URL mula sa chat window, i-paste sa SplitCam (iwanang blangko ang key field), Go Live."
       "<ol><li>I-install ang SplitCam.</li><li>Idagdag ang camera + scene.</li><li>Kopyahin ang StreamRay URL mula sa chat.</li><li>I-paste ang URL sa SplitCam.</li><li>Pindutin ang Go Live.</li></ol>",
       "Sa StreamRay double-click ang <strong>Broadcast Now</strong>, buksan ang <strong>Other</strong> menu, piliin ang <strong>OBS Broadcaster</strong> at <strong>Save and Close</strong>. Pagkatapos ay nag-po-post ang StreamRay ng <strong>stream URL sa chat window</strong> — kopyahin mula doon. Iwanang <strong>blangko</strong> ang stream key field ng SplitCam; nag-aauthenticate lang ang StreamRay sa pamamagitan ng URL.",
       [("Nasa chat ang URL", "Hindi pinapakita ng StreamRay ang stream URL sa settings box — nai-post ito sa chat window ng broadcast. Kopyahin mula doon."),
        ("Iwanang blangko ang key field", "Hindi gumagamit ng separate key ang StreamRay — URL lang. Huwag maglagay ng anuman sa SplitCam key field."),
        _T_ETH, _T_TEST],
       [("Saan ang StreamRay stream URL?", "Pagkatapos i-activate ang OBS Broadcaster, nag-po-post ang StreamRay ng URL sa chat window — kopyahin mula sa chat."),
        ("Bakit walang stream key sa StreamRay?", "Nag-aauthenticate lang ang StreamRay sa pamamagitan ng URL — iwanang blangko ang SplitCam key field."),
        ("Anong bitrate para sa StreamRay?", "Hindi nag-de-declare ng opisyal na ceiling ang StreamRay — tumira sa 3,500–6,000 Kbps sa 1080p at patakbuhin ang speed test ng SplitCam, dahil hindi nagbibigay ng bitrate feedback ang URL-only flow."),
        ("Libre ba ang SplitCam para sa StreamRay?", "Oo — libre, walang watermark at walang time limit, na bumabagay sa URL-only flow ng StreamRay: i-paste ang link at ikaw ay live na.")]),
    _p("xlovecam", "XLoveCam",
       "Mag-broadcast sa XLoveCam gamit ang SplitCam — RTMP link & key",
       "Mag-broadcast sa XLoveCam gamit ang libreng SplitCam — RTMP link at key, regional servers, scenes at overlays. Walang watermark.",
       "xlovecam, x love cam, xlovecam broadcast, xlovecam rtmp link, xlovecam stream key",
       'Paano mag-broadcast sa <span class="accent">XLoveCam</span> gamit ang SplitCam',
       "XLoveCam broadcast",
       "RTMP link + key setup para sa XLoveCam.",
       "Ang XLoveCam ay European multilingual cam platform. Ipinapakita ng account settings ang parehong <strong style='color:var(--text)'>RTMP link</strong> at <strong style='color:var(--text)'>stream key</strong> — kinukuha ng libreng <strong style='color:var(--text)'>SplitCam</strong> ang pareho at nag-broadcast na may kumpletong scenes at overlays.",
       "Mag-broadcast sa XLoveCam gamit ang SplitCam: i-install ang SplitCam, buuin ang scene, sa XLoveCam buksan ang <em>My Account → settings</em>, kopyahin ang RTMP link at stream key, i-paste ang pareho sa SplitCam, simulan ang show."
       "<ol><li>I-install ang SplitCam.</li><li>Idagdag ang camera + scene.</li><li>Kopyahin ang RTMP link + key mula sa XLoveCam.</li><li>I-paste pareho sa SplitCam.</li><li>Pindutin ang Go Live.</li></ol>",
       "Sa XLoveCam buksan ang <strong>My Account</strong> → <strong>settings</strong>. Ipinapakita ng settings ang parehong <strong>RTMP link</strong> at <strong>stream key</strong> — kopyahin pareho sa server URL at key fields ng SplitCam, pagkatapos <strong>Start your show</strong> sa XLoveCam.",
       [("Kopyahin ang link AT key", "Nagbibigay ang XLoveCam ng RTMP link AT separate stream key — kailangan mo pareho sa SplitCam, hindi lang isa."),
        ("Multilingual audience", "European at multilingual ang XLoveCam — malinaw na text overlay sa wika mo ay tumutulong sa mga viewers na mahanap ka."),
        ("Piliin ang pinakamalapit na server", "Nag-aalok ang XLoveCam ng regional RTMP servers — Europe, North America, South America at Asia. Ang pinakamalapit ay nagbabawas ng latency at dropped frames."),
        _T_ETH],
       [("Saan ang XLoveCam RTMP data?", "My Account → settings — nagpapakita ng parehong RTMP link at key."),
        ("Sinusuportahan ba ng XLoveCam ang external encoders?", "Oo — nagbibigay ito ng RTMP link at key, kaya gumagana ang SplitCam bilang encoder."),
        ("Anong bitrate para sa XLoveCam?", "Hindi naglalathala ng fixed limit ang XLoveCam; 3,500–6,000 Kbps sa 1080p ang ideal. Ang pagpili ng pinakamalapit na regional server ay pantay-pantay ang importansya — nagbabawas ng dropped frames."),
        ("Libre ba ang SplitCam para sa XLoveCam?", "Oo — libre, walang watermark at walang time limit. Walang gastos sa software para abutin ang multilingual European audience ng XLoveCam.")]),
    _p("soulcams", "SoulCams",
       "Mag-broadcast sa SoulCams gamit ang SplitCam — OBS settings",
       "Mag-broadcast sa SoulCams gamit ang libreng SplitCam — OBS settings, RTMP server at key, multi-camera scenes at overlays.",
       "soul cams, soulcams, soulcams broadcast, soulcams obs, soulcams rtmp, soulcams broadcast",
       'Paano mag-broadcast sa <span class="accent">SoulCams</span> gamit ang SplitCam',
       "SoulCams broadcast",
       "OBS settings para sa SoulCams.",
       "Ang SoulCams ay cam platform na ang OBS settings ay nagpapakita ng <strong style='color:var(--text)'>RTMP server at stream key na magkasama</strong> sa isang window. I-paste pareho sa libreng <strong style='color:var(--text)'>SplitCam</strong> para mag-broadcast na may multi-camera scenes at overlays.",
       "Mag-broadcast sa SoulCams gamit ang SplitCam: i-install ang SplitCam, buuin ang scene, sa SoulCams i-click ang Go Online → Settings → OBS, kopyahin ang server at key, i-paste pareho sa SplitCam, Go Live."
       "<ol><li>I-install ang SplitCam.</li><li>Idagdag ang camera + scene.</li><li>Buksan ang SoulCams Settings → OBS.</li><li>I-paste ang server + key sa SplitCam.</li><li>Pindutin ang Go Live.</li></ol>",
       "Sa SoulCams mag-log in at i-click ang <strong>Go Online</strong>, pagkatapos buksan ang <strong>Settings</strong> → <strong>OBS</strong>. Pinapakita ng OBS window ang <strong>RTMP server</strong> at <strong>stream key</strong> na magkasama — kopyahin pareho sa SplitCam.",
       [("Server at key na magkatabi", "Pinapakita ng SoulCams ang RTMP server at key sa parehong OBS window — kuhanin pareho sa isang galaw."),
        ("Go Online muna", "Lumalabas lang ang OBS settings pagkatapos i-click ang Go Online sa SoulCams — gawin ito bago hanapin ang encoder data."),
        ("I-block ang mga hindi gustong rehiyon", "Pinapayagan ng SoulCams ang geo-blocking sa panig ng modelo — pumili kung anong mga bansa ang hindi makakakita ng stream bago pindutin ang Go Online."),
        _T_ETH, _T_TEST],
       [("Saan ang OBS settings ng SoulCams?", "Mag-log in, i-click ang Go Online, pagkatapos Settings → OBS — ipinapakita nang magkasama ang RTMP server at stream key."),
        ("Sinusuportahan ba ng SoulCams ang external encoders?", "Oo — ang OBS settings ay nagbibigay ng RTMP server at key, kaya gumagana ang SplitCam."),
        ("Anong bitrate para sa SoulCams?", "Hindi nagbibigay ng opisyal na numero ang SoulCams — tumira sa 3,500–6,000 Kbps sa 1080p at subukan ang upload, dahil hindi nagpapakita ng bitrate guidance ang OBS window."),
        ("Libre ba ang SplitCam para sa SoulCams?", "Oo — libre, walang watermark at walang time limit, kaya ang kumpletong SoulCams show na may multi-camera scenes at overlays ay walang gastos sa encoder side.")]),
    _p("imlive", "ImLive",
       "Mag-broadcast sa ImLive gamit ang SplitCam — Virtual camera",
       "Setup ng Im Live stream gamit ang libreng SplitCam — direktang ginagamit ng ImLive ang webcam (walang RTMP), ikonekta ang SplitCam bilang virtual camera na may scenes.",
       "im live stream, imlive splitcam, imlive broadcast, imlive virtual camera, imlive webcam, im live cam",
       'Paano gamitin ang <span class="accent">ImLive</span> gamit ang SplitCam',
       "SplitCam sa ImLive",
       "Virtual camera setup para sa ImLive — walang RTMP.",
       "Direktang ginagamit ng ImLive ang webcam sa browser — <strong style='color:var(--text)'>walang RTMP at walang stream key</strong>. Kumokonekta ang libreng <strong style='color:var(--text)'>SplitCam</strong> bilang <strong style='color:var(--text)'>virtual camera</strong>: buuin ang scene sa SplitCam, pagkatapos piliin ang SplitCam bilang camera sa ImLive.",
       "Gamitin ang SplitCam sa ImLive: i-install ang SplitCam, buuin ang scene na may media layers, buksan ang ImLive at magsimula ng video chat, sa ImLive settings piliin ang SplitCam bilang webcam at microphone."
       "<ol><li>I-install ang SplitCam.</li><li>Buuin ang scene sa SplitCam.</li><li>Magsimula ng video chat sa ImLive.</li><li>Piliin ang SplitCam bilang ImLive camera.</li><li>Simulan ang chat.</li></ol>",
       "Mag-log in sa ImLive site at i-click ang <strong>Start Video Chat</strong>, pagkatapos buksan ang <strong>Go To Settings</strong> para ma-access ang camera at microphone options. Sa ImLive settings piliin ang <strong>SplitCam</strong> bilang webcam at microphone.",
       [("Walang kailangang stream key", "Walang RTMP ang ImLive — huwag maghanap ng server URL o key. Pinipili lang ang SplitCam bilang camera device."),
        ("I-set din ang SplitCam bilang microphone", "Piliin ang SplitCam para sa microphone bukod sa camera, para makapasok din ang audio mix at noise suppression sa live."),
        ("Buuin ang scene bago mag-live", "Pinapakita ng ImLive ang ipinapadala ng SplitCam — ayusin ang layers bago simulan ang chat."),
        _T_TEST],
       [("Gumagamit ba ang ImLive ng RTMP o stream key?", "Hindi — direktang ginagamit ng ImLive ang webcam sa pamamagitan ng browser. Kumokonekta ang SplitCam bilang virtual camera, walang key na kokopyahin."),
        ("Paano pipiliin ang SplitCam sa ImLive?", "Start Video Chat → Go To Settings → piliin ang SplitCam bilang webcam at microphone."),
        ("Maaari ba akong gumamit ng overlays sa ImLive?", "Oo — buuin sa SplitCam scene; pinapakita ng ImLive ang composed result."),
        ("Libre ba ang SplitCam para sa ImLive?", "Oo — libre, walang watermark at walang time limit. Bilang virtual camera para sa ImLive, hindi ito nagdadagdag ng gastos o branding sa video chat mo.")],
       steps=[
           ("I-install ang SplitCam", "Ang SplitCam ay libreng software para sa Windows at macOS. I-install ito — walang watermark, walang sign-up. Para sa ImLive ito ay gumagana bilang <strong>virtual camera</strong>, hindi RTMP encoder."),
           ("Buuin ang scene sa SplitCam", "Buksan ang SplitCam at gamitin ang <strong>Media Layers +</strong> para idagdag ang webcam at anumang overlays, text, filters o AI background. Ang composed scene na ito ang makikita ng ImLive bilang camera mo."),
           ("Magsimula ng video chat sa ImLive", "Mag-log in sa ImLive site at i-click ang <strong>Start Video Chat</strong>, pagkatapos buksan ang <strong>Go To Settings</strong> para ma-access ang camera at microphone options."),
           ("Piliin ang SplitCam bilang camera", "Sa ImLive settings piliin ang <strong>SplitCam</strong> bilang webcam AT bilang microphone. Pinapakita ngayon ng ImLive ang buong SplitCam scene mo sa halip na flat webcam."),
           ("Simulan ang Free Live Chat", "I-click ang <strong>Free Live Chat</strong> sa ImLive para mag-live. Para baguhin ang hitsura sa kalagitnaan ng session, i-edit ang scene sa SplitCam — agad na nag-uupdate ang ImLive."),
       ]),
    _p("vxlive", "VXLive",
       "Mag-broadcast sa VXLive gamit ang SplitCam — Opisyal na suporta",
       "Mag-broadcast sa VXLive (VXModels / VISIT-X) gamit ang libreng SplitCam — opisyal na VISIT-X preset, server at key, scenes. Walang watermark.",
       "vxlive, visit-x, vxmodels splitcam, vxlive broadcast, visit-x stream, vxlive rtmp",
       'Paano mag-broadcast sa <span class="accent">VXLive</span> gamit ang SplitCam',
       "VXLive broadcast",
       "Opisyal na sinusuportahan ng VXLive ang SplitCam (VISIT-X preset).",
       "Ang VXLive (VXModels / VISIT-X) ay cam platform mula sa German market — at isa sa iilan na <strong style='color:var(--text)'>opisyal na sumusuporta sa SplitCam sa pangalan</strong>. May dedicated help article ang VXModels para sa pagkonekta ng <strong style='color:var(--text)'>SplitCam</strong> sa VXLive, at nagbibigay ang SplitCam ng VISIT-X bilang ready-made channel preset.",
       "Mag-broadcast sa VXLive gamit ang SplitCam: i-install ang SplitCam, buuin ang scene, sa VXLive piliin ang «Stream with third-party software», kopyahin ang server URL at key, sa SplitCam piliin ang VISIT-X preset at i-paste, Go Live sa SplitCam, pagkatapos GO ONLINE sa VXLive."
       "<ol><li>I-install ang SplitCam.</li><li>Idagdag ang camera + scene.</li><li>Kunin ang server URL + key mula sa VXLive.</li><li>Piliin ang VISIT-X preset sa SplitCam, i-paste.</li><li>Go Live, pagkatapos GO ONLINE sa VXLive.</li></ol>",
       "Sa VXLive piliin ang <strong>Stream with third-party software</strong> at piliin ang opsyon para sa <strong>OBS, SplitCam o XSplit</strong>. Nagbibigay ang VXLive ng <strong>server URL</strong> at <strong>stream key</strong>. Sa SplitCam piliin ang <strong>VISIT-X</strong> bilang streaming platform, i-paste pareho, pindutin ang <strong>Go Live</strong> sa SplitCam, pagkatapos <strong>GO ONLINE</strong> sa VXLive.",
       [("Integrated preset ang VISIT-X", "Huwag mag-type ng raw RTMP URL — may VISIT-X ang SplitCam sa platform list; pumili lang at i-paste ang server URL at key."),
        ("Two-step go-live", "Sa VXLive pindutin muna ang Go Live sa SplitCam, pagkatapos GO ONLINE sa VXLive — pareho, sa ganitong pagkakasunod-sunod."),
        ("German market", "Karamihan sa audience ng VXLive ay German-speaking — German text overlay o title ay tumutulong na konekta sa viewers."),
        _T_ETH],
       [("Opisyal bang sinusuportahan ng VXLive ang SplitCam?", "Oo — pinapanatili ng VXModels (VXLive) ang dedicated opisyal na help article para sa SplitCam setup at inililista ang SplitCam katabi ng OBS at XSplit bilang sinusuportahang broadcasting software."),
        ("Paano ikokonekta ang SplitCam sa VXLive?", "Sa VXLive piliin ang «Stream with third-party software», pagkatapos sa SplitCam piliin ang VISIT-X preset at i-paste ang server URL at stream key na ibinigay ng VXLive."),
        ("Mag-live ba ako sa SplitCam o sa VXLive?", "Pareho — una Go Live sa SplitCam, pagkatapos GO ONLINE sa VXLive."),
        ("Bakit inirerekomenda ng VXModels ang SplitCam?", "Inirerekomenda ng opisyal na help article ng VXModels ang SplitCam partikular para alisin ang mga webcam image artifacts at pixelation at i-stabilize ang koneksyon — hindi lang bilang generic encoder.")]),
    _p("virtwish", "VirtWish",
       "Mag-broadcast sa VirtWish gamit ang SplitCam — Stream URL & key",
       "Mag-broadcast sa VirtWish gamit ang libreng SplitCam — Profile → Start Broadcast OBS section, stream URL at key, scenes at overlays.",
       "virtwish, virtwish broadcast, virtwish broadcasting software, virtwish rtmp, virtwish stream key, virtwish obs",
       'Paano mag-broadcast sa <span class="accent">VirtWish</span> gamit ang SplitCam',
       "VirtWish broadcast",
       "Stream URL + key setup para sa VirtWish.",
       "Ang VirtWish ay interactive cam platform. Nagbibigay ang broadcast settings ng <strong style='color:var(--text)'>stream URL at separate stream key</strong> sa OBS section — kinukuha ng libreng <strong style='color:var(--text)'>SplitCam</strong> pareho at pinapatakbo ang show na may scenes at overlays.",
       "Mag-broadcast sa VirtWish gamit ang SplitCam: i-install ang SplitCam, buuin ang scene, sa VirtWish buksan ang <em>Profile → Start Broadcast</em> hanggang sa OBS section, kopyahin ang link at key, i-paste pareho sa SplitCam, Go Live."
       "<ol><li>I-install ang SplitCam.</li><li>Idagdag ang camera + scene.</li><li>Kunin ang URL + key mula sa VirtWish.</li><li>I-paste pareho sa SplitCam.</li><li>Pindutin ang Go Live.</li></ol>",
       "Sa VirtWish i-click ang icon sa top right corner → <strong>Profile</strong> → <strong>Start Broadcast</strong>, pagkatapos <strong>Start Broadcast</strong> ulit para makarating sa OBS section. <strong>Kopyahin ang link sa unang linya</strong> sa Stream URL field ng SplitCam, at ang <strong>Stream Key</strong> na hiwalay sa key field.",
       [("Link sa unang linya", "Inilalagay ng OBS section ng VirtWish ang stream URL sa unang linya — kopyahin sa SplitCam Stream URL, pagkatapos ang separate key."),
        ("Dalawang click sa Start Broadcast", "I-click ang Start Broadcast nang dalawang beses sa VirtWish para makarating sa OBS section — inaasahan, hindi bug."),
        _T_ETH, _T_TEST],
       [("Saan ang VirtWish RTMP data?", "Icon sa taas-kanan → Profile → Start Broadcast dalawang beses → ang OBS section ay nagpapakita ng link at stream key."),
        ("Sinusuportahan ba ng VirtWish ang external encoders?", "Oo — nagbibigay ang OBS section ng stream URL at key, kaya gumagana ang SplitCam."),
        ("Anong bitrate para sa VirtWish?", "Hindi naglalathala ng opisyal na ceiling ang VirtWish; 3,500–6,000 Kbps sa 1080p ay ligtas. Itugma ang resolution ng SplitCam sa nakaset sa VirtWish para maiwasan ang rescaling."),
        ("Libre ba ang SplitCam para sa VirtWish?", "Oo — libre, walang watermark at walang time limit. Ang URL-and-key setup ng VirtWish ay nagkakahalaga lamang ng ilang minuto na kinakailangan.")]),
    _p("xmodels", "XModels",
       "Mag-broadcast sa XModels gamit ang SplitCam — Libreng gabay",
       "Mag-broadcast sa XModels gamit ang libreng SplitCam — external encoder option sa model account settings, RTMP key, scenes at overlays.",
       "xmodels, xmodels broadcast, xmodels broadcasting software, xmodels rtmp, xmodels external encoder",
       'Paano mag-broadcast sa <span class="accent">XModels</span> gamit ang SplitCam',
       "XModels broadcast",
       "External encoder setup para sa XModels streams.",
       "Ang XModels ay cam-streaming platform na may built-in na <strong style='color:var(--text)'>external encoder option</strong> sa model account settings. Nag-broadcast ang libreng <strong style='color:var(--text)'>SplitCam</strong> doon na may multi-camera scenes, overlays at filters sa halip na isang flat camera.",
       "Mag-broadcast sa XModels gamit ang SplitCam: i-install ang SplitCam, buuin ang scene, sa XModels model account i-activate ang external encoder option, kopyahin ang server URL at stream key, i-paste sa SplitCam, Go Live."
       "<ol><li>I-install ang SplitCam.</li><li>Idagdag ang camera + scene.</li><li>I-activate ang external encoder sa XModels settings.</li><li>I-paste ang server URL + key sa SplitCam.</li><li>Pindutin ang Go Live.</li></ol>",
       "Sa XModels <strong>model account settings</strong>, i-activate ang <strong>broadcast via external encoder</strong> option. Nagbibigay ang XModels ng <strong>stream key</strong> — kopyahin sa SplitCam. Kung wala ang opsyon kung saan inaasahan mo, ang XModels support ay sa pamamagitan ng FAQ chat sa site at <strong>info@xmodels.com</strong>; ipinapakita rin ito ng video sa itaas.",
       [("Nasa account settings ito", "Inilalagay ng XModels ang external encoder option sa model account settings, hindi sa hiwalay na broadcast screen."),
        ("Support: chat + email", "Walang malaking public help center ang XModels — ang site FAQ chat at info@xmodels.com ang opisyal na support channels."),
        ("I-stack ang overlays sa SplitCam", "Tip goals, pangalan at social handles bilang scene layers — hindi ito idinadagdag ng basic camera ng XModels."),
        _T_ETH],
       [("Sinusuportahan ba ng XModels ang external encoders?", "Oo — ang model account settings ay may kasamang external encoder broadcast option na nagbibigay ng stream key, kaya gumagana ang SplitCam."),
        ("Saan ako kukuha ng XModels help?", "Ang XModels support ay sa pamamagitan ng FAQ chat sa site at email info@xmodels.com — walang malaking public help center."),
        ("Anong bitrate para sa XModels?", "Walang dokumentadong opisyal na numero ang XModels — gamitin ang 3,500–6,000 Kbps sa 1080p at patakbuhin ang speed test ng SplitCam, dahil ang XModels support ay chat at email lamang."),
        ("Libre ba ang SplitCam para sa XModels?", "Oo — libre, walang watermark at walang time limit, kaya ang broadcasting sa European network ng XModels ay walang dagdag na gastos sa software.")]),
    _p("flirt4free", "Flirt4Free",
       "Mag-broadcast sa Flirt for Free cam gamit ang SplitCam — Libreng gabay",
       "Mag-broadcast sa Flirt for Free cam gamit ang libreng SplitCam — External Broadcast Form, RTMP URL at Stream Name, scenes at overlays.",
       "flirt for free cam, flirt 4 free cam, flirt4free, flirt4free broadcast, flirt4free external broadcast, flirt4free rtmp",
       'Paano mag-broadcast sa <span class="accent">Flirt4Free</span> gamit ang SplitCam',
       "Flirt4Free broadcast",
       "External Broadcast Form setup para sa Flirt4Free.",
       "Ang Flirt4Free ay isa sa pinakamatandang cam platforms, nag-aair simula noong 90s. Opisyal nitong sinusuportahan ang external broadcasting sa pamamagitan ng <strong style='color:var(--text)'>External Broadcast Form</strong> — nagpapadala ang libreng <strong style='color:var(--text)'>SplitCam</strong> ng stream habang nag-set ang form ng resolution at bitrate.",
       "Mag-broadcast sa Flirt4Free gamit ang SplitCam: i-install ang SplitCam, buuin ang scene, buksan ang Flirt4Free External Broadcast Form, kopyahin ang RTMP URL at Stream Name at i-set ang resolution/bitrate, i-paste sa SplitCam, Go Live."
       "<ol><li>I-install ang SplitCam.</li><li>Idagdag ang camera + scene.</li><li>Buksan ang Flirt4Free External Broadcast Form.</li><li>I-paste ang RTMP URL + Stream Name sa SplitCam.</li><li>Pindutin ang Go Live.</li></ol>",
       "Sa Flirt4Free model area buksan ang <strong>External Broadcast Form</strong>. Hindi tulad ng karamihan ng cam sites, nagbibigay ang Flirt4Free ng <strong>RTMP URL</strong> at <strong>Stream Name</strong> (hindi «key»), at saka resolution at bitrate fields na pinupunan mo sa form mismo. Kopyahin ang URL at Stream Name sa server at key fields ng SplitCam.",
       [("Stream Name ito, hindi key", "Tinatawag ng Flirt4Free ang credential bilang Stream Name. I-paste mo ito sa SplitCam stream key field — parehong tungkulin."),
        ("I-set ang resolution/bitrate sa form", "Ang External Broadcast Form ng Flirt4Free ay may sariling resolution at bitrate fields — i-align sa SplitCam settings para hindi ma-rescale ang image."),
        ("Historikal na platform", "Tumatakbo ang Flirt4Free simula noong 90s — mature ang model tools, at ang External Broadcast Form ay documented bahagi nito."),
        _T_ETH],
       [("Sinusuportahan ba ng Flirt4Free ang external encoders?", "Oo — opisyal, sa pamamagitan ng External Broadcast Form, na nagbibigay ng RTMP URL at Stream Name. Gumagana ang SplitCam bilang encoder."),
        ("Saan ako kukuha ng Flirt4Free RTMP data?", "Mula sa External Broadcast Form sa model area — nagpapakita ng RTMP URL, Stream Name at resolution/bitrate fields."),
        ("Anong bitrate para sa Flirt4Free?", "3,500–6,000 Kbps sa 1080p — i-set ang parehong halaga sa External Broadcast Form at sa SplitCam."),
        ("Libre ba ang SplitCam para sa Flirt4Free?", "Oo — libre, walang watermark at walang time limit, na bumabagay sa historikal na platform tulad ng Flirt4Free kung saan ang shows ay maaaring mahaba.")]),
    _p("mfc-alerts", "MFC Alerts",
       "Idagdag ang MFC Alerts sa stream gamit ang SplitCam",
       "Ipakita ang mga animated na tip alerts sa MyFreeCams stream — mfcalerts.com URL bilang Browser layer sa libreng SplitCam, sa itaas ng webcam.",
       "mfc alerts, myfreecams alerts, idagdag ang mfc alerts, mfcalerts splitcam, myfreecams tip alerts, myfreecams alerts overlay",
       'Paano idagdag ang <span class="accent">MFC Alerts</span> sa stream',
       "Idagdag ang MFC Alerts",
       "Ipakita ang mga animated na tip alerts sa MyFreeCams stream.",
       "Ipinapakita ng MFC Alerts ang mga animated effects sa MyFreeCams stream mo tuwing nagpapadala ng tip ang viewer. Tumatakbo ito bilang <strong style='color:var(--text)'>Browser layer</strong> sa loob ng libreng <strong style='color:var(--text)'>SplitCam</strong> — i-set up minsan at ang mga tips ay nag-tritrigger ng on-screen reactions live.",
       "Magdagdag ng MFC Alerts gamit ang SplitCam: i-install ang SplitCam, idagdag ang webcam, buksan ang Browser tab at i-load ang mfcalerts.com, kopyahin ang alerts URL, idagdag bilang Browser layer sa itaas ng webcam, pagkatapos test gamit ang test tip."
       "<ol><li>I-install ang SplitCam.</li><li>Idagdag ang webcam.</li><li>Kunin ang URL sa mfcalerts.com.</li><li>Idagdag bilang Browser layer sa itaas ng webcam.</li><li>Magpadala ng test tip.</li></ol>",
       "Sa SplitCam buksan ang <strong>Browser</strong> tab at mag-navigate sa <strong>www.mfcalerts.com</strong>. Mag-log in o mag-register. Gamitin ang <strong>Copy to clipboard</strong> para kopyahin ang personal na alerts URL. I-paste ang URL sa Browser window ng SplitCam at i-click ang <strong>Add</strong>. Pagkatapos i-reorder ang source list para ang <strong>MFC Alerts ay nasa itaas ng webcam</strong> (3-dot menu → Move Up).",
       [("Kailangan nasa itaas ng webcam ang MFC Alerts", "Pinakakaraniwang pagkakamali: kung ang MFC Alerts layer ay nasa ibaba ng webcam sa source list, mananatiling nakatago ang mga effects. Itaas."),
        ("Kailangan ang mfcalerts.com account", "Personal ang alerts URL — mag-register sa mfcalerts.com muna kung walang account."),
        ("Magpadala ng test tip bago mag-live", "Gamitin ang Settings → Send test tip para kumpirmahin na gumagana ang overlay — huwag mag-discover ng error sa kalagitnaan ng show."),
        _T_ETH],
       [("Ano ang MFC Alerts?", "Notification system para sa MyFreeCams na nagpapakita ng video effects sa stream mo kapag nagpapadala ng tips ang viewers — idinadagdag bilang Browser overlay sa SplitCam."),
        ("Bakit hindi lumalabas ang MFC Alerts ko?", "Halos palaging layer order — kailangan ang MFC Alerts Browser layer ay nasa itaas ng webcam sa source list ng SplitCam."),
        ("Kailangan ko ba ng account para sa MFC Alerts?", "Oo — mag-register sa mfcalerts.com para makuha ang personal na alerts URL."),
        ("Libre ba ang SplitCam para dito?", "Oo — libre ang SplitCam, walang watermark at walang time limit, at tumatakbo ang MFC Alerts browser overlay sa loob nang walang dagdag na gastos.")],
       steps=[
           ("I-install ang SplitCam at idagdag ang webcam", "I-install ang libreng SplitCam para sa Windows o macOS, pagkatapos idagdag ang <strong>webcam</strong> bilang source. Nakaupo ang MFC Alerts bilang layer sa itaas ng camera na ito."),
           ("Buksan ang Browser tab at pumunta sa mfcalerts.com", "Sa SplitCam buksan ang <strong>Browser</strong> tab at mag-navigate sa <strong>www.mfcalerts.com</strong>. Mag-log in, o mag-register kung wala kang mfcalerts.com account pa."),
           ("Kopyahin ang alerts URL", "Sa mfcalerts.com gamitin ang <strong>Copy to clipboard</strong> para kopyahin ang personal na alerts URL — ito ang page na nagre-render ng tip animations."),
           ("Idagdag ang URL bilang Browser layer — sa itaas ng webcam", "I-paste ang URL sa Browser window ng SplitCam at i-click ang <strong>Add</strong>. Pagkatapos i-reorder ang source list para ang <strong>MFC Alerts ay nasa itaas ng webcam</strong> (3-dot menu → Move Up). Kung nasa ibaba, mananatiling nakatago ang mga effects."),
           ("Test gamit ang test tip", "Buksan ang <strong>Settings → Send test tip</strong> at kumpirmahin na lumalabas ang alert effect sa itaas ng camera mo. Pagkatapos mag-broadcast nang normal sa MyFreeCams — ang mga tunay na tips ay nag-tritrigger na ngayon ng animations."),
       ]),
    _p("lovense", "Lovense",
       "Magdagdag ng Lovense toy sa stream gamit ang SplitCam",
       "Ikonekta ang interactive Lovense toy sa cam stream gamit ang libreng SplitCam — Lovense SplitCam Toolset, on-screen tip alerts, reactions.",
       "idagdag ang lovense sa stream, lovense cam stream, lovense splitcam, lovense splitcam toolset, lovense interactive toy streaming",
       'Paano magdagdag ng <span class="accent">Lovense toy</span> sa stream',
       "Magdagdag ng Lovense toy",
       "Ikonekta ang interactive Lovense toy sa cam stream.",
       "Pinapatakbo mo ang cam stream sa pamamagitan ng libreng <strong style='color:var(--text)'>SplitCam</strong> at ipinapares ang <strong style='color:var(--text)'>Lovense</strong> toy na tumutugon sa tokens. Idinodokumento ng Lovense ang opisyal na <strong style='color:var(--text)'>Lovense SplitCam Toolset</strong>, at nagbibigay ang SplitCam ng opisyal na Lovense plugin — sinusuportahan ang integration mula sa parehong panig.",
       "Para magdagdag ng Lovense toy sa stream: i-install ang SplitCam at Lovense software, i-pair ang toy, i-link ang Lovense sa cam platform, idagdag ang Lovense status bilang Browser layer sa SplitCam, pagkatapos mag-broadcast nang normal."
       "<ol><li>I-install ang SplitCam.</li><li>I-install ang Lovense software at i-pair ang toy.</li><li>I-link ang Lovense sa cam site.</li><li>Idagdag ang Lovense overlay sa SplitCam.</li><li>Pindutin ang Go Live.</li></ol>",
       "I-install ang Lovense Connect / Lovense Stream (opisyal na desktop app). I-on ang toy at i-pair sa pamamagitan ng Bluetooth para magpakita ang app na connected. Sa Lovense app i-link ang cam account para tumugon ang toy sa viewer tokens / tips. Nagbibigay ang Lovense ng overlay / widget URL — idagdag bilang <strong>Browser</strong> layer sa SplitCam scene.",
       [("Gamitin ang opisyal na Lovense SplitCam Toolset", "Naglalathala ang Lovense ng SplitCam-specific toolset na may sariling installation guide — nagdadagdag ng toy activity overlay at tip alerts na ginawa para sa SplitCam."),
        ("I-update ang Lovense Cam Extension", "Nangangailangan ang toolset ng recent Lovense Cam Extension (30.1.4 o mas bago) — i-update bago mag-live."),
        ("Panatilihing naka-charge ang toy", "Halos walang baterya sa kalagitnaan ng show ay pumapatay sa interactive side — i-charge nang buo bago mag-live."),
        ("Subukan ang reaction sa tokens", "Magpadala ng maliit na test tip para kumpirmahin na tumutugon ang toy bago buksan ang room."),
        ("Suriin ang version requirements", "Nangangailangan ng SplitCam 10.4.5 o mas bago ang Lovense SplitCam Toolset. Sinasaklaw ng Lovense Cam Extension ang Chaturbate, Stripchat, BongaCams, MyFreeCams at CamSoda nang opisyal — para sa anumang ibang site, gamitin ang Generic URL integration ng Lovense.")],
       [("Opisyal bang sinusuportahan ng Lovense ang SplitCam?", "Oo — idinodokumento ng Lovense ang opisyal na «Lovense SplitCam Toolset» na may sariling installation guide, at nagbibigay ang SplitCam ng opisyal na Lovense plugin. Sinusuportahan ang integration mula sa parehong panig."),
        ("Direktang kumokonekta ba ang toy sa SplitCam?", "Hindi — ipinapares ang toy sa Lovense app; ipinapakita ng SplitCam ang Lovense overlay at nag-bo-broadcast ng camera."),
        ("Anong cam sites ang sumusuporta sa Lovense?", "Sinusuportahan ng Lovense Cam Extension ang Chaturbate, Stripchat, BongaCams, MyFreeCams at CamSoda nang opisyal, na may varying support para sa iba — suriin ang kasalukuyang listahan sa Lovense app."),
        ("Maaari ko bang ipakita ang mga kamakailang tips sa screen?", "Oo — idagdag ang Lovense widget URL bilang Browser layer sa SplitCam.")],
       steps=[
           ("I-install ang SplitCam", "Ang SplitCam ay libreng streaming software para sa Windows at macOS — ang encoder na nagpapadala ng video mo sa cam platform. I-install; walang watermark."),
           ("I-install ang Lovense software at i-pair ang toy", "I-install ang Lovense Connect / Lovense Stream (opisyal na desktop app). I-on ang toy at i-pair sa pamamagitan ng Bluetooth para magpakita ang app na connected."),
           ("I-link ang Lovense sa cam platform", "Sa Lovense app i-link ang cam account para tumugon ang toy sa viewer tokens / tips. Sinusuportahan ang karamihan ng major cam platforms."),
           ("Idagdag ang Lovense overlay sa SplitCam", "Nagbibigay ang Lovense ng overlay / widget URL. Idagdag bilang <strong>Browser</strong> layer sa SplitCam scene para makita ng viewers ang toy status at recent tips on screen."),
           ("Buuin ang scene at Go Live", "Idagdag ang camera at iba pang overlays, i-paste ang cam platform RTMP key sa SplitCam at i-click ang <strong>Go Live</strong>. Tumutugon ang toy sa tips in real time."),
       ]),
    _p("multistream-cams", "Maramihang cam sites",
       "Mag-broadcast sa maramihang cam sites nang sabay-sabay gamit ang SplitCam",
       "Mag-broadcast sa MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat at higit pa nang sabay-sabay gamit ang libreng multistreaming ng SplitCam. Isang click, walang watermark.",
       "broadcast sa maramihang cam sites, multistream cam sites, broadcast sa chaturbate at bongacams nang sabay-sabay, multistream cam software",
       'Paano mag-broadcast sa <span class="accent">maramihang cam sites</span> nang sabay-sabay',
       "Cam multistreaming",
       "Mag-broadcast sa maramihang cam sites nang sabay-sabay.",
       "Maaaring mag-broadcast ang libreng <strong style='color:var(--text)'>SplitCam</strong> ng isang encoding sa <strong style='color:var(--text)'>maramihang cam sites nang sabay-sabay</strong> — MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat at higit pa. Walang watermark, isang click.",
       "Para mag-broadcast sa maramihang cam sites nang sabay-sabay: i-install ang SplitCam, buuin ang scene, kunin ang RTMP server URL at stream key ng bawat cam site, idagdag lahat sa multistreaming settings ng SplitCam, i-click ang Go Live nang minsan."
       "<ol><li>I-install ang SplitCam.</li><li>Idagdag ang camera + scene.</li><li>Kunin ang RTMP key mula sa bawat cam site.</li><li>Idagdag lahat ng keys sa SplitCam multistream.</li><li>Pindutin ang Go Live nang minsan.</li></ol>",
       "Sa bawat cam platform i-activate ang external / RTMP broadcasting at kopyahin ang <strong>server URL</strong> at <strong>stream key</strong>. Sa SplitCam buksan ang <strong>Stream Settings</strong> at idagdag ang bawat cam site bilang custom RTMP destination — i-paste ang server URL at key. I-check lahat ng gusto mong i-live. Pindutin ang <strong>Go Live</strong>.",
       [("Bantayan ang upload mo", "Pinaparami ng multistreaming ang upload load. Ang bawat destination ay gumagamit ng sariling bitrate — siguraduhing kaya ng koneksyon mo ang kabuuan."),
        ("Suriin ang patakaran ng platform", "Ang ilang cam sites ay nagbabawal ng sabay-sabay na broadcasting sa ibang lugar — kumpirmahin bago mag-multistream."),
        ("Cable — hindi mo kayang tiisin ang drops dito", "Pinaparami ng multistreaming ang upload load, kaya ang isang wi-fi drop ay maaaring pumatay sa lahat ng destinations nang sabay-sabay. Hindi opsyonal ang cable dito."),
        ("Bantayan ang health monitor", "Pinapakita ng SplitCam ang status sa bawat destination — i-drop ang isang site kung hindi kaya ng upload.")],
       [("Libre ba ang SplitCam multistreaming?", "Oo — built-in at libre ang multistreaming, walang per-destination fee, walang watermark."),
        ("Ilang cam sites ang puwede kong i-broadcast nang sabay-sabay?", "Kasingdami ng kaya ng upload bandwidth mo — ang bawat destination ay gumagamit ng sariling bitrate."),
        ("Gumagamit ba ito ng cloud relay?", "Hindi — nagpapadala ang SplitCam ng streams peer-to-peer direkta mula sa PC patungo sa ingest ng bawat platform."),
        ("Pinabagal ba ng multistreaming ang PC ko?", "Ginagawa nang minsan ang encoding at na-reuse; pinananatiling mababa ng hardware encoding ang CPU load. Ang upload bandwidth ang totoong limit.")],
       steps=[
           ("I-install ang SplitCam", "Ang SplitCam ay libreng streaming software para sa Windows at macOS na may built-in na multistreaming. I-install — walang watermark, walang sign-up."),
           ("I-set up ang camera at scene", "Buksan ang SplitCam, idagdag ang webcam at buuin ang scene na may overlays at filters. Isang scene ang nag-fi-feed sa bawat destination."),
           ("Kunin ang RTMP key mula sa bawat cam site", "Sa bawat cam platform i-activate ang external / RTMP broadcasting at kopyahin ang <strong>server URL</strong> at <strong>stream key</strong>. Ulitin para sa bawat site na gusto mong i-broadcast — tingnan ang mga indibidwal na platform guide para sa tamang ruta."),
           ("Idagdag ang bawat destination sa SplitCam", "Buksan ang <strong>Stream Settings</strong> at idagdag ang bawat cam site bilang custom RTMP destination — i-paste ang server URL at key. I-check lahat ng gusto mong i-live."),
           ("I-click ang Go Live nang minsan", "Pindutin ang <strong>Go Live</strong>. Nagpapadala ang SplitCam ng stream sa bawat napiling cam site nang sabay-sabay, peer-to-peer, mula sa isang encoding — walang dagdag na bayad."),
       ]),
    _p("livejasmin", "LiveJasmin",
       "Mag-broadcast sa LiveJasmin gamit ang SplitCam — HD external encoder",
       "Mag-broadcast sa LiveJasmin gamit ang libreng SplitCam — Model Center external encoder, HD 1080p setup, multi-camera scenes at overlays. Walang watermark, walang sign-up.",
       "livejasmin broadcast, livejasmin obs, livejasmin external encoder, livejasmin rtmp, livejasmin stream key, livejasmin model setup",
       'Paano mag-broadcast sa <span class="accent">LiveJasmin</span> gamit ang SplitCam',
       "LiveJasmin broadcast",
       "External encoder setup para sa HD-only Model Center ng LiveJasmin.",
       "Ang LiveJasmin ang flagship ng Docler Holding — isa sa pinakamalalaking cam networks sa mundo at HD-only platform. Ang inirerekomendang broadcaster ay ang sariling <strong>JasminCAM</strong> client, pero binubuksan din ng Model Center ang standard na <strong>External Encoder</strong> path — ang libreng <strong style='color:var(--text)'>SplitCam</strong> ay kumokonekta dito, na nagbibigay-daan sa iyong mag-stream gamit ang multi-camera scenes, beauty filters at overlays sa parehong HD stream.",
       "Mag-broadcast sa LiveJasmin gamit ang SplitCam: i-install ang SplitCam, buuin ang HD scene, sa Model Center pumunta sa <em>Settings → Broadcast → External Encoder</em>, kopyahin ang server URL at stream key, i-paste sa SplitCam, Go Live."
       "<ol><li>I-install ang SplitCam.</li><li>Idagdag ang camera + HD scene.</li><li>Kunin ang URL at stream key mula sa Model Center.</li><li>I-paste sa SplitCam.</li><li>Pindutin ang Go Live.</li></ol>",
       "Mag-log in sa <strong>modelcenter.livejasmin.com</strong>, buksan ang <strong>Settings → Broadcast → External Encoder</strong>. Inilalantad ng Model Center ang <strong>server URL</strong> at <strong>stream key</strong> na nakatali sa account mo — kopyahin pareho sa custom RTMP fields ng SplitCam. <strong>Tandaan:</strong> kailangang ma-approve muna ang mga bagong account (48–72 oras) bago lumabas ang External Encoder option, at ipinapatupad ng platform ang HD-only output.",
       [("HD o ma-derank ka", "HD-only ang LiveJasmin — anumang nasa baba ng 1280×720 ay nanganganib na ipakita lamang sa mas mababang-bayad na listahan, sa baba ng 1080p ay mawawala ang 'Premium' eligibility. Itutok sa 1920×1080 sa 30 fps, 4,000–6,000 Kbps."),
        ("JasminCAM vs external encoder", "Ang sariling JasminCAM client ng Docler ang nagbibigay ng pinakamalinis na HD compliance, pero ang external encoders (OBS, SplitCam, vMix) ay opisyal na suportado kapag na-approve na ang account mo — binubuksan nila ang multi-camera scenes at overlays na hindi kayang gawin ng JasminCAM."),
        ("Free chat ≠ private show", "Ang free chat ay preview lang — walang kahubaran. Ang Private at Gold shows ang kinikitaan ng model. I-plano ang scene mo na mukhang matibay parehong nakadamit AT sa show mode."),
        _T_ETH],
       [("Opisyal bang sinusuportahan ng LiveJasmin ang external encoders tulad ng SplitCam?", "Oo — kasama sa Model Center ang External Encoder option sa Settings → Broadcast. Ang JasminCAM ang inirerekomendang client, pero ang OBS, SplitCam at iba pang RTMP encoders ay tahasang nakalista bilang suportado kapag na-approve na ang model account mo."),
        ("Saan ko kukunin ang LiveJasmin stream key ko?", "Sa loob ng Model Center: Settings → Broadcast → External Encoder. Lumalabas doon ang server URL at unique stream key — kopyahin pareho sa custom RTMP fields ng SplitCam. Nakatali ang key sa account mo; tratuhin tulad ng password."),
        ("Anong bitrate para sa LiveJasmin?", "HD-only ang LiveJasmin — itutok sa 1920×1080 sa 30 fps, 4,000–6,000 Kbps na may 2-second keyframe interval. Kung mas mababa ng kapansin-pansin, mawawala ang Premium label at ma-derank ka."),
        ("Libre ba ang SplitCam para sa LiveJasmin?", "Oo — libre ang SplitCam, walang watermark at walang time limit. Ang tanging 'gastos' ay ang pag-abot sa HD requirements ng LiveJasmin, na natively kayang gawin ng SplitCam sa pamamagitan ng 1080p scene composition at beauty filters.")],
       steps=[
           ("I-download at i-install ang SplitCam", "Ang SplitCam ay libreng live-streaming software para sa Windows at macOS — walang sign-up, walang card, walang watermark. Ito ang encoder na nagpapadala ng HD video mo sa LiveJasmin."),
           ("Buuin ang HD scene mo", "Buksan ang SplitCam at idagdag ang webcam mo sa 1080p mode. Maglagay ng overlays, text, second camera o telepono, beauty filters o AI background — humihingi ng HD quality ang LiveJasmin at kailangang mukhang premium ang ginawa mong scene sa buong free chat AT private shows."),
           ("Kunin ang LiveJasmin URL at stream key mo", "Mag-log in sa <strong>modelcenter.livejasmin.com</strong> (kailangang ma-approve muna ang account mo — karaniwan 48–72 oras pagkatapos mag-sign up). Buksan ang <strong>Settings → Broadcast → External Encoder</strong>. Inilalantad ng pahina ang <strong>server URL</strong> at unique na <strong>stream key</strong>. Kopyahin pareho."),
           ("I-connect ang SplitCam sa LiveJasmin", "Sa SplitCam buksan ang <strong>Stream Settings</strong>, i-paste ang LiveJasmin server URL at stream key sa custom RTMP fields. Itakda ang bitrate sa 4,000–6,000 Kbps sa 1920×1080, 30 fps, na may 2-second keyframe. Patakbuhin muna ang built-in speed test — humihingi ng bandwidth ang HD streams."),
           ("I-click ang Go Live", "Pindutin ang <strong>Go Live</strong> sa SplitCam, pagkatapos mag-online sa LiveJasmin Model Center. Sa loob ng ~10 segundo aabot sa network ng LiveJasmin ang HD feed mo. Ang mga sumusunod na broadcasts ay isang click lang — buksan ang SplitCam, Go Live, pagkatapos mag-online sa LiveJasmin."),
       ]),
    _p("myfreecams", "MyFreeCams",
       "Paano mag-broadcast sa MyFreeCams (MFC) gamit ang SplitCam — Model Web Broadcaster bypass",
       "Mag-broadcast sa MyFreeCams gamit ang libreng SplitCam — Model Admin external broadcaster, token economy ng MFC, multi-camera scenes, overlays. Walang watermark, walang sign-up.",
       "myfreecams broadcast, mfc external broadcaster, myfreecams obs, mfc rtmp, mfc stream key, model admin, mfc token",
       'Paano mag-broadcast sa <span class="accent">MyFreeCams</span> gamit ang SplitCam',
       "MyFreeCams broadcast",
       "External broadcaster setup para sa token-based Model Admin ng MFC.",
       "Ang MyFreeCams (MFC) ay isa sa mga pinakamatandang cam platforms — purong token economy, walang gauntlet ng model approval, at isang loyal na Premium-member base. Ang default Model Web Broadcaster ay single-camera browser tool, pero binubuksan din ng Model Admin ang opsyong <strong>External Broadcaster</strong> na kinokonekta ng libreng <strong style='color:var(--text)'>SplitCam</strong> — binubuksan nito ang multi-camera scenes, overlays, at filters sa parehong token stream.",
       "Mag-broadcast sa MFC gamit ang SplitCam: i-install ang SplitCam, buuin ang scene, Model Admin → Broadcaster, lumipat mula Web Broadcaster sa External Broadcaster, kopyahin ang server URL at key, i-paste sa SplitCam, Go Live."
       "<ol><li>I-install ang SplitCam.</li><li>Buuin ang scene.</li><li>Model Admin → Broadcaster, lumipat sa External Broadcaster.</li><li>Kopyahin ang URL + key, i-paste sa SplitCam.</li><li>Pindutin ang Go Live.</li></ol>",
       "Mag-log in sa MyFreeCams, buksan ang <strong>Model Admin → Broadcaster</strong>, lumipat mula <strong>Web Broadcaster</strong> patungo sa <strong>External Broadcaster</strong>. Ipinapakita ng pahina ang <strong>server URL</strong> (<strong>rtmp://publish.myfreecams.com…</strong>) at <strong>stream key</strong> na nakatali sa model account — kopyahin pareho sa custom RTMP fields ng SplitCam. Nakatali ang key sa account.",
       [("Purong tipping/token economy ang MFC", "Hindi subscription model ang MFC — purong tips at tokens ito. I-plano ang scene mo para suportahan ang tip flow: on-screen goal counters, tip menus, at malinaw na call-to-action."),
        ("Web Broadcaster vs External — pumili minsan", "Sa Model Admin → Broadcaster pumili ka ng Web Broadcaster (isang camera, browser) o External Broadcaster (RTMP). Lumipat sa External bago ka mag-go live — dito kumokonekta ang SplitCam, OBS, at vMix."),
        ("Idagdag ang MFC Alerts bilang Browser layer", "Idagdag ang <strong>mfcalerts.com</strong> URL bilang Browser layer sa SplitCam sa ibabaw ng camera — lumalabas real-time sa ibabaw ng broadcast ang tip alerts, goal bars, at notifications, na nag-uudyok sa members na mag-contribute."),
        _T_ETH],
       [("Sinusuportahan ba ng MFC ang external encoders tulad ng SplitCam?", "Oo — sa pamamagitan ng External Broadcaster sa Model Admin. Opisyal na gumagana ang standard RTMP broadcast sa OBS, SplitCam, at vMix; piliin lang ang External Broadcaster (sa halip na Web Broadcaster) sa Model Admin → Broadcaster."),
        ("Saan ko kukunin ang MFC stream key ko?", "Sa loob ng Model Admin → Broadcaster → External Broadcaster. Ipinapakita ng pahina ang server URL na nakaturo sa <strong>publish.myfreecams.com</strong> at stream key na nakatali sa model account — i-paste pareho sa custom RTMP fields ng SplitCam."),
        ("Anong bitrate para sa MFC?", "Sinusuportahan ng MFC ang hanggang ~6,000 Kbps na may 2-second keyframe push. Itutok sa 1920×1080 sa 30 fps, 3,500–6,000 Kbps — panatilihin ito sa pinakamataas na kayang i-handle ng koneksyon mo; sensitibo sa HD quality ang Premium base."),
        ("Libre ba ang SplitCam para sa MFC?", "Oo — libre ang SplitCam, walang watermark, walang time limit. Pwede mong ipadala ang multi-camera, beauty filters, at MFC Alerts overlay sa MFC sa pamamagitan ng External Broadcaster path.")],
       steps=[
           ("I-install ang SplitCam", "Ang SplitCam ay libreng live-streaming software para sa Windows at macOS — walang sign-up, walang card, walang watermark. Ito ang encoder na nagpapadala ng broadcast mo sa RTMP endpoint ng MFC."),
           ("Buuin ang scene mo", "Sa SplitCam idagdag ang webcam mo, maglagay ng overlays, beauty filters, at second camera. Idagdag ang <strong>mfcalerts.com</strong> bilang Browser layer sa ibabaw ng camera — lumalabas real-time sa ibabaw ng stream mo ang tip alerts at goal bars."),
           ("Model Admin → Broadcaster → External Broadcaster", "Mag-log in sa MyFreeCams, buksan ang <strong>Model Admin → Broadcaster</strong> at lumipat mula <strong>Web Broadcaster</strong> patungo sa <strong>External Broadcaster</strong>. Ipinapakita ng pahina ang server URL na nakaturo sa <strong>publish.myfreecams.com</strong> at unique account stream key — kopyahin pareho."),
           ("I-connect ang SplitCam sa MFC", "Sa SplitCam buksan ang <strong>Stream Settings</strong>, i-paste ang MFC server URL at stream key sa custom RTMP fields. Itakda ang bitrate sa 3,500–6,000 Kbps sa 1920×1080, 30 fps, na may 2-second keyframe."),
           ("I-click ang Go Live", "Pindutin ang <strong>Go Live</strong> sa SplitCam — natatanggap ng MFC ang stream sa loob ng ilang segundo at live na ang room mo sa token economy. Ang sumusunod na broadcasts ay isang click lang."),
       ]),
    _p("cherry-tv", "Cherry.tv",
       "Paano mag-broadcast sa Cherry.tv gamit ang SplitCam — Web3-friendly external encoder",
       "Mag-broadcast sa Cherry.tv gamit ang libreng SplitCam — Streamer Dashboard external encoder, crypto-friendly cam platform, multi-camera scenes. Walang watermark, walang sign-up.",
       "cherry tv broadcast, cherry.tv obs, cherry tv external encoder, cherry.tv rtmp, cherry.tv stream key, cherry tv streamer, web3 cam",
       'Paano mag-broadcast sa <span class="accent">Cherry.tv</span> gamit ang SplitCam',
       "Cherry.tv broadcast",
       "External encoder setup para sa Streamer Dashboard ng Cherry.tv.",
       "Ang Cherry.tv ay mas bagong, mabilis lumalaking cam platform na may Web3 angle — crypto-friendly payouts at mas mababang entry barriers kumpara sa mga legacy networks tulad ng LiveJasmin. Browser-based ang default broadcaster, pero binubuksan ng Streamer Dashboard ang standard external encoder path na kinokonekta ng libreng <strong style='color:var(--text)'>SplitCam</strong>.",
       "Mag-broadcast sa Cherry.tv gamit ang SplitCam: i-install ang SplitCam, buuin ang scene, Streamer Dashboard → Broadcast Settings → External Encoder, kopyahin ang URL at key, i-paste sa SplitCam, Go Live."
       "<ol><li>I-install ang SplitCam.</li><li>Idagdag ang camera + scene.</li><li>Kunin ang URL at key mula sa Streamer Dashboard.</li><li>I-paste sa SplitCam.</li><li>Pindutin ang Go Live.</li></ol>",
       "Mag-log in sa streamer account ng Cherry.tv, buksan ang <strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong>. Nakatali sa account ang server URL at stream key. Kailangan ng basic verification ang mga bagong account (mas magaan ang onboarding ng Cherry.tv kumpara sa legacy networks).",
       [("Magaan ang entry, lumalago ang traffic", "Walang 72-hour Docler-style review — mabilis ang onboarding at lumalago ang viewer base. Magandang lugar para sa early-mover na gustong kumuha ng posisyon bago ma-crowded ang platform."),
        ("Crypto + fiat payouts", "Nag-aalok ang Cherry.tv ng crypto payouts kasama ng fiat — itakda ang payout preference sa dashboard kung gusto mong dumiretso sa wallet ang earnings mo."),
        ("Browser broadcaster vs external", "Mabilis ang browser broadcaster pero single-camera. I-connect ang SplitCam sa External Encoder at bubuksan mo ang multi-camera scenes, overlays, beauty filters, at AI background — mas malinis na visual, mas mahabang session."),
        _T_ETH],
       [("Sinusuportahan ba ng Cherry.tv ang external encoders?", "Oo — may standard RTMP External Encoder path ang Streamer Dashboard. Kumokonekta dito ang OBS, SplitCam, at vMix; piliin lang ang External Encoder sa Broadcast Settings."),
        ("Saan ko kukunin ang Cherry.tv stream key ko?", "Sa loob ng Streamer Dashboard → Broadcast Settings → External Encoder. Lumalabas doon ang server URL at unique account stream key — kopyahin pareho sa custom RTMP fields ng SplitCam."),
        ("Anong bitrate para sa Cherry.tv?", "Itutok sa 1920×1080 sa 30 fps, 3,500–6,000 Kbps na may 2-second keyframe interval. Bago ang platform, bata ang audience — inaasahan ang HD quality."),
        ("Libre ba ang SplitCam para sa Cherry.tv?", "Oo — libre ang SplitCam, walang watermark, walang time limit. Pwede mong ipadala ang multi-camera scenes, overlays, at beauty filters sa Cherry.tv nang walang dagdag na gastos.")],
       steps=[
           ("I-install ang SplitCam", "Ang SplitCam ay libreng live-streaming software para sa Windows at macOS — walang sign-up, walang card, walang watermark. Ito ang encoder na nagpapadala ng broadcast mo sa RTMP endpoint ng Cherry.tv."),
           ("Buuin ang scene mo", "Sa SplitCam idagdag ang webcam mo, maglagay ng overlays, beauty filters, at second camera — mas bata at platform-savvy ang Cherry.tv audience; kailangang pakiramdam modern at mabilis ng scene mo."),
           ("Streamer Dashboard → Broadcast Settings → External Encoder", "Mag-log in sa Cherry.tv, buksan ang <strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong>. Ipinapakita ng pahina ang server URL at unique account stream key — kopyahin pareho."),
           ("I-connect ang SplitCam sa Cherry.tv", "Sa SplitCam buksan ang <strong>Stream Settings</strong>, i-paste ang Cherry.tv server URL at stream key sa custom RTMP fields. Itakda ang bitrate sa 3,500–6,000 Kbps sa 1920×1080, 30 fps."),
           ("I-click ang Go Live", "Pindutin ang <strong>Go Live</strong> sa SplitCam, pagkatapos mag-online mula sa Streamer Dashboard ng Cherry.tv. Sa loob ng ilang segundo aabot sa Cherry.tv ang stream mo at magsisimulang dumagsa ang mga viewer."),
       ]),
]
