# -*- coding: utf-8 -*-
"""Swedish (sv) content for cam-streaming-guides. Native Swedish, 20 platforms."""

_T_ETH = ("Använd kabelanslutning", "Ethernet slår Wi-Fi vid långa sändningar — tappade bildrutor "
          "betyder tappade tips. Koppla en kabel till datorn som sänder.")
_T_TEST = ("Gör ett privat test först", "Kör en kort testsändning för att kontrollera kamera, ljud, "
           "bildkomposition och overlays innan du öppnar rummet för tittare.")

def _p(slug, name, title, desc, kw, h1html, h1short, card, intro, quick, key_how, tips, faq, steps=None):
    d = {"slug": slug, "name": name, "title": title, "desc": desc, "kw": kw,
         "h1html": h1html, "h1short": h1short, "card": card, "intro": intro,
         "quick": quick, "key_how": key_how, "tips": tips, "faq": faq}
    if steps: d["steps"] = steps
    return d

PLATFORMS_SV = [
    _p("chaturbate", "Chaturbate",
       "Sänd på Chaturbate med SplitCam — Token & RTMP",
       "Sänd på Chaturbate med SplitCam gratis — broadcast token, RTMP, flerkamerascener och overlays. Ingen vattenstämpel, ingen registrering.",
       "sända chaturbate, chaturbate broadcast token, chaturbate rtmp obs, chaturbate extern kodare, chaturbate live",
       'Så sänder du på <span class="accent">Chaturbate</span> med SplitCam',
       "Sända Chaturbate",
       "Token-baserad uppsättning med extern kodare på Chaturbate.",
       "Chaturbate är en av de största cam-plattformarna, byggd på token-ekonomi. Dess webbläsarsändare är bara ett platt enkamerasverktyg — byt till en <strong style='color:var(--text)'>extern kodare</strong> med gratis <strong style='color:var(--text)'>SplitCam</strong> så låser du upp flerkamerascener, overlays och filter i samma token-baserade sändning.",
       "Sänd på Chaturbate med SplitCam: installera SplitCam, bygg din scen, öppna <em>Broadcast Yourself → My Broadcast</em> på Chaturbate, kopiera broadcast token, klistra in i SplitCam, Go Live."
       "<ol><li>Installera SplitCam.</li><li>Lägg till kamera + scen.</li><li>Kopiera broadcast token från Chaturbate.</li><li>Klistra in i SplitCam.</li><li>Tryck Go Live.</li></ol>",
       "På Chaturbate klickar du <strong>Broadcast Yourself</strong> för att komma till sidan <strong>My Broadcast</strong>, sedan <strong>View RTMP/OBS broadcast information and stream key</strong>. Nyckeln visas som en <strong>broadcast token</strong> — kopiera den. Behandla den som ett lösenord; dela aldrig.",
       [("Token är nyckeln", "Chaturbate använder din broadcast token, inte en generell streamnyckel. Behandla den som ett lösenord och återställ den om den läcker."),
        ("Gott om utrymme", "Chaturbates RTMP-ingest tar emot upp till 4K, 60 fps och hög bitrate — gränsen är din uppladdning, inte plattformen. Nyckelbildruta varannan sekund."),
        _T_ETH, _T_TEST],
       [("Tillåter Chaturbate OBS / extern kodare?", "Ja — Chaturbate stöder externa kodare officiellt och har en egen artikel «How do I set up OBS?». Aktivera via «Use External Encoder to Broadcast» i sändningsinställningarna."),
        ("Var är min Chaturbate-streamnyckel?", "Broadcast Yourself → My Broadcast → View RTMP/OBS broadcast information and stream key. Nyckeln är din broadcast token."),
        ("Vilken bitrate för Chaturbate?", "3500–6000 Kbps i 1080p är mer än nog. Chaturbates tak är högt — den verkliga gränsen är din uppladdning; kör SplitCams inbyggda hastighetstest först."),
        ("Är SplitCam gratis för Chaturbate?", "Ja — helt gratis, ingen vattenstämpel och ingen tidsgräns: kodaren äter inte av dina token-intäkter.")]),
    _p("cam4", "CAM4",
       "Sänd på CAM4 med SplitCam — External Encoder",
       "Sänd på CAM4 med SplitCam gratis — External Encoder, streamnyckel, geoblockering och overlays. Ingen vattenstämpel.",
       "sända cam4, cam4.com, cam4 external encoder, cam4 streamnyckel, cam4 rtmp obs",
       'Så sänder du på <span class="accent">CAM4</span> med SplitCam',
       "Sända CAM4",
       "External Encoder på CAM4 med geokontroll.",
       "CAM4 är en global cam-and-earn-plattform med inbyggd geokontroll — du kan dölja din sändning i vissa länder. Att sända via gratis <strong style='color:var(--text)'>SplitCam</strong> som extern kodare låser upp scenväxling och overlays som grundverktyget saknar.",
       "Sänd på CAM4 med SplitCam: installera SplitCam, bygg din scen, öppna <em>Broadcast &amp; Earn Money → Start Broadcast → External Encoder</em> på CAM4, Get Stream Key, klistra in i SplitCam, Go Live."
       "<ol><li>Installera SplitCam.</li><li>Lägg till kamera + scen.</li><li>Hämta streamnyckeln från CAM4.</li><li>Klistra in i SplitCam.</li><li>Tryck Go Live.</li></ol>",
       "På CAM4 klickar du <strong>Broadcast</strong> → <strong>Broadcast &amp; Earn Money</strong> → <strong>Start Broadcast</strong>, sedan <strong>External Encoder</strong> överst. Fyll i födelsedatum, kön och land, använd <strong>Get Stream Key</strong> och kopiera. Det gröna reglaget i SplitCams Stream Settings betyder anslutning.",
       [("Ställ in geobegränsningar", "CAM4 låter dig dölja sändningen i vissa länder och regioner — ställ in det på CAM4-sidan före go-live."),
        ("Håll koll på det gröna reglaget", "CAM4-uppsättningen visar ett grönt reglage i SplitCams Stream Settings när nyckeln godtas — rött = kolla nyckeln."),
        ("Lägre bitrate än vanligt", "CAM4:s RTMP-ingest begränsar videobitrate till runt 3000 Kbps — lägre än de flesta cam-sajter. Tvinga inte högre."),
        _T_ETH],
       [("Stöder CAM4 OBS / extern kodare officiellt?", "Ja — CAM4 har en officiell OBS Guide på supportsidan och rekommenderar External Encoder för bästa upplevelse. SplitCam använder samma RTMP-väg."),
        ("Kan jag geoblockera min CAM4-sändning?", "Ja — CAM4 har inbyggda geobegränsningar för att dölja sändningen i vissa länder. Ställ in det på CAM4, inte i SplitCam."),
        ("Var är CAM4:s streamnyckel?", "Broadcast → Broadcast & Earn Money → Start Broadcast → External Encoder → Get Stream Key."),
        ("Vilken bitrate för CAM4?", "Lägre än snittet — CAM4:s RTMP-ingest begränsar ~3000 Kbps vid 30 fps med nyckelbildruta varje sekund. Officiella tabellen råder att inte överstiga ~3000.")]),
    _p("bongacams", "BongaCams",
       "Sänd på BongaCams med SplitCam — External Encoder",
       "Sänd på BongaCams med SplitCam gratis — External Encoder, flerkamerascener, overlays och AI-bakgrunder. Ingen vattenstämpel.",
       "bongacams, bongcams, sända bongacams, bongacams external encoder, bongacams rtmp obs",
       'Så sänder du på <span class="accent">BongaCams</span> med SplitCam',
       "Sända BongaCams",
       "External Encoder-uppsättning för BongaCams.",
       "BongaCams är en global cam-plattform. Sändning med extern kodare är inte alltid påslagen — när den aktiverats styr gratis <strong style='color:var(--text)'>SplitCam</strong> sändningen med flerkamerascener, overlays och AI-bakgrunder.",
       "Sänd på BongaCams med SplitCam: installera SplitCam, bygg din scen, öppna <em>Options → Broadcast settings → Select Encoder → External Encoder</em> på BongaCams, kopiera URL och nyckel, klistra in i SplitCam, Go Live."
       "<ol><li>Installera SplitCam.</li><li>Lägg till kamera + scen.</li><li>Hämta URL och nyckel från BongaCams.</li><li>Klistra in i SplitCam.</li><li>Tryck Go Live.</li></ol>",
       "På BongaCams öppnar du <strong>Options</strong> → <strong>Broadcast settings</strong> → <strong>Select Encoder</strong> → <strong>External Encoder</strong> och kopierar visad server-URL och streamnyckel. <strong>Om knappen External Encoder saknas</strong>, kontakta BongaCams support och be om att aktivera extern kodning på kontot.",
       [("Ingen External Encoder-knapp? Support", "BongaCams aktiverar extern kodning per konto — om alternativet saknas i Broadcast settings aktiverar supporten det."),
        ("Matcha upplösningen", "BongaCams rekommenderar att webbkamerans och sändningens upplösning stämmer — t.ex. båda 1280×720."),
        _T_ETH, _T_TEST],
       [("Varför visas inte External Encoder-knappen på BongaCams?", "Extern kodning är inte påslagen som standard på varje konto — kontakta BongaCams support för att slå på den, så dyker knappen upp i Broadcast settings."),
        ("Måste jag verifiera mitt BongaCams-konto?", "Ja — sändning kräver 18+, officiell ID-handling för åldersverifiering och kontogodkännande innan live."),
        ("Vilken bitrate för BongaCams?", "BongaCams RTMP-ingest begränsar videobitrate till runt 6000 Kbps med nyckelbildruta varannan sekund — 3500–6000 i 1080p är idealzonen; testa uppladdningen först."),
        ("Är SplitCam gratis för BongaCams?", "Ja — helt gratis, ingen vattenstämpel och ingen tidsgräns, så kodaren minskar inte dina token-intäkter på BongaCams.")]),
    _p("stripchat", "Stripchat",
       "Sänd på Stripchat med SplitCam — strip cam-uppsättning",
       "Sänd på Stripchat — en strip cam-plattform — med SplitCam gratis. Extern mjukvara, token-baserad nyckel, scener och overlays.",
       "strip cam, stripchat live stream, sända stripchat, stripchat external software, stripchat streamnyckel, stripchat rtmp obs",
       'Så sänder du på <span class="accent">Stripchat</span> med SplitCam',
       "Sända Stripchat",
       "Extern mjukvara-uppsättning för Stripchat-sändning.",
       "Stripchat är en stor cam-plattform med fokus på interaktivitet. Läget <em>external software</em> ger dig en token-baserad nyckel — mata in den i gratis <strong style='color:var(--text)'>SplitCam</strong> och sänd med scener, overlays och filter i stället för en platt kamera.",
       "Sänd på Stripchat med SplitCam: installera SplitCam, bygg din scen, välj <em>Switch to external software</em> på Stripchat, kopiera streamnyckeln, klistra in i SplitCam, Go Live."
       "<ol><li>Installera SplitCam.</li><li>Lägg till kamera + scen.</li><li>Hämta streamnyckeln från Stripchat.</li><li>Klistra in i SplitCam.</li><li>Tryck Go Live.</li></ol>",
       "På Stripchat väljer du <strong>Switch to external software</strong>, sedan <strong>Show external software settings for the stream</strong>. Kopiera streamnyckeln — Stripchat visar den som en token. Håll den hemlig.",
       [("Matcha upplösningen med sajten", "Stripchats FAQ varnar: upplösningen i din mjukvara måste matcha sajten exakt, annars faller videon isär. Ställ in båda lika."),
        ("Akta minimum 2 Mbps", "Stripchat anger 2 Mbps uppladdning som minimum — och säger rakt ut att det inte räcker för OBS-sändning eller multistream. Sikta mycket högre."),
        ("Nyckeln är en token", "Stripchats streamnyckel är en token — kopiera exakt, dela aldrig, återställ vid läcka."),
        _T_ETH],
       [("Rekommenderar Stripchat OBS / extern mjukvara?", "Ja — Stripchats officiella FAQ rekommenderar extern sändningsmjukvara som OBS «för att uppnå bästa video- och ljudkvalitet». SplitCam fungerar likadant."),
        ("Hur byter jag Stripchat till extern mjukvara?", "I Broadcast Center väljer du Switch to External Broadcast Software (OBS), sedan öppnar du external software settings för att visa streamnyckeln (token)."),
        ("Vilken bitrate för Stripchat?", "RTMP-ingest tar emot upp till ~6000 Kbps med nyckelbildruta varannan sekund. 3500–6000 i 1080p är idealt — men måste vara klart över minimum 2 Mbps, särskilt för OBS-sändning."),
        ("Är SplitCam gratis för Stripchat?", "Ja — inga licensavgifter, ingen vattenstämpel, ingen tidsgräns: även långa interaktiva Stripchat-shower kostar inget på kodarsidan.")]),
    _p("onlyfans", "OnlyFans",
       "Live på OnlyFans med SplitCam — Auktorisering eller nyckel",
       "Live på OnlyFans med SplitCam gratis — logga in via auktorisering eller OBS Key, flerkamerascener, overlays. Ingen vattenstämpel.",
       "live onlyfans, onlyfans live stream, onlyfans auktorisering splitcam, onlyfans obs key, onlyfans sändningsmjukvara",
       'Så går du <span class="accent">live på OnlyFans</span> med SplitCam',
       "Live OnlyFans",
       "Auktorisera en gång eller klistra in nyckel — live på OnlyFans.",
       "Livesänd OnlyFans för dina prenumeranter. SplitCam ansluter på <strong style='color:var(--text)'>två sätt</strong> — logga in en gång med ditt OnlyFans-konto så hämtar SplitCam streamnyckeln automatiskt och synkar den, eller klistra in OBS Key manuellt. Båda låter dig sända med flerkamerascener, overlays och filter.",
       "Live på OnlyFans med SplitCam: installera SplitCam, bygg din scen, öppna Stream Settings &rarr; Add Channel &rarr; OnlyFans och välj <em>Auktorisering</em> — logga in med OnlyFans-kontot, SplitCam hämtar nyckeln automatiskt — och tryck Go Live. Med kontot anslutet kan du ändra OnlyFans sändningsparametrar i SplitCam utan att öppna OnlyFans-sajten.",
       "På OnlyFans: <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; avsnittet <strong>Other</strong>, kopiera <strong>OBS Key</strong>. Eller använd alternativet <strong>Auktorisering</strong> i SplitCam för att logga in — nyckeln hämtas automatiskt och förblir synkad.",
       [("Auktorisering vs Stream Key", "Två sätt att ansluta: <strong>Auktorisering</strong> (logga in en gång, nyckeln hämtas och synkas — enklaste vägen) eller <strong>Stream Key</strong> (kopiera OBS Key på OnlyFans → Profile → Settings → Other och klistra in)."),
        ("Ändra inställningar utan att lämna SplitCam", "Med auktorisering förblir kontot anslutet, så du ställer in OnlyFans live-parametrar från SplitCam under eller efter sändningen — utan att besöka OnlyFans-sajten."),
        ("Blygsam bitrate", "OnlyFans RTMP-ingest begränsar videobitrate till runt 2500 Kbps — snävare än de flesta cam-sajter. Sikta på 720p–1080p vid ~2000–2500."),
        _T_ETH],
       [("Hur ansluter jag OnlyFans till SplitCam?", "Två sätt. <strong>Auktorisering</strong> — Stream Settings → Add Channel → OnlyFans → logga in med OnlyFans-kontot så hämtar SplitCam nyckeln automatiskt. Eller <strong>Stream Key</strong> — kopiera OBS Key på OnlyFans → Profile → Settings → Other och klistra in."),
        ("Kan jag ändra OnlyFans live-inställningar utan att öppna sajten?", "Ja — med auktoriseringsmetoden förblir SplitCam ansluten till OnlyFans-kontot, så nyckel och inställningar synkas automatiskt. Du ändrar allt från SplitCam under eller efter sändningen, utan att besöka onlyfans.com."),
        ("Vilken bitrate för OnlyFans?", "Blygsam — OnlyFans RTMP-ingest begränsar bitrate till runt 2500 Kbps, klart snävare än andra cam-plattformar. Sikta på 720p–1080p kring 2000–2500 Kbps."),
        ("Är SplitCam gratis för live på OnlyFans?", "Ja — gratis, ingen vattenstämpel och ingen tidsgräns. Inga kostnader på kodarsidan.")],
       steps=[
           ("Ladda ner och installera SplitCam", "SplitCam är gratis livesändningsmjukvara för Windows och macOS — ingen registrering, inget kort, ingen vattenstämpel. Det är kodaren som skickar din video till OnlyFans."),
           ("Ställ in kamera och scen", "Öppna SplitCam och lägg till din webbkamera. Bygg scenen som du vill att tittarna ska se den — overlays, text, andra kamera, skönhetsfilter eller AI-bakgrund, allt appliceras live."),
           ("Anslutning — Sätt 1: Auktorisering (rekommenderas)", "I SplitCam öppnar du <strong>Stream Settings</strong> &rarr; <strong>Add Channel</strong> &rarr; <strong>OnlyFans</strong> och väljer <strong>Auktorisering</strong>. Logga in med e-post och lösenord för OnlyFans. SplitCam länkar kontot, hämtar streamnyckeln automatiskt och synkar den — och låter dig hantera OnlyFans live-parametrar inuti SplitCam, ändra dem under eller efter sändningen utan att öppna OnlyFans-sajten."),
           ("Anslutning — Sätt 2: Stream Key (manuellt)", "Vill du inte logga in? Använd nyckeln. På OnlyFans öppnar du <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; avsnittet <strong>Other</strong> och kopierar <strong>OBS Key</strong>. I SplitCam, Add Channel &rarr; OnlyFans, klistra in i nyckelfältet. Nyckeln är statisk — för att ändra inställningar senare återgår du till OnlyFans-sajten."),
           ("Go Live", "Oavsett sätt trycker du <strong>Go Live</strong> i SplitCam. Med Sätt 1 kan du fortsätta finjustera OnlyFans-parametrarna från SplitCam i realtid; med Sätt 2 förblir nyckeln exakt som du angav."),
       ]),
    _p("camplace", "CamPlace",
       "Sänd på CamPlace med SplitCam — gratis guide",
       "Sänd på CamPlace med SplitCam gratis — extern kodare, RTMP-nyckel, scener och overlays. Steg för steg, ingen vattenstämpel.",
       "sända camplace, camplace broadcasting software, camplace rtmp, camplace extern kodare, camplace streamnyckel",
       'Så sänder du på <span class="accent">CamPlace</span> med SplitCam',
       "Sända CamPlace",
       "Extern kodare-uppsättning för CamPlace-sändning.",
       "CamPlace är en cam-streamingplattform. Det finns ingen offentlig OBS-artikel, så <strong style='color:var(--text)'>videoguiden ovan</strong> är din referens — gratis <strong style='color:var(--text)'>SplitCam</strong> ansluter via standard-RTMP och lägger till scener, overlays och AI-bakgrunder som grundkameran saknar.",
       "Sänd på CamPlace med SplitCam: installera SplitCam, bygg din scen, slå på extern/RTMP-sändning på CamPlace, kopiera server-URL och streamnyckel, klistra in i SplitCam, Go Live. Följ videon för den aktuella vägen."
       "<ol><li>Installera SplitCam.</li><li>Lägg till kamera + scen.</li><li>Hämta RTMP-nyckeln från CamPlace.</li><li>Klistra in i SplitCam.</li><li>Tryck Go Live.</li></ol>",
       "Logga in på CamPlace och öppna sändningsinställningarna. Byt till alternativet extern kodare / RTMP / OBS för att visa <strong>server-URL</strong> och <strong>streamnyckel</strong>, kopiera båda. CamPlace publicerar ingen officiell OBS-dokumentation — <strong>videon ovan</strong> är den mest tillförlitliga steg-för-steg-vägen genom det aktuella gränssnittet.",
       [("Ingen officiell OBS-guide — använd videon", "CamPlace saknar offentlig artikel om extern kodare; videon ovan är referens för den aktuella vägen."),
        ("Standard-RTMP fungerar", "Även utan dokumentation tar CamPlace emot standard server-URL för RTMP och nyckel — SplitCam ansluter som ett anpassat RTMP-mål."),
        ("Stapla overlays i SplitCam", "Tipsmål, namn och sociala mediers handtag lägger du till som scenlager — CamPlaces grundkamera lägger inte till dem."),
        _T_ETH],
       [("Har CamPlace en officiell OBS-guide?", "Ingen offentlig artikel om extern kodare hittad. CamPlace tar emot standard-RTMP-URL och nyckel, så SplitCam fungerar — följ videon."),
        ("Stöder CamPlace extern kodare?", "Ja — tar emot standard RTMP-streamnyckel, så SplitCam ansluter som ett anpassat RTMP-mål."),
        ("Vilken bitrate för CamPlace?", "CamPlace publicerar inga officiella siffror — använd 3500–6000 Kbps i 1080p som säkert intervall och låt SplitCams hastighetstest avgöra det verkliga taket."),
        ("Är SplitCam gratis för CamPlace?", "Ja — gratis, ingen vattenstämpel och ingen tidsgräns. Eftersom CamPlace saknar egen kodare löser det gratis RTMP-verktyget det.")]),
    _p("camsoda", "CamSoda",
       "CamSoda live med SplitCam — gratis uppsättning",
       "CamSoda live med SplitCam gratis — Use OBS Broadcaster, regionala servrar, scener och overlays. Ingen vattenstämpel.",
       "camsoda live, sända camsoda, camsoda obs broadcaster, camsoda rtmp obs, camsoda live broadcast",
       'Så sänder du på <span class="accent">CamSoda</span> med SplitCam',
       "Sända CamSoda",
       "Use OBS Broadcaster-uppsättning på CamSoda.",
       "CamSoda är en cam-plattform från USA känd för interaktiva, ovanliga showformat. Den stöder OBS-sändning officiellt — det finns en <strong style='color:var(--text)'>Use OBS Broadcaster</strong>-knapp på Go Live-sidan och en officiell OBS-guide på CamSodas wiki. Gratis <strong style='color:var(--text)'>SplitCam</strong> fungerar likadant.",
       "Sänd på CamSoda med SplitCam: installera SplitCam, bygg din scen, klicka Use OBS Broadcaster på CamSodas Go Live-sida, kopiera server-URL och streamnyckel, klistra in i SplitCam, Go Live."
       "<ol><li>Installera SplitCam.</li><li>Lägg till kamera + scen.</li><li>Klicka Use OBS Broadcaster på CamSoda.</li><li>Klistra in server-URL + nyckel i SplitCam.</li><li>Tryck Go Live.</li></ol>",
       "På CamSodas <strong>Go Live</strong>-sida klickar du <strong>Use OBS Broadcaster</strong>. CamSoda visar RTMP-server-URL och streamnyckel — kopiera båda. Välj den närmaste regionala servern (Nordamerika, Europa, Asien osv.). CamSodas wiki har en komplett OBS-guide för detaljer.",
       [("Verifiera dig för att ta emot tips", "På CamSoda kan vem som helst sända, men för att ta emot tips måste du slutföra CamSodas verifieringsprocess."),
        ("Välj närmaste regionala server", "CamSoda erbjuder regionala ingest-servrar — den närmaste (NA / Europa / Asien / Sydamerika / Oceanien) minskar fördröjning och tappade bildrutor."),
        ("Tak vid 1080p / 30 fps", "CamSodas ingest når runt 1080p, 30 fps och ~6000 Kbps — tvinga inte högre."),
        _T_ETH],
       [("Stöder CamSoda OBS / extern kodare?", "Ja — officiellt. Det finns en Use OBS Broadcaster-knapp på Go Live-sidan och en OBS-guide på CamSodas wiki, så SplitCam fungerar."),
        ("Behöver jag verifiering på CamSoda?", "För att sända, nej. För att ta emot tips, ja — CamSoda kräver att du först går igenom verifieringsprocessen."),
        ("Vilken upplösning stöder CamSoda?", "Upp till 1920×1080 vid 30 fps, max runt 6000 Kbps i RTMP-ingest."),
        ("Är SplitCam gratis för CamSoda?", "Ja — gratis, ingen vattenstämpel och ingen tidsgräns. Fungerar med CamSodas gratis Use OBS Broadcaster-läge, så hela uppställningen kostar inget.")]),
    _p("streamate", "Streamate",
       "Sänd på Streamate med SplitCam — integrerad kanal",
       "Sänd på Streamate med SplitCam gratis — integrerad kanal, SM Connect-nyckel, scener och overlays. Ingen vattenstämpel.",
       "streamate, streamate sm connect, sända streamate, streamate broadcasting software, streamate rtmp",
       'Så sänder du på <span class="accent">Streamate</span> med SplitCam',
       "Sända Streamate",
       "Streamate är en integrerad kanal i SplitCam — snabb uppsättning.",
       "Streamate är en etablerad cam-plattform — och ett <strong style='color:var(--text)'>förkonfigurerat mål i SplitCam</strong>, i kanallistan, så uppsättningen går snabbare än manuell RTMP-inmatning: välj Streamate, klistra in nyckeln, klart.",
       "Sänd på Streamate med SplitCam: installera SplitCam, bygg din scen, använd <em>SM Connect → Start Show</em> på Streamate och kopiera nyckeln, öppna sedan <em>Stream Settings → Add Channel → Streamate</em> i SplitCam och klistra in."
       "<ol><li>Installera SplitCam.</li><li>Lägg till kamera + scen.</li><li>Hämta Streamate-nyckeln via SM Connect.</li><li>Add Channel → Streamate i SplitCam.</li><li>Tryck Go Live.</li></ol>",
       "På Streamate öppnar du <strong>SM Connect</strong>, godkänner villkoren, klickar <strong>Start Show</strong> till vänster och stänger fönstret som öppnas — kopiera sedan streamnyckeln. I SplitCam öppnar du <strong>Stream Settings</strong> → <strong>Add Channel</strong>, väljer <strong>Streamate</strong> i listan och klistrar in nyckeln. Det gröna reglaget betyder anslutning.",
       [("Streamate är integrerad", "Ingen manuell RTMP-URL — SplitCam har Streamate i Add Channel-listan; välj bara och klistra in nyckeln."),
        ("Stäng SM Connect-popupen", "Efter Start Show öppnar Streamate ett fönster — stäng det; det visar bara streamnyckeln."),
        ("Lås upplösningen till 1080p", "Fältet Video Resolution i SM Connect kan tyst hoppa till 1440, vilket inte faktiskt skickas och tyst sänker din kvalitet — ställ in 1080p manuellt. Att bitraten sjunker vid stillbild är normalt: Streamates stream är adaptiv."),
        _T_ETH, _T_TEST],
       [("Är Streamate integrerad i SplitCam?", "Ja — Streamate dyker upp i SplitCams Add Channel-lista; du väljer den, du skriver inte in RTMP-URL manuellt."),
        ("Var är Streamates streamnyckel?", "SM Connect → godkänn villkoren → Start Show → stäng popupen → kopiera nyckeln."),
        ("Vilken bitrate för Streamate?", "Streamate sätter inget hårt tak — 3500–6000 Kbps i 1080p fungerar bra. Streamen är adaptiv, så lägre bitrate vid stillbild är normalt, inte ett fel."),
        ("Är SplitCam gratis för Streamate?", "Ja — gratis, ingen vattenstämpel och ingen tidsgräns; och eftersom Streamate är en integrerad kanal i SplitCam finns inga separata kodarkostnader.")]),
    _p("streamray", "StreamRay",
       "Sänd på StreamRay cam med SplitCam — URL i chatten",
       "Sänd på StreamRay cam med SplitCam gratis — URL postas i chatten, OBS Broadcaster-läge, scener och overlays. Ingen vattenstämpel.",
       "streamray, streamray cam, sända streamray, streamray obs broadcaster, streamray rtmp",
       'Så sänder du på <span class="accent">StreamRay</span> med SplitCam',
       "Sända StreamRay",
       "Extern kodare av typen URL-i-chatten för StreamRay.",
       "StreamRay har en ovanlig extern kodare-uppsättning — den skickar stream-URL:en i <strong style='color:var(--text)'>sändningens chattfönster</strong> och använder ingen separat nyckel. Gratis <strong style='color:var(--text)'>SplitCam</strong> hanterar detta enbart-URL-flöde.",
       "Sänd på StreamRay med SplitCam: installera SplitCam, bygg din scen, slå på OBS Broadcaster på StreamRay, kopiera stream-URL:en från chattfönstret, klistra in i SplitCam (lämna nyckelfältet tomt), Go Live."
       "<ol><li>Installera SplitCam.</li><li>Lägg till kamera + scen.</li><li>Kopiera StreamRay-URL:en från chatten.</li><li>Klistra in URL:en i SplitCam.</li><li>Tryck Go Live.</li></ol>",
       "På StreamRay dubbelklickar du <strong>Broadcast Now</strong>, öppnar menyn <strong>Other</strong>, väljer <strong>OBS Broadcaster</strong> och <strong>Save and Close</strong>. StreamRay postar sedan <strong>stream-URL:en i chattfönstret</strong> — kopiera den därifrån. Lämna SplitCams streamnyckelfält <strong>tomt</strong>; StreamRay verifierar bara via URL.",
       [("URL:en finns i chatten", "StreamRay visar inte stream-URL:en i inställningsrutan — den postar den i sändningens chattfönster. Kopiera den därifrån."),
        ("Lämna nyckelfältet tomt", "StreamRay använder ingen separat nyckel — bara URL. Skriv inget i SplitCams nyckelfält."),
        _T_ETH, _T_TEST],
       [("Var är StreamRays stream-URL?", "Efter att du slagit på OBS Broadcaster postar StreamRay URL:en i chattfönstret — kopiera från chatten."),
        ("Varför finns ingen streamnyckel på StreamRay?", "StreamRay verifierar bara via URL — lämna SplitCams nyckelfält tomt."),
        ("Vilken bitrate för StreamRay?", "StreamRay anger inget officiellt tak — sikta på 3500–6000 Kbps i 1080p och kör SplitCams hastighetstest, eftersom enbart-URL-flödet inte ger bitrate-återkoppling."),
        ("Är SplitCam gratis för StreamRay?", "Ja — gratis, ingen vattenstämpel och ingen tidsgräns, passar StreamRays enbart-URL-flöde: klistra in en länk och du är live.")]),
    _p("xlovecam", "XLoveCam",
       "Sänd på XLoveCam med SplitCam — RTMP-länk & nyckel",
       "Sänd på XLoveCam med SplitCam gratis — RTMP-länk och nyckel, regionala servrar, scener och overlays. Ingen vattenstämpel.",
       "xlovecam, x love cam, sända xlovecam, xlovecam rtmp link, xlovecam streamnyckel",
       'Så sänder du på <span class="accent">XLoveCam</span> med SplitCam',
       "Sända XLoveCam",
       "RTMP-länk + nyckel-uppsättning för XLoveCam.",
       "XLoveCam är en europeisk flerspråkig cam-plattform. Kontoinställningarna visar både <strong style='color:var(--text)'>RTMP-länk</strong> och <strong style='color:var(--text)'>streamnyckel</strong> — gratis <strong style='color:var(--text)'>SplitCam</strong> tar båda och sänder med fulla scener och overlays.",
       "Sänd på XLoveCam med SplitCam: installera SplitCam, bygg din scen, öppna <em>My Account → settings</em> på XLoveCam, kopiera RTMP-länk och streamnyckel, klistra in båda i SplitCam, starta showen."
       "<ol><li>Installera SplitCam.</li><li>Lägg till kamera + scen.</li><li>Kopiera RTMP-länk + nyckel från XLoveCam.</li><li>Klistra in båda i SplitCam.</li><li>Tryck Go Live.</li></ol>",
       "På XLoveCam öppnar du <strong>My Account</strong> → <strong>settings</strong>. Inställningarna visar både <strong>RTMP-länk</strong> och <strong>streamnyckel</strong> — kopiera båda till SplitCams fält för server-URL och nyckel, sedan <strong>Start your show</strong> på XLoveCam.",
       [("Kopiera länk OCH nyckel", "XLoveCam ger RTMP-länk OCH en separat streamnyckel — du behöver båda i SplitCam, inte bara en."),
        ("Flerspråkig publik", "XLoveCam är europeisk och flerspråkig — tydliga textöverlägg på ditt språk hjälper tittarna att hitta dig."),
        ("Välj närmaste server", "XLoveCam erbjuder regionala RTMP-servrar — Europa, Nordamerika, Sydamerika och Asien. Den närmaste minskar fördröjning och tappade bildrutor."),
        _T_ETH],
       [("Var finns XLoveCams RTMP-data?", "My Account → settings — visar både RTMP-länk och nyckel."),
        ("Stöder XLoveCam extern kodare?", "Ja — den tillhandahåller RTMP-länk och nyckel, så SplitCam fungerar som kodare."),
        ("Vilken bitrate för XLoveCam?", "XLoveCam publicerar ingen fast gräns; 3500–6000 Kbps i 1080p är idealt. Att välja närmaste regionala server är lika viktigt — det minskar tappade bildrutor."),
        ("Är SplitCam gratis för XLoveCam?", "Ja — gratis, ingen vattenstämpel och ingen tidsgräns. Att nå XLoveCams flerspråkiga europeiska publik kostar inga mjukvaruavgifter.")]),
    _p("soulcams", "SoulCams",
       "Sänd på SoulCams med SplitCam — OBS-inställningar",
       "Sänd på SoulCams med SplitCam gratis — OBS-inställningar, RTMP-server och nyckel, flerkamerascener och overlays.",
       "soul cams, soulcams, sända soulcams, soulcams obs, soulcams rtmp, soulcams broadcast",
       'Så sänder du på <span class="accent">SoulCams</span> med SplitCam',
       "Sända SoulCams",
       "OBS-inställningar för SoulCams.",
       "SoulCams är en cam-plattform vars OBS-inställningar visar <strong style='color:var(--text)'>RTMP-server och streamnyckel tillsammans</strong> i ett fönster. Klistra in båda i gratis <strong style='color:var(--text)'>SplitCam</strong> och sänd med flerkamerascener och overlays.",
       "Sänd på SoulCams med SplitCam: installera SplitCam, bygg din scen, klicka Go Online → Settings → OBS på SoulCams, kopiera server och nyckel, klistra in båda i SplitCam, Go Live."
       "<ol><li>Installera SplitCam.</li><li>Lägg till kamera + scen.</li><li>Öppna SoulCams Settings → OBS.</li><li>Klistra in server + nyckel i SplitCam.</li><li>Tryck Go Live.</li></ol>",
       "På SoulCams loggar du in och klickar <strong>Go Online</strong>, öppnar sedan <strong>Settings</strong> → <strong>OBS</strong>. OBS-fönstret visar <strong>RTMP-server</strong> och <strong>streamnyckel</strong> tillsammans — kopiera båda till SplitCam.",
       [("Server och nyckel sida vid sida", "SoulCams visar RTMP-server och nyckel i samma OBS-fönster — ta båda samtidigt."),
        ("Go Online först", "OBS-inställningarna dyker upp först efter att du klickat Go Online på SoulCams — gör det innan du letar efter kodardata."),
        ("Blockera oönskade regioner", "SoulCams tillåter geoblockering från modellens sida — välj vilka länder som inte ska se streamen innan du klickar Go Online."),
        _T_ETH, _T_TEST],
       [("Var är SoulCams OBS-inställningar?", "Logga in, klicka Go Online, sedan Settings → OBS — RTMP-server och streamnyckel visas tillsammans."),
        ("Stöder SoulCams extern kodare?", "Ja — OBS-inställningarna ger RTMP-server och nyckel, så SplitCam fungerar."),
        ("Vilken bitrate för SoulCams?", "SoulCams ger inga officiella siffror — sikta på 3500–6000 Kbps i 1080p och testa uppladdningen, eftersom OBS-fönstret inte visar bitrate-vägledning."),
        ("Är SplitCam gratis för SoulCams?", "Ja — gratis, ingen vattenstämpel och ingen tidsgräns, så fulla shower på SoulCams med flerkamerascener och overlays kostar inget på kodarsidan.")]),
    _p("imlive", "ImLive",
       "Använd ImLive med SplitCam — virtuell kamera",
       "Im Live stream-uppsättning med SplitCam gratis — ImLive använder live-webbkamera (ingen RTMP), anslut SplitCam som virtuell kamera med scener.",
       "im live stream, imlive splitcam, sända imlive, imlive virtuell kamera, imlive webcam, im live cam",
       'Så använder du <span class="accent">ImLive</span> med SplitCam',
       "SplitCam på ImLive",
       "Virtuell kamera-uppsättning för ImLive — ingen RTMP.",
       "ImLive använder en live-webbkamera i webbläsaren — <strong style='color:var(--text)'>ingen RTMP eller streamnyckel</strong>. Gratis <strong style='color:var(--text)'>SplitCam</strong> ansluter som en <strong style='color:var(--text)'>virtuell kamera</strong>: bygg din scen i SplitCam, välj sedan SplitCam som kamera på ImLive.",
       "Använd SplitCam med ImLive: installera SplitCam, bygg din scen med medialager, öppna ImLive och starta videochatt, välj SplitCam som webbkamera och mikrofon i ImLives inställningar."
       "<ol><li>Installera SplitCam.</li><li>Bygg din scen i SplitCam.</li><li>Starta videochatt på ImLive.</li><li>Välj SplitCam som ImLive-kamera.</li><li>Starta chatten.</li></ol>",
       "Logga in på ImLive-sajten och klicka <strong>Start Video Chat</strong>, öppna sedan <strong>Go To Settings</strong> för att nå kamera- och mikrofonalternativen. I ImLives inställningar väljer du <strong>SplitCam</strong> som webbkamera och mikrofon.",
       [("Ingen streamnyckel behövs", "ImLive har ingen RTMP — leta inte efter server-URL eller nyckel. SplitCam väljs bara som kameraenhet."),
        ("Ställ in SplitCam även som mikrofon", "Välj SplitCam för mikrofonen utöver kameran så att ljudmix och brusreducering också går till livesändningen."),
        ("Bygg scenen före sändning", "ImLive visar det SplitCam skickar — ordna lagren innan du startar chatten."),
        _T_TEST],
       [("Använder ImLive RTMP eller streamnyckel?", "Inget av dem — ImLive använder en live-webbkamera via webbläsaren. SplitCam ansluter som virtuell kamera, ingen nyckel att kopiera."),
        ("Hur väljer jag SplitCam på ImLive?", "Start Video Chat → Go To Settings → välj SplitCam som webbkamera och mikrofon."),
        ("Kan jag använda overlays på ImLive?", "Ja — bygg dem i SplitCam-scenen; ImLive visar det sammansatta resultatet."),
        ("Är SplitCam gratis för ImLive?", "Ja — gratis, ingen vattenstämpel och ingen tidsgräns. Som virtuell kamera för ImLive lägger den inte till kostnader eller varumärkning i din videochatt.")],
       steps=[
           ("Installera SplitCam", "SplitCam är gratis mjukvara för Windows och macOS. Installera den — ingen vattenstämpel, ingen registrering. För ImLive fungerar den som en <strong>virtuell kamera</strong>, inte en RTMP-kodare."),
           ("Bygg din scen i SplitCam", "Öppna SplitCam och använd <strong>Media Layers +</strong> för att lägga till webbkameran plus valfria overlays, text, filter eller AI-bakgrund. Den sammansatta scenen är det ImLive ser som din kamera."),
           ("Starta videochatt på ImLive", "Logga in på ImLive-sajten och klicka <strong>Start Video Chat</strong>, öppna sedan <strong>Go To Settings</strong> för att nå kamera- och mikrofonalternativen."),
           ("Välj SplitCam som kamera", "I ImLives inställningar väljer du <strong>SplitCam</strong> som webbkamera OCH mikrofon. ImLive visar nu din fulla SplitCam-scen, inte en platt webbkamera."),
           ("Starta Free Live Chat", "Klicka <strong>Free Live Chat</strong> på ImLive för att gå live. För att ändra utseendet mitt i sessionen redigerar du scenen i SplitCam — ImLive uppdateras direkt."),
       ]),
    _p("vxlive", "VXLive",
       "Sänd på VXLive med SplitCam — officiellt stöd",
       "Sänd på VXLive (VXModels / VISIT-X) med SplitCam gratis — officiell VISIT-X-preset, server och nyckel, scener. Ingen vattenstämpel.",
       "vxlive, visit-x, vxmodels splitcam, sända vxlive, visit-x stream, vxlive rtmp",
       'Så sänder du på <span class="accent">VXLive</span> med SplitCam',
       "Sända VXLive",
       "VXLive stöder SplitCam officiellt (VISIT-X-preset).",
       "VXLive (VXModels / VISIT-X) är en cam-plattform från den tyska marknaden — och en av få som <strong style='color:var(--text)'>stöder SplitCam officiellt vid namn</strong>. VXModels har en särskild hjälpartikel om att ansluta <strong style='color:var(--text)'>SplitCam</strong> till VXLive, och SplitCam erbjuder VISIT-X som en färdig kanalpreset.",
       "Sänd på VXLive med SplitCam: installera SplitCam, bygg din scen, välj «Stream with third-party software» på VXLive, kopiera server-URL och nyckel, välj VISIT-X-preset i SplitCam och klistra in, Go Live i SplitCam, sedan GO ONLINE på VXLive."
       "<ol><li>Installera SplitCam.</li><li>Lägg till kamera + scen.</li><li>Hämta server-URL + nyckel från VXLive.</li><li>Välj VISIT-X-preset i SplitCam, klistra in.</li><li>Go Live, sedan GO ONLINE på VXLive.</li></ol>",
       "På VXLive väljer du <strong>Stream with third-party software</strong> och alternativet <strong>OBS, SplitCam eller XSplit</strong>. VXLive ger <strong>server-URL</strong> och <strong>streamnyckel</strong>. I SplitCam väljer du <strong>VISIT-X</strong> som streamingplattform, klistrar in båda, trycker <strong>Go Live</strong> i SplitCam, sedan <strong>GO ONLINE</strong> på VXLive.",
       [("VISIT-X är en integrerad preset", "Skriv inte in en rå RTMP-URL — SplitCam har VISIT-X i plattformslistan; välj bara och klistra in server-URL och nyckel."),
        ("Tvåstegs go-live", "På VXLive trycker du först Go Live i SplitCam, sedan GO ONLINE på VXLive — båda, i den ordningen."),
        ("Tysk marknad", "VXLives publik är mestadels tysktalande — tyska textöverlägg eller titlar hjälper dig att nå tittarna."),
        _T_ETH],
       [("Stöder VXLive SplitCam officiellt?", "Ja — VXModels (VXLive) underhåller en särskild officiell hjälpartikel för SplitCam-uppsättning och listar SplitCam tillsammans med OBS och XSplit som stödd sändningsmjukvara."),
        ("Hur ansluter jag SplitCam till VXLive?", "På VXLive väljer du «Stream with third-party software», sedan väljer du VISIT-X-preset i SplitCam och klistrar in server-URL och streamnyckel som VXLive ger."),
        ("Är jag live i SplitCam eller VXLive?", "I båda — Go Live i SplitCam först, sedan GO ONLINE på VXLive."),
        ("Varför rekommenderar VXModels SplitCam?", "VXModels officiella hjälpartikel rekommenderar SplitCam specifikt för att ta bort webbkameraartefakter och pixelering och stabilisera anslutningen — inte bara som en generell kodare.")]),
    _p("virtwish", "VirtWish",
       "Sänd på VirtWish med SplitCam — stream-URL & nyckel",
       "Sänd på VirtWish med SplitCam gratis — avsnittet OBS Profile → Start Broadcast, stream-URL och nyckel, scener och overlays.",
       "virtwish, sända virtwish, virtwish broadcasting software, virtwish rtmp, virtwish streamnyckel, virtwish obs",
       'Så sänder du på <span class="accent">VirtWish</span> med SplitCam',
       "Sända VirtWish",
       "Stream-URL + nyckel-uppsättning för VirtWish.",
       "VirtWish är en interaktiv cam-plattform. Sändningsinställningarna ger dig <strong style='color:var(--text)'>separat stream-URL och streamnyckel</strong> i OBS-avsnittet — gratis <strong style='color:var(--text)'>SplitCam</strong> tar båda och kör showen med scener och overlays.",
       "Sänd på VirtWish med SplitCam: installera SplitCam, bygg din scen, öppna <em>Profile → Start Broadcast</em> till OBS-avsnittet på VirtWish, kopiera länk och nyckel, klistra in båda i SplitCam, Go Live."
       "<ol><li>Installera SplitCam.</li><li>Lägg till kamera + scen.</li><li>Hämta URL + nyckel från VirtWish.</li><li>Klistra in båda i SplitCam.</li><li>Tryck Go Live.</li></ol>",
       "På VirtWish klickar du ikonen uppe till höger → <strong>Profile</strong> → <strong>Start Broadcast</strong>, sedan <strong>Start Broadcast</strong> igen för att nå OBS-avsnittet. <strong>Kopiera länken på första raden</strong> till SplitCams Stream URL-fält och den separata <strong>Stream Key</strong> till nyckelfältet.",
       [("Länken är på första raden", "VirtWishs OBS-avsnitt lägger stream-URL:en på första raden — kopiera den till SplitCams Stream URL, sedan den separata nyckeln."),
        ("Två klick på Start Broadcast", "Du klickar Start Broadcast två gånger på VirtWish för att nå OBS-avsnittet — det är normalt, inte ett fel."),
        _T_ETH, _T_TEST],
       [("Var finns VirtWishs RTMP-data?", "Ikonen uppe till höger → Profile → Start Broadcast två gånger → OBS-avsnittet visar länk och streamnyckel."),
        ("Stöder VirtWish extern kodare?", "Ja — OBS-avsnittet tillhandahåller stream-URL och nyckel, så SplitCam fungerar."),
        ("Vilken bitrate för VirtWish?", "VirtWish publicerar inget officiellt tak; 3500–6000 Kbps i 1080p är säkert. Matcha SplitCams upplösning med den inställda i VirtWish för att undvika omskalning."),
        ("Är SplitCam gratis för VirtWish?", "Ja — gratis, ingen vattenstämpel och ingen tidsgräns. VirtWishs URL-och-nyckel-uppsättning tar bara de minuter som behövs.")]),
    _p("xmodels", "XModels",
       "Sänd på XModels med SplitCam — gratis guide",
       "Sänd på XModels med SplitCam gratis — extern kodare-alternativ i modellkontots inställningar, RTMP-nyckel, scener och overlays.",
       "xmodels, sända xmodels, xmodels broadcasting software, xmodels rtmp, xmodels extern kodare",
       'Så sänder du på <span class="accent">XModels</span> med SplitCam',
       "Sända XModels",
       "Extern kodare-uppsättning för XModels-sändning.",
       "XModels är en cam-streamingplattform med ett inbyggt <strong style='color:var(--text)'>extern kodare-alternativ</strong> i modellkontots inställningar. Gratis <strong style='color:var(--text)'>SplitCam</strong> sänder där med flerkamerascener, overlays och filter i stället för en platt kamera.",
       "Sänd på XModels med SplitCam: installera SplitCam, bygg din scen, slå på extern kodare-alternativet i XModels modellkonto, kopiera server-URL och streamnyckel, klistra in i SplitCam, Go Live."
       "<ol><li>Installera SplitCam.</li><li>Lägg till kamera + scen.</li><li>Slå på extern kodare i XModels-inställningarna.</li><li>Klistra in server-URL + nyckel i SplitCam.</li><li>Tryck Go Live.</li></ol>",
       "I XModels <strong>modellkontoinställningar</strong> slår du på alternativet <strong>sänd via extern kodare</strong>. XModels ger en <strong>streamnyckel</strong> — kopiera den till SplitCam. Om alternativet inte finns där du väntar är XModels support via FAQ-chatt på sajten och <strong>info@xmodels.com</strong>; videon ovan visar det också.",
       [("Det finns i kontoinställningarna", "XModels placerar extern kodare-alternativet i modellkontots inställningar, inte på en separat sändningsskärm."),
        ("Support: chatt + e-post", "XModels har inget stort offentligt hjälpcenter — FAQ-chatt på sajten och info@xmodels.com är de officiella supportkanalerna."),
        ("Stapla overlays i SplitCam", "Tipsmål, namn och sociala mediers handtag lägger du till som scenlager — XModels grundkamera lägger inte till dem."),
        _T_ETH],
       [("Stöder XModels extern kodare?", "Ja — modellkontots inställningar har ett extern kodare-sändningsalternativ som ger en streamnyckel, så SplitCam fungerar."),
        ("Var får jag hjälp med XModels?", "XModels support är via FAQ-chatt på sajten och e-post info@xmodels.com — inget stort offentligt hjälpcenter."),
        ("Vilken bitrate för XModels?", "XModels dokumenterar inga officiella siffror — använd 3500–6000 Kbps i 1080p och kör SplitCams hastighetstest, eftersom XModels support bara är via chatt och e-post."),
        ("Är SplitCam gratis för XModels?", "Ja — gratis, ingen vattenstämpel och ingen tidsgräns, så att sända till XModels europeiska nätverk lägger inte till mjukvarukostnader.")]),
    _p("flirt4free", "Flirt4Free",
       "Sänd på Flirt for Free cam med SplitCam — gratis guide",
       "Sänd på Flirt for Free cam med SplitCam gratis — External Broadcast Form, RTMP URL och Stream Name, scener och overlays.",
       "flirt for free cam, flirt 4 free cam, flirt4free, sända flirt4free, flirt4free external broadcast, flirt4free rtmp",
       'Så sänder du på <span class="accent">Flirt4Free</span> med SplitCam',
       "Sända Flirt4Free",
       "External Broadcast Form-uppsättning för Flirt4Free.",
       "Flirt4Free är en av de äldsta cam-plattformarna, i sändning sedan 90-talet. Den stöder extern sändning officiellt via <strong style='color:var(--text)'>External Broadcast Form</strong> — gratis <strong style='color:var(--text)'>SplitCam</strong> skickar streamen medan formuläret ställer in upplösning och bitrate.",
       "Sänd på Flirt4Free med SplitCam: installera SplitCam, bygg din scen, öppna Flirt4Frees External Broadcast Form, kopiera RTMP URL och Stream Name och ställ in upplösning/bitrate, klistra in i SplitCam, Go Live."
       "<ol><li>Installera SplitCam.</li><li>Lägg till kamera + scen.</li><li>Öppna Flirt4Frees External Broadcast Form.</li><li>Klistra in RTMP URL + Stream Name i SplitCam.</li><li>Tryck Go Live.</li></ol>",
       "I Flirt4Frees modellzon öppnar du <strong>External Broadcast Form</strong>. Till skillnad från de flesta cam-sajter ger Flirt4Free <strong>RTMP URL</strong> och <strong>Stream Name</strong> (inte «nyckel»), plus fält för upplösning och bitrate som du fyller i direkt i formuläret. Kopiera URL och Stream Name till SplitCams fält för server och nyckel.",
       [("Det är Stream Name, inte nyckel", "Flirt4Free kallar sina uppgifter Stream Name. Du klistrar in det i SplitCams streamnyckelfält — funktionen är densamma."),
        ("Ställ in upplösning/bitrate i formuläret", "Flirt4Frees External Broadcast Form har egna fält för upplösning och bitrate — anpassa dem efter SplitCams inställningar så att bilden inte skalas om."),
        ("Plattform med historia", "Flirt4Free har körts sedan 90-talet — dess modellverktyg är mogna, och External Broadcast Form är en dokumenterad del av dem."),
        _T_ETH],
       [("Stöder Flirt4Free extern kodare?", "Ja — officiellt, via External Broadcast Form som ger RTMP URL och Stream Name. SplitCam fungerar som kodare."),
        ("Var får jag Flirt4Frees RTMP-data?", "Från External Broadcast Form i modellzonen — visar RTMP URL, Stream Name och fält för upplösning/bitrate."),
        ("Vilken bitrate för Flirt4Free?", "3500–6000 Kbps i 1080p — ställ in samma värden i External Broadcast Form och i SplitCam."),
        ("Är SplitCam gratis för Flirt4Free?", "Ja — gratis, ingen vattenstämpel och ingen tidsgräns, passar en plattform med historia som Flirt4Free där showerna kan bli långa.")]),
    _p("mfc-alerts", "MFC Alerts",
       "Lägg till MFC Alerts i sändningen med SplitCam",
       "Visa animerade tips-aviseringar i din MyFreeCams-sändning — mfcalerts.com-URL som Browser-lager i gratis SplitCam, ovanför webbkameran.",
       "mfc alerts, myfreecams alerts, lägg till mfc alerts, mfcalerts splitcam, myfreecams tip alerts, myfreecams alerts overlay",
       'Så lägger du till <span class="accent">MFC Alerts</span> i sändningen',
       "Lägg till MFC Alerts",
       "Visa animerade tips-aviseringar i din MyFreeCams-sändning.",
       "MFC Alerts visar animerade effekter i din MyFreeCams-sändning varje gång en tittare skickar ett tips. Det körs som ett <strong style='color:var(--text)'>Browser-lager</strong> inuti gratis <strong style='color:var(--text)'>SplitCam</strong> — ställ in en gång så utlöser tips reaktioner på skärmen i realtid.",
       "Lägg till MFC Alerts med SplitCam: installera SplitCam, lägg till webbkameran, öppna Browser-fliken och ladda mfcalerts.com, kopiera din aviserings-URL, lägg till som Browser-lager ovanför webbkameran, testa sedan med ett testtips."
       "<ol><li>Installera SplitCam.</li><li>Lägg till webbkameran.</li><li>Hämta URL på mfcalerts.com.</li><li>Lägg till som Browser-lager ovanför webbkameran.</li><li>Skicka ett testtips.</li></ol>",
       "I SplitCam öppnar du fliken <strong>Browser</strong> och går till <strong>www.mfcalerts.com</strong>. Logga in eller registrera dig. Använd <strong>Copy to clipboard</strong> för att kopiera din privata aviserings-URL. Klistra in URL:en i SplitCams Browser-fönster och klicka <strong>Add</strong>. Ordna sedan källistan så att <strong>MFC Alerts ligger ovanför webbkameran</strong> (3-prickarsmenyn → Move Up).",
       [("MFC Alerts måste ligga ovanför webbkameran", "Vanligaste felet: om MFC Alerts-lagret ligger under webbkameran i källistan förblir effekten dold. Flytta upp det."),
        ("Konto på mfcalerts.com behövs", "Aviserings-URL:en är privat — registrera dig först på mfcalerts.com om du saknar konto."),
        ("Skicka ett testtips före sändning", "Använd Settings → Send test tip för att säkerställa att overlayen fungerar — upptäck inte felet mitt i showen."),
        _T_ETH],
       [("Vad är MFC Alerts?", "Ett aviseringssystem för MyFreeCams som visar videoeffekter i din sändning när tittare skickar tips — läggs till som ett Browser-overlay i SplitCam."),
        ("Varför visas inte mina MFC Alerts?", "Nästan alltid är det lagerordningen — MFC Alerts Browser-lagret måste ligga ovanför webbkameran i SplitCams källista."),
        ("Behöver jag ett konto för MFC Alerts?", "Ja — registrera dig på mfcalerts.com för att få din privata aviserings-URL."),
        ("Är SplitCam gratis för detta?", "Ja — SplitCam är gratis, ingen vattenstämpel och ingen tidsgräns, och MFC Alerts webbläsar-overlay körs inuti det utan extra kostnad.")],
       steps=[
           ("Installera SplitCam och lägg till webbkameran", "Installera gratis SplitCam för Windows eller macOS, lägg sedan till en <strong>webbkamera</strong> som källa. MFC Alerts ligger som ett lager ovanför denna kamera."),
           ("Öppna Browser-fliken och gå till mfcalerts.com", "I SplitCam öppnar du fliken <strong>Browser</strong> och går till <strong>www.mfcalerts.com</strong>. Logga in, eller registrera dig om du inte har ett mfcalerts.com-konto."),
           ("Kopiera din aviserings-URL", "På mfcalerts.com använder du <strong>Copy to clipboard</strong> för att kopiera din privata aviserings-URL — det är sidan som renderar tips-animationerna."),
           ("Lägg till URL:en som Browser-lager — ovanför webbkameran", "Klistra in URL:en i SplitCams Browser-fönster och klicka <strong>Add</strong>. Ordna sedan källistan så att <strong>MFC Alerts ligger ovanför webbkameran</strong> (3-prickarsmenyn → Move Up). Ligger den under förblir effekten dold."),
           ("Testa med ett testtips", "Öppna <strong>Settings → Send test tip</strong> och säkerställ att aviseringseffekten dyker upp ovanför kameran. Sänd sedan som vanligt på MyFreeCams — riktiga tips utlöser nu animationer."),
       ]),
    _p("lovense", "Lovense",
       "Lägg till Lovense-leksaker i sändningen med SplitCam",
       "Anslut interaktiva Lovense-leksaker till cam-sändningen med gratis SplitCam — Lovense SplitCam Toolset, tips-aviseringar på skärmen, reaktioner.",
       "lägg till lovense i sändningen, lovense cam stream, lovense splitcam, lovense splitcam toolset, lovense interactive toy streaming",
       'Så lägger du till <span class="accent">Lovense-leksaker</span> i sändningen',
       "Lägg till Lovense-leksaker",
       "Anslut interaktiva Lovense-leksaker till din cam-sändning.",
       "Du kör en cam-sändning via gratis <strong style='color:var(--text)'>SplitCam</strong> och parar en <strong style='color:var(--text)'>Lovense</strong>-leksak som reagerar på tokens. Lovense dokumenterar ett officiellt <strong style='color:var(--text)'>Lovense SplitCam Toolset</strong>, och SplitCam erbjuder en officiell Lovense-plugin — integrationen stöds från båda håll.",
       "För att lägga till Lovense-leksaker i sändningen: installera SplitCam och Lovense-mjukvaran, para leksaken, anslut Lovense till cam-plattformen, lägg till Lovense-status som Browser-lager i SplitCam, sänd sedan som vanligt."
       "<ol><li>Installera SplitCam.</li><li>Installera Lovense-mjukvaran och para leksaken.</li><li>Anslut Lovense till din cam-sajt.</li><li>Lägg till Lovense-overlay i SplitCam.</li><li>Tryck Go Live.</li></ol>",
       "Installera Lovense Connect / Lovense Stream (den officiella skrivbordsappen). Slå på leksaken och para via Bluetooth så att appen visar ansluten. I Lovense-appen kopplar du ditt cam-konto så att leksaken reagerar på tittarnas tokens / tips. Lovense ger en overlay-/widget-URL — lägg till som <strong>Browser</strong>-lager i SplitCam-scenen.",
       [("Använd det officiella Lovense SplitCam Toolset", "Lovense publicerar ett särskilt toolset för SplitCam med egen installationsguide — det lägger till overlays för leksaksaktivitet och tips-aviseringar gjorda för SplitCam."),
        ("Uppdatera Lovense Cam Extension", "Toolsetet kräver den senaste Lovense Cam Extension (30.1.4 eller nyare) — uppdatera före sändning."),
        ("Håll leksaken laddad", "Lågt batteri mitt i showen förstör den interaktiva sidan — ladda fullt före sändning."),
        ("Testa token-reaktionen", "Skicka ett litet testtips för att säkerställa att leksaken reagerar innan du öppnar rummet."),
        ("Kolla versionskraven", "Lovense SplitCam Toolset kräver SplitCam 10.4.5 eller nyare. Lovense Cam Extension omfattar officiellt Chaturbate, Stripchat, BongaCams, MyFreeCams och CamSoda — för andra sajter, använd Lovense Generic URL-integration.")],
       [("Stöder Lovense SplitCam officiellt?", "Ja — Lovense dokumenterar ett officiellt «Lovense SplitCam Toolset» med egen installationsguide, och SplitCam erbjuder en officiell Lovense-plugin. Integrationen stöds från båda håll."),
        ("Ansluter leksaken direkt till SplitCam?", "Nej — leksaken paras med Lovense-appen; SplitCam visar Lovense-overlayen och sänder kameran."),
        ("Vilka cam-sajter stöder Lovense?", "Lovense Cam Extension stöder officiellt Chaturbate, Stripchat, BongaCams, MyFreeCams och CamSoda, med varierande stöd för andra — kolla den aktuella listan i Lovense-appen."),
        ("Kan jag visa senaste tips på skärmen?", "Ja — lägg till Lovense widget-URL som Browser-lager i SplitCam.")],
       steps=[
           ("Installera SplitCam", "SplitCam är gratis livesändningsmjukvara för Windows och macOS — kodaren som skickar din video till cam-plattformen. Installera den; ingen vattenstämpel."),
           ("Installera Lovense-mjukvaran och para leksaken", "Installera Lovense Connect / Lovense Stream (den officiella skrivbordsappen). Slå på leksaken och para via Bluetooth så att appen visar ansluten."),
           ("Anslut Lovense till cam-plattformen", "I Lovense-appen kopplar du ditt cam-konto så att leksaken reagerar på tittarnas tokens / tips. De flesta stora cam-plattformar stöds."),
           ("Lägg till Lovense-overlay i SplitCam", "Lovense ger en overlay-/widget-URL. Lägg till som <strong>Browser</strong>-lager i SplitCam-scenen så att tittarna ser leksaksstatus och senaste tips på skärmen."),
           ("Bygg scenen och Go Live", "Lägg till kamera och andra overlays, klistra in cam-plattformens RTMP-nyckel i SplitCam och klicka <strong>Go Live</strong>. Leksaken reagerar på tips i realtid."),
       ]),
    _p("multistream-cams", "Flera cam-sajter",
       "Sänd till flera cam-sajter samtidigt med SplitCam",
       "Sänd till MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat och fler samtidigt med SplitCams gratis multistream. Ett klick, ingen vattenstämpel.",
       "sända till flera cam-sajter, multistream cam sites, sända chaturbate och bongacams samtidigt, multistream cam-mjukvara",
       'Så sänder du till <span class="accent">flera cam-sajter</span> samtidigt',
       "Multistream cam",
       "Sänd till flera cam-sajter samtidigt.",
       "Gratis <strong style='color:var(--text)'>SplitCam</strong> kan sända en kodning till <strong style='color:var(--text)'>flera cam-sajter samtidigt</strong> — MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat och fler. Ingen vattenstämpel, ett klick.",
       "För att sända till flera cam-sajter samtidigt: installera SplitCam, bygg din scen, hämta RTMP-server-URL och streamnyckel för varje cam-sajt, lägg till alla i SplitCams multistream-inställningar, klicka Go Live en gång."
       "<ol><li>Installera SplitCam.</li><li>Lägg till kamera + scen.</li><li>Hämta RTMP-nycklar från varje cam-sajt.</li><li>Lägg till alla nycklar i SplitCams multistream.</li><li>Tryck Go Live en gång.</li></ol>",
       "På varje cam-plattform slår du på extern / RTMP-sändning och kopierar <strong>server-URL</strong> och <strong>streamnyckel</strong>. I SplitCam öppnar du <strong>Stream Settings</strong> och lägger till varje cam-sajt som ett anpassat RTMP-mål — klistra in server-URL och nyckel. Bocka för alla du vill vara live på. Tryck <strong>Go Live</strong>.",
       [("Håll koll på din uppladdning", "Multistream multiplicerar uppladdningsbelastningen. Varje mål använder sin egen bitrate — se till att linjen klarar summan."),
        ("Kolla plattformsreglerna", "Vissa cam-sajter förbjuder samtidig sändning på annat håll — kolla före multistream."),
        ("Kabel — här får det inte falla", "Multistream multiplicerar uppladdningsbelastningen, så ett wifi-avbrott kan fälla alla mål samtidigt. Kabel är inget alternativ här."),
        ("Övervaka hälsomonitorn", "SplitCam visar status per mål — koppla bort en sajt om uppladdningen inte räcker.")],
       [("Är SplitCams multistream gratis?", "Ja — multistream är inbyggd och gratis, ingen avgift per mål, ingen vattenstämpel."),
        ("Hur många cam-sajter kan jag sända till samtidigt?", "Så många som din uppladdningsbandbredd klarar — varje mål använder sin egen bitrate."),
        ("Använder den en moln-relay?", "Nej — SplitCam skickar streamen peer-to-peer direkt från datorn till varje plattforms ingest."),
        ("Saktar multistream ner min dator?", "Kodningen görs en gång och återanvänds; hårdvarukodning håller CPU-belastningen låg. Uppladdningsbandbredden är den verkliga gränsen.")],
       steps=[
           ("Installera SplitCam", "SplitCam är gratis livesändningsmjukvara för Windows och macOS med inbyggd multistream. Installera den — ingen vattenstämpel, ingen registrering."),
           ("Ställ in kamera och scen", "Öppna SplitCam, lägg till webbkameran och bygg en scen med overlays och filter. En scen matar varje mål."),
           ("Hämta RTMP-nycklar från varje cam-sajt", "På varje cam-plattform slår du på extern / RTMP-sändning och kopierar <strong>server-URL</strong> och <strong>streamnyckel</strong>. Upprepa för varje sajt du vill sända till — se respektive plattforms guide för den exakta vägen."),
           ("Lägg till varje mål i SplitCam", "Öppna <strong>Stream Settings</strong> och lägg till varje cam-sajt som ett anpassat RTMP-mål — klistra in server-URL och nyckel. Bocka för alla du vill vara live på."),
           ("Klicka Go Live en gång", "Tryck <strong>Go Live</strong>. SplitCam skickar streamen till varje vald cam-sajt samtidigt, peer-to-peer, från en kodning — utan extra kostnad."),
       ]),
    _p("livejasmin", "LiveJasmin",
       "Sänd på LiveJasmin med SplitCam — Extern HD-kodare",
       "Sänd på LiveJasmin med SplitCam gratis — extern kodare i Model Center, HD 1080p-uppsättning, flerkamerascener och overlays. Ingen vattenstämpel, ingen registrering.",
       "sända livejasmin, livejasmin obs, livejasmin extern kodare, livejasmin rtmp, livejasmin stream key, livejasmin modelluppsättning",
       'Så sänder du på <span class="accent">LiveJasmin</span> med SplitCam',
       "Sända LiveJasmin",
       "Extern kodare-uppsättning för LiveJasmins Model Center som kör enbart HD.",
       "LiveJasmin är Docler Holdings flaggskepp — ett av världens största cam-nätverk och en plattform som kör enbart HD. Den föredragna sändaren är den egna klienten <strong>JasminCAM</strong>, men Model Center exponerar också en standard <strong>External Encoder</strong>-väg som gratis <strong style='color:var(--text)'>SplitCam</strong> kopplar in mot — så du kan sända flerkamerascener, beauty-filter och overlays i samma HD-stream.",
       "Sänd på LiveJasmin med SplitCam: installera SplitCam, bygg din HD-scen, gå till <em>Settings → Broadcast → External Encoder</em> i Model Center, kopiera server-URL och streamnyckel, klistra in i SplitCam, Go Live."
       "<ol><li>Installera SplitCam.</li><li>Lägg till kamera + HD-scen.</li><li>Hämta URL och streamnyckel från Model Center.</li><li>Klistra in i SplitCam.</li><li>Tryck Go Live.</li></ol>",
       "Logga in på <strong>modelcenter.livejasmin.com</strong>, öppna <strong>Settings → Broadcast → External Encoder</strong>. Model Center visar en <strong>server-URL</strong> och en <strong>streamnyckel</strong> kopplade till ditt konto — kopiera båda till SplitCams anpassade RTMP-fält. <strong>Obs:</strong> nya konton måste godkännas (48–72 timmar) innan external encoder-alternativet dyker upp, och plattformen tvingar fram enbart HD-utgång.",
       [("HD — annars åker du ner i rankingen", "LiveJasmin är enbart HD — allt under 1280×720 riskerar att bara visas på listor med sämre betalning, allt under 1080p förlorar «Premium»-statusen. Sikta på 1920×1080 vid 30 fps, 4000–6000 Kbps."),
        ("JasminCAM vs extern kodare", "Doclers egen JasminCAM-klient ger den renaste HD-efterlevnaden, men externa kodare (OBS, SplitCam, vMix) stöds officiellt när ditt konto är godkänt — de låser upp flerkamerascener och overlays som JasminCAM inte klarar."),
        ("Free chat ≠ private show", "Free chat är bara förhandsvisning — ingen nakenhet. Du tjänar pengarna i Private- och Gold show. Planera scenen så att den ser stark ut både påklädd OCH i show-läge."),
        _T_ETH],
       [("Stöder LiveJasmin officiellt externa kodare som SplitCam?", "Ja — Model Center har en External Encoder-flik under Settings → Broadcast. JasminCAM är rekommenderad klient, men OBS, SplitCam och andra RTMP-kodare listas uttryckligen som stödda så fort ditt modellkonto är godkänt."),
        ("Var hittar jag min streamnyckel för LiveJasmin?", "Inne i Model Center: Settings → Broadcast → External Encoder. Både server-URL och den unika streamnyckeln visas där — kopiera båda till SplitCams anpassade RTMP-fält. Nyckeln är kopplad till ditt konto; behandla den som ett lösenord."),
        ("Vilken bitrate ska jag köra på LiveJasmin?", "LiveJasmin är enbart HD — sikta på 1920×1080 vid 30 fps, 4000–6000 Kbps med nyckelbildruta varannan sekund. Allt märkbart under det tappar Premium-etiketten och åker ner i rankingen."),
        ("Är SplitCam gratis att köra mot LiveJasmin?", "Ja — SplitCam är gratis, ingen vattenstämpel och ingen tidsgräns. Den enda «kostnaden» är att leva upp till LiveJasmins HD-krav, vilket SplitCam fixar nativt med 1080p-scenkomposition och beauty-filter.")],
       steps=[
           ("Ladda ner och installera SplitCam", "SplitCam är gratis livesändningsmjukvara för Windows och macOS — ingen registrering, inget kort, ingen vattenstämpel. Det är kodaren som skickar din HD-video till LiveJasmin."),
           ("Bygg din HD-scen", "Öppna SplitCam och lägg till webbkameran i 1080p-läge. Lägg på overlays, text, en andra kamera eller din mobil, beauty-filter eller en AI-bakgrund — LiveJasmin kräver HD-kvalitet och din komponerade scen ska se premium ut både under free chat OCH i privata shower."),
           ("Hämta din LiveJasmin-URL och streamnyckel", "Logga in på <strong>modelcenter.livejasmin.com</strong> (ditt konto måste vara godkänt först — vanligtvis 48–72 timmar efter registrering). Öppna <strong>Settings → Broadcast → External Encoder</strong>. Sidan visar en <strong>server-URL</strong> och en unik <strong>streamnyckel</strong>. Kopiera båda."),
           ("Koppla SplitCam till LiveJasmin", "I SplitCam öppnar du <strong>Stream Settings</strong> och klistrar in LiveJasmins server-URL och streamnyckel i de anpassade RTMP-fälten. Sätt bitrate till 4000–6000 Kbps vid 1920×1080, 30 fps, med nyckelbildruta varannan sekund. Kör det inbyggda hastighetstestet först — HD-streamar är krävande."),
           ("Klicka Go Live", "Tryck <strong>Go Live</strong> i SplitCam och gå sedan online i LiveJasmins Model Center. Inom cirka 10 sekunder når din HD-feed LiveJasmins nätverk. Kommande sändningar är ett klick — öppna SplitCam, Go Live, gå online på LiveJasmin."),
       ]),
    _p("myfreecams", "MyFreeCams",
       "Så sänder du på MyFreeCams (MFC) med SplitCam — kringgå Model Web Broadcaster",
       "Sänd på MyFreeCams med gratis SplitCam — extern broadcaster via Model Admin, MFC:s tokenekonomi, flerkamerasceer, overlays. Ingen vattenstämpel, ingen registrering.",
       "myfreecams sändning, mfc extern broadcaster, myfreecams obs, mfc rtmp, mfc streamnyckel, model admin, mfc token",
       'Så sänder du på <span class="accent">MyFreeCams</span> med SplitCam',
       "Sänd på MyFreeCams",
       "Konfiguration av extern broadcaster för MFC:s tokenbaserade Model Admin.",
       "MFC är en av de äldsta cam-plattformarna — ren tokenekonomi, ingen utdragen modellgranskning och en lojal bas av Premium-medlemmar. Standard <strong>Model Web Broadcaster</strong> är ett enkamerat browserverktyg, men <strong>Model Admin</strong> exponerar även en <strong>External Broadcaster</strong>-option som gratis <strong style='color:var(--text)'>SplitCam</strong> kopplar till — vilket låser upp flerkamerasceer, overlays och filter på samma tokenstream.",
       "Sänd på MyFreeCams med SplitCam: installera, bygg scenen, i Model Admin → Broadcaster växla Web till <em>External Broadcaster</em>, kopiera server-URL och streamnyckel, klistra in i SplitCam, Go Live."
       "<ol><li>Installera SplitCam.</li><li>Lägg till kamera och overlays.</li><li>Hämta URL och nyckel från Model Admin.</li><li>Klistra in i SplitCam.</li><li>Tryck Go Live.</li></ol>",
       "Logga in på MyFreeCams, öppna <strong>Model Admin → Broadcaster</strong> och växla från <strong>Web</strong> till <strong>External Broadcaster</strong>. Sidan visar en server-URL (rtmp://publish.myfreecams.com…) och en streamnyckel knutna till modellkontot. Kopiera båda till SplitCams anpassade RTMP-fält.",
       [("MFC är ren tipsekonomi i tokens, inte prenumerationer", "Kärnan i intäkterna är tips i free chat — Premium-medlemmar kan gå in i private, men brödfödan är tokens i öppen chatt. Bygg scenen för konstant tippingsuppmaning, inte för korta «show för pengar»."),
        ("Web vs External Broadcaster", "Standard Web Broadcaster är en kamera i webbläsaren — snabbt men magert. External Broadcaster via SplitCam, OBS eller vMix låser upp flerkamerasceer, overlays och beauty-filter på samma tokenstream."),
        ("MFC Alerts-integration", "Lägg URL:en från mfcalerts.com som ett Browser-lager över kameran i SplitCam — du får animerade tipsalerts direkt i bilden, utan att växla fönster och utan extra plugins."),
        _T_ETH],
       [("Stöder MFC officiellt externa broadcasters som SplitCam?", "Ja — Model Admin har en External Broadcaster-option med standard RTMP-server-URL och streamnyckel. OBS, SplitCam, vMix — allt fungerar efter en enkel växling Web → External Broadcaster."),
        ("Var hittar jag min MFC-streamnyckel?", "Model Admin → Broadcaster → växla till External Broadcaster. Server-URL och streamnyckel dyker upp direkt på samma sida. Kopiera båda till SplitCams anpassade RTMP-fält — nyckeln är knuten till ditt konto, behandla den som ett lösenord."),
        ("Vilken bitrate för MFC?", "Upp till runt 6000 Kbps med nyckelbildruta varannan sekund. Tryck ut 1920×1080 vid 30 fps och 3500–6000 Kbps — din faktiska uppladdning är gränsen, inte MFC. Kör SplitCams inbyggda hastighetstest först."),
        ("Är SplitCam gratis för MFC?", "Ja — SplitCam är gratis, ingen vattenstämpel, ingen tidsgräns. External Broadcaster på MFC-sidan är också gratis — det är standard RTMP, inga extraavgifter.")],
       steps=[
           ("Ladda ner och installera SplitCam", "SplitCam är gratis livesändningsmjukvara för Windows och macOS — ingen registrering, inget kort, ingen vattenstämpel. Det är encodern som skickar din video till MyFreeCams."),
           ("Bygg scenen", "Öppna SplitCam och lägg till kameran, overlays, en andra kamera eller mobil, beauty-filter eller AI-bakgrund. Lägg in URL:en från <strong>mfcalerts.com</strong> som ett Browser-lager över kameran — animerade tipsalerts visas direkt i streamen."),
           ("Hämta MFC-URL och streamnyckel", "Logga in på MyFreeCams, öppna <strong>Model Admin → Broadcaster</strong> och växla från <strong>Web</strong> till <strong>External Broadcaster</strong>. Kopiera server-URL (rtmp://publish.myfreecams.com…) och streamnyckel."),
           ("Koppla SplitCam till MFC", "I SplitCam öppnar du <strong>Stream Settings</strong> och klistrar in MFC:s URL och streamnyckel i de anpassade RTMP-fälten. Sätt bitrate till 3500–6000 Kbps vid 1920×1080, 30 fps, med nyckelbildruta varannan sekund. Kör det inbyggda hastighetstestet först."),
           ("Klicka Go Live", "Tryck <strong>Go Live</strong> i SplitCam — inom cirka 10 sekunder når din feed MFC. Kommande sändningar är ett klick: öppna SplitCam, Go Live."),
       ]),
    _p("cherry-tv", "Cherry.tv",
       "Så sänder du på Cherry.tv med SplitCam — Web3-vänlig extern encoder",
       "Sänd på Cherry.tv med gratis SplitCam — extern encoder via Streamer Dashboard, kryptovänlig cam-plattform, flerkamerasceer. Ingen vattenstämpel, ingen registrering.",
       "cherry tv sändning, cherry.tv obs, cherry tv extern encoder, cherry.tv rtmp, cherry.tv streamnyckel, cherry tv streamer, web3 cam",
       'Så sänder du på <span class="accent">Cherry.tv</span> med SplitCam',
       "Sänd på Cherry.tv",
       "Konfiguration av extern encoder för Cherry.tvs Streamer Dashboard.",
       "Cherry.tv är en nyare, snabbväxande cam-plattform med tydlig Web3-vinkel — kryptovänliga utbetalningar och lägre tröskel än hos äldre nätverk som LiveJasmin. Standardbroadcastern är webbläsarbaserad, men <strong>Streamer Dashboard</strong> exponerar även en standardväg via extern encoder som gratis <strong style='color:var(--text)'>SplitCam</strong> kopplar till — vilket låter dig sända med flerkamerasceer, overlays och filter.",
       "Sänd på Cherry.tv med SplitCam: installera SplitCam, bygg scenen, i Streamer Dashboard → <em>Broadcast Settings → External Encoder</em> kopiera URL och nyckel, klistra in i SplitCam, Go Live."
       "<ol><li>Installera SplitCam.</li><li>Lägg till kamera och overlays.</li><li>Hämta URL och nyckel från Streamer Dashboard.</li><li>Klistra in i SplitCam.</li><li>Tryck Go Live.</li></ol>",
       "Logga in på ditt streamerkonto på Cherry.tv, öppna <strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong>. Server-URL och streamnyckel är knutna till ditt konto. Nya konton behöver först en grundläggande verifiering (vanligtvis snabbt — Cherry.tv har lättare onboarding än äldre cam-nätverk) innan External Encoder-alternativet är fullt aktivt.",
       [("Lättare ingång, växande trafik", "Ingen 72-timmars Docler-granskning — bra läge att bygga följarbas innan konkurrensen drar åt. Nya konton får ofta hyfsad synlighet i listningen."),
        ("Krypto-utbetalningar vid sidan av vanlig fiat", "Cherry.tv erbjuder kryptoutbetalningar parallellt med vanliga banköverföringar — användbart i regioner där traditionella cam-nätverks utbetalningar är långsamma eller begränsade."),
        ("Browser-broadcaster vs extern", "Standard browser-broadcaster är bekväm men en ensam källa. SplitCam via External Encoder låser upp flerkamerasceer, overlays, beauty-filter och AI-bakgrund — det är skillnaden mellan «vanlig stream» och premium-scen."),
        _T_ETH],
       [("Stöder Cherry.tv externa encoders som SplitCam?", "Ja — Streamer Dashboard har External Encoder under Broadcast Settings med standard RTMP-server-URL och streamnyckel. OBS, SplitCam och andra RTMP-encoders ansluter utan problem."),
        ("Var hittar jag min Cherry.tv-streamnyckel?", "Streamer Dashboard → Broadcast Settings → External Encoder. Både URL och nyckel visas på samma sida — kopiera båda till SplitCams anpassade RTMP-fält."),
        ("Vilken bitrate för Cherry.tv?", "3500–6000 Kbps vid 1920×1080, 30 fps, med nyckelbildruta varannan sekund. Kör SplitCams inbyggda hastighetstest först för att bekräfta att uppladdningen håller vald bitrate stabilt."),
        ("Är SplitCam gratis för Cherry.tv?", "Ja — SplitCam är gratis, ingen vattenstämpel, ingen tidsgräns. External Encoder på Cherry.tv-sidan är också gratis.")],
       steps=[
           ("Ladda ner och installera SplitCam", "SplitCam är gratis livesändningsmjukvara för Windows och macOS — ingen registrering, inget kort, ingen vattenstämpel. Det är encodern som skickar din video till Cherry.tv."),
           ("Bygg scenen", "Öppna SplitCam och lägg till kameran, overlays, eventuellt en andra kamera eller mobil, beauty-filter och AI-bakgrund. Cherry.tvs publik är yngre och plattformsvan — en polerad scen hjälper dig sticka ut."),
           ("Hämta Cherry.tv-URL och streamnyckel", "Logga in på ditt streamerkonto på Cherry.tv, öppna <strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong>. Kopiera server-URL och streamnyckel."),
           ("Koppla SplitCam till Cherry.tv", "I SplitCam öppnar du <strong>Stream Settings</strong> och klistrar in URL och nyckel i de anpassade RTMP-fälten. Sätt bitrate till 3500–6000 Kbps vid 1920×1080, 30 fps, med nyckelbildruta varannan sekund. Kör det inbyggda hastighetstestet först."),
           ("Klicka Go Live", "Tryck <strong>Go Live</strong> i SplitCam och gå sedan online i Streamer Dashboard på Cherry.tv. Inom cirka 10 sekunder når din feed Cherry.tv. Kommande sändningar är ett klick."),
       ]),
    _p("amateurtv", "AmateurTV",
       "Så sänder du på AmateurTV med SplitCam — spansktalande cam-nätverk",
       "Sänd på AmateurTV med gratis SplitCam — External Encoder via Model Panel, spansktalande cam-nätverk för Spanien och Latinamerika, flerkamerasceer. Ingen vattenstämpel, ingen registrering.",
       "amateurtv sändning, amateur.tv obs, amateurtv external encoder, amateurtv rtmp, amateurtv streamnyckel, modelos amateur tv",
       'Så sänder du på <span class="accent">AmateurTV</span> med SplitCam',
       "Sänd på AmateurTV",
       "Konfiguration av External Encoder för AmateurTVs spansktalande nätverk.",
       "AmateurTV är det ledande spansktalande cam-nätverket — stark publik i Spanien, Mexiko, Argentina och hela Latinamerika. Standardbroadcastern i Model Panel fungerar i webbläsaren, men exponerar även en standardväg via <strong>External Encoder</strong> som gratis <strong style='color:var(--text)'>SplitCam</strong> kopplar till — vilket låter dig sända med flerkamerasceer, beauty-filter och overlays till en hispanofon publik som USA-centrerade nätverk inte betjänar väl.",
       "Sänd på AmateurTV med SplitCam: installera SplitCam, bygg scenen, i Model Panel öppna <em>Broadcast Settings → External Encoder</em>, kopiera server-URL och streamnyckel, klistra in i SplitCam, Go Live."
       "<ol><li>Installera SplitCam.</li><li>Lägg till kamera och scen.</li><li>Hämta URL och nyckel från Model Panel.</li><li>Klistra in i SplitCam.</li><li>Tryck Go Live.</li></ol>",
       "Logga in på ditt modellkonto på AmateurTV, öppna <strong>Model Panel</strong> och gå till <strong>Broadcast Settings → External Encoder</strong>. Sidan visar en <strong>server-URL</strong> och en <strong>streamnyckel</strong> knutna till ditt konto — kopiera båda till SplitCams anpassade RTMP-fält. Nya modellkonton behöver ID-verifiering innan första sändning.",
       [("Hispanofon publik först", "AmateurTVs trafik är överväldigande spansktalande — Spanien dagtid, LatAm under amerikansk kvällstid. Streamtitlar, scentexter och overlays på spanska överträffar dramatiskt enbart engelska versioner på det här nätverket."),
        ("LatAm-tidszon är din prime", "Trafiktoppen korrelerar med kvällstid i LatAm (UTC-3 till UTC-6). Är du flexibel träffar sena CET-kvällar / tidiga asiatiska morgnar både Spanien- och LatAm-toppen."),
        ("Solid mellanskikts-payout", "Inte branschens högsta RPM, men stabilt — AmateurTV betalar pålitligt och den hispanofona nischen har mindre konkurrens än amerikanska toppnätverk."),
        _T_ETH],
       [("Stöder AmateurTV officiellt externa encoders som SplitCam?", "Ja — Model Panel har External Encoder under Broadcast Settings. AmateurTV ger en standard RTMP-server-URL och streamnyckel; OBS, SplitCam, vMix och andra RTMP-encoders ansluter alla."),
        ("Var hittar jag min AmateurTV-streamnyckel?", "Model Panel → Broadcast Settings → External Encoder. Både server-URL och streamnyckel visas där. Kopiera båda till SplitCams anpassade RTMP-fält. Nyckeln är knuten till kontot."),
        ("Vilken bitrate för AmateurTV?", "Standard cam-inställningar — tryck ut 1920×1080 vid 30 fps, 3500–6000 Kbps med nyckelbildruta varannan sekund. Kör SplitCams inbyggda hastighetstest först."),
        ("Är SplitCam gratis för AmateurTV?", "Ja — SplitCam är gratis, ingen vattenstämpel, ingen tidsgräns. External Encoder på AmateurTV-sidan slås på gratis.")],
       steps=[
           ("Ladda ner och installera SplitCam", "SplitCam är gratis livesändningsmjukvara för Windows och macOS — ingen registrering, inget kort, ingen vattenstämpel. Det är encodern som skickar din video till AmateurTV."),
           ("Bygg scenen", "Öppna SplitCam och lägg till kameran. Lägg till overlays, text, en andra kamera eller mobil, beauty-filter eller AI-bakgrund. Använd spansk text på overlays — AmateurTVs publik är hispanofon."),
           ("Hämta AmateurTV-URL och streamnyckel", "Logga in på ditt modellkonto på AmateurTV, öppna <strong>Model Panel</strong>, gå till <strong>Broadcast Settings → External Encoder</strong>. Sidan visar en <strong>server-URL</strong> och en unik <strong>streamnyckel</strong>. Kopiera båda."),
           ("Koppla SplitCam till AmateurTV", "I SplitCam öppnar du <strong>Stream Settings</strong> och klistrar in AmateurTVs URL och streamnyckel i de anpassade RTMP-fälten. Sätt bitrate till 3500–6000 Kbps vid 1920×1080, 30 fps, med nyckelbildruta varannan sekund. Kör det inbyggda hastighetstestet först."),
           ("Klicka Go Live", "Tryck <strong>Go Live</strong> i SplitCam och gå sedan online i Model Panel på AmateurTV. Inom cirka 10 sekunder når din feed nätverket. Kommande sändningar är ett klick — öppna SplitCam, Go Live."),
       ]),
    _p("camster", "Camster",
       "Så sänder du på Camster med SplitCam — External Encoder via Model Hub",
       "Sänd på Camster med gratis SplitCam — External Encoder via Model Hub, etablerad cam-plattform i mellanskiktet, flerkamerasceer och overlays. Ingen vattenstämpel, ingen registrering.",
       "camster sändning, camster.com obs, camster external encoder, camster rtmp, camster streamnyckel, camster model hub",
       'Så sänder du på <span class="accent">Camster</span> med SplitCam',
       "Sänd på Camster",
       "Konfiguration av External Encoder för Camsters Model Hub.",
       "Camster är en etablerad cam-plattform i mellanskiktet — mindre än Chaturbate eller LiveJasmin men med en lojal användarbas och rättvisa utbetalningar. Standardbroadcastern i Model Hub fungerar i webbläsaren, men exponerar även en standardväg via <strong>External Encoder</strong> som gratis <strong style='color:var(--text)'>SplitCam</strong> kopplar till — vilket låter dig sända med flerkamerasceer, overlays och filter som den inbyggda broadcastern inte klarar.",
       "Sänd på Camster med SplitCam: installera SplitCam, bygg scenen, i Model Hub öppna <em>Broadcast Settings → External Encoder</em>, kopiera server-URL och streamnyckel, klistra in i SplitCam, Go Live."
       "<ol><li>Installera SplitCam.</li><li>Lägg till kamera och scen.</li><li>Hämta URL och nyckel från Model Hub.</li><li>Klistra in i SplitCam.</li><li>Tryck Go Live.</li></ol>",
       "Logga in på ditt modellkonto på Camster, öppna <strong>Model Hub</strong> och gå till <strong>Broadcast Settings → External Encoder</strong>. Sidan visar en <strong>server-URL</strong> och en <strong>streamnyckel</strong> knutna till ditt konto — kopiera båda till SplitCams anpassade RTMP-fält. Nyckeln är kontobunden; behandla den som ett lösenord.",
       [("Mellanskikt betyder mindre konkurrens", "Camster har stadig trafik men färre broadcasters än toppnätverken — lättare att landa på förstasidan med en polerad scen och konsekvent schema."),
        ("Browser-broadcaster vs extern", "Standardbroadcastern i webbläsaren är enkamerakälla. SplitCam via External Encoder låser upp flerkamerasceer, overlays, beauty-filter och AI-bakgrund."),
        ("Stabila utbetalningar, rättvisa splits", "Camsters revenue split är rättvis för mellanskiktet — inte branschens högsta, men pålitliga månadsutbetalningar och få modellklagomål om betalningsförseningar."),
        _T_ETH],
       [("Stöder Camster officiellt externa encoders som SplitCam?", "Ja — Model Hub har External Encoder under Broadcast Settings. Standard RTMP-server-URL och streamnyckel; OBS, SplitCam och andra RTMP-encoders ansluter alla."),
        ("Var hittar jag min Camster-streamnyckel?", "Model Hub → Broadcast Settings → External Encoder. Både server-URL och streamnyckel visas där. Kopiera båda till SplitCams anpassade RTMP-fält."),
        ("Vilken bitrate för Camster?", "Standard cam-inställningar — tryck ut 1920×1080 vid 30 fps, 3500–6000 Kbps med nyckelbildruta varannan sekund. Kör SplitCams inbyggda hastighetstest först."),
        ("Är SplitCam gratis för Camster?", "Ja — SplitCam är gratis, ingen vattenstämpel, ingen tidsgräns. External Encoder på Camster-sidan är gratis.")],
       steps=[
           ("Ladda ner och installera SplitCam", "SplitCam är gratis livesändningsmjukvara för Windows och macOS — ingen registrering, inget kort, ingen vattenstämpel."),
           ("Bygg scenen", "Öppna SplitCam och lägg till kameran. Lägg till overlays, text, en andra kamera eller mobil, beauty-filter eller AI-bakgrund — allt appliceras live."),
           ("Hämta Camster-URL och streamnyckel", "Logga in på ditt modellkonto på Camster, öppna <strong>Model Hub</strong>, gå till <strong>Broadcast Settings → External Encoder</strong>. Sidan visar en <strong>server-URL</strong> och en unik <strong>streamnyckel</strong>. Kopiera båda."),
           ("Koppla SplitCam till Camster", "I SplitCam öppnar du <strong>Stream Settings</strong> och klistrar in Camsters URL och streamnyckel i de anpassade RTMP-fälten. Sätt bitrate till 3500–6000 Kbps vid 1920×1080, 30 fps, med nyckelbildruta varannan sekund. Kör det inbyggda hastighetstestet först."),
           ("Klicka Go Live", "Tryck <strong>Go Live</strong> i SplitCam och gå sedan online i Model Hub på Camster. Inom cirka 10 sekunder når din feed Camster."),
       ]),
    _p("camversity", "Camversity",
       "Så sänder du på Camversity med SplitCam — External Encoder via Performer Dashboard",
       "Sänd på Camversity med gratis SplitCam — External Encoder via Performer Dashboard, växande oberoende cam-plattform, flerkamerasceer. Ingen vattenstämpel, ingen registrering.",
       "camversity sändning, camversity obs, camversity external encoder, camversity rtmp, camversity streamnyckel, camversity performer",
       'Så sänder du på <span class="accent">Camversity</span> med SplitCam',
       "Sänd på Camversity",
       "Konfiguration av External Encoder för Camversitys Performer Dashboard.",
       "Camversity är en växande oberoende cam-plattform med fokus på performer-vänliga verktyg och lägre provisioner än äldre nätverk. Standardbroadcastern i Performer Dashboard fungerar i webbläsaren, men exponerar även en standardväg via <strong>External Encoder</strong> som gratis <strong style='color:var(--text)'>SplitCam</strong> kopplar till — vilket låter dig sända med flerkamerasceer, overlays och filter.",
       "Sänd på Camversity med SplitCam: installera SplitCam, bygg scenen, i Performer Dashboard öppna <em>Stream Settings → External Encoder</em>, kopiera server-URL och streamnyckel, klistra in i SplitCam, Go Live."
       "<ol><li>Installera SplitCam.</li><li>Lägg till kamera och scen.</li><li>Hämta URL och nyckel från Performer Dashboard.</li><li>Klistra in i SplitCam.</li><li>Tryck Go Live.</li></ol>",
       "Logga in på ditt performerkonto på Camversity, öppna <strong>Performer Dashboard</strong> och gå till <strong>Stream Settings → External Encoder</strong>. Sidan visar en <strong>server-URL</strong> och en <strong>streamnyckel</strong> knutna till ditt konto — kopiera båda till SplitCams anpassade RTMP-fält. Nya konton behöver standard ID-verifiering innan första sändning.",
       [("Performer-vänliga splits", "Camversitys revenue split är mer förmånlig för performers än äldre nätverks — värt att jämföra med din nuvarande huvudplattform om du är tidig i din cam-karriär."),
        ("Lättare onboarding än Docler", "Camversitys verifiering är snabbare än LiveJasmins 48–72 timmars godkännande, men fortfarande seriös (inga slumpmässiga / overifierade modeller). Bra mellanväg."),
        ("Bygg en scen, inte bara en webbkamera", "Camversitys standard Performer Dashboard-broadcaster är enkällskanal. SplitCam via External Encoder låser upp flerkamerasceer, overlays och beauty-filter."),
        _T_ETH],
       [("Stöder Camversity officiellt externa encoders som SplitCam?", "Ja — Performer Dashboard har External Encoder under Stream Settings. Standard RTMP-server-URL och streamnyckel; OBS, SplitCam, vMix ansluter alla."),
        ("Var hittar jag min Camversity-streamnyckel?", "Performer Dashboard → Stream Settings → External Encoder. Både server-URL och streamnyckel visas där."),
        ("Vilken bitrate för Camversity?", "Tryck ut 1920×1080 vid 30 fps, 3500–6000 Kbps med nyckelbildruta varannan sekund. Kör SplitCams inbyggda hastighetstest först."),
        ("Är SplitCam gratis för Camversity?", "Ja — SplitCam är gratis, ingen vattenstämpel, ingen tidsgräns. External Encoder på Camversity-sidan är gratis.")],
       steps=[
           ("Ladda ner och installera SplitCam", "SplitCam är gratis livesändningsmjukvara för Windows och macOS — ingen registrering, inget kort, ingen vattenstämpel."),
           ("Bygg scenen", "Öppna SplitCam och lägg till kameran. Lägg till overlays, text, en andra kamera eller mobil, beauty-filter eller AI-bakgrund."),
           ("Hämta Camversity-URL och streamnyckel", "Logga in på ditt performerkonto på Camversity, öppna <strong>Performer Dashboard</strong>, gå till <strong>Stream Settings → External Encoder</strong>. Sidan visar en <strong>server-URL</strong> och en unik <strong>streamnyckel</strong>. Kopiera båda."),
           ("Koppla SplitCam till Camversity", "I SplitCam öppnar du <strong>Stream Settings</strong> och klistrar in Camversitys URL och streamnyckel i de anpassade RTMP-fälten. Sätt bitrate till 3500–6000 Kbps vid 1920×1080, 30 fps, med nyckelbildruta varannan sekund."),
           ("Klicka Go Live", "Tryck <strong>Go Live</strong> i SplitCam och gå sedan online i Performer Dashboard. Inom cirka 10 sekunder når din feed Camversity."),
       ]),
]
