# -*- coding: utf-8 -*-
"""Czech (cs) content for cam-streaming-guides. Native Czech, 20 platforms."""

_T_ETH = ("Použijte drátové připojení", "Ethernet poráží Wi-Fi při dlouhém vysílání — ztracené snímky "
          "znamenají ztracené tipy. Zapojte kabel do počítače, který vysílá.")
_T_TEST = ("Nejdřív si udělejte soukromý test", "Spusťte krátké testovací vysílání, abyste zkontrolovali "
           "kameru, zvuk, kompozici a překryvy, než otevřete místnost divákům.")

def _p(slug, name, title, desc, kw, h1html, h1short, card, intro, quick, key_how, tips, faq, steps=None):
    d = {"slug": slug, "name": name, "title": title, "desc": desc, "kw": kw,
         "h1html": h1html, "h1short": h1short, "card": card, "intro": intro,
         "quick": quick, "key_how": key_how, "tips": tips, "faq": faq}
    if steps: d["steps"] = steps
    return d

PLATFORMS_CS = [
    _p("chaturbate", "Chaturbate",
       "Vysílání na Chaturbate se SplitCam — Token a RTMP",
       "Vysílání na Chaturbate se SplitCam zdarma — broadcast token, RTMP, vícekamerové scény a překryvy. Bez vodoznaku, bez registrace.",
       "vysílání chaturbate, chaturbate broadcast token, chaturbate rtmp obs, chaturbate externí kodér, chaturbate live",
       'Jak vysílat na <span class="accent">Chaturbate</span> se SplitCam',
       "Vysílání Chaturbate",
       "Nastavení založené na tokenu s externím kodérem na Chaturbate.",
       "Chaturbate je jedna z největších cam platforem, postavená na ekonomice tokenů. Její prohlížečový nástroj pro vysílání je jen plochý nástroj s jednou kamerou — přechod na <strong style='color:var(--text)'>externí kodér</strong> se SplitCam zdarma odemkne vícekamerové scény, překryvy a filtry ve stejném vysílání založeném na tokenech.",
       "Vysílání na Chaturbate se SplitCam: nainstalujte SplitCam, sestavte scénu, na Chaturbate otevřete <em>Broadcast Yourself → My Broadcast</em>, zkopírujte broadcast token, vložte do SplitCam, Go Live."
       "<ol><li>Nainstalujte SplitCam.</li><li>Přidejte kameru + scénu.</li><li>Zkopírujte broadcast token z Chaturbate.</li><li>Vložte do SplitCam.</li><li>Stiskněte Go Live.</li></ol>",
       "Na Chaturbate klikněte na <strong>Broadcast Yourself</strong>, abyste přešli na stránku <strong>My Broadcast</strong>, poté <strong>View RTMP/OBS broadcast information and stream key</strong>. Klíč se zobrazí jako <strong>broadcast token</strong> — zkopírujte ho. Zacházejte s ním jako s heslem; nikdy ho nesdílejte.",
       [("Token je klíč", "Chaturbate používá váš broadcast token, ne obecný stream key. Zacházejte s ním jako s heslem a resetujte ho, pokud unikne."),
        ("Hodně rezervy", "RTMP ingest Chaturbate přijímá až 4K, 60 fps a vysoký bitrate — limitem je váš upload, ne platforma. Klíčový snímek každé 2 sekundy."),
        _T_ETH, _T_TEST],
       [("Povoluje Chaturbate OBS / externí kodér?", "Ano — Chaturbate oficiálně podporuje externí kodéry a má vlastní článek «How do I set up OBS?». Zapněte to přes «Use External Encoder to Broadcast» v nastavení vysílání."),
        ("Kde je můj stream key Chaturbate?", "Broadcast Yourself → My Broadcast → View RTMP/OBS broadcast information and stream key. Klíčem je váš broadcast token."),
        ("Jaký bitrate pro Chaturbate?", "3500–6000 Kbps v 1080p je víc než dost. Strop Chaturbate je vysoký — skutečným limitem je váš upload; nejdřív spusťte vestavěný test rychlosti SplitCam."),
        ("Je SplitCam zdarma pro Chaturbate?", "Ano — zcela zdarma, bez vodoznaku a bez časového limitu: kodér nesnižuje vaše výdělky v tokenech.")]),
    _p("cam4", "CAM4",
       "Vysílání na CAM4 se SplitCam — External Encoder",
       "Vysílání na CAM4 se SplitCam zdarma — External Encoder, stream key, geoblokování a překryvy. Bez vodoznaku.",
       "vysílání cam4, cam4.com, cam4 external encoder, cam4 stream key, cam4 rtmp obs",
       'Jak vysílat na <span class="accent">CAM4</span> se SplitCam',
       "Vysílání CAM4",
       "External Encoder na CAM4 s geo kontrolou.",
       "CAM4 je globální cam-and-earn platforma s vestavěnou geo kontrolou — vysílání můžete skrýt v určitých zemích. Vysílání přes SplitCam zdarma jako externí kodér odemkne přepínání scén a překryvy, které základní nástroj nemá.",
       "Vysílání na CAM4 se SplitCam: nainstalujte SplitCam, sestavte scénu, na CAM4 otevřete <em>Broadcast &amp; Earn Money → Start Broadcast → External Encoder</em>, Get Stream Key, vložte do SplitCam, Go Live."
       "<ol><li>Nainstalujte SplitCam.</li><li>Přidejte kameru + scénu.</li><li>Získejte stream key z CAM4.</li><li>Vložte do SplitCam.</li><li>Stiskněte Go Live.</li></ol>",
       "Na CAM4 klikněte na <strong>Broadcast</strong> → <strong>Broadcast &amp; Earn Money</strong> → <strong>Start Broadcast</strong>, poté <strong>External Encoder</strong> nahoře. Vyplňte datum narození, pohlaví a zemi, použijte <strong>Get Stream Key</strong> a zkopírujte. Zelený posuvník v Stream Settings SplitCam znamená připojení.",
       [("Nastavte geo omezení", "CAM4 umožňuje skrýt vysílání v určitých zemích a regionech — nastavte to na straně CAM4 před go-live."),
        ("Sledujte zelený posuvník", "Nastavení CAM4 zobrazí zelený posuvník v Stream Settings SplitCam, když je klíč přijat — červená = zkontrolujte klíč."),
        ("Nižší bitrate než obvykle", "RTMP ingest CAM4 omezuje bitrate videa na zhruba 3000 Kbps — méně než většina cam stránek. Netlačte výš."),
        _T_ETH],
       [("Podporuje CAM4 OBS / externí kodér oficiálně?", "Ano — CAM4 má oficiální OBS Guide na stránce podpory a doporučuje External Encoder pro nejlepší zážitek. SplitCam používá stejnou RTMP cestu."),
        ("Můžu geo-blokovat vysílání CAM4?", "Ano — CAM4 má vestavěná geo omezení pro skrytí vysílání v určitých zemích. Nastavte to na CAM4, ne ve SplitCam."),
        ("Kde je stream key CAM4?", "Broadcast → Broadcast & Earn Money → Start Broadcast → External Encoder → Get Stream Key."),
        ("Jaký bitrate pro CAM4?", "Nižší než průměr — RTMP ingest CAM4 omezuje ~3000 Kbps při 30 fps s klíčovým snímkem po 1 sekundě. Oficiální tabulka radí nepřekračovat ~3000.")]),
    _p("bongacams", "BongaCams",
       "Vysílání na BongaCams se SplitCam — External Encoder",
       "Vysílání na BongaCams se SplitCam zdarma — External Encoder, vícekamerové scény, překryvy a AI pozadí. Bez vodoznaku.",
       "bongacams, bongcams, vysílání bongacams, bongacams external encoder, bongacams rtmp obs",
       'Jak vysílat na <span class="accent">BongaCams</span> se SplitCam',
       "Vysílání BongaCams",
       "Nastavení External Encoder pro BongaCams.",
       "BongaCams je globální cam platforma. Vysílání externím kodérem není vždy zapnuté — po aktivaci SplitCam zdarma ovládá vysílání s vícekamerovými scénami, překryvy a AI pozadími.",
       "Vysílání na BongaCams se SplitCam: nainstalujte SplitCam, sestavte scénu, na BongaCams otevřete <em>Options → Broadcast settings → Select Encoder → External Encoder</em>, zkopírujte URL a klíč, vložte do SplitCam, Go Live."
       "<ol><li>Nainstalujte SplitCam.</li><li>Přidejte kameru + scénu.</li><li>Získejte URL a klíč z BongaCams.</li><li>Vložte do SplitCam.</li><li>Stiskněte Go Live.</li></ol>",
       "Na BongaCams otevřete <strong>Options</strong> → <strong>Broadcast settings</strong> → <strong>Select Encoder</strong> → <strong>External Encoder</strong> a zkopírujte zobrazenou URL serveru a stream key. <strong>Pokud tlačítko External Encoder chybí</strong>, kontaktujte podporu BongaCams a požádejte o zapnutí externího kódování na účtu.",
       [("Žádné tlačítko External Encoder? Podpora", "BongaCams zapíná externí kódování pro každý účet zvlášť — pokud možnost v Broadcast settings chybí, aktivuje ji podpora."),
        ("Sjednoťte rozlišení", "BongaCams doporučuje, aby rozlišení webkamery a vysílání souhlasilo — např. obojí 1280×720."),
        _T_ETH, _T_TEST],
       [("Proč se tlačítko External Encoder na BongaCams neobjevuje?", "Externí kódování není ve výchozím nastavení zapnuté na každém účtu — kontaktujte podporu BongaCams, aby ho zapnula, a tlačítko se objeví v Broadcast settings."),
        ("Musím ověřit účet BongaCams?", "Ano — vysílání vyžaduje 18+, oficiální doklad pro ověření věku a schválení účtu před živým vysíláním."),
        ("Jaký bitrate pro BongaCams?", "RTMP ingest BongaCams omezuje bitrate videa na zhruba 6000 Kbps s klíčovým snímkem po 2 sekundách — 3500–6000 v 1080p je ideální zóna; nejdřív otestujte upload."),
        ("Je SplitCam zdarma pro BongaCams?", "Ano — zcela zdarma, bez vodoznaku a bez časového limitu, takže kodér nezmenšuje vaše výdělky v tokenech na BongaCams.")]),
    _p("stripchat", "Stripchat",
       "Vysílání na Stripchat se SplitCam — nastavení strip cam",
       "Vysílání na Stripchat — strip cam platformě — se SplitCam zdarma. Externí software, klíč založený na tokenu, scény a překryvy.",
       "strip cam, stripchat live stream, vysílání stripchat, stripchat external software, stripchat stream key, stripchat rtmp obs",
       'Jak vysílat na <span class="accent">Stripchat</span> se SplitCam',
       "Vysílání Stripchat",
       "Nastavení externího softwaru pro vysílání Stripchat.",
       "Stripchat je velká cam platforma zaměřená na interaktivitu. Režim <em>external software</em> vám dá klíč založený na tokenu — zadejte ho do SplitCam zdarma a vysílejte se scénami, překryvy a filtry místo ploché kamery.",
       "Vysílání na Stripchat se SplitCam: nainstalujte SplitCam, sestavte scénu, na Stripchat vyberte <em>Switch to external software</em>, zkopírujte stream key, vložte do SplitCam, Go Live."
       "<ol><li>Nainstalujte SplitCam.</li><li>Přidejte kameru + scénu.</li><li>Získejte stream key ze Stripchat.</li><li>Vložte do SplitCam.</li><li>Stiskněte Go Live.</li></ol>",
       "Na Stripchat vyberte <strong>Switch to external software</strong>, poté <strong>Show external software settings for the stream</strong>. Zkopírujte stream key — Stripchat ho zobrazuje jako token. Držte ho v tajnosti.",
       [("Sjednoťte rozlišení se stránkou", "FAQ Stripchat varuje: rozlišení ve vašem softwaru musí přesně odpovídat stránce, jinak se video rozpadne. Nastavte obojí stejně."),
        ("Pozor na minimum 2 Mbps", "Stripchat uvádí 2 Mbps uploadu jako minimum — a upřímně říká, že to nestačí na vysílání OBS nebo multistream. Mířte výrazně výš."),
        ("Klíč je token", "Stream key Stripchat je token — kopírujte přesně, nikdy nesdílejte, resetujte při úniku."),
        _T_ETH],
       [("Doporučuje Stripchat OBS / externí software?", "Ano — oficiální FAQ Stripchat doporučuje externí vysílací software jako OBS «pro dosažení nejlepší kvality videa a zvuku». SplitCam funguje stejně."),
        ("Jak přepnout Stripchat na externí software?", "V Broadcast Center vyberte Switch to External Broadcast Software (OBS), poté otevřete external software settings, aby se zobrazil stream key (token)."),
        ("Jaký bitrate pro Stripchat?", "RTMP ingest přijímá až ~6000 Kbps s klíčovým snímkem po 2 sekundách. 3500–6000 v 1080p je ideální — ale musí být výrazně nad minimem 2 Mbps, zvlášť pro vysílání OBS."),
        ("Je SplitCam zdarma pro Stripchat?", "Ano — bez licenčních poplatků, bez vodoznaku, bez časového limitu: ani dlouhá interaktivní show na Stripchat nic nestojí na straně kodéru.")]),
    _p("onlyfans", "OnlyFans",
       "Živě na OnlyFans se SplitCam — Autorizace nebo klíč",
       "Živě na OnlyFans se SplitCam zdarma — přihlášení přes autorizaci nebo OBS Key, vícekamerové scény, překryvy. Bez vodoznaku.",
       "živě onlyfans, onlyfans live stream, onlyfans autorizace splitcam, onlyfans obs key, onlyfans vysílací software",
       'Jak vysílat <span class="accent">živě na OnlyFans</span> se SplitCam',
       "Živě OnlyFans",
       "Autorizujte se jednou nebo vložte klíč — živě na OnlyFans.",
       "Živé vysílání OnlyFans pro vaše odběratele. SplitCam se připojuje <strong style='color:var(--text)'>dvěma způsoby</strong> — přihlaste se jednou účtem OnlyFans a SplitCam automaticky získá stream key a synchronizuje ho, nebo vložte OBS Key ručně. Oba umožňují vysílat s vícekamerovými scénami, překryvy a filtry.",
       "Živě na OnlyFans se SplitCam: nainstalujte SplitCam, sestavte scénu, otevřete Stream Settings &rarr; Add Channel &rarr; OnlyFans a vyberte <em>Autorizace</em> — přihlaste se účtem OnlyFans, SplitCam získá klíč automaticky — a stiskněte Go Live. S připojeným účtem můžete měnit parametry vysílání OnlyFans ve SplitCam, aniž byste otevírali web OnlyFans.",
       "Na OnlyFans: <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; sekce <strong>Other</strong>, zkopírujte <strong>OBS Key</strong>. Nebo použijte možnost <strong>Autorizace</strong> ve SplitCam k přihlášení — klíč se získá automaticky a zůstane synchronizovaný.",
       [("Autorizace vs Stream Key", "Dva způsoby připojení: <strong>Autorizace</strong> (přihlaste se jednou, klíč se získá a synchronizuje — nejjednodušší cesta) nebo <strong>Stream Key</strong> (zkopírujte OBS Key na OnlyFans → Profile → Settings → Other a vložte)."),
        ("Měňte nastavení bez opuštění SplitCam", "S autorizací zůstává účet připojený, takže parametry živého vysílání OnlyFans nastavujete ze SplitCam během nebo po vysílání — bez návštěvy webu OnlyFans."),
        ("Skromný bitrate", "RTMP ingest OnlyFans omezuje bitrate videa na zhruba 2500 Kbps — přísněji než většina cam stránek. Mířte na 720p–1080p při ~2000–2500."),
        _T_ETH],
       [("Jak připojit OnlyFans ke SplitCam?", "Dvěma způsoby. <strong>Autorizace</strong> — Stream Settings → Add Channel → OnlyFans → přihlaste se účtem OnlyFans a SplitCam získá klíč automaticky. Nebo <strong>Stream Key</strong> — zkopírujte OBS Key na OnlyFans → Profile → Settings → Other a vložte."),
        ("Můžu měnit nastavení živého vysílání OnlyFans bez otevření webu?", "Ano — s metodou Autorizace zůstává SplitCam připojený k účtu OnlyFans, takže klíč a nastavení se synchronizují automaticky. Vše měníte ze SplitCam během nebo po vysílání, bez návštěvy onlyfans.com."),
        ("Jaký bitrate pro OnlyFans?", "Skromný — RTMP ingest OnlyFans omezuje bitrate na zhruba 2500 Kbps, výrazně přísněji než jiné cam platformy. Mířte na 720p–1080p kolem 2000–2500 Kbps."),
        ("Je SplitCam zdarma pro živé vysílání na OnlyFans?", "Ano — zdarma, bez vodoznaku a bez časového limitu. Žádné náklady na straně kodéru.")],
       steps=[
           ("Stáhněte a nainstalujte SplitCam", "SplitCam je bezplatný software pro živé vysílání pro Windows a macOS — bez registrace, bez karty, bez vodoznaku. Je to kodér, který posílá vaše video na OnlyFans."),
           ("Nastavte kameru a scénu", "Otevřete SplitCam a přidejte webkameru. Sestavte scénu tak, jak chcete, aby ji diváci viděli — překryvy, text, druhá kamera, beauty filtry nebo AI pozadí, vše se aplikuje živě."),
           ("Připojení — Způsob 1: Autorizace (doporučeno)", "Ve SplitCam otevřete <strong>Stream Settings</strong> &rarr; <strong>Add Channel</strong> &rarr; <strong>OnlyFans</strong> a vyberte <strong>Autorizace</strong>. Přihlaste se e-mailem a heslem OnlyFans. SplitCam propojí účet, automaticky získá stream key a bude ho synchronizovat — a také vám umožní spravovat parametry živého vysílání OnlyFans uvnitř SplitCam, měnit je během nebo po vysílání bez otevření webu OnlyFans."),
           ("Připojení — Způsob 2: Stream Key (ručně)", "Nechcete se přihlašovat? Použijte klíč. Na OnlyFans otevřete <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; sekce <strong>Other</strong> a zkopírujte <strong>OBS Key</strong>. Ve SplitCam, Add Channel &rarr; OnlyFans, vložte do pole klíče. Tento klíč je statický — pro pozdější změnu nastavení se vraťte na web OnlyFans."),
           ("Go Live", "Ať tak či onak, stiskněte <strong>Go Live</strong> ve SplitCam. U Způsobu 1 můžete dál ladit parametry OnlyFans ze SplitCam v reálném čase; u Způsobu 2 zůstane klíč přesně takový, jaký jste zadali."),
       ]),
    _p("camplace", "CamPlace",
       "Vysílání na CamPlace se SplitCam — bezplatný návod",
       "Vysílání na CamPlace se SplitCam zdarma — externí kodér, RTMP klíč, scény a překryvy. Krok za krokem, bez vodoznaku.",
       "vysílání camplace, camplace broadcasting software, camplace rtmp, camplace externí kodér, camplace stream key",
       'Jak vysílat na <span class="accent">CamPlace</span> se SplitCam',
       "Vysílání CamPlace",
       "Nastavení externího kodéru pro vysílání CamPlace.",
       "CamPlace je cam streaming platforma. Veřejný článek o OBS neexistuje, takže <strong style='color:var(--text)'>video návod výše</strong> je vaším vodítkem — SplitCam zdarma se připojuje přes standardní RTMP a přidává scény, překryvy a AI pozadí, které základní kamera nemá.",
       "Vysílání na CamPlace se SplitCam: nainstalujte SplitCam, sestavte scénu, zapněte externí/RTMP vysílání na CamPlace, zkopírujte URL serveru a stream key, vložte do SplitCam, Go Live. Postupujte podle videa pro aktuální cestu."
       "<ol><li>Nainstalujte SplitCam.</li><li>Přidejte kameru + scénu.</li><li>Získejte RTMP klíč z CamPlace.</li><li>Vložte do SplitCam.</li><li>Stiskněte Go Live.</li></ol>",
       "Přihlaste se na CamPlace a otevřete nastavení vysílání. Přepněte na možnost externího kodéru / RTMP / OBS, aby se zobrazila <strong>URL serveru</strong> a <strong>stream key</strong>, zkopírujte obojí. CamPlace nepublikuje oficiální dokumentaci OBS — <strong>video výše</strong> je nejspolehlivější cesta krok za krokem přes aktuální rozhraní.",
       [("Žádný oficiální návod OBS — použijte video", "CamPlace nemá veřejný článek o externím kodéru; video výše je vodítkem pro aktuální cestu."),
        ("Standardní RTMP funguje", "I když to není zdokumentované, CamPlace přijímá standardní URL serveru RTMP a klíč — SplitCam se připojuje jako vlastní cíl RTMP."),
        ("Skládejte překryvy ve SplitCam", "Cíle tipů, jméno a odkazy na sociální sítě přidejte jako vrstvy scény — základní kamera CamPlace je nepřidá."),
        _T_ETH],
       [("Má CamPlace oficiální návod OBS?", "Žádný veřejný článek o externím kodéru nenalezen. CamPlace přijímá standardní URL RTMP a klíč, takže SplitCam funguje — postupujte podle videa."),
        ("Podporuje CamPlace externí kodér?", "Ano — přijímá standardní stream key RTMP, takže SplitCam se připojuje jako vlastní cíl RTMP."),
        ("Jaký bitrate pro CamPlace?", "CamPlace nepublikuje oficiální čísla — použijte 3500–6000 Kbps v 1080p jako bezpečné rozmezí a nechte test rychlosti SplitCam určit skutečný strop."),
        ("Je SplitCam zdarma pro CamPlace?", "Ano — zdarma, bez vodoznaku a bez časového limitu. Protože CamPlace nemá vlastní kodér, bezplatný RTMP nástroj to vyřeší.")]),
    _p("camsoda", "CamSoda",
       "CamSoda živě se SplitCam — bezplatné nastavení",
       "CamSoda živě se SplitCam zdarma — Use OBS Broadcaster, regionální servery, scény a překryvy. Bez vodoznaku.",
       "camsoda live, vysílání camsoda, camsoda obs broadcaster, camsoda rtmp obs, camsoda live broadcast",
       'Jak vysílat na <span class="accent">CamSoda</span> se SplitCam',
       "Vysílání CamSoda",
       "Nastavení Use OBS Broadcaster na CamSoda.",
       "CamSoda je cam platforma z USA známá interaktivními, neobvyklými formáty show. Oficiálně podporuje vysílání OBS — na stránce Go Live je tlačítko <strong style='color:var(--text)'>Use OBS Broadcaster</strong> a na wiki CamSoda oficiální návod k OBS. SplitCam zdarma funguje stejně.",
       "Vysílání na CamSoda se SplitCam: nainstalujte SplitCam, sestavte scénu, klikněte na Use OBS Broadcaster na stránce Go Live CamSoda, zkopírujte URL serveru a stream key, vložte do SplitCam, Go Live."
       "<ol><li>Nainstalujte SplitCam.</li><li>Přidejte kameru + scénu.</li><li>Klikněte na Use OBS Broadcaster na CamSoda.</li><li>Vložte URL serveru + klíč do SplitCam.</li><li>Stiskněte Go Live.</li></ol>",
       "Na stránce <strong>Go Live</strong> CamSoda klikněte na <strong>Use OBS Broadcaster</strong>. CamSoda zobrazí URL serveru RTMP a stream key — zkopírujte obojí. Vyberte nejbližší regionální server (Severní Amerika, Evropa, Asie atd.). Wiki CamSoda má kompletní návod k OBS pro detaily.",
       [("Ověřte se, abyste dostávali tipy", "Na CamSoda může vysílat kdokoli, ale abyste dostávali tipy, musíte dokončit proces ověření CamSoda."),
        ("Vyberte nejbližší regionální server", "CamSoda nabízí regionální ingest servery — nejbližší (SA / Evropa / Asie / Jižní Amerika / Oceánie) snižuje zpoždění a ztrátu snímků."),
        ("Strop u 1080p / 30 fps", "Ingest CamSoda dosahuje zhruba 1080p, 30 fps a ~6000 Kbps — netlačte výš."),
        _T_ETH],
       [("Podporuje CamSoda OBS / externí kodér?", "Ano — oficiálně. Na stránce Go Live je tlačítko Use OBS Broadcaster a na wiki CamSoda návod k OBS, takže SplitCam funguje."),
        ("Potřebuji ověření na CamSoda?", "Pro vysílání ne. Pro příjem tipů ano — CamSoda vyžaduje nejdřív projít procesem ověření."),
        ("Jaké rozlišení CamSoda podporuje?", "Až 1920×1080 při 30 fps, maximálně kolem 6000 Kbps v RTMP ingest."),
        ("Je SplitCam zdarma pro CamSoda?", "Ano — zdarma, bez vodoznaku a bez časového limitu. Funguje s bezplatným režimem Use OBS Broadcaster CamSoda, takže celá sestava nic nestojí.")]),
    _p("streamate", "Streamate",
       "Vysílání na Streamate se SplitCam — integrovaný kanál",
       "Vysílání na Streamate se SplitCam zdarma — integrovaný kanál, klíč SM Connect, scény a překryvy. Bez vodoznaku.",
       "streamate, streamate sm connect, vysílání streamate, streamate broadcasting software, streamate rtmp",
       'Jak vysílat na <span class="accent">Streamate</span> se SplitCam',
       "Vysílání Streamate",
       "Streamate je integrovaný kanál ve SplitCam — rychlé nastavení.",
       "Streamate je zavedená cam platforma — a je <strong style='color:var(--text)'>předkonfigurovaným cílem ve SplitCam</strong>, v seznamu kanálů, takže nastavení je rychlejší než ruční zadávání RTMP: vyberte Streamate, vložte klíč, hotovo.",
       "Vysílání na Streamate se SplitCam: nainstalujte SplitCam, sestavte scénu, na Streamate použijte <em>SM Connect → Start Show</em> a zkopírujte klíč, poté ve SplitCam otevřete <em>Stream Settings → Add Channel → Streamate</em> a vložte."
       "<ol><li>Nainstalujte SplitCam.</li><li>Přidejte kameru + scénu.</li><li>Získejte klíč Streamate přes SM Connect.</li><li>Add Channel → Streamate ve SplitCam.</li><li>Stiskněte Go Live.</li></ol>",
       "Na Streamate otevřete <strong>SM Connect</strong>, souhlaste s podmínkami, klikněte na <strong>Start Show</strong> vlevo a zavřete otevřené okno — poté zkopírujte streamovací klíč. Ve SplitCam otevřete <strong>Stream Settings</strong> → <strong>Add Channel</strong>, vyberte <strong>Streamate</strong> ze seznamu a vložte klíč. Zelený posuvník znamená připojení.",
       [("Streamate je integrovaný", "Žádná ruční URL RTMP — SplitCam má Streamate v seznamu Add Channel; stačí vybrat a vložit klíč."),
        ("Zavřete popup SM Connect", "Po Start Show Streamate otevře okno — zavřete ho; slouží jen k zobrazení streamovacího klíče."),
        ("Zamkněte rozlišení na 1080p", "Pole Video Resolution v SM Connect může tiše skočit na 1440, které se ve skutečnosti neodesílá a tiše snižuje vaši kvalitu — nastavte ručně 1080p. Pokles bitrate při statickém obrazu je normální: stream Streamate je adaptivní."),
        _T_ETH, _T_TEST],
       [("Je Streamate integrovaný ve SplitCam?", "Ano — Streamate se objevuje v seznamu Add Channel SplitCam; vybíráte ho, nezadáváte URL RTMP ručně."),
        ("Kde je streamovací klíč Streamate?", "SM Connect → souhlaste s podmínkami → Start Show → zavřete popup → zkopírujte klíč."),
        ("Jaký bitrate pro Streamate?", "Streamate nestanovuje tvrdý strop — 3500–6000 Kbps v 1080p funguje dobře. Stream je adaptivní, takže nižší bitrate při statickém obrazu je normální, ne chyba."),
        ("Je SplitCam zdarma pro Streamate?", "Ano — zdarma, bez vodoznaku a bez časového limitu; a protože Streamate je integrovaný kanál ve SplitCam, nejsou žádné samostatné náklady na kodér.")]),
    _p("streamray", "StreamRay",
       "Vysílání na StreamRay cam se SplitCam — URL v chatu",
       "Vysílání na StreamRay cam se SplitCam zdarma — URL zveřejněná v chatu, režim OBS Broadcaster, scény a překryvy. Bez vodoznaku.",
       "streamray, streamray cam, vysílání streamray, streamray obs broadcaster, streamray rtmp",
       'Jak vysílat na <span class="accent">StreamRay</span> se SplitCam',
       "Vysílání StreamRay",
       "Nastavení externího kodéru typu URL-v-chatu pro StreamRay.",
       "StreamRay má neobvyklé nastavení externího kodéru — posílá URL streamu do <strong style='color:var(--text)'>okna chatu vysílání</strong> a nepoužívá samostatný klíč. SplitCam zdarma zvládá tento tok jen s URL.",
       "Vysílání na StreamRay se SplitCam: nainstalujte SplitCam, sestavte scénu, na StreamRay zapněte OBS Broadcaster, zkopírujte URL streamu z okna chatu, vložte do SplitCam (pole klíče nechte prázdné), Go Live."
       "<ol><li>Nainstalujte SplitCam.</li><li>Přidejte kameru + scénu.</li><li>Zkopírujte URL StreamRay z chatu.</li><li>Vložte URL do SplitCam.</li><li>Stiskněte Go Live.</li></ol>",
       "Na StreamRay dvakrát klikněte na <strong>Broadcast Now</strong>, otevřete menu <strong>Other</strong>, vyberte <strong>OBS Broadcaster</strong> a <strong>Save and Close</strong>. StreamRay poté zveřejní <strong>URL streamu v okně chatu</strong> — zkopírujte ji odtud. Pole stream key SplitCam nechte <strong>prázdné</strong>; StreamRay ověřuje jen přes URL.",
       [("URL je v chatu", "StreamRay nezobrazuje URL streamu v poli nastavení — zveřejní ji v okně chatu vysílání. Zkopírujte ji odtud."),
        ("Nechte pole klíče prázdné", "StreamRay nepoužívá samostatný klíč — jen URL. Do pole klíče SplitCam nic nezadávejte."),
        _T_ETH, _T_TEST],
       [("Kde je URL streamu StreamRay?", "Po zapnutí OBS Broadcaster StreamRay zveřejní URL v okně chatu — zkopírujte z chatu."),
        ("Proč na StreamRay není stream key?", "StreamRay ověřuje jen přes URL — nechte pole klíče SplitCam prázdné."),
        ("Jaký bitrate pro StreamRay?", "StreamRay neuvádí oficiální strop — mířte na 3500–6000 Kbps v 1080p a spusťte test rychlosti SplitCam, protože tok jen s URL nedává zpětnou vazbu o bitrate."),
        ("Je SplitCam zdarma pro StreamRay?", "Ano — zdarma, bez vodoznaku a bez časového limitu, hodí se k toku StreamRay jen s URL: vložte jeden odkaz a jste živě.")]),
    _p("xlovecam", "XLoveCam",
       "Vysílání na XLoveCam se SplitCam — RTMP odkaz a klíč",
       "Vysílání na XLoveCam se SplitCam zdarma — RTMP odkaz a klíč, regionální servery, scény a překryvy. Bez vodoznaku.",
       "xlovecam, x love cam, vysílání xlovecam, xlovecam rtmp link, xlovecam stream key",
       'Jak vysílat na <span class="accent">XLoveCam</span> se SplitCam',
       "Vysílání XLoveCam",
       "Nastavení RTMP odkaz + klíč pro XLoveCam.",
       "XLoveCam je evropská vícejazyčná cam platforma. Nastavení účtu zobrazují jak <strong style='color:var(--text)'>RTMP odkaz</strong>, tak <strong style='color:var(--text)'>stream key</strong> — SplitCam zdarma vezme obojí a vysílá s plnými scénami a překryvy.",
       "Vysílání na XLoveCam se SplitCam: nainstalujte SplitCam, sestavte scénu, na XLoveCam otevřete <em>My Account → settings</em>, zkopírujte RTMP odkaz a stream key, vložte obojí do SplitCam, spusťte show."
       "<ol><li>Nainstalujte SplitCam.</li><li>Přidejte kameru + scénu.</li><li>Zkopírujte RTMP odkaz + klíč z XLoveCam.</li><li>Vložte obojí do SplitCam.</li><li>Stiskněte Go Live.</li></ol>",
       "Na XLoveCam otevřete <strong>My Account</strong> → <strong>settings</strong>. Nastavení zobrazují jak <strong>RTMP odkaz</strong>, tak <strong>stream key</strong> — zkopírujte obojí do polí URL serveru a klíče SplitCam, poté <strong>Start your show</strong> na XLoveCam.",
       [("Zkopírujte odkaz I klíč", "XLoveCam dává RTMP odkaz I samostatný stream key — potřebujete obojí ve SplitCam, ne jen jedno."),
        ("Vícejazyčné publikum", "XLoveCam je evropský a vícejazyčný — čitelné textové překryvy ve vašem jazyce pomáhají divákům vás najít."),
        ("Vyberte nejbližší server", "XLoveCam nabízí regionální RTMP servery — Evropa, Severní Amerika, Jižní Amerika a Asie. Nejbližší snižuje zpoždění a ztrátu snímků."),
        _T_ETH],
       [("Kde jsou data RTMP XLoveCam?", "My Account → settings — zobrazuje jak RTMP odkaz, tak klíč."),
        ("Podporuje XLoveCam externí kodér?", "Ano — poskytuje RTMP odkaz a klíč, takže SplitCam funguje jako kodér."),
        ("Jaký bitrate pro XLoveCam?", "XLoveCam nepublikuje pevný limit; 3500–6000 Kbps v 1080p je ideální. Výběr nejbližšího regionálního serveru je stejně důležitý — snižuje ztrátu snímků."),
        ("Je SplitCam zdarma pro XLoveCam?", "Ano — zdarma, bez vodoznaku a bez časového limitu. Dosáhnout na vícejazyčné evropské publikum XLoveCam nestojí žádné náklady na software.")]),
    _p("soulcams", "SoulCams",
       "Vysílání na SoulCams se SplitCam — nastavení OBS",
       "Vysílání na SoulCams se SplitCam zdarma — nastavení OBS, RTMP server a klíč, vícekamerové scény a překryvy.",
       "soul cams, soulcams, vysílání soulcams, soulcams obs, soulcams rtmp, soulcams broadcast",
       'Jak vysílat na <span class="accent">SoulCams</span> se SplitCam',
       "Vysílání SoulCams",
       "Nastavení OBS pro SoulCams.",
       "SoulCams je cam platforma, jejíž nastavení OBS zobrazuje <strong style='color:var(--text)'>RTMP server a stream key spolu</strong> v jednom okně. Vložte obojí do SplitCam zdarma a vysílejte s vícekamerovými scénami a překryvy.",
       "Vysílání na SoulCams se SplitCam: nainstalujte SplitCam, sestavte scénu, na SoulCams klikněte na Go Online → Settings → OBS, zkopírujte server a klíč, vložte obojí do SplitCam, Go Live."
       "<ol><li>Nainstalujte SplitCam.</li><li>Přidejte kameru + scénu.</li><li>Otevřete SoulCams Settings → OBS.</li><li>Vložte server + klíč do SplitCam.</li><li>Stiskněte Go Live.</li></ol>",
       "Na SoulCams se přihlaste a klikněte na <strong>Go Online</strong>, poté otevřete <strong>Settings</strong> → <strong>OBS</strong>. Okno OBS zobrazuje <strong>RTMP server</strong> a <strong>stream key</strong> spolu — zkopírujte obojí do SplitCam.",
       [("Server a klíč vedle sebe", "SoulCams zobrazuje RTMP server a klíč ve stejném okně OBS — vezměte obojí najednou."),
        ("Nejdřív Go Online", "Nastavení OBS se objeví až po kliknutí na Go Online na SoulCams — udělejte to před hledáním dat kodéru."),
        ("Zablokujte nechtěné regiony", "SoulCams umožňuje geoblokování ze strany modelky — vyberte, které země neuvidí stream, před kliknutím na Go Online."),
        _T_ETH, _T_TEST],
       [("Kde je nastavení OBS SoulCams?", "Přihlaste se, klikněte na Go Online, poté Settings → OBS — RTMP server a stream key jsou zobrazeny spolu."),
        ("Podporuje SoulCams externí kodér?", "Ano — nastavení OBS dává RTMP server a klíč, takže SplitCam funguje."),
        ("Jaký bitrate pro SoulCams?", "SoulCams nedává oficiální čísla — mířte na 3500–6000 Kbps v 1080p a otestujte upload, protože okno OBS nezobrazuje doporučení k bitrate."),
        ("Je SplitCam zdarma pro SoulCams?", "Ano — zdarma, bez vodoznaku a bez časového limitu, takže plné show na SoulCams s vícekamerovými scénami a překryvy nic nestojí na straně kodéru.")]),
    _p("imlive", "ImLive",
       "Použití ImLive se SplitCam — virtuální kamera",
       "Nastavení Im Live stream se SplitCam zdarma — ImLive používá živou webkameru (bez RTMP), připojte SplitCam jako virtuální kameru se scénami.",
       "im live stream, imlive splitcam, vysílání imlive, imlive virtuální kamera, imlive webcam, im live cam",
       'Jak používat <span class="accent">ImLive</span> se SplitCam',
       "SplitCam na ImLive",
       "Nastavení virtuální kamery pro ImLive — bez RTMP.",
       "ImLive používá živou webkameru v prohlížeči — <strong style='color:var(--text)'>žádné RTMP ani stream key</strong>. SplitCam zdarma se připojuje jako <strong style='color:var(--text)'>virtuální kamera</strong>: sestavte scénu ve SplitCam, poté vyberte SplitCam jako kameru na ImLive.",
       "Použití SplitCam s ImLive: nainstalujte SplitCam, sestavte scénu s mediálními vrstvami, otevřete ImLive a spusťte videochat, v nastavení ImLive vyberte SplitCam jako webkameru a mikrofon."
       "<ol><li>Nainstalujte SplitCam.</li><li>Sestavte scénu ve SplitCam.</li><li>Spusťte videochat na ImLive.</li><li>Vyberte SplitCam jako kameru ImLive.</li><li>Spusťte chat.</li></ol>",
       "Přihlaste se na web ImLive a klikněte na <strong>Start Video Chat</strong>, poté otevřete <strong>Go To Settings</strong> pro přístup k možnostem kamery a mikrofonu. V nastavení ImLive vyberte <strong>SplitCam</strong> jako webkameru a mikrofon.",
       [("Stream key není potřeba", "ImLive nemá RTMP — nehledejte URL serveru ani klíč. SplitCam se jen vybírá jako zařízení kamery."),
        ("Nastavte SplitCam i jako mikrofon", "Vyberte SplitCam pro mikrofon vedle kamery, aby do živého vysílání šel i mix zvuku a potlačení šumu."),
        ("Sestavte scénu před vysíláním", "ImLive zobrazuje to, co SplitCam posílá — uspořádejte vrstvy před spuštěním chatu."),
        _T_TEST],
       [("Používá ImLive RTMP nebo stream key?", "Ani jedno — ImLive používá živou webkameru přes prohlížeč. SplitCam se připojuje jako virtuální kamera, žádný klíč ke kopírování."),
        ("Jak vybrat SplitCam na ImLive?", "Start Video Chat → Go To Settings → vyberte SplitCam jako webkameru a mikrofon."),
        ("Můžu používat překryvy na ImLive?", "Ano — sestavte je ve scéně SplitCam; ImLive zobrazí složený výsledek."),
        ("Je SplitCam zdarma pro ImLive?", "Ano — zdarma, bez vodoznaku a bez časového limitu. Jako virtuální kamera pro ImLive nepřidává náklady ani branding do vašeho videochatu.")],
       steps=[
           ("Nainstalujte SplitCam", "SplitCam je bezplatný software pro Windows a macOS. Nainstalujte ho — bez vodoznaku, bez registrace. Pro ImLive funguje jako <strong>virtuální kamera</strong>, ne jako RTMP kodér."),
           ("Sestavte scénu ve SplitCam", "Otevřete SplitCam a použijte <strong>Media Layers +</strong> k přidání webkamery plus libovolných překryvů, textu, filtrů nebo AI pozadí. Tato složená scéna je to, co ImLive uvidí jako vaši kameru."),
           ("Spusťte videochat na ImLive", "Přihlaste se na web ImLive a klikněte na <strong>Start Video Chat</strong>, poté otevřete <strong>Go To Settings</strong> pro přístup k možnostem kamery a mikrofonu."),
           ("Vyberte SplitCam jako kameru", "V nastavení ImLive vyberte <strong>SplitCam</strong> jako webkameru I mikrofon. ImLive nyní zobrazuje vaši plnou scénu SplitCam, ne plochou webkameru."),
           ("Spusťte Free Live Chat", "Klikněte na <strong>Free Live Chat</strong> na ImLive pro živé vysílání. Pro změnu vzhledu uprostřed relace upravte scénu ve SplitCam — ImLive se okamžitě aktualizuje."),
       ]),
    _p("vxlive", "VXLive",
       "Vysílání na VXLive se SplitCam — oficiální podpora",
       "Vysílání na VXLive (VXModels / VISIT-X) se SplitCam zdarma — oficiální preset VISIT-X, server a klíč, scény. Bez vodoznaku.",
       "vxlive, visit-x, vxmodels splitcam, vysílání vxlive, visit-x stream, vxlive rtmp",
       'Jak vysílat na <span class="accent">VXLive</span> se SplitCam',
       "Vysílání VXLive",
       "VXLive podporuje SplitCam oficiálně (preset VISIT-X).",
       "VXLive (VXModels / VISIT-X) je cam platforma z německého trhu — a jedna z mála, které <strong style='color:var(--text)'>oficiálně podporují SplitCam jménem</strong>. VXModels má vyhrazený článek nápovědy o připojení <strong style='color:var(--text)'>SplitCam</strong> k VXLive a SplitCam nabízí VISIT-X jako hotový preset kanálu.",
       "Vysílání na VXLive se SplitCam: nainstalujte SplitCam, sestavte scénu, na VXLive vyberte «Stream with third-party software», zkopírujte URL serveru a klíč, ve SplitCam vyberte preset VISIT-X a vložte, Go Live ve SplitCam, poté GO ONLINE na VXLive."
       "<ol><li>Nainstalujte SplitCam.</li><li>Přidejte kameru + scénu.</li><li>Získejte URL serveru + klíč z VXLive.</li><li>Vyberte preset VISIT-X ve SplitCam, vložte.</li><li>Go Live, poté GO ONLINE na VXLive.</li></ol>",
       "Na VXLive vyberte <strong>Stream with third-party software</strong> a možnost <strong>OBS, SplitCam nebo XSplit</strong>. VXLive poskytuje <strong>URL serveru</strong> a <strong>stream key</strong>. Ve SplitCam vyberte <strong>VISIT-X</strong> jako streamovací platformu, vložte obojí, stiskněte <strong>Go Live</strong> ve SplitCam, poté <strong>GO ONLINE</strong> na VXLive.",
       [("VISIT-X je integrovaný preset", "Nezadávejte syrovou URL RTMP — SplitCam má VISIT-X v seznamu platforem; stačí vybrat a vložit URL serveru a klíč."),
        ("Dvoufázové go-live", "Na VXLive nejdřív stiskněte Go Live ve SplitCam, poté GO ONLINE na VXLive — obojí, v tomto pořadí."),
        ("Německý trh", "Publikum VXLive je převážně německy mluvící — německé textové překryvy nebo titulky pomáhají se spojit s diváky."),
        _T_ETH],
       [("Podporuje VXLive SplitCam oficiálně?", "Ano — VXModels (VXLive) udržuje vyhrazený oficiální článek nápovědy pro nastavení SplitCam a uvádí SplitCam vedle OBS a XSplit jako podporovaný vysílací software."),
        ("Jak připojit SplitCam k VXLive?", "Na VXLive vyberte «Stream with third-party software», poté ve SplitCam vyberte preset VISIT-X a vložte URL serveru a stream key, které VXLive dá."),
        ("Jsem živě ve SplitCam nebo VXLive?", "V obojím — nejdřív Go Live ve SplitCam, poté GO ONLINE na VXLive."),
        ("Proč VXModels doporučuje SplitCam?", "Oficiální článek nápovědy VXModels doporučuje SplitCam konkrétně k odstranění artefaktů obrazu webkamery a pixelizace a ke stabilizaci připojení — ne jen jako obecný kodér.")]),
    _p("virtwish", "VirtWish",
       "Vysílání na VirtWish se SplitCam — URL streamu a klíč",
       "Vysílání na VirtWish se SplitCam zdarma — sekce OBS Profile → Start Broadcast, URL streamu a klíč, scény a překryvy.",
       "virtwish, vysílání virtwish, virtwish broadcasting software, virtwish rtmp, virtwish stream key, virtwish obs",
       'Jak vysílat na <span class="accent">VirtWish</span> se SplitCam',
       "Vysílání VirtWish",
       "Nastavení URL streamu + klíč pro VirtWish.",
       "VirtWish je interaktivní cam platforma. Nastavení vysílání vám dají <strong style='color:var(--text)'>samostatnou URL streamu a stream key</strong> v sekci OBS — SplitCam zdarma vezme obojí a vede show se scénami a překryvy.",
       "Vysílání na VirtWish se SplitCam: nainstalujte SplitCam, sestavte scénu, na VirtWish otevřete <em>Profile → Start Broadcast</em> až k sekci OBS, zkopírujte odkaz a klíč, vložte obojí do SplitCam, Go Live."
       "<ol><li>Nainstalujte SplitCam.</li><li>Přidejte kameru + scénu.</li><li>Získejte URL + klíč z VirtWish.</li><li>Vložte obojí do SplitCam.</li><li>Stiskněte Go Live.</li></ol>",
       "Na VirtWish klikněte na ikonu vpravo nahoře → <strong>Profile</strong> → <strong>Start Broadcast</strong>, poté <strong>Start Broadcast</strong> znovu, abyste se dostali k sekci OBS. <strong>Zkopírujte odkaz z prvního řádku</strong> do pole Stream URL SplitCam a samostatný <strong>Stream Key</strong> do pole klíče.",
       [("Odkaz je na prvním řádku", "Sekce OBS VirtWish dává URL streamu na první řádek — zkopírujte ji do Stream URL SplitCam, poté samostatný klíč."),
        ("Dvě kliknutí na Start Broadcast", "Na VirtWish klikáte na Start Broadcast dvakrát, abyste se dostali k sekci OBS — to je normální, ne chyba."),
        _T_ETH, _T_TEST],
       [("Kde jsou data RTMP VirtWish?", "Ikona vpravo nahoře → Profile → Start Broadcast dvakrát → sekce OBS zobrazí odkaz a stream key."),
        ("Podporuje VirtWish externí kodér?", "Ano — sekce OBS poskytuje URL streamu a klíč, takže SplitCam funguje."),
        ("Jaký bitrate pro VirtWish?", "VirtWish nepublikuje oficiální strop; 3500–6000 Kbps v 1080p je bezpečné. Sjednoťte rozlišení SplitCam s tím nastaveným ve VirtWish, abyste předešli přeškálování."),
        ("Je SplitCam zdarma pro VirtWish?", "Ano — zdarma, bez vodoznaku a bez časového limitu. Nastavení URL-a-klíč VirtWish zabere jen potřebných pár minut.")]),
    _p("xmodels", "XModels",
       "Vysílání na XModels se SplitCam — bezplatný návod",
       "Vysílání na XModels se SplitCam zdarma — možnost externího kodéru v nastavení účtu modelky, RTMP klíč, scény a překryvy.",
       "xmodels, vysílání xmodels, xmodels broadcasting software, xmodels rtmp, xmodels externí kodér",
       'Jak vysílat na <span class="accent">XModels</span> se SplitCam',
       "Vysílání XModels",
       "Nastavení externího kodéru pro vysílání XModels.",
       "XModels je cam streaming platforma s vestavěnou <strong style='color:var(--text)'>možností externího kodéru</strong> v nastavení účtu modelky. SplitCam zdarma tam vysílá s vícekamerovými scénami, překryvy a filtry místo jedné ploché kamery.",
       "Vysílání na XModels se SplitCam: nainstalujte SplitCam, sestavte scénu, v účtu modelky XModels zapněte možnost externího kodéru, zkopírujte URL serveru a stream key, vložte do SplitCam, Go Live."
       "<ol><li>Nainstalujte SplitCam.</li><li>Přidejte kameru + scénu.</li><li>Zapněte externí kodér v nastavení XModels.</li><li>Vložte URL serveru + klíč do SplitCam.</li><li>Stiskněte Go Live.</li></ol>",
       "V <strong>nastavení účtu modelky</strong> XModels zapněte možnost <strong>vysílání přes externí kodér</strong>. XModels poskytuje <strong>stream key</strong> — zkopírujte ho do SplitCam. Pokud možnost není tam, kde čekáte, podpora XModels je přes FAQ chat na webu a <strong>info@xmodels.com</strong>; video výše to také ukazuje.",
       [("Je to v nastavení účtu", "XModels umisťuje možnost externího kodéru do nastavení účtu modelky, ne na samostatnou obrazovku vysílání."),
        ("Podpora: chat + e-mail", "XModels nemá velké veřejné centrum nápovědy — FAQ chat na webu a info@xmodels.com jsou oficiální kanály podpory."),
        ("Skládejte překryvy ve SplitCam", "Cíle tipů, jméno a odkazy na sociální sítě přidejte jako vrstvy scény — základní kamera XModels je nepřidá."),
        _T_ETH],
       [("Podporuje XModels externí kodér?", "Ano — nastavení účtu modelky má možnost vysílání externím kodérem, která poskytuje stream key, takže SplitCam funguje."),
        ("Kde získat pomoc XModels?", "Podpora XModels je přes FAQ chat na webu a e-mail info@xmodels.com — žádné velké veřejné centrum nápovědy."),
        ("Jaký bitrate pro XModels?", "XModels nedokumentuje oficiální čísla — použijte 3500–6000 Kbps v 1080p a spusťte test rychlosti SplitCam, protože podpora XModels je jen přes chat a e-mail."),
        ("Je SplitCam zdarma pro XModels?", "Ano — zdarma, bez vodoznaku a bez časového limitu, takže vysílání do evropské sítě XModels nepřidává náklady na software.")]),
    _p("flirt4free", "Flirt4Free",
       "Vysílání na Flirt for Free cam se SplitCam — bezplatný návod",
       "Vysílání na Flirt for Free cam se SplitCam zdarma — External Broadcast Form, RTMP URL a Stream Name, scény a překryvy.",
       "flirt for free cam, flirt 4 free cam, flirt4free, vysílání flirt4free, flirt4free external broadcast, flirt4free rtmp",
       'Jak vysílat na <span class="accent">Flirt4Free</span> se SplitCam',
       "Vysílání Flirt4Free",
       "Nastavení External Broadcast Form pro Flirt4Free.",
       "Flirt4Free je jedna z nejstarších cam platforem, v provozu od 90. let. Oficiálně podporuje externí vysílání přes <strong style='color:var(--text)'>External Broadcast Form</strong> — SplitCam zdarma posílá stream a formulář nastavuje rozlišení a bitrate.",
       "Vysílání na Flirt4Free se SplitCam: nainstalujte SplitCam, sestavte scénu, otevřete External Broadcast Form Flirt4Free, zkopírujte RTMP URL a Stream Name a nastavte rozlišení/bitrate, vložte do SplitCam, Go Live."
       "<ol><li>Nainstalujte SplitCam.</li><li>Přidejte kameru + scénu.</li><li>Otevřete External Broadcast Form Flirt4Free.</li><li>Vložte RTMP URL + Stream Name do SplitCam.</li><li>Stiskněte Go Live.</li></ol>",
       "V zóně modelky Flirt4Free otevřete <strong>External Broadcast Form</strong>. Na rozdíl od většiny cam stránek dává Flirt4Free <strong>RTMP URL</strong> a <strong>Stream Name</strong> (ne «klíč»), plus pole rozlišení a bitrate, která vyplníte přímo ve formuláři. Zkopírujte URL a Stream Name do polí serveru a klíče SplitCam.",
       [("Je to Stream Name, ne klíč", "Flirt4Free nazývá své údaje Stream Name. Vkládáte ho do pole stream key SplitCam — funkce je stejná."),
        ("Nastavte rozlišení/bitrate ve formuláři", "External Broadcast Form Flirt4Free má vlastní pole rozlišení a bitrate — sjednoťte je s nastavením SplitCam, aby se obraz nepřeškáloval."),
        ("Platforma s historií", "Flirt4Free běží od 90. let — její nástroje pro modelky jsou vyzrálé a External Broadcast Form je jejich zdokumentovaná část."),
        _T_ETH],
       [("Podporuje Flirt4Free externí kodér?", "Ano — oficiálně, přes External Broadcast Form, který poskytuje RTMP URL a Stream Name. SplitCam funguje jako kodér."),
        ("Kde získat data RTMP Flirt4Free?", "Z External Broadcast Form v zóně modelky — zobrazuje RTMP URL, Stream Name a pole rozlišení/bitrate."),
        ("Jaký bitrate pro Flirt4Free?", "3500–6000 Kbps v 1080p — nastavte stejné hodnoty v External Broadcast Form i ve SplitCam."),
        ("Je SplitCam zdarma pro Flirt4Free?", "Ano — zdarma, bez vodoznaku a bez časového limitu, hodí se k historické platformě jako Flirt4Free, kde show bývají dlouhé.")]),
    _p("mfc-alerts", "MFC Alerts",
       "Přidání MFC Alerts do vysílání se SplitCam",
       "Zobrazujte animovaná upozornění na tipy ve vysílání MyFreeCams — URL mfcalerts.com jako vrstva Browser ve SplitCam zdarma, nad webkamerou.",
       "mfc alerts, myfreecams alerts, přidat mfc alerts, mfcalerts splitcam, myfreecams tip alerts, myfreecams alerts overlay",
       'Jak přidat <span class="accent">MFC Alerts</span> do vysílání',
       "Přidat MFC Alerts",
       "Zobrazujte animovaná upozornění na tipy ve vysílání MyFreeCams.",
       "MFC Alerts zobrazuje animované efekty ve vašem vysílání MyFreeCams pokaždé, když divák pošle tip. Běží jako <strong style='color:var(--text)'>vrstva Browser</strong> uvnitř SplitCam zdarma — nastavte jednou a tipy spouštějí reakce na obrazovce v reálném čase.",
       "Přidání MFC Alerts se SplitCam: nainstalujte SplitCam, přidejte webkameru, otevřete kartu Browser a načtěte mfcalerts.com, zkopírujte svou URL upozornění, přidejte jako vrstvu Browser nad webkameru, poté otestujte testovacím tipem."
       "<ol><li>Nainstalujte SplitCam.</li><li>Přidejte webkameru.</li><li>Získejte URL na mfcalerts.com.</li><li>Přidejte jako vrstvu Browser nad webkameru.</li><li>Pošlete testovací tip.</li></ol>",
       "Ve SplitCam otevřete kartu <strong>Browser</strong> a přejděte na <strong>www.mfcalerts.com</strong>. Přihlaste se nebo zaregistrujte. Použijte <strong>Copy to clipboard</strong> ke zkopírování své soukromé URL upozornění. Vložte URL do okna Browser SplitCam a klikněte na <strong>Add</strong>. Poté uspořádejte seznam zdrojů tak, aby <strong>MFC Alerts byl nad webkamerou</strong> (menu se 3 tečkami → Move Up).",
       [("MFC Alerts musí být nad webkamerou", "Nejčastější chyba: pokud je vrstva MFC Alerts pod webkamerou v seznamu zdrojů, efekt zůstane skrytý. Posuňte ji nahoru."),
        ("Potřeba účet mfcalerts.com", "URL upozornění je soukromá — nejdřív se zaregistrujte na mfcalerts.com, pokud nemáte účet."),
        ("Pošlete testovací tip před vysíláním", "Použijte Settings → Send test tip, abyste se ujistili, že překryv funguje — neobjevujte chybu uprostřed show."),
        _T_ETH],
       [("Co je MFC Alerts?", "Systém upozornění pro MyFreeCams, který zobrazuje video efekty ve vašem vysílání, když diváci posílají tipy — přidává se jako překryv Browser ve SplitCam."),
        ("Proč se mé MFC Alerts nezobrazují?", "Téměř vždy je to pořadí vrstev — vrstva Browser MFC Alerts musí být nad webkamerou v seznamu zdrojů SplitCam."),
        ("Potřebuji účet pro MFC Alerts?", "Ano — zaregistrujte se na mfcalerts.com, abyste získali svou soukromou URL upozornění."),
        ("Je SplitCam zdarma pro tohle?", "Ano — SplitCam je zdarma, bez vodoznaku a bez časového limitu, a prohlížečový překryv MFC Alerts v něm běží bez dalších nákladů.")],
       steps=[
           ("Nainstalujte SplitCam a přidejte webkameru", "Nainstalujte SplitCam zdarma pro Windows nebo macOS, poté přidejte <strong>webkameru</strong> jako zdroj. MFC Alerts leží jako vrstva nad touto kamerou."),
           ("Otevřete kartu Browser a přejděte na mfcalerts.com", "Ve SplitCam otevřete kartu <strong>Browser</strong> a přejděte na <strong>www.mfcalerts.com</strong>. Přihlaste se nebo se zaregistrujte, pokud ještě nemáte účet mfcalerts.com."),
           ("Zkopírujte svou URL upozornění", "Na mfcalerts.com použijte <strong>Copy to clipboard</strong> ke zkopírování své soukromé URL upozornění — to je stránka, která vykresluje animace tipů."),
           ("Přidejte URL jako vrstvu Browser — nad webkameru", "Vložte URL do okna Browser SplitCam a klikněte na <strong>Add</strong>. Poté uspořádejte seznam zdrojů tak, aby <strong>MFC Alerts byl nad webkamerou</strong> (menu se 3 tečkami → Move Up). Pokud je pod ní, efekt zůstane skrytý."),
           ("Otestujte testovacím tipem", "Otevřete <strong>Settings → Send test tip</strong> a ujistěte se, že se efekt upozornění objeví nad kamerou. Poté vysílejte normálně na MyFreeCams — skutečné tipy nyní spouštějí animace."),
       ]),
    _p("lovense", "Lovense",
       "Přidání hraček Lovense do vysílání se SplitCam",
       "Připojte interaktivní hračky Lovense ke cam vysílání se SplitCam zdarma — Lovense SplitCam Toolset, upozornění na tipy na obrazovce, reakce.",
       "přidat lovense do vysílání, lovense cam stream, lovense splitcam, lovense splitcam toolset, lovense interactive toy streaming",
       'Jak přidat <span class="accent">hračky Lovense</span> do vysílání',
       "Přidat hračky Lovense",
       "Připojte interaktivní hračky Lovense ke svému cam vysílání.",
       "Vedete cam vysílání přes SplitCam zdarma a párujete hračku <strong style='color:var(--text)'>Lovense</strong>, která reaguje na tokeny. Lovense dokumentuje oficiální <strong style='color:var(--text)'>Lovense SplitCam Toolset</strong> a SplitCam nabízí oficiální plugin Lovense — integrace je podporována z obou stran.",
       "Pro přidání hraček Lovense do vysílání: nainstalujte SplitCam a software Lovense, spárujte hračku, připojte Lovense ke cam platformě, přidejte stav Lovense jako vrstvu Browser ve SplitCam, poté vysílejte normálně."
       "<ol><li>Nainstalujte SplitCam.</li><li>Nainstalujte software Lovense a spárujte hračku.</li><li>Připojte Lovense ke své cam stránce.</li><li>Přidejte překryv Lovense ve SplitCam.</li><li>Stiskněte Go Live.</li></ol>",
       "Nainstalujte Lovense Connect / Lovense Stream (oficiální desktopová aplikace). Zapněte hračku a spárujte přes Bluetooth, aby aplikace ukázala připojení. V aplikaci Lovense propojte svůj cam účet, aby hračka reagovala na tokeny / tipy diváků. Lovense poskytuje URL překryvu / widgetu — přidejte jako vrstvu <strong>Browser</strong> ve scéně SplitCam.",
       [("Použijte oficiální Lovense SplitCam Toolset", "Lovense publikuje vyhrazený toolset pro SplitCam s vlastním návodem k instalaci — přidává překryvy aktivity hračky a upozornění na tipy vytvořená pro SplitCam."),
        ("Aktualizujte Lovense Cam Extension", "Toolset vyžaduje nejnovější Lovense Cam Extension (30.1.4 nebo novější) — aktualizujte před vysíláním."),
        ("Udržujte hračku nabitou", "Slabá baterie uprostřed show pokazí interaktivní stránku — nabijte naplno před vysíláním."),
        ("Otestujte reakci na tokeny", "Pošlete malý testovací tip, abyste se ujistili, že hračka reaguje, před otevřením místnosti."),
        ("Zkontrolujte požadavky na verzi", "Lovense SplitCam Toolset vyžaduje SplitCam 10.4.5 nebo novější. Lovense Cam Extension oficiálně zahrnuje Chaturbate, Stripchat, BongaCams, MyFreeCams a CamSoda — pro jiné stránky použijte integraci Generic URL Lovense.")],
       [("Podporuje Lovense SplitCam oficiálně?", "Ano — Lovense dokumentuje oficiální «Lovense SplitCam Toolset» s vlastním návodem k instalaci a SplitCam nabízí oficiální plugin Lovense. Integrace je podporována z obou stran."),
        ("Připojuje se hračka přímo ke SplitCam?", "Ne — hračka se páruje s aplikací Lovense; SplitCam zobrazuje překryv Lovense a vysílá kameru."),
        ("Které cam stránky podporují Lovense?", "Lovense Cam Extension oficiálně podporuje Chaturbate, Stripchat, BongaCams, MyFreeCams a CamSoda, s různou podporou ostatních — zkontrolujte aktuální seznam v aplikaci Lovense."),
        ("Můžu zobrazovat poslední tipy na obrazovce?", "Ano — přidejte URL widgetu Lovense jako vrstvu Browser ve SplitCam.")],
       steps=[
           ("Nainstalujte SplitCam", "SplitCam je bezplatný software pro živé vysílání pro Windows a macOS — kodér, který posílá vaše video na cam platformu. Nainstalujte ho; bez vodoznaku."),
           ("Nainstalujte software Lovense a spárujte hračku", "Nainstalujte Lovense Connect / Lovense Stream (oficiální desktopová aplikace). Zapněte hračku a spárujte přes Bluetooth, aby aplikace ukázala připojení."),
           ("Připojte Lovense ke cam platformě", "V aplikaci Lovense propojte svůj cam účet, aby hračka reagovala na tokeny / tipy diváků. Podporuje se většina velkých cam platforem."),
           ("Přidejte překryv Lovense ve SplitCam", "Lovense poskytuje URL překryvu / widgetu. Přidejte jako vrstvu <strong>Browser</strong> ve scéně SplitCam, aby diváci viděli stav hračky a poslední tipy na obrazovce."),
           ("Sestavte scénu a Go Live", "Přidejte kameru a další překryvy, vložte RTMP klíč cam platformy do SplitCam a klikněte na <strong>Go Live</strong>. Hračka reaguje na tipy v reálném čase."),
       ]),
    _p("multistream-cams", "Více cam stránek",
       "Vysílání na více cam stránek najednou se SplitCam",
       "Vysílejte na MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat a další najednou s bezplatným multistreamem SplitCam. Jedno kliknutí, bez vodoznaku.",
       "vysílání na více cam stránek, multistream cam sites, vysílání chaturbate a bongacams najednou, software multistream cam",
       'Jak vysílat na <span class="accent">více cam stránek</span> najednou',
       "Multistream cam",
       "Vysílejte na více cam stránek najednou.",
       "SplitCam zdarma umí vysílat jedno kódování na <strong style='color:var(--text)'>více cam stránek najednou</strong> — MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat a další. Bez vodoznaku, jedno kliknutí.",
       "Pro vysílání na více cam stránek najednou: nainstalujte SplitCam, sestavte scénu, získejte URL serveru RTMP a stream key každé cam stránky, přidejte všechny do nastavení multistreamu SplitCam, klikněte na Go Live jednou."
       "<ol><li>Nainstalujte SplitCam.</li><li>Přidejte kameru + scénu.</li><li>Získejte RTMP klíče z každé cam stránky.</li><li>Přidejte všechny klíče do multistreamu SplitCam.</li><li>Stiskněte Go Live jednou.</li></ol>",
       "Na každé cam platformě zapněte externí / RTMP vysílání a zkopírujte <strong>URL serveru</strong> a <strong>stream key</strong>. Ve SplitCam otevřete <strong>Stream Settings</strong> a přidejte každou cam stránku jako vlastní cíl RTMP — vložte URL serveru a klíč. Zaškrtněte všechny, kde chcete být živě. Stiskněte <strong>Go Live</strong>.",
       [("Hlídejte si upload", "Multistream násobí zátěž uploadu. Každý cíl používá vlastní bitrate — ujistěte se, že vaše linka unese součet."),
        ("Zkontrolujte pravidla platforem", "Některé cam stránky zakazují souběžné vysílání jinde — zkontrolujte před multistreamem."),
        ("Kabel — tady padnout nesmí", "Multistream násobí zátěž uploadu, takže jeden výpadek wi-fi může shodit všechny cíle najednou. Kabel tady není volba."),
        ("Sledujte monitor stavu", "SplitCam zobrazuje stav každého cíle — odpojte jednu stránku, pokud upload nestíhá.")],
       [("Je multistream SplitCam zdarma?", "Ano — multistream je vestavěný a zdarma, bez poplatku za cíl, bez vodoznaku."),
        ("Na kolik cam stránek můžu vysílat najednou?", "Na tolik, kolik unese šířka pásma vašeho uploadu — každý cíl používá vlastní bitrate."),
        ("Používá cloudový relay?", "Ne — SplitCam posílá stream peer-to-peer přímo z PC do ingest každé platformy."),
        ("Zpomalí multistream můj PC?", "Kódování se dělá jednou a používá se opakovaně; hardwarové kódování drží zátěž CPU nízko. Šířka pásma uploadu je skutečný limit.")],
       steps=[
           ("Nainstalujte SplitCam", "SplitCam je bezplatný software pro živé vysílání pro Windows a macOS s vestavěným multistreamem. Nainstalujte ho — bez vodoznaku, bez registrace."),
           ("Nastavte kameru a scénu", "Otevřete SplitCam, přidejte webkameru a sestavte scénu s překryvy a filtry. Jedna scéna napájí každý cíl."),
           ("Získejte RTMP klíče z každé cam stránky", "Na každé cam platformě zapněte externí / RTMP vysílání a zkopírujte <strong>URL serveru</strong> a <strong>stream key</strong>. Opakujte pro každou stránku, na kterou chcete vysílat — přesnou cestu najdete v návodech jednotlivých platforem."),
           ("Přidejte každý cíl ve SplitCam", "Otevřete <strong>Stream Settings</strong> a přidejte každou cam stránku jako vlastní cíl RTMP — vložte URL serveru a klíč. Zaškrtněte všechny, kde chcete být živě."),
           ("Klikněte na Go Live jednou", "Stiskněte <strong>Go Live</strong>. SplitCam posílá stream na každou vybranou cam stránku najednou, peer-to-peer, z jednoho kódování — bez dalších nákladů."),
       ]),
    _p("livejasmin", "LiveJasmin",
       "Vysílání na LiveJasmin se SplitCam — Externí kodér HD",
       "Vysílání na LiveJasmin se SplitCam zdarma — externí kodér v Model Center, nastavení HD 1080p, vícekamerové scény a překryvy. Bez vodoznaku, bez registrace.",
       "vysílání livejasmin, livejasmin obs, livejasmin externí kodér, livejasmin rtmp, livejasmin stream key, livejasmin nastavení modelky",
       'Jak vysílat na <span class="accent">LiveJasmin</span> se SplitCam',
       "Vysílání LiveJasmin",
       "Nastavení externího kodéru pro Model Center LiveJasmin, který funguje jen v HD.",
       "LiveJasmin je vlajková loď Docler Holding — jedna z největších cam sítí na světě a platforma fungující výhradně v HD. Jejím preferovaným nástrojem na vysílání je vlastní klient <strong>JasminCAM</strong>, ale Model Center nabízí i standardní cestu přes <strong>External Encoder</strong>, na kterou se napojí <strong style='color:var(--text)'>SplitCam</strong> zdarma — díky tomu můžete vysílat vícekamerové scény, beauty filtry a překryvy ve stejném HD streamu.",
       "Vysílání na LiveJasmin se SplitCam: nainstalujte SplitCam, sestavte HD scénu, v Model Center jděte do <em>Settings → Broadcast → External Encoder</em>, zkopírujte URL serveru a stream key, vložte do SplitCam, Go Live."
       "<ol><li>Nainstalujte SplitCam.</li><li>Přidejte kameru + HD scénu.</li><li>Získejte URL a stream key z Model Center.</li><li>Vložte do SplitCam.</li><li>Stiskněte Go Live.</li></ol>",
       "Přihlaste se na <strong>modelcenter.livejasmin.com</strong>, otevřete <strong>Settings → Broadcast → External Encoder</strong>. Model Center zobrazí <strong>URL serveru</strong> a <strong>stream key</strong> vázané na váš účet — zkopírujte obojí do vlastních RTMP polí ve SplitCam. <strong>Pozor:</strong> nové účty musí být schválené (48–72 hodin) než se možnost externího kodéru objeví, a platforma vynucuje výstup výhradně v HD.",
       [("HD, jinak letíte dolů", "LiveJasmin je výhradně HD — cokoliv pod 1280×720 hrozí, že se ukážete jen na hůř placených seznamech, cokoliv pod 1080p ztrácí způsobilost pro «Premium». Mířte na 1920×1080 při 30 fps, 4000–6000 Kbps."),
        ("JasminCAM vs externí kodér", "Vlastní klient Docleru JasminCAM dává nejčistší shodu s HD požadavky, ale externí kodéry (OBS, SplitCam, vMix) jsou oficiálně podporované jakmile je váš účet schválený — odemknou vícekamerové scény a překryvy, které JasminCAM neumí."),
        ("Free chat ≠ private show", "Free chat je jen náhled — bez nahoty. Vyděláváte v Private a Gold show. Naplánujte scénu tak, aby vypadala silně oblečená I v režimu show."),
        _T_ETH],
       [("Podporuje LiveJasmin oficiálně externí kodéry jako SplitCam?", "Ano — Model Center obsahuje volbu External Encoder v Settings → Broadcast. JasminCAM je doporučený klient, ale OBS, SplitCam a další RTMP kodéry jsou výslovně uvedené jako podporované jakmile je váš účet modelky schválený."),
        ("Kde najdu svůj stream key LiveJasmin?", "Uvnitř Model Center: Settings → Broadcast → External Encoder. Najdete tam jak URL serveru, tak unikátní stream key — zkopírujte obojí do vlastních RTMP polí ve SplitCam. Klíč je vázaný na váš účet; chovejte se k němu jako k heslu."),
        ("Jaký bitrate použít pro LiveJasmin?", "LiveJasmin je výhradně HD — mířte na 1920×1080 při 30 fps, 4000–6000 Kbps s intervalem klíčového snímku 2 sekundy. Cokoliv znatelně pod tím ztrácí štítek Premium a letíte dolů v hodnocení."),
        ("Je SplitCam zdarma pro LiveJasmin?", "Ano — SplitCam je zdarma, bez vodoznaku a bez časového limitu. Jediná «cena» je dotáhnout HD požadavky LiveJasmin, což SplitCam zvládá nativně 1080p kompozicí scény a beauty filtry.")],
       steps=[
           ("Stáhněte a nainstalujte SplitCam", "SplitCam je bezplatný software pro živé vysílání pro Windows a macOS — bez registrace, bez karty, bez vodoznaku. Je to kodér, který posílá vaše HD video na LiveJasmin."),
           ("Sestavte HD scénu", "Otevřete SplitCam a přidejte webkameru v režimu 1080p. Navrstvěte překryvy, text, druhou kameru nebo telefon, beauty filtry nebo AI pozadí — LiveJasmin vyžaduje HD kvalitu a vaše složená scéna musí vypadat prémiově jak ve free chatu, TAK v privátních show."),
           ("Získejte URL a stream key LiveJasmin", "Přihlaste se na <strong>modelcenter.livejasmin.com</strong> (váš účet musí být nejdřív schválený — obvykle 48–72 hodin po registraci). Otevřete <strong>Settings → Broadcast → External Encoder</strong>. Stránka zobrazí <strong>URL serveru</strong> a unikátní <strong>stream key</strong>. Zkopírujte obojí."),
           ("Připojte SplitCam k LiveJasmin", "Ve SplitCam otevřete <strong>Stream Settings</strong>, vložte URL serveru LiveJasmin a stream key do vlastních RTMP polí. Nastavte bitrate na 4000–6000 Kbps při 1920×1080, 30 fps, klíčový snímek po 2 sekundách. Nejdřív spusťte vestavěný test rychlosti — HD streamy jsou náročné."),
           ("Klikněte Go Live", "Stiskněte <strong>Go Live</strong> ve SplitCam a pak jděte online v Model Center LiveJasmin. Do zhruba 10 sekund vaše HD vysílání dorazí do sítě LiveJasmin. Další vysílání je jedno kliknutí — otevřete SplitCam, Go Live, pak jděte online na LiveJasmin."),
       ]),
    _p("myfreecams", "MyFreeCams",
       "Vysílání na MyFreeCams (MFC) se SplitCam — obejití Model Web Broadcaster",
       "Vysílání na MyFreeCams s bezplatným SplitCam — externí broadcaster v Model Admin, tokenová ekonomika MFC, vícekamerové scény, overlaye. Bez vodoznaku, bez registrace.",
       "myfreecams vysílání, mfc externí broadcaster, myfreecams obs, mfc rtmp, mfc stream key, model admin, mfc token",
       'Jak vysílat na <span class="accent">MyFreeCams</span> se SplitCam',
       "Vysílání na MyFreeCams",
       "Konfigurace externího broadcasteru pro tokenový Model Admin v MFC.",
       "MFC je jedna z nejstarších cam platforem — čistá tokenová ekonomika, žádné martyrium se schvalováním modelek a věrná základna Premium členů. Výchozí <strong>Model Web Broadcaster</strong> je jednokamerový nástroj v prohlížeči, ale <strong>Model Admin</strong> nabízí i možnost <strong>External Broadcaster</strong>, ke které se připojuje bezplatný <strong style='color:var(--text)'>SplitCam</strong> — a odemyká vícekamerové scény, overlaye a filtry na stejném tokenovém streamu.",
       "Vysílání na MyFreeCams se SplitCam: nainstalujte, postavte scénu, v Model Admin → Broadcaster přepněte Web na <em>External Broadcaster</em>, zkopírujte URL serveru a stream key, vložte do SplitCam, Go Live."
       "<ol><li>Nainstalujte SplitCam.</li><li>Přidejte kameru a overlaye.</li><li>Získejte URL a klíč z Model Admin.</li><li>Vložte do SplitCam.</li><li>Stiskněte Go Live.</li></ol>",
       "Přihlaste se na MyFreeCams, otevřete <strong>Model Admin → Broadcaster</strong> a přepněte z <strong>Web</strong> na <strong>External Broadcaster</strong>. Stránka zobrazí URL serveru (rtmp://publish.myfreecams.com…) a stream key vázané na účet modelky. Zkopírujte obojí do vlastních RTMP polí ve SplitCam.",
       [("MFC jsou čisté tipy v tokenech, ne předplatné", "Jádro výdělku jsou tipy ve free chatu — Premium členové můžou jít do private, ale chleba s máslem jsou tokeny ve veřejném chatu. Postavte scénu na neustálé pobízení k tippingu, ne na krátké «show za peníze»."),
        ("Web vs External Broadcaster", "Výchozí Web Broadcaster je jedna kamera v prohlížeči — rychlý, ale chudý. External Broadcaster přes SplitCam, OBS nebo vMix odemyká vícekamerové scény, overlaye a beauty filtry na stejném tokenovém streamu."),
        ("Integrace MFC Alerts", "Přidejte URL z mfcalerts.com jako Browser vrstvu nad kameru ve SplitCam — dostanete animované alerty tipů přímo v obraze, bez přepínání oken a bez dalších pluginů."),
        _T_ETH],
       [("Podporuje MFC oficiálně externí broadcastery jako SplitCam?", "Ano — Model Admin má volbu External Broadcaster se standardním URL serveru RTMP a stream key. OBS, SplitCam, vMix — všechno funguje po jednoduchém přepnutí Web → External Broadcaster."),
        ("Kde najdu stream key na MFC?", "Model Admin → Broadcaster → přepněte na External Broadcaster. URL serveru a stream key se objeví hned na stejné stránce. Zkopírujte obojí do vlastních RTMP polí ve SplitCam — klíč je vázaný na váš účet, berte ho jako heslo."),
        ("Jaký bitrate pro MFC?", "Až kolem 6000 Kbps s klíčovým snímkem po 2 sekundách. Vyšlete 1920×1080 při 30 fps a 3500–6000 Kbps — váš reálný upload je limit, ne MFC. Nejdřív spusťte vestavěný test rychlosti SplitCam."),
        ("Je SplitCam zdarma pro MFC?", "Ano — SplitCam je zdarma, bez vodoznaku, bez časového limitu. External Broadcaster na straně MFC je taky zdarma — je to standardní RTMP, žádné poplatky navíc.")],
       steps=[
           ("Stáhněte a nainstalujte SplitCam", "SplitCam je bezplatný software pro živé vysílání pro Windows a macOS — bez registrace, bez karty, bez vodoznaku. Je to enkodér, který posílá vaše video na MyFreeCams."),
           ("Postavte scénu", "Otevřete SplitCam a přidejte kameru, overlaye, druhou kameru nebo telefon, beauty filtry nebo AI pozadí. Přidejte URL z <strong>mfcalerts.com</strong> jako Browser vrstvu nad kameru — dostanete animované alerty tipů přímo ve streamu."),
           ("Získejte URL a stream key MFC", "Přihlaste se na MyFreeCams, otevřete <strong>Model Admin → Broadcaster</strong> a přepněte z <strong>Web</strong> na <strong>External Broadcaster</strong>. Zkopírujte URL serveru (rtmp://publish.myfreecams.com…) a stream key."),
           ("Připojte SplitCam k MFC", "Ve SplitCam otevřete <strong>Stream Settings</strong>, vložte URL a stream key MFC do vlastních RTMP polí. Nastavte bitrate 3500–6000 Kbps při 1920×1080, 30 fps, klíčový snímek po 2 sekundách. Nejdřív spusťte vestavěný test rychlosti."),
           ("Klikněte Go Live", "Stiskněte <strong>Go Live</strong> ve SplitCam — do zhruba 10 sekund vaše vysílání dorazí na MFC. Další vysílání je jedno kliknutí: otevřete SplitCam, Go Live."),
       ]),
    _p("cherry-tv", "Cherry.tv",
       "Vysílání na Cherry.tv se SplitCam — externí enkodér přátelský k Web3",
       "Vysílání na Cherry.tv s bezplatným SplitCam — externí enkodér ve Streamer Dashboard, cam platforma přátelská ke kryptu, vícekamerové scény. Bez vodoznaku, bez registrace.",
       "cherry tv vysílání, cherry.tv obs, cherry tv externí enkodér, cherry.tv rtmp, cherry.tv stream key, cherry tv streamer, web3 cam",
       'Jak vysílat na <span class="accent">Cherry.tv</span> se SplitCam',
       "Vysílání na Cherry.tv",
       "Konfigurace externího enkodéru pro Streamer Dashboard Cherry.tv.",
       "Cherry.tv je novější, rychle rostoucí cam platforma s výrazným Web3 akcentem — výplaty přátelské ke kryptu a nižší vstupní bariéra než staré sítě typu LiveJasmin. Výchozí broadcaster běží v prohlížeči, ale <strong>Streamer Dashboard</strong> nabízí i standardní cestu přes externí enkodér, ke které se připojuje bezplatný <strong style='color:var(--text)'>SplitCam</strong> — a umožňuje vám vysílat s vícekamerovými scénami, overlayi a filtry.",
       "Vysílání na Cherry.tv se SplitCam: nainstalujte SplitCam, postavte scénu, ve Streamer Dashboard → <em>Broadcast Settings → External Encoder</em> zkopírujte URL a stream key, vložte do SplitCam, Go Live."
       "<ol><li>Nainstalujte SplitCam.</li><li>Přidejte kameru a overlaye.</li><li>Získejte URL a klíč ze Streamer Dashboard.</li><li>Vložte do SplitCam.</li><li>Stiskněte Go Live.</li></ol>",
       "Přihlaste se ke streamer účtu na Cherry.tv, otevřete <strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong>. URL serveru a stream key jsou vázané na váš účet. Nové účty musí nejdřív projít základní verifikací (obvykle rychle — Cherry.tv má lehčí onboarding než staré cam sítě), než se možnost External Encoder plně aktivuje.",
       [("Lehčí vstup, rostoucí provoz", "Žádná 72hodinová recenze ve stylu Docler — dobrý okamžik, kdy si vybudovat základnu sledujících, než konkurence přitvrdí. Nové účty mají slušnou viditelnost v listingu."),
        ("Kryptovýplaty vedle standardního fiatu", "Cherry.tv nabízí výplaty v kryptu vedle klasických převodů — užitečné tam, kde jsou tradiční výplaty cam sítí pomalé nebo regionálně omezené."),
        ("Browser broadcaster vs externí", "Výchozí broadcaster v prohlížeči je pohodlný, ale je to jeden zdroj. SplitCam přes External Encoder odemyká vícekamerové scény, overlaye, beauty filtry a AI pozadí — to je rozdíl mezi «obyčejným streamem» a premium scénou."),
        _T_ETH],
       [("Podporuje Cherry.tv externí enkodéry jako SplitCam?", "Ano — Streamer Dashboard má External Encoder v Broadcast Settings se standardním URL serveru RTMP a stream key. OBS, SplitCam a další RTMP enkodéry se připojí bez problému."),
        ("Kde najdu stream key na Cherry.tv?", "Streamer Dashboard → Broadcast Settings → External Encoder. URL serveru i klíč se objeví na stejné stránce — zkopírujte obojí do vlastních RTMP polí ve SplitCam."),
        ("Jaký bitrate pro Cherry.tv?", "3500–6000 Kbps při 1920×1080, 30 fps, klíčový snímek po 2 sekundách. Nejdřív spusťte vestavěný test rychlosti SplitCam a ověřte, že upload stabilně utáhne zvolený bitrate."),
        ("Je SplitCam zdarma pro Cherry.tv?", "Ano — SplitCam je zdarma, bez vodoznaku, bez časového limitu. External Encoder na straně Cherry.tv je taky zdarma.")],
       steps=[
           ("Stáhněte a nainstalujte SplitCam", "SplitCam je bezplatný software pro živé vysílání pro Windows a macOS — bez registrace, bez karty, bez vodoznaku. Je to enkodér, který posílá vaše video na Cherry.tv."),
           ("Postavte scénu", "Otevřete SplitCam a přidejte kameru, overlaye, případně druhou kameru nebo telefon, beauty filtry a AI pozadí. Publikum Cherry.tv je mladší a v platformách zběhlé — vypiplaná scéna reálně pomáhá vyniknout."),
           ("Získejte URL a stream key Cherry.tv", "Přihlaste se ke streamer účtu na Cherry.tv, otevřete <strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong>. Zkopírujte URL serveru a stream key."),
           ("Připojte SplitCam k Cherry.tv", "Ve SplitCam otevřete <strong>Stream Settings</strong>, vložte URL a klíč do vlastních RTMP polí. Nastavte bitrate 3500–6000 Kbps při 1920×1080, 30 fps, klíčový snímek po 2 sekundách. Nejdřív spusťte vestavěný test rychlosti."),
           ("Klikněte Go Live", "Stiskněte <strong>Go Live</strong> ve SplitCam, potom jděte online ve Streamer Dashboard na Cherry.tv. Do zhruba 10 sekund vaše vysílání dorazí na Cherry.tv. Další vysílání je jedno kliknutí."),
       ]),
]
