# -*- coding: utf-8 -*-
"""Persian/Farsi (fa) content for cam-streaming-guides. Native Persian (RTL), 19 platforms."""

_T_ETH = ("از اتصال سیمی استفاده کنید", "اترنت در پخش‌های طولانی از Wi-Fi بهتر است — فریم‌های "
          "گم‌شده به معنای انعام‌های گم‌شده است. کابل را به رایانه پخش‌کننده وصل کنید.")
_T_TEST = ("ابتدا تست خصوصی انجام دهید", "یک پخش آزمایشی کوتاه برای بررسی دوربین، صدا، "
           "کادربندی و پوشش‌ها قبل از باز کردن اتاق برای بینندگان انجام دهید.")

def _p(slug, name, title, desc, kw, h1html, h1short, card, intro, quick, key_how, tips, faq, steps=None):
    d = {"slug": slug, "name": name, "title": title, "desc": desc, "kw": kw,
         "h1html": h1html, "h1short": h1short, "card": card, "intro": intro,
         "quick": quick, "key_how": key_how, "tips": tips, "faq": faq}
    if steps: d["steps"] = steps
    return d

PLATFORMS_FA = [
    _p("chaturbate", "Chaturbate",
       "پخش در Chaturbate با SplitCam — توکن و RTMP",
       "پخش در Chaturbate با SplitCam رایگان — broadcast token، RTMP، صحنه‌های چندکاره و پوشش‌ها. بدون واترمارک، بدون ثبت‌نام.",
       "پخش chaturbate, chaturbate broadcast token, chaturbate rtmp obs, chaturbate رمزگذار خارجی, chaturbate live",
       'نحوه پخش در <span class="accent">Chaturbate</span> با SplitCam',
       "پخش Chaturbate",
       "تنظیم مبتنی بر توکن با رمزگذار خارجی در Chaturbate.",
       "Chaturbate یکی از بزرگ‌ترین پلتفرم‌های کم است که بر اقتصاد توکن بنا شده. ابزار پخش مرورگر آن فقط یک ابزار تک‌دوربینه ساده است — انتقال به <strong style='color:var(--text)'>رمزگذار خارجی</strong> با <strong style='color:var(--text)'>SplitCam</strong> رایگان صحنه‌های چندکاره، پوشش‌ها و فیلترها را در همان پخش مبتنی بر توکن باز می‌کند.",
       "پخش در Chaturbate با SplitCam: SplitCam را نصب کنید، صحنه بسازید، در Chaturbate <em>Broadcast Yourself → My Broadcast</em> را باز کنید، broadcast token را کپی کنید، در SplitCam جای‌گذاری کنید، Go Live."
       "<ol><li>SplitCam را نصب کنید.</li><li>دوربین + صحنه اضافه کنید.</li><li>broadcast token از Chaturbate کپی کنید.</li><li>در SplitCam جای‌گذاری کنید.</li><li>Go Live را فشار دهید.</li></ol>",
       "در Chaturbate روی <strong>Broadcast Yourself</strong> کلیک کنید تا به صفحه <strong>My Broadcast</strong> بروید، سپس <strong>View RTMP/OBS broadcast information and stream key</strong>. کلید به صورت <strong>broadcast token</strong> نمایش داده می‌شود — آن را کپی کنید. مثل رمز عبور با آن رفتار کنید؛ هرگز به اشتراک نگذارید.",
       [("توکن همان کلید است", "Chaturbate از broadcast token شما استفاده می‌کند، نه یک کلید جریان عمومی. مثل رمز عبور با آن رفتار کنید و اگر لو رفت آن را بازنشانی کنید."),
        ("فضای زیاد", "RTMP ingest چتربیت تا 4K، 60 fps و بیت‌ریت بالا را می‌پذیرد — محدودیت آپلود شماست، نه پلتفرم. فریم کلیدی هر ۲ ثانیه."),
        _T_ETH, _T_TEST],
       [("آیا Chaturbate OBS / رمزگذار خارجی را مجاز می‌داند؟", "بله — Chaturbate رمزگذارهای خارجی را رسماً پشتیبانی می‌کند و مقاله‌ای با عنوان «How do I set up OBS?» دارد. از طریق «Use External Encoder to Broadcast» در تنظیمات پخش فعال کنید."),
        ("کلید جریان Chaturbate من کجاست؟", "Broadcast Yourself → My Broadcast → View RTMP/OBS broadcast information and stream key. کلید همان broadcast token شماست."),
        ("بیت‌ریت Chaturbate چقدر باشد؟", "3500–6000 کیلوبیت بر ثانیه در 1080p بیش از کافی است. سقف Chaturbate بالاست — محدودیت واقعی آپلود شماست؛ ابتدا تست سرعت داخلی SplitCam را اجرا کنید."),
        ("آیا SplitCam برای Chaturbate رایگان است؟", "بله — کاملاً رایگان، بدون واترمارک و بدون محدودیت زمانی: رمزگذار درآمد توکن شما را کاهش نمی‌دهد.")]),
    _p("cam4", "CAM4",
       "پخش در CAM4 با SplitCam — External Encoder",
       "پخش در CAM4 با SplitCam رایگان — External Encoder، کلید جریان، مسدودسازی جغرافیایی و پوشش‌ها. بدون واترمارک.",
       "پخش cam4, cam4.com, cam4 external encoder, cam4 کلید جریان, cam4 rtmp obs",
       'نحوه پخش در <span class="accent">CAM4</span> با SplitCam',
       "پخش CAM4",
       "External Encoder در CAM4 با کنترل جغرافیایی.",
       "CAM4 یک پلتفرم جهانی cam-and-earn با کنترل جغرافیایی داخلی است — می‌توانید پخش را در کشورهای خاص مخفی کنید. پخش از طریق <strong style='color:var(--text)'>SplitCam</strong> رایگان به عنوان رمزگذار خارجی تغییر صحنه و پوشش‌هایی را که ابزار پایه ندارد باز می‌کند.",
       "پخش در CAM4 با SplitCam: SplitCam را نصب کنید، صحنه بسازید، در CAM4 <em>Broadcast &amp; Earn Money → Start Broadcast → External Encoder</em> را باز کنید، Get Stream Key، در SplitCam جای‌گذاری کنید، Go Live."
       "<ol><li>SplitCam را نصب کنید.</li><li>دوربین + صحنه اضافه کنید.</li><li>کلید جریان از CAM4 دریافت کنید.</li><li>در SplitCam جای‌گذاری کنید.</li><li>Go Live را فشار دهید.</li></ol>",
       "در CAM4 روی <strong>Broadcast</strong> → <strong>Broadcast &amp; Earn Money</strong> → <strong>Start Broadcast</strong> کلیک کنید، سپس <strong>External Encoder</strong> در بالا. تاریخ تولد، جنسیت و کشور را وارد کنید، از <strong>Get Stream Key</strong> استفاده کرده و کپی کنید. لغزنده سبز در Stream Settings SplitCam نشان‌دهنده اتصال است.",
       [("محدودیت‌های جغرافیایی تنظیم کنید", "CAM4 اجازه می‌دهد پخش را در کشورها و مناطق خاص مخفی کنید — این را قبل از go-live در CAM4 تنظیم کنید."),
        ("به لغزنده سبز توجه کنید", "تنظیمات CAM4 هنگام پذیرفتن کلید، لغزنده سبزی در Stream Settings SplitCam نشان می‌دهد — قرمز = کلید را بررسی کنید."),
        ("بیت‌ریت پایین‌تر از معمول", "RTMP ingest CAM4 بیت‌ریت ویدیو را به حدود ۳۰۰۰ کیلوبیت بر ثانیه محدود می‌کند — کمتر از اکثر سایت‌های کم. آن را بالاتر نبرید."),
        _T_ETH],
       [("آیا CAM4 OBS / رمزگذار خارجی را رسماً پشتیبانی می‌کند؟", "بله — CAM4 یک OBS Guide رسمی در صفحه پشتیبانی دارد و External Encoder را برای بهترین تجربه توصیه می‌کند."),
        ("آیا می‌توانم پخش CAM4 را مسدود جغرافیایی کنم؟", "بله — CAM4 محدودیت‌های جغرافیایی داخلی برای مخفی کردن پخش در کشورهای خاص دارد. این را در CAM4 تنظیم کنید، نه در SplitCam."),
        ("کلید جریان CAM4 کجاست؟", "Broadcast → Broadcast & Earn Money → Start Broadcast → External Encoder → Get Stream Key."),
        ("بیت‌ریت CAM4 چقدر باشد؟", "پایین‌تر از میانگین — RTMP ingest CAM4 در ۳۰ fps با فریم کلیدی ۱ ثانیه به حدود ۳۰۰۰ کیلوبیت بر ثانیه محدود می‌شود.")]),
    _p("bongacams", "BongaCams",
       "پخش در BongaCams با SplitCam — External Encoder",
       "پخش در BongaCams با SplitCam رایگان — External Encoder، صحنه‌های چندکاره، پوشش‌ها و پس‌زمینه‌های هوش مصنوعی. بدون واترمارک.",
       "bongacams, bongcams, پخش bongacams, bongacams external encoder, bongacams rtmp obs",
       'نحوه پخش در <span class="accent">BongaCams</span> با SplitCam',
       "پخش BongaCams",
       "تنظیم External Encoder برای BongaCams.",
       "BongaCams یک پلتفرم کم جهانی است. پخش با رمزگذار خارجی همیشه فعال نیست — پس از فعال‌سازی، <strong style='color:var(--text)'>SplitCam</strong> رایگان پخش را با صحنه‌های چندکاره، پوشش‌ها و پس‌زمینه‌های هوش مصنوعی کنترل می‌کند.",
       "پخش در BongaCams با SplitCam: SplitCam را نصب کنید، صحنه بسازید، در BongaCams <em>Options → Broadcast settings → Select Encoder → External Encoder</em> را باز کنید، URL و کلید را کپی کنید، در SplitCam جای‌گذاری کنید، Go Live."
       "<ol><li>SplitCam را نصب کنید.</li><li>دوربین + صحنه اضافه کنید.</li><li>URL و کلید از BongaCams دریافت کنید.</li><li>در SplitCam جای‌گذاری کنید.</li><li>Go Live را فشار دهید.</li></ol>",
       "در BongaCams <strong>Options</strong> → <strong>Broadcast settings</strong> → <strong>Select Encoder</strong> → <strong>External Encoder</strong> را باز کنید و URL سرور و کلید جریان نمایش داده شده را کپی کنید. <strong>اگر دکمه External Encoder وجود ندارد</strong>، با پشتیبانی BongaCams تماس بگیرید و درخواست فعال‌سازی رمزگذاری خارجی روی حساب کنید.",
       [("بدون دکمه External Encoder؟ پشتیبانی", "BongaCams رمزگذاری خارجی را برای هر حساب جداگانه فعال می‌کند — اگر گزینه در Broadcast settings نیست، پشتیبانی آن را فعال می‌کند."),
        ("رزولوشن را تطبیق دهید", "BongaCams توصیه می‌کند رزولوشن وب‌کم و پخش یکسان باشد — مثلاً هر دو ۱۲۸۰×۷۲۰."),
        _T_ETH, _T_TEST],
       [("چرا دکمه External Encoder در BongaCams ظاهر نمی‌شود؟", "رمزگذاری خارجی به طور پیش‌فرض روی هر حساب فعال نیست — با پشتیبانی BongaCams تماس بگیرید تا فعال شود."),
        ("آیا باید حساب BongaCams را تأیید کنم؟", "بله — پخش نیاز به ۱۸+، مدرک رسمی برای تأیید سن و تأیید حساب قبل از پخش زنده دارد."),
        ("بیت‌ریت BongaCams چقدر باشد؟", "RTMP ingest BongaCams بیت‌ریت ویدیو را به حدود ۶۰۰۰ کیلوبیت بر ثانیه با فریم کلیدی ۲ ثانیه محدود می‌کند — ۳۵۰۰–۶۰۰۰ در ۱۰۸۰p منطقه ایده‌آل است."),
        ("آیا SplitCam برای BongaCams رایگان است؟", "بله — کاملاً رایگان، بدون واترمارک و بدون محدودیت زمانی.")]),
    _p("stripchat", "Stripchat",
       "پخش در Stripchat با SplitCam — تنظیم strip cam",
       "پخش در Stripchat با SplitCam رایگان. نرم‌افزار خارجی، کلید مبتنی بر توکن، صحنه‌ها و پوشش‌ها.",
       "strip cam, stripchat live stream, پخش stripchat, stripchat external software, stripchat کلید جریان, stripchat rtmp obs",
       'نحوه پخش در <span class="accent">Stripchat</span> با SplitCam',
       "پخش Stripchat",
       "تنظیم نرم‌افزار خارجی برای پخش Stripchat.",
       "Stripchat یک پلتفرم کم بزرگ با تمرکز بر تعامل است. حالت <em>external software</em> به شما یک کلید مبتنی بر توکن می‌دهد — آن را در <strong style='color:var(--text)'>SplitCam</strong> رایگان وارد کنید تا با صحنه‌ها، پوشش‌ها و فیلترها پخش کنید.",
       "پخش در Stripchat با SplitCam: SplitCam را نصب کنید، صحنه بسازید، در Stripchat <em>Switch to external software</em> را انتخاب کنید، کلید جریان را کپی کنید، در SplitCam جای‌گذاری کنید، Go Live."
       "<ol><li>SplitCam را نصب کنید.</li><li>دوربین + صحنه اضافه کنید.</li><li>کلید جریان از Stripchat دریافت کنید.</li><li>در SplitCam جای‌گذاری کنید.</li><li>Go Live را فشار دهید.</li></ol>",
       "در Stripchat <strong>Switch to external software</strong> و سپس <strong>Show external software settings for the stream</strong> را انتخاب کنید. کلید جریان را کپی کنید — Stripchat آن را به عنوان توکن نمایش می‌دهد. آن را محرمانه نگه دارید.",
       [("رزولوشن را با سایت تطبیق دهید", "FAQ Stripchat هشدار می‌دهد: رزولوشن نرم‌افزار شما باید دقیقاً با سایت مطابقت داشته باشد وگرنه ویدیو خراب می‌شود."),
        ("حداقل ۲ مگابیت بر ثانیه توجه کنید", "Stripchat ۲ مگابیت بر ثانیه آپلود را به عنوان حداقل ذکر می‌کند — و صراحتاً می‌گوید برای پخش OBS یا multistream کافی نیست. بسیار بالاتر هدف بگیرید."),
        ("کلید توکن است", "کلید جریان Stripchat توکن است — دقیقاً کپی کنید، هرگز به اشتراک نگذارید، اگر لو رفت بازنشانی کنید."),
        _T_ETH],
       [("آیا Stripchat OBS / نرم‌افزار خارجی را توصیه می‌کند؟", "بله — FAQ رسمی Stripchat نرم‌افزار پخش خارجی مثل OBS را «برای دستیابی به بهترین کیفیت» توصیه می‌کند."),
        ("چطور Stripchat را به نرم‌افزار خارجی تغییر دهم؟", "در Broadcast Center گزینه Switch to External Broadcast Software (OBS) را انتخاب کنید، سپس external software settings را باز کنید."),
        ("بیت‌ریت Stripchat چقدر باشد؟", "RTMP ingest تا ~۶۰۰۰ کیلوبیت بر ثانیه با فریم کلیدی ۲ ثانیه می‌پذیرد. ۳۵۰۰–۶۰۰۰ در ۱۰۸۰p ایده‌آل است."),
        ("آیا SplitCam برای Stripchat رایگان است؟", "بله — بدون هزینه مجوز، بدون واترمارک، بدون محدودیت زمانی.")]),
    _p("onlyfans", "OnlyFans",
       "پخش زنده OnlyFans با SplitCam — مجوز یا کلید",
       "پخش زنده OnlyFans با SplitCam رایگان — ورود از طریق مجوز یا OBS Key، صحنه‌های چندکاره، پوشش‌ها. بدون واترمارک.",
       "پخش زنده onlyfans, onlyfans live stream, onlyfans مجوز splitcam, onlyfans obs key, onlyfans نرم‌افزار پخش",
       'نحوه <span class="accent">پخش زنده OnlyFans</span> با SplitCam',
       "پخش زنده OnlyFans",
       "یک‌بار مجوز دهید یا کلید جای‌گذاری کنید — پخش زنده در OnlyFans.",
       "پخش زنده OnlyFans برای مشترکان شما. SplitCam به <strong style='color:var(--text)'>دو روش</strong> متصل می‌شود — یک‌بار با حساب OnlyFans وارد شوید و SplitCam به طور خودکار کلید جریان را دریافت و همگام‌سازی می‌کند، یا OBS Key را دستی جای‌گذاری کنید.",
       "پخش زنده OnlyFans با SplitCam: SplitCam را نصب کنید، صحنه بسازید، Stream Settings &rarr; Add Channel &rarr; OnlyFans را باز کنید و <em>مجوز</em> را انتخاب کنید — با حساب OnlyFans وارد شوید، SplitCam کلید را خودکار دریافت می‌کند — سپس Go Live.",
       "در OnlyFans: <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; بخش <strong>Other</strong>، <strong>OBS Key</strong> را کپی کنید. یا از گزینه <strong>مجوز</strong> در SplitCam برای ورود استفاده کنید — کلید خودکار دریافت و همگام می‌شود.",
       [("مجوز در مقابل Stream Key", "دو روش اتصال: <strong>مجوز</strong> (یک‌بار وارد شوید، کلید دریافت و همگام می‌شود — ساده‌ترین روش) یا <strong>Stream Key</strong> (OBS Key را در OnlyFans → Profile → Settings → Other کپی کرده و جای‌گذاری کنید)."),
        ("تنظیمات را بدون خروج از SplitCam تغییر دهید", "با مجوز، حساب متصل می‌ماند، بنابراین پارامترهای پخش زنده OnlyFans را از SplitCam در طول یا پس از پخش تنظیم می‌کنید."),
        ("بیت‌ریت متوسط", "RTMP ingest OnlyFans بیت‌ریت ویدیو را به حدود ۲۵۰۰ کیلوبیت بر ثانیه محدود می‌کند — سخت‌گیرانه‌تر از اکثر سایت‌های کم."),
        _T_ETH],
       [("چطور OnlyFans را به SplitCam متصل کنم؟", "دو روش. <strong>مجوز</strong> — Stream Settings → Add Channel → OnlyFans → با حساب OnlyFans وارد شوید. یا <strong>Stream Key</strong> — OBS Key را در OnlyFans → Profile → Settings → Other کپی کرده و جای‌گذاری کنید."),
        ("می‌توانم تنظیمات پخش زنده OnlyFans را بدون باز کردن سایت تغییر دهم؟", "بله — با روش مجوز، SplitCam به حساب OnlyFans متصل می‌ماند و کلید و تنظیمات خودکار همگام می‌شوند."),
        ("بیت‌ریت OnlyFans چقدر باشد؟", "متوسط — RTMP ingest OnlyFans بیت‌ریت را به حدود ۲۵۰۰ کیلوبیت بر ثانیه محدود می‌کند. ۷۲۰p–۱۰۸۰p در ~۲۰۰۰–۲۵۰۰ هدف بگیرید."),
        ("آیا SplitCam برای پخش زنده OnlyFans رایگان است؟", "بله — رایگان، بدون واترمارک و بدون محدودیت زمانی.")]),
    _p("camplace", "CamPlace",
       "پخش در CamPlace با SplitCam — راهنمای رایگان",
       "پخش در CamPlace با SplitCam رایگان — رمزگذار خارجی، کلید RTMP، صحنه‌ها و پوشش‌ها. گام‌به‌گام، بدون واترمارک.",
       "پخش camplace, camplace broadcasting software, camplace rtmp, camplace رمزگذار خارجی, camplace کلید جریان",
       'نحوه پخش در <span class="accent">CamPlace</span> با SplitCam',
       "پخش CamPlace",
       "تنظیم رمزگذار خارجی برای پخش CamPlace.",
       "CamPlace یک پلتفرم cam-streaming است. مقاله‌ای عمومی درباره OBS وجود ندارد، بنابراین <strong style='color:var(--text)'>راهنمای ویدیویی بالا</strong> مرجع شماست — <strong style='color:var(--text)'>SplitCam</strong> رایگان از طریق RTMP استاندارد متصل می‌شود.",
       "پخش در CamPlace با SplitCam: SplitCam را نصب کنید، صحنه بسازید، پخش خارجی/RTMP را در CamPlace فعال کنید، URL سرور و کلید جریان را کپی کنید، در SplitCam جای‌گذاری کنید، Go Live."
       "<ol><li>SplitCam را نصب کنید.</li><li>دوربین + صحنه اضافه کنید.</li><li>کلید RTMP از CamPlace دریافت کنید.</li><li>در SplitCam جای‌گذاری کنید.</li><li>Go Live را فشار دهید.</li></ol>",
       "وارد CamPlace شوید و تنظیمات پخش را باز کنید. به گزینه رمزگذار خارجی / RTMP / OBS تغییر دهید تا <strong>URL سرور</strong> و <strong>کلید جریان</strong> نمایش داده شود، هر دو را کپی کنید.",
       [("بدون راهنمای OBS رسمی — از ویدیو استفاده کنید", "CamPlace مقاله‌ای درباره رمزگذار خارجی ندارد؛ ویدیوی بالا مرجع مسیر فعلی است."),
        ("RTMP استاندارد کار می‌کند", "با وجود عدم مستندسازی، CamPlace URL سرور RTMP استاندارد و کلید را می‌پذیرد — SplitCam به عنوان یک مقصد RTMP سفارشی متصل می‌شود."),
        ("پوشش‌ها را در SplitCam بچینید", "اهداف انعام، نام و دستیار شبکه‌های اجتماعی را به عنوان لایه‌های صحنه اضافه کنید."),
        _T_ETH],
       [("آیا CamPlace راهنمای OBS رسمی دارد؟", "هیچ مقاله‌ای درباره رمزگذار خارجی پیدا نشد. CamPlace URL RTMP استاندارد و کلید را می‌پذیرد، بنابراین SplitCam کار می‌کند — از ویدیو پیروی کنید."),
        ("آیا CamPlace رمزگذار خارجی را پشتیبانی می‌کند؟", "بله — کلید جریان RTMP استاندارد را می‌پذیرد."),
        ("بیت‌ریت CamPlace چقدر باشد؟", "CamPlace ارقام رسمی منتشر نمی‌کند — از ۳۵۰۰–۶۰۰۰ کیلوبیت بر ثانیه در ۱۰۸۰p به عنوان محدوده ایمن استفاده کنید."),
        ("آیا SplitCam برای CamPlace رایگان است؟", "بله — رایگان، بدون واترمارک و بدون محدودیت زمانی.")]),
    _p("camsoda", "CamSoda",
       "CamSoda پخش زنده با SplitCam — تنظیم رایگان",
       "CamSoda پخش زنده با SplitCam رایگان — Use OBS Broadcaster، سرورهای منطقه‌ای، صحنه‌ها و پوشش‌ها. بدون واترمارک.",
       "camsoda live, پخش camsoda, camsoda obs broadcaster, camsoda rtmp obs, camsoda live broadcast",
       'نحوه پخش در <span class="accent">CamSoda</span> با SplitCam',
       "پخش CamSoda",
       "تنظیم Use OBS Broadcaster در CamSoda.",
       "CamSoda یک پلتفرم کم آمریکایی است که با فرمت‌های نمایش تعاملی و غیرمعمول شناخته شده است. پخش OBS را رسماً پشتیبانی می‌کند — دکمه <strong style='color:var(--text)'>Use OBS Broadcaster</strong> در صفحه Go Live و راهنمای OBS رسمی در ویکی CamSoda وجود دارد.",
       "پخش در CamSoda با SplitCam: SplitCam را نصب کنید، صحنه بسازید، روی Use OBS Broadcaster در صفحه Go Live CamSoda کلیک کنید، URL سرور و کلید جریان را کپی کنید، در SplitCam جای‌گذاری کنید، Go Live."
       "<ol><li>SplitCam را نصب کنید.</li><li>دوربین + صحنه اضافه کنید.</li><li>Use OBS Broadcaster در CamSoda کلیک کنید.</li><li>URL سرور + کلید را در SplitCam جای‌گذاری کنید.</li><li>Go Live را فشار دهید.</li></ol>",
       "در صفحه <strong>Go Live</strong> CamSoda روی <strong>Use OBS Broadcaster</strong> کلیک کنید. CamSoda URL سرور RTMP و کلید جریان را نمایش می‌دهد — هر دو را کپی کنید. نزدیک‌ترین سرور منطقه‌ای را انتخاب کنید.",
       [("برای دریافت انعام تأیید شوید", "در CamSoda هر کسی می‌تواند پخش کند، اما برای دریافت انعام باید فرآیند تأیید CamSoda را تکمیل کنید."),
        ("نزدیک‌ترین سرور منطقه‌ای را انتخاب کنید", "CamSoda سرورهای ingest منطقه‌ای ارائه می‌دهد — نزدیک‌ترین (آمریکای شمالی / اروپا / آسیا / آمریکای جنوبی / اقیانوسیه) تأخیر و فریم‌های از دست رفته را کاهش می‌دهد."),
        ("سقف در ۱۰۸۰p / ۳۰ fps", "ingest CamSoda به حدود ۱۰۸۰p، ۳۰ fps و ~۶۰۰۰ کیلوبیت بر ثانیه می‌رسد — بالاتر نبرید."),
        _T_ETH],
       [("آیا CamSoda OBS / رمزگذار خارجی را پشتیبانی می‌کند؟", "بله — رسماً. دکمه Use OBS Broadcaster در صفحه Go Live و راهنمای OBS در ویکی CamSoda وجود دارد."),
        ("آیا نیاز به تأیید در CamSoda دارم؟", "برای پخش نه. برای دریافت انعام بله."),
        ("چه رزولوشنی CamSoda پشتیبانی می‌کند؟", "تا ۱۹۲۰×۱۰۸۰ در ۳۰ fps، حداکثر حدود ۶۰۰۰ کیلوبیت بر ثانیه."),
        ("آیا SplitCam برای CamSoda رایگان است؟", "بله — رایگان، بدون واترمارک و بدون محدودیت زمانی.")]),
    _p("streamate", "Streamate",
       "پخش در Streamate با SplitCam — کانال یکپارچه",
       "پخش در Streamate با SplitCam رایگان — کانال یکپارچه، کلید SM Connect، صحنه‌ها و پوشش‌ها. بدون واترمارک.",
       "streamate, streamate sm connect, پخش streamate, streamate broadcasting software, streamate rtmp",
       'نحوه پخش در <span class="accent">Streamate</span> با SplitCam',
       "پخش Streamate",
       "Streamate یک کانال یکپارچه در SplitCam است — تنظیم سریع.",
       "Streamate یک پلتفرم کم معتبر است — و یک <strong style='color:var(--text)'>مقصد از پیش پیکربندی شده در SplitCam</strong> در لیست کانال‌هاست، بنابراین تنظیم سریع‌تر از ورود دستی RTMP است: Streamate را انتخاب کنید، کلید را جای‌گذاری کنید، تمام.",
       "پخش در Streamate با SplitCam: SplitCam را نصب کنید، صحنه بسازید، در Streamate از <em>SM Connect → Start Show</em> استفاده کنید و کلید را کپی کنید، سپس در SplitCam <em>Stream Settings → Add Channel → Streamate</em> را باز کنید و جای‌گذاری کنید."
       "<ol><li>SplitCam را نصب کنید.</li><li>دوربین + صحنه اضافه کنید.</li><li>کلید Streamate را از طریق SM Connect دریافت کنید.</li><li>Add Channel → Streamate در SplitCam.</li><li>Go Live را فشار دهید.</li></ol>",
       "در Streamate <strong>SM Connect</strong> را باز کنید، شرایط را بپذیرید، <strong>Start Show</strong> را از سمت چپ کلیک کنید و پنجره باز شده را ببندید — سپس کلید پخش را کپی کنید.",
       [("Streamate یکپارچه است", "بدون URL RTMP دستی — SplitCam Streamate را در لیست Add Channel دارد؛ فقط انتخاب کرده و کلید را جای‌گذاری کنید."),
        ("پنجره SM Connect را ببندید", "پس از Start Show، Streamate یک پنجره باز می‌کند — آن را ببندید؛ فقط برای نمایش کلید پخش است."),
        ("رزولوشن را روی ۱۰۸۰p قفل کنید", "فیلد Video Resolution در SM Connect ممکن است بی‌صدا به ۱۴۴۰ بپرد — دستی روی ۱۰۸۰p تنظیم کنید."),
        _T_ETH, _T_TEST],
       [("آیا Streamate در SplitCam یکپارچه است؟", "بله — Streamate در لیست Add Channel SplitCam ظاهر می‌شود."),
        ("کلید پخش Streamate کجاست؟", "SM Connect → شرایط را بپذیرید → Start Show → پنجره را ببندید → کلید را کپی کنید."),
        ("بیت‌ریت Streamate چقدر باشد؟", "Streamate سقف سختی ندارد — ۳۵۰۰–۶۰۰۰ کیلوبیت بر ثانیه در ۱۰۸۰p خوب کار می‌کند."),
        ("آیا SplitCam برای Streamate رایگان است؟", "بله — رایگان، بدون واترمارک و بدون محدودیت زمانی.")]),
    _p("streamray", "StreamRay",
       "پخش در StreamRay cam با SplitCam — URL در چت",
       "پخش در StreamRay cam با SplitCam رایگان — URL در چت ارسال می‌شود، حالت OBS Broadcaster، صحنه‌ها و پوشش‌ها.",
       "streamray, streamray cam, پخش streamray, streamray obs broadcaster, streamray rtmp",
       'نحوه پخش در <span class="accent">StreamRay</span> با SplitCam',
       "پخش StreamRay",
       "تنظیم رمزگذار خارجی نوع URL-در-چت برای StreamRay.",
       "StreamRay تنظیم رمزگذار خارجی غیرمعمولی دارد — URL جریان را در <strong style='color:var(--text)'>پنجره چت پخش</strong> ارسال می‌کند و از کلید جداگانه استفاده نمی‌کند.",
       "پخش در StreamRay با SplitCam: SplitCam را نصب کنید، صحنه بسازید، OBS Broadcaster را در StreamRay فعال کنید، URL جریان را از پنجره چت کپی کنید، در SplitCam جای‌گذاری کنید (فیلد کلید را خالی بگذارید)، Go Live."
       "<ol><li>SplitCam را نصب کنید.</li><li>دوربین + صحنه اضافه کنید.</li><li>URL StreamRay را از چت کپی کنید.</li><li>URL را در SplitCam جای‌گذاری کنید.</li><li>Go Live را فشار دهید.</li></ol>",
       "در StreamRay دوبار کلیک کنید <strong>Broadcast Now</strong>، منوی <strong>Other</strong> را باز کنید، <strong>OBS Broadcaster</strong> و <strong>Save and Close</strong> را انتخاب کنید. StreamRay سپس <strong>URL جریان را در پنجره چت</strong> ارسال می‌کند — از آنجا کپی کنید. فیلد کلید جریان SplitCam را <strong>خالی</strong> بگذارید.",
       [("URL در چت است", "StreamRay URL جریان را در جعبه تنظیمات نمایش نمی‌دهد — آن را در پنجره چت پخش ارسال می‌کند."),
        ("فیلد کلید را خالی بگذارید", "StreamRay از کلید جداگانه استفاده نمی‌کند — فقط URL."),
        _T_ETH, _T_TEST],
       [("URL جریان StreamRay کجاست؟", "پس از فعال‌سازی OBS Broadcaster، StreamRay URL را در پنجره چت ارسال می‌کند."),
        ("چرا کلید جریانی در StreamRay وجود ندارد؟", "StreamRay فقط از طریق URL تأیید می‌کند — فیلد کلید SplitCam را خالی بگذارید."),
        ("بیت‌ریت StreamRay چقدر باشد؟", "StreamRay سقف رسمی ذکر نمی‌کند — ۳۵۰۰–۶۰۰۰ کیلوبیت بر ثانیه در ۱۰۸۰p هدف بگیرید."),
        ("آیا SplitCam برای StreamRay رایگان است؟", "بله — رایگان، بدون واترمارک و بدون محدودیت زمانی.")]),
    _p("xlovecam", "XLoveCam",
       "پخش در XLoveCam با SplitCam — لینک RTMP و کلید",
       "پخش در XLoveCam با SplitCam رایگان — لینک RTMP و کلید، سرورهای منطقه‌ای، صحنه‌ها و پوشش‌ها.",
       "xlovecam, x love cam, پخش xlovecam, xlovecam rtmp link, xlovecam کلید جریان",
       'نحوه پخش در <span class="accent">XLoveCam</span> با SplitCam',
       "پخش XLoveCam",
       "تنظیم لینک RTMP + کلید برای XLoveCam.",
       "XLoveCam یک پلتفرم کم اروپایی چندزبانه است. تنظیمات حساب هم <strong style='color:var(--text)'>لینک RTMP</strong> و هم <strong style='color:var(--text)'>کلید جریان</strong> را نمایش می‌دهد.",
       "پخش در XLoveCam با SplitCam: SplitCam را نصب کنید، صحنه بسازید، در XLoveCam <em>My Account → settings</em> را باز کنید، لینک RTMP و کلید جریان را کپی کنید، هر دو را در SplitCam جای‌گذاری کنید، نمایش را شروع کنید."
       "<ol><li>SplitCam را نصب کنید.</li><li>دوربین + صحنه اضافه کنید.</li><li>لینک RTMP + کلید را از XLoveCam کپی کنید.</li><li>هر دو را در SplitCam جای‌گذاری کنید.</li><li>Go Live را فشار دهید.</li></ol>",
       "در XLoveCam <strong>My Account</strong> → <strong>settings</strong> را باز کنید. تنظیمات هم <strong>لینک RTMP</strong> و هم <strong>کلید جریان</strong> را نمایش می‌دهد.",
       [("لینک و کلید را کپی کنید", "XLoveCam لینک RTMP و کلید جریان جداگانه می‌دهد — به هر دو در SplitCam نیاز دارید."),
        ("مخاطبان چندزبانه", "XLoveCam اروپایی و چندزبانه است — پوشش‌های متنی واضح به زبان شما به بینندگان کمک می‌کند شما را پیدا کنند."),
        ("نزدیک‌ترین سرور را انتخاب کنید", "XLoveCam سرورهای RTMP منطقه‌ای ارائه می‌دهد — اروپا، آمریکای شمالی، آمریکای جنوبی و آسیا."),
        _T_ETH],
       [("داده‌های RTMP XLoveCam کجاست؟", "My Account → settings — هم لینک RTMP و هم کلید را نمایش می‌دهد."),
        ("آیا XLoveCam رمزگذار خارجی را پشتیبانی می‌کند؟", "بله — لینک RTMP و کلید ارائه می‌دهد."),
        ("بیت‌ریت XLoveCam چقدر باشد؟", "XLoveCam محدودیت ثابتی منتشر نمی‌کند؛ ۳۵۰۰–۶۰۰۰ در ۱۰۸۰p ایده‌آل است."),
        ("آیا SplitCam برای XLoveCam رایگان است؟", "بله — رایگان، بدون واترمارک و بدون محدودیت زمانی.")]),
    _p("soulcams", "SoulCams",
       "پخش در SoulCams با SplitCam — تنظیمات OBS",
       "پخش در SoulCams با SplitCam رایگان — تنظیمات OBS، سرور RTMP و کلید، صحنه‌های چندکاره و پوشش‌ها.",
       "soul cams, soulcams, پخش soulcams, soulcams obs, soulcams rtmp, soulcams broadcast",
       'نحوه پخش در <span class="accent">SoulCams</span> با SplitCam',
       "پخش SoulCams",
       "تنظیمات OBS برای SoulCams.",
       "SoulCams پلتفرمی است که تنظیمات OBS آن <strong style='color:var(--text)'>سرور RTMP و کلید جریان را با هم</strong> در یک پنجره نمایش می‌دهد.",
       "پخش در SoulCams با SplitCam: SplitCam را نصب کنید، صحنه بسازید، در SoulCams روی Go Online → Settings → OBS کلیک کنید، سرور و کلید را کپی کنید، هر دو را در SplitCam جای‌گذاری کنید، Go Live."
       "<ol><li>SplitCam را نصب کنید.</li><li>دوربین + صحنه اضافه کنید.</li><li>SoulCams Settings → OBS را باز کنید.</li><li>سرور + کلید را در SplitCam جای‌گذاری کنید.</li><li>Go Live را فشار دهید.</li></ol>",
       "در SoulCams وارد شوید و <strong>Go Online</strong> را کلیک کنید، سپس <strong>Settings</strong> → <strong>OBS</strong> را باز کنید. پنجره OBS <strong>سرور RTMP</strong> و <strong>کلید جریان</strong> را با هم نمایش می‌دهد.",
       [("سرور و کلید کنار هم هستند", "SoulCams سرور RTMP و کلید را در همان پنجره OBS نمایش می‌دهد — هر دو را یک‌جا بگیرید."),
        ("ابتدا Go Online", "تنظیمات OBS فقط پس از کلیک Go Online در SoulCams ظاهر می‌شود."),
        ("مناطق ناخواسته را مسدود کنید", "SoulCams مسدودسازی جغرافیایی از طرف مدل را مجاز می‌داند."),
        _T_ETH, _T_TEST],
       [("تنظیمات OBS SoulCams کجاست؟", "وارد شوید، Go Online کلیک کنید، سپس Settings → OBS."),
        ("آیا SoulCams رمزگذار خارجی را پشتیبانی می‌کند؟", "بله — تنظیمات OBS سرور RTMP و کلید می‌دهد."),
        ("بیت‌ریت SoulCams چقدر باشد؟", "SoulCams ارقام رسمی نمی‌دهد — ۳۵۰۰–۶۰۰۰ در ۱۰۸۰p هدف بگیرید."),
        ("آیا SplitCam برای SoulCams رایگان است؟", "بله — رایگان، بدون واترمارک و بدون محدودیت زمانی.")]),
    _p("imlive", "ImLive",
       "استفاده از ImLive با SplitCam — دوربین مجازی",
       "تنظیم Im Live stream با SplitCam رایگان — ImLive از دوربین زنده استفاده می‌کند (بدون RTMP)، SplitCam را به عنوان دوربین مجازی متصل کنید.",
       "im live stream, imlive splitcam, پخش imlive, imlive دوربین مجازی, imlive webcam, im live cam",
       'نحوه استفاده از <span class="accent">ImLive</span> با SplitCam',
       "SplitCam در ImLive",
       "تنظیم دوربین مجازی برای ImLive — بدون RTMP.",
       "ImLive از وب‌کم زنده در مرورگر استفاده می‌کند — <strong style='color:var(--text)'>بدون RTMP یا کلید جریان</strong>. <strong style='color:var(--text)'>SplitCam</strong> رایگان به عنوان <strong style='color:var(--text)'>دوربین مجازی</strong> متصل می‌شود.",
       "استفاده از SplitCam با ImLive: SplitCam را نصب کنید، صحنه با لایه‌های رسانه بسازید، ImLive را باز کنید و چت ویدیویی شروع کنید، در تنظیمات ImLive SplitCam را به عنوان وب‌کم و میکروفون انتخاب کنید."
       "<ol><li>SplitCam را نصب کنید.</li><li>صحنه را در SplitCam بسازید.</li><li>چت ویدیویی در ImLive شروع کنید.</li><li>SplitCam را به عنوان دوربین ImLive انتخاب کنید.</li><li>چت را شروع کنید.</li></ol>",
       "وارد سایت ImLive شوید و <strong>Start Video Chat</strong> را کلیک کنید، سپس <strong>Go To Settings</strong> را برای دسترسی به گزینه‌های دوربین و میکروفون باز کنید.",
       [("کلید جریان لازم نیست", "ImLive RTMP ندارد — URL سرور یا کلید را جستجو نکنید. SplitCam فقط به عنوان دستگاه دوربین انتخاب می‌شود."),
        ("SplitCam را به عنوان میکروفون هم تنظیم کنید", "SplitCam را برای میکروفون علاوه بر دوربین انتخاب کنید."),
        ("صحنه را قبل از پخش بسازید", "ImLive آنچه SplitCam ارسال می‌کند را نمایش می‌دهد."),
        _T_TEST],
       [("آیا ImLive از RTMP یا کلید جریان استفاده می‌کند؟", "هیچ‌کدام — ImLive از وب‌کم زنده از طریق مرورگر استفاده می‌کند."),
        ("چطور SplitCam را در ImLive انتخاب کنم؟", "Start Video Chat → Go To Settings → SplitCam را به عنوان وب‌کم و میکروفون انتخاب کنید."),
        ("می‌توانم از پوشش‌ها در ImLive استفاده کنم؟", "بله — آنها را در صحنه SplitCam بسازید."),
        ("آیا SplitCam برای ImLive رایگان است؟", "بله — رایگان، بدون واترمارک و بدون محدودیت زمانی.")],
       steps=[
           ("SplitCam را نصب کنید", "SplitCam نرم‌افزار رایگان برای Windows و macOS است. آن را نصب کنید — بدون واترمارک، بدون ثبت‌نام."),
           ("صحنه را در SplitCam بسازید", "SplitCam را باز کنید و از <strong>Media Layers +</strong> برای افزودن وب‌کم با پوشش‌ها، متن، فیلترها یا پس‌زمینه هوش مصنوعی استفاده کنید."),
           ("چت ویدیویی در ImLive شروع کنید", "وارد سایت ImLive شوید و <strong>Start Video Chat</strong> را کلیک کنید، سپس <strong>Go To Settings</strong> را باز کنید."),
           ("SplitCam را به عنوان دوربین انتخاب کنید", "در تنظیمات ImLive، <strong>SplitCam</strong> را به عنوان وب‌کم و میکروفون انتخاب کنید."),
           ("Free Live Chat را شروع کنید", "روی <strong>Free Live Chat</strong> در ImLive کلیک کنید تا پخش زنده شود."),
       ]),
    _p("vxlive", "VXLive",
       "پخش در VXLive با SplitCam — پشتیبانی رسمی",
       "پخش در VXLive (VXModels / VISIT-X) با SplitCam رایگان — preset رسمی VISIT-X، سرور و کلید، صحنه‌ها.",
       "vxlive, visit-x, vxmodels splitcam, پخش vxlive, visit-x stream, vxlive rtmp",
       'نحوه پخش در <span class="accent">VXLive</span> با SplitCam',
       "پخش VXLive",
       "VXLive از SplitCam رسماً پشتیبانی می‌کند (preset VISIT-X).",
       "VXLive (VXModels / VISIT-X) یک پلتفرم کم از بازار آلمان است — و یکی از معدود پلتفرم‌هایی که <strong style='color:var(--text)'>از SplitCam با نام رسماً پشتیبانی می‌کند</strong>.",
       "پخش در VXLive با SplitCam: SplitCam را نصب کنید، صحنه بسازید، در VXLive «Stream with third-party software» را انتخاب کنید، URL سرور و کلید را کپی کنید، در SplitCam preset VISIT-X را انتخاب و جای‌گذاری کنید، در SplitCam Go Live، سپس GO ONLINE در VXLive."
       "<ol><li>SplitCam را نصب کنید.</li><li>دوربین + صحنه اضافه کنید.</li><li>URL سرور + کلید از VXLive دریافت کنید.</li><li>preset VISIT-X در SplitCam انتخاب کنید، جای‌گذاری کنید.</li><li>Go Live، سپس GO ONLINE در VXLive.</li></ol>",
       "در VXLive <strong>Stream with third-party software</strong> و گزینه <strong>OBS, SplitCam یا XSplit</strong> را انتخاب کنید.",
       [("VISIT-X یک preset یکپارچه است", "URL RTMP خام وارد نکنید — SplitCam VISIT-X را در لیست پلتفرم‌ها دارد."),
        ("go-live دو مرحله‌ای", "در VXLive ابتدا در SplitCam Go Live، سپس GO ONLINE در VXLive — هر دو، به این ترتیب."),
        ("بازار آلمان", "مخاطبان VXLive عمدتاً آلمانی‌زبان هستند."),
        _T_ETH],
       [("آیا VXLive از SplitCam رسماً پشتیبانی می‌کند؟", "بله — VXModels مقاله راهنمایی اختصاصی برای تنظیم SplitCam دارد."),
        ("چطور SplitCam را به VXLive متصل کنم؟", "در VXLive «Stream with third-party software» را انتخاب کنید، سپس در SplitCam preset VISIT-X را انتخاب کنید."),
        ("در SplitCam پخش می‌کنم یا VXLive؟", "هر دو — ابتدا در SplitCam Go Live، سپس GO ONLINE در VXLive."),
        ("چرا VXModels SplitCam را توصیه می‌کند؟", "مقاله راهنمای رسمی VXModels SplitCam را برای حذف آرتیفکت‌های تصویر و پیکسل‌شدگی توصیه می‌کند.")]),
    _p("virtwish", "VirtWish",
       "پخش در VirtWish با SplitCam — URL جریان و کلید",
       "پخش در VirtWish با SplitCam رایگان — بخش OBS Profile → Start Broadcast، URL جریان و کلید، صحنه‌ها و پوشش‌ها.",
       "virtwish, پخش virtwish, virtwish broadcasting software, virtwish rtmp, virtwish کلید جریان, virtwish obs",
       'نحوه پخش در <span class="accent">VirtWish</span> با SplitCam',
       "پخش VirtWish",
       "تنظیم URL جریان + کلید برای VirtWish.",
       "VirtWish یک پلتفرم کم تعاملی است. تنظیمات پخش <strong style='color:var(--text)'>URL جریان و کلید جریان جداگانه</strong> در بخش OBS می‌دهد.",
       "پخش در VirtWish با SplitCam: SplitCam را نصب کنید، صحنه بسازید، در VirtWish <em>Profile → Start Broadcast</em> تا بخش OBS بروید، لینک و کلید را کپی کنید، هر دو را در SplitCam جای‌گذاری کنید، Go Live."
       "<ol><li>SplitCam را نصب کنید.</li><li>دوربین + صحنه اضافه کنید.</li><li>URL + کلید از VirtWish دریافت کنید.</li><li>هر دو را در SplitCam جای‌گذاری کنید.</li><li>Go Live را فشار دهید.</li></ol>",
       "در VirtWish روی آیکون گوشه بالا سمت راست → <strong>Profile</strong> → <strong>Start Broadcast</strong> کلیک کنید، سپس دوباره <strong>Start Broadcast</strong> تا به بخش OBS برسید.",
       [("لینک در ردیف اول است", "بخش OBS VirtWish URL جریان را در ردیف اول قرار می‌دهد."),
        ("دو کلیک روی Start Broadcast", "دوبار روی Start Broadcast در VirtWish کلیک می‌کنید تا به بخش OBS برسید — این طبیعی است."),
        _T_ETH, _T_TEST],
       [("داده‌های RTMP VirtWish کجاست؟", "آیکون گوشه بالا راست → Profile → Start Broadcast دوبار → بخش OBS لینک و کلید جریان را نمایش می‌دهد."),
        ("آیا VirtWish رمزگذار خارجی را پشتیبانی می‌کند؟", "بله — بخش OBS URL جریان و کلید ارائه می‌دهد."),
        ("بیت‌ریت VirtWish چقدر باشد؟", "VirtWish سقف رسمی منتشر نمی‌کند؛ ۳۵۰۰–۶۰۰۰ در ۱۰۸۰p امن است."),
        ("آیا SplitCam برای VirtWish رایگان است؟", "بله — رایگان، بدون واترمارک و بدون محدودیت زمانی.")]),
    _p("xmodels", "XModels",
       "پخش در XModels با SplitCam — راهنمای رایگان",
       "پخش در XModels با SplitCam رایگان — گزینه رمزگذار خارجی در تنظیمات حساب مدل، کلید RTMP، صحنه‌ها و پوشش‌ها.",
       "xmodels, پخش xmodels, xmodels broadcasting software, xmodels rtmp, xmodels رمزگذار خارجی",
       'نحوه پخش در <span class="accent">XModels</span> با SplitCam',
       "پخش XModels",
       "تنظیم رمزگذار خارجی برای پخش XModels.",
       "XModels یک پلتفرم cam-streaming با <strong style='color:var(--text)'>گزینه رمزگذار خارجی</strong> داخلی در تنظیمات حساب مدل است.",
       "پخش در XModels با SplitCam: SplitCam را نصب کنید، صحنه بسازید، در حساب مدل XModels گزینه رمزگذار خارجی را فعال کنید، URL سرور و کلید جریان را کپی کنید، در SplitCam جای‌گذاری کنید، Go Live."
       "<ol><li>SplitCam را نصب کنید.</li><li>دوربین + صحنه اضافه کنید.</li><li>رمزگذار خارجی را در تنظیمات XModels فعال کنید.</li><li>URL سرور + کلید را در SplitCam جای‌گذاری کنید.</li><li>Go Live را فشار دهید.</li></ol>",
       "در <strong>تنظیمات حساب مدل</strong> XModels، گزینه <strong>پخش از طریق رمزگذار خارجی</strong> را فعال کنید.",
       [("در تنظیمات حساب است", "XModels گزینه رمزگذار خارجی را در تنظیمات حساب مدل قرار می‌دهد."),
        ("پشتیبانی: چت + ایمیل", "XModels مرکز راهنمایی عمومی بزرگی ندارد — چت FAQ در سایت و info@xmodels.com."),
        ("پوشش‌ها را در SplitCam بچینید", "اهداف انعام، نام و کانال‌های شبکه اجتماعی را به عنوان لایه‌های صحنه اضافه کنید."),
        _T_ETH],
       [("آیا XModels رمزگذار خارجی را پشتیبانی می‌کند؟", "بله — تنظیمات حساب مدل گزینه پخش رمزگذار خارجی دارد."),
        ("کجا کمک XModels را بگیرم؟", "پشتیبانی XModels از طریق چت FAQ در سایت و ایمیل info@xmodels.com."),
        ("بیت‌ریت XModels چقدر باشد؟", "XModels ارقام رسمی مستند نمی‌کند — از ۳۵۰۰–۶۰۰۰ در ۱۰۸۰p استفاده کنید."),
        ("آیا SplitCam برای XModels رایگان است؟", "بله — رایگان، بدون واترمارک و بدون محدودیت زمانی.")]),
    _p("flirt4free", "Flirt4Free",
       "پخش در Flirt for Free cam با SplitCam — راهنمای رایگان",
       "پخش در Flirt for Free cam با SplitCam رایگان — External Broadcast Form، RTMP URL و Stream Name، صحنه‌ها و پوشش‌ها.",
       "flirt for free cam, flirt 4 free cam, flirt4free, پخش flirt4free, flirt4free external broadcast, flirt4free rtmp",
       'نحوه پخش در <span class="accent">Flirt4Free</span> با SplitCam',
       "پخش Flirt4Free",
       "تنظیم External Broadcast Form برای Flirt4Free.",
       "Flirt4Free یکی از قدیمی‌ترین پلتفرم‌های کم است که از دهه ۱۹۹۰ فعال است. از طریق <strong style='color:var(--text)'>External Broadcast Form</strong> پخش خارجی را رسماً پشتیبانی می‌کند.",
       "پخش در Flirt4Free با SplitCam: SplitCam را نصب کنید، صحنه بسازید، External Broadcast Form Flirt4Free را باز کنید، RTMP URL و Stream Name را کپی کنید و رزولوشن/بیت‌ریت را تنظیم کنید، در SplitCam جای‌گذاری کنید، Go Live."
       "<ol><li>SplitCam را نصب کنید.</li><li>دوربین + صحنه اضافه کنید.</li><li>External Broadcast Form Flirt4Free را باز کنید.</li><li>RTMP URL + Stream Name را در SplitCam جای‌گذاری کنید.</li><li>Go Live را فشار دهید.</li></ol>",
       "در ناحیه مدل Flirt4Free <strong>External Broadcast Form</strong> را باز کنید. Flirt4Free برخلاف اکثر سایت‌های کم، <strong>RTMP URL</strong> و <strong>Stream Name</strong> (نه «کلید») می‌دهد.",
       [("Stream Name است نه کلید", "Flirt4Free اطلاعات خود را Stream Name می‌نامد. آن را در فیلد کلید جریان SplitCam جای‌گذاری کنید — عملکرد یکسان است."),
        ("رزولوشن/بیت‌ریت را در فرم تنظیم کنید", "External Broadcast Form Flirt4Free فیلدهای رزولوشن و بیت‌ریت خود دارد."),
        ("پلتفرم با تاریخچه", "Flirt4Free از دهه ۱۹۹۰ فعال است."),
        _T_ETH],
       [("آیا Flirt4Free رمزگذار خارجی را پشتیبانی می‌کند؟", "بله — رسماً، از طریق External Broadcast Form که RTMP URL و Stream Name می‌دهد."),
        ("داده‌های RTMP Flirt4Free را از کجا بگیرم؟", "از External Broadcast Form در ناحیه مدل."),
        ("بیت‌ریت Flirt4Free چقدر باشد؟", "۳۵۰۰–۶۰۰۰ در ۱۰۸۰p — مقادیر یکسان را هم در External Broadcast Form و هم در SplitCam تنظیم کنید."),
        ("آیا SplitCam برای Flirt4Free رایگان است؟", "بله — رایگان، بدون واترمارک و بدون محدودیت زمانی.")]),
    _p("mfc-alerts", "MFC Alerts",
       "افزودن MFC Alerts به پخش با SplitCam",
       "هشدارهای انعام متحرک را در پخش MyFreeCams نمایش دهید — URL mfcalerts.com به عنوان لایه Browser در SplitCam رایگان، روی وب‌کم.",
       "mfc alerts, myfreecams alerts, افزودن mfc alerts, mfcalerts splitcam, myfreecams tip alerts, myfreecams alerts overlay",
       'نحوه افزودن <span class="accent">MFC Alerts</span> به پخش',
       "افزودن MFC Alerts",
       "هشدارهای انعام متحرک را در پخش MyFreeCams نمایش دهید.",
       "MFC Alerts هر بار که بیننده‌ای انعام ارسال می‌کند افکت‌های متحرک در پخش MyFreeCams شما نمایش می‌دهد. به عنوان یک <strong style='color:var(--text)'>لایه Browser</strong> درون <strong style='color:var(--text)'>SplitCam</strong> رایگان اجرا می‌شود.",
       "افزودن MFC Alerts با SplitCam: SplitCam را نصب کنید، وب‌کم اضافه کنید، تب Browser را باز کرده و mfcalerts.com را بارگذاری کنید، URL هشدار را کپی کنید، به عنوان لایه Browser روی وب‌کم اضافه کنید، سپس با انعام آزمایشی تست کنید."
       "<ol><li>SplitCam را نصب کنید.</li><li>وب‌کم اضافه کنید.</li><li>URL را از mfcalerts.com دریافت کنید.</li><li>به عنوان لایه Browser روی وب‌کم اضافه کنید.</li><li>انعام آزمایشی ارسال کنید.</li></ol>",
       "در SplitCam تب <strong>Browser</strong> را باز کنید و به <strong>www.mfcalerts.com</strong> بروید. وارد شوید یا ثبت‌نام کنید. از <strong>Copy to clipboard</strong> برای کپی کردن URL هشدار خصوصی‌تان استفاده کنید.",
       [("MFC Alerts باید روی وب‌کم باشد", "رایج‌ترین اشتباه: اگر لایه MFC Alerts زیر وب‌کم در لیست منابع باشد، افکت پنهان می‌ماند. آن را به بالا منتقل کنید."),
        ("حساب mfcalerts.com لازم است", "URL هشدار خصوصی است — اگر حساب ندارید ابتدا در mfcalerts.com ثبت‌نام کنید."),
        ("قبل از پخش زنده انعام آزمایشی ارسال کنید", "از Settings → Send test tip استفاده کنید تا مطمئن شوید پوشش کار می‌کند."),
        _T_ETH],
       [("MFC Alerts چیست؟", "سیستم اطلاع‌رسانی برای MyFreeCams که هنگام ارسال انعام توسط بینندگان افکت‌های ویدیویی در پخش شما نمایش می‌دهد."),
        ("چرا MFC Alerts من نمایش داده نمی‌شود؟", "تقریباً همیشه مشکل ترتیب لایه‌هاست — لایه Browser MFC Alerts باید در لیست منابع SplitCam بالاتر از وب‌کم باشد."),
        ("آیا برای MFC Alerts به حساب نیاز دارم؟", "بله — در mfcalerts.com ثبت‌نام کنید تا URL هشدار خصوصی‌تان را دریافت کنید."),
        ("آیا SplitCam برای این رایگان است؟", "بله — SplitCam رایگان است، بدون واترمارک و بدون محدودیت زمانی.")],
       steps=[
           ("SplitCam را نصب کنید و وب‌کم اضافه کنید", "SplitCam رایگان را برای Windows یا macOS نصب کنید، سپس <strong>وب‌کم</strong> را به عنوان منبع اضافه کنید."),
           ("تب Browser را باز کرده و به mfcalerts.com بروید", "در SplitCam تب <strong>Browser</strong> را باز کنید و به <strong>www.mfcalerts.com</strong> بروید. وارد شوید یا ثبت‌نام کنید."),
           ("URL هشدار را کپی کنید", "در mfcalerts.com از <strong>Copy to clipboard</strong> برای کپی URL هشدار خصوصی‌تان استفاده کنید."),
           ("URL را به عنوان لایه Browser اضافه کنید — روی وب‌کم", "URL را در پنجره Browser SplitCam جای‌گذاری کنید و <strong>Add</strong> را کلیک کنید. سپس لیست منابع را طوری مرتب کنید که <strong>MFC Alerts بالاتر از وب‌کم</strong> باشد."),
           ("با انعام آزمایشی تست کنید", "<strong>Settings → Send test tip</strong> را باز کنید و مطمئن شوید افکت هشدار بالای دوربین ظاهر می‌شود."),
       ]),
    _p("lovense", "Lovense",
       "افزودن اسباب‌بازی‌های Lovense به پخش با SplitCam",
       "اسباب‌بازی‌های تعاملی Lovense را با SplitCam رایگان به پخش کم متصل کنید — Lovense SplitCam Toolset، هشدارهای انعام روی صفحه، واکنش‌ها.",
       "افزودن lovense به پخش, lovense cam stream, lovense splitcam, lovense splitcam toolset, lovense interactive toy streaming",
       'نحوه افزودن <span class="accent">اسباب‌بازی‌های Lovense</span> به پخش',
       "افزودن اسباب‌بازی‌های Lovense",
       "اسباب‌بازی‌های تعاملی Lovense را به پخش کم خود متصل کنید.",
       "پخش کم را از طریق <strong style='color:var(--text)'>SplitCam</strong> رایگان اجرا می‌کنید و اسباب‌بازی <strong style='color:var(--text)'>Lovense</strong> که به توکن‌ها واکنش نشان می‌دهد را جفت می‌کنید. Lovense یک <strong style='color:var(--text)'>Lovense SplitCam Toolset</strong> رسمی مستند کرده است.",
       "برای افزودن اسباب‌بازی‌های Lovense به پخش: SplitCam و نرم‌افزار Lovense را نصب کنید، اسباب‌بازی را جفت کنید، Lovense را به پلتفرم کم متصل کنید، وضعیت Lovense را به عنوان لایه Browser در SplitCam اضافه کنید، سپس مثل معمول پخش کنید."
       "<ol><li>SplitCam را نصب کنید.</li><li>نرم‌افزار Lovense را نصب کنید و اسباب‌بازی را جفت کنید.</li><li>Lovense را به سایت کم خود متصل کنید.</li><li>پوشش Lovense را در SplitCam اضافه کنید.</li><li>Go Live را فشار دهید.</li></ol>",
       "Lovense Connect / Lovense Stream (اپلیکیشن دسکتاپ رسمی) را نصب کنید. اسباب‌بازی را روشن کرده و از طریق Bluetooth جفت کنید تا اپلیکیشن اتصال را نشان دهد.",
       [("از Lovense SplitCam Toolset رسمی استفاده کنید", "Lovense یک toolset اختصاصی برای SplitCam با راهنمای نصب خود منتشر می‌کند."),
        ("Lovense Cam Extension را به‌روزرسانی کنید", "Toolset به Lovense Cam Extension جدید (۳۰.۱.۴ یا بالاتر) نیاز دارد — قبل از پخش زنده به‌روزرسانی کنید."),
        ("اسباب‌بازی را شارژ نگه دارید", "باتری ضعیف در وسط نمایش بخش تعاملی را خراب می‌کند — قبل از پخش زنده کاملاً شارژ کنید."),
        ("واکنش توکن را آزمایش کنید", "قبل از باز کردن اتاق، یک انعام آزمایشی کوچک ارسال کنید تا مطمئن شوید اسباب‌بازی واکنش نشان می‌دهد."),
        ("الزامات نسخه را بررسی کنید", "Lovense SplitCam Toolset به SplitCam ۱۰.۴.۵ یا بالاتر نیاز دارد.")],
       [("آیا Lovense از SplitCam رسماً پشتیبانی می‌کند؟", "بله — Lovense یک «Lovense SplitCam Toolset» رسمی با راهنمای نصب خود مستند کرده است."),
        ("آیا اسباب‌بازی مستقیماً به SplitCam متصل می‌شود؟", "خیر — اسباب‌بازی با اپلیکیشن Lovense جفت می‌شود؛ SplitCam پوشش Lovense را نمایش می‌دهد و دوربین را پخش می‌کند."),
        ("کدام سایت‌های کم از Lovense پشتیبانی می‌کنند؟", "Lovense Cam Extension رسماً از Chaturbate، Stripchat، BongaCams، MyFreeCams و CamSoda پشتیبانی می‌کند."),
        ("می‌توانم آخرین انعام‌ها را روی صفحه نمایش دهم؟", "بله — URL widget Lovense را به عنوان لایه Browser در SplitCam اضافه کنید.")],
       steps=[
           ("SplitCam را نصب کنید", "SplitCam نرم‌افزار پخش زنده رایگان برای Windows و macOS است."),
           ("نرم‌افزار Lovense را نصب کنید و اسباب‌بازی را جفت کنید", "Lovense Connect / Lovense Stream را نصب کنید. اسباب‌بازی را روشن کرده و از طریق Bluetooth جفت کنید."),
           ("Lovense را به پلتفرم کم متصل کنید", "در اپلیکیشن Lovense، حساب کم خود را متصل کنید تا اسباب‌بازی به توکن‌ها / انعام‌های بینندگان واکنش نشان دهد."),
           ("پوشش Lovense را در SplitCam اضافه کنید", "Lovense یک URL پوشش / widget ارائه می‌دهد. آن را به عنوان لایه <strong>Browser</strong> در صحنه SplitCam اضافه کنید."),
           ("صحنه را بسازید و Go Live", "دوربین و پوشش‌های دیگر اضافه کنید، کلید RTMP پلتفرم کم را در SplitCam جای‌گذاری کنید و <strong>Go Live</strong> را کلیک کنید."),
       ]),
    _p("multistream-cams", "چندین سایت کم",
       "پخش به چندین سایت کم به صورت همزمان با SplitCam",
       "به MyFreeCams، Chaturbate، BongaCams، CAM4، Stripchat و بیشتر به صورت همزمان با multistream رایگان SplitCam پخش کنید. یک کلیک، بدون واترمارک.",
       "پخش به چندین سایت کم, multistream cam sites, پخش chaturbate و bongacams همزمان, نرم‌افزار multistream کم",
       'نحوه پخش به <span class="accent">چندین سایت کم</span> به صورت همزمان',
       "Multistream کم",
       "به چندین سایت کم به صورت همزمان پخش کنید.",
       "<strong style='color:var(--text)'>SplitCam</strong> رایگان می‌تواند یک رمزگذاری را به <strong style='color:var(--text)'>چندین سایت کم به صورت همزمان</strong> پخش کند — MyFreeCams، Chaturbate، BongaCams، CAM4، Stripchat و بیشتر. بدون واترمارک، یک کلیک.",
       "برای پخش به چندین سایت کم همزمان: SplitCam را نصب کنید، صحنه بسازید، URL سرور RTMP و کلید جریان هر سایت کم را دریافت کنید، همه را به تنظیمات multistream SplitCam اضافه کنید، یک‌بار Go Live را کلیک کنید."
       "<ol><li>SplitCam را نصب کنید.</li><li>دوربین + صحنه اضافه کنید.</li><li>کلیدهای RTMP از هر سایت کم دریافت کنید.</li><li>همه کلیدها را به multistream SplitCam اضافه کنید.</li><li>یک‌بار Go Live را فشار دهید.</li></ol>",
       "در هر پلتفرم کم پخش خارجی / RTMP را فعال کنید و <strong>URL سرور</strong> و <strong>کلید جریان</strong> را کپی کنید. در SplitCam <strong>Stream Settings</strong> را باز کنید و هر سایت کم را به عنوان یک مقصد RTMP سفارشی اضافه کنید.",
       [("به آپلود خود توجه کنید", "Multistream بار آپلود را چند برابر می‌کند. هر مقصد بیت‌ریت خود را استفاده می‌کند — مطمئن شوید خط شما مجموع را تحمل می‌کند."),
        ("قوانین پلتفرم را بررسی کنید", "برخی سایت‌های کم پخش همزمان در جای دیگر را ممنوع می‌کنند — قبل از multistream بررسی کنید."),
        ("کابل — اینجا نباید قطع شود", "Multistream بار آپلود را چند برابر می‌کند، بنابراین یک قطعی Wi-Fi می‌تواند همه مقاصد را به صورت همزمان از کار بیندازد."),
        ("نظارت بر وضعیت", "SplitCam وضعیت هر مقصد را نمایش می‌دهد — اگر آپلود کافی نیست یک سایت را جدا کنید.")],
       [("آیا multistream SplitCam رایگان است؟", "بله — multistream داخلی و رایگان است، بدون هزینه برای هر مقصد، بدون واترمارک."),
        ("می‌توانم به چند سایت کم همزمان پخش کنم؟", "به هر تعداد که پهنای باند آپلود شما تحمل کند."),
        ("آیا از cloud relay استفاده می‌کند؟", "خیر — SplitCam جریان را به صورت peer-to-peer مستقیماً از رایانه به ingest هر پلتفرم ارسال می‌کند."),
        ("آیا multistream رایانه من را کند می‌کند؟", "رمزگذاری یک‌بار انجام می‌شود و دوباره استفاده می‌شود؛ رمزگذاری سخت‌افزاری بار CPU را پایین نگه می‌دارد.")],
       steps=[
           ("SplitCam را نصب کنید", "SplitCam نرم‌افزار پخش زنده رایگان برای Windows و macOS با multistream داخلی است."),
           ("دوربین و صحنه را تنظیم کنید", "SplitCam را باز کنید، وب‌کم اضافه کنید و صحنه با پوشش‌ها و فیلترها بسازید."),
           ("کلیدهای RTMP از هر سایت کم دریافت کنید", "در هر پلتفرم کم پخش خارجی / RTMP را فعال کنید و <strong>URL سرور</strong> و <strong>کلید جریان</strong> را کپی کنید."),
           ("هر مقصد را در SplitCam اضافه کنید", "<strong>Stream Settings</strong> را باز کنید و هر سایت کم را به عنوان مقصد RTMP سفارشی اضافه کنید."),
           ("یک‌بار Go Live را کلیک کنید", "<strong>Go Live</strong> را فشار دهید. SplitCam جریان را به هر سایت کم انتخاب شده به صورت همزمان ارسال می‌کند."),
       ]),
    _p("livejasmin", "LiveJasmin",
       "پخش در LiveJasmin با SplitCam — رمزگذار خارجی HD",
       "پخش در LiveJasmin با SplitCam رایگان — رمزگذار خارجی Model Center، تنظیم HD 1080p، صحنه‌های چندکاره و پوشش‌ها. بدون واترمارک، بدون ثبت‌نام.",
       "پخش livejasmin, livejasmin obs, livejasmin external encoder, livejasmin rtmp, livejasmin stream key, livejasmin model setup",
       'نحوه پخش در <span class="accent">LiveJasmin</span> با SplitCam',
       "پخش LiveJasmin",
       "تنظیم رمزگذار خارجی برای Model Center فقط-HD لایوجاسمین.",
       "LiveJasmin پرچم‌دار شرکت Docler Holding است — یکی از بزرگ‌ترین شبکه‌های کم در جهان و یک پلتفرم کاملاً HD. ابزار پخش پیشنهادی آن کلاینت اختصاصی <strong>JasminCAM</strong> است، اما Model Center مسیر استاندارد <strong>External Encoder</strong> را نیز در اختیار می‌گذارد که <strong style='color:var(--text)'>SplitCam</strong> رایگان به آن متصل می‌شود — به شما اجازه می‌دهد روی همان پخش HD از صحنه‌های چندکاره، فیلترهای زیبایی و پوشش‌ها بهره ببرید.",
       "پخش در LiveJasmin با SplitCam: SplitCam را نصب کنید، صحنه HD بسازید، در Model Center به <em>Settings → Broadcast → External Encoder</em> بروید، URL سرور و stream key را کپی کنید، در SplitCam جای‌گذاری کنید، Go Live."
       "<ol><li>SplitCam را نصب کنید.</li><li>دوربین + صحنه HD اضافه کنید.</li><li>URL و stream key را از Model Center بگیرید.</li><li>در SplitCam جای‌گذاری کنید.</li><li>Go Live را فشار دهید.</li></ol>",
       "وارد <strong>modelcenter.livejasmin.com</strong> شوید، <strong>Settings → Broadcast → External Encoder</strong> را باز کنید. Model Center یک <strong>URL سرور</strong> و یک <strong>stream key</strong> منحصر به حساب شما را نمایش می‌دهد — هر دو را در فیلدهای RTMP سفارشی SplitCam جای‌گذاری کنید. <strong>توجه:</strong> حساب‌های جدید باید تأیید شوند (۴۸ تا ۷۲ ساعت) تا گزینه رمزگذار خارجی نمایان شود، و پلتفرم خروجی فقط-HD را اعمال می‌کند.",
       [("HD یا رتبه‌ات پایین می‌آید", "LiveJasmin فقط HD است — هر چیزی زیر 1280×720 ریسک این را دارد که فقط در فهرست‌های با درآمد پایین نمایش داده شود، و هر چیزی زیر 1080p واجد شرایط «Premium» نخواهد بود. ۱۹۲۰×۱۰۸۰ در ۳۰ fps با ۴۰۰۰ تا ۶۰۰۰ کیلوبیت بر ثانیه را هدف بگیرید."),
        ("JasminCAM در برابر رمزگذار خارجی", "کلاینت JasminCAM متعلق به Docler تمیزترین تطابق با HD را دارد، اما رمزگذارهای خارجی (OBS، SplitCam، vMix) پس از تأیید حساب رسماً پشتیبانی می‌شوند — و صحنه‌های چندکاره و پوشش‌هایی را باز می‌کنند که JasminCAM توان آن را ندارد."),
        ("Free chat ≠ شوی خصوصی", "Free chat فقط پیش‌نمایش است — بدون برهنگی. شوهای خصوصی و Gold show جایی است که مدل درآمد دارد. صحنه‌ات را طوری طراحی کن که هم با لباس و هم در حالت شو قوی به نظر برسد."),
        _T_ETH],
       [("آیا LiveJasmin رسماً از رمزگذارهای خارجی مانند SplitCam پشتیبانی می‌کند؟", "بله — Model Center شامل گزینه External Encoder در Settings → Broadcast است. JasminCAM کلاینت پیشنهادی است، اما OBS، SplitCam و سایر رمزگذارهای RTMP پس از تأیید حساب مدل به صراحت به عنوان پشتیبانی‌شده ذکر شده‌اند."),
        ("stream key لایوجاسمین را از کجا می‌گیرم؟", "از داخل Model Center: Settings → Broadcast → External Encoder. هم URL سرور و هم stream key منحصر به فرد در آنجا ظاهر می‌شوند — هر دو را در فیلدهای RTMP سفارشی SplitCam جای‌گذاری کنید. کلید مخصوص حساب شماست؛ مثل رمز عبور با آن رفتار کنید."),
        ("برای LiveJasmin چه بیت‌ریتی استفاده کنم؟", "LiveJasmin فقط HD است — ۱۹۲۰×۱۰۸۰ در ۳۰ fps، ۴۰۰۰ تا ۶۰۰۰ کیلوبیت بر ثانیه با فاصله keyframe دو ثانیه‌ای را هدف بگیرید. هر چیزی پایین‌تر از این به طور محسوس برچسب Premium را از دست می‌دهد و رتبه‌اش پایین می‌آید."),
        ("آیا استفاده از SplitCam با LiveJasmin رایگان است؟", "بله — SplitCam رایگان است، بدون واترمارک و بدون محدودیت زمانی. تنها هزینه برآورده کردن الزامات HD لایوجاسمین است که SplitCam با ترکیب صحنه ۱۰۸۰p و فیلترهای زیبایی به صورت بومی از پس آن برمی‌آید.")],
       steps=[
           ("SplitCam را دانلود و نصب کنید", "SplitCam نرم‌افزار پخش زنده رایگان برای Windows و macOS است — بدون ثبت‌نام، بدون کارت، بدون واترمارک. این رمزگذاری است که ویدیوی HD شما را به LiveJasmin می‌فرستد."),
           ("صحنه HD خود را بسازید", "SplitCam را باز کنید و وب‌کم خود را در حالت 1080p اضافه کنید. پوشش‌ها، متن، یک دوربین دوم یا گوشی، فیلترهای زیبایی یا پس‌زمینه AI اضافه کنید — LiveJasmin کیفیت HD می‌خواهد و صحنه ترکیبی شما باید هم در Free chat و هم در شوهای خصوصی پرمیوم به نظر برسد."),
           ("URL و stream key لایوجاسمین را دریافت کنید", "وارد <strong>modelcenter.livejasmin.com</strong> شوید (حساب شما ابتدا باید تأیید شود — معمولاً ۴۸ تا ۷۲ ساعت پس از ثبت‌نام). <strong>Settings → Broadcast → External Encoder</strong> را باز کنید. این صفحه یک <strong>URL سرور</strong> و یک <strong>stream key</strong> منحصر به فرد نشان می‌دهد. هر دو را کپی کنید."),
           ("SplitCam را به LiveJasmin متصل کنید", "در SplitCam <strong>Stream Settings</strong> را باز کنید، URL سرور و stream key لایوجاسمین را در فیلدهای RTMP سفارشی جای‌گذاری کنید. بیت‌ریت را روی ۴۰۰۰ تا ۶۰۰۰ کیلوبیت بر ثانیه در ۱۹۲۰×۱۰۸۰، ۳۰ fps، با keyframe دو ثانیه‌ای تنظیم کنید. ابتدا تست سرعت داخلی را اجرا کنید — جریان‌های HD سنگین هستند."),
           ("Go Live را کلیک کنید", "<strong>Go Live</strong> را در SplitCam فشار دهید، سپس در Model Center لایوجاسمین آنلاین شوید. در حدود ۱۰ ثانیه فید HD شما به شبکه LiveJasmin می‌رسد. پخش‌های بعدی فقط با یک کلیک انجام می‌شود — SplitCam را باز کنید، Go Live بزنید، سپس در LiveJasmin آنلاین شوید."),
       ]),
    _p("myfreecams", "MyFreeCams",
       "نحوه پخش در MyFreeCams (MFC) با SplitCam — دور زدن Model Web Broadcaster",
       "پخش در MyFreeCams با SplitCam رایگان — External Broadcaster در Model Admin، اقتصاد توکنی MFC، صحنه‌های چندکاره و پوشش‌ها. بدون واترمارک، بدون ثبت‌نام.",
       "پخش myfreecams, mfc external broadcaster, myfreecams obs, mfc rtmp, mfc stream key, model admin, mfc token",
       'نحوه پخش در <span class="accent">MyFreeCams</span> با SplitCam',
       "پخش MyFreeCams",
       "تنظیم پخش‌کننده خارجی برای Model Admin توکنی MFC.",
       "‏MyFreeCams (MFC) یکی از قدیمی‌ترین پلتفرم‌های کم است — اقتصاد توکنی خالص، بدون مسیرهای پیچیده تأیید مدل، و یک پایگاه وفادار از اعضای <strong>Premium</strong>. پخش‌کننده پیش‌فرض Model Web Broadcaster ابزاری مرورگری با یک دوربین است، اما <strong>Model Admin</strong> گزینه <strong>External Broadcaster</strong> را نیز در اختیار می‌گذارد که <strong style='color:var(--text)'>SplitCam</strong> رایگان به آن متصل می‌شود — و صحنه‌های چندکاره، پوشش‌ها و فیلترهای زیبایی را باز می‌کند.",
       "پخش در MyFreeCams با SplitCam: SplitCam را نصب کنید، صحنه بسازید، در Model Admin از <em>Web Broadcaster</em> به <em>External Broadcaster</em> تغییر دهید، URL سرور و stream key را کپی کنید، در SplitCam جای‌گذاری کنید، Go Live بزنید."
       "<ol><li>SplitCam را نصب کنید.</li><li>دوربین + صحنه اضافه کنید.</li><li>در Model Admin به External Broadcaster تغییر دهید.</li><li>URL و stream key را در SplitCam جای‌گذاری کنید.</li><li>Go Live را بزنید.</li></ol>",
       "وارد MyFreeCams شوید، <strong>Model Admin → Broadcaster</strong> را باز کنید و از <strong>Web Broadcaster</strong> به <strong>External Broadcaster</strong> تغییر دهید. این صفحه URL سرور (<code>rtmp://publish.myfreecams.com…</code>) و stream key را نشان می‌دهد. هر دو را در فیلدهای RTMP سفارشی SplitCam جای‌گذاری کنید. کلید به حساب شما گره خورده است — مانند رمز عبور با آن رفتار کنید.",
       [("اقتصاد انعام و توکن خالص", "‏MFC یک پلتفرم خالص tipping/tokens است — اعضای Premium می‌توانند شوی خصوصی بگیرند، اما نان روزانه شما انعام در Free chat است. صحنه‌ای طراحی کنید که در طول کل شیفت تعامل مستمر را ترغیب کند."),
        ("‏Web در برابر External Broadcaster", "پخش‌کننده پیش‌فرض فقط یک منبع تصویر دارد — External Broadcaster چندین صحنه، پوشش، فیلترهای زیبایی و پس‌زمینه‌های AI را باز می‌کند. این همان چیزی است که پخش آماتور را از ظاهر pro جدا می‌کند."),
        ("هشدارهای MFC Alerts به عنوان لایه Browser", "‏<strong>mfcalerts.com</strong> را به عنوان یک لایه Browser روی دوربین در SplitCam اضافه کنید — هشدارهای انعام و دنبال‌کنندگان جدید مستقیماً روی صفحه ظاهر می‌شوند و این انگیزه قوی‌ای به مخاطب برای ارسال توکن بیشتر می‌دهد."),
        _T_ETH],
       [("آیا MyFreeCams از پخش‌کننده‌های خارجی پشتیبانی می‌کند؟", "بله — Model Admin گزینه External Broadcaster را با پشتیبانی استاندارد RTMP دارد. OBS، SplitCam و vMix همگی پس از تغییر از Web Broadcaster با MFC کار می‌کنند."),
        ("stream key ام‌اف‌سی را از کجا می‌گیرم؟", "در Model Admin → Broadcaster → External Broadcaster. صفحه URL سرور (publish.myfreecams.com) و stream key مرتبط با حساب شما را نمایش می‌دهد."),
        ("برای MyFreeCams چه بیت‌ریتی؟", "‏MFC تا حدود ۶۰۰۰ کیلوبیت بر ثانیه با فاصله keyframe دو ثانیه‌ای را می‌پذیرد. ۱۹۲۰×۱۰۸۰ در ۳۰ fps با ۳۵۰۰ تا ۶۰۰۰ کیلوبیت بر ثانیه را هدف بگیرید. ابتدا تست سرعت داخلی SplitCam را اجرا کنید."),
        ("آیا استفاده از SplitCam با MFC رایگان است؟", "بله — SplitCam کاملاً رایگان است، بدون واترمارک و بدون محدودیت زمانی. رمزگذار سهمی از توکن‌های شما برنمی‌دارد.")],
       steps=[
           ("SplitCam را نصب کنید", "‏SplitCam نرم‌افزار پخش زنده رایگان برای Windows و macOS است — بدون ثبت‌نام، بدون کارت، بدون واترمارک. این رمزگذاری است که ویدیوی شما را با RTMP به MyFreeCams می‌فرستد."),
           ("صحنه‌تان را بسازید", "‏SplitCam را باز کنید و وب‌کم، پوشش‌ها، متن، یک دوربین دوم یا گوشی، فیلترهای زیبایی یا پس‌زمینه AI را اضافه کنید. <strong>mfcalerts.com</strong> را به عنوان لایه Browser روی دوربین اضافه کنید تا هشدارهای انعام و دنبال‌کننده مستقیماً روی صفحه نمایش داده شوند."),
           ("‏MFC را به External Broadcaster تغییر دهید", "وارد MyFreeCams شوید، <strong>Model Admin → Broadcaster</strong> را باز کنید و از <strong>Web Broadcaster</strong> به <strong>External Broadcaster</strong> تغییر دهید. URL سرور (<code>rtmp://publish.myfreecams.com…</code>) و stream key را کپی کنید."),
           ("‏SplitCam را به MFC متصل کنید", "در SplitCam <strong>Stream Settings</strong> را باز کنید، URL و stream key را در فیلدهای RTMP سفارشی جای‌گذاری کنید. بیت‌ریت را روی ۳۵۰۰ تا ۶۰۰۰ کیلوبیت بر ثانیه در ۱۹۲۰×۱۰۸۰، ۳۰ fps با keyframe دو ثانیه‌ای تنظیم کنید."),
           ("‏Go Live را کلیک کنید", "<strong>Go Live</strong> را در SplitCam فشار دهید. اتاق شما در عرض چند ثانیه روی MyFreeCams ظاهر می‌شود. پخش‌های بعدی فقط با یک کلیک انجام می‌شوند — SplitCam را باز کنید، Go Live بزنید و بگذارید MFC Alerts برای شما کار کند."),
       ]),
    _p("cherry-tv", "Cherry.tv",
       "نحوه پخش در Cherry.tv با SplitCam — رمزگذار خارجی دوستدار Web3",
       "پخش در Cherry.tv با SplitCam رایگان — External Encoder در Streamer Dashboard، پلتفرم کم دوستدار کریپتو، صحنه‌های چندکاره. بدون واترمارک، بدون ثبت‌نام.",
       "پخش cherry tv, cherry.tv obs, cherry tv external encoder, cherry.tv rtmp, cherry.tv stream key, cherry tv streamer, web3 cam",
       'نحوه پخش در <span class="accent">Cherry.tv</span> با SplitCam',
       "پخش Cherry.tv",
       "تنظیم رمزگذار خارجی برای Streamer Dashboard چری‌تی‌وی.",
       "‏Cherry.tv یک پلتفرم کم جدید و در حال رشد سریع با نگاه <strong>Web3</strong> است — پرداخت‌های دوستدار کریپتو و سد ورود کم‌تر نسبت به شبکه‌های قدیمی مانند LiveJasmin. <strong>Streamer Dashboard</strong> یک مسیر استاندارد رمزگذار خارجی را نمایش می‌دهد که <strong style='color:var(--text)'>SplitCam</strong> رایگان به آن متصل می‌شود — و صحنه‌های چندکاره، پوشش‌ها و فیلترهای زیبایی را روی پخش شما باز می‌کند.",
       "پخش در Cherry.tv با SplitCam: SplitCam را نصب کنید، صحنه بسازید، در <em>Streamer Dashboard → Broadcast Settings → External Encoder</em>، URL و stream key را کپی کنید، در SplitCam جای‌گذاری کنید، Go Live بزنید."
       "<ol><li>SplitCam را نصب کنید.</li><li>دوربین + صحنه اضافه کنید.</li><li>Streamer Dashboard → Broadcast Settings → External Encoder را باز کنید.</li><li>URL و stream key را در SplitCam جای‌گذاری کنید.</li><li>Go Live را بزنید.</li></ol>",
       "وارد حساب Streamer در Cherry.tv شوید، <strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong> را باز کنید. URL سرور و stream key به حساب شما گره خورده‌اند. حساب‌های جدید نیاز به احراز هویت پایه دارند (Cherry.tv onboarding سبک‌تری از بازیگران بزرگ‌تر دارد).",
       [("سد ورود سبک‌تر و ترافیک در حال رشد", "‏onboarding چری‌تی‌وی سریع‌تر و ساده‌تر از LiveJasmin یا Streamate است — پایگاه مخاطبان هنوز در حال رشد است و این فرصت خوبی برای ورود زودهنگام و ساختن مخاطب پیش از شلوغ شدن پلتفرم است."),
        ("پرداخت‌های کریپتو در دسترس", "در کنار پرداخت فیات سنتی، Cherry.tv از پرداخت‌های کریپتو پشتیبانی می‌کند — برای مدل‌های مناطقی با محدودیت در پردازنده‌های سنتی یا کسانی که تسویه سریع را ترجیح می‌دهند مفید است."),
        ("پخش‌کننده خارجی همه چیز را باز می‌کند", "پخش‌کننده مرورگر برای شروع کافی است، اما SplitCam با رمزگذار خارجی صحنه‌های چندکاره، پوشش‌ها، فیلترهای زیبایی و پس‌زمینه‌های AI را باز می‌کند — دقیقاً همان چیزی که مخاطب جوان‌تر و آگاه‌تر به پلتفرم چری‌تی‌وی انتظار دارد."),
        _T_ETH],
       [("آیا Cherry.tv از رمزگذارهای خارجی پشتیبانی می‌کند؟", "بله — Streamer Dashboard گزینه External Encoder را با پشتیبانی استاندارد RTMP دارد. OBS، SplitCam و vMix همگی پس از اتصال حساب از طریق Broadcast Settings کار می‌کنند."),
        ("stream key چری‌تی‌وی را از کجا می‌گیرم؟", "در <strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong>. URL سرور و stream key به حساب گره خورده‌اند و در همان صفحه نمایش داده می‌شوند. با کلید مانند رمز عبور رفتار کنید."),
        ("برای Cherry.tv چه بیت‌ریتی؟", "‏۳۵۰۰ تا ۶۰۰۰ کیلوبیت بر ثانیه در ۱۹۲۰×۱۰۸۰ و ۳۰ fps با فاصله keyframe دو ثانیه‌ای را هدف بگیرید. ابتدا تست سرعت داخلی SplitCam را برای تأیید آپلود اجرا کنید."),
        ("آیا استفاده از SplitCam با Cherry.tv رایگان است؟", "بله — SplitCam کاملاً رایگان است، بدون واترمارک و بدون محدودیت زمانی. ترکیب کامل صحنه با پوشش‌ها و فیلترها بدون هیچ هزینه نرم‌افزاری.")],
       steps=[
           ("‏SplitCam را نصب کنید", "‏SplitCam نرم‌افزار پخش زنده رایگان برای Windows و macOS است — بدون ثبت‌نام، بدون کارت، بدون واترمارک."),
           ("صحنه‌تان را بسازید", "‏SplitCam را باز کنید و وب‌کم را با پوشش‌ها، متن، فیلترهای زیبایی یا پس‌زمینه AI اضافه کنید. مخاطبان Cherry.tv جوان‌تر و آگاه به پلتفرم‌ها هستند — یک صحنه امروزی با گرافیک تمیز و نورپردازی خوب شما را از بقیه جدا می‌کند."),
           ("‏URL و stream key را از Cherry.tv بگیرید", "در حساب Cherry.tv خود <strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong> را باز کنید. URL سرور و stream key را کپی کنید."),
           ("‏SplitCam را به Cherry.tv متصل کنید", "در SplitCam <strong>Stream Settings</strong> را باز کنید، URL سرور و stream key را در فیلدهای RTMP سفارشی جای‌گذاری کنید. ۳۵۰۰ تا ۶۰۰۰ کیلوبیت بر ثانیه را در ۱۹۲۰×۱۰۸۰، ۳۰ fps، با keyframe دو ثانیه‌ای تنظیم کنید."),
           ("‏Go Live را کلیک کنید", "<strong>Go Live</strong> را در SplitCam فشار دهید، سپس از <strong>Streamer Dashboard</strong> در Cherry.tv آنلاین شوید. اتاق شما در عرض چند ثانیه آنلاین می‌شود. پخش‌های بعدی فقط با یک کلیک انجام می‌شوند — SplitCam را باز کنید، Go Live بزنید، در Cherry.tv آنلاین شوید."),
       ]),
]
