# -*- coding: utf-8 -*-
"""Thai (th) content for cam-streaming-guides."""

_T_ETH = ("ใช้การเชื่อมต่อแบบมีสาย", "อีเทอร์เน็ตชนะ Wi-Fi ในการสตรีมที่ยาว — เฟรมที่หายคือทิปที่หาย ลากสายไปยังพีซีสตรีม")
_T_TEST = ("ทำการทดสอบส่วนตัวก่อน", "รันการถ่ายทอดทดสอบสั้นๆ เพื่อตรวจสอบกล้อง เสียง การจัดเฟรม และโอเวอร์เลย์ก่อนเปิดห้องให้ผู้ชม")

def _p(slug, name, title, desc, kw, h1html, h1short, card, intro, quick, key_how, tips, faq, steps=None):
    d = {"slug": slug, "name": name, "title": title, "desc": desc, "kw": kw,
         "h1html": h1html, "h1short": h1short, "card": card, "intro": intro,
         "quick": quick, "key_how": key_how, "tips": tips, "faq": faq}
    if steps: d["steps"] = steps
    return d

PLATFORMS_TH = [
    _p("chaturbate", "Chaturbate",
       "ถ่ายทอดบน Chaturbate ด้วย SplitCam — Token & RTMP",
       "ถ่ายทอดบน Chaturbate ด้วย SplitCam ฟรี — broadcast token, RTMP, ฉากหลายกล้องและโอเวอร์เลย์ ไม่มีลายน้ำ",
       "chaturbate ถ่ายทอด, chaturbate broadcast token, chaturbate rtmp obs, chaturbate external encoder, chaturbate live",
       'วิธีถ่ายทอดบน <span class="accent">Chaturbate</span> ด้วย SplitCam',
       "ถ่ายทอด Chaturbate",
       "การตั้งค่าตาม token ด้วย encoder ภายนอกบน Chaturbate",
       "Chaturbate เป็นหนึ่งในแพลตฟอร์ม cam ที่ใหญ่ที่สุด สร้างขึ้นบนเศรษฐกิจ token เครื่องมือถ่ายทอดผ่านเบราว์เซอร์เป็นเครื่องมือกล้องเดียวแบบเรียบๆ — การเปลี่ยนไปใช้ <strong style='color:var(--text)'>encoder ภายนอก</strong> ด้วย <strong style='color:var(--text)'>SplitCam</strong> ฟรี เปิดฉากหลายกล้อง โอเวอร์เลย์ และฟิลเตอร์บนสตรีมที่ใช้ token เดียวกัน",
       "ถ่ายทอดบน Chaturbate ด้วย SplitCam: ติดตั้ง SplitCam สร้างฉาก บน Chaturbate เปิด <em>Broadcast Yourself → My Broadcast</em> คัดลอก broadcast token วางใน SplitCam Go Live"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มกล้อง + ฉาก</li><li>คัดลอก broadcast token จาก Chaturbate</li><li>วางใน SplitCam</li><li>กด Go Live</li></ol>",
       "บน Chaturbate คลิก <strong>Broadcast Yourself</strong> สำหรับหน้า <strong>My Broadcast</strong> จากนั้น <strong>View RTMP/OBS broadcast information and stream key</strong> คีย์ปรากฏเป็น <strong>broadcast token</strong> — คัดลอก ปฏิบัติกับมันเหมือนรหัสผ่าน ไม่เปิดเผยต่อสาธารณะ",
       [("Token คือคีย์", "Chaturbate ใช้ broadcast token แทนคีย์สตรีมทั่วไป ปฏิบัติเหมือนรหัสผ่านและรีเซ็ตเมื่อรั่วไหล"),
        ("พื้นที่เหลือเฟือ", "RTMP ingest ของ Chaturbate รับได้สูงสุด 4K, 60 fps และบิตเรตสูง — ขีดจำกัดคืออัปโหลด ไม่ใช่แพลตฟอร์ม Keyframe ทุก 2 วินาที"),
        _T_ETH, _T_TEST],
       [("Chaturbate อนุญาต OBS / encoder ภายนอกหรือไม่?", "ใช่ — Chaturbate รองรับ encoder ภายนอกอย่างเป็นทางการพร้อมบทความ «How do I set up OBS?» เปิดใช้งานผ่าน «Use External Encoder to Broadcast» ในการตั้งค่าการถ่ายทอด"),
        ("คีย์สตรีม Chaturbate อยู่ที่ไหน?", "Broadcast Yourself → My Broadcast → View RTMP/OBS broadcast information and stream key คีย์คือ broadcast token"),
        ("บิตเรตสำหรับ Chaturbate?", "3,500–6,000 Kbps ที่ 1080p เพียงพอ เพดานของ Chaturbate สูง — ขีดจำกัดจริงคืออัปโหลด รันการทดสอบความเร็วในตัวของ SplitCam ก่อน"),
        ("SplitCam ฟรีสำหรับ Chaturbate หรือไม่?", "ใช่ — ฟรีทั้งหมด ไม่มีลายน้ำและไม่จำกัดเวลา: encoder ไม่กินรายได้ token ของคุณ")]),
    _p("cam4", "CAM4",
       "ถ่ายทอดบน CAM4 ด้วย SplitCam — External Encoder",
       "ถ่ายทอดบน CAM4 ด้วย SplitCam ฟรี — External Encoder, stream key, การบล็อกตามภูมิภาคและโอเวอร์เลย์ ไม่มีลายน้ำ",
       "cam4 ถ่ายทอด, cam4.com, cam4 external encoder, cam4 stream key, cam4 rtmp obs",
       'วิธีถ่ายทอดบน <span class="accent">CAM4</span> ด้วย SplitCam',
       "ถ่ายทอด CAM4",
       "External Encoder บน CAM4 พร้อมตัวควบคุมตามภูมิภาค",
       "CAM4 เป็นแพลตฟอร์ม cam-and-earn ระดับโลกพร้อมตัวควบคุมภูมิภาคในตัว — คุณสามารถซ่อนการถ่ายทอดในประเทศที่เลือก การถ่ายทอดผ่าน <strong style='color:var(--text)'>SplitCam</strong> ฟรีเป็น encoder ภายนอกเปิดการสลับฉากและโอเวอร์เลย์ที่เครื่องมือถ่ายทอดพื้นฐานไม่มี",
       "ถ่ายทอดบน CAM4 ด้วย SplitCam: ติดตั้ง SplitCam สร้างฉาก บน CAM4 ไปที่ <em>Broadcast &amp; Earn Money → Start Broadcast → External Encoder</em> Get Stream Key วางใน SplitCam Go Live"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มกล้อง + ฉาก</li><li>รับคีย์สตรีมจาก CAM4</li><li>วางใน SplitCam</li><li>กด Go Live</li></ol>",
       "บน CAM4 คลิก <strong>Broadcast</strong> → <strong>Broadcast &amp; Earn Money</strong> → <strong>Start Broadcast</strong> จากนั้น <strong>External Encoder</strong> ด้านบน กรอกวันเกิด เพศ และประเทศ ใช้ <strong>Get Stream Key</strong> และคัดลอก แถบเลื่อนสีเขียวใน Stream Settings ของ SplitCam ยืนยันการเชื่อมต่อ",
       [("ตั้งค่าข้อจำกัดทางภูมิภาค", "CAM4 อนุญาตให้ซ่อนการถ่ายทอดในประเทศและภูมิภาคที่เฉพาะเจาะจง — ตั้งค่าบน CAM4 ก่อน go-live"),
        ("ดูแถบเลื่อนสีเขียว", "การตั้งค่า CAM4 แสดงแถบเลื่อนสีเขียวใน Stream Settings ของ SplitCam เมื่อคีย์ได้รับการยอมรับ — แดง = ตรวจคีย์"),
        ("บิตเรตต่ำกว่าปกติ", "CAM4 ingest จำกัดบิตเรตวิดีโอที่ประมาณ 3,000 Kbps — ต่ำกว่าไซต์ cam ส่วนใหญ่ อย่าดันสูงกว่า"),
        _T_ETH],
       [("CAM4 รองรับ OBS / encoder ภายนอกอย่างเป็นทางการหรือไม่?", "ใช่ — CAM4 มี OBS Guide อย่างเป็นทางการบนไซต์สนับสนุนและแนะนำ External Encoder เพื่อประสบการณ์ที่ดีที่สุด SplitCam ใช้เส้นทาง RTMP เดียวกัน"),
        ("ฉันสามารถบล็อกสตรีม CAM4 ตามภูมิภาคได้หรือไม่?", "ใช่ — CAM4 มีการจำกัดตามภูมิภาคในตัวเพื่อซ่อนการถ่ายทอดในบางประเทศ ตั้งค่าใน CAM4 ไม่ใช่ใน SplitCam"),
        ("คีย์สตรีม CAM4 อยู่ที่ไหน?", "Broadcast → Broadcast & Earn Money → Start Broadcast → External Encoder → Get Stream Key"),
        ("บิตเรตสำหรับ CAM4?", "ต่ำกว่าค่าเฉลี่ย — CAM4 ingest จำกัดที่ ~3,000 Kbps ที่ 30 fps พร้อม keyframe 1 วินาที ตารางทางการแนะนำไม่เกิน ~3,000")]),
    _p("bongacams", "BongaCams",
       "ถ่ายทอดบน BongaCams ด้วย SplitCam — External Encoder",
       "ถ่ายทอดบน BongaCams ด้วย SplitCam ฟรี — External Encoder, ฉากหลายกล้อง, โอเวอร์เลย์ และพื้นหลัง AI ไม่มีลายน้ำ",
       "bongacams, bongcams, bongacams ถ่ายทอด, bongacams external encoder, bongacams rtmp obs",
       'วิธีถ่ายทอดบน <span class="accent">BongaCams</span> ด้วย SplitCam',
       "ถ่ายทอด BongaCams",
       "การตั้งค่า External Encoder สำหรับ BongaCams",
       "BongaCams เป็นแพลตฟอร์ม cam ระดับโลก การถ่ายทอดผ่าน encoder ภายนอกไม่ได้เปิดใช้งานเสมอ — เมื่อเปิดใช้งานแล้ว <strong style='color:var(--text)'>SplitCam</strong> ฟรีขับเคลื่อนการถ่ายทอดด้วยฉากหลายกล้อง โอเวอร์เลย์ และพื้นหลัง AI",
       "ถ่ายทอดบน BongaCams ด้วย SplitCam: ติดตั้ง SplitCam สร้างฉาก บน BongaCams ไปที่ <em>Options → Broadcast settings → Select Encoder → External Encoder</em> คัดลอก URL และคีย์ วางใน SplitCam Go Live"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มกล้อง + ฉาก</li><li>รับ URL และคีย์จาก BongaCams</li><li>วางใน SplitCam</li><li>กด Go Live</li></ol>",
       "บน BongaCams เปิด <strong>Options</strong> → <strong>Broadcast settings</strong> → <strong>Select Encoder</strong> → <strong>External Encoder</strong> และคัดลอก URL เซิร์ฟเวอร์และคีย์สตรีมที่แสดง <strong>หากปุ่ม External Encoder หายไป</strong> ติดต่อฝ่ายสนับสนุน BongaCams และขอเปิดใช้งานการเข้ารหัสภายนอกในบัญชีของคุณ",
       [("ไม่มีปุ่ม External Encoder? ฝ่ายสนับสนุน", "BongaCams เปิดใช้งานการเข้ารหัสภายนอกเป็นบัญชี — หากตัวเลือกหายไปจาก Broadcast settings ฝ่ายสนับสนุนจะเปิดใช้งาน"),
        ("ปรับความละเอียดให้ตรงกัน", "BongaCams แนะนำให้ความละเอียดของเว็บแคมและการถ่ายทอดตรงกัน — เช่น ทั้งคู่ 1280×720"),
        _T_ETH, _T_TEST],
       [("ทำไมปุ่ม External Encoder ไม่ปรากฏใน BongaCams?", "การเข้ารหัสภายนอกไม่ได้เปิดใช้งานโดยค่าเริ่มต้นในทุกบัญชี — ติดต่อฝ่ายสนับสนุน BongaCams เพื่อเปิดใช้งาน และปุ่มจะปรากฏใน Broadcast settings"),
        ("ฉันต้องยืนยันบัญชี BongaCams หรือไม่?", "ใช่ — การถ่ายทอดต้องมีอายุ 18+ ID ทางการสำหรับการยืนยันอายุ และการอนุมัติบัญชีก่อนไลฟ์"),
        ("บิตเรตสำหรับ BongaCams?", "BongaCams RTMP ingest จำกัดบิตเรตวิดีโอที่ประมาณ 6,000 Kbps พร้อม keyframe 2 วินาที — 3,500–6,000 ที่ 1080p เป็นโซนอุดมคติ ทดสอบอัปโหลดก่อน"),
        ("SplitCam ฟรีสำหรับ BongaCams หรือไม่?", "ใช่ — ฟรีทั้งหมด ไม่มีลายน้ำและไม่จำกัดเวลา ดังนั้น encoder ไม่ลดรายได้ token ของคุณบน BongaCams")]),
    _p("stripchat", "Stripchat",
       "ถ่ายทอดบน Stripchat ด้วย SplitCam — Strip Cam Setup",
       "ถ่ายทอดบน Stripchat — แพลตฟอร์ม strip cam — ด้วย SplitCam ฟรี ซอฟต์แวร์ภายนอก คีย์ token ฉากและโอเวอร์เลย์",
       "strip cam, stripchat live stream, stripchat ถ่ายทอด, stripchat external software, stripchat stream key, stripchat rtmp obs",
       'วิธีถ่ายทอดบน <span class="accent">Stripchat</span> ด้วย SplitCam',
       "ถ่ายทอด Stripchat",
       "การตั้งค่าซอฟต์แวร์ภายนอกสำหรับ Stripchat",
       "Stripchat เป็นแพลตฟอร์ม cam ขนาดใหญ่ที่เน้นการโต้ตอบ โหมด <em>external software</em> ให้คีย์ตาม token — ใส่เข้าใน <strong style='color:var(--text)'>SplitCam</strong> ฟรี เพื่อถ่ายทอดด้วยฉาก โอเวอร์เลย์ และฟิลเตอร์แทนกล้องเรียบๆ",
       "ถ่ายทอดบน Stripchat ด้วย SplitCam: ติดตั้ง SplitCam สร้างฉาก บน Stripchat เลือก <em>Switch to external software</em> คัดลอกคีย์สตรีม วางใน SplitCam Go Live"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มกล้อง + ฉาก</li><li>รับคีย์สตรีมจาก Stripchat</li><li>วางใน SplitCam</li><li>กด Go Live</li></ol>",
       "บน Stripchat เลือก <strong>Switch to external software</strong> จากนั้น <strong>Show external software settings for the stream</strong> คัดลอกคีย์สตรีม — Stripchat แสดงเป็น token เก็บเป็นส่วนตัว",
       [("ปรับความละเอียดให้ตรงกับไซต์", "FAQ ของ Stripchat เตือน: ความละเอียดในซอฟต์แวร์ของคุณต้องตรงกับไซต์อย่างแม่นยำ มิฉะนั้นวิดีโอจะแตก ตั้งทั้งคู่เหมือนกัน"),
        ("ระวังขั้นต่ำ 2 Mbps", "Stripchat ระบุอัปโหลด 2 Mbps เป็นขั้นต่ำ — และบอกตรงๆ ว่าไม่เพียงพอสำหรับ OBS streaming หรือมัลติสตรีม เล็งให้สูงกว่ามาก"),
        ("คีย์คือ token", "คีย์สตรีมของ Stripchat คือ token — คัดลอกแม่นยำ อย่าแชร์ รีเซ็ตเมื่อรั่วไหล"),
        _T_ETH],
       [("Stripchat แนะนำ OBS / ซอฟต์แวร์ภายนอกหรือไม่?", "ใช่ — FAQ ทางการของ Stripchat แนะนำซอฟต์แวร์ถ่ายทอดภายนอกเช่น OBS «เพื่อให้ได้คุณภาพวิดีโอและเสียงที่ดีที่สุด» SplitCam ทำงานเหมือนกัน"),
        ("ฉันจะเปลี่ยน Stripchat ไปใช้ซอฟต์แวร์ภายนอกได้อย่างไร?", "ใน Broadcast Center เลือก Switch to External Broadcast Software (OBS) จากนั้นเปิด external software settings เพื่อเปิดเผยคีย์สตรีม (token)"),
        ("บิตเรตสำหรับ Stripchat?", "RTMP ingest รับได้สูงสุด ~6,000 Kbps พร้อม keyframe 2 วินาที 3,500–6,000 ที่ 1080p อุดมคติ — แต่ต้องสูงกว่าขั้นต่ำ 2 Mbps อย่างมาก โดยเฉพาะ OBS streaming"),
        ("SplitCam ฟรีสำหรับ Stripchat หรือไม่?", "ใช่ — ไม่มีค่าธรรมเนียมใบอนุญาต ไม่มีลายน้ำ ไม่จำกัดเวลา: แม้แต่โชว์ Stripchat แบบโต้ตอบที่ยาวก็ไม่เสียค่าใช้จ่ายฝั่ง encoder")]),
    _p("onlyfans", "OnlyFans",
       "ไลฟ์บน OnlyFans ด้วย SplitCam — อนุญาตหรือคีย์",
       "ไลฟ์บน OnlyFans ด้วย SplitCam ฟรี — เข้าสู่ระบบผ่านการอนุญาตหรือ OBS Key ฉากหลายกล้องและโอเวอร์เลย์ ไม่มีลายน้ำ",
       "onlyfans ไลฟ์, onlyfans live stream, onlyfans อนุญาต splitcam, onlyfans obs key, onlyfans streaming software",
       'วิธีไลฟ์บน <span class="accent">OnlyFans</span> ด้วย SplitCam',
       "Live OnlyFans",
       "อนุญาตครั้งเดียวหรือวางคีย์ — ไลฟ์บน OnlyFans",
       "OnlyFans live สำหรับผู้สมัครรับข้อมูลของคุณ SplitCam เชื่อมต่อใน <strong style='color:var(--text)'>สองวิธี</strong> — เข้าสู่ระบบครั้งเดียวด้วยบัญชี OnlyFans และ SplitCam ดึงคีย์สตรีมโดยอัตโนมัติและรักษาให้ซิงค์ หรือวาง OBS Key ด้วยตนเอง ทั้งสองกรณีคุณถ่ายทอดด้วยฉากหลายกล้อง โอเวอร์เลย์ และฟิลเตอร์",
       "ไลฟ์บน OnlyFans ด้วย SplitCam: ติดตั้ง SplitCam สร้างฉาก เปิด Stream Settings &rarr; Add Channel &rarr; OnlyFans และเลือก <em>การอนุญาต</em> — เข้าสู่ระบบด้วยบัญชี OnlyFans SplitCam ดึงคีย์อัตโนมัติ — และกด Go Live ด้วยบัญชีที่เชื่อมต่อ คุณสามารถเปลี่ยนพารามิเตอร์สตรีม OnlyFans ใน SplitCam โดยไม่ต้องเปิดไซต์ OnlyFans",
       "บน OnlyFans: <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; ส่วน <strong>Other</strong> คัดลอก <strong>OBS Key</strong> หรือใช้ตัวเลือก <strong>การอนุญาต</strong> ใน SplitCam สำหรับการเข้าสู่ระบบบัญชี — คีย์จะถูกดึงและซิงค์โดยอัตโนมัติ",
       [("การอนุญาต vs Stream Key", "สองวิธีในการเชื่อมต่อ: <strong>การอนุญาต</strong> (เข้าสู่ระบบครั้งเดียว คีย์ถูกดึงและซิงค์ — เส้นทางที่ง่ายที่สุด) หรือ <strong>Stream Key</strong> (คัดลอก OBS Key บน OnlyFans → Profile → Settings → Other และวาง)"),
        ("เปลี่ยนการตั้งค่าโดยไม่ออกจาก SplitCam", "ด้วยการอนุญาต บัญชียังคงเชื่อมต่ออยู่ ดังนั้นปรับพารามิเตอร์ OnlyFans live จาก SplitCam ระหว่างหรือหลังการถ่ายทอด — โดยไม่ต้องผ่านไซต์ OnlyFans"),
        ("บิตเรตปานกลาง", "OnlyFans RTMP ingest จำกัดบิตเรตวิดีโอที่ประมาณ 2,500 Kbps — เข้มงวดกว่าไซต์ cam ส่วนใหญ่ เล็ง 720p–1080p ที่ ~2,000–2,500"),
        _T_ETH],
       [("ฉันจะเชื่อม OnlyFans กับ SplitCam อย่างไร?", "สองวิธี <strong>การอนุญาต</strong> — Stream Settings → Add Channel → OnlyFans → เข้าสู่ระบบด้วยบัญชี OnlyFans และ SplitCam ดึงคีย์อัตโนมัติ หรือ <strong>Stream Key</strong> — คัดลอก OBS Key บน OnlyFans → Profile → Settings → Other และวาง"),
        ("ฉันสามารถเปลี่ยนการตั้งค่า OnlyFans live โดยไม่เปิดไซต์ได้หรือไม่?", "ใช่ — ด้วยวิธีการอนุญาต SplitCam ยังคงเชื่อมต่อกับบัญชี OnlyFans ดังนั้นคีย์และการตั้งค่าจะซิงค์อัตโนมัติ"),
        ("บิตเรตสำหรับ OnlyFans?", "ปานกลาง — OnlyFans RTMP ingest จำกัดบิตเรตที่ประมาณ 2,500 Kbps เข้มงวดกว่าแพลตฟอร์ม cam อื่นๆ มาก เล็ง 720p–1080p ที่ประมาณ 2,000–2,500 Kbps"),
        ("SplitCam ฟรีสำหรับ OnlyFans live หรือไม่?", "ใช่ — ฟรี ไม่มีลายน้ำและไม่จำกัดเวลา ไม่มีค่าใช้จ่ายฝั่ง encoder")],
       steps=[
           ("ดาวน์โหลดและติดตั้ง SplitCam", "SplitCam เป็นซอฟต์แวร์สตรีมมิ่งสดฟรีสำหรับ Windows และ macOS — ไม่ต้องสมัคร ไม่ต้องใช้บัตร ไม่มีลายน้ำ เป็น encoder ที่ส่งวิดีโอของคุณไปยัง OnlyFans"),
           ("ตั้งค่ากล้องและฉาก", "เปิด SplitCam และเพิ่มเว็บแคม สร้างฉากตามที่คุณต้องการให้ผู้ชมเห็น — โอเวอร์เลย์ ข้อความ กล้องที่สอง ฟิลเตอร์ความงามหรือพื้นหลัง AI ทุกอย่างใช้แบบสด"),
           ("การเชื่อมต่อ — วิธีที่ 1: การอนุญาต (แนะนำ)", "ใน SplitCam เปิด <strong>Stream Settings</strong> &rarr; <strong>Add Channel</strong> &rarr; <strong>OnlyFans</strong> และเลือก <strong>การอนุญาต</strong> เข้าสู่ระบบด้วยอีเมลและรหัสผ่าน OnlyFans SplitCam เชื่อมบัญชีของคุณ ดึงคีย์สตรีมอัตโนมัติและรักษาให้ซิงค์ — และให้คุณจัดการพารามิเตอร์ OnlyFans live ภายใน SplitCam เปลี่ยนระหว่างหรือหลังการถ่ายทอดโดยไม่ต้องเปิดไซต์ OnlyFans"),
           ("การเชื่อมต่อ — วิธีที่ 2: Stream Key (ด้วยตนเอง)", "ไม่อยากเข้าสู่ระบบ? ใช้คีย์ บน OnlyFans ไปที่ <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; ส่วน <strong>Other</strong> และคัดลอก <strong>OBS Key</strong> ใน SplitCam, Add Channel &rarr; OnlyFans วางในช่องคีย์ คีย์นี้คงที่ — หากต้องการเปลี่ยนการตั้งค่าในภายหลังกลับไปยังไซต์ OnlyFans"),
           ("Go Live", "ไม่ว่าวิธีใด กด <strong>Go Live</strong> ใน SplitCam ด้วยวิธีที่ 1 คุณสามารถปรับพารามิเตอร์ OnlyFans จาก SplitCam แบบเรียลไทม์ต่อไปได้ ด้วยวิธีที่ 2 คีย์ยังคงเหมือนที่ตั้งไว้"),
       ]),
    _p("camplace", "CamPlace",
       "ถ่ายทอดบน CamPlace ด้วย SplitCam — คู่มือฟรี",
       "ถ่ายทอดบน CamPlace ด้วย SplitCam ฟรี — encoder ภายนอก คีย์ RTMP ฉากและโอเวอร์เลย์ ทีละขั้นตอน ไม่มีลายน้ำ",
       "camplace ถ่ายทอด, camplace broadcasting software, camplace rtmp, camplace external encoder, camplace stream key",
       'วิธีถ่ายทอดบน <span class="accent">CamPlace</span> ด้วย SplitCam',
       "ถ่ายทอด CamPlace",
       "การตั้งค่า encoder ภายนอกสำหรับ CamPlace",
       "CamPlace เป็นแพลตฟอร์ม cam-streaming ไม่มีบทความ OBS สาธารณะ ดังนั้น <strong style='color:var(--text)'>คู่มือวิดีโอด้านบน</strong> คือข้อมูลอ้างอิงของคุณ — <strong style='color:var(--text)'>SplitCam</strong> ฟรีเชื่อมต่อผ่าน RTMP มาตรฐานและเพิ่มฉาก โอเวอร์เลย์ และพื้นหลัง AI ที่กล้องพื้นฐานไม่มี",
       "ถ่ายทอดบน CamPlace ด้วย SplitCam: ติดตั้ง SplitCam สร้างฉาก เปิดใช้งานการถ่ายทอดภายนอก/RTMP บน CamPlace คัดลอก URL เซิร์ฟเวอร์และคีย์สตรีม วางใน SplitCam Go Live ทำตามวิดีโอสำหรับเส้นทางปัจจุบัน"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มกล้อง + ฉาก</li><li>รับคีย์ RTMP จาก CamPlace</li><li>วางใน SplitCam</li><li>กด Go Live</li></ol>",
       "เข้าสู่ระบบ CamPlace และเปิดการตั้งค่าการถ่ายทอด เปลี่ยนเป็นตัวเลือก encoder ภายนอก / RTMP / OBS เพื่อเปิดเผย <strong>URL เซิร์ฟเวอร์</strong> และ <strong>คีย์สตรีม</strong> คัดลอกทั้งคู่ CamPlace ไม่ได้เผยแพร่เอกสาร OBS ทางการ — <strong>วิดีโอด้านบน</strong> คือเส้นทางทีละขั้นตอนที่เชื่อถือได้ที่สุดผ่านอินเทอร์เฟซปัจจุบัน",
       [("ไม่มีคู่มือ OBS ทางการ — ใช้วิดีโอ", "CamPlace ไม่มีบทความสาธารณะเกี่ยวกับ encoder ภายนอก วิดีโอด้านบนคือข้อมูลอ้างอิงสำหรับเส้นทางปัจจุบัน"),
        ("RTMP มาตรฐานใช้งานได้", "แม้ไม่มีเอกสาร CamPlace ยอมรับ URL เซิร์ฟเวอร์ RTMP มาตรฐานและคีย์ — SplitCam เชื่อมต่อเป็นปลายทาง RTMP กำหนดเอง"),
        _T_ETH, _T_TEST],
       [("CamPlace มีคู่มือ OBS ทางการหรือไม่?", "ไม่พบบทความสาธารณะเกี่ยวกับ encoder ภายนอก CamPlace ยอมรับ RTMP URL มาตรฐานและคีย์ ดังนั้น SplitCam ใช้งานได้ — ทำตามวิดีโอ"),
        ("CamPlace รองรับ encoder ภายนอกหรือไม่?", "ใช่ — รับคีย์สตรีม RTMP มาตรฐาน ดังนั้น SplitCam เชื่อมต่อเป็นปลายทาง RTMP กำหนดเอง"),
        ("บิตเรตสำหรับ CamPlace?", "CamPlace ไม่ได้เผยแพร่ตัวเลขทางการ — ใช้ 3,500–6,000 Kbps ที่ 1080p เป็นช่วงปลอดภัย และให้การทดสอบความเร็วของ SplitCam กำหนดเพดานจริงของคุณ"),
        ("SplitCam ฟรีสำหรับ CamPlace หรือไม่?", "ใช่ — ฟรี ไม่มีลายน้ำและไม่จำกัดเวลา เนื่องจาก CamPlace ไม่ได้มาพร้อม encoder ของตัวเอง เครื่องมือ RTMP ฟรีทำงานได้")]),
    _p("camsoda", "CamSoda",
       "CamSoda live ด้วย SplitCam — การตั้งค่าฟรี",
       "CamSoda live ด้วย SplitCam ฟรี — Use OBS Broadcaster เซิร์ฟเวอร์ภูมิภาค ฉากและโอเวอร์เลย์ ไม่มีลายน้ำ",
       "camsoda live, camsoda ถ่ายทอด, camsoda obs broadcaster, camsoda rtmp obs, camsoda live broadcast",
       'วิธีถ่ายทอดบน <span class="accent">CamSoda</span> ด้วย SplitCam',
       "ถ่ายทอด CamSoda",
       "การตั้งค่า Use OBS Broadcaster บน CamSoda",
       "CamSoda เป็นแพลตฟอร์ม cam ของสหรัฐที่มีชื่อเสียงในด้านรูปแบบโชว์แบบโต้ตอบและไม่ธรรมดา รองรับการสตรีม OBS อย่างเป็นทางการ — มีปุ่ม <strong style='color:var(--text)'>Use OBS Broadcaster</strong> บนหน้า Go Live และคู่มือ OBS ทางการบน CamSoda wiki <strong style='color:var(--text)'>SplitCam</strong> ฟรีทำงานเหมือนกัน",
       "ถ่ายทอดบน CamSoda ด้วย SplitCam: ติดตั้ง SplitCam สร้างฉาก คลิก Use OBS Broadcaster บนหน้า Go Live ของ CamSoda คัดลอก URL เซิร์ฟเวอร์และคีย์สตรีม วางใน SplitCam Go Live"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มกล้อง + ฉาก</li><li>คลิก Use OBS Broadcaster บน CamSoda</li><li>วาง URL เซิร์ฟเวอร์ + คีย์ใน SplitCam</li><li>กด Go Live</li></ol>",
       "บนหน้า <strong>Go Live</strong> ของ CamSoda คลิก <strong>Use OBS Broadcaster</strong> CamSoda แสดง URL เซิร์ฟเวอร์ RTMP และคีย์สตรีม — คัดลอกทั้งคู่ เลือกเซิร์ฟเวอร์ภูมิภาค (อเมริกาเหนือ ยุโรป เอเชีย ฯลฯ) ที่ใกล้ที่สุด CamSoda wiki มีคู่มือ OBS เต็มรูปแบบสำหรับรายละเอียด",
       [("ยืนยันเพื่อรับทิป", "บน CamSoda ทุกคนสามารถถ่ายทอดได้ แต่หากต้องการรับทิป คุณต้องดำเนินการยืนยันของ CamSoda ให้เสร็จสิ้น"),
        ("เลือกเซิร์ฟเวอร์ภูมิภาคที่ใกล้ที่สุด", "CamSoda เสนอเซิร์ฟเวอร์ ingest ภูมิภาค — ที่ใกล้ที่สุด (NA / ยุโรป / เอเชีย / อเมริกาใต้ / โอเชียเนีย) ลดความล่าช้าและเฟรมที่หาย"),
        ("เพดานที่ 1080p / 30 fps", "CamSoda ingest ไปถึงประมาณ 1080p, 30 fps และ ~6,000 Kbps — อย่าดันสูงกว่า"),
        _T_ETH],
       [("CamSoda รองรับ OBS / encoder ภายนอกหรือไม่?", "ใช่ — อย่างเป็นทางการ มีปุ่ม Use OBS Broadcaster บนหน้า Go Live และคู่มือ OBS บน CamSoda wiki ดังนั้น SplitCam ใช้งานได้"),
        ("ฉันต้องยืนยันตัวเองบน CamSoda หรือไม่?", "สำหรับการถ่ายทอด ไม่ สำหรับการรับทิป ใช่ — CamSoda ต้องการให้ดำเนินการยืนยันก่อน"),
        ("CamSoda รองรับความละเอียดอะไร?", "สูงสุด 1920×1080 ที่ 30 fps ประมาณ 6,000 Kbps สูงสุดบน RTMP ingest"),
        ("SplitCam ฟรีสำหรับ CamSoda หรือไม่?", "ใช่ — ฟรี ไม่มีลายน้ำและไม่จำกัดเวลา ทำงานร่วมกับโหมด Use OBS Broadcaster ฟรีของ CamSoda ดังนั้นทั้งห่วงโซ่ไม่เสียค่าใช้จ่าย")]),
    _p("streamate", "Streamate",
       "ถ่ายทอดบน Streamate ด้วย SplitCam — ช่องที่รวมเข้ากัน",
       "ถ่ายทอดบน Streamate ด้วย SplitCam ฟรี — ช่องที่รวมเข้ากัน คีย์ SM Connect ฉากและโอเวอร์เลย์ ไม่มีลายน้ำ",
       "streamate, streamate sm connect, streamate ถ่ายทอด, streamate broadcasting software, streamate rtmp",
       'วิธีถ่ายทอดบน <span class="accent">Streamate</span> ด้วย SplitCam',
       "ถ่ายทอด Streamate",
       "Streamate เป็นช่องที่รวมเข้ากันใน SplitCam — ตั้งค่าเร็ว",
       "Streamate เป็นแพลตฟอร์ม cam ที่ก่อตั้งขึ้น — และเป็นหนึ่งใน <strong style='color:var(--text)'>ปลายทางที่กำหนดค่าไว้ล่วงหน้าใน SplitCam</strong> ในรายการช่อง ดังนั้นการตั้งค่าเร็วกว่าการป้อน RTMP ด้วยตนเอง: คุณเลือก Streamate วางคีย์ เสร็จ",
       "ถ่ายทอดบน Streamate ด้วย SplitCam: ติดตั้ง SplitCam สร้างฉาก บน Streamate ใช้ <em>SM Connect → Start Show</em> และคัดลอกคีย์ จากนั้นใน SplitCam เปิด <em>Stream Settings → Add Channel → Streamate</em> และวาง"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มกล้อง + ฉาก</li><li>รับคีย์ Streamate ผ่าน SM Connect</li><li>Add Channel → Streamate ใน SplitCam</li><li>กด Go Live</li></ol>",
       "บน Streamate เปิด <strong>SM Connect</strong> ยอมรับข้อกำหนด คลิก <strong>Start Show</strong> ทางซ้ายและปิดหน้าต่างที่เปิด — จากนั้นคัดลอกคีย์สตรีมมิ่ง ใน SplitCam เปิด <strong>Stream Settings</strong> → <strong>Add Channel</strong> เลือก <strong>Streamate</strong> จากรายการและวางคีย์ แถบเลื่อนสีเขียวยืนยันการเชื่อมต่อ",
       [("Streamate รวมเข้ากัน", "ไม่มี URL RTMP ด้วยตนเอง — SplitCam มี Streamate ในรายการ Add Channel เพียงแค่เลือกและวางคีย์"),
        ("ปิดหน้าต่างป๊อปอัพ SM Connect", "หลังจาก Start Show Streamate เปิดหน้าต่าง — ปิด มันมีไว้เพื่อเปิดเผยคีย์สตรีมมิ่งเท่านั้น"),
        ("ล็อกความละเอียดเป็น 1080p", "ฟิลด์ Video Resolution ใน SM Connect อาจกระโดดไป 1440 อย่างเงียบๆ ซึ่งไม่ได้ส่งจริงและลดคุณภาพของคุณอย่างเงียบๆ — ตั้งค่าเป็น 1080p ด้วยตนเอง บิตเรตที่ลดลงในภาพนิ่งเป็นปกติ: สตรีม Streamate ปรับเปลี่ยนได้"),
        _T_ETH, _T_TEST],
       [("Streamate รวมเข้ากับ SplitCam หรือไม่?", "ใช่ — Streamate ปรากฏในรายการ Add Channel ของ SplitCam คุณเลือกแทนการพิมพ์ URL RTMP ด้วยตนเอง"),
        ("คีย์สตรีมมิ่ง Streamate อยู่ที่ไหน?", "SM Connect → ยอมรับข้อกำหนด → Start Show → ปิดป๊อปอัพ → คัดลอกคีย์"),
        ("บิตเรตสำหรับ Streamate?", "Streamate ไม่ได้ตั้งเพดานแข็ง — 3,500–6,000 Kbps ที่ 1080p ทำงานได้ดี สตรีมปรับเปลี่ยนได้ ดังนั้นบิตเรตที่ต่ำกว่าในภาพนิ่งเป็นปกติ ไม่ใช่บั๊ก"),
        ("SplitCam ฟรีสำหรับ Streamate หรือไม่?", "ใช่ — ฟรี ไม่มีลายน้ำและไม่จำกัดเวลา และเนื่องจาก Streamate เป็นช่องที่รวมเข้ากันใน SplitCam ไม่มีค่าใช้จ่าย encoder แยกต่างหาก")]),
    _p("streamray", "StreamRay",
       "ถ่ายทอดบน StreamRay cam ด้วย SplitCam — Chat URL",
       "ถ่ายทอดบน StreamRay cam ด้วย SplitCam ฟรี — URL โพสต์ในแชท โหมด OBS Broadcaster ฉากและโอเวอร์เลย์ ไม่มีลายน้ำ",
       "streamray, streamray cam, streamray ถ่ายทอด, streamray obs broadcaster, streamray rtmp",
       'วิธีถ่ายทอดบน <span class="accent">StreamRay</span> ด้วย SplitCam',
       "ถ่ายทอด StreamRay",
       "การตั้งค่า encoder ภายนอก URL-in-chat สำหรับ StreamRay",
       "StreamRay มีการตั้งค่า encoder ภายนอกที่ไม่ธรรมดา — จัดส่ง URL สตรีมใน <strong style='color:var(--text)'>หน้าต่างแชทของการถ่ายทอด</strong> และไม่ใช้คีย์สตรีมแยกต่างหาก <strong style='color:var(--text)'>SplitCam</strong> ฟรีจัดการกระแสเฉพาะ URL นี้",
       "ถ่ายทอดบน StreamRay ด้วย SplitCam: ติดตั้ง SplitCam สร้างฉาก บน StreamRay เปิดใช้งาน OBS Broadcaster คัดลอก URL สตรีมจากหน้าต่างแชท วางใน SplitCam (ปล่อยช่องคีย์ว่าง) Go Live"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มกล้อง + ฉาก</li><li>คัดลอก StreamRay URL จากแชท</li><li>วาง URL ใน SplitCam</li><li>กด Go Live</li></ol>",
       "บน StreamRay ดับเบิลคลิก <strong>Broadcast Now</strong> เปิดเมนู <strong>Other</strong> เลือก <strong>OBS Broadcaster</strong> และ <strong>Save and Close</strong> StreamRay จะโพสต์ <strong>URL สตรีมในหน้าต่างแชท</strong> — คัดลอกจากที่นั่น ปล่อยช่องคีย์สตรีมของ SplitCam <strong>ว่าง</strong> StreamRay พิสูจน์ตัวตนผ่าน URL เท่านั้น",
       [("URL อยู่ในแชท", "StreamRay ไม่แสดง URL สตรีมในกล่องการตั้งค่า — โพสต์ในหน้าต่างแชทของการถ่ายทอด คัดลอกจากที่นั่น"),
        ("ปล่อยช่องคีย์ว่าง", "StreamRay ไม่ใช้คีย์แยกต่างหาก — เฉพาะ URL อย่าใส่อะไรในช่องคีย์ของ SplitCam"),
        _T_ETH, _T_TEST],
       [("URL สตรีม StreamRay อยู่ที่ไหน?", "หลังจากเปิดใช้งาน OBS Broadcaster StreamRay โพสต์ URL ในหน้าต่างแชท — คัดลอกจากแชท"),
        ("ทำไมไม่มีคีย์สตรีมบน StreamRay?", "StreamRay พิสูจน์ตัวตนผ่าน URL เท่านั้น — ปล่อยช่องคีย์ของ SplitCam ว่าง"),
        ("บิตเรตสำหรับ StreamRay?", "StreamRay ไม่ประกาศเพดานทางการ — เล็ง 3,500–6,000 Kbps ที่ 1080p และรันการทดสอบความเร็วของ SplitCam เนื่องจากกระแสเฉพาะ URL ไม่ให้ข้อเสนอแนะบิตเรต"),
        ("SplitCam ฟรีสำหรับ StreamRay หรือไม่?", "ใช่ — ฟรี ไม่มีลายน้ำและไม่จำกัดเวลา ซึ่งตรงกับกระแสเฉพาะ URL ของ StreamRay: วางลิงก์แล้วคุณก็ไลฟ์")]),
    _p("xlovecam", "XLoveCam",
       "ถ่ายทอดบน XLoveCam ด้วย SplitCam — RTMP link & คีย์",
       "ถ่ายทอดบน XLoveCam ด้วย SplitCam ฟรี — RTMP link และคีย์ เซิร์ฟเวอร์ภูมิภาค ฉากและโอเวอร์เลย์ ไม่มีลายน้ำ",
       "xlovecam, x love cam, xlovecam ถ่ายทอด, xlovecam rtmp link, xlovecam stream key",
       'วิธีถ่ายทอดบน <span class="accent">XLoveCam</span> ด้วย SplitCam',
       "ถ่ายทอด XLoveCam",
       "การตั้งค่า RTMP link + คีย์สำหรับ XLoveCam",
       "XLoveCam เป็นแพลตฟอร์ม cam ยุโรปหลายภาษา การตั้งค่าบัญชีแสดงทั้ง <strong style='color:var(--text)'>RTMP link</strong> และ <strong style='color:var(--text)'>คีย์สตรีม</strong> — <strong style='color:var(--text)'>SplitCam</strong> ฟรีรับทั้งสองและถ่ายทอดด้วยฉากและโอเวอร์เลย์เต็มรูปแบบ",
       "ถ่ายทอดบน XLoveCam ด้วย SplitCam: ติดตั้ง SplitCam สร้างฉาก บน XLoveCam เปิด <em>My Account → settings</em> คัดลอก RTMP link และคีย์สตรีม วางทั้งคู่ใน SplitCam เริ่มโชว์"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มกล้อง + ฉาก</li><li>คัดลอก RTMP link + คีย์จาก XLoveCam</li><li>วางทั้งคู่ใน SplitCam</li><li>กด Go Live</li></ol>",
       "บน XLoveCam เปิด <strong>My Account</strong> → <strong>settings</strong> การตั้งค่าแสดงทั้ง <strong>RTMP link</strong> และ <strong>คีย์สตรีม</strong> — คัดลอกทั้งคู่ในช่อง URL เซิร์ฟเวอร์และคีย์ของ SplitCam จากนั้น <strong>Start your show</strong> บน XLoveCam",
       [("คัดลอกลิงก์และคีย์", "XLoveCam ให้ RTMP link และคีย์สตรีมแยกต่างหาก — คุณต้องการทั้งคู่ใน SplitCam ไม่ใช่แค่อันเดียว"),
        ("ผู้ชมหลายภาษา", "XLoveCam เป็นยุโรปและหลายภาษา — โอเวอร์เลย์ข้อความที่ชัดเจนในภาษาของคุณช่วยให้ผู้ชมพบคุณ"),
        ("เลือกเซิร์ฟเวอร์ที่ใกล้ที่สุด", "XLoveCam เสนอเซิร์ฟเวอร์ RTMP ภูมิภาค — ยุโรป อเมริกาเหนือ อเมริกาใต้ และเอเชีย ที่ใกล้ที่สุดลดความล่าช้าและเฟรมที่หาย"),
        _T_ETH],
       [("ข้อมูล RTMP ของ XLoveCam อยู่ที่ไหน?", "My Account → settings — แสดงทั้ง RTMP link และคีย์"),
        ("XLoveCam รองรับ encoder ภายนอกหรือไม่?", "ใช่ — ให้ RTMP link และคีย์ ดังนั้น SplitCam ทำงานเป็น encoder"),
        ("บิตเรตสำหรับ XLoveCam?", "XLoveCam ไม่ได้เผยแพร่ขีดจำกัดคงที่ 3,500–6,000 Kbps ที่ 1080p อุดมคติ การเลือกเซิร์ฟเวอร์ภูมิภาคที่ใกล้ที่สุดมีความสำคัญพอๆ กัน — ลดเฟรมที่หาย"),
        ("SplitCam ฟรีสำหรับ XLoveCam หรือไม่?", "ใช่ — ฟรี ไม่มีลายน้ำและไม่จำกัดเวลา การเข้าถึงผู้ชมยุโรปหลายภาษาของ XLoveCam ไม่เสียค่าซอฟต์แวร์")]),
    _p("soulcams", "SoulCams",
       "ถ่ายทอดบน SoulCams ด้วย SplitCam — การตั้งค่า OBS",
       "ถ่ายทอดบน SoulCams ด้วย SplitCam ฟรี — การตั้งค่า OBS เซิร์ฟเวอร์ RTMP และคีย์ ฉากหลายกล้องและโอเวอร์เลย์",
       "soul cams, soulcams, soulcams ถ่ายทอด, soulcams obs, soulcams rtmp, soulcams broadcast",
       'วิธีถ่ายทอดบน <span class="accent">SoulCams</span> ด้วย SplitCam',
       "ถ่ายทอด SoulCams",
       "การตั้งค่า OBS สำหรับ SoulCams",
       "SoulCams เป็นแพลตฟอร์ม cam ที่การตั้งค่า OBS แสดง <strong style='color:var(--text)'>เซิร์ฟเวอร์ RTMP และคีย์สตรีมร่วมกัน</strong> ในหน้าต่างเดียว วางทั้งคู่ใน <strong style='color:var(--text)'>SplitCam</strong> ฟรีเพื่อถ่ายทอดด้วยฉากหลายกล้องและโอเวอร์เลย์",
       "ถ่ายทอดบน SoulCams ด้วย SplitCam: ติดตั้ง SplitCam สร้างฉาก บน SoulCams คลิก Go Online → Settings → OBS คัดลอกเซิร์ฟเวอร์และคีย์ วางทั้งคู่ใน SplitCam Go Live"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มกล้อง + ฉาก</li><li>เปิด SoulCams Settings → OBS</li><li>วางเซิร์ฟเวอร์ + คีย์ใน SplitCam</li><li>กด Go Live</li></ol>",
       "บน SoulCams เข้าสู่ระบบและคลิก <strong>Go Online</strong> จากนั้นเปิด <strong>Settings</strong> → <strong>OBS</strong> หน้าต่าง OBS แสดง <strong>เซิร์ฟเวอร์ RTMP</strong> และ <strong>คีย์สตรีม</strong> ร่วมกัน — คัดลอกทั้งคู่ใน SplitCam",
       [("เซิร์ฟเวอร์และคีย์เคียงข้างกัน", "SoulCams แสดงเซิร์ฟเวอร์ RTMP และคีย์ในหน้าต่าง OBS เดียวกัน — คุณรับทั้งคู่ในครั้งเดียว"),
        ("Go Online ก่อน", "การตั้งค่า OBS ปรากฏหลังจากคลิก Go Online บน SoulCams เท่านั้น — ทำก่อนค้นหาข้อมูล encoder"),
        ("บล็อกภูมิภาคที่ไม่ต้องการ", "SoulCams อนุญาตการบล็อกตามภูมิภาคจากฝั่งโมเดล — เลือกประเทศที่ไม่สามารถดูสตรีมก่อนกด Go Online"),
        _T_ETH, _T_TEST],
       [("การตั้งค่า OBS ของ SoulCams อยู่ที่ไหน?", "เข้าสู่ระบบ คลิก Go Online จากนั้น Settings → OBS — เซิร์ฟเวอร์ RTMP และคีย์สตรีมแสดงร่วมกัน"),
        ("SoulCams รองรับ encoder ภายนอกหรือไม่?", "ใช่ — การตั้งค่า OBS ให้เซิร์ฟเวอร์ RTMP และคีย์ ดังนั้น SplitCam ทำงานได้"),
        ("บิตเรตสำหรับ SoulCams?", "SoulCams ไม่ให้ตัวเลขทางการ — เล็ง 3,500–6,000 Kbps ที่ 1080p และทดสอบอัปโหลด เนื่องจากหน้าต่าง OBS ไม่แสดงคำแนะนำบิตเรต"),
        ("SplitCam ฟรีสำหรับ SoulCams หรือไม่?", "ใช่ — ฟรี ไม่มีลายน้ำและไม่จำกัดเวลา ดังนั้นโชว์ SoulCams เต็มรูปแบบด้วยฉากหลายกล้องและโอเวอร์เลย์ไม่เสียค่าใช้จ่ายฝั่ง encoder")]),
    _p("imlive", "ImLive",
       "ถ่ายทอดบน ImLive ด้วย SplitCam — กล้องเสมือน",
       "การตั้งค่า Im Live stream ด้วย SplitCam ฟรี — ImLive ใช้เว็บแคมโดยตรง (ไม่มี RTMP) เชื่อม SplitCam เป็นกล้องเสมือนพร้อมฉาก",
       "im live stream, imlive splitcam, imlive ถ่ายทอด, imlive กล้องเสมือน, imlive webcam, im live cam",
       'วิธีใช้ <span class="accent">ImLive</span> ด้วย SplitCam',
       "SplitCam บน ImLive",
       "การตั้งค่ากล้องเสมือนสำหรับ ImLive — ไม่มี RTMP",
       "ImLive ใช้เว็บแคมโดยตรงในเบราว์เซอร์ — <strong style='color:var(--text)'>ไม่มี RTMP และไม่มีคีย์สตรีม</strong> <strong style='color:var(--text)'>SplitCam</strong> ฟรีเชื่อมต่อเป็น <strong style='color:var(--text)'>กล้องเสมือน</strong>: สร้างฉากใน SplitCam จากนั้นเลือก SplitCam เป็นกล้องใน ImLive",
       "ใช้ SplitCam กับ ImLive: ติดตั้ง SplitCam สร้างฉากด้วยเลเยอร์สื่อ เปิด ImLive และเริ่มแชทวิดีโอ ในการตั้งค่า ImLive เลือก SplitCam เป็นเว็บแคมและไมโครโฟน"
       "<ol><li>ติดตั้ง SplitCam</li><li>สร้างฉากใน SplitCam</li><li>เริ่มแชทวิดีโอบน ImLive</li><li>เลือก SplitCam เป็นกล้อง ImLive</li><li>เริ่มแชท</li></ol>",
       "เข้าสู่ระบบไซต์ ImLive และคลิก <strong>Start Video Chat</strong> จากนั้นเปิด <strong>Go To Settings</strong> เพื่อเข้าถึงตัวเลือกกล้องและไมโครโฟน ในการตั้งค่า ImLive เลือก <strong>SplitCam</strong> เป็นเว็บแคมและไมโครโฟน",
       [("ไม่ต้องใช้คีย์สตรีม", "ImLive ไม่มี RTMP — อย่าค้นหา URL เซิร์ฟเวอร์หรือคีย์ SplitCam เพียงถูกเลือกเป็นอุปกรณ์กล้อง"),
        ("ตั้ง SplitCam เป็นไมโครโฟนด้วย", "เลือก SplitCam สำหรับไมโครโฟนนอกเหนือจากกล้อง เพื่อให้การผสมเสียงและการระงับเสียงรบกวนเข้าสู่ไลฟ์ด้วย"),
        ("สร้างฉากก่อนไลฟ์", "ImLive แสดงสิ่งที่ SplitCam ส่ง — จัดเลเยอร์ก่อนเริ่มแชท"),
        _T_TEST],
       [("ImLive ใช้ RTMP หรือคีย์สตรีม?", "ไม่ — ImLive ใช้เว็บแคมโดยตรงผ่านเบราว์เซอร์ SplitCam เชื่อมต่อเป็นกล้องเสมือน ไม่มีคีย์ให้คัดลอก"),
        ("ฉันจะเลือก SplitCam บน ImLive อย่างไร?", "Start Video Chat → Go To Settings → เลือก SplitCam เป็นเว็บแคมและไมโครโฟน"),
        ("ฉันใช้โอเวอร์เลย์บน ImLive ได้ไหม?", "ได้ — สร้างในฉาก SplitCam ImLive แสดงผลลัพธ์รวม"),
        ("SplitCam ฟรีสำหรับ ImLive หรือไม่?", "ใช่ — ฟรี ไม่มีลายน้ำและไม่จำกัดเวลา ในฐานะกล้องเสมือนสำหรับ ImLive ไม่เพิ่มค่าใช้จ่ายหรือการสร้างแบรนด์ให้แชทวิดีโอของคุณ")],
       steps=[
           ("ติดตั้ง SplitCam", "SplitCam เป็นซอฟต์แวร์ฟรีสำหรับ Windows และ macOS ติดตั้ง — ไม่มีลายน้ำ ไม่ต้องสมัคร สำหรับ ImLive ทำงานเป็น <strong>กล้องเสมือน</strong> ไม่ใช่ encoder RTMP"),
           ("สร้างฉากใน SplitCam", "เปิด SplitCam และใช้ <strong>Media Layers +</strong> เพื่อเพิ่มเว็บแคมและโอเวอร์เลย์ ข้อความ ฟิลเตอร์ หรือพื้นหลัง AI ฉากที่ประกอบขึ้นนี้คือสิ่งที่ ImLive จะเห็นเป็นกล้องของคุณ"),
           ("เริ่มแชทวิดีโอบน ImLive", "เข้าสู่ระบบไซต์ ImLive และคลิก <strong>Start Video Chat</strong> จากนั้นเปิด <strong>Go To Settings</strong> เพื่อเข้าถึงตัวเลือกกล้องและไมโครโฟน"),
           ("เลือก SplitCam เป็นกล้อง", "ในการตั้งค่า ImLive เลือก <strong>SplitCam</strong> เป็นเว็บแคมและไมโครโฟน ImLive แสดงฉาก SplitCam เต็มรูปแบบของคุณแทนเว็บแคมเรียบๆ"),
           ("เริ่ม Free Live Chat", "คลิก <strong>Free Live Chat</strong> บน ImLive เพื่อไลฟ์ หากต้องการเปลี่ยนรูปลักษณ์กลางเซสชัน แก้ไขฉากใน SplitCam — ImLive อัปเดตทันที"),
       ]),
    _p("vxlive", "VXLive",
       "ถ่ายทอดบน VXLive ด้วย SplitCam — การสนับสนุนทางการ",
       "ถ่ายทอดบน VXLive (VXModels / VISIT-X) ด้วย SplitCam ฟรี — VISIT-X preset ทางการ เซิร์ฟเวอร์และคีย์ ฉาก ไม่มีลายน้ำ",
       "vxlive, visit-x, vxmodels splitcam, vxlive ถ่ายทอด, visit-x stream, vxlive rtmp",
       'วิธีถ่ายทอดบน <span class="accent">VXLive</span> ด้วย SplitCam',
       "ถ่ายทอด VXLive",
       "VXLive รองรับ SplitCam อย่างเป็นทางการ (VISIT-X preset)",
       "VXLive (VXModels / VISIT-X) เป็นแพลตฟอร์ม cam จากตลาดเยอรมัน — และเป็นหนึ่งในไม่กี่แห่งที่ <strong style='color:var(--text)'>รองรับ SplitCam อย่างเป็นทางการตามชื่อ</strong> VXModels มีบทความช่วยเหลือเฉพาะสำหรับเชื่อม <strong style='color:var(--text)'>SplitCam</strong> กับ VXLive และ SplitCam ให้ VISIT-X เป็น preset ช่องสำเร็จรูป",
       "ถ่ายทอดบน VXLive ด้วย SplitCam: ติดตั้ง SplitCam สร้างฉาก บน VXLive เลือก «Stream with third-party software» คัดลอก URL เซิร์ฟเวอร์และคีย์ ใน SplitCam เลือก VISIT-X preset และวาง Go Live ใน SplitCam จากนั้น GO ONLINE บน VXLive"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มกล้อง + ฉาก</li><li>รับ URL เซิร์ฟเวอร์ + คีย์จาก VXLive</li><li>เลือก VISIT-X preset ใน SplitCam วาง</li><li>Go Live จากนั้น GO ONLINE บน VXLive</li></ol>",
       "บน VXLive เลือก <strong>Stream with third-party software</strong> และเลือกตัวเลือกสำหรับ <strong>OBS, SplitCam หรือ XSplit</strong> VXLive ให้ <strong>URL เซิร์ฟเวอร์</strong> และ <strong>คีย์สตรีม</strong> ใน SplitCam เลือก <strong>VISIT-X</strong> เป็นแพลตฟอร์มสตรีมมิ่ง วางทั้งคู่ กด <strong>Go Live</strong> ใน SplitCam จากนั้น <strong>GO ONLINE</strong> บน VXLive",
       [("VISIT-X เป็น preset ที่รวมเข้ากัน", "อย่าพิมพ์ URL RTMP ดิบ — SplitCam มี VISIT-X ในรายการแพลตฟอร์ม เพียงเลือกและวาง URL เซิร์ฟเวอร์และคีย์"),
        ("Go-live สองขั้นตอน", "บน VXLive กด Go Live ใน SplitCam ก่อน จากนั้น GO ONLINE บน VXLive — ทั้งคู่ ตามลำดับ"),
        ("ตลาดเยอรมัน", "ผู้ชม VXLive ส่วนใหญ่พูดภาษาเยอรมัน — โอเวอร์เลย์ข้อความหรือชื่อภาษาเยอรมันช่วยเชื่อมต่อกับผู้ชม"),
        _T_ETH],
       [("VXLive รองรับ SplitCam อย่างเป็นทางการหรือไม่?", "ใช่ — VXModels (VXLive) ดูแลบทความช่วยเหลือทางการเฉพาะสำหรับการตั้งค่า SplitCam และแสดง SplitCam ควบคู่กับ OBS และ XSplit เป็นซอฟต์แวร์ถ่ายทอดที่รองรับ"),
        ("ฉันจะเชื่อม SplitCam กับ VXLive อย่างไร?", "บน VXLive คุณเลือก «Stream with third-party software» จากนั้นใน SplitCam คุณเลือก VISIT-X preset และวาง URL เซิร์ฟเวอร์และคีย์สตรีมที่ VXLive ให้"),
        ("ฉันไลฟ์ใน SplitCam หรือบน VXLive?", "ทั้งคู่ — Go Live ใน SplitCam ก่อน จากนั้น GO ONLINE บน VXLive"),
        ("ทำไม VXModels แนะนำ SplitCam?", "บทความช่วยเหลือทางการของ VXModels แนะนำ SplitCam โดยเฉพาะเพื่อกำจัดสิ่งประดิษฐ์ในภาพเว็บแคมและการแตกของพิกเซลและทำให้การเชื่อมต่อเสถียร — ไม่ใช่แค่ encoder ทั่วไป")]),
    _p("virtwish", "VirtWish",
       "ถ่ายทอดบน VirtWish ด้วย SplitCam — URL สตรีมและคีย์",
       "ถ่ายทอดบน VirtWish ด้วย SplitCam ฟรี — Profile → Start Broadcast ส่วน OBS URL สตรีมและคีย์ ฉากและโอเวอร์เลย์",
       "virtwish, virtwish ถ่ายทอด, virtwish broadcasting software, virtwish rtmp, virtwish stream key, virtwish obs",
       'วิธีถ่ายทอดบน <span class="accent">VirtWish</span> ด้วย SplitCam',
       "ถ่ายทอด VirtWish",
       "การตั้งค่า URL สตรีม + คีย์สำหรับ VirtWish",
       "VirtWish เป็นแพลตฟอร์ม cam แบบโต้ตอบ การตั้งค่าการถ่ายทอดให้ <strong style='color:var(--text)'>URL สตรีมและคีย์สตรีมแยกต่างหาก</strong> ในส่วน OBS — <strong style='color:var(--text)'>SplitCam</strong> ฟรีรับทั้งคู่และรันโชว์ด้วยฉากและโอเวอร์เลย์",
       "ถ่ายทอดบน VirtWish ด้วย SplitCam: ติดตั้ง SplitCam สร้างฉาก บน VirtWish เปิด <em>Profile → Start Broadcast</em> จนถึงส่วน OBS คัดลอกลิงก์และคีย์ วางทั้งคู่ใน SplitCam Go Live"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มกล้อง + ฉาก</li><li>รับ URL + คีย์จาก VirtWish</li><li>วางทั้งคู่ใน SplitCam</li><li>กด Go Live</li></ol>",
       "บน VirtWish คลิกไอคอนมุมขวาบน → <strong>Profile</strong> → <strong>Start Broadcast</strong> จากนั้น <strong>Start Broadcast</strong> อีกครั้งเพื่อไปถึงส่วน OBS <strong>คัดลอกลิงก์บนบรรทัดแรก</strong> ในช่อง Stream URL ของ SplitCam และ <strong>Stream Key</strong> แยกต่างหากในช่องคีย์",
       [("ลิงก์บนบรรทัดแรก", "ส่วน OBS ของ VirtWish วาง URL สตรีมบนบรรทัดแรก — คัดลอกไปยัง Stream URL ของ SplitCam จากนั้นคีย์แยกต่างหาก"),
        ("คลิก Start Broadcast สองครั้ง", "คุณคลิก Start Broadcast สองครั้งบน VirtWish เพื่อไปถึงส่วน OBS — คาดหวัง ไม่ใช่บั๊ก"),
        _T_ETH, _T_TEST],
       [("ข้อมูล RTMP ของ VirtWish อยู่ที่ไหน?", "ไอคอนบนขวา → Profile → Start Broadcast สองครั้ง → ส่วน OBS แสดงลิงก์และคีย์สตรีม"),
        ("VirtWish รองรับ encoder ภายนอกหรือไม่?", "ใช่ — ส่วน OBS ให้ URL สตรีมและคีย์ ดังนั้น SplitCam ทำงาน"),
        ("บิตเรตสำหรับ VirtWish?", "VirtWish ไม่ได้เผยแพร่เพดานทางการ 3,500–6,000 Kbps ที่ 1080p ปลอดภัย ปรับความละเอียดของ SplitCam ให้ตรงกับที่ตั้งบน VirtWish เพื่อหลีกเลี่ยงการปรับขนาดใหม่"),
        ("SplitCam ฟรีสำหรับ VirtWish หรือไม่?", "ใช่ — ฟรี ไม่มีลายน้ำและไม่จำกัดเวลา การตั้งค่า URL และคีย์ของ VirtWish ใช้เวลาเพียงไม่กี่นาที")]),
    _p("xmodels", "XModels",
       "ถ่ายทอดบน XModels ด้วย SplitCam — คู่มือฟรี",
       "ถ่ายทอดบน XModels ด้วย SplitCam ฟรี — ตัวเลือก encoder ภายนอกในการตั้งค่าบัญชีโมเดล คีย์ RTMP ฉากและโอเวอร์เลย์",
       "xmodels, xmodels ถ่ายทอด, xmodels broadcasting software, xmodels rtmp, xmodels external encoder",
       'วิธีถ่ายทอดบน <span class="accent">XModels</span> ด้วย SplitCam',
       "ถ่ายทอด XModels",
       "การตั้งค่า encoder ภายนอกสำหรับ XModels",
       "XModels เป็นแพลตฟอร์ม cam-streaming พร้อม <strong style='color:var(--text)'>ตัวเลือก encoder ภายนอก</strong> ในตัวในการตั้งค่าบัญชีโมเดล <strong style='color:var(--text)'>SplitCam</strong> ฟรีถ่ายทอดที่นั่นด้วยฉากหลายกล้อง โอเวอร์เลย์ และฟิลเตอร์แทนกล้องเรียบๆ เดียว",
       "ถ่ายทอดบน XModels ด้วย SplitCam: ติดตั้ง SplitCam สร้างฉาก ในบัญชีโมเดล XModels เปิดใช้งานตัวเลือก encoder ภายนอก คัดลอก URL เซิร์ฟเวอร์และคีย์สตรีม วางใน SplitCam Go Live"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มกล้อง + ฉาก</li><li>เปิดใช้งาน encoder ภายนอกในการตั้งค่า XModels</li><li>วาง URL เซิร์ฟเวอร์ + คีย์ใน SplitCam</li><li>กด Go Live</li></ol>",
       "ใน <strong>การตั้งค่าบัญชีโมเดล</strong> ของ XModels เปิดใช้งานตัวเลือก <strong>ถ่ายทอดผ่าน encoder ภายนอก</strong> XModels ให้ <strong>คีย์สตรีม</strong> — คัดลอกไปยัง SplitCam หากตัวเลือกไม่อยู่ในที่ที่คุณคาดหวัง ฝ่ายสนับสนุน XModels อยู่ผ่านการแชท FAQ บนไซต์และ <strong>info@xmodels.com</strong> วิดีโอด้านบนแสดงด้วย",
       [("อยู่ในการตั้งค่าบัญชี", "XModels วางตัวเลือก encoder ภายนอกในการตั้งค่าบัญชีโมเดล ไม่ใช่บนหน้าจอถ่ายทอดแยกต่างหาก"),
        ("ฝ่ายสนับสนุน: แชท + อีเมล", "XModels ไม่มีศูนย์ช่วยเหลือสาธารณะขนาดใหญ่ — แชท FAQ บนไซต์และ info@xmodels.com เป็นช่องทางสนับสนุนทางการ"),
        ("ซ้อนโอเวอร์เลย์ใน SplitCam", "เป้าหมายทิป ชื่อ และโซเชียลแฮนเดิลเป็นเลเยอร์ฉาก — กล้องพื้นฐานของ XModels ไม่เพิ่มสิ่งเหล่านี้"),
        _T_ETH],
       [("XModels รองรับ encoder ภายนอกหรือไม่?", "ใช่ — การตั้งค่าบัญชีโมเดลรวมตัวเลือกการถ่ายทอดผ่าน encoder ภายนอกที่ให้คีย์สตรีม ดังนั้น SplitCam ทำงาน"),
        ("ฉันจะได้รับความช่วยเหลือ XModels ที่ไหน?", "ฝ่ายสนับสนุน XModels อยู่ผ่านการแชท FAQ บนไซต์และอีเมล info@xmodels.com — ไม่มีศูนย์ช่วยเหลือสาธารณะขนาดใหญ่"),
        ("บิตเรตสำหรับ XModels?", "XModels ไม่ได้บันทึกตัวเลขทางการ — ใช้ 3,500–6,000 Kbps ที่ 1080p และรันการทดสอบความเร็วของ SplitCam เนื่องจากฝ่ายสนับสนุน XModels เป็นเพียงแชทและอีเมล"),
        ("SplitCam ฟรีสำหรับ XModels หรือไม่?", "ใช่ — ฟรี ไม่มีลายน้ำและไม่จำกัดเวลา ดังนั้นการถ่ายทอดไปยังเครือข่ายยุโรปของ XModels ไม่เพิ่มค่าซอฟต์แวร์")]),
    _p("flirt4free", "Flirt4Free",
       "ถ่ายทอดบน Flirt for Free cam ด้วย SplitCam — คู่มือฟรี",
       "ถ่ายทอดบน Flirt for Free cam ด้วย SplitCam ฟรี — External Broadcast Form, RTMP URL และ Stream Name ฉากและโอเวอร์เลย์",
       "flirt for free cam, flirt 4 free cam, flirt4free, flirt4free ถ่ายทอด, flirt4free external broadcast, flirt4free rtmp",
       'วิธีถ่ายทอดบน <span class="accent">Flirt4Free</span> ด้วย SplitCam',
       "ถ่ายทอด Flirt4Free",
       "การตั้งค่า External Broadcast Form สำหรับ Flirt4Free",
       "Flirt4Free เป็นหนึ่งในแพลตฟอร์ม cam ที่เก่าแก่ที่สุด ออกอากาศตั้งแต่ทศวรรษ 90 รองรับการถ่ายทอดภายนอกอย่างเป็นทางการผ่าน <strong style='color:var(--text)'>External Broadcast Form</strong> — <strong style='color:var(--text)'>SplitCam</strong> ฟรีส่งสตรีมในขณะที่ฟอร์มตั้งค่าความละเอียดและบิตเรต",
       "ถ่ายทอดบน Flirt4Free ด้วย SplitCam: ติดตั้ง SplitCam สร้างฉาก เปิด Flirt4Free External Broadcast Form คัดลอก RTMP URL และ Stream Name และตั้งความละเอียด/บิตเรต วางใน SplitCam Go Live"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มกล้อง + ฉาก</li><li>เปิด Flirt4Free External Broadcast Form</li><li>วาง RTMP URL + Stream Name ใน SplitCam</li><li>กด Go Live</li></ol>",
       "ในพื้นที่โมเดลของ Flirt4Free เปิด <strong>External Broadcast Form</strong> ไม่เหมือนไซต์ cam ส่วนใหญ่ Flirt4Free ให้ <strong>RTMP URL</strong> และ <strong>Stream Name</strong> (ไม่ใช่ «คีย์») รวมถึงฟิลด์ความละเอียดและบิตเรตที่คุณกรอกในฟอร์มเอง คัดลอก URL และ Stream Name ในช่องเซิร์ฟเวอร์และคีย์ของ SplitCam",
       [("เป็น Stream Name ไม่ใช่คีย์", "Flirt4Free เรียกหนังสือรับรองว่า Stream Name คุณวางในช่องคีย์สตรีมของ SplitCam — บทบาทเดียวกัน"),
        ("ตั้งความละเอียด/บิตเรตในฟอร์ม", "External Broadcast Form ของ Flirt4Free มีฟิลด์ความละเอียดและบิตเรตของตัวเอง — จัดให้ตรงกับการตั้งค่าของ SplitCam เพื่อไม่ให้ภาพถูกปรับขนาด"),
        ("แพลตฟอร์มประวัติศาสตร์", "Flirt4Free ทำงานตั้งแต่ทศวรรษ 90 — เครื่องมือโมเดลพัฒนาแล้ว และ External Broadcast Form เป็นส่วนหนึ่งที่บันทึกไว้"),
        _T_ETH],
       [("Flirt4Free รองรับ encoder ภายนอกหรือไม่?", "ใช่ — อย่างเป็นทางการ ผ่าน External Broadcast Form ที่ให้ RTMP URL และ Stream Name SplitCam ทำงานเป็น encoder"),
        ("ฉันรับข้อมูล RTMP ของ Flirt4Free ที่ไหน?", "จาก External Broadcast Form ในพื้นที่โมเดล — แสดง RTMP URL, Stream Name และฟิลด์ความละเอียด/บิตเรต"),
        ("บิตเรตสำหรับ Flirt4Free?", "3,500–6,000 Kbps ที่ 1080p — ตั้งค่าเดียวกันใน External Broadcast Form และใน SplitCam"),
        ("SplitCam ฟรีสำหรับ Flirt4Free หรือไม่?", "ใช่ — ฟรี ไม่มีลายน้ำและไม่จำกัดเวลา ซึ่งเข้ากันกับแพลตฟอร์มประวัติศาสตร์อย่าง Flirt4Free ที่โชว์อาจยาวนาน")]),
    _p("mfc-alerts", "MFC Alerts",
       "เพิ่ม MFC Alerts ลงในสตรีมด้วย SplitCam",
       "แสดงทิปอเลิร์ตเคลื่อนไหวในสตรีม MyFreeCams — mfcalerts.com URL เป็นเลเยอร์เบราว์เซอร์ใน SplitCam ฟรี เหนือเว็บแคม",
       "mfc alerts, myfreecams alerts, เพิ่ม mfc alerts, mfcalerts splitcam, myfreecams tip alerts, myfreecams alerts overlay",
       'วิธีเพิ่ม <span class="accent">MFC Alerts</span> ลงในสตรีม',
       "เพิ่ม MFC Alerts",
       "แสดงทิปอเลิร์ตเคลื่อนไหวในสตรีม MyFreeCams",
       "MFC Alerts แสดงเอฟเฟกต์เคลื่อนไหวในสตรีม MyFreeCams ของคุณทุกครั้งที่ผู้ชมส่งทิป มันทำงานเป็น <strong style='color:var(--text)'>เลเยอร์เบราว์เซอร์</strong> ภายใน <strong style='color:var(--text)'>SplitCam</strong> ฟรี — ตั้งค่าครั้งเดียวและทิปจะกระตุ้นการตอบสนองบนหน้าจอแบบสด",
       "เพิ่ม MFC Alerts ด้วย SplitCam: ติดตั้ง SplitCam เพิ่มเว็บแคม เปิดแท็บเบราว์เซอร์และโหลด mfcalerts.com คัดลอก URL อเลิร์ต เพิ่มเป็นเลเยอร์เบราว์เซอร์เหนือเว็บแคม จากนั้นทดสอบด้วยทิปทดสอบ"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มเว็บแคม</li><li>รับ URL จาก mfcalerts.com</li><li>เพิ่มเป็นเลเยอร์เบราว์เซอร์เหนือเว็บแคม</li><li>ส่งทิปทดสอบ</li></ol>",
       "ใน SplitCam เปิดแท็บ <strong>Browser</strong> และไปที่ <strong>www.mfcalerts.com</strong> เข้าสู่ระบบหรือสมัครสมาชิก ใช้ <strong>Copy to clipboard</strong> เพื่อคัดลอก URL อเลิร์ตส่วนตัวของคุณ วาง URL ในหน้าต่างเบราว์เซอร์ของ SplitCam และคลิก <strong>Add</strong> จากนั้นจัดลำดับรายการแหล่งใหม่ให้ <strong>MFC Alerts อยู่เหนือเว็บแคม</strong> (เมนู 3 จุด → Move Up)",
       [("MFC Alerts ต้องอยู่เหนือเว็บแคม", "ข้อผิดพลาดที่พบบ่อยที่สุด: ถ้าเลเยอร์ MFC Alerts อยู่ใต้เว็บแคมในรายการแหล่ง เอฟเฟกต์จะถูกซ่อน เลื่อนขึ้น"),
        ("ต้องมีบัญชี mfcalerts.com", "URL อเลิร์ตเป็นส่วนตัว — สมัครที่ mfcalerts.com ก่อนหากคุณไม่มีบัญชี"),
        ("ส่งทิปทดสอบก่อนไลฟ์", "ใช้ Settings → Send test tip เพื่อยืนยันว่าโอเวอร์เลย์ทำงาน — อย่าค้นพบข้อผิดพลาดกลางโชว์"),
        _T_ETH],
       [("MFC Alerts คืออะไร?", "ระบบการแจ้งเตือนสำหรับ MyFreeCams ที่แสดงเอฟเฟกต์วิดีโอในสตรีมของคุณเมื่อผู้ชมส่งทิป — เพิ่มเป็นโอเวอร์เลย์เบราว์เซอร์ใน SplitCam"),
        ("ทำไม MFC Alerts ของฉันไม่ปรากฏ?", "เกือบทุกครั้งคือลำดับเลเยอร์ — เลเยอร์ MFC Alerts Browser ต้องอยู่เหนือเว็บแคมในรายการแหล่งของ SplitCam"),
        ("ฉันต้องการบัญชีสำหรับ MFC Alerts หรือไม่?", "ใช่ — สมัครที่ mfcalerts.com เพื่อรับ URL อเลิร์ตส่วนตัวของคุณ"),
        ("SplitCam ฟรีสำหรับสิ่งนี้หรือไม่?", "ใช่ — SplitCam ฟรี ไม่มีลายน้ำและไม่จำกัดเวลา และโอเวอร์เลย์เบราว์เซอร์ของ MFC Alerts ทำงานภายในโดยไม่มีค่าใช้จ่ายเพิ่มเติม")],
       steps=[
           ("ติดตั้ง SplitCam และเพิ่มเว็บแคม", "ติดตั้ง SplitCam ฟรีสำหรับ Windows หรือ macOS จากนั้นเพิ่ม <strong>เว็บแคม</strong> เป็นแหล่ง MFC Alerts นั่งเป็นเลเยอร์เหนือกล้องนี้"),
           ("เปิดแท็บเบราว์เซอร์และไปที่ mfcalerts.com", "ใน SplitCam เปิดแท็บ <strong>Browser</strong> และไปที่ <strong>www.mfcalerts.com</strong> เข้าสู่ระบบ หรือสมัครหากคุณยังไม่มีบัญชี mfcalerts.com"),
           ("คัดลอก URL อเลิร์ตของคุณ", "บน mfcalerts.com ใช้ <strong>Copy to clipboard</strong> เพื่อคัดลอก URL อเลิร์ตส่วนตัวของคุณ — เป็นหน้าที่เรนเดอร์อนิเมชันทิป"),
           ("เพิ่ม URL เป็นเลเยอร์เบราว์เซอร์ — เหนือเว็บแคม", "วาง URL ในหน้าต่างเบราว์เซอร์ของ SplitCam และคลิก <strong>Add</strong> จากนั้นจัดลำดับรายการแหล่งใหม่ให้ <strong>MFC Alerts อยู่เหนือเว็บแคม</strong> (เมนู 3 จุด → Move Up) ถ้าอยู่ใต้ เอฟเฟกต์จะถูกซ่อน"),
           ("ทดสอบด้วยทิปทดสอบ", "เปิด <strong>Settings → Send test tip</strong> และยืนยันว่าเอฟเฟกต์อเลิร์ตปรากฏเหนือกล้องของคุณ จากนั้นถ่ายทอดตามปกติบน MyFreeCams — ทิปจริงตอนนี้กระตุ้นอนิเมชัน"),
       ]),
    _p("lovense", "Lovense",
       "เพิ่มของเล่น Lovense ลงในสตรีมด้วย SplitCam",
       "เชื่อมต่อของเล่น Lovense แบบโต้ตอบกับสตรีม cam ด้วย SplitCam ฟรี — Lovense SplitCam Toolset ทิปอเลิร์ตบนหน้าจอ การโต้ตอบ",
       "เพิ่ม lovense ในสตรีม, lovense cam stream, lovense splitcam, lovense splitcam toolset, lovense interactive toy streaming",
       'วิธีเพิ่ม <span class="accent">ของเล่น Lovense</span> ลงในสตรีม',
       "เพิ่มของเล่น Lovense",
       "เชื่อมต่อของเล่น Lovense แบบโต้ตอบกับสตรีม cam ของคุณ",
       "คุณรันสตรีม cam ผ่าน <strong style='color:var(--text)'>SplitCam</strong> ฟรีและจับคู่ของเล่น <strong style='color:var(--text)'>Lovense</strong> ที่ตอบสนองต่อโทเค็น Lovense บันทึก <strong style='color:var(--text)'>Lovense SplitCam Toolset</strong> ทางการ และ SplitCam ให้ปลั๊กอิน Lovense ทางการ — การรวมเข้ากันได้รับการสนับสนุนจากทั้งสองด้าน",
       "ในการเพิ่มของเล่น Lovense ลงในสตรีม: ติดตั้ง SplitCam และซอฟต์แวร์ Lovense จับคู่ของเล่น เชื่อม Lovense กับแพลตฟอร์ม cam ของคุณ เพิ่มสถานะ Lovense เป็นเลเยอร์เบราว์เซอร์ใน SplitCam จากนั้นถ่ายทอดตามปกติ"
       "<ol><li>ติดตั้ง SplitCam</li><li>ติดตั้งซอฟต์แวร์ Lovense และจับคู่ของเล่น</li><li>เชื่อม Lovense กับไซต์ cam ของคุณ</li><li>เพิ่มโอเวอร์เลย์ Lovense ใน SplitCam</li><li>กด Go Live</li></ol>",
       "ติดตั้ง Lovense Connect / Lovense Stream (แอปเดสก์ท็อปทางการ) เปิดของเล่นและจับคู่ผ่าน Bluetooth ให้แอปแสดงเชื่อมต่อแล้ว ในแอป Lovense เชื่อมบัญชี cam ของคุณเพื่อให้ของเล่นตอบสนองต่อโทเค็น/ทิปของผู้ชม Lovense ให้ URL โอเวอร์เลย์/วิดเจ็ต — เพิ่มเป็นเลเยอร์ <strong>Browser</strong> ในฉากของ SplitCam",
       [("ใช้ Lovense SplitCam Toolset ทางการ", "Lovense เผยแพร่ toolset เฉพาะของ SplitCam พร้อมคู่มือการติดตั้งของตัวเอง — เพิ่มโอเวอร์เลย์กิจกรรมของเล่นและทิปอเลิร์ตที่สร้างสำหรับ SplitCam"),
        ("อัปเดต Lovense Cam Extension", "Toolset ต้องใช้ Lovense Cam Extension ล่าสุด (30.1.4 หรือใหม่กว่า) — อัปเดตก่อนไลฟ์"),
        ("เก็บของเล่นไว้ชาร์จ", "แบตเตอรี่ที่เกือบหมดกลางโชว์ฆ่าด้านโต้ตอบ — ชาร์จเต็มก่อนไลฟ์"),
        ("ทดสอบการตอบสนองต่อโทเค็น", "ส่งทิปทดสอบเล็กๆ เพื่อยืนยันว่าของเล่นตอบสนองก่อนเปิดห้อง"),
        ("ตรวจสอบความต้องการเวอร์ชัน", "Lovense SplitCam Toolset ต้องการ SplitCam 10.4.5 หรือใหม่กว่า Lovense Cam Extension ครอบคลุม Chaturbate, Stripchat, BongaCams, MyFreeCams และ CamSoda อย่างเป็นทางการ — สำหรับไซต์อื่นๆ ใช้การรวมเข้ากับ Generic URL ของ Lovense")],
       [("Lovense รองรับ SplitCam อย่างเป็นทางการหรือไม่?", "ใช่ — Lovense บันทึก «Lovense SplitCam Toolset» อย่างเป็นทางการพร้อมคู่มือการติดตั้งของตัวเอง และ SplitCam ให้ปลั๊กอิน Lovense ทางการ การรวมเข้ากันได้รับการสนับสนุนจากทั้งสองด้าน"),
        ("ของเล่นเชื่อมต่อโดยตรงกับ SplitCam หรือไม่?", "ไม่ — ของเล่นจับคู่กับแอป Lovense SplitCam แสดงโอเวอร์เลย์ Lovense และถ่ายทอดกล้อง"),
        ("ไซต์ cam ใดรองรับ Lovense?", "Lovense Cam Extension รองรับ Chaturbate, Stripchat, BongaCams, MyFreeCams และ CamSoda อย่างเป็นทางการ ด้วยการสนับสนุนที่แตกต่างกันสำหรับอื่นๆ — ตรวจสอบรายการปัจจุบันในแอป Lovense"),
        ("ฉันสามารถแสดงทิปล่าสุดบนหน้าจอได้หรือไม่?", "ใช่ — เพิ่ม URL วิดเจ็ต Lovense เป็นเลเยอร์เบราว์เซอร์ใน SplitCam")],
       steps=[
           ("ติดตั้ง SplitCam", "SplitCam เป็นซอฟต์แวร์สตรีมมิ่งฟรีสำหรับ Windows และ macOS — encoder ที่ส่งวิดีโอของคุณไปยังแพลตฟอร์ม cam ติดตั้ง; ไม่มีลายน้ำ"),
           ("ติดตั้งซอฟต์แวร์ Lovense และจับคู่ของเล่น", "ติดตั้ง Lovense Connect / Lovense Stream (แอปเดสก์ท็อปทางการ) เปิดของเล่นและจับคู่ผ่าน Bluetooth ให้แอปแสดงเชื่อมต่อแล้ว"),
           ("เชื่อม Lovense กับแพลตฟอร์ม cam", "ในแอป Lovense เชื่อมบัญชี cam ของคุณเพื่อให้ของเล่นตอบสนองต่อโทเค็น/ทิปของผู้ชม แพลตฟอร์ม cam ใหญ่ๆ ส่วนใหญ่ได้รับการสนับสนุน"),
           ("เพิ่มโอเวอร์เลย์ Lovense ใน SplitCam", "Lovense ให้ URL โอเวอร์เลย์/วิดเจ็ต เพิ่มเป็นเลเยอร์ <strong>Browser</strong> ในฉาก SplitCam เพื่อให้ผู้ชมเห็นสถานะของเล่นและทิปล่าสุดบนหน้าจอ"),
           ("สร้างฉากและ Go Live", "เพิ่มกล้องและโอเวอร์เลย์อื่นๆ วางคีย์ RTMP ของแพลตฟอร์ม cam ใน SplitCam และคลิก <strong>Go Live</strong> ของเล่นตอบสนองต่อทิปแบบเรียลไทม์"),
       ]),
    _p("multistream-cams", "หลายไซต์ cam",
       "ถ่ายทอดไปยังหลายไซต์ cam พร้อมกันด้วย SplitCam",
       "ถ่ายทอดไปยัง MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat และอื่นๆ พร้อมกันด้วยมัลติสตรีมฟรีของ SplitCam คลิกเดียว ไม่มีลายน้ำ",
       "ถ่ายทอดไปยังหลายไซต์ cam, multistream cam sites, ถ่ายทอดไปยัง chaturbate และ bongacams พร้อมกัน, multistream cam ซอฟต์แวร์",
       'วิธีถ่ายทอดไปยัง <span class="accent">หลายไซต์ cam</span> พร้อมกัน',
       "Cam มัลติสตรีมมิ่ง",
       "ถ่ายทอดไปยังหลายไซต์ cam พร้อมกัน",
       "<strong style='color:var(--text)'>SplitCam</strong> ฟรีสามารถถ่ายทอดการเข้ารหัสหนึ่งครั้งไปยัง <strong style='color:var(--text)'>หลายไซต์ cam พร้อมกัน</strong> — MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat และอื่นๆ ไม่มีลายน้ำ คลิกเดียว",
       "ในการถ่ายทอดไปยังหลายไซต์ cam ในครั้งเดียว: ติดตั้ง SplitCam สร้างฉาก รับ URL เซิร์ฟเวอร์ RTMP และคีย์สตรีมของแต่ละไซต์ cam เพิ่มทั้งหมดในการตั้งค่ามัลติสตรีมมิ่งของ SplitCam คลิก Go Live ครั้งเดียว"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มกล้อง + ฉาก</li><li>รับคีย์ RTMP จากแต่ละไซต์ cam</li><li>เพิ่มคีย์ทั้งหมดใน SplitCam multistream</li><li>กด Go Live ครั้งเดียว</li></ol>",
       "บนแต่ละแพลตฟอร์ม cam เปิดใช้งานการถ่ายทอดภายนอก / RTMP และคัดลอก <strong>URL เซิร์ฟเวอร์</strong> และ <strong>คีย์สตรีม</strong> ใน SplitCam เปิด <strong>Stream Settings</strong> และเพิ่มแต่ละไซต์ cam เป็นปลายทาง RTMP กำหนดเอง — วาง URL เซิร์ฟเวอร์และคีย์ ตรวจสอบทุกสิ่งที่คุณต้องการให้ถ่ายทอด กด <strong>Go Live</strong>",
       [("เฝ้าดูการอัปโหลดของคุณ", "มัลติสตรีมมิ่งคูณภาระอัปโหลด แต่ละปลายทางใช้บิตเรตของตัวเอง — ตรวจสอบให้แน่ใจว่าการเชื่อมต่อของคุณสามารถจัดการผลรวมได้"),
        ("ตรวจสอบกฎของแพลตฟอร์ม", "ไซต์ cam บางแห่งห้ามการถ่ายทอดพร้อมกันที่อื่น — ยืนยันก่อนมัลติสตรีมมิ่ง"),
        ("สายเคเบิล — คุณไม่สามารถยอมรับการหลุดที่นี่ได้", "มัลติสตรีมมิ่งคูณภาระอัปโหลด ดังนั้นการหลุด wi-fi ครั้งเดียวสามารถล้มปลายทางทั้งหมดในคราวเดียว สายเคเบิลไม่ใช่ทางเลือกที่นี่"),
        ("ดูตัวตรวจสอบสุขภาพ", "SplitCam แสดงสถานะตามปลายทาง — ทิ้งไซต์หากการอัปโหลดไม่สามารถจัดการได้")],
       [("มัลติสตรีมมิ่งของ SplitCam ฟรีหรือไม่?", "ใช่ — มัลติสตรีมมิ่งสร้างขึ้นในตัวและฟรี ไม่มีค่าธรรมเนียมต่อปลายทาง ไม่มีลายน้ำ"),
        ("ฉันสามารถถ่ายทอดไปยังไซต์ cam กี่แห่งพร้อมกัน?", "เท่าที่แบนด์วิธอัปโหลดของคุณสามารถจัดการได้ — แต่ละปลายทางใช้บิตเรตของตัวเอง"),
        ("ใช้ cloud relay หรือไม่?", "ไม่ — SplitCam ส่งสตรีมแบบเพียร์ทูเพียร์โดยตรงจากพีซีไปยัง ingest ของแต่ละแพลตฟอร์ม"),
        ("มัลติสตรีมมิ่งทำให้พีซีของฉันช้าลงหรือไม่?", "การเข้ารหัสทำครั้งเดียวและใช้ซ้ำ การเข้ารหัสฮาร์ดแวร์ทำให้ภาระ CPU ต่ำ แบนด์วิธอัปโหลดเป็นขีดจำกัดจริง")],
       steps=[
           ("ติดตั้ง SplitCam", "SplitCam เป็นซอฟต์แวร์สตรีมมิ่งฟรีสำหรับ Windows และ macOS พร้อมมัลติสตรีมมิ่งในตัว ติดตั้ง — ไม่มีลายน้ำ ไม่ต้องสมัคร"),
           ("ตั้งค่ากล้องและฉาก", "เปิด SplitCam เพิ่มเว็บแคมและสร้างฉากด้วยโอเวอร์เลย์และฟิลเตอร์ ฉากเดียวให้อาหารแต่ละปลายทาง"),
           ("รับคีย์ RTMP จากแต่ละไซต์ cam", "บนแต่ละแพลตฟอร์ม cam เปิดใช้งานการถ่ายทอดภายนอก / RTMP และคัดลอก <strong>URL เซิร์ฟเวอร์</strong> และ <strong>คีย์สตรีม</strong> ทำซ้ำสำหรับแต่ละไซต์ที่คุณต้องการถ่ายทอด — ดูคู่มือแพลตฟอร์มแต่ละรายการสำหรับเส้นทางที่แน่นอน"),
           ("เพิ่มปลายทางแต่ละรายการใน SplitCam", "เปิด <strong>Stream Settings</strong> และเพิ่มแต่ละไซต์ cam เป็นปลายทาง RTMP กำหนดเอง — วาง URL เซิร์ฟเวอร์และคีย์ ตรวจสอบทุกสิ่งที่คุณต้องการให้ถ่ายทอด"),
           ("คลิก Go Live ครั้งเดียว", "กด <strong>Go Live</strong> SplitCam ส่งสตรีมไปยังแต่ละไซต์ cam ที่เลือกพร้อมกัน เพียร์ทูเพียร์ จากการเข้ารหัสเดียว — ไม่มีค่าธรรมเนียมเพิ่มเติม"),
       ]),
    _p("livejasmin", "LiveJasmin",
       "ถ่ายทอดบน LiveJasmin ด้วย SplitCam — HD External Encoder",
       "ถ่ายทอดบน LiveJasmin ด้วย SplitCam ฟรี — Model Center External Encoder, การตั้งค่า HD 1080p, ฉากหลายกล้องและโอเวอร์เลย์ ไม่มีลายน้ำ ไม่ต้องสมัคร",
       "livejasmin ถ่ายทอด, livejasmin obs, livejasmin external encoder, livejasmin rtmp, livejasmin stream key, livejasmin model setup",
       'วิธีถ่ายทอดบน <span class="accent">LiveJasmin</span> ด้วย SplitCam',
       "ถ่ายทอด LiveJasmin",
       "การตั้งค่า encoder ภายนอกสำหรับ Model Center แบบ HD-only ของ LiveJasmin",
       "LiveJasmin เป็นเรือธงของ Docler Holding — หนึ่งในเครือข่าย cam ที่ใหญ่ที่สุดในโลกและเป็นแพลตฟอร์ม HD-only โปรแกรมถ่ายทอดที่แนะนำคือไคลเอนต์ <strong>JasminCAM</strong> ของบริษัทเอง แต่ Model Center ยังเปิดเส้นทาง <strong>External Encoder</strong> มาตรฐานไว้ — <strong style='color:var(--text)'>SplitCam</strong> ฟรีเชื่อมต่อเข้าทางนี้ ทำให้คุณถ่ายทอดด้วยฉากหลายกล้อง ฟิลเตอร์ความงาม และโอเวอร์เลย์บนสตรีม HD เดียวกัน",
       "ถ่ายทอดบน LiveJasmin ด้วย SplitCam: ติดตั้ง SplitCam สร้างฉาก HD ใน Model Center ไปที่ <em>Settings → Broadcast → External Encoder</em> คัดลอก URL เซิร์ฟเวอร์และ stream key วางใน SplitCam Go Live"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มกล้อง + ฉาก HD</li><li>รับ URL และ stream key จาก Model Center</li><li>วางใน SplitCam</li><li>กด Go Live</li></ol>",
       "เข้าสู่ระบบที่ <strong>modelcenter.livejasmin.com</strong> เปิด <strong>Settings → Broadcast → External Encoder</strong> Model Center จะแสดง <strong>URL เซิร์ฟเวอร์</strong> และ <strong>stream key</strong> ที่ผูกกับบัญชีของคุณ — คัดลอกทั้งคู่ไปวางในช่อง RTMP กำหนดเองของ SplitCam <strong>หมายเหตุ:</strong> บัญชีใหม่ต้องได้รับการอนุมัติ (48–72 ชั่วโมง) ก่อนตัวเลือก External Encoder จะปรากฏ และแพลตฟอร์มบังคับเอาต์พุต HD-only",
       [("ถ้าไม่ HD จะถูกลดอันดับ", "LiveJasmin เป็น HD-only — ต่ำกว่า 1280×720 เสี่ยงถูกแสดงเฉพาะในรายการที่จ่ายต่ำ ต่ำกว่า 1080p เสียคุณสมบัติ «Premium» ดันที่ 1920×1080, 30 fps, 4,000–6,000 Kbps"),
        ("JasminCAM vs encoder ภายนอก", "ไคลเอนต์ JasminCAM ของ Docler เองให้ความสอดคล้องกับ HD ที่สะอาดที่สุด แต่ encoder ภายนอก (OBS, SplitCam, vMix) ได้รับการรองรับอย่างเป็นทางการหลังบัญชีของคุณผ่านการอนุมัติ — ปลดล็อกฉากหลายกล้องและโอเวอร์เลย์ที่ JasminCAM ทำไม่ได้"),
        ("Free chat ≠ Private show", "Free chat เป็นโหมดพรีวิวเท่านั้น — ห้ามเปลือย Private และ Gold show คือที่ที่โมเดลทำเงิน วางแผนฉากให้ดูดีทั้งตอนใส่เสื้อผ้าและตอนโหมดโชว์"),
        _T_ETH],
       [("LiveJasmin รองรับ encoder ภายนอกอย่าง SplitCam อย่างเป็นทางการหรือไม่?", "ใช่ — Model Center มีตัวเลือก External Encoder ใน Settings → Broadcast JasminCAM เป็นไคลเอนต์ที่แนะนำ แต่ OBS, SplitCam และ encoder RTMP อื่นๆ ถูกระบุไว้อย่างชัดเจนว่ารองรับเมื่อบัญชีโมเดลของคุณได้รับการอนุมัติ"),
        ("stream key ของ LiveJasmin อยู่ที่ไหน?", "ภายใน Model Center: Settings → Broadcast → External Encoder ทั้ง URL เซิร์ฟเวอร์และ stream key เฉพาะตัวจะปรากฏที่นั่น — คัดลอกทั้งคู่ไปวางในช่อง RTMP กำหนดเองของ SplitCam คีย์ผูกกับบัญชีของคุณ ปฏิบัติเหมือนรหัสผ่าน"),
        ("ใช้บิตเรตเท่าไรสำหรับ LiveJasmin?", "LiveJasmin เป็น HD-only — เล็งที่ 1920×1080, 30 fps, 4,000–6,000 Kbps พร้อม keyframe ทุก 2 วินาที ต่ำกว่านั้นอย่างเห็นได้ชัดจะเสียป้าย Premium และถูกลดอันดับ"),
        ("SplitCam ใช้กับ LiveJasmin ฟรีหรือไม่?", "ใช่ — SplitCam ฟรี ไม่มีลายน้ำ ไม่จำกัดเวลา «ต้นทุน» เดียวคือการทำให้ผ่านเกณฑ์ HD ของ LiveJasmin ซึ่ง SplitCam จัดการได้ในตัวด้วยการประกอบฉาก 1080p และฟิลเตอร์ความงาม")],
       steps=[
           ("ดาวน์โหลดและติดตั้ง SplitCam", "SplitCam เป็นซอฟต์แวร์ถ่ายทอดสดฟรีสำหรับ Windows และ macOS — ไม่ต้องสมัคร ไม่ต้องใช้บัตร ไม่มีลายน้ำ เป็น encoder ที่ส่งวิดีโอ HD ของคุณไปยัง LiveJasmin"),
           ("สร้างฉาก HD ของคุณ", "เปิด SplitCam และเพิ่มเว็บแคมในโหมด 1080p ซ้อนด้วยโอเวอร์เลย์ ข้อความ กล้องตัวที่สองหรือมือถือ ฟิลเตอร์ความงามหรือพื้นหลัง AI — LiveJasmin ต้องการคุณภาพ HD และฉากที่ประกอบแล้วต้องดูพรีเมียมตลอดทั้งใน free chat และ private show"),
           ("รับ URL และ stream key ของ LiveJasmin", "เข้าสู่ระบบที่ <strong>modelcenter.livejasmin.com</strong> (บัญชีของคุณต้องได้รับการอนุมัติก่อน — โดยปกติ 48–72 ชั่วโมงหลังสมัคร) เปิด <strong>Settings → Broadcast → External Encoder</strong> หน้านี้จะแสดง <strong>URL เซิร์ฟเวอร์</strong> และ <strong>stream key</strong> เฉพาะตัว คัดลอกทั้งคู่"),
           ("เชื่อม SplitCam กับ LiveJasmin", "ใน SplitCam เปิด <strong>Stream Settings</strong> วาง URL เซิร์ฟเวอร์และ stream key ของ LiveJasmin ลงในช่อง RTMP กำหนดเอง ตั้งบิตเรตเป็น 4,000–6,000 Kbps ที่ 1920×1080, 30 fps, keyframe 2 วินาที รันการทดสอบความเร็วในตัวก่อน — สตรีม HD ใช้แบนด์วิธสูง"),
           ("คลิก Go Live", "กด <strong>Go Live</strong> ใน SplitCam แล้วออนไลน์ที่ LiveJasmin Model Center ภายในประมาณ 10 วินาทีฟีด HD ของคุณจะไปถึงเครือข่ายของ LiveJasmin การถ่ายทอดครั้งต่อๆ ไปเป็นคลิกเดียว — เปิด SplitCam, Go Live, แล้วออนไลน์ที่ LiveJasmin"),
       ]),
    _p("myfreecams", "MyFreeCams",
       "วิธีถ่ายทอดบน MyFreeCams (MFC) ด้วย SplitCam — ข้าม Model Web Broadcaster",
       "ถ่ายทอดบน MyFreeCams ด้วย SplitCam ฟรี — Model Admin External Broadcaster, ระบบโทเคน MFC, ฉากหลายกล้อง, โอเวอร์เลย์ ไม่มีลายน้ำ ไม่ต้องสมัคร",
       "myfreecams ถ่ายทอด, mfc external broadcaster, myfreecams obs, mfc rtmp, mfc stream key, model admin, mfc token",
       'วิธีถ่ายทอดบน <span class="accent">MyFreeCams</span> ด้วย SplitCam',
       "ถ่ายทอด MyFreeCams",
       "การตั้งค่า broadcaster ภายนอกสำหรับ Model Admin แบบโทเคนของ MFC",
       "MFC เป็นหนึ่งในแพลตฟอร์ม cam ที่เก่าแก่ที่สุด — ระบบโทเคนล้วน ไม่มีด่านอนุมัติโมเดลที่ยุ่งยาก และมีฐานสมาชิก Premium ที่เหนียวแน่น Model Web Broadcaster เริ่มต้นคือเครื่องมือกล้องเดี่ยวในเบราว์เซอร์ แต่ Model Admin ยังเปิดเส้นทาง External Broadcaster ไว้ด้วย — <strong style='color:var(--text)'>SplitCam</strong> ฟรีเชื่อมเข้าทางนี้ ปลดล็อกฉากหลายกล้อง โอเวอร์เลย์ และฟิลเตอร์ความงาม",
       "ถ่ายทอดบน MyFreeCams ด้วย SplitCam: ติดตั้ง SplitCam สร้างฉาก ไปที่ Model Admin → Broadcaster เปลี่ยนจาก Web Broadcaster เป็น External Broadcaster คัดลอก URL เซิร์ฟเวอร์และ stream key วางใน SplitCam Go Live"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มกล้อง + ฉาก</li><li>เปลี่ยนเป็น External Broadcaster ใน Model Admin</li><li>วาง URL และ stream key ใน SplitCam</li><li>กด Go Live</li></ol>",
       "เข้าสู่ระบบ MyFreeCams เปิด <strong>Model Admin → Broadcaster</strong> แล้วเปลี่ยนจาก <strong>Web Broadcaster</strong> เป็น <strong>External Broadcaster</strong> หน้านี้จะแสดง URL เซิร์ฟเวอร์ (rtmp://publish.myfreecams.com…) และ stream key ที่ผูกกับบัญชีโมเดลของคุณ — คัดลอกทั้งคู่ไปวางในช่อง RTMP กำหนดเองของ SplitCam คีย์ผูกกับบัญชี ปฏิบัติเหมือนรหัสผ่าน",
       [("MFC คือระบบทิป/โทเคนล้วน — ไม่ใช่ระบบสมัครสมาชิก", "หัวใจของ MFC ไม่ใช่ subscription แต่เป็นทิปใน free chat — สมาชิก Premium ไปเล่น private ได้ แต่รายได้ประจำมาจาก free chat ในชุดปกติ วางแผนฉากให้ทำเงินได้แม้ในโหมดใส่เสื้อผ้าและเป็นกันเอง"),
        ("Web Broadcaster vs External Broadcaster", "Web Broadcaster เริ่มต้นเป็นเครื่องมือสัญญาณเดียว External Broadcaster ปลดล็อกฉากหลายกล้อง โอเวอร์เลย์ และฟิลเตอร์ความงามผ่าน SplitCam/OBS — ช่องว่างระหว่างโมเดลรายได้สูงกับน้องใหม่อยู่ตรงนี้"),
        ("ใช้ mfcalerts.com แสดงทิปบนวิดีโอ", "ใน SplitCam เพิ่ม mfcalerts.com เป็นเลเยอร์ Browser บนกล้อง — แอนิเมชันทิปและชื่อสมาชิกจะปรากฏในภาพโดยตรง ช่วยเพิ่ม conversion ของทิปใน free chat อย่างเห็นได้ชัด"),
        _T_ETH],
       [("MFC รองรับ broadcaster ภายนอกอย่าง SplitCam หรือไม่?", "ใช่ — Model Admin มีตัวเลือก External Broadcaster เป็น RTMP มาตรฐาน OBS, SplitCam, vMix ใช้ได้ทั้งหมด"),
        ("stream key ของ MFC อยู่ที่ไหน?", "Model Admin → Broadcaster → External Broadcaster — URL เซิร์ฟเวอร์และ stream key อยู่หน้าเดียวกัน คัดลอกทั้งคู่ไปวางใน SplitCam"),
        ("ใช้บิตเรตเท่าไรสำหรับ MFC?", "MFC รองรับสูงสุดประมาณ 6,000 Kbps พร้อม keyframe ทุก 2 วินาที ดัน 1920×1080, 30 fps, 3,500–6,000 Kbps คือช่วงปลอดภัย"),
        ("SplitCam ใช้กับ MFC ฟรีหรือไม่?", "ใช่ — SplitCam ฟรี ไม่มีลายน้ำ ไม่จำกัดเวลา")],
       steps=[
           ("ดาวน์โหลดและติดตั้ง SplitCam", "SplitCam เป็น encoder ถ่ายทอดสดฟรีสำหรับ Windows และ macOS — ไม่ต้องสมัคร ไม่ต้องใช้บัตร ไม่มีลายน้ำ"),
           ("สร้างฉากของคุณ", "ใน SplitCam เพิ่มเว็บแคม ซ้อนโอเวอร์เลย์ ข้อความ กล้องตัวที่สองหรือมือถือ ฟิลเตอร์ความงามหรือพื้นหลัง AI เพิ่ม <strong>mfcalerts.com</strong> เป็นเลเยอร์ Browser บนกล้อง เพื่อให้แอนิเมชันทิปปรากฏในภาพ free chat โดยตรง"),
           ("เปลี่ยนเป็น External Broadcaster ใน Model Admin", "เข้าสู่ระบบ MFC เปิด <strong>Model Admin → Broadcaster</strong> แล้วเปลี่ยนจาก Web Broadcaster เป็น <strong>External Broadcaster</strong> คัดลอก URL เซิร์ฟเวอร์ (rtmp://publish.myfreecams.com…) และ stream key ที่แสดงขึ้น"),
           ("วาง URL และ key ใน SplitCam", "เปิด <strong>Stream Settings</strong> ใน SplitCam แล้ววาง URL และ stream key ในช่อง RTMP กำหนดเอง ตั้งบิตเรตเป็น 3,500–6,000 Kbps ที่ 1920×1080, 30 fps, keyframe 2 วินาที"),
           ("คลิก Go Live", "กด <strong>Go Live</strong> ใน SplitCam ภายในประมาณ 10 วินาทีสัญญาณไปถึง MFC และคุณจะออนไลน์อยู่ในห้อง"),
       ]),
    _p("cherry-tv", "Cherry.tv",
       "วิธีถ่ายทอดบน Cherry.tv ด้วย SplitCam — External Encoder แนว Web3",
       "ถ่ายทอดบน Cherry.tv ด้วย SplitCam ฟรี — Streamer Dashboard ที่รองรับ encoder ภายนอก แพลตฟอร์ม cam ที่เป็นมิตรกับคริปโต ฉากหลายกล้อง ไม่มีลายน้ำ ไม่ต้องสมัคร",
       "cherry tv ถ่ายทอด, cherry.tv obs, cherry tv external encoder, cherry.tv rtmp, cherry.tv stream key, cherry tv streamer, web3 cam",
       'วิธีถ่ายทอดบน <span class="accent">Cherry.tv</span> ด้วย SplitCam',
       "ถ่ายทอด Cherry.tv",
       "การตั้งค่า encoder ภายนอกสำหรับ Streamer Dashboard ของ Cherry.tv",
       "Cherry.tv เป็นแพลตฟอร์ม cam น้องใหม่ที่โตเร็วและมีกลิ่นอาย Web3 — รองรับการจ่ายเงินด้วยคริปโต และมีขั้นตอนการเข้าง่ายกว่าเครือข่ายเก่าอย่าง LiveJasmin ค่าเริ่มต้นเป็นการถ่ายทอดผ่านเบราว์เซอร์ แต่ Streamer Dashboard ยังเปิดเส้นทาง External Encoder มาตรฐานไว้ — <strong style='color:var(--text)'>SplitCam</strong> ฟรีเชื่อมเข้าทางนี้",
       "ถ่ายทอดบน Cherry.tv ด้วย SplitCam: ติดตั้ง SplitCam สร้างฉาก ไปที่ Streamer Dashboard → Broadcast Settings → External Encoder คัดลอก URL และ stream key วางใน SplitCam Go Live"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มกล้อง + ฉาก</li><li>เปิด External Encoder ใน Streamer Dashboard</li><li>วาง URL และ stream key ใน SplitCam</li><li>กด Go Live</li></ol>",
       "เข้าสู่ระบบบัญชี streamer ของ Cherry.tv เปิด <strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong> URL เซิร์ฟเวอร์และ stream key ผูกกับบัญชี บัญชีใหม่ต้องผ่านการยืนยันตัวพื้นฐาน แต่ขั้นตอน onboarding ของ Cherry.tv เบากว่าเครือข่าย cam เก่าๆ มาก",
       [("ขั้นเริ่มเบา และทราฟฟิกกำลังโต", "ไม่มีการรีวิวแบบ 72 ชั่วโมงของ Docler — Cherry.tv เป็นจุดดีสำหรับการเข้าก่อนแล้วชิงฐานผู้ติดตาม"),
        ("รับเงินได้ทั้งคริปโตและสกุลเงินทั่วไป", "Cherry.tv รองรับการจ่ายเงินด้วยคริปโต — มีประโยชน์มากในประเทศที่ระบบจ่ายเงินดั้งเดิมช้าหรือถูกจำกัด"),
        ("ถ่ายทอดผ่านเบราว์เซอร์ vs encoder ภายนอก", "เครื่องมือถ่ายทอดในเบราว์เซอร์ของ Cherry.tv ใช้กล้องเดียวเท่านั้น SplitCam ปลดล็อกฉากหลายกล้อง โอเวอร์เลย์ ฟิลเตอร์ความงาม และพื้นหลัง AI — งานภาพยกระดับชัดเจน"),
        _T_ETH],
       [("Cherry.tv รองรับ encoder ภายนอกหรือไม่?", "ใช่ — Streamer Dashboard มีตัวเลือก External Encoder ใต้ Broadcast Settings เป็น RTMP มาตรฐาน OBS/SplitCam ใช้ได้ตามปกติ"),
        ("stream key ของ Cherry.tv อยู่ที่ไหน?", "Streamer Dashboard → Broadcast Settings → External Encoder — URL และ stream key อยู่หน้าเดียวกัน"),
        ("ใช้บิตเรตเท่าไรสำหรับ Cherry.tv?", "ตั้งเป้า 1920×1080, 30 fps, 3,500–6,000 Kbps พร้อม keyframe 2 วินาที"),
        ("SplitCam ใช้กับ Cherry.tv ฟรีหรือไม่?", "ใช่ — SplitCam ฟรี ไม่มีลายน้ำ ไม่จำกัดเวลา")],
       steps=[
           ("ดาวน์โหลดและติดตั้ง SplitCam", "SplitCam เป็น encoder ถ่ายทอดสดฟรีสำหรับ Windows และ macOS — ไม่ต้องสมัคร ไม่ต้องใช้บัตร ไม่มีลายน้ำ"),
           ("สร้างฉาก", "เพิ่มเว็บแคมและโอเวอร์เลย์ — ผู้ชม Cherry.tv อายุน้อยกว่าและคุ้นแพลตฟอร์มมากกว่า การออกแบบและบรรยากาศของภาพจึงสำคัญ ลองผสมโอเวอร์เลย์สีสด ข้อความเคลื่อนไหว และพื้นหลัง AI"),
           ("รับ URL และ stream key", "ใน <strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong> คัดลอก URL เซิร์ฟเวอร์และ stream key"),
           ("วางใน SplitCam", "เปิด <strong>Stream Settings</strong> ใน SplitCam แล้ววาง URL และ stream key ตั้งบิตเรตเป็น 3,500–6,000 Kbps ที่ 1920×1080, 30 fps, keyframe 2 วินาที"),
           ("คลิก Go Live", "กด <strong>Go Live</strong> ใน SplitCam แล้วเปลี่ยนสถานะเป็นออนไลน์ใน Streamer Dashboard — คุณจะอยู่บน Cherry.tv ทันที"),
       ]),
    _p("amateurtv", "AmateurTV",
       "วิธีถ่ายทอดบน AmateurTV ด้วย SplitCam — เครือข่าย cam สำหรับผู้พูดสเปน",
       "ถ่ายทอดบน AmateurTV ด้วย SplitCam ฟรี — Model Panel ที่รองรับ external encoder เครือข่าย cam ภาษาสเปนของสเปนและละตินอเมริกา ฉากหลายกล้อง ไม่มีลายน้ำ ไม่ต้องสมัคร",
       "amateurtv ถ่ายทอด, amateur.tv obs, amateurtv external encoder, amateurtv rtmp, amateurtv stream key, modelos amateur tv",
       'วิธีถ่ายทอดบน <span class="accent">AmateurTV</span> ด้วย SplitCam',
       "ถ่ายทอด AmateurTV",
       "การตั้งค่า external encoder สำหรับเครือข่ายภาษาสเปนของ AmateurTV",
       "AmateurTV เป็นเครือข่าย cam อันดับหนึ่งของโลกผู้พูดภาษาสเปน — มีผู้ชมแน่นในสเปน เม็กซิโก อาร์เจนตินา และทั่วละตินอเมริกา เครื่องมือถ่ายทอดเริ่มต้นของ Model Panel ทำงานในเบราว์เซอร์ แต่ก็เปิดเส้นทาง <strong>External Encoder</strong> มาตรฐานไว้ด้วย — <strong style='color:var(--text)'>SplitCam</strong> ฟรีต่อเข้าทางนี้ ทำให้คุณถ่ายทอดด้วยฉากหลายกล้อง ฟิลเตอร์ความงาม และโอเวอร์เลย์ ให้กลุ่มผู้ชมภาษาสเปนที่เครือข่ายฝั่งสหรัฐฯ ไม่ค่อยใส่ใจ",
       "ถ่ายทอดบน AmateurTV ด้วย SplitCam: ติดตั้ง SplitCam สร้างฉาก เปิด <em>Broadcast Settings → External Encoder</em> ใน Model Panel คัดลอก URL เซิร์ฟเวอร์และ stream key วางใน SplitCam Go Live"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มกล้อง + ฉาก</li><li>รับ URL และ stream key จาก Model Panel</li><li>วางใน SplitCam</li><li>กด Go Live</li></ol>",
       "เข้าสู่ระบบบัญชีโมเดล AmateurTV เปิด <strong>Model Panel</strong> ไปที่ <strong>Broadcast Settings → External Encoder</strong> หน้านี้จะแสดง URL เซิร์ฟเวอร์และ stream key ที่ผูกกับบัญชีของคุณ — คัดลอกทั้งคู่ไปวางในช่อง RTMP กำหนดเองของ SplitCam บัญชีโมเดลใหม่ต้องผ่านการยืนยันตัวก่อนถึงจะถ่ายทอดได้",
       [("ผู้ชมภาษาสเปนต้องมาก่อน", "ทราฟฟิกของ AmateurTV เป็นภาษาสเปนแทบทั้งหมด — กลางวันเน้นสเปน ช่วงเย็นเวลาสหรัฐฯ เน้นละตินอเมริกา ใช้ภาษาสเปนทั้งในชื่อห้อง ข้อความบนฉาก และโอเวอร์เลย์ จะทำผลงานดีกว่าภาษาอังกฤษล้วนชัดเจน"),
        ("เขตเวลาละตินอเมริกาคือไพรม์ของคุณ", "ทราฟฟิกพีคตรงกับช่วงเย็นของละตินอเมริกา (UTC-3 ถึง UTC-6) ถ้าตารางคุณยืดหยุ่น การถ่ายทอดช่วงดึกของยุโรป / เช้าตรู่ของเอเชียจะกินทั้งพีคสเปนและละตินอเมริกาในรอบเดียว"),
        ("ส่วนแบ่งระดับกลางที่นิ่ง", "RPM ไม่ใช่สูงสุดในวงการ แต่จ่ายสม่ำเสมอ และตลาดผู้พูดสเปนมีการแข่งขันน้อยกว่าเครือข่ายชั้นนำของสหรัฐฯ มาก"),
        _T_ETH],
       [("AmateurTV รองรับ external encoder อย่าง SplitCam อย่างเป็นทางการหรือไม่?", "ใช่ — Model Panel มีตัวเลือก External Encoder ใต้ Broadcast Settings AmateurTV ให้ URL เซิร์ฟเวอร์และ stream key แบบ RTMP มาตรฐาน OBS, SplitCam, vMix และ encoder RTMP อื่นๆ ต่อได้หมด"),
        ("stream key ของ AmateurTV อยู่ที่ไหน?", "Model Panel → Broadcast Settings → External Encoder URL เซิร์ฟเวอร์และ stream key อยู่ในหน้าเดียวกัน คัดลอกทั้งคู่ไปวางในช่อง RTMP กำหนดเองของ SplitCam key ผูกกับบัญชี"),
        ("ใช้บิตเรตเท่าไรสำหรับ AmateurTV?", "ตั้งคุณภาพ cam มาตรฐาน — 1920×1080, 30 fps, 3,500–6,000 Kbps พร้อม keyframe 2 วินาที รันสปีดเทสต์ในตัวของ SplitCam ก่อน"),
        ("SplitCam ใช้กับ AmateurTV ฟรีหรือไม่?", "ใช่ — SplitCam ฟรี ไม่มีลายน้ำ ไม่จำกัดเวลา ตัวเลือก External Encoder ของ AmateurTV ก็เปิดใช้ได้ฟรี")],
       steps=[
           ("ดาวน์โหลดและติดตั้ง SplitCam", "SplitCam เป็นซอฟต์แวร์ถ่ายทอดสดฟรีสำหรับ Windows และ macOS — ไม่ต้องสมัคร ไม่ต้องใช้บัตร ไม่มีลายน้ำ มันคือ encoder ที่ส่งวิดีโอของคุณไปยัง AmateurTV"),
           ("สร้างฉาก", "เปิด SplitCam และเพิ่มเว็บแคม ทับโอเวอร์เลย์ ข้อความ กล้องที่สองหรือมือถือ ฟิลเตอร์ความงาม หรือพื้นหลัง AI ใช้ข้อความภาษาสเปนบนโอเวอร์เลย์เพื่อจับกลุ่มผู้ชมสเปนของ AmateurTV"),
           ("รับ URL และ stream key ของ AmateurTV", "เข้าสู่ระบบบัญชีโมเดล AmateurTV เปิด <strong>Model Panel</strong> ไปที่ <strong>Broadcast Settings → External Encoder</strong> หน้านี้จะแสดง URL เซิร์ฟเวอร์และ stream key เฉพาะของคุณ คัดลอกทั้งคู่"),
           ("เชื่อม SplitCam เข้ากับ AmateurTV", "เปิด <strong>Stream Settings</strong> ใน SplitCam แล้ววาง URL และ stream key ของ AmateurTV ในช่อง RTMP กำหนดเอง ตั้งบิตเรตเป็น 3,500–6,000 Kbps ที่ 1920×1080, 30 fps, keyframe 2 วินาที รันสปีดเทสต์ในตัวก่อน"),
           ("คลิก Go Live", "กด <strong>Go Live</strong> ใน SplitCam แล้วเปลี่ยนสถานะเป็นออนไลน์จาก Model Panel บน AmateurTV ภายในประมาณ 10 วินาทีสัญญาณไปถึงเครือข่าย รอบถัดไปคลิกเดียวจบ — เปิด SplitCam กด Go Live"),
       ]),
    _p("camster", "Camster",
       "วิธีถ่ายทอดบน Camster ด้วย SplitCam — Model Hub external encoder",
       "ถ่ายทอดบน Camster ด้วย SplitCam ฟรี — Model Hub ที่รองรับ external encoder แพลตฟอร์ม cam ระดับกลางที่อยู่ตัวแล้ว ฉากหลายกล้องและโอเวอร์เลย์ ไม่มีลายน้ำ ไม่ต้องสมัคร",
       "camster ถ่ายทอด, camster.com obs, camster external encoder, camster rtmp, camster stream key, camster model hub",
       'วิธีถ่ายทอดบน <span class="accent">Camster</span> ด้วย SplitCam',
       "ถ่ายทอด Camster",
       "การตั้งค่า external encoder สำหรับ Model Hub ของ Camster",
       "Camster เป็นแพลตฟอร์ม cam ระดับกลางที่อยู่ตัวแล้ว — เล็กกว่า Chaturbate หรือ LiveJasmin แต่มีฐานผู้ใช้ที่ภักดีและส่วนแบ่งที่ยุติธรรม เครื่องมือถ่ายทอดเริ่มต้นของ Model Hub ทำงานในเบราว์เซอร์ แต่ก็เปิดเส้นทาง <strong>External Encoder</strong> มาตรฐานไว้ด้วย — <strong style='color:var(--text)'>SplitCam</strong> ฟรีต่อเข้าทางนี้ ทำให้คุณถ่ายทอดด้วยฉากหลายกล้อง โอเวอร์เลย์ และฟิลเตอร์ ซึ่งเครื่องมือในเบราว์เซอร์ทำไม่ได้",
       "ถ่ายทอดบน Camster ด้วย SplitCam: ติดตั้ง SplitCam สร้างฉาก เปิด <em>Broadcast Settings → External Encoder</em> ใน Model Hub คัดลอก URL เซิร์ฟเวอร์และ stream key วางใน SplitCam Go Live"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มกล้อง + ฉาก</li><li>รับ URL และ stream key จาก Model Hub</li><li>วางใน SplitCam</li><li>กด Go Live</li></ol>",
       "เข้าสู่ระบบบัญชีโมเดล Camster เปิด <strong>Model Hub</strong> ไปที่ <strong>Broadcast Settings → External Encoder</strong> หน้านี้จะแสดง URL เซิร์ฟเวอร์และ stream key ที่ผูกกับบัญชีของคุณ — คัดลอกทั้งคู่ไปวางในช่อง RTMP กำหนดเองของ SplitCam key ผูกกับบัญชี ดูแลเหมือนรหัสผ่าน",
       [("ระดับกลางคือมีคู่แข่งน้อยกว่า", "Camster มีทราฟฟิกสม่ำเสมอ แต่ผู้ถ่ายทอดน้อยกว่าเครือข่ายชั้นนำ — ทำให้ขึ้นหน้าแรกได้ง่ายขึ้นถ้าคุณมีฉากที่ใส่ใจและตารางที่นิ่ง"),
        ("ถ่ายทอดในเบราว์เซอร์ vs external", "เครื่องมือในเบราว์เซอร์เริ่มต้นเป็นแหล่งเดียว ส่วน SplitCam ผ่าน External Encoder ปลดล็อกฉากหลายกล้อง โอเวอร์เลย์ ฟิลเตอร์ความงาม และพื้นหลัง AI"),
        ("การจ่ายเงินสม่ำเสมอ ส่วนแบ่งยุติธรรม", "ส่วนแบ่งของ Camster ยุติธรรมสำหรับระดับกลาง — ไม่ใช่สูงสุดในวงการ แต่จ่ายรายเดือนตรงเวลา และมีโมเดลร้องเรียนเรื่องจ่ายช้าน้อยมาก"),
        _T_ETH],
       [("Camster รองรับ external encoder อย่าง SplitCam อย่างเป็นทางการหรือไม่?", "ใช่ — Model Hub มีตัวเลือก External Encoder ใต้ Broadcast Settings ใช้ URL เซิร์ฟเวอร์และ stream key แบบ RTMP มาตรฐาน OBS, SplitCam และ encoder RTMP อื่นๆ ต่อได้หมด"),
        ("stream key ของ Camster อยู่ที่ไหน?", "Model Hub → Broadcast Settings → External Encoder URL เซิร์ฟเวอร์และ stream key อยู่ในหน้าเดียวกัน คัดลอกทั้งคู่ไปวางในช่อง RTMP กำหนดเองของ SplitCam"),
        ("ใช้บิตเรตเท่าไรสำหรับ Camster?", "ตั้งคุณภาพ cam มาตรฐาน — 1920×1080, 30 fps, 3,500–6,000 Kbps พร้อม keyframe 2 วินาที รันสปีดเทสต์ในตัวของ SplitCam ก่อน"),
        ("SplitCam ใช้กับ Camster ฟรีหรือไม่?", "ใช่ — SplitCam ฟรี ไม่มีลายน้ำ ไม่จำกัดเวลา ตัวเลือก External Encoder ของ Camster ก็ฟรี")],
       steps=[
           ("ดาวน์โหลดและติดตั้ง SplitCam", "SplitCam เป็นซอฟต์แวร์ถ่ายทอดสดฟรีสำหรับ Windows และ macOS — ไม่ต้องสมัคร ไม่ต้องใช้บัตร ไม่มีลายน้ำ"),
           ("สร้างฉาก", "เปิด SplitCam และเพิ่มเว็บแคม ทับโอเวอร์เลย์ ข้อความ กล้องที่สองหรือมือถือ ฟิลเตอร์ความงาม หรือพื้นหลัง AI — ทั้งหมดทำสดได้"),
           ("รับ URL และ stream key ของ Camster", "เข้าสู่ระบบบัญชีโมเดล Camster เปิด <strong>Model Hub</strong> ไปที่ <strong>Broadcast Settings → External Encoder</strong> หน้านี้จะแสดง URL เซิร์ฟเวอร์และ stream key เฉพาะของคุณ คัดลอกทั้งคู่"),
           ("เชื่อม SplitCam เข้ากับ Camster", "เปิด <strong>Stream Settings</strong> ใน SplitCam แล้ววาง URL และ stream key ของ Camster ในช่อง RTMP กำหนดเอง ตั้งบิตเรตเป็น 3,500–6,000 Kbps ที่ 1920×1080, 30 fps, keyframe 2 วินาที รันสปีดเทสต์ในตัวก่อน"),
           ("คลิก Go Live", "กด <strong>Go Live</strong> ใน SplitCam แล้วเปลี่ยนสถานะเป็นออนไลน์จาก Model Hub บน Camster ภายในประมาณ 10 วินาทีสัญญาณไปถึง Camster"),
       ]),
    _p("camversity", "Camversity",
       "วิธีถ่ายทอดบน Camversity ด้วย SplitCam — Performer Dashboard external encoder",
       "ถ่ายทอดบน Camversity ด้วย SplitCam ฟรี — Performer Dashboard ที่รองรับ external encoder แพลตฟอร์ม cam อิสระที่กำลังเติบโตและเป็นมิตรกับ performer ฉากหลายกล้อง ไม่มีลายน้ำ ไม่ต้องสมัคร",
       "camversity ถ่ายทอด, camversity obs, camversity external encoder, camversity rtmp, camversity stream key, camversity performer",
       'วิธีถ่ายทอดบน <span class="accent">Camversity</span> ด้วย SplitCam',
       "ถ่ายทอด Camversity",
       "การตั้งค่า external encoder สำหรับ Performer Dashboard ของ Camversity",
       "Camversity เป็นแพลตฟอร์ม cam อิสระที่กำลังเติบโต — เน้นเครื่องมือที่เป็นมิตรกับ performer และอัตราค่าคอมที่ต่ำกว่าเครือข่ายดั้งเดิม เครื่องมือถ่ายทอดเริ่มต้นของ Performer Dashboard ทำงานในเบราว์เซอร์ แต่ก็เปิดเส้นทาง <strong>External Encoder</strong> มาตรฐานไว้ด้วย — <strong style='color:var(--text)'>SplitCam</strong> ฟรีต่อเข้าทางนี้ ทำให้คุณถ่ายทอดด้วยฉากหลายกล้อง โอเวอร์เลย์ และฟิลเตอร์",
       "ถ่ายทอดบน Camversity ด้วย SplitCam: ติดตั้ง SplitCam สร้างฉาก เปิด <em>Stream Settings → External Encoder</em> ใน Performer Dashboard คัดลอก URL เซิร์ฟเวอร์และ stream key วางใน SplitCam Go Live"
       "<ol><li>ติดตั้ง SplitCam</li><li>เพิ่มกล้อง + ฉาก</li><li>รับ URL และ stream key จาก Performer Dashboard</li><li>วางใน SplitCam</li><li>กด Go Live</li></ol>",
       "เข้าสู่ระบบบัญชี performer ของ Camversity เปิด <strong>Performer Dashboard</strong> ไปที่ <strong>Stream Settings → External Encoder</strong> หน้านี้จะแสดง URL เซิร์ฟเวอร์และ stream key ที่ผูกกับบัญชี — คัดลอกทั้งคู่ไปวางในช่อง RTMP กำหนดเองของ SplitCam บัญชีใหม่ต้องผ่านการยืนยันตัวมาตรฐานก่อนถ่ายทอดได้",
       [("ส่วนแบ่งเป็นมิตรกับ performer", "ส่วนแบ่งของ Camversity เอนเข้าฝั่ง performer มากกว่าเครือข่ายดั้งเดิม — น่าเอามาเทียบกับแพลตฟอร์มหลักของคุณ ถ้าคุณเพิ่งเริ่มอาชีพ cam"),
        ("Onboarding เบากว่า Docler", "การยืนยันของ Camversity เร็วกว่ารอบอนุมัติ 48–72 ชั่วโมงของ LiveJasmin แต่ยังคงน่าเชื่อถือ (ไม่มีโมเดลที่ไม่ยืนยันตัวหลุดเข้ามา) เป็นจุดสมดุลที่ดี"),
        ("สร้างฉาก ไม่ใช่แค่เปิดเว็บแคม", "เครื่องมือเริ่มต้นของ Performer Dashboard ใน Camversity ใช้แหล่งเดียว ส่วน SplitCam ผ่าน External Encoder ปลดล็อกหลายกล้อง โอเวอร์เลย์ ฟิลเตอร์ความงาม"),
        _T_ETH],
       [("Camversity รองรับ external encoder อย่าง SplitCam อย่างเป็นทางการหรือไม่?", "ใช่ — Performer Dashboard มีตัวเลือก External Encoder ใต้ Stream Settings ใช้ URL เซิร์ฟเวอร์และ stream key แบบ RTMP มาตรฐาน OBS, SplitCam, vMix ต่อได้หมด"),
        ("stream key ของ Camversity อยู่ที่ไหน?", "Performer Dashboard → Stream Settings → External Encoder URL เซิร์ฟเวอร์และ stream key อยู่ในหน้าเดียวกัน"),
        ("ใช้บิตเรตเท่าไรสำหรับ Camversity?", "ตั้งเป้า 1920×1080, 30 fps, 3,500–6,000 Kbps พร้อม keyframe 2 วินาที รันสปีดเทสต์ในตัวของ SplitCam ก่อน"),
        ("SplitCam ใช้กับ Camversity ฟรีหรือไม่?", "ใช่ — SplitCam ฟรี ไม่มีลายน้ำ ไม่จำกัดเวลา ตัวเลือก External Encoder ของ Camversity ก็ฟรี")],
       steps=[
           ("ดาวน์โหลดและติดตั้ง SplitCam", "SplitCam เป็นซอฟต์แวร์ถ่ายทอดสดฟรีสำหรับ Windows และ macOS — ไม่ต้องสมัคร ไม่ต้องใช้บัตร ไม่มีลายน้ำ"),
           ("สร้างฉาก", "เปิด SplitCam และเพิ่มเว็บแคม ทับโอเวอร์เลย์ ข้อความ กล้องที่สองหรือมือถือ ฟิลเตอร์ความงาม หรือพื้นหลัง AI"),
           ("รับ URL และ stream key ของ Camversity", "เข้าสู่ระบบบัญชี performer ของ Camversity เปิด <strong>Performer Dashboard</strong> ไปที่ <strong>Stream Settings → External Encoder</strong> หน้านี้จะแสดง URL เซิร์ฟเวอร์และ stream key เฉพาะของคุณ คัดลอกทั้งคู่"),
           ("เชื่อม SplitCam เข้ากับ Camversity", "เปิด <strong>Stream Settings</strong> ใน SplitCam แล้ววาง URL และ stream key ของ Camversity ในช่อง RTMP กำหนดเอง ตั้งบิตเรตเป็น 3,500–6,000 Kbps ที่ 1920×1080, 30 fps, keyframe 2 วินาที"),
           ("คลิก Go Live", "กด <strong>Go Live</strong> ใน SplitCam แล้วเปลี่ยนสถานะเป็นออนไลน์จาก Performer Dashboard ภายในประมาณ 10 วินาทีสัญญาณไปถึง Camversity"),
       ]),
]
