# -*- coding: utf-8 -*-
"""Ukrainian (uk) content for cam-streaming-guides. Native Ukrainian, 20 platforms."""

_T_ETH = ("Використовуйте дротове з'єднання", "Ethernet перемагає Wi-Fi під час довгих трансляцій — "
          "втрачені кадри означають втрачені чайові. Підключіть кабель до комп'ютера, що веде ефір.")
_T_TEST = ("Спершу зробіть приватний тест", "Проведіть коротку тестову трансляцію, щоб перевірити камеру, "
           "звук, кадрування та оверлеї, перш ніж відкривати кімнату для глядачів.")

def _p(slug, name, title, desc, kw, h1html, h1short, card, intro, quick, key_how, tips, faq, steps=None):
    d = {"slug": slug, "name": name, "title": title, "desc": desc, "kw": kw,
         "h1html": h1html, "h1short": h1short, "card": card, "intro": intro,
         "quick": quick, "key_how": key_how, "tips": tips, "faq": faq}
    if steps: d["steps"] = steps
    return d

PLATFORMS_UK = [
    _p("chaturbate", "Chaturbate",
       "Трансляція на Chaturbate зі SplitCam — Токен і RTMP",
       "Трансляція на Chaturbate з безкоштовним SplitCam — broadcast token, RTMP, мультикамерні сцени й оверлеї. Без водяного знака, без реєстрації.",
       "трансляція chaturbate, chaturbate broadcast token, chaturbate rtmp obs, chaturbate зовнішній кодувальник, chaturbate live",
       'Як транслювати на <span class="accent">Chaturbate</span> зі SplitCam',
       "Трансляція Chaturbate",
       "Налаштування на основі токена із зовнішнім кодувальником на Chaturbate.",
       "Chaturbate — одна з найбільших кам-платформ, побудована на економіці токенів. Її браузерний інструмент трансляції — лише плаский інструмент з однією камерою. Перехід на <strong style='color:var(--text)'>зовнішній кодувальник</strong> із безкоштовним <strong style='color:var(--text)'>SplitCam</strong> відкриває мультикамерні сцени, оверлеї та фільтри в тій самій трансляції на токенах.",
       "Трансляція на Chaturbate зі SplitCam: встановіть SplitCam, зберіть сцену, на Chaturbate відкрийте <em>Broadcast Yourself → My Broadcast</em>, скопіюйте broadcast token, вставте у SplitCam, Go Live."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте камеру + сцену.</li><li>Скопіюйте broadcast token з Chaturbate.</li><li>Вставте у SplitCam.</li><li>Натисніть Go Live.</li></ol>",
       "На Chaturbate натисніть <strong>Broadcast Yourself</strong>, щоб перейти на сторінку <strong>My Broadcast</strong>, далі <strong>View RTMP/OBS broadcast information and stream key</strong>. Ключ показується як <strong>broadcast token</strong> — скопіюйте його. Поводьтеся з ним як із паролем; ніколи не діліться.",
       [("Токен — це ключ", "Chaturbate використовує ваш broadcast token, а не загальний ключ трансляції. Поводьтеся з ним як із паролем і скиньте, якщо він витік."),
        ("Багато запасу", "RTMP ingest Chaturbate приймає до 4K, 60 fps і високий бітрейт — обмеження у вашому аплоуді, а не на платформі. Ключовий кадр кожні 2 секунди."),
        _T_ETH, _T_TEST],
       [("Чи дозволяє Chaturbate OBS / зовнішній кодувальник?", "Так — Chaturbate офіційно підтримує зовнішні кодувальники й має власну статтю «How do I set up OBS?». Увімкніть через «Use External Encoder to Broadcast» у налаштуваннях трансляції."),
        ("Де мій ключ трансляції Chaturbate?", "Broadcast Yourself → My Broadcast → View RTMP/OBS broadcast information and stream key. Ключ — це ваш broadcast token."),
        ("Який бітрейт для Chaturbate?", "3500–6000 Кбіт/с у 1080p — більш ніж достатньо. Стеля Chaturbate висока — реальне обмеження у вашому аплоуді; спершу запустіть вбудований тест швидкості SplitCam."),
        ("Чи безкоштовний SplitCam для Chaturbate?", "Так — повністю безкоштовний, без водяного знака й без обмеження часу: кодувальник не з'їдає ваші заробітки в токенах.")]),
    _p("cam4", "CAM4",
       "Трансляція на CAM4 зі SplitCam — External Encoder",
       "Трансляція на CAM4 з безкоштовним SplitCam — External Encoder, ключ трансляції, гео-блокування й оверлеї. Без водяного знака.",
       "трансляція cam4, cam4.com, cam4 external encoder, cam4 ключ трансляції, cam4 rtmp obs",
       'Як транслювати на <span class="accent">CAM4</span> зі SplitCam',
       "Трансляція CAM4",
       "External Encoder на CAM4 з гео-контролем.",
       "CAM4 — глобальна платформа cam-and-earn із вбудованим гео-контролем — ви можете приховати трансляцію в певних країнах. Трансляція через безкоштовний <strong style='color:var(--text)'>SplitCam</strong> як зовнішній кодувальник відкриває перемикання сцен і оверлеї, яких немає в базовому інструменті.",
       "Трансляція на CAM4 зі SplitCam: встановіть SplitCam, зберіть сцену, на CAM4 відкрийте <em>Broadcast &amp; Earn Money → Start Broadcast → External Encoder</em>, Get Stream Key, вставте у SplitCam, Go Live."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте камеру + сцену.</li><li>Отримайте ключ трансляції з CAM4.</li><li>Вставте у SplitCam.</li><li>Натисніть Go Live.</li></ol>",
       "На CAM4 натисніть <strong>Broadcast</strong> → <strong>Broadcast &amp; Earn Money</strong> → <strong>Start Broadcast</strong>, далі <strong>External Encoder</strong> угорі. Введіть дату народження, стать і країну, скористайтеся <strong>Get Stream Key</strong> і скопіюйте. Зелений повзунок у Stream Settings SplitCam означає з'єднання.",
       [("Налаштуйте гео-обмеження", "CAM4 дозволяє приховувати трансляцію в певних країнах і регіонах — налаштуйте це на боці CAM4 перед go-live."),
        ("Стежте за зеленим повзунком", "Налаштування CAM4 показує зелений повзунок у Stream Settings SplitCam, коли ключ прийнято — червоний = перевірте ключ."),
        ("Нижчий бітрейт, ніж зазвичай", "RTMP ingest CAM4 обмежує відеобітрейт приблизно до 3000 Кбіт/с — нижче, ніж на більшості кам-сайтів. Не змушуйте вище."),
        _T_ETH],
       [("Чи підтримує CAM4 OBS / зовнішній кодувальник офіційно?", "Так — у CAM4 є офіційний OBS Guide на сторінці підтримки, і вона рекомендує External Encoder для найкращого досвіду. SplitCam використовує той самий шлях RTMP."),
        ("Чи можу я гео-заблокувати трансляцію CAM4?", "Так — у CAM4 є вбудовані гео-обмеження, щоб приховати трансляцію в певних країнах. Налаштуйте це на CAM4, а не у SplitCam."),
        ("Де ключ трансляції CAM4?", "Broadcast → Broadcast & Earn Money → Start Broadcast → External Encoder → Get Stream Key."),
        ("Який бітрейт для CAM4?", "Нижчий за середній — RTMP ingest CAM4 обмежує ~3000 Кбіт/с при 30 fps з ключовим кадром 1 секунда. Офіційна таблиця радить не перевищувати ~3000.")]),
    _p("bongacams", "BongaCams",
       "Трансляція на BongaCams зі SplitCam — External Encoder",
       "Трансляція на BongaCams з безкоштовним SplitCam — External Encoder, мультикамерні сцени, оверлеї й AI-фони. Без водяного знака.",
       "bongacams, bongcams, трансляція bongacams, bongacams external encoder, bongacams rtmp obs",
       'Як транслювати на <span class="accent">BongaCams</span> зі SplitCam',
       "Трансляція BongaCams",
       "Налаштування External Encoder для BongaCams.",
       "BongaCams — глобальна кам-платформа. Трансляція зовнішнім кодувальником не завжди увімкнена — після активації безкоштовний <strong style='color:var(--text)'>SplitCam</strong> керує трансляцією з мультикамерними сценами, оверлеями й AI-фонами.",
       "Трансляція на BongaCams зі SplitCam: встановіть SplitCam, зберіть сцену, на BongaCams відкрийте <em>Options → Broadcast settings → Select Encoder → External Encoder</em>, скопіюйте URL і ключ, вставте у SplitCam, Go Live."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте камеру + сцену.</li><li>Отримайте URL і ключ з BongaCams.</li><li>Вставте у SplitCam.</li><li>Натисніть Go Live.</li></ol>",
       "На BongaCams відкрийте <strong>Options</strong> → <strong>Broadcast settings</strong> → <strong>Select Encoder</strong> → <strong>External Encoder</strong> і скопіюйте показаний URL сервера та ключ трансляції. <strong>Якщо кнопки External Encoder немає</strong>, зверніться до підтримки BongaCams і попросіть увімкнути зовнішнє кодування на акаунті.",
       [("Немає кнопки External Encoder? Підтримка", "BongaCams вмикає зовнішнє кодування для кожного акаунта окремо — якщо опції немає в Broadcast settings, її активує підтримка."),
        ("Узгодьте роздільну здатність", "BongaCams радить, щоб роздільна здатність вебкамери й трансляції збігалися — наприклад, обидві 1280×720."),
        _T_ETH, _T_TEST],
       [("Чому кнопка External Encoder не з'являється на BongaCams?", "Зовнішнє кодування не ввімкнене за замовчуванням на кожному акаунті — зверніться до підтримки BongaCams, щоб увімкнути, і кнопка з'явиться в Broadcast settings."),
        ("Чи треба верифікувати акаунт BongaCams?", "Так — трансляція потребує 18+, офіційного документа для перевірки віку та схвалення акаунта перед ефіром."),
        ("Який бітрейт для BongaCams?", "RTMP ingest BongaCams обмежує відеобітрейт приблизно до 6000 Кбіт/с із ключовим кадром 2 секунди — 3500–6000 у 1080p ідеально; спершу протестуйте аплоуд."),
        ("Чи безкоштовний SplitCam для BongaCams?", "Так — повністю безкоштовний, без водяного знака й без обмеження часу, тож кодувальник не зменшує ваші заробітки в токенах на BongaCams.")]),
    _p("stripchat", "Stripchat",
       "Трансляція на Stripchat зі SplitCam — налаштування strip cam",
       "Трансляція на Stripchat — платформі strip cam — з безкоштовним SplitCam. Зовнішнє ПЗ, ключ на основі токена, сцени й оверлеї.",
       "strip cam, stripchat live stream, трансляція stripchat, stripchat external software, stripchat ключ трансляції, stripchat rtmp obs",
       'Як транслювати на <span class="accent">Stripchat</span> зі SplitCam',
       "Трансляція Stripchat",
       "Налаштування зовнішнього ПЗ для трансляції Stripchat.",
       "Stripchat — велика кам-платформа з фокусом на інтерактивності. Режим <em>external software</em> дає вам ключ на основі токена — введіть його в безкоштовний <strong style='color:var(--text)'>SplitCam</strong>, щоб транслювати зі сценами, оверлеями й фільтрами замість плоскої камери.",
       "Трансляція на Stripchat зі SplitCam: встановіть SplitCam, зберіть сцену, на Stripchat виберіть <em>Switch to external software</em>, скопіюйте ключ трансляції, вставте у SplitCam, Go Live."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте камеру + сцену.</li><li>Отримайте ключ трансляції зі Stripchat.</li><li>Вставте у SplitCam.</li><li>Натисніть Go Live.</li></ol>",
       "На Stripchat виберіть <strong>Switch to external software</strong>, далі <strong>Show external software settings for the stream</strong>. Скопіюйте ключ трансляції — Stripchat показує його як токен. Тримайте в таємниці.",
       [("Узгодьте роздільну здатність із сайтом", "FAQ Stripchat попереджає: роздільна здатність у вашому ПЗ має точно збігатися із сайтом, інакше відео розсиплеться. Зробіть обидві однаковими."),
        ("Увага на мінімум 2 Мбіт/с", "Stripchat вказує 2 Мбіт/с аплоуду як мінімум — і прямо каже, що цього замало для трансляції OBS чи мультистриму. Цільтеся значно вище."),
        ("Ключ — це токен", "Ключ трансляції Stripchat — це токен — копіюйте точно, ніколи не діліться, скиньте, якщо витік."),
        _T_ETH],
       [("Чи рекомендує Stripchat OBS / зовнішнє ПЗ?", "Так — офіційний FAQ Stripchat рекомендує зовнішнє ПЗ для трансляцій, як-от OBS, «для досягнення найкращої якості відео та звуку». SplitCam працює так само."),
        ("Як переключити Stripchat на зовнішнє ПЗ?", "У Broadcast Center виберіть Switch to External Broadcast Software (OBS), далі відкрийте external software settings, щоб показати ключ трансляції (токен)."),
        ("Який бітрейт для Stripchat?", "RTMP ingest приймає до ~6000 Кбіт/с із ключовим кадром 2 секунди. 3500–6000 у 1080p ідеально — але має бути значно вище за мінімум 2 Мбіт/с, особливо для трансляції OBS."),
        ("Чи безкоштовний SplitCam для Stripchat?", "Так — без ліцензійної плати, без водяного знака, без обмеження часу: навіть довгі інтерактивні шоу на Stripchat нічого не коштують на боці кодувальника.")]),
    _p("onlyfans", "OnlyFans",
       "Лайв на OnlyFans зі SplitCam — Авторизація або ключ",
       "Лайв на OnlyFans з безкоштовним SplitCam — вхід через авторизацію або OBS Key, мультикамерні сцени, оверлеї. Без водяного знака.",
       "лайв onlyfans, onlyfans live stream, onlyfans авторизація splitcam, onlyfans obs key, onlyfans програма для трансляцій",
       'Як вести <span class="accent">лайв на OnlyFans</span> зі SplitCam',
       "Лайв OnlyFans",
       "Авторизуйтеся раз або вставте ключ — лайв на OnlyFans.",
       "Лайв OnlyFans для ваших підписників. SplitCam під'єднується <strong style='color:var(--text)'>двома способами</strong> — увійдіть раз акаунтом OnlyFans, і SplitCam автоматично отримає ключ трансляції й синхронізує його, або вставте OBS Key вручну. Обидва дають транслювати з мультикамерними сценами, оверлеями й фільтрами.",
       "Лайв на OnlyFans зі SplitCam: встановіть SplitCam, зберіть сцену, відкрийте Stream Settings &rarr; Add Channel &rarr; OnlyFans і виберіть <em>Авторизація</em> — увійдіть акаунтом OnlyFans, SplitCam отримає ключ автоматично — і натисніть Go Live. З під'єднаним акаунтом ви можете змінювати параметри трансляції OnlyFans у SplitCam, не відкриваючи сайт OnlyFans.",
       "На OnlyFans: <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; розділ <strong>Other</strong>, скопіюйте <strong>OBS Key</strong>. Або скористайтеся опцією <strong>Авторизація</strong> в SplitCam, щоб увійти — ключ отримається автоматично й залишиться синхронізованим.",
       [("Авторизація проти Stream Key", "Два способи під'єднання: <strong>Авторизація</strong> (увійдіть раз, ключ отримується й синхронізується — найпростіший шлях) або <strong>Stream Key</strong> (скопіюйте OBS Key на OnlyFans → Profile → Settings → Other і вставте)."),
        ("Змінюйте налаштування, не виходячи зі SplitCam", "З авторизацією акаунт залишається під'єднаним, тож параметри лайву OnlyFans ви налаштовуєте з SplitCam під час або після трансляції — без заходу на сайт OnlyFans."),
        ("Скромний бітрейт", "RTMP ingest OnlyFans обмежує відеобітрейт приблизно до 2500 Кбіт/с — жорсткіше, ніж на більшості кам-сайтів. Цільтеся в 720p–1080p при ~2000–2500."),
        _T_ETH],
       [("Як під'єднати OnlyFans до SplitCam?", "Двома способами. <strong>Авторизація</strong> — Stream Settings → Add Channel → OnlyFans → увійдіть акаунтом OnlyFans, і SplitCam отримає ключ автоматично. Або <strong>Stream Key</strong> — скопіюйте OBS Key на OnlyFans → Profile → Settings → Other і вставте."),
        ("Чи можу я змінювати налаштування лайву OnlyFans, не відкриваючи сайт?", "Так — зі способом Авторизації SplitCam залишається під'єднаним до акаунта OnlyFans, тож ключ і налаштування синхронізуються автоматично. Усе змінюєте з SplitCam під час або після трансляції, без заходу на onlyfans.com."),
        ("Який бітрейт для OnlyFans?", "Скромний — RTMP ingest OnlyFans обмежує бітрейт приблизно до 2500 Кбіт/с, значно жорсткіше за інші кам-платформи. Цільтеся в 720p–1080p при ~2000–2500 Кбіт/с."),
        ("Чи безкоштовний SplitCam для лайву на OnlyFans?", "Так — безкоштовний, без водяного знака й без обмеження часу. Жодних витрат на боці кодувальника.")],
       steps=[
           ("Завантажте та встановіть SplitCam", "SplitCam — безкоштовна програма для трансляцій на Windows і macOS — без реєстрації, без картки, без водяного знака. Це кодувальник, що надсилає ваше відео на OnlyFans."),
           ("Налаштуйте камеру й сцену", "Відкрийте SplitCam і додайте вебкамеру. Зберіть сцену так, як хочете, щоб її бачили глядачі — оверлеї, текст, друга камера, beauty-фільтри чи AI-фон, усе застосовується наживо."),
           ("З'єднання — Спосіб 1: Авторизація (рекомендовано)", "У SplitCam відкрийте <strong>Stream Settings</strong> &rarr; <strong>Add Channel</strong> &rarr; <strong>OnlyFans</strong> і виберіть <strong>Авторизація</strong>. Увійдіть email і паролем OnlyFans. SplitCam під'єднає акаунт, автоматично отримає ключ трансляції й синхронізуватиме його — а також дасть керувати параметрами лайву OnlyFans усередині SplitCam, змінюючи їх під час або після трансляції без відкриття сайту OnlyFans."),
           ("З'єднання — Спосіб 2: Stream Key (вручну)", "Не хочете входити? Скористайтеся ключем. На OnlyFans відкрийте <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; розділ <strong>Other</strong> і скопіюйте <strong>OBS Key</strong>. У SplitCam, Add Channel &rarr; OnlyFans, вставте в поле ключа. Цей ключ статичний — щоб змінити налаштування пізніше, поверніться на сайт OnlyFans."),
           ("Go Live", "Хай який спосіб, натисніть <strong>Go Live</strong> у SplitCam. Зі Способом 1 ви можете й далі підлаштовувати параметри OnlyFans із SplitCam у реальному часі; зі Способом 2 ключ залишається саме таким, як ви задали."),
       ]),
    _p("camplace", "CamPlace",
       "Трансляція на CamPlace зі SplitCam — безкоштовний посібник",
       "Трансляція на CamPlace з безкоштовним SplitCam — зовнішній кодувальник, ключ RTMP, сцени й оверлеї. Покроково, без водяного знака.",
       "трансляція camplace, camplace broadcasting software, camplace rtmp, camplace зовнішній кодувальник, camplace ключ трансляції",
       'Як транслювати на <span class="accent">CamPlace</span> зі SplitCam',
       "Трансляція CamPlace",
       "Налаштування зовнішнього кодувальника для трансляції CamPlace.",
       "CamPlace — платформа кам-стримінгу. Публічної статті про OBS немає, тож <strong style='color:var(--text)'>відеопосібник вище</strong> — ваш орієнтир. Безкоштовний <strong style='color:var(--text)'>SplitCam</strong> під'єднується через стандартний RTMP і додає сцени, оверлеї та AI-фони, яких немає в базовій камері.",
       "Трансляція на CamPlace зі SplitCam: встановіть SplitCam, зберіть сцену, увімкніть зовнішню/RTMP трансляцію на CamPlace, скопіюйте URL сервера й ключ трансляції, вставте у SplitCam, Go Live. Дотримуйтесь відео для актуального шляху."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте камеру + сцену.</li><li>Отримайте ключ RTMP з CamPlace.</li><li>Вставте у SplitCam.</li><li>Натисніть Go Live.</li></ol>",
       "Увійдіть на CamPlace й відкрийте налаштування трансляції. Перемкніть на опцію зовнішнього кодувальника / RTMP / OBS, щоб показати <strong>URL сервера</strong> і <strong>ключ трансляції</strong>, скопіюйте обидва. CamPlace не публікує офіційну документацію OBS — <strong>відео вище</strong> — найнадійніший покроковий шлях через поточний інтерфейс.",
       [("Немає офіційного посібника OBS — використовуйте відео", "У CamPlace немає публічної статті про зовнішній кодувальник; відео вище — орієнтир для поточного шляху."),
        ("Стандартний RTMP працює", "Хоч і недокументовано, CamPlace приймає стандартний URL сервера RTMP і ключ — SplitCam під'єднується як кастомна ціль RTMP."),
        ("Складайте оверлеї у SplitCam", "Цілі чайових, ім'я та хендли соцмереж додайте як шари сцени — базова камера CamPlace їх не додасть."),
        _T_ETH],
       [("Чи є в CamPlace офіційний посібник OBS?", "Публічної статті про зовнішній кодувальник не знайдено. CamPlace приймає стандартний URL RTMP і ключ, тож SplitCam працює — дотримуйтесь відео."),
        ("Чи підтримує CamPlace зовнішній кодувальник?", "Так — приймає стандартний ключ трансляції RTMP, тож SplitCam під'єднується як кастомна ціль RTMP."),
        ("Який бітрейт для CamPlace?", "CamPlace не публікує офіційних цифр — використовуйте 3500–6000 Кбіт/с у 1080p як безпечний діапазон і дайте тесту швидкості SplitCam визначити реальну стелю."),
        ("Чи безкоштовний SplitCam для CamPlace?", "Так — безкоштовний, без водяного знака й без обмеження часу. Оскільки в CamPlace немає власного кодувальника, безкоштовний інструмент RTMP вирішує це.")]),
    _p("camsoda", "CamSoda",
       "CamSoda лайв зі SplitCam — безкоштовне налаштування",
       "CamSoda лайв з безкоштовним SplitCam — Use OBS Broadcaster, регіональні сервери, сцени й оверлеї. Без водяного знака.",
       "camsoda live, трансляція camsoda, camsoda obs broadcaster, camsoda rtmp obs, camsoda live broadcast",
       'Як транслювати на <span class="accent">CamSoda</span> зі SplitCam',
       "Трансляція CamSoda",
       "Налаштування Use OBS Broadcaster на CamSoda.",
       "CamSoda — кам-платформа зі США, відома інтерактивними, незвичними форматами шоу. Вона офіційно підтримує трансляцію OBS — на сторінці Go Live є кнопка <strong style='color:var(--text)'>Use OBS Broadcaster</strong>, а у вікі CamSoda — офіційний посібник з OBS. Безкоштовний <strong style='color:var(--text)'>SplitCam</strong> працює так само.",
       "Трансляція на CamSoda зі SplitCam: встановіть SplitCam, зберіть сцену, натисніть Use OBS Broadcaster на сторінці Go Live CamSoda, скопіюйте URL сервера й ключ трансляції, вставте у SplitCam, Go Live."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте камеру + сцену.</li><li>Натисніть Use OBS Broadcaster на CamSoda.</li><li>Вставте URL сервера + ключ у SplitCam.</li><li>Натисніть Go Live.</li></ol>",
       "На сторінці <strong>Go Live</strong> CamSoda натисніть <strong>Use OBS Broadcaster</strong>. CamSoda показує URL сервера RTMP і ключ трансляції — скопіюйте обидва. Виберіть найближчий регіональний сервер (Північна Америка, Європа, Азія тощо). У вікі CamSoda є повний посібник з OBS для деталей.",
       [("Верифікуйтеся, щоб отримувати чайові", "На CamSoda транслювати може будь-хто, але щоб отримувати чайові, треба пройти процес верифікації CamSoda."),
        ("Виберіть найближчий регіональний сервер", "CamSoda пропонує регіональні сервери ingest — найближчий (ПН Америка / Європа / Азія / ПД Америка / Океанія) зменшує затримку й втрату кадрів."),
        ("Стеля у 1080p / 30 fps", "Ingest CamSoda сягає приблизно 1080p, 30 fps і ~6000 Кбіт/с — не змушуйте вище."),
        _T_ETH],
       [("Чи підтримує CamSoda OBS / зовнішній кодувальник?", "Так — офіційно. На сторінці Go Live є кнопка Use OBS Broadcaster, а у вікі CamSoda — посібник з OBS, тож SplitCam працює."),
        ("Чи потрібна верифікація на CamSoda?", "Для трансляції — ні. Щоб отримувати чайові — так, CamSoda вимагає спершу пройти процес верифікації."),
        ("Яку роздільну здатність підтримує CamSoda?", "До 1920×1080 при 30 fps, максимум близько 6000 Кбіт/с у RTMP ingest."),
        ("Чи безкоштовний SplitCam для CamSoda?", "Так — безкоштовний, без водяного знака й без обмеження часу. Працює з безкоштовним режимом Use OBS Broadcaster CamSoda, тож увесь комплект безкоштовний.")]),
    _p("streamate", "Streamate",
       "Трансляція на Streamate зі SplitCam — інтегрований канал",
       "Трансляція на Streamate з безкоштовним SplitCam — інтегрований канал, ключ SM Connect, сцени й оверлеї. Без водяного знака.",
       "streamate, streamate sm connect, трансляція streamate, streamate broadcasting software, streamate rtmp",
       'Як транслювати на <span class="accent">Streamate</span> зі SplitCam',
       "Трансляція Streamate",
       "Streamate — інтегрований канал у SplitCam — швидке налаштування.",
       "Streamate — усталена кам-платформа, і вона є <strong style='color:var(--text)'>наперед налаштованою ціллю в SplitCam</strong>, у списку каналів, тож налаштування швидше за ручний ввід RTMP: виберіть Streamate, вставте ключ, готово.",
       "Трансляція на Streamate зі SplitCam: встановіть SplitCam, зберіть сцену, на Streamate скористайтеся <em>SM Connect → Start Show</em> і скопіюйте ключ, далі у SplitCam відкрийте <em>Stream Settings → Add Channel → Streamate</em> і вставте."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте камеру + сцену.</li><li>Отримайте ключ Streamate через SM Connect.</li><li>Add Channel → Streamate у SplitCam.</li><li>Натисніть Go Live.</li></ol>",
       "На Streamate відкрийте <strong>SM Connect</strong>, погодьтеся з умовами, натисніть <strong>Start Show</strong> ліворуч і закрийте вікно, що відкрилося — далі скопіюйте ключ стримінгу. У SplitCam відкрийте <strong>Stream Settings</strong> → <strong>Add Channel</strong>, виберіть <strong>Streamate</strong> зі списку й вставте ключ. Зелений повзунок означає з'єднання.",
       [("Streamate інтегрований", "Без ручного URL RTMP — у SplitCam Streamate є у списку Add Channel; просто виберіть і вставте ключ."),
        ("Закрийте попап SM Connect", "Після Start Show Streamate відкриває вікно — закрийте; воно лише для показу ключа стримінгу."),
        ("Зафіксуйте роздільну здатність на 1080p", "Поле Video Resolution у SM Connect може нишком стрибнути на 1440, що насправді не надсилається й тихо знижує вашу якість — задайте вручну 1080p. Падіння бітрейту при нерухомому зображенні нормальне: стрим Streamate адаптивний."),
        _T_ETH, _T_TEST],
       [("Чи інтегрований Streamate у SplitCam?", "Так — Streamate з'являється у списку Add Channel SplitCam; ви його вибираєте, а не вводите URL RTMP вручну."),
        ("Де ключ стримінгу Streamate?", "SM Connect → погодьтеся з умовами → Start Show → закрийте попап → скопіюйте ключ."),
        ("Який бітрейт для Streamate?", "Streamate не задає жорсткої стелі — 3500–6000 Кбіт/с у 1080p працює добре. Стрим адаптивний, тож нижчий бітрейт при нерухомому зображенні нормальний, а не баг."),
        ("Чи безкоштовний SplitCam для Streamate?", "Так — безкоштовний, без водяного знака й без обмеження часу; а оскільки Streamate — інтегрований канал у SplitCam, окремих витрат на кодувальник немає.")]),
    _p("streamray", "StreamRay",
       "Трансляція на StreamRay cam зі SplitCam — URL у чаті",
       "Трансляція на StreamRay cam з безкоштовним SplitCam — URL публікується в чаті, режим OBS Broadcaster, сцени й оверлеї. Без водяного знака.",
       "streamray, streamray cam, трансляція streamray, streamray obs broadcaster, streamray rtmp",
       'Як транслювати на <span class="accent">StreamRay</span> зі SplitCam',
       "Трансляція StreamRay",
       "Налаштування зовнішнього кодувальника типу URL-у-чаті для StreamRay.",
       "StreamRay має незвичне налаштування зовнішнього кодувальника — він надсилає URL трансляції у <strong style='color:var(--text)'>вікно чату трансляції</strong> й не використовує окремий ключ. Безкоштовний <strong style='color:var(--text)'>SplitCam</strong> опрацьовує цей потік лише з URL.",
       "Трансляція на StreamRay зі SplitCam: встановіть SplitCam, зберіть сцену, на StreamRay увімкніть OBS Broadcaster, скопіюйте URL трансляції з вікна чату, вставте у SplitCam (поле ключа залиште порожнім), Go Live."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте камеру + сцену.</li><li>Скопіюйте URL StreamRay з чату.</li><li>Вставте URL у SplitCam.</li><li>Натисніть Go Live.</li></ol>",
       "На StreamRay двічі клацніть <strong>Broadcast Now</strong>, відкрийте меню <strong>Other</strong>, виберіть <strong>OBS Broadcaster</strong> і <strong>Save and Close</strong>. StreamRay тоді публікує <strong>URL трансляції у вікні чату</strong> — скопіюйте звідти. Поле ключа SplitCam залиште <strong>порожнім</strong>; StreamRay верифікує лише через URL.",
       [("URL у чаті", "StreamRay не показує URL трансляції в полі налаштувань — він публікує його у вікні чату трансляції. Скопіюйте звідти."),
        ("Залиште поле ключа порожнім", "StreamRay не використовує окремий ключ — лише URL. Не вводьте нічого в поле ключа SplitCam."),
        _T_ETH, _T_TEST],
       [("Де URL трансляції StreamRay?", "Після ввімкнення OBS Broadcaster StreamRay публікує URL у вікні чату — скопіюйте з чату."),
        ("Чому на StreamRay немає ключа трансляції?", "StreamRay верифікує лише через URL — залиште поле ключа SplitCam порожнім."),
        ("Який бітрейт для StreamRay?", "StreamRay не вказує офіційної стелі — цільтеся в 3500–6000 Кбіт/с у 1080p і запустіть тест швидкості SplitCam, бо потік лише з URL не дає зворотного зв'язку про бітрейт."),
        ("Чи безкоштовний SplitCam для StreamRay?", "Так — безкоштовний, без водяного знака й без обмеження часу, пасує до потоку StreamRay лише з URL: вставте одне посилання — і ви наживо.")]),
    _p("xlovecam", "XLoveCam",
       "Трансляція на XLoveCam зі SplitCam — посилання RTMP і ключ",
       "Трансляція на XLoveCam з безкоштовним SplitCam — посилання RTMP і ключ, регіональні сервери, сцени й оверлеї. Без водяного знака.",
       "xlovecam, x love cam, трансляція xlovecam, xlovecam rtmp link, xlovecam ключ трансляції",
       'Як транслювати на <span class="accent">XLoveCam</span> зі SplitCam',
       "Трансляція XLoveCam",
       "Налаштування посилання RTMP + ключ для XLoveCam.",
       "XLoveCam — європейська багатомовна кам-платформа. Налаштування акаунта показують і <strong style='color:var(--text)'>посилання RTMP</strong>, і <strong style='color:var(--text)'>ключ трансляції</strong> — безкоштовний <strong style='color:var(--text)'>SplitCam</strong> бере обидва й транслює з повними сценами та оверлеями.",
       "Трансляція на XLoveCam зі SplitCam: встановіть SplitCam, зберіть сцену, на XLoveCam відкрийте <em>My Account → settings</em>, скопіюйте посилання RTMP і ключ трансляції, вставте обидва у SplitCam, почніть шоу."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте камеру + сцену.</li><li>Скопіюйте посилання RTMP + ключ з XLoveCam.</li><li>Вставте обидва у SplitCam.</li><li>Натисніть Go Live.</li></ol>",
       "На XLoveCam відкрийте <strong>My Account</strong> → <strong>settings</strong>. Налаштування показують і <strong>посилання RTMP</strong>, і <strong>ключ трансляції</strong> — скопіюйте обидва в поля URL сервера й ключа SplitCam, далі <strong>Start your show</strong> на XLoveCam.",
       [("Скопіюйте посилання І ключ", "XLoveCam дає посилання RTMP І окремий ключ трансляції — вам потрібні обидва у SplitCam, а не один."),
        ("Багатомовна аудиторія", "XLoveCam європейський і багатомовний — чіткі текстові оверлеї вашою мовою допомагають глядачам вас знайти."),
        ("Виберіть найближчий сервер", "XLoveCam пропонує регіональні сервери RTMP — Європа, ПН Америка, ПД Америка й Азія. Найближчий зменшує затримку й втрату кадрів."),
        _T_ETH],
       [("Де дані RTMP XLoveCam?", "My Account → settings — показує і посилання RTMP, і ключ."),
        ("Чи підтримує XLoveCam зовнішній кодувальник?", "Так — надає посилання RTMP і ключ, тож SplitCam працює як кодувальник."),
        ("Який бітрейт для XLoveCam?", "XLoveCam не публікує фіксованого обмеження; 3500–6000 Кбіт/с у 1080p ідеально. Вибір найближчого регіонального сервера так само важливий — зменшує втрату кадрів."),
        ("Чи безкоштовний SplitCam для XLoveCam?", "Так — безкоштовний, без водяного знака й без обмеження часу. Дотягнутися до багатомовної європейської аудиторії XLoveCam не коштує грошей на ПЗ.")]),
    _p("soulcams", "SoulCams",
       "Трансляція на SoulCams зі SplitCam — налаштування OBS",
       "Трансляція на SoulCams з безкоштовним SplitCam — налаштування OBS, сервер RTMP і ключ, мультикамерні сцени й оверлеї.",
       "soul cams, soulcams, трансляція soulcams, soulcams obs, soulcams rtmp, soulcams broadcast",
       'Як транслювати на <span class="accent">SoulCams</span> зі SplitCam',
       "Трансляція SoulCams",
       "Налаштування OBS для SoulCams.",
       "SoulCams — кам-платформа, налаштування OBS якої показує <strong style='color:var(--text)'>сервер RTMP і ключ трансляції разом</strong> в одному вікні. Вставте обидва в безкоштовний <strong style='color:var(--text)'>SplitCam</strong>, щоб транслювати з мультикамерними сценами й оверлеями.",
       "Трансляція на SoulCams зі SplitCam: встановіть SplitCam, зберіть сцену, на SoulCams натисніть Go Online → Settings → OBS, скопіюйте сервер і ключ, вставте обидва у SplitCam, Go Live."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте камеру + сцену.</li><li>Відкрийте SoulCams Settings → OBS.</li><li>Вставте сервер + ключ у SplitCam.</li><li>Натисніть Go Live.</li></ol>",
       "На SoulCams увійдіть і натисніть <strong>Go Online</strong>, далі відкрийте <strong>Settings</strong> → <strong>OBS</strong>. Вікно OBS показує <strong>сервер RTMP</strong> і <strong>ключ трансляції</strong> разом — скопіюйте обидва у SplitCam.",
       [("Сервер і ключ поруч", "SoulCams показує сервер RTMP і ключ в одному вікні OBS — беріть обидва водночас."),
        ("Спершу Go Online", "Налаштування OBS з'являються лише після натискання Go Online на SoulCams — зробіть це перед пошуком даних кодувальника."),
        ("Заблокуйте небажані регіони", "SoulCams дозволяє гео-блокування з боку моделі — виберіть, які країни не побачать стрим, перед натисканням Go Online."),
        _T_ETH, _T_TEST],
       [("Де налаштування OBS SoulCams?", "Увійдіть, натисніть Go Online, далі Settings → OBS — сервер RTMP і ключ трансляції показано разом."),
        ("Чи підтримує SoulCams зовнішній кодувальник?", "Так — налаштування OBS дають сервер RTMP і ключ, тож SplitCam працює."),
        ("Який бітрейт для SoulCams?", "SoulCams не дає офіційних цифр — цільтеся в 3500–6000 Кбіт/с у 1080p і протестуйте аплоуд, бо вікно OBS не показує підказок щодо бітрейту."),
        ("Чи безкоштовний SplitCam для SoulCams?", "Так — безкоштовний, без водяного знака й без обмеження часу, тож повні шоу на SoulCams з мультикамерними сценами й оверлеями нічого не коштують на боці кодувальника.")]),
    _p("imlive", "ImLive",
       "Використання ImLive зі SplitCam — віртуальна камера",
       "Налаштування Im Live stream з безкоштовним SplitCam — ImLive використовує живу вебкамеру (без RTMP), під'єднайте SplitCam як віртуальну камеру зі сценами.",
       "im live stream, imlive splitcam, трансляція imlive, imlive віртуальна камера, imlive webcam, im live cam",
       'Як використовувати <span class="accent">ImLive</span> зі SplitCam',
       "SplitCam на ImLive",
       "Налаштування віртуальної камери для ImLive — без RTMP.",
       "ImLive використовує живу вебкамеру в браузері — <strong style='color:var(--text)'>без RTMP і ключа трансляції</strong>. Безкоштовний <strong style='color:var(--text)'>SplitCam</strong> під'єднується як <strong style='color:var(--text)'>віртуальна камера</strong>: зберіть сцену у SplitCam, далі виберіть SplitCam камерою на ImLive.",
       "Використання SplitCam з ImLive: встановіть SplitCam, зберіть сцену з медіашарами, відкрийте ImLive й почніть відеочат, у налаштуваннях ImLive виберіть SplitCam вебкамерою й мікрофоном."
       "<ol><li>Встановіть SplitCam.</li><li>Зберіть сцену у SplitCam.</li><li>Почніть відеочат на ImLive.</li><li>Виберіть SplitCam камерою ImLive.</li><li>Почніть чат.</li></ol>",
       "Увійдіть на сайт ImLive й натисніть <strong>Start Video Chat</strong>, далі відкрийте <strong>Go To Settings</strong>, щоб отримати доступ до опцій камери й мікрофона. У налаштуваннях ImLive виберіть <strong>SplitCam</strong> вебкамерою й мікрофоном.",
       [("Ключ трансляції не потрібен", "У ImLive немає RTMP — не шукайте URL сервера чи ключ. SplitCam просто вибирається як пристрій камери."),
        ("Задайте SplitCam і мікрофоном", "Виберіть SplitCam для мікрофона на додачу до камери, щоб міксований звук і шумозаглушення теж потрапляли в ефір."),
        ("Зберіть сцену до ефіру", "ImLive показує те, що надсилає SplitCam — упорядкуйте шари перед початком чату."),
        _T_TEST],
       [("Чи використовує ImLive RTMP або ключ трансляції?", "Жодного — ImLive використовує живу вебкамеру через браузер. SplitCam під'єднується як віртуальна камера, ключа для копіювання немає."),
        ("Як вибрати SplitCam на ImLive?", "Start Video Chat → Go To Settings → виберіть SplitCam вебкамерою й мікрофоном."),
        ("Чи можу я використовувати оверлеї на ImLive?", "Так — зберіть їх у сцені SplitCam; ImLive показує зведений результат."),
        ("Чи безкоштовний SplitCam для ImLive?", "Так — безкоштовний, без водяного знака й без обмеження часу. Як віртуальна камера для ImLive він не додає витрат чи брендингу до вашого відеочату.")],
       steps=[
           ("Встановіть SplitCam", "SplitCam — безкоштовна програма для Windows і macOS. Встановіть — без водяного знака, без реєстрації. Для ImLive він працює як <strong>віртуальна камера</strong>, а не кодувальник RTMP."),
           ("Зберіть сцену у SplitCam", "Відкрийте SplitCam і скористайтеся <strong>Media Layers +</strong>, щоб додати вебкамеру плюс будь-які оверлеї, текст, фільтри чи AI-фон. Ця зведена сцена — те, що ImLive побачить як вашу камеру."),
           ("Почніть відеочат на ImLive", "Увійдіть на сайт ImLive й натисніть <strong>Start Video Chat</strong>, далі відкрийте <strong>Go To Settings</strong>, щоб отримати доступ до опцій камери й мікрофона."),
           ("Виберіть SplitCam камерою", "У налаштуваннях ImLive виберіть <strong>SplitCam</strong> вебкамерою І мікрофоном. ImLive тепер показує вашу повну сцену SplitCam, а не плоску вебкамеру."),
           ("Почніть Free Live Chat", "Натисніть <strong>Free Live Chat</strong> на ImLive, щоб вийти наживо. Щоб змінити вигляд посеред сесії, відредагуйте сцену у SplitCam — ImLive оновлюється миттєво."),
       ]),
    _p("vxlive", "VXLive",
       "Трансляція на VXLive зі SplitCam — офіційна підтримка",
       "Трансляція на VXLive (VXModels / VISIT-X) з безкоштовним SplitCam — офіційний пресет VISIT-X, сервер і ключ, сцени. Без водяного знака.",
       "vxlive, visit-x, vxmodels splitcam, трансляція vxlive, visit-x stream, vxlive rtmp",
       'Як транслювати на <span class="accent">VXLive</span> зі SplitCam',
       "Трансляція VXLive",
       "VXLive офіційно підтримує SplitCam (пресет VISIT-X).",
       "VXLive (VXModels / VISIT-X) — кам-платформа з німецького ринку, і одна з небагатьох, що <strong style='color:var(--text)'>офіційно підтримують SplitCam за назвою</strong>. VXModels має окрему статтю довідки про під'єднання <strong style='color:var(--text)'>SplitCam</strong> до VXLive, а SplitCam пропонує VISIT-X як готовий пресет каналу.",
       "Трансляція на VXLive зі SplitCam: встановіть SplitCam, зберіть сцену, на VXLive виберіть «Stream with third-party software», скопіюйте URL сервера й ключ, у SplitCam виберіть пресет VISIT-X і вставте, Go Live у SplitCam, далі GO ONLINE на VXLive."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте камеру + сцену.</li><li>Отримайте URL сервера + ключ з VXLive.</li><li>Виберіть пресет VISIT-X у SplitCam, вставте.</li><li>Go Live, далі GO ONLINE на VXLive.</li></ol>",
       "На VXLive виберіть <strong>Stream with third-party software</strong> й опцію <strong>OBS, SplitCam або XSplit</strong>. VXLive дає <strong>URL сервера</strong> і <strong>ключ трансляції</strong>. У SplitCam виберіть <strong>VISIT-X</strong> платформою стримінгу, вставте обидва, натисніть <strong>Go Live</strong> у SplitCam, далі <strong>GO ONLINE</strong> на VXLive.",
       [("VISIT-X — інтегрований пресет", "Не вводьте сирий URL RTMP — у SplitCam VISIT-X є у списку платформ; просто виберіть і вставте URL сервера й ключ."),
        ("Двоетапний go-live", "На VXLive спершу натисніть Go Live у SplitCam, далі GO ONLINE на VXLive — обидва, у такому порядку."),
        ("Німецький ринок", "Аудиторія VXLive переважно німецькомовна — німецькі текстові оверлеї чи заголовки допомагають порозумітися з глядачами."),
        _T_ETH],
       [("Чи підтримує VXLive SplitCam офіційно?", "Так — VXModels (VXLive) веде окрему офіційну статтю довідки про налаштування SplitCam і вказує SplitCam поряд з OBS і XSplit як підтримуване ПЗ для трансляцій."),
        ("Як під'єднати SplitCam до VXLive?", "На VXLive виберіть «Stream with third-party software», далі у SplitCam виберіть пресет VISIT-X і вставте URL сервера й ключ трансляції, що дає VXLive."),
        ("Я наживо у SplitCam чи VXLive?", "В обох — спершу Go Live у SplitCam, далі GO ONLINE на VXLive."),
        ("Чому VXModels рекомендує SplitCam?", "Офіційна стаття довідки VXModels рекомендує SplitCam саме для усунення артефактів зображення вебкамери й пікселізації та стабілізації з'єднання — не просто як загальний кодувальник.")]),
    _p("virtwish", "VirtWish",
       "Трансляція на VirtWish зі SplitCam — URL трансляції і ключ",
       "Трансляція на VirtWish з безкоштовним SplitCam — розділ OBS Profile → Start Broadcast, URL трансляції і ключ, сцени й оверлеї.",
       "virtwish, трансляція virtwish, virtwish broadcasting software, virtwish rtmp, virtwish ключ трансляції, virtwish obs",
       'Як транслювати на <span class="accent">VirtWish</span> зі SplitCam',
       "Трансляція VirtWish",
       "Налаштування URL трансляції + ключ для VirtWish.",
       "VirtWish — інтерактивна кам-платформа. Налаштування трансляції дають вам <strong style='color:var(--text)'>окремі URL трансляції й ключ</strong> у розділі OBS — безкоштовний <strong style='color:var(--text)'>SplitCam</strong> бере обидва й веде шоу зі сценами й оверлеями.",
       "Трансляція на VirtWish зі SplitCam: встановіть SplitCam, зберіть сцену, на VirtWish відкрийте <em>Profile → Start Broadcast</em> до розділу OBS, скопіюйте посилання й ключ, вставте обидва у SplitCam, Go Live."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте камеру + сцену.</li><li>Отримайте URL + ключ з VirtWish.</li><li>Вставте обидва у SplitCam.</li><li>Натисніть Go Live.</li></ol>",
       "На VirtWish натисніть піктограму вгорі праворуч → <strong>Profile</strong> → <strong>Start Broadcast</strong>, далі <strong>Start Broadcast</strong> ще раз, щоб дійти до розділу OBS. <strong>Скопіюйте посилання з першого рядка</strong> в поле Stream URL SplitCam, а окремий <strong>Stream Key</strong> — у поле ключа.",
       [("Посилання в першому рядку", "Розділ OBS VirtWish ставить URL трансляції в перший рядок — скопіюйте його в Stream URL SplitCam, далі окремий ключ."),
        ("Два кліки Start Broadcast", "Ви клацаєте Start Broadcast двічі на VirtWish, щоб дійти до розділу OBS — це нормально, не баг."),
        _T_ETH, _T_TEST],
       [("Де дані RTMP VirtWish?", "Піктограма вгорі праворуч → Profile → Start Broadcast двічі → розділ OBS показує посилання й ключ трансляції."),
        ("Чи підтримує VirtWish зовнішній кодувальник?", "Так — розділ OBS надає URL трансляції й ключ, тож SplitCam працює."),
        ("Який бітрейт для VirtWish?", "VirtWish не публікує офіційної стелі; 3500–6000 Кбіт/с у 1080p безпечно. Узгодьте роздільну здатність SplitCam із заданою у VirtWish, щоб уникнути перемасштабування."),
        ("Чи безкоштовний SplitCam для VirtWish?", "Так — безкоштовний, без водяного знака й без обмеження часу. Налаштування URL-і-ключ VirtWish займає лише потрібні кілька хвилин.")]),
    _p("xmodels", "XModels",
       "Трансляція на XModels зі SplitCam — безкоштовний посібник",
       "Трансляція на XModels з безкоштовним SplitCam — опція зовнішнього кодувальника в налаштуваннях акаунта моделі, ключ RTMP, сцени й оверлеї.",
       "xmodels, трансляція xmodels, xmodels broadcasting software, xmodels rtmp, xmodels зовнішній кодувальник",
       'Як транслювати на <span class="accent">XModels</span> зі SplitCam',
       "Трансляція XModels",
       "Налаштування зовнішнього кодувальника для трансляції XModels.",
       "XModels — платформа кам-стримінгу з вбудованою <strong style='color:var(--text)'>опцією зовнішнього кодувальника</strong> в налаштуваннях акаунта моделі. Безкоштовний <strong style='color:var(--text)'>SplitCam</strong> транслює там з мультикамерними сценами, оверлеями й фільтрами замість однієї плоскої камери.",
       "Трансляція на XModels зі SplitCam: встановіть SplitCam, зберіть сцену, в акаунті моделі XModels увімкніть опцію зовнішнього кодувальника, скопіюйте URL сервера й ключ трансляції, вставте у SplitCam, Go Live."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте камеру + сцену.</li><li>Увімкніть зовнішній кодувальник у налаштуваннях XModels.</li><li>Вставте URL сервера + ключ у SplitCam.</li><li>Натисніть Go Live.</li></ol>",
       "У <strong>налаштуваннях акаунта моделі</strong> XModels увімкніть опцію <strong>трансляції через зовнішній кодувальник</strong>. XModels надає <strong>ключ трансляції</strong> — скопіюйте його у SplitCam. Якщо опції немає там, де очікуєте, підтримка XModels — через чат FAQ на сайті та <strong>info@xmodels.com</strong>; відео вище теж це показує.",
       [("Це в налаштуваннях акаунта", "XModels розміщує опцію зовнішнього кодувальника в налаштуваннях акаунта моделі, а не на окремому екрані трансляції."),
        ("Підтримка: чат + email", "У XModels немає великого публічного центру довідки — чат FAQ на сайті та info@xmodels.com — офіційні канали підтримки."),
        ("Складайте оверлеї у SplitCam", "Цілі чайових, ім'я та хендли соцмереж додайте як шари сцени — базова камера XModels їх не додасть."),
        _T_ETH],
       [("Чи підтримує XModels зовнішній кодувальник?", "Так — налаштування акаунта моделі мають опцію трансляції зовнішнім кодувальником, що надає ключ трансляції, тож SplitCam працює."),
        ("Де отримати допомогу XModels?", "Підтримка XModels — через чат FAQ на сайті та email info@xmodels.com — великого публічного центру довідки немає."),
        ("Який бітрейт для XModels?", "XModels не документує офіційних цифр — використовуйте 3500–6000 Кбіт/с у 1080p і запустіть тест швидкості SplitCam, бо підтримка XModels лише через чат і email."),
        ("Чи безкоштовний SplitCam для XModels?", "Так — безкоштовний, без водяного знака й без обмеження часу, тож трансляція в європейську мережу XModels не додає витрат на ПЗ.")]),
    _p("flirt4free", "Flirt4Free",
       "Трансляція на Flirt for Free cam зі SplitCam — безкоштовний посібник",
       "Трансляція на Flirt for Free cam з безкоштовним SplitCam — External Broadcast Form, RTMP URL і Stream Name, сцени й оверлеї.",
       "flirt for free cam, flirt 4 free cam, flirt4free, трансляція flirt4free, flirt4free external broadcast, flirt4free rtmp",
       'Як транслювати на <span class="accent">Flirt4Free</span> зі SplitCam',
       "Трансляція Flirt4Free",
       "Налаштування External Broadcast Form для Flirt4Free.",
       "Flirt4Free — одна з найстаріших кам-платформ, в ефірі з 90-х. Вона офіційно підтримує зовнішню трансляцію через <strong style='color:var(--text)'>External Broadcast Form</strong> — безкоштовний <strong style='color:var(--text)'>SplitCam</strong> надсилає стрим, а форма задає роздільну здатність і бітрейт.",
       "Трансляція на Flirt4Free зі SplitCam: встановіть SplitCam, зберіть сцену, відкрийте External Broadcast Form Flirt4Free, скопіюйте RTMP URL і Stream Name та задайте роздільну здатність/бітрейт, вставте у SplitCam, Go Live."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте камеру + сцену.</li><li>Відкрийте External Broadcast Form Flirt4Free.</li><li>Вставте RTMP URL + Stream Name у SplitCam.</li><li>Натисніть Go Live.</li></ol>",
       "У зоні моделі Flirt4Free відкрийте <strong>External Broadcast Form</strong>. На відміну від більшості кам-сайтів, Flirt4Free дає <strong>RTMP URL</strong> і <strong>Stream Name</strong> (а не «ключ»), плюс поля роздільної здатності й бітрейту, які ви заповнюєте в самій формі. Скопіюйте URL і Stream Name у поля сервера й ключа SplitCam.",
       [("Це Stream Name, а не ключ", "Flirt4Free називає свої дані Stream Name. Ви вставляєте його в поле ключа SplitCam — функція та сама."),
        ("Задайте роздільну здатність/бітрейт у формі", "External Broadcast Form Flirt4Free має власні поля роздільної здатності й бітрейту — узгодьте їх із налаштуваннями SplitCam, щоб зображення не перемасштабовувалось."),
        ("Платформа з історією", "Flirt4Free працює з 90-х — її інструменти для моделей зрілі, а External Broadcast Form — задокументована їх частина."),
        _T_ETH],
       [("Чи підтримує Flirt4Free зовнішній кодувальник?", "Так — офіційно, через External Broadcast Form, що надає RTMP URL і Stream Name. SplitCam працює як кодувальник."),
        ("Де отримати дані RTMP Flirt4Free?", "З External Broadcast Form у зоні моделі — показує RTMP URL, Stream Name і поля роздільної здатності/бітрейту."),
        ("Який бітрейт для Flirt4Free?", "3500–6000 Кбіт/с у 1080p — задайте однакові значення в External Broadcast Form і у SplitCam."),
        ("Чи безкоштовний SplitCam для Flirt4Free?", "Так — безкоштовний, без водяного знака й без обмеження часу, пасує до історичної платформи на кшталт Flirt4Free, де шоу бувають довгими.")]),
    _p("mfc-alerts", "MFC Alerts",
       "Додавання MFC Alerts до трансляції зі SplitCam",
       "Показуйте анімовані сповіщення про чайові в трансляції MyFreeCams — URL mfcalerts.com як шар Browser у безкоштовному SplitCam, над вебкамерою.",
       "mfc alerts, myfreecams alerts, додати mfc alerts, mfcalerts splitcam, myfreecams tip alerts, myfreecams alerts overlay",
       'Як додати <span class="accent">MFC Alerts</span> до трансляції',
       "Додати MFC Alerts",
       "Показуйте анімовані сповіщення про чайові в трансляції MyFreeCams.",
       "MFC Alerts показує анімовані ефекти у вашій трансляції MyFreeCams щоразу, коли глядач надсилає чайові. Він працює як <strong style='color:var(--text)'>шар Browser</strong> усередині безкоштовного <strong style='color:var(--text)'>SplitCam</strong> — налаштуйте раз, і чайові викликають реакції на екрані в реальному часі.",
       "Додавання MFC Alerts зі SplitCam: встановіть SplitCam, додайте вебкамеру, відкрийте вкладку Browser і завантажте mfcalerts.com, скопіюйте свій URL сповіщень, додайте як шар Browser над вебкамерою, далі перевірте тестовими чайовими."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте вебкамеру.</li><li>Отримайте URL на mfcalerts.com.</li><li>Додайте як шар Browser над вебкамерою.</li><li>Надішліть тестові чайові.</li></ol>",
       "У SplitCam відкрийте вкладку <strong>Browser</strong> і перейдіть на <strong>www.mfcalerts.com</strong>. Увійдіть або зареєструйтеся. Скористайтеся <strong>Copy to clipboard</strong>, щоб скопіювати свій приватний URL сповіщень. Вставте URL у вікно Browser SplitCam і натисніть <strong>Add</strong>. Далі впорядкуйте список джерел, щоб <strong>MFC Alerts був над вебкамерою</strong> (меню з 3 крапок → Move Up).",
       [("MFC Alerts має бути над вебкамерою", "Найпоширеніша помилка: якщо шар MFC Alerts під вебкамерою в списку джерел, ефект прихований. Пересуньте його нагору."),
        ("Потрібен акаунт mfcalerts.com", "URL сповіщень приватний — спершу зареєструйтеся на mfcalerts.com, якщо немає акаунта."),
        ("Надішліть тестові чайові до ефіру", "Скористайтеся Settings → Send test tip, щоб переконатися, що оверлей працює — не відкривайте помилку посеред шоу."),
        _T_ETH],
       [("Що таке MFC Alerts?", "Система сповіщень для MyFreeCams, що показує відеоефекти у вашій трансляції, коли глядачі надсилають чайові — додається як оверлей Browser у SplitCam."),
        ("Чому мої MFC Alerts не показуються?", "Майже завжди це порядок шарів — шар Browser MFC Alerts має бути над вебкамерою в списку джерел SplitCam."),
        ("Чи потрібен акаунт для MFC Alerts?", "Так — зареєструйтеся на mfcalerts.com, щоб отримати свій приватний URL сповіщень."),
        ("Чи безкоштовний SplitCam для цього?", "Так — SplitCam безкоштовний, без водяного знака й без обмеження часу, а браузерний оверлей MFC Alerts працює всередині нього без додаткових витрат.")],
       steps=[
           ("Встановіть SplitCam і додайте вебкамеру", "Встановіть безкоштовний SplitCam для Windows чи macOS, далі додайте <strong>вебкамеру</strong> джерелом. MFC Alerts лягає шаром над цією камерою."),
           ("Відкрийте вкладку Browser і перейдіть на mfcalerts.com", "У SplitCam відкрийте вкладку <strong>Browser</strong> і перейдіть на <strong>www.mfcalerts.com</strong>. Увійдіть або зареєструйтеся, якщо ще немає акаунта mfcalerts.com."),
           ("Скопіюйте свій URL сповіщень", "На mfcalerts.com скористайтеся <strong>Copy to clipboard</strong>, щоб скопіювати свій приватний URL сповіщень — це сторінка, що рендерить анімації чайових."),
           ("Додайте URL як шар Browser — над вебкамерою", "Вставте URL у вікно Browser SplitCam і натисніть <strong>Add</strong>. Далі впорядкуйте список джерел, щоб <strong>MFC Alerts був над вебкамерою</strong> (меню з 3 крапок → Move Up). Якщо нижче, ефект прихований."),
           ("Перевірте тестовими чайовими", "Відкрийте <strong>Settings → Send test tip</strong> і переконайтеся, що ефект сповіщення з'являється над камерою. Далі транслюйте звичайно на MyFreeCams — справжні чайові тепер викликають анімації."),
       ]),
    _p("lovense", "Lovense",
       "Додавання іграшок Lovense до трансляції зі SplitCam",
       "Під'єднайте інтерактивні іграшки Lovense до кам-трансляції з безкоштовним SplitCam — Lovense SplitCam Toolset, сповіщення про чайові на екрані, реакції.",
       "додати lovense до трансляції, lovense cam stream, lovense splitcam, lovense splitcam toolset, lovense interactive toy streaming",
       'Як додати <span class="accent">іграшки Lovense</span> до трансляції',
       "Додати іграшки Lovense",
       "Під'єднайте інтерактивні іграшки Lovense до кам-трансляції.",
       "Ви ведете кам-трансляцію через безкоштовний <strong style='color:var(--text)'>SplitCam</strong> і парите іграшку <strong style='color:var(--text)'>Lovense</strong>, що реагує на токени. Lovense документує офіційний <strong style='color:var(--text)'>Lovense SplitCam Toolset</strong>, а SplitCam пропонує офіційний плагін Lovense — інтеграція підтримується з обох боків.",
       "Щоб додати іграшки Lovense до трансляції: встановіть SplitCam і ПЗ Lovense, спаруйте іграшку, під'єднайте Lovense до кам-платформи, додайте статус Lovense як шар Browser у SplitCam, далі транслюйте звичайно."
       "<ol><li>Встановіть SplitCam.</li><li>Встановіть ПЗ Lovense і спаруйте іграшку.</li><li>Під'єднайте Lovense до свого кам-сайту.</li><li>Додайте оверлей Lovense у SplitCam.</li><li>Натисніть Go Live.</li></ol>",
       "Встановіть Lovense Connect / Lovense Stream (офіційний десктопний застосунок). Увімкніть іграшку й спаруйте через Bluetooth, щоб застосунок показав з'єднання. У застосунку Lovense під'єднайте свій кам-акаунт, щоб іграшка реагувала на токени / чайові глядачів. Lovense надає URL оверлея / віджета — додайте як шар <strong>Browser</strong> у сцені SplitCam.",
       [("Використовуйте офіційний Lovense SplitCam Toolset", "Lovense публікує окремий toolset для SplitCam з власним посібником встановлення — додає оверлеї активності іграшки й сповіщення про чайові, зроблені для SplitCam."),
        ("Оновіть Lovense Cam Extension", "Toolset потребує найновішого Lovense Cam Extension (30.1.4 або новіше) — оновіть до ефіру."),
        ("Тримайте іграшку зарядженою", "Низький заряд посеред шоу ламає інтерактивну частину — зарядіть повністю до ефіру."),
        ("Перевірте реакцію на токени", "Надішліть невеликі тестові чайові, щоб переконатися, що іграшка реагує, перед відкриттям кімнати."),
        ("Перевірте вимоги до версії", "Lovense SplitCam Toolset потребує SplitCam 10.4.5 або новіше. Lovense Cam Extension офіційно охоплює Chaturbate, Stripchat, BongaCams, MyFreeCams і CamSoda — для інших сайтів використовуйте інтеграцію Generic URL Lovense.")],
       [("Чи підтримує Lovense SplitCam офіційно?", "Так — Lovense документує офіційний «Lovense SplitCam Toolset» з власним посібником встановлення, а SplitCam пропонує офіційний плагін Lovense. Інтеграція підтримується з обох боків."),
        ("Чи під'єднується іграшка прямо до SplitCam?", "Ні — іграшка парується із застосунком Lovense; SplitCam показує оверлей Lovense і транслює камеру."),
        ("Які кам-сайти підтримують Lovense?", "Lovense Cam Extension офіційно підтримує Chaturbate, Stripchat, BongaCams, MyFreeCams і CamSoda, з різною підтримкою інших — перевірте актуальний список у застосунку Lovense."),
        ("Чи можу я показувати останні чайові на екрані?", "Так — додайте URL віджета Lovense як шар Browser у SplitCam.")],
       steps=[
           ("Встановіть SplitCam", "SplitCam — безкоштовна програма для трансляцій на Windows і macOS — кодувальник, що надсилає ваше відео на кам-платформу. Встановіть; без водяного знака."),
           ("Встановіть ПЗ Lovense і спаруйте іграшку", "Встановіть Lovense Connect / Lovense Stream (офіційний десктопний застосунок). Увімкніть іграшку й спаруйте через Bluetooth, щоб застосунок показав з'єднання."),
           ("Під'єднайте Lovense до кам-платформи", "У застосунку Lovense під'єднайте свій кам-акаунт, щоб іграшка реагувала на токени / чайові глядачів. Підтримується більшість великих кам-платформ."),
           ("Додайте оверлей Lovense у SplitCam", "Lovense надає URL оверлея / віджета. Додайте як шар <strong>Browser</strong> у сцені SplitCam, щоб глядачі бачили статус іграшки й останні чайові на екрані."),
           ("Зберіть сцену й Go Live", "Додайте камеру й інші оверлеї, вставте ключ RTMP кам-платформи у SplitCam і натисніть <strong>Go Live</strong>. Іграшка реагує на чайові в реальному часі."),
       ]),
    _p("multistream-cams", "Кілька кам-сайтів",
       "Трансляція на кілька кам-сайтів одночасно зі SplitCam",
       "Транслюйте на MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat та інші одночасно з безкоштовним мультистримом SplitCam. Один клік, без водяного знака.",
       "трансляція на кілька кам-сайтів, multistream cam sites, трансляція chaturbate і bongacams одночасно, програма мультистриму cam",
       'Як транслювати на <span class="accent">кілька кам-сайтів</span> одночасно',
       "Мультистрим cam",
       "Транслюйте на кілька кам-сайтів одночасно.",
       "Безкоштовний <strong style='color:var(--text)'>SplitCam</strong> може транслювати одне кодування на <strong style='color:var(--text)'>кілька кам-сайтів одночасно</strong> — MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat та інші. Без водяного знака, один клік.",
       "Щоб транслювати на кілька кам-сайтів одночасно: встановіть SplitCam, зберіть сцену, отримайте URL сервера RTMP і ключ трансляції кожного кам-сайту, додайте всі в налаштування мультистриму SplitCam, натисніть Go Live один раз."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте камеру + сцену.</li><li>Отримайте ключі RTMP з кожного кам-сайту.</li><li>Додайте всі ключі в мультистрим SplitCam.</li><li>Натисніть Go Live один раз.</li></ol>",
       "На кожній кам-платформі увімкніть зовнішню / RTMP трансляцію й скопіюйте <strong>URL сервера</strong> та <strong>ключ трансляції</strong>. У SplitCam відкрийте <strong>Stream Settings</strong> і додайте кожен кам-сайт як кастомну ціль RTMP — вставте URL сервера й ключ. Позначте всі, де хочете бути наживо. Натисніть <strong>Go Live</strong>.",
       [("Стежте за своїм аплоудом", "Мультистрим множить навантаження на аплоуд. Кожна ціль використовує власний бітрейт — переконайтеся, що канал витримає суму."),
        ("Перевірте правила платформ", "Деякі кам-сайти забороняють одночасну трансляцію деінде — перевірте перед мультистримом."),
        ("Кабель — тут падати не можна", "Мультистрим множить навантаження на аплоуд, тож один обрив wi-fi може скинути всі цілі водночас. Кабель тут не опція."),
        ("Стежте за монітором стану", "SplitCam показує статус кожної цілі — відключіть один сайт, якщо аплоуд не тягне.")],
       [("Чи безкоштовний мультистрим SplitCam?", "Так — мультистрим вбудований і безкоштовний, без плати за ціль, без водяного знака."),
        ("На скільки кам-сайтів я можу транслювати одночасно?", "На стільки, скільки витримає пропускна здатність аплоуду — кожна ціль використовує власний бітрейт."),
        ("Чи використовує він хмарний relay?", "Ні — SplitCam надсилає стрим peer-to-peer прямо з ПК до ingest кожної платформи."),
        ("Чи сповільнює мультистрим мій ПК?", "Кодування робиться раз і використовується повторно; апаратне кодування тримає навантаження на CPU низьким. Пропускна здатність аплоуду — справжнє обмеження.")],
       steps=[
           ("Встановіть SplitCam", "SplitCam — безкоштовна програма для трансляцій на Windows і macOS із вбудованим мультистримом. Встановіть — без водяного знака, без реєстрації."),
           ("Налаштуйте камеру й сцену", "Відкрийте SplitCam, додайте вебкамеру й зберіть сцену з оверлеями й фільтрами. Одна сцена живить кожну ціль."),
           ("Отримайте ключі RTMP з кожного кам-сайту", "На кожній кам-платформі увімкніть зовнішню / RTMP трансляцію й скопіюйте <strong>URL сервера</strong> та <strong>ключ трансляції</strong>. Повторіть для кожного сайту, на який хочете транслювати — точний шлях дивіться в посібниках відповідних платформ."),
           ("Додайте кожну ціль у SplitCam", "Відкрийте <strong>Stream Settings</strong> і додайте кожен кам-сайт як кастомну ціль RTMP — вставте URL сервера й ключ. Позначте всі, де хочете бути наживо."),
           ("Натисніть Go Live один раз", "Натисніть <strong>Go Live</strong>. SplitCam надсилає стрим на кожен вибраний кам-сайт одночасно, peer-to-peer, з одного кодування — без додаткових витрат."),
       ]),
    _p("livejasmin", "LiveJasmin",
       "Трансляція на LiveJasmin зі SplitCam — Зовнішній кодувальник HD",
       "Трансляція на LiveJasmin з безкоштовним SplitCam — зовнішній кодувальник у Model Center, налаштування HD 1080p, мультикамерні сцени й оверлеї. Без водяного знака, без реєстрації.",
       "трансляція livejasmin, livejasmin obs, livejasmin зовнішній кодувальник, livejasmin rtmp, livejasmin stream key, livejasmin налаштування моделі",
       'Як транслювати на <span class="accent">LiveJasmin</span> зі SplitCam',
       "Трансляція LiveJasmin",
       "Налаштування зовнішнього кодувальника для Model Center LiveJasmin, який працює лише в HD.",
       "LiveJasmin — флагман Docler Holding, одна з найбільших кам-мереж у світі й платформа, що працює виключно у HD. Її основний нададач — фірмовий клієнт <strong>JasminCAM</strong>, але Model Center також надає стандартний шлях <strong>External Encoder</strong>, до якого підключається безкоштовний <strong style='color:var(--text)'>SplitCam</strong> — дозволяючи транслювати мультикамерні сцени, beauty-фільтри й оверлеї в тій самій HD-трансляції.",
       "Трансляція на LiveJasmin зі SplitCam: встановіть SplitCam, зберіть HD-сцену, у Model Center відкрийте <em>Settings → Broadcast → External Encoder</em>, скопіюйте URL сервера й ключ трансляції, вставте у SplitCam, Go Live."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте камеру + HD-сцену.</li><li>Отримайте URL і ключ трансляції з Model Center.</li><li>Вставте у SplitCam.</li><li>Натисніть Go Live.</li></ol>",
       "Увійдіть на <strong>modelcenter.livejasmin.com</strong>, відкрийте <strong>Settings → Broadcast → External Encoder</strong>. Model Center покаже <strong>URL сервера</strong> та <strong>ключ трансляції</strong>, прив'язані до вашого акаунта — скопіюйте обидва в кастомні поля RTMP у SplitCam. <strong>Зверніть увагу:</strong> нові акаунти спершу мають бути затверджені (48–72 години), перш ніж з'явиться опція зовнішнього кодувальника, а платформа примусово вимагає вивід лише у HD.",
       [("HD або вилітаєш з рейтингу", "LiveJasmin лише HD — усе нижче 1280×720 ризикує показуватись тільки на гірше оплачуваних списках, усе нижче 1080p втрачає право на «Premium». Цільтесь у 1920×1080 при 30 fps, 4000–6000 Кбіт/с."),
        ("JasminCAM vs зовнішній кодувальник", "Фірмовий клієнт Docler — JasminCAM — дає найчистішу відповідність HD-вимогам, але зовнішні кодувальники (OBS, SplitCam, vMix) офіційно підтримуються після затвердження акаунта — вони відкривають мультикамерні сцени й оверлеї, яких JasminCAM не вміє."),
        ("Free chat ≠ Private show", "Free chat — лише прев'ю, без оголеності. Заробляєте у Private та Gold show. Сплануйте сцену так, щоб вона виглядала сильно як в одязі, ТАК і в режимі шоу."),
        _T_ETH],
       [("Чи офіційно підтримує LiveJasmin зовнішні кодувальники на кшталт SplitCam?", "Так — Model Center має опцію External Encoder у Settings → Broadcast. JasminCAM — рекомендований клієнт, але OBS, SplitCam та інші RTMP-кодувальники прямо вказані як підтримувані після затвердження вашого акаунта моделі."),
        ("Де взяти мій ключ трансляції LiveJasmin?", "Усередині Model Center: Settings → Broadcast → External Encoder. Там з'являються і URL сервера, і унікальний ключ трансляції — скопіюйте обидва в кастомні поля RTMP у SplitCam. Ключ прив'язаний до вашого акаунта; поводьтеся з ним як із паролем."),
        ("Який бітрейт ставити для LiveJasmin?", "LiveJasmin — лише HD. Цільтесь у 1920×1080 при 30 fps, 4000–6000 Кбіт/с з інтервалом ключового кадру 2 секунди. Усе помітно нижче втрачає мітку Premium і випадає з рейтингу."),
        ("Чи безкоштовний SplitCam для LiveJasmin?", "Так — SplitCam безкоштовний, без водяного знака й без обмеження часу. Єдина «ціна» — це дотягнути HD-вимоги LiveJasmin, з чим SplitCam справляється нативно через композицію сцени у 1080p і beauty-фільтри.")],
       steps=[
           ("Завантажте та встановіть SplitCam", "SplitCam — безкоштовне ПЗ для трансляцій на Windows і macOS, без реєстрації, без картки, без водяного знака. Це кодувальник, який надсилає ваше HD-відео в LiveJasmin."),
           ("Зберіть HD-сцену", "Відкрийте SplitCam і додайте вебкамеру в режимі 1080p. Накладіть оверлеї, текст, другу камеру або телефон, beauty-фільтри чи AI-фон — LiveJasmin вимагає HD-якості, і ваша зібрана сцена має виглядати преміально як у free chat, ТАК і у приватних шоу."),
           ("Отримайте URL і ключ трансляції LiveJasmin", "Увійдіть на <strong>modelcenter.livejasmin.com</strong> (ваш акаунт спершу має бути затверджений — зазвичай 48–72 години після реєстрації). Відкрийте <strong>Settings → Broadcast → External Encoder</strong>. Сторінка покаже <strong>URL сервера</strong> й унікальний <strong>ключ трансляції</strong>. Скопіюйте обидва."),
           ("Підключіть SplitCam до LiveJasmin", "У SplitCam відкрийте <strong>Stream Settings</strong>, вставте URL сервера LiveJasmin і ключ трансляції у кастомні поля RTMP. Поставте бітрейт 4000–6000 Кбіт/с при 1920×1080, 30 fps, ключовий кадр кожні 2 секунди. Спершу запустіть вбудований тест швидкості — HD-стріми вимогливі."),
           ("Натисніть Go Live", "Натисніть <strong>Go Live</strong> у SplitCam, потім перейдіть онлайн у Model Center LiveJasmin. Приблизно за 10 секунд ваш HD-сигнал доходить до мережі LiveJasmin. Наступні трансляції — один клік: відкрити SplitCam, Go Live, потім вийти онлайн на LiveJasmin."),
       ]),
    _p("myfreecams", "MyFreeCams",
       "Трансляція на MyFreeCams (MFC) зі SplitCam — обхід Model Web Broadcaster",
       "Трансляція на MyFreeCams з безкоштовним SplitCam — зовнішній broadcaster у Model Admin, токенова економіка MFC, мультикамерні сцени, оверлеї. Без вотермарки, без реєстрації.",
       "myfreecams трансляція, mfc зовнішній broadcaster, myfreecams obs, mfc rtmp, mfc ключ трансляції, model admin, mfc токен",
       'Як транслювати на <span class="accent">MyFreeCams</span> зі SplitCam',
       "Трансляція на MyFreeCams",
       "Налаштування зовнішнього broadcaster для токенового Model Admin у MFC.",
       "MFC — одна з найстаріших cam-платформ: чиста токенова економіка, без виснажливого схвалення моделей і з лояльною базою Premium-учасників. Стандартний <strong>Model Web Broadcaster</strong> — це однокамерний інструмент у браузері, але <strong>Model Admin</strong> відкриває й опцію <strong>External Broadcaster</strong>, до якої підключається безкоштовний <strong style='color:var(--text)'>SplitCam</strong> — розблоковуючи мультикамерні сцени, оверлеї та фільтри в тій же токеновій трансляції.",
       "Трансляція на MyFreeCams зі SplitCam: встановіть, зберіть сцену, у Model Admin → Broadcaster перемкніть Web на <em>External Broadcaster</em>, скопіюйте URL сервера та ключ, вставте у SplitCam, Go Live."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте камеру й оверлеї.</li><li>Отримайте URL і ключ із Model Admin.</li><li>Вставте у SplitCam.</li><li>Натисніть Go Live.</li></ol>",
       "Увійдіть на MyFreeCams, відкрийте <strong>Model Admin → Broadcaster</strong> і перемкніть із <strong>Web</strong> на <strong>External Broadcaster</strong>. Сторінка покаже URL сервера (rtmp://publish.myfreecams.com…) та ключ трансляції, прив'язані до акаунта моделі. Скопіюйте обидва в кастомні поля RTMP у SplitCam.",
       [("MFC — це чисті чайові в токенах, не підписки", "Основа заробітку — чайові у free chat. Premium-учасники можуть піти в private, але хліб із маслом — це токени в публічному чаті. Будуйте сцену під постійне підштовхування до тіпів, а не під короткі «шоу за гроші»."),
        ("Web vs External Broadcaster", "Стандартний Web Broadcaster — це одна камера в браузері, швидко, але бідно. External Broadcaster через SplitCam, OBS чи vMix розблоковує мультикамерні сцени, оверлеї та beauty-фільтри в тій же токеновій трансляції."),
        ("Інтеграція з MFC Alerts", "Додайте URL із mfcalerts.com як Browser-шар над камерою у SplitCam — отримуєте анімовані алерти чайових прямо в кадрі, без перемикання вікон і додаткових плагінів."),
        _T_ETH],
       [("Чи офіційно MFC підтримує зовнішні broadcaster-и на кшталт SplitCam?", "Так — Model Admin має опцію External Broadcaster зі стандартним URL сервера RTMP і ключем трансляції. OBS, SplitCam, vMix — усе працює після простого перемикання Web → External Broadcaster."),
        ("Де знайти ключ трансляції MFC?", "Model Admin → Broadcaster → перемкніть на External Broadcaster. URL сервера й ключ трансляції з'являться відразу на тій же сторінці. Скопіюйте обидва в кастомні поля RTMP у SplitCam — ключ прив'язаний до вашого акаунта, тримайте як пароль."),
        ("Який бітрейт для MFC?", "До приблизно 6000 Кбіт/с із ключовим кадром кожні 2 секунди. Виштовхуйте 1920×1080 при 30 fps та 3500–6000 Кбіт/с — реальний ліміт — ваш аплоад, а не MFC. Спершу запустіть вбудований тест швидкості SplitCam."),
        ("Чи безкоштовний SplitCam для MFC?", "Так — SplitCam безкоштовний, без вотермарки, без обмеження часу. Опція External Broadcaster на боці MFC також безкоштовна — це стандартний RTMP, без додаткових платежів.")],
       steps=[
           ("Завантажте та встановіть SplitCam", "SplitCam — безкоштовне ПЗ для прямих трансляцій для Windows і macOS — без реєстрації, без картки, без вотермарки. Це енкодер, який надсилає ваше відео на MyFreeCams."),
           ("Зберіть сцену", "Відкрийте SplitCam і додайте камеру, оверлеї, другу камеру або телефон, beauty-фільтри чи AI-фон. Додайте URL із <strong>mfcalerts.com</strong> як Browser-шар над камерою — отримуєте анімовані алерти чайових прямо в трансляції."),
           ("Отримайте URL і ключ трансляції MFC", "Увійдіть на MyFreeCams, відкрийте <strong>Model Admin → Broadcaster</strong> і перемкніть із <strong>Web</strong> на <strong>External Broadcaster</strong>. Скопіюйте URL сервера (rtmp://publish.myfreecams.com…) та ключ трансляції."),
           ("Підключіть SplitCam до MFC", "У SplitCam відкрийте <strong>Stream Settings</strong>, вставте URL і ключ MFC у кастомні поля RTMP. Поставте бітрейт 3500–6000 Кбіт/с при 1920×1080, 30 fps, ключовий кадр кожні 2 секунди. Спершу запустіть вбудований тест швидкості."),
           ("Натисніть Go Live", "Натисніть <strong>Go Live</strong> у SplitCam — приблизно за 10 секунд ваш сигнал доходить до MFC. Наступні трансляції — один клік: відкрити SplitCam, Go Live."),
       ]),
    _p("cherry-tv", "Cherry.tv",
       "Трансляція на Cherry.tv зі SplitCam — зовнішній енкодер, дружній до Web3",
       "Трансляція на Cherry.tv з безкоштовним SplitCam — зовнішній енкодер у Streamer Dashboard, cam-платформа, дружня до крипти, мультикамерні сцени. Без вотермарки, без реєстрації.",
       "cherry tv трансляція, cherry.tv obs, cherry tv зовнішній енкодер, cherry.tv rtmp, cherry.tv ключ трансляції, cherry tv streamer, web3 cam",
       'Як транслювати на <span class="accent">Cherry.tv</span> зі SplitCam',
       "Трансляція на Cherry.tv",
       "Налаштування зовнішнього енкодера для Streamer Dashboard Cherry.tv.",
       "Cherry.tv — новіша, швидко зростаюча cam-платформа з виразним Web3-акцентом: дружні до крипти виплати й нижчий поріг входу, ніж у старих мереж типу LiveJasmin. Стандартний broadcaster працює у браузері, але <strong>Streamer Dashboard</strong> відкриває й стандартний шлях зовнішнього енкодера, до якого підключається безкоштовний <strong style='color:var(--text)'>SplitCam</strong> — дозволяючи транслювати з мультикамерними сценами, оверлеями та фільтрами.",
       "Трансляція на Cherry.tv зі SplitCam: встановіть SplitCam, зберіть сцену, у Streamer Dashboard → <em>Broadcast Settings → External Encoder</em> скопіюйте URL і ключ, вставте у SplitCam, Go Live."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте камеру й оверлеї.</li><li>Отримайте URL і ключ зі Streamer Dashboard.</li><li>Вставте у SplitCam.</li><li>Натисніть Go Live.</li></ol>",
       "Увійдіть у streamer-акаунт на Cherry.tv, відкрийте <strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong>. URL сервера та ключ трансляції прив'язані до вашого акаунта. Нові акаунти спершу мають пройти базову верифікацію (зазвичай швидко — Cherry.tv має легший онбординг, ніж старі cam-мережі), перш ніж опція External Encoder повністю активується.",
       [("Легший вхід, зростаючий трафік", "Жодного 72-годинного review у стилі Docler — гарний момент, щоб побудувати базу підписників, поки конкуренція не закрутила гайки. Нові акаунти мають пристойну видимість у лістингу."),
        ("Крипто-виплати поруч зі стандартним фіатом", "Cherry.tv пропонує виплати в крипті паралельно зі звичайними переказами — корисно там, де традиційні виплати cam-мереж повільні чи регіонально обмежені."),
        ("Browser broadcaster vs зовнішній", "Стандартний broadcaster у браузері зручний, але це одне джерело. SplitCam через External Encoder розблоковує мультикамерні сцени, оверлеї, beauty-фільтри й AI-фон — це різниця між «звичайним стрімом» і преміум-сценою."),
        _T_ETH],
       [("Чи підтримує Cherry.tv зовнішні енкодери на кшталт SplitCam?", "Так — Streamer Dashboard має External Encoder у Broadcast Settings зі стандартним URL сервера RTMP і ключем трансляції. OBS, SplitCam та інші RTMP-енкодери підключаються без проблем."),
        ("Де знайти ключ трансляції Cherry.tv?", "Streamer Dashboard → Broadcast Settings → External Encoder. URL сервера й ключ з'являються на тій же сторінці — скопіюйте обидва в кастомні поля RTMP у SplitCam."),
        ("Який бітрейт для Cherry.tv?", "3500–6000 Кбіт/с при 1920×1080, 30 fps, ключовий кадр кожні 2 секунди. Спершу запустіть вбудований тест швидкості SplitCam, щоб переконатися, що аплоад стабільно тримає обраний бітрейт."),
        ("Чи безкоштовний SplitCam для Cherry.tv?", "Так — SplitCam безкоштовний, без вотермарки, без обмеження часу. Опція External Encoder на боці Cherry.tv також безкоштовна.")],
       steps=[
           ("Завантажте та встановіть SplitCam", "SplitCam — безкоштовне ПЗ для прямих трансляцій для Windows і macOS — без реєстрації, без картки, без вотермарки. Це енкодер, який надсилає ваше відео на Cherry.tv."),
           ("Зберіть сцену", "Відкрийте SplitCam і додайте камеру, оверлеї, за потреби другу камеру або телефон, beauty-фільтри й AI-фон. Аудиторія Cherry.tv молодша й добре орієнтується в платформах — відшліфована сцена реально допомагає виділитися."),
           ("Отримайте URL і ключ трансляції Cherry.tv", "Увійдіть у streamer-акаунт на Cherry.tv, відкрийте <strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong>. Скопіюйте URL сервера та ключ трансляції."),
           ("Підключіть SplitCam до Cherry.tv", "У SplitCam відкрийте <strong>Stream Settings</strong>, вставте URL і ключ у кастомні поля RTMP. Поставте бітрейт 3500–6000 Кбіт/с при 1920×1080, 30 fps, ключовий кадр кожні 2 секунди. Спершу запустіть вбудований тест швидкості."),
           ("Натисніть Go Live", "Натисніть <strong>Go Live</strong> у SplitCam, потім перейдіть онлайн у Streamer Dashboard на Cherry.tv. Приблизно за 10 секунд ваш сигнал доходить до Cherry.tv. Наступні трансляції — один клік."),
       ]),
    _p("amateurtv", "AmateurTV",
       "Трансляція на AmateurTV зі SplitCam — іспаномовна cam-мережа",
       "Трансляція на AmateurTV з безкоштовним SplitCam — External Encoder у Model Panel, cam-мережа для Іспанії та Латинської Америки, мультикамерні сцени. Без вотермарки, без реєстрації.",
       "amateurtv трансляція, amateur.tv obs, amateurtv external encoder, amateurtv rtmp, amateurtv ключ трансляції, modelos amateur tv",
       'Як транслювати на <span class="accent">AmateurTV</span> зі SplitCam',
       "Трансляція на AmateurTV",
       "Налаштування External Encoder для іспаномовної мережі AmateurTV.",
       "AmateurTV — провідна іспаномовна cam-мережа з сильною аудиторією в Іспанії, Мексиці, Аргентині та по всій Латинській Америці. Стандартний broadcaster у Model Panel працює у браузері, але відкриває й стандартний шлях через <strong>External Encoder</strong>, до якого підключається безкоштовний <strong style='color:var(--text)'>SplitCam</strong> — дозволяючи транслювати з мультикамерними сценами, beauty-фільтрами та оверлеями іспаномовній аудиторії, яку мережі, орієнтовані на США, обслуговують погано.",
       "Трансляція на AmateurTV зі SplitCam: встановіть SplitCam, зберіть сцену, у Model Panel відкрийте <em>Broadcast Settings → External Encoder</em>, скопіюйте URL сервера та stream key, вставте у SplitCam, Go Live."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте камеру й сцену.</li><li>Отримайте URL і ключ із Model Panel.</li><li>Вставте у SplitCam.</li><li>Натисніть Go Live.</li></ol>",
       "Увійдіть в акаунт моделі AmateurTV, відкрийте <strong>Model Panel</strong> і перейдіть до <strong>Broadcast Settings → External Encoder</strong>. Сторінка покаже <strong>URL сервера</strong> та <strong>stream key</strong>, прив'язані до вашого акаунта — скопіюйте обидва в кастомні поля RTMP у SplitCam. Нові акаунти моделей мають пройти верифікацію особи, перш ніж вийти в ефір.",
       [("Іспаномовна аудиторія передусім", "Трафік AmateurTV переважно іспаномовний — Іспанія вдень, LatAm увечері за американським часом. Назви трансляцій, тексти на сцені та оверлеї іспанською розгромно випереджають англомовні в цій мережі."),
        ("Часовий пояс LatAm — ваш прайм", "Пік трафіку корелює з вечірніми годинами LatAm (UTC-3 до UTC-6). Якщо у вас гнучкий графік, трансляції пізно ввечері за CET / рано вранці за азійським часом потрапляють і в пік Іспанії, і LatAm."),
        ("Стабільні виплати середнього рівня", "Не найвищий RPM у галузі, але стабільний — AmateurTV платить регулярно, а іспаномовна ніша має меншу конкуренцію, ніж топові мережі США."),
        _T_ETH],
       [("Чи офіційно AmateurTV підтримує зовнішні енкодери на кшталт SplitCam?", "Так — Model Panel має опцію External Encoder у Broadcast Settings. AmateurTV надає стандартний URL сервера RTMP і stream key; OBS, SplitCam, vMix та інші RTMP-енкодери підключаються без проблем."),
        ("Де знайти stream key AmateurTV?", "Model Panel → Broadcast Settings → External Encoder. URL сервера й stream key з'являються там разом. Скопіюйте обидва в кастомні поля RTMP у SplitCam. Ключ прив'язаний до акаунта."),
        ("Який бітрейт для AmateurTV?", "Стандартні налаштування cam-якості — виштовхуйте 1920×1080 при 30 fps, 3500–6000 Кбіт/с із ключовим кадром кожні 2 секунди. Спершу запустіть вбудований тест швидкості SplitCam."),
        ("Чи безкоштовний SplitCam для AmateurTV?", "Так — SplitCam безкоштовний, без вотермарки, без обмеження часу. Опція External Encoder на боці AmateurTV вмикається безкоштовно.")],
       steps=[
           ("Завантажте та встановіть SplitCam", "SplitCam — безкоштовне ПЗ для прямих трансляцій для Windows і macOS — без реєстрації, без картки, без вотермарки. Це енкодер, який надсилає ваше відео на AmateurTV."),
           ("Зберіть сцену", "Відкрийте SplitCam і додайте камеру. Додайте оверлеї, тексти, другу камеру або телефон, beauty-фільтри чи AI-фон. Використовуйте іспанські тексти на оверлеях — аудиторія AmateurTV іспаномовна."),
           ("Отримайте URL і stream key AmateurTV", "Увійдіть в акаунт моделі AmateurTV, відкрийте <strong>Model Panel</strong>, перейдіть до <strong>Broadcast Settings → External Encoder</strong>. Сторінка покаже <strong>URL сервера</strong> та унікальний <strong>stream key</strong>. Скопіюйте обидва."),
           ("Підключіть SplitCam до AmateurTV", "У SplitCam відкрийте <strong>Stream Settings</strong>, вставте URL і stream key AmateurTV у кастомні поля RTMP. Поставте бітрейт 3500–6000 Кбіт/с при 1920×1080, 30 fps, ключовий кадр кожні 2 секунди. Спершу запустіть вбудований тест швидкості."),
           ("Натисніть Go Live", "Натисніть <strong>Go Live</strong> у SplitCam, потім перейдіть онлайн у Model Panel на AmateurTV. Приблизно за 10 секунд ваш сигнал доходить до мережі. Наступні трансляції — один клік: відкрити SplitCam, Go Live."),
       ]),
    _p("camster", "Camster",
       "Трансляція на Camster зі SplitCam — External Encoder у Model Hub",
       "Трансляція на Camster з безкоштовним SplitCam — External Encoder у Model Hub, усталена cam-платформа середнього рівня, мультикамерні сцени й оверлеї. Без вотермарки, без реєстрації.",
       "camster трансляція, camster.com obs, camster external encoder, camster rtmp, camster ключ трансляції, camster model hub",
       'Як транслювати на <span class="accent">Camster</span> зі SplitCam',
       "Трансляція на Camster",
       "Налаштування External Encoder для Model Hub у Camster.",
       "Camster — усталена cam-платформа середнього рівня: менша за Chaturbate чи LiveJasmin, але з лояльною базою користувачів і чесними виплатами. Стандартний broadcaster у Model Hub працює у браузері, але відкриває й стандартний шлях через <strong>External Encoder</strong>, до якого підключається безкоштовний <strong style='color:var(--text)'>SplitCam</strong> — дозволяючи транслювати з мультикамерними сценами, оверлеями та фільтрами, які вбудований broadcaster не тягне.",
       "Трансляція на Camster зі SplitCam: встановіть SplitCam, зберіть сцену, у Model Hub відкрийте <em>Broadcast Settings → External Encoder</em>, скопіюйте URL сервера та stream key, вставте у SplitCam, Go Live."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте камеру й сцену.</li><li>Отримайте URL і ключ із Model Hub.</li><li>Вставте у SplitCam.</li><li>Натисніть Go Live.</li></ol>",
       "Увійдіть в акаунт моделі Camster, відкрийте <strong>Model Hub</strong> і перейдіть до <strong>Broadcast Settings → External Encoder</strong>. Сторінка покаже <strong>URL сервера</strong> та <strong>stream key</strong>, прив'язані до вашого акаунта — скопіюйте обидва в кастомні поля RTMP у SplitCam. Ключ прив'язаний до акаунта; тримайте як пароль.",
       [("Середній рівень = менша конкуренція", "У Camster стабільний трафік, але менше нададавачів, ніж у топових мереж — простіше потрапити на головну сторінку з відшліфованою сценою та регулярним розкладом."),
        ("Browser broadcaster vs зовнішній", "Стандартний broadcaster у браузері — одне джерело. SplitCam через External Encoder розблоковує мультикамерні сцени, оверлеї, beauty-фільтри й AI-фон."),
        ("Стабільні виплати, чесні розподіли", "Розподіл доходу в Camster чесний як на середній рівень — не найвищий у галузі, але регулярні щомісячні виплати й мало скарг моделей на затримки платежів."),
        _T_ETH],
       [("Чи офіційно Camster підтримує зовнішні енкодери на кшталт SplitCam?", "Так — Model Hub має опцію External Encoder у Broadcast Settings. Стандартний URL сервера RTMP і stream key; OBS, SplitCam та інші RTMP-енкодери підключаються."),
        ("Де знайти stream key Camster?", "Model Hub → Broadcast Settings → External Encoder. URL сервера й stream key з'являються там разом. Скопіюйте обидва в кастомні поля RTMP у SplitCam."),
        ("Який бітрейт для Camster?", "Стандартні налаштування cam-якості — виштовхуйте 1920×1080 при 30 fps, 3500–6000 Кбіт/с із ключовим кадром кожні 2 секунди. Спершу запустіть вбудований тест швидкості SplitCam."),
        ("Чи безкоштовний SplitCam для Camster?", "Так — SplitCam безкоштовний, без вотермарки, без обмеження часу. Опція External Encoder на боці Camster безкоштовна.")],
       steps=[
           ("Завантажте та встановіть SplitCam", "SplitCam — безкоштовне ПЗ для прямих трансляцій для Windows і macOS — без реєстрації, без картки, без вотермарки."),
           ("Зберіть сцену", "Відкрийте SplitCam і додайте камеру. Додайте оверлеї, тексти, другу камеру або телефон, beauty-фільтри чи AI-фон — усе накладається наживо."),
           ("Отримайте URL і stream key Camster", "Увійдіть в акаунт моделі Camster, відкрийте <strong>Model Hub</strong>, перейдіть до <strong>Broadcast Settings → External Encoder</strong>. Сторінка покаже <strong>URL сервера</strong> та унікальний <strong>stream key</strong>. Скопіюйте обидва."),
           ("Підключіть SplitCam до Camster", "У SplitCam відкрийте <strong>Stream Settings</strong>, вставте URL і stream key Camster у кастомні поля RTMP. Поставте бітрейт 3500–6000 Кбіт/с при 1920×1080, 30 fps, ключовий кадр кожні 2 секунди. Спершу запустіть вбудований тест швидкості."),
           ("Натисніть Go Live", "Натисніть <strong>Go Live</strong> у SplitCam, потім перейдіть онлайн у Model Hub на Camster. Приблизно за 10 секунд ваш сигнал доходить до Camster."),
       ]),
    _p("camversity", "Camversity",
       "Трансляція на Camversity зі SplitCam — External Encoder у Performer Dashboard",
       "Трансляція на Camversity з безкоштовним SplitCam — External Encoder у Performer Dashboard, зростаюча незалежна cam-платформа, мультикамерні сцени. Без вотермарки, без реєстрації.",
       "camversity трансляція, camversity obs, camversity external encoder, camversity rtmp, camversity ключ трансляції, camversity performer",
       'Як транслювати на <span class="accent">Camversity</span> зі SplitCam',
       "Трансляція на Camversity",
       "Налаштування External Encoder для Performer Dashboard у Camversity.",
       "Camversity — зростаюча незалежна cam-платформа з акцентом на інструменти, дружні до performer-ів, і нижчі комісії, ніж у застарілих мереж. Стандартний broadcaster у Performer Dashboard працює у браузері, але відкриває й стандартний шлях через <strong>External Encoder</strong>, до якого підключається безкоштовний <strong style='color:var(--text)'>SplitCam</strong> — дозволяючи транслювати з мультикамерними сценами, оверлеями та фільтрами.",
       "Трансляція на Camversity зі SplitCam: встановіть SplitCam, зберіть сцену, у Performer Dashboard відкрийте <em>Stream Settings → External Encoder</em>, скопіюйте URL сервера та stream key, вставте у SplitCam, Go Live."
       "<ol><li>Встановіть SplitCam.</li><li>Додайте камеру й сцену.</li><li>Отримайте URL і ключ із Performer Dashboard.</li><li>Вставте у SplitCam.</li><li>Натисніть Go Live.</li></ol>",
       "Увійдіть в акаунт performer-а Camversity, відкрийте <strong>Performer Dashboard</strong> і перейдіть до <strong>Stream Settings → External Encoder</strong>. Сторінка покаже <strong>URL сервера</strong> та <strong>stream key</strong>, прив'язані до вашого акаунта — скопіюйте обидва в кастомні поля RTMP у SplitCam. Нові акаунти мають пройти стандартну верифікацію особи, перш ніж вийти в ефір.",
       [("Розподіли, дружні до performer-ів", "Розподіл доходу в Camversity вигідніший для performer-ів, ніж у застарілих мереж — варто порівняти з вашою поточною основною платформою, якщо ви на старті cam-кар'єри."),
        ("Легший онбординг, ніж у Docler", "Верифікація в Camversity швидша за 48–72-годинне затвердження LiveJasmin, але все одно справжня (без випадкових / неперевірених моделей). Гарна золота середина."),
        ("Будуйте сцену, а не лише камеру", "Стандартний broadcaster Performer Dashboard у Camversity — одне джерело. SplitCam через External Encoder розблоковує мультикамерні сцени, оверлеї та beauty-фільтри."),
        _T_ETH],
       [("Чи офіційно Camversity підтримує зовнішні енкодери на кшталт SplitCam?", "Так — Performer Dashboard має External Encoder у Stream Settings. Стандартний URL сервера RTMP і stream key; OBS, SplitCam і vMix підключаються."),
        ("Де знайти stream key Camversity?", "Performer Dashboard → Stream Settings → External Encoder. URL сервера й stream key з'являються там разом."),
        ("Який бітрейт для Camversity?", "Виштовхуйте 1920×1080 при 30 fps, 3500–6000 Кбіт/с із ключовим кадром кожні 2 секунди. Спершу запустіть вбудований тест швидкості SplitCam."),
        ("Чи безкоштовний SplitCam для Camversity?", "Так — SplitCam безкоштовний, без вотермарки, без обмеження часу. Опція External Encoder на боці Camversity безкоштовна.")],
       steps=[
           ("Завантажте та встановіть SplitCam", "SplitCam — безкоштовне ПЗ для прямих трансляцій для Windows і macOS — без реєстрації, без картки, без вотермарки."),
           ("Зберіть сцену", "Відкрийте SplitCam і додайте камеру. Додайте оверлеї, тексти, другу камеру або телефон, beauty-фільтри чи AI-фон."),
           ("Отримайте URL і stream key Camversity", "Увійдіть в акаунт performer-а Camversity, відкрийте <strong>Performer Dashboard</strong>, перейдіть до <strong>Stream Settings → External Encoder</strong>. Сторінка покаже <strong>URL сервера</strong> та унікальний <strong>stream key</strong>. Скопіюйте обидва."),
           ("Підключіть SplitCam до Camversity", "У SplitCam відкрийте <strong>Stream Settings</strong>, вставте URL і stream key Camversity у кастомні поля RTMP. Поставте бітрейт 3500–6000 Кбіт/с при 1920×1080, 30 fps, ключовий кадр кожні 2 секунди."),
           ("Натисніть Go Live", "Натисніть <strong>Go Live</strong> у SplitCam, потім перейдіть онлайн у Performer Dashboard. Приблизно за 10 секунд ваш сигнал доходить до Camversity."),
       ]),
]
