# -*- coding: utf-8 -*-
"""Indonesian (id) content for cam-streaming-guides. Native Indonesian, 19 platforms."""

_T_ETH = ("Pakai koneksi kabel", "Ethernet mengalahkan Wi-Fi saat siaran panjang — frame yang "
          "hilang berarti tip yang hilang. Tarik kabel ke PC siaran.")
_T_TEST = ("Lakukan tes privat dulu", "Jalankan siaran tes singkat untuk memeriksa kamera, audio, "
           "framing, dan overlay sebelum membuka room untuk penonton.")

def _p(slug, name, title, desc, kw, h1html, h1short, card, intro, quick, key_how, tips, faq, steps=None):
    d = {"slug": slug, "name": name, "title": title, "desc": desc, "kw": kw,
         "h1html": h1html, "h1short": h1short, "card": card, "intro": intro,
         "quick": quick, "key_how": key_how, "tips": tips, "faq": faq}
    if steps: d["steps"] = steps
    return d

PLATFORMS_ID = [
    _p("chaturbate", "Chaturbate",
       "Siaran di Chaturbate dengan SplitCam — Token & RTMP",
       "Siaran di Chaturbate dengan SplitCam gratis — broadcast token, RTMP, scene multi-kamera, dan overlay. Tanpa watermark, tanpa daftar.",
       "siaran chaturbate, chaturbate broadcast token, chaturbate rtmp obs, chaturbate encoder eksternal, chaturbate live",
       'Cara siaran di <span class="accent">Chaturbate</span> dengan SplitCam',
       "Siaran Chaturbate",
       "Pengaturan berbasis token dengan encoder eksternal di Chaturbate.",
       "Chaturbate adalah salah satu platform cam terbesar, dibangun di atas ekonomi token. Broadcaster browser-nya cuma alat satu kamera yang datar — beralih ke <strong style='color:var(--text)'>encoder eksternal</strong> dengan <strong style='color:var(--text)'>SplitCam</strong> gratis membuka scene multi-kamera, overlay, dan filter di siaran berbasis token yang sama.",
       "Siaran di Chaturbate dengan SplitCam: pasang SplitCam, susun scene, di Chaturbate buka <em>Broadcast Yourself → My Broadcast</em>, salin broadcast token, tempel di SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + scene.</li><li>Salin broadcast token dari Chaturbate.</li><li>Tempel di SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di Chaturbate klik <strong>Broadcast Yourself</strong> untuk halaman <strong>My Broadcast</strong>, lalu <strong>View RTMP/OBS broadcast information and stream key</strong>. Kunci muncul sebagai <strong>broadcast token</strong> — salin. Perlakukan seperti kata sandi; jangan pernah dibagikan.",
       [("Token adalah kuncinya", "Chaturbate memakai broadcast token-mu, bukan stream key umum. Perlakukan seperti kata sandi dan reset jika bocor."),
        ("Ruang lega", "RTMP ingest Chaturbate menerima hingga 4K, 60 fps, dan bitrate tinggi — batasnya adalah upload-mu, bukan platform. Keyframe tiap 2 detik."),
        _T_ETH, _T_TEST],
       [("Apakah Chaturbate mengizinkan OBS / encoder eksternal?", "Ya — Chaturbate mendukung encoder eksternal secara resmi dengan artikel «How do I set up OBS?» sendiri. Aktifkan via «Use External Encoder to Broadcast» di pengaturan siaran."),
        ("Di mana stream key Chaturbate saya?", "Broadcast Yourself → My Broadcast → View RTMP/OBS broadcast information and stream key. Kuncinya adalah broadcast token-mu."),
        ("Bitrate berapa untuk Chaturbate?", "3.500–6.000 Kbps di 1080p sudah lebih dari cukup. Plafon Chaturbate tinggi — batas sebenarnya adalah upload-mu; jalankan dulu tes kecepatan bawaan SplitCam."),
        ("Apakah SplitCam gratis untuk Chaturbate?", "Ya — sepenuhnya gratis, tanpa watermark dan tanpa batas waktu: encoder tidak memakan penghasilan token-mu.")]),
    _p("cam4", "CAM4",
       "Siaran di CAM4 dengan SplitCam — External Encoder",
       "Siaran di CAM4 dengan SplitCam gratis — External Encoder, stream key, blokir geo, dan overlay. Tanpa watermark.",
       "siaran cam4, cam4.com, cam4 external encoder, cam4 stream key, cam4 rtmp obs",
       'Cara siaran di <span class="accent">CAM4</span> dengan SplitCam',
       "Siaran CAM4",
       "External Encoder di CAM4 dengan kontrol geo.",
       "CAM4 adalah platform cam-and-earn global dengan kontrol geo bawaan — kamu bisa menyembunyikan siaran di negara tertentu. Siaran lewat <strong style='color:var(--text)'>SplitCam</strong> gratis sebagai encoder eksternal membuka pergantian scene dan overlay yang tidak dilakukan broadcaster dasar.",
       "Siaran di CAM4 dengan SplitCam: pasang SplitCam, susun scene, di CAM4 buka <em>Broadcast &amp; Earn Money → Start Broadcast → External Encoder</em>, Get Stream Key, tempel di SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + scene.</li><li>Ambil stream key dari CAM4.</li><li>Tempel di SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di CAM4 klik <strong>Broadcast</strong> → <strong>Broadcast &amp; Earn Money</strong> → <strong>Start Broadcast</strong>, lalu <strong>External Encoder</strong> di atas. Isi tanggal lahir, gender, dan negara, gunakan <strong>Get Stream Key</strong> lalu salin. Slider hijau di Stream Settings SplitCam menandakan koneksi.",
       [("Atur batasan geo", "CAM4 mengizinkan menyembunyikan siaran di negara dan wilayah tertentu — atur di sisi CAM4 sebelum go-live."),
        ("Perhatikan slider hijau", "Pengaturan CAM4 menampilkan slider hijau di Stream Settings SplitCam saat kunci diterima — merah = periksa kuncinya."),
        ("Bitrate lebih rendah dari biasanya", "Ingest CAM4 membatasi bitrate video sekitar 3.000 Kbps — lebih rendah dari kebanyakan situs cam. Jangan dipaksa lebih tinggi."),
        _T_ETH],
       [("Apakah CAM4 mendukung OBS / encoder eksternal secara resmi?", "Ya — CAM4 punya OBS Guide resmi di situs dukungan dan menyarankan External Encoder untuk pengalaman terbaik. SplitCam memakai jalur RTMP yang sama."),
        ("Bisakah memblokir geo siaran CAM4 saya?", "Ya — CAM4 punya pembatasan geo bawaan untuk menyembunyikan siaran di negara tertentu. Atur di CAM4, bukan di SplitCam."),
        ("Di mana stream key CAM4?", "Broadcast → Broadcast & Earn Money → Start Broadcast → External Encoder → Get Stream Key."),
        ("Bitrate berapa untuk CAM4?", "Lebih rendah dari rata-rata — ingest CAM4 membatasi ~3.000 Kbps di 30 fps dengan keyframe 1 detik. Tabel resmi menyarankan tidak melebihi ~3.000.")]),
    _p("bongacams", "BongaCams",
       "Siaran di BongaCams dengan SplitCam — External Encoder",
       "Siaran di BongaCams dengan SplitCam gratis — External Encoder, scene multi-kamera, overlay, dan latar AI. Tanpa watermark.",
       "bongacams, bongcams, siaran bongacams, bongacams external encoder, bongacams rtmp obs",
       'Cara siaran di <span class="accent">BongaCams</span> dengan SplitCam',
       "Siaran BongaCams",
       "Pengaturan External Encoder untuk BongaCams.",
       "BongaCams adalah platform cam global. Siaran encoder eksternal tidak selalu aktif — setelah diaktifkan, <strong style='color:var(--text)'>SplitCam</strong> gratis mengendalikan siaran dengan scene multi-kamera, overlay, dan latar AI.",
       "Siaran di BongaCams dengan SplitCam: pasang SplitCam, susun scene, di BongaCams buka <em>Options → Broadcast settings → Select Encoder → External Encoder</em>, salin URL dan kunci, tempel di SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + scene.</li><li>Ambil URL dan kunci dari BongaCams.</li><li>Tempel di SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di BongaCams buka <strong>Options</strong> → <strong>Broadcast settings</strong> → <strong>Select Encoder</strong> → <strong>External Encoder</strong> dan salin URL server serta stream key yang ditampilkan. <strong>Jika tombol External Encoder tidak ada</strong>, hubungi dukungan BongaCams dan minta encoding eksternal diaktifkan di akunmu.",
       [("Tidak ada tombol External Encoder? Dukungan", "BongaCams mengaktifkan encoding eksternal per akun — jika opsi tidak ada di Broadcast settings, dukungan yang mengaktifkannya."),
        ("Samakan resolusi", "BongaCams menyarankan resolusi webcam dan siaran cocok — misalnya keduanya 1280×720."),
        _T_ETH, _T_TEST],
       [("Kenapa tombol External Encoder tidak muncul di BongaCams?", "Encoding eksternal tidak aktif secara default di setiap akun — hubungi dukungan BongaCams untuk mengaktifkannya, lalu tombol muncul di Broadcast settings."),
        ("Apakah perlu memverifikasi akun BongaCams?", "Ya — siaran butuh 18+, ID resmi untuk verifikasi usia, dan persetujuan akun sebelum live."),
        ("Bitrate berapa untuk BongaCams?", "RTMP ingest BongaCams membatasi bitrate video sekitar 6.000 Kbps dengan keyframe 2 detik — 3.500–6.000 di 1080p adalah zona ideal; tes upload dulu."),
        ("Apakah SplitCam gratis untuk BongaCams?", "Ya — sepenuhnya gratis, tanpa watermark dan tanpa batas waktu, jadi encoder tidak mengurangi penghasilan token-mu di BongaCams.")]),
    _p("stripchat", "Stripchat",
       "Siaran di Stripchat dengan SplitCam — Setup Strip Cam",
       "Siaran di Stripchat — platform strip cam — dengan SplitCam gratis. Software eksternal, kunci token, scene, dan overlay.",
       "strip cam, stripchat live stream, siaran stripchat, stripchat external software, stripchat stream key, stripchat rtmp obs",
       'Cara siaran di <span class="accent">Stripchat</span> dengan SplitCam',
       "Siaran Stripchat",
       "Pengaturan software eksternal untuk siaran Stripchat.",
       "Stripchat adalah platform cam besar yang fokus pada interaktivitas. Mode <em>external software</em> memberimu kunci berbasis token — masukkan ke <strong style='color:var(--text)'>SplitCam</strong> gratis untuk siaran dengan scene, overlay, dan filter, bukan kamera datar.",
       "Siaran di Stripchat dengan SplitCam: pasang SplitCam, susun scene, di Stripchat pilih <em>Switch to external software</em>, salin stream key, tempel di SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + scene.</li><li>Ambil stream key dari Stripchat.</li><li>Tempel di SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di Stripchat pilih <strong>Switch to external software</strong>, lalu <strong>Show external software settings for the stream</strong>. Salin stream key — Stripchat menampilkannya sebagai token. Jaga kerahasiaannya.",
       [("Samakan resolusi dengan situs", "FAQ Stripchat memperingatkan: resolusi di software-mu harus persis cocok dengan situs, kalau tidak video jadi pecah. Atur keduanya sama."),
        ("Awas batas minimum 2 Mbps", "Stripchat mencantumkan 2 Mbps upload sebagai minimum — dan menyatakan terus terang itu tidak cukup untuk siaran OBS atau multistream. Bidik jauh lebih tinggi."),
        ("Kunci adalah token", "Stream key Stripchat adalah token — salin persis, jangan pernah dibagikan, reset jika bocor."),
        _T_ETH],
       [("Apakah Stripchat menyarankan OBS / software eksternal?", "Ya — FAQ resmi Stripchat menyarankan software siaran eksternal seperti OBS «untuk mencapai kualitas video dan audio terbaik». SplitCam bekerja dengan cara yang sama."),
        ("Bagaimana mengalihkan Stripchat ke software eksternal?", "Di Broadcast Center pilih Switch to External Broadcast Software (OBS), lalu buka external software settings untuk menampilkan stream key (token)."),
        ("Bitrate berapa untuk Stripchat?", "RTMP ingest menerima hingga ~6.000 Kbps dengan keyframe 2 detik. 3.500–6.000 di 1080p ideal — tapi harus jauh di atas minimum 2 Mbps, terutama untuk siaran OBS."),
        ("Apakah SplitCam gratis untuk Stripchat?", "Ya — tanpa biaya lisensi, tanpa watermark, tanpa batas waktu: bahkan show Stripchat interaktif yang panjang tidak ada biaya di sisi encoder.")]),
    _p("onlyfans", "OnlyFans",
       "Live di OnlyFans dengan SplitCam — Otorisasi atau kunci",
       "Live di OnlyFans dengan SplitCam gratis — masuk via otorisasi atau OBS Key, scene multi-kamera, overlay. Tanpa watermark.",
       "live onlyfans, onlyfans live stream, onlyfans otorisasi splitcam, onlyfans obs key, onlyfans software siaran",
       'Cara live di <span class="accent">OnlyFans</span> dengan SplitCam',
       "Live OnlyFans",
       "Otorisasi sekali atau tempel kunci — live di OnlyFans.",
       "Live OnlyFans untuk para pelangganmu. SplitCam terhubung dengan <strong style='color:var(--text)'>dua cara</strong> — masuk sekali dengan akun OnlyFans dan SplitCam mengambil stream key otomatis serta menyinkronkannya, atau tempel OBS Key secara manual. Keduanya membiarkanmu siaran dengan scene multi-kamera, overlay, dan filter.",
       "Live di OnlyFans dengan SplitCam: pasang SplitCam, susun scene, buka Stream Settings &rarr; Add Channel &rarr; OnlyFans dan pilih <em>Otorisasi</em> — masuk dengan akun OnlyFans, SplitCam mengambil kunci otomatis — lalu tekan Go Live. Dengan akun terhubung, kamu bisa mengubah parameter siaran OnlyFans di SplitCam tanpa membuka situs OnlyFans.",
       "Di OnlyFans: <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; bagian <strong>Other</strong>, salin <strong>OBS Key</strong>. Atau gunakan opsi <strong>Otorisasi</strong> di SplitCam untuk masuk akun — kunci diambil otomatis dan tetap sinkron.",
       [("Otorisasi vs Stream Key", "Dua cara terhubung: <strong>Otorisasi</strong> (masuk sekali, kunci diambil dan disinkronkan — jalur termudah) atau <strong>Stream Key</strong> (salin OBS Key di OnlyFans → Profile → Settings → Other lalu tempel)."),
        ("Ubah pengaturan tanpa keluar dari SplitCam", "Dengan otorisasi akun tetap terhubung, jadi kamu mengatur parameter live OnlyFans dari SplitCam selama atau setelah siaran — tanpa lewat situs OnlyFans."),
        ("Bitrate sederhana", "RTMP ingest OnlyFans membatasi bitrate video sekitar 2.500 Kbps — lebih ketat dari kebanyakan situs cam. Bidik 720p–1080p di ~2.000–2.500."),
        _T_ETH],
       [("Bagaimana menghubungkan OnlyFans ke SplitCam?", "Dua cara. <strong>Otorisasi</strong> — Stream Settings → Add Channel → OnlyFans → masuk dengan akun OnlyFans dan SplitCam mengambil kunci otomatis. Atau <strong>Stream Key</strong> — salin OBS Key di OnlyFans → Profile → Settings → Other lalu tempel."),
        ("Bisakah mengubah pengaturan live OnlyFans tanpa membuka situs?", "Ya — dengan metode Otorisasi SplitCam tetap terhubung ke akun OnlyFans-mu, jadi kunci dan pengaturan tersinkron otomatis. Kamu ubah semua dari SplitCam selama atau setelah siaran, tanpa mengunjungi onlyfans.com."),
        ("Bitrate berapa untuk OnlyFans?", "Sederhana — RTMP ingest OnlyFans membatasi bitrate sekitar 2.500 Kbps, jauh lebih ketat dari platform cam lain. Bidik 720p–1080p sekitar 2.000–2.500 Kbps."),
        ("Apakah SplitCam gratis untuk live OnlyFans?", "Ya — gratis, tanpa watermark dan tanpa batas waktu. Tanpa biaya di sisi encoder.")],
       steps=[
           ("Unduh dan pasang SplitCam", "SplitCam adalah software live-streaming gratis untuk Windows dan macOS — tanpa daftar, tanpa kartu, tanpa watermark. Inilah encoder yang mengirim videomu ke OnlyFans."),
           ("Atur kamera dan scene", "Buka SplitCam dan tambahkan webcam-mu. Susun scene seperti yang ingin dilihat penonton — overlay, teks, kamera kedua, filter kecantikan, atau latar AI, semua diterapkan secara live."),
           ("Koneksi — Cara 1: Otorisasi (disarankan)", "Di SplitCam buka <strong>Stream Settings</strong> &rarr; <strong>Add Channel</strong> &rarr; <strong>OnlyFans</strong> dan pilih <strong>Otorisasi</strong>. Masuk dengan email dan kata sandi OnlyFans. SplitCam menautkan akunmu, mengambil stream key otomatis dan menjaganya sinkron — serta membiarkanmu mengelola parameter live OnlyFans di dalam SplitCam, mengubahnya selama atau setelah siaran tanpa membuka situs OnlyFans."),
           ("Koneksi — Cara 2: Stream Key (manual)", "Lebih suka tidak masuk? Pakai kuncinya. Di OnlyFans buka <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; bagian <strong>Other</strong> dan salin <strong>OBS Key</strong>. Di SplitCam, Add Channel &rarr; OnlyFans, tempel ke kolom kunci. Kunci ini statis — untuk mengubah pengaturan nanti kembali ke situs OnlyFans."),
           ("Go Live", "Apa pun caranya, tekan <strong>Go Live</strong> di SplitCam. Dengan Cara 1 kamu bisa terus menyetel parameter OnlyFans dari SplitCam secara real time; dengan Cara 2 kunci tetap persis seperti yang kamu atur."),
       ]),
    _p("camplace", "CamPlace",
       "Siaran di CamPlace dengan SplitCam — Panduan gratis",
       "Siaran di CamPlace dengan SplitCam gratis — encoder eksternal, kunci RTMP, scene, dan overlay. Langkah demi langkah, tanpa watermark.",
       "siaran camplace, camplace broadcasting software, camplace rtmp, camplace encoder eksternal, camplace stream key",
       'Cara siaran di <span class="accent">CamPlace</span> dengan SplitCam',
       "Siaran CamPlace",
       "Pengaturan encoder eksternal untuk siaran CamPlace.",
       "CamPlace adalah platform cam-streaming. Tidak ada artikel OBS publik, jadi <strong style='color:var(--text)'>panduan video di atas</strong> adalah referensimu — <strong style='color:var(--text)'>SplitCam</strong> gratis terhubung via RTMP standar dan menambahkan scene, overlay, serta latar AI yang tidak dilakukan kamera dasar.",
       "Siaran di CamPlace dengan SplitCam: pasang SplitCam, susun scene, aktifkan siaran eksternal/RTMP di CamPlace, salin URL server dan stream key, tempel di SplitCam, Go Live. Ikuti video untuk jalur terkini."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + scene.</li><li>Ambil kunci RTMP dari CamPlace.</li><li>Tempel di SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Masuk ke CamPlace dan buka pengaturan siaran. Beralih ke opsi encoder eksternal / RTMP / OBS untuk menampilkan <strong>URL server</strong> dan <strong>stream key</strong>, salin keduanya. CamPlace tidak menerbitkan dokumentasi OBS resmi — <strong>video di atas</strong> adalah jalur langkah demi langkah paling andal melalui antarmuka saat ini.",
       [("Tidak ada panduan OBS resmi — pakai video", "CamPlace tidak punya artikel publik tentang encoder eksternal; video di atas adalah referensi jalur terkini."),
        ("RTMP standar berfungsi", "Meski tak terdokumentasi, CamPlace menerima URL server RTMP standar dan kunci — SplitCam terhubung sebagai tujuan RTMP kustom."),
        ("Tumpuk overlay di SplitCam", "Target tip, nama, dan handle media sosial sebagai lapisan scene — kamera dasar CamPlace tidak menambahkannya."),
        _T_ETH],
       [("Apakah CamPlace punya panduan OBS resmi?", "Tidak ditemukan artikel publik tentang encoder eksternal. CamPlace menerima URL RTMP standar dan kunci, jadi SplitCam berfungsi — ikuti video."),
        ("Apakah CamPlace mendukung encoder eksternal?", "Ya — menerima stream key RTMP standar, jadi SplitCam terhubung sebagai tujuan RTMP kustom."),
        ("Bitrate berapa untuk CamPlace?", "CamPlace tidak menerbitkan angka resmi — pakai 3.500–6.000 Kbps di 1080p sebagai rentang aman dan biarkan tes kecepatan SplitCam menentukan plafon sebenarnya."),
        ("Apakah SplitCam gratis untuk CamPlace?", "Ya — gratis, tanpa watermark dan tanpa batas waktu. Karena CamPlace tidak punya encoder sendiri, alat RTMP gratis menyelesaikannya.")]),
    _p("camsoda", "CamSoda",
       "CamSoda live dengan SplitCam — Setup gratis",
       "CamSoda live dengan SplitCam gratis — Use OBS Broadcaster, server regional, scene, dan overlay. Tanpa watermark.",
       "camsoda live, siaran camsoda, camsoda obs broadcaster, camsoda rtmp obs, camsoda live broadcast",
       'Cara siaran di <span class="accent">CamSoda</span> dengan SplitCam',
       "Siaran CamSoda",
       "Pengaturan Use OBS Broadcaster di CamSoda.",
       "CamSoda adalah platform cam asal AS yang terkenal dengan format show interaktif dan tak biasa. Mendukung siaran OBS secara resmi — ada tombol <strong style='color:var(--text)'>Use OBS Broadcaster</strong> di halaman Go Live dan panduan OBS resmi di wiki CamSoda. <strong style='color:var(--text)'>SplitCam</strong> gratis bekerja dengan cara yang sama.",
       "Siaran di CamSoda dengan SplitCam: pasang SplitCam, susun scene, klik Use OBS Broadcaster di halaman Go Live CamSoda, salin URL server dan stream key, tempel di SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + scene.</li><li>Klik Use OBS Broadcaster di CamSoda.</li><li>Tempel URL server + kunci di SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di halaman <strong>Go Live</strong> CamSoda klik <strong>Use OBS Broadcaster</strong>. CamSoda menampilkan URL server RTMP dan stream key — salin keduanya. Pilih server regional (Amerika Utara, Eropa, Asia, dll.) terdekat. Wiki CamSoda punya panduan OBS lengkap untuk detail.",
       [("Verifikasi untuk menerima tip", "Di CamSoda siapa pun bisa siaran, tapi untuk menerima tip kamu harus menyelesaikan proses verifikasi CamSoda."),
        ("Pilih server regional terdekat", "CamSoda menyediakan server ingest regional — yang terdekat (NA / Eropa / Asia / Amerika Selatan / Oseania) mengurangi latensi dan frame yang hilang."),
        ("Plafon di 1080p / 30 fps", "Ingest CamSoda mencapai sekitar 1080p, 30 fps, dan ~6.000 Kbps — jangan dipaksa lebih tinggi."),
        _T_ETH],
       [("Apakah CamSoda mendukung OBS / encoder eksternal?", "Ya — secara resmi. Ada tombol Use OBS Broadcaster di halaman Go Live dan panduan OBS di wiki CamSoda, jadi SplitCam berfungsi."),
        ("Apakah perlu verifikasi di CamSoda?", "Untuk siaran, tidak. Untuk menerima tip, ya — CamSoda mengharuskan proses verifikasi dulu."),
        ("Resolusi apa yang didukung CamSoda?", "Hingga 1920×1080 di 30 fps, sekitar 6.000 Kbps maksimum di RTMP ingest."),
        ("Apakah SplitCam gratis untuk CamSoda?", "Ya — gratis, tanpa watermark dan tanpa batas waktu. Berfungsi dengan mode Use OBS Broadcaster gratis CamSoda, jadi seluruh rangkaian tidak ada biaya.")]),
    _p("streamate", "Streamate",
       "Siaran di Streamate dengan SplitCam — Kanal terintegrasi",
       "Siaran di Streamate dengan SplitCam gratis — kanal terintegrasi, kunci SM Connect, scene, dan overlay. Tanpa watermark.",
       "streamate, streamate sm connect, siaran streamate, streamate broadcasting software, streamate rtmp",
       'Cara siaran di <span class="accent">Streamate</span> dengan SplitCam',
       "Siaran Streamate",
       "Streamate adalah kanal terintegrasi di SplitCam — setup cepat.",
       "Streamate adalah platform cam mapan — dan termasuk <strong style='color:var(--text)'>tujuan prakonfigurasi di SplitCam</strong>, di daftar kanal, jadi setup lebih cepat dari input RTMP manual: pilih Streamate, tempel kunci, selesai.",
       "Siaran di Streamate dengan SplitCam: pasang SplitCam, susun scene, di Streamate gunakan <em>SM Connect → Start Show</em> dan salin kunci, lalu di SplitCam buka <em>Stream Settings → Add Channel → Streamate</em> dan tempel."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + scene.</li><li>Ambil kunci Streamate via SM Connect.</li><li>Add Channel → Streamate di SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di Streamate buka <strong>SM Connect</strong>, setujui ketentuan, klik <strong>Start Show</strong> di kiri dan tutup jendela yang terbuka — lalu salin kunci streaming. Di SplitCam buka <strong>Stream Settings</strong> → <strong>Add Channel</strong>, pilih <strong>Streamate</strong> dari daftar dan tempel kuncinya. Slider hijau menandakan koneksi.",
       [("Streamate terintegrasi", "Tanpa URL RTMP manual — SplitCam punya Streamate di daftar Add Channel; cukup pilih dan tempel kunci."),
        ("Tutup popup SM Connect", "Setelah Start Show Streamate membuka jendela — tutup; itu hanya untuk menampilkan kunci streaming."),
        ("Kunci resolusi ke 1080p", "Kolom Video Resolution di SM Connect bisa diam-diam melompat ke 1440, yang tidak benar-benar dikirim dan menurunkan kualitasmu diam-diam — atur manual ke 1080p. Bitrate yang turun saat gambar diam itu normal: stream Streamate adaptif."),
        _T_ETH, _T_TEST],
       [("Apakah Streamate terintegrasi di SplitCam?", "Ya — Streamate muncul di daftar Add Channel SplitCam; kamu pilih, bukan ketik URL RTMP manual."),
        ("Di mana kunci streaming Streamate?", "SM Connect → setujui ketentuan → Start Show → tutup popup → salin kunci."),
        ("Bitrate berapa untuk Streamate?", "Streamate tidak menetapkan plafon keras — 3.500–6.000 Kbps di 1080p bekerja baik. Stream adaptif, jadi bitrate lebih rendah saat gambar diam itu normal, bukan bug."),
        ("Apakah SplitCam gratis untuk Streamate?", "Ya — gratis, tanpa watermark dan tanpa batas waktu; dan karena Streamate kanal terintegrasi di SplitCam, tidak ada biaya encoder terpisah.")]),
    _p("streamray", "StreamRay",
       "Siaran di StreamRay cam dengan SplitCam — URL chat",
       "Siaran di StreamRay cam dengan SplitCam gratis — URL diposting di chat, mode OBS Broadcaster, scene, dan overlay. Tanpa watermark.",
       "streamray, streamray cam, siaran streamray, streamray obs broadcaster, streamray rtmp",
       'Cara siaran di <span class="accent">StreamRay</span> dengan SplitCam',
       "Siaran StreamRay",
       "Pengaturan encoder eksternal URL-di-chat untuk StreamRay.",
       "StreamRay punya pengaturan encoder eksternal yang tak biasa — mengirim URL stream di <strong style='color:var(--text)'>jendela chat siaran</strong> dan tidak memakai stream key terpisah. <strong style='color:var(--text)'>SplitCam</strong> gratis menangani alur hanya-URL ini.",
       "Siaran di StreamRay dengan SplitCam: pasang SplitCam, susun scene, di StreamRay aktifkan OBS Broadcaster, salin URL stream dari jendela chat, tempel di SplitCam (biarkan kolom kunci kosong), Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + scene.</li><li>Salin URL StreamRay dari chat.</li><li>Tempel URL di SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di StreamRay klik dua kali <strong>Broadcast Now</strong>, buka menu <strong>Other</strong>, pilih <strong>OBS Broadcaster</strong> dan <strong>Save and Close</strong>. StreamRay lalu memposting <strong>URL stream di jendela chat</strong> — salin dari sana. Biarkan kolom stream key SplitCam <strong>kosong</strong>; StreamRay hanya memverifikasi via URL.",
       [("URL ada di chat", "StreamRay tidak menampilkan URL stream di kotak pengaturan — diposting di jendela chat siaran. Salin dari sana."),
        ("Biarkan kolom kunci kosong", "StreamRay tidak memakai kunci terpisah — hanya URL. Jangan isi apa pun di kolom kunci SplitCam."),
        _T_ETH, _T_TEST],
       [("Di mana URL stream StreamRay?", "Setelah mengaktifkan OBS Broadcaster, StreamRay memposting URL di jendela chat — salin dari chat."),
        ("Kenapa tidak ada stream key di StreamRay?", "StreamRay hanya memverifikasi via URL — biarkan kolom kunci SplitCam kosong."),
        ("Bitrate berapa untuk StreamRay?", "StreamRay tidak menyatakan plafon resmi — bidik 3.500–6.000 Kbps di 1080p dan jalankan tes kecepatan SplitCam, karena alur hanya-URL tidak memberi umpan balik bitrate."),
        ("Apakah SplitCam gratis untuk StreamRay?", "Ya — gratis, tanpa watermark dan tanpa batas waktu, cocok dengan alur hanya-URL StreamRay: tempel satu tautan dan kamu live.")]),
    _p("xlovecam", "XLoveCam",
       "Siaran di XLoveCam dengan SplitCam — Tautan RTMP & kunci",
       "Siaran di XLoveCam dengan SplitCam gratis — tautan RTMP dan kunci, server regional, scene, dan overlay. Tanpa watermark.",
       "xlovecam, x love cam, siaran xlovecam, xlovecam rtmp link, xlovecam stream key",
       'Cara siaran di <span class="accent">XLoveCam</span> dengan SplitCam',
       "Siaran XLoveCam",
       "Pengaturan tautan RTMP + kunci untuk XLoveCam.",
       "XLoveCam adalah platform cam multibahasa Eropa. Pengaturan akun menampilkan baik <strong style='color:var(--text)'>tautan RTMP</strong> maupun <strong style='color:var(--text)'>stream key</strong> — <strong style='color:var(--text)'>SplitCam</strong> gratis mengambil keduanya dan siaran dengan scene serta overlay penuh.",
       "Siaran di XLoveCam dengan SplitCam: pasang SplitCam, susun scene, di XLoveCam buka <em>My Account → settings</em>, salin tautan RTMP dan stream key, tempel keduanya di SplitCam, mulai show."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + scene.</li><li>Salin tautan RTMP + kunci dari XLoveCam.</li><li>Tempel keduanya di SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di XLoveCam buka <strong>My Account</strong> → <strong>settings</strong>. Pengaturan menampilkan baik <strong>tautan RTMP</strong> maupun <strong>stream key</strong> — salin keduanya ke kolom URL server dan kunci SplitCam, lalu <strong>Start your show</strong> di XLoveCam.",
       [("Salin tautan DAN kunci", "XLoveCam memberi tautan RTMP DAN stream key terpisah — kamu butuh keduanya di SplitCam, bukan satu saja."),
        ("Audiens multibahasa", "XLoveCam Eropa dan multibahasa — overlay teks yang jelas dalam bahasamu membantu penonton menemukanmu."),
        ("Pilih server terdekat", "XLoveCam menyediakan server RTMP regional — Eropa, Amerika Utara, Amerika Selatan, dan Asia. Yang terdekat mengurangi latensi dan frame yang hilang."),
        _T_ETH],
       [("Di mana data RTMP XLoveCam?", "My Account → settings — menampilkan baik tautan RTMP maupun kunci."),
        ("Apakah XLoveCam mendukung encoder eksternal?", "Ya — menyediakan tautan RTMP dan kunci, jadi SplitCam berfungsi sebagai encoder."),
        ("Bitrate berapa untuk XLoveCam?", "XLoveCam tidak menerbitkan batas tetap; 3.500–6.000 Kbps di 1080p ideal. Memilih server regional terdekat sama pentingnya — mengurangi frame yang hilang."),
        ("Apakah SplitCam gratis untuk XLoveCam?", "Ya — gratis, tanpa watermark dan tanpa batas waktu. Menjangkau audiens Eropa multibahasa XLoveCam tidak butuh biaya software.")]),
    _p("soulcams", "SoulCams",
       "Siaran di SoulCams dengan SplitCam — Pengaturan OBS",
       "Siaran di SoulCams dengan SplitCam gratis — pengaturan OBS, server RTMP dan kunci, scene multi-kamera, dan overlay.",
       "soul cams, soulcams, siaran soulcams, soulcams obs, soulcams rtmp, soulcams broadcast",
       'Cara siaran di <span class="accent">SoulCams</span> dengan SplitCam',
       "Siaran SoulCams",
       "Pengaturan OBS untuk SoulCams.",
       "SoulCams adalah platform cam yang pengaturan OBS-nya menampilkan <strong style='color:var(--text)'>server RTMP dan stream key bersama</strong> di satu jendela. Tempel keduanya di <strong style='color:var(--text)'>SplitCam</strong> gratis untuk siaran dengan scene multi-kamera dan overlay.",
       "Siaran di SoulCams dengan SplitCam: pasang SplitCam, susun scene, di SoulCams klik Go Online → Settings → OBS, salin server dan kunci, tempel keduanya di SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + scene.</li><li>Buka SoulCams Settings → OBS.</li><li>Tempel server + kunci di SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di SoulCams masuk dan klik <strong>Go Online</strong>, lalu buka <strong>Settings</strong> → <strong>OBS</strong>. Jendela OBS menampilkan <strong>server RTMP</strong> dan <strong>stream key</strong> bersama — salin keduanya ke SplitCam.",
       [("Server dan kunci berdampingan", "SoulCams menampilkan server RTMP dan kunci di jendela OBS yang sama — ambil keduanya sekaligus."),
        ("Go Online dulu", "Pengaturan OBS muncul hanya setelah klik Go Online di SoulCams — lakukan itu sebelum mencari data encoder."),
        ("Blokir wilayah yang tidak diinginkan", "SoulCams mengizinkan blokir geo dari sisi model — pilih negara mana yang tidak bisa melihat stream sebelum tekan Go Online."),
        _T_ETH, _T_TEST],
       [("Di mana pengaturan OBS SoulCams?", "Masuk, klik Go Online, lalu Settings → OBS — server RTMP dan stream key ditampilkan bersama."),
        ("Apakah SoulCams mendukung encoder eksternal?", "Ya — pengaturan OBS memberi server RTMP dan kunci, jadi SplitCam berfungsi."),
        ("Bitrate berapa untuk SoulCams?", "SoulCams tidak memberi angka resmi — bidik 3.500–6.000 Kbps di 1080p dan tes upload, karena jendela OBS tidak menampilkan panduan bitrate."),
        ("Apakah SplitCam gratis untuk SoulCams?", "Ya — gratis, tanpa watermark dan tanpa batas waktu, jadi show SoulCams penuh dengan scene multi-kamera dan overlay tidak ada biaya di sisi encoder.")]),
    _p("imlive", "ImLive",
       "Siaran di ImLive dengan SplitCam — Kamera virtual",
       "Setup Im Live stream dengan SplitCam gratis — ImLive memakai webcam langsung (tanpa RTMP), hubungkan SplitCam sebagai kamera virtual dengan scene.",
       "im live stream, imlive splitcam, siaran imlive, imlive kamera virtual, imlive webcam, im live cam",
       'Cara memakai <span class="accent">ImLive</span> dengan SplitCam',
       "SplitCam di ImLive",
       "Pengaturan kamera virtual untuk ImLive — tanpa RTMP.",
       "ImLive memakai webcam langsung di browser — <strong style='color:var(--text)'>tidak ada RTMP maupun stream key</strong>. <strong style='color:var(--text)'>SplitCam</strong> gratis terhubung sebagai <strong style='color:var(--text)'>kamera virtual</strong>: susun scene di SplitCam, lalu pilih SplitCam sebagai kamera di ImLive.",
       "Memakai SplitCam dengan ImLive: pasang SplitCam, susun scene dengan media layer, buka ImLive dan mulai video chat, di pengaturan ImLive pilih SplitCam sebagai webcam dan mikrofon."
       "<ol><li>Pasang SplitCam.</li><li>Susun scene di SplitCam.</li><li>Mulai video chat di ImLive.</li><li>Pilih SplitCam sebagai kamera ImLive.</li><li>Mulai chat.</li></ol>",
       "Masuk ke situs ImLive dan klik <strong>Start Video Chat</strong>, lalu buka <strong>Go To Settings</strong> untuk mengakses opsi kamera dan mikrofon. Di pengaturan ImLive pilih <strong>SplitCam</strong> sebagai webcam dan mikrofon.",
       [("Tidak perlu stream key", "ImLive tidak punya RTMP — jangan cari URL server atau kunci. SplitCam hanya dipilih sebagai perangkat kamera."),
        ("Atur SplitCam sebagai mikrofon juga", "Pilih SplitCam untuk mikrofon selain kamera, agar mix audio dan peredam bising juga masuk ke live."),
        ("Susun scene sebelum live", "ImLive menampilkan apa yang dikirim SplitCam — atur lapisan sebelum mulai chat."),
        _T_TEST],
       [("Apakah ImLive memakai RTMP atau stream key?", "Tidak keduanya — ImLive memakai webcam langsung lewat browser. SplitCam terhubung sebagai kamera virtual, tidak ada kunci untuk disalin."),
        ("Bagaimana memilih SplitCam di ImLive?", "Start Video Chat → Go To Settings → pilih SplitCam sebagai webcam dan mikrofon."),
        ("Bisakah memakai overlay di ImLive?", "Ya — susun di scene SplitCam; ImLive menampilkan hasil gabungan."),
        ("Apakah SplitCam gratis untuk ImLive?", "Ya — gratis, tanpa watermark dan tanpa batas waktu. Sebagai kamera virtual untuk ImLive, tidak menambah biaya atau branding ke video chat-mu.")],
       steps=[
           ("Pasang SplitCam", "SplitCam adalah software gratis untuk Windows dan macOS. Pasang — tanpa watermark, tanpa daftar. Untuk ImLive ia bekerja sebagai <strong>kamera virtual</strong>, bukan encoder RTMP."),
           ("Susun scene di SplitCam", "Buka SplitCam dan gunakan <strong>Media Layers +</strong> untuk menambah webcam plus overlay, teks, filter, atau latar AI apa pun. Scene gabungan inilah yang akan dilihat ImLive sebagai kameramu."),
           ("Mulai video chat di ImLive", "Masuk ke situs ImLive dan klik <strong>Start Video Chat</strong>, lalu buka <strong>Go To Settings</strong> untuk mengakses opsi kamera dan mikrofon."),
           ("Pilih SplitCam sebagai kamera", "Di pengaturan ImLive pilih <strong>SplitCam</strong> sebagai webcam DAN mikrofon. ImLive kini menampilkan scene SplitCam lengkapmu, bukan webcam datar."),
           ("Mulai Free Live Chat", "Klik <strong>Free Live Chat</strong> di ImLive untuk live. Untuk mengubah tampilan di tengah sesi, edit scene di SplitCam — ImLive memperbarui seketika."),
       ]),
    _p("vxlive", "VXLive",
       "Siaran di VXLive dengan SplitCam — Dukungan resmi",
       "Siaran di VXLive (VXModels / VISIT-X) dengan SplitCam gratis — preset VISIT-X resmi, server dan kunci, scene. Tanpa watermark.",
       "vxlive, visit-x, vxmodels splitcam, siaran vxlive, visit-x stream, vxlive rtmp",
       'Cara siaran di <span class="accent">VXLive</span> dengan SplitCam',
       "Siaran VXLive",
       "VXLive mendukung SplitCam secara resmi (preset VISIT-X).",
       "VXLive (VXModels / VISIT-X) adalah platform cam dari pasar Jerman — dan salah satu dari sedikit yang <strong style='color:var(--text)'>mendukung SplitCam secara resmi dengan nama</strong>. VXModels punya artikel bantuan khusus untuk menghubungkan <strong style='color:var(--text)'>SplitCam</strong> ke VXLive, dan SplitCam menyediakan VISIT-X sebagai preset kanal siap pakai.",
       "Siaran di VXLive dengan SplitCam: pasang SplitCam, susun scene, di VXLive pilih «Stream with third-party software», salin URL server dan kunci, di SplitCam pilih preset VISIT-X dan tempel, Go Live di SplitCam, lalu GO ONLINE di VXLive."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + scene.</li><li>Ambil URL server + kunci dari VXLive.</li><li>Pilih preset VISIT-X di SplitCam, tempel.</li><li>Go Live, lalu GO ONLINE di VXLive.</li></ol>",
       "Di VXLive pilih <strong>Stream with third-party software</strong> dan pilih opsi <strong>OBS, SplitCam, atau XSplit</strong>. VXLive menyediakan <strong>URL server</strong> dan <strong>stream key</strong>. Di SplitCam pilih <strong>VISIT-X</strong> sebagai platform streaming, tempel keduanya, tekan <strong>Go Live</strong> di SplitCam, lalu <strong>GO ONLINE</strong> di VXLive.",
       [("VISIT-X adalah preset terintegrasi", "Jangan ketik URL RTMP mentah — SplitCam punya VISIT-X di daftar platform; cukup pilih dan tempel URL server dan kunci."),
        ("Go-live dua langkah", "Di VXLive tekan Go Live di SplitCam dulu, lalu GO ONLINE di VXLive — keduanya, dalam urutan itu."),
        ("Pasar Jerman", "Audiens VXLive mayoritas berbahasa Jerman — overlay teks atau judul Jerman membantu terhubung dengan penonton."),
        _T_ETH],
       [("Apakah VXLive mendukung SplitCam secara resmi?", "Ya — VXModels (VXLive) memelihara artikel bantuan resmi khusus untuk setup SplitCam dan mencantumkan SplitCam bersama OBS dan XSplit sebagai software siaran yang didukung."),
        ("Bagaimana menghubungkan SplitCam ke VXLive?", "Di VXLive pilih «Stream with third-party software», lalu di SplitCam pilih preset VISIT-X dan tempel URL server serta stream key yang diberikan VXLive."),
        ("Apakah saya live di SplitCam atau VXLive?", "Keduanya — Go Live di SplitCam dulu, lalu GO ONLINE di VXLive."),
        ("Kenapa VXModels menyarankan SplitCam?", "Artikel bantuan resmi VXModels menyarankan SplitCam khusus untuk menghilangkan artefak gambar webcam dan pikselasi serta menstabilkan koneksi — bukan sekadar encoder umum.")]),
    _p("virtwish", "VirtWish",
       "Siaran di VirtWish dengan SplitCam — URL stream & kunci",
       "Siaran di VirtWish dengan SplitCam gratis — bagian OBS Profile → Start Broadcast, URL stream dan kunci, scene, dan overlay.",
       "virtwish, siaran virtwish, virtwish broadcasting software, virtwish rtmp, virtwish stream key, virtwish obs",
       'Cara siaran di <span class="accent">VirtWish</span> dengan SplitCam',
       "Siaran VirtWish",
       "Pengaturan URL stream + kunci untuk VirtWish.",
       "VirtWish adalah platform cam interaktif. Pengaturan siaran memberimu <strong style='color:var(--text)'>URL stream dan stream key terpisah</strong> di bagian OBS — <strong style='color:var(--text)'>SplitCam</strong> gratis mengambil keduanya dan menjalankan show dengan scene dan overlay.",
       "Siaran di VirtWish dengan SplitCam: pasang SplitCam, susun scene, di VirtWish buka <em>Profile → Start Broadcast</em> hingga bagian OBS, salin tautan dan kunci, tempel keduanya di SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + scene.</li><li>Ambil URL + kunci dari VirtWish.</li><li>Tempel keduanya di SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di VirtWish klik ikon di pojok kanan atas → <strong>Profile</strong> → <strong>Start Broadcast</strong>, lalu <strong>Start Broadcast</strong> lagi untuk mencapai bagian OBS. <strong>Salin tautan di baris pertama</strong> ke kolom Stream URL SplitCam, dan <strong>Stream Key</strong> terpisah ke kolom kunci.",
       [("Tautan di baris pertama", "Bagian OBS VirtWish menaruh URL stream di baris pertama — salin ke Stream URL SplitCam, lalu kunci terpisah."),
        ("Dua klik di Start Broadcast", "Kamu klik Start Broadcast dua kali di VirtWish untuk mencapai bagian OBS — itu wajar, bukan bug."),
        _T_ETH, _T_TEST],
       [("Di mana data RTMP VirtWish?", "Ikon kanan atas → Profile → Start Broadcast dua kali → bagian OBS menampilkan tautan dan stream key."),
        ("Apakah VirtWish mendukung encoder eksternal?", "Ya — bagian OBS menyediakan URL stream dan kunci, jadi SplitCam berfungsi."),
        ("Bitrate berapa untuk VirtWish?", "VirtWish tidak menerbitkan plafon resmi; 3.500–6.000 Kbps di 1080p aman. Samakan resolusi SplitCam dengan yang diatur di VirtWish untuk menghindari penskalaan ulang."),
        ("Apakah SplitCam gratis untuk VirtWish?", "Ya — gratis, tanpa watermark dan tanpa batas waktu. Pengaturan URL-dan-kunci VirtWish hanya memakan beberapa menit yang dibutuhkan.")]),
    _p("xmodels", "XModels",
       "Siaran di XModels dengan SplitCam — Panduan gratis",
       "Siaran di XModels dengan SplitCam gratis — opsi encoder eksternal di pengaturan akun model, kunci RTMP, scene, dan overlay.",
       "xmodels, siaran xmodels, xmodels broadcasting software, xmodels rtmp, xmodels encoder eksternal",
       'Cara siaran di <span class="accent">XModels</span> dengan SplitCam',
       "Siaran XModels",
       "Pengaturan encoder eksternal untuk siaran XModels.",
       "XModels adalah platform cam-streaming dengan <strong style='color:var(--text)'>opsi encoder eksternal</strong> bawaan di pengaturan akun model. <strong style='color:var(--text)'>SplitCam</strong> gratis siaran di sana dengan scene multi-kamera, overlay, dan filter, bukan satu kamera datar.",
       "Siaran di XModels dengan SplitCam: pasang SplitCam, susun scene, di akun model XModels aktifkan opsi encoder eksternal, salin URL server dan stream key, tempel di SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + scene.</li><li>Aktifkan encoder eksternal di pengaturan XModels.</li><li>Tempel URL server + kunci di SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di <strong>pengaturan akun model</strong> XModels, aktifkan opsi <strong>siaran via encoder eksternal</strong>. XModels menyediakan <strong>stream key</strong> — salin ke SplitCam. Jika opsi tidak ada di tempat yang kamu harapkan, dukungan XModels lewat chat FAQ di situs dan <strong>info@xmodels.com</strong>; video di atas juga menunjukkannya.",
       [("Ada di pengaturan akun", "XModels menaruh opsi encoder eksternal di pengaturan akun model, bukan di layar siaran terpisah."),
        ("Dukungan: chat + email", "XModels tidak punya pusat bantuan publik besar — chat FAQ di situs dan info@xmodels.com adalah kanal dukungan resmi."),
        ("Tumpuk overlay di SplitCam", "Target tip, nama, dan handle media sosial sebagai lapisan scene — kamera dasar XModels tidak menambahkannya."),
        _T_ETH],
       [("Apakah XModels mendukung encoder eksternal?", "Ya — pengaturan akun model menyertakan opsi siaran encoder eksternal yang menyediakan stream key, jadi SplitCam berfungsi."),
        ("Di mana mendapat bantuan XModels?", "Dukungan XModels lewat chat FAQ di situs dan email info@xmodels.com — tidak ada pusat bantuan publik besar."),
        ("Bitrate berapa untuk XModels?", "XModels tidak mendokumentasikan angka resmi — pakai 3.500–6.000 Kbps di 1080p dan jalankan tes kecepatan SplitCam, karena dukungan XModels hanya chat dan email."),
        ("Apakah SplitCam gratis untuk XModels?", "Ya — gratis, tanpa watermark dan tanpa batas waktu, jadi siaran ke jaringan Eropa XModels tidak menambah biaya software.")]),
    _p("flirt4free", "Flirt4Free",
       "Siaran di Flirt for Free cam dengan SplitCam — Panduan gratis",
       "Siaran di Flirt for Free cam dengan SplitCam gratis — External Broadcast Form, RTMP URL dan Stream Name, scene, dan overlay.",
       "flirt for free cam, flirt 4 free cam, flirt4free, siaran flirt4free, flirt4free external broadcast, flirt4free rtmp",
       'Cara siaran di <span class="accent">Flirt4Free</span> dengan SplitCam',
       "Siaran Flirt4Free",
       "Pengaturan External Broadcast Form untuk Flirt4Free.",
       "Flirt4Free adalah salah satu platform cam tertua, mengudara sejak 90-an. Mendukung siaran eksternal secara resmi via <strong style='color:var(--text)'>External Broadcast Form</strong> — <strong style='color:var(--text)'>SplitCam</strong> gratis mengirim stream sementara form mengatur resolusi dan bitrate.",
       "Siaran di Flirt4Free dengan SplitCam: pasang SplitCam, susun scene, buka External Broadcast Form Flirt4Free, salin RTMP URL dan Stream Name serta atur resolusi/bitrate, tempel di SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + scene.</li><li>Buka External Broadcast Form Flirt4Free.</li><li>Tempel RTMP URL + Stream Name di SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di area model Flirt4Free buka <strong>External Broadcast Form</strong>. Berbeda dari kebanyakan situs cam, Flirt4Free memberi <strong>RTMP URL</strong> dan <strong>Stream Name</strong> (bukan «kunci»), plus kolom resolusi dan bitrate yang kamu isi di form itu sendiri. Salin URL dan Stream Name ke kolom server dan kunci SplitCam.",
       [("Itu Stream Name, bukan kunci", "Flirt4Free menyebut kredensialnya Stream Name. Kamu tempel ke kolom stream key SplitCam — fungsinya sama."),
        ("Atur resolusi/bitrate di form", "External Broadcast Form Flirt4Free punya kolom resolusi dan bitrate sendiri — sejajarkan dengan pengaturan SplitCam agar gambar tidak diskala ulang."),
        ("Platform bersejarah", "Flirt4Free berjalan sejak 90-an — alat model-nya matang, dan External Broadcast Form adalah bagian terdokumentasi darinya."),
        _T_ETH],
       [("Apakah Flirt4Free mendukung encoder eksternal?", "Ya — secara resmi, via External Broadcast Form yang menyediakan RTMP URL dan Stream Name. SplitCam berfungsi sebagai encoder."),
        ("Di mana mendapat data RTMP Flirt4Free?", "Dari External Broadcast Form di area model — menampilkan RTMP URL, Stream Name, dan kolom resolusi/bitrate."),
        ("Bitrate berapa untuk Flirt4Free?", "3.500–6.000 Kbps di 1080p — atur nilai sama di External Broadcast Form dan di SplitCam."),
        ("Apakah SplitCam gratis untuk Flirt4Free?", "Ya — gratis, tanpa watermark dan tanpa batas waktu, cocok dengan platform bersejarah seperti Flirt4Free yang show-nya bisa panjang.")]),
    _p("mfc-alerts", "MFC Alerts",
       "Tambah MFC Alerts ke siaran dengan SplitCam",
       "Tampilkan tip alert animasi di siaran MyFreeCams — URL mfcalerts.com sebagai lapisan Browser di SplitCam gratis, di atas webcam.",
       "mfc alerts, myfreecams alerts, tambah mfc alerts, mfcalerts splitcam, myfreecams tip alerts, myfreecams alerts overlay",
       'Cara menambah <span class="accent">MFC Alerts</span> ke siaranmu',
       "Tambah MFC Alerts",
       "Tampilkan tip alert animasi di siaran MyFreeCams.",
       "MFC Alerts menampilkan efek animasi di siaran MyFreeCams-mu setiap kali penonton mengirim tip. Berjalan sebagai <strong style='color:var(--text)'>lapisan Browser</strong> di dalam <strong style='color:var(--text)'>SplitCam</strong> gratis — atur sekali dan tip memicu reaksi di layar secara live.",
       "Menambah MFC Alerts dengan SplitCam: pasang SplitCam, tambah webcam, buka tab Browser dan muat mfcalerts.com, salin URL alert-mu, tambah sebagai lapisan Browser di atas webcam, lalu uji dengan tip tes."
       "<ol><li>Pasang SplitCam.</li><li>Tambah webcam.</li><li>Ambil URL di mfcalerts.com.</li><li>Tambah sebagai lapisan Browser di atas webcam.</li><li>Kirim tip tes.</li></ol>",
       "Di SplitCam buka tab <strong>Browser</strong> dan buka <strong>www.mfcalerts.com</strong>. Masuk atau daftar. Gunakan <strong>Copy to clipboard</strong> untuk menyalin URL alert pribadimu. Tempel URL ke jendela Browser SplitCam dan klik <strong>Add</strong>. Lalu atur ulang daftar sumber agar <strong>MFC Alerts di atas webcam</strong> (menu 3 titik → Move Up).",
       [("MFC Alerts harus di atas webcam", "Kesalahan paling umum: jika lapisan MFC Alerts di bawah webcam di daftar sumber, efek tetap tersembunyi. Pindahkan ke atas."),
        ("Perlu akun mfcalerts.com", "URL alert bersifat pribadi — daftar di mfcalerts.com dulu jika belum punya akun."),
        ("Kirim tip tes sebelum live", "Gunakan Settings → Send test tip untuk memastikan overlay bekerja — jangan menemukan kesalahan di tengah show."),
        _T_ETH],
       [("Apa itu MFC Alerts?", "Sistem notifikasi untuk MyFreeCams yang menampilkan efek video di siaranmu saat penonton mengirim tip — ditambahkan sebagai overlay Browser di SplitCam."),
        ("Kenapa MFC Alerts saya tidak muncul?", "Hampir selalu urutan lapisan — lapisan Browser MFC Alerts harus di atas webcam di daftar sumber SplitCam."),
        ("Apakah perlu akun untuk MFC Alerts?", "Ya — daftar di mfcalerts.com untuk mendapat URL alert pribadimu."),
        ("Apakah SplitCam gratis untuk ini?", "Ya — SplitCam gratis, tanpa watermark dan tanpa batas waktu, dan overlay browser MFC Alerts berjalan di dalamnya tanpa biaya tambahan.")],
       steps=[
           ("Pasang SplitCam dan tambah webcam", "Pasang SplitCam gratis untuk Windows atau macOS, lalu tambahkan <strong>webcam</strong> sebagai sumber. MFC Alerts duduk sebagai lapisan di atas kamera ini."),
           ("Buka tab Browser dan ke mfcalerts.com", "Di SplitCam buka tab <strong>Browser</strong> dan buka <strong>www.mfcalerts.com</strong>. Masuk, atau daftar jika belum punya akun mfcalerts.com."),
           ("Salin URL alert-mu", "Di mfcalerts.com gunakan <strong>Copy to clipboard</strong> untuk menyalin URL alert pribadimu — inilah halaman yang merender animasi tip."),
           ("Tambah URL sebagai lapisan Browser — di atas webcam", "Tempel URL ke jendela Browser SplitCam dan klik <strong>Add</strong>. Lalu atur ulang daftar sumber agar <strong>MFC Alerts di atas webcam</strong> (menu 3 titik → Move Up). Jika di bawah, efek tetap tersembunyi."),
           ("Uji dengan tip tes", "Buka <strong>Settings → Send test tip</strong> dan pastikan efek alert muncul di atas kamera. Lalu siaran normal di MyFreeCams — tip asli kini memicu animasi."),
       ]),
    _p("lovense", "Lovense",
       "Tambah mainan Lovense ke siaran dengan SplitCam",
       "Hubungkan mainan Lovense interaktif ke siaran cam dengan SplitCam gratis — Lovense SplitCam Toolset, tip alert di layar, reaksi.",
       "tambah lovense ke siaran, lovense cam stream, lovense splitcam, lovense splitcam toolset, lovense interactive toy streaming",
       'Cara menambah <span class="accent">mainan Lovense</span> ke siaranmu',
       "Tambah mainan Lovense",
       "Hubungkan mainan Lovense interaktif ke siaran cam-mu.",
       "Kamu menjalankan siaran cam lewat <strong style='color:var(--text)'>SplitCam</strong> gratis dan memasangkan mainan <strong style='color:var(--text)'>Lovense</strong> yang bereaksi pada token. Lovense mendokumentasikan <strong style='color:var(--text)'>Lovense SplitCam Toolset</strong> resmi, dan SplitCam menyediakan plugin Lovense resmi — integrasi didukung dari kedua sisi.",
       "Untuk menambah mainan Lovense ke siaran: pasang SplitCam dan software Lovense, pasangkan mainan, hubungkan Lovense ke platform cam-mu, tambahkan status Lovense sebagai lapisan Browser di SplitCam, lalu siaran normal."
       "<ol><li>Pasang SplitCam.</li><li>Pasang software Lovense dan pasangkan mainan.</li><li>Hubungkan Lovense ke situs cam-mu.</li><li>Tambah overlay Lovense di SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Pasang Lovense Connect / Lovense Stream (aplikasi desktop resmi). Nyalakan mainan dan pasangkan via Bluetooth agar aplikasi menampilkan terhubung. Di aplikasi Lovense hubungkan akun cam-mu agar mainan bereaksi pada token / tip penonton. Lovense menyediakan URL overlay / widget — tambahkan sebagai lapisan <strong>Browser</strong> di scene SplitCam.",
       [("Pakai Lovense SplitCam Toolset resmi", "Lovense menerbitkan toolset khusus SplitCam dengan panduan pemasangan sendiri — menambahkan overlay aktivitas mainan dan tip alert yang dibuat untuk SplitCam."),
        ("Perbarui Lovense Cam Extension", "Toolset butuh Lovense Cam Extension terbaru (30.1.4 atau lebih baru) — perbarui sebelum live."),
        ("Jaga mainan tetap terisi", "Baterai hampir habis di tengah show mematikan sisi interaktif — isi penuh sebelum live."),
        ("Uji reaksi token", "Kirim tip tes kecil untuk memastikan mainan bereaksi sebelum membuka room."),
        ("Cek persyaratan versi", "Lovense SplitCam Toolset butuh SplitCam 10.4.5 atau lebih baru. Lovense Cam Extension secara resmi mencakup Chaturbate, Stripchat, BongaCams, MyFreeCams, dan CamSoda — untuk situs lain, pakai integrasi Generic URL Lovense.")],
       [("Apakah Lovense mendukung SplitCam secara resmi?", "Ya — Lovense mendokumentasikan «Lovense SplitCam Toolset» resmi dengan panduan pemasangan sendiri, dan SplitCam menyediakan plugin Lovense resmi. Integrasi didukung dari kedua sisi."),
        ("Apakah mainan terhubung langsung ke SplitCam?", "Tidak — mainan dipasangkan dengan aplikasi Lovense; SplitCam menampilkan overlay Lovense dan menyiarkan kamera."),
        ("Situs cam mana yang mendukung Lovense?", "Lovense Cam Extension secara resmi mendukung Chaturbate, Stripchat, BongaCams, MyFreeCams, dan CamSoda, dengan dukungan bervariasi untuk lainnya — cek daftar terkini di aplikasi Lovense."),
        ("Bisakah menampilkan tip terbaru di layar?", "Ya — tambahkan URL widget Lovense sebagai lapisan Browser di SplitCam.")],
       steps=[
           ("Pasang SplitCam", "SplitCam adalah software live-streaming gratis untuk Windows dan macOS — encoder yang mengirim videomu ke platform cam. Pasang; tanpa watermark."),
           ("Pasang software Lovense dan pasangkan mainan", "Pasang Lovense Connect / Lovense Stream (aplikasi desktop resmi). Nyalakan mainan dan pasangkan via Bluetooth agar aplikasi menampilkan terhubung."),
           ("Hubungkan Lovense ke platform cam", "Di aplikasi Lovense hubungkan akun cam-mu agar mainan bereaksi pada token / tip penonton. Sebagian besar platform cam besar didukung."),
           ("Tambah overlay Lovense di SplitCam", "Lovense menyediakan URL overlay / widget. Tambahkan sebagai lapisan <strong>Browser</strong> di scene SplitCam agar penonton melihat status mainan dan tip terbaru di layar."),
           ("Susun scene dan Go Live", "Tambah kamera dan overlay lain, tempel kunci RTMP platform cam ke SplitCam dan klik <strong>Go Live</strong>. Mainan bereaksi pada tip secara real time."),
       ]),
    _p("multistream-cams", "Beberapa situs cam",
       "Siaran ke beberapa situs cam sekaligus dengan SplitCam",
       "Siaran ke MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat, dan lainnya sekaligus dengan multistream gratis SplitCam. Satu klik, tanpa watermark.",
       "siaran ke beberapa situs cam, multistream cam sites, siaran chaturbate dan bongacams sekaligus, software multistream cam",
       'Cara siaran ke <span class="accent">beberapa situs cam</span> sekaligus',
       "Multistream cam",
       "Siaran ke beberapa situs cam sekaligus.",
       "<strong style='color:var(--text)'>SplitCam</strong> gratis bisa menyiarkan satu encoding ke <strong style='color:var(--text)'>beberapa situs cam sekaligus</strong> — MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat, dan lainnya. Tanpa watermark, satu klik.",
       "Untuk siaran ke beberapa situs cam sekaligus: pasang SplitCam, susun scene, ambil URL server RTMP dan stream key tiap situs cam, tambahkan semua ke pengaturan multistream SplitCam, klik Go Live sekali."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + scene.</li><li>Ambil kunci RTMP dari tiap situs cam.</li><li>Tambah semua kunci ke multistream SplitCam.</li><li>Tekan Go Live sekali.</li></ol>",
       "Di tiap platform cam aktifkan siaran eksternal / RTMP dan salin <strong>URL server</strong> dan <strong>stream key</strong>. Di SplitCam buka <strong>Stream Settings</strong> dan tambahkan tiap situs cam sebagai tujuan RTMP kustom — tempel URL server dan kunci. Centang semua yang ingin kamu livenya. Tekan <strong>Go Live</strong>.",
       [("Perhatikan upload-mu", "Multistream melipatgandakan beban upload. Tiap tujuan memakai bitrate-nya sendiri — pastikan koneksimu sanggup menanggung totalnya."),
        ("Cek aturan platform", "Beberapa situs cam melarang siaran serentak di tempat lain — pastikan sebelum multistream."),
        ("Kabel — di sini tak boleh putus", "Multistream melipatgandakan beban upload, jadi satu putus wi-fi bisa menjatuhkan semua tujuan sekaligus. Kabel di sini tidak opsional."),
        ("Pantau monitor kesehatan", "SplitCam menampilkan status per tujuan — lepas satu situs jika upload tak sanggup.")],
       [("Apakah multistream SplitCam gratis?", "Ya — multistream bawaan dan gratis, tanpa biaya per tujuan, tanpa watermark."),
        ("Berapa banyak situs cam bisa saya siarkan sekaligus?", "Sebanyak yang sanggup ditanggung bandwidth upload-mu — tiap tujuan memakai bitrate-nya sendiri."),
        ("Apakah memakai cloud relay?", "Tidak — SplitCam mengirim stream peer-to-peer langsung dari PC ke ingest tiap platform."),
        ("Apakah multistream memperlambat PC saya?", "Encoding dilakukan sekali dan dipakai ulang; encoding perangkat keras menjaga beban CPU rendah. Bandwidth upload adalah batas sebenarnya.")],
       steps=[
           ("Pasang SplitCam", "SplitCam adalah software live-streaming gratis untuk Windows dan macOS dengan multistream bawaan. Pasang — tanpa watermark, tanpa daftar."),
           ("Atur kamera dan scene", "Buka SplitCam, tambah webcam dan susun scene dengan overlay dan filter. Satu scene memberi makan tiap tujuan."),
           ("Ambil kunci RTMP dari tiap situs cam", "Di tiap platform cam aktifkan siaran eksternal / RTMP dan salin <strong>URL server</strong> dan <strong>stream key</strong>. Ulangi untuk tiap situs yang ingin kamu siarkan — lihat panduan platform masing-masing untuk jalur tepatnya."),
           ("Tambah tiap tujuan di SplitCam", "Buka <strong>Stream Settings</strong> dan tambahkan tiap situs cam sebagai tujuan RTMP kustom — tempel URL server dan kunci. Centang semua yang ingin kamu livenya."),
           ("Klik Go Live sekali", "Tekan <strong>Go Live</strong>. SplitCam mengirim stream ke tiap situs cam terpilih sekaligus, peer-to-peer, dari satu encoding — tanpa biaya tambahan."),
       ]),
    _p("livejasmin", "LiveJasmin",
       "Siaran di LiveJasmin dengan SplitCam — Encoder eksternal HD",
       "Siaran di LiveJasmin dengan SplitCam gratis — encoder eksternal Model Center, setup HD 1080p, scene multi-kamera, dan overlay. Tanpa watermark, tanpa daftar.",
       "siaran livejasmin, livejasmin obs, livejasmin encoder eksternal, livejasmin rtmp, livejasmin stream key, setup model livejasmin",
       'Cara siaran di <span class="accent">LiveJasmin</span> dengan SplitCam',
       "Siaran LiveJasmin",
       "Setup encoder eksternal untuk Model Center LiveJasmin yang HD-only.",
       "LiveJasmin adalah unggulan Docler Holding — salah satu jaringan cam terbesar di dunia dan platform HD-only. Broadcaster yang direkomendasikan adalah klien <strong>JasminCAM</strong> milik mereka sendiri, tapi Model Center juga membuka jalur <strong>External Encoder</strong> standar — <strong style='color:var(--text)'>SplitCam</strong> gratis terhubung ke sini, memungkinkanmu siaran dengan scene multi-kamera, filter kecantikan, dan overlay di stream HD yang sama.",
       "Siaran di LiveJasmin dengan SplitCam: pasang SplitCam, susun scene HD, di Model Center buka <em>Settings → Broadcast → External Encoder</em>, salin URL server dan stream key, tempel di SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + scene HD.</li><li>Ambil URL dan stream key dari Model Center.</li><li>Tempel di SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Masuk ke <strong>modelcenter.livejasmin.com</strong>, buka <strong>Settings → Broadcast → External Encoder</strong>. Model Center menampilkan <strong>URL server</strong> dan <strong>stream key</strong> yang terikat ke akunmu — salin keduanya ke kolom RTMP kustom di SplitCam. <strong>Catatan:</strong> akun baru harus disetujui dulu (48–72 jam) sebelum opsi External Encoder muncul, dan platform memberlakukan output HD-only.",
       [("HD atau ranking turun", "LiveJasmin HD-only — apa pun di bawah 1280×720 berisiko hanya tampil di daftar berbayar rendah, di bawah 1080p kehilangan kelayakan 'Premium'. Targetkan 1920×1080 di 30 fps, 4.000–6.000 Kbps."),
        ("JasminCAM vs encoder eksternal", "Klien JasminCAM milik Docler memberi kepatuhan HD paling bersih, tapi encoder eksternal (OBS, SplitCam, vMix) didukung resmi setelah akunmu disetujui — mereka membuka scene multi-kamera dan overlay yang tak bisa dilakukan JasminCAM."),
        ("Free chat ≠ private show", "Free chat hanya pratinjau — tanpa ketelanjangan. Private dan Gold show adalah tempat model menghasilkan. Rancang scene-mu supaya terlihat kuat baik berpakaian maupun di mode show."),
        _T_ETH],
       [("Apakah LiveJasmin secara resmi mendukung encoder eksternal seperti SplitCam?", "Ya — Model Center menyertakan opsi External Encoder di Settings → Broadcast. JasminCAM adalah klien yang direkomendasikan, tapi OBS, SplitCam, dan encoder RTMP lain secara eksplisit terdaftar didukung setelah akun model-mu disetujui."),
        ("Di mana saya ambil stream key LiveJasmin?", "Di dalam Model Center: Settings → Broadcast → External Encoder. URL server dan stream key unik muncul di sana — salin keduanya ke kolom RTMP kustom SplitCam. Kuncinya terikat ke akun; perlakukan seperti kata sandi."),
        ("Bitrate berapa untuk LiveJasmin?", "LiveJasmin HD-only — targetkan 1920×1080 di 30 fps, 4.000–6.000 Kbps dengan interval keyframe 2 detik. Di bawah itu jauh akan kehilangan label Premium dan ranking turun."),
        ("Apakah SplitCam gratis untuk LiveJasmin?", "Ya — SplitCam gratis, tanpa watermark dan tanpa batas waktu. Satu-satunya 'biaya' adalah memenuhi syarat HD LiveJasmin, yang ditangani SplitCam secara native dengan komposisi scene 1080p dan filter kecantikan.")],
       steps=[
           ("Download dan pasang SplitCam", "SplitCam adalah software live-streaming gratis untuk Windows dan macOS — tanpa daftar, tanpa kartu, tanpa watermark. Ia adalah encoder yang mengirim video HD-mu ke LiveJasmin."),
           ("Susun scene HD-mu", "Buka SplitCam dan tambahkan webcam di mode 1080p. Tumpuk overlay, teks, kamera kedua atau HP, filter kecantikan, atau latar AI — LiveJasmin butuh kualitas HD dan scene yang kamu susun harus terlihat premium sepanjang free chat DAN private show."),
           ("Ambil URL dan stream key LiveJasmin", "Masuk ke <strong>modelcenter.livejasmin.com</strong> (akunmu harus disetujui dulu — biasanya 48–72 jam setelah daftar). Buka <strong>Settings → Broadcast → External Encoder</strong>. Halaman menampilkan <strong>URL server</strong> dan <strong>stream key</strong> unik. Salin keduanya."),
           ("Hubungkan SplitCam ke LiveJasmin", "Di SplitCam buka <strong>Stream Settings</strong>, tempel URL server LiveJasmin dan stream key ke kolom RTMP kustom. Atur bitrate 4.000–6.000 Kbps di 1920×1080, 30 fps, dengan keyframe 2 detik. Jalankan tes kecepatan bawaan dulu — stream HD menuntut bandwidth."),
           ("Klik Go Live", "Tekan <strong>Go Live</strong> di SplitCam, lalu online di LiveJasmin Model Center. Dalam ~10 detik feed HD-mu sampai ke jaringan LiveJasmin. Siaran berikutnya cukup satu klik — buka SplitCam, Go Live, lalu online di LiveJasmin."),
       ]),
    _p("myfreecams", "MyFreeCams",
       "Cara siaran di MyFreeCams (MFC) dengan SplitCam — bypass Model Web Broadcaster",
       "Siaran di MyFreeCams dengan SplitCam gratis — Model Admin external broadcaster, ekonomi token MFC, scene multi-kamera, overlay. Tanpa watermark, tanpa daftar.",
       "siaran myfreecams, mfc external broadcaster, myfreecams obs, mfc rtmp, mfc stream key, model admin, mfc token",
       'Cara siaran di <span class="accent">MyFreeCams</span> dengan SplitCam',
       "Siaran MyFreeCams",
       "Setup external broadcaster untuk Model Admin MFC yang berbasis token.",
       "MyFreeCams (MFC) adalah salah satu platform cam tertua — ekonomi token murni, tanpa gauntlet persetujuan model, dan basis member Premium yang setia. Model Web Broadcaster default-nya adalah tool browser satu-kamera, tapi Model Admin juga membuka opsi <strong>External Broadcaster</strong> yang dihubungkan oleh <strong style='color:var(--text)'>SplitCam</strong> gratis — membuka scene multi-kamera, overlay, dan filter di stream token yang sama.",
       "Siaran di MFC dengan SplitCam: pasang SplitCam, susun scene, Model Admin → Broadcaster, ganti dari Web Broadcaster ke External Broadcaster, salin URL server dan key, tempel di SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Susun scene.</li><li>Model Admin → Broadcaster, ganti ke External Broadcaster.</li><li>Salin URL + key, tempel di SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Masuk ke MyFreeCams, buka <strong>Model Admin → Broadcaster</strong>, ganti dari <strong>Web Broadcaster</strong> ke <strong>External Broadcaster</strong>. Halaman menampilkan <strong>URL server</strong> (<strong>rtmp://publish.myfreecams.com…</strong>) dan <strong>stream key</strong> yang terikat ke akun model — salin keduanya ke kolom RTMP kustom di SplitCam. Key terikat ke akun.",
       [("MFC adalah ekonomi tip/token murni", "MFC tidak berjalan di model langganan — murni tip dan token. Rancang scene-mu agar mendukung aliran tip: counter target di layar, tip menu, dan call-to-action yang jelas."),
        ("Web Broadcaster vs External — pilih sekali", "Di Model Admin → Broadcaster kamu pilih Web Broadcaster (satu kamera, browser) atau External Broadcaster (RTMP). Ganti ke External sebelum go live — di sinilah SplitCam, OBS, dan vMix terhubung."),
        ("Tambah MFC Alerts sebagai layer Browser", "Tambahkan URL <strong>mfcalerts.com</strong> sebagai layer Browser di SplitCam di atas kamera — alert tip, goal bar, dan notifikasi muncul real-time di atas siaran, mendorong member untuk berkontribusi."),
        _T_ETH],
       [("Apakah MFC mendukung encoder eksternal seperti SplitCam?", "Ya — lewat External Broadcaster di Model Admin. Siaran RTMP standar bekerja resmi dengan OBS, SplitCam, dan vMix; cukup pilih External Broadcaster (bukan Web Broadcaster) di Model Admin → Broadcaster."),
        ("Di mana saya ambil stream key MFC?", "Di dalam Model Admin → Broadcaster → External Broadcaster. Halaman menampilkan URL server yang mengarah ke <strong>publish.myfreecams.com</strong> dan stream key yang terikat ke akun model — tempel keduanya ke kolom RTMP kustom SplitCam."),
        ("Bitrate berapa untuk MFC?", "MFC mendukung hingga ~6.000 Kbps dengan keyframe push 2 detik. Targetkan 1920×1080 di 30 fps, 3.500–6.000 Kbps — pertahankan setinggi yang dimampu koneksimu, basis Premium peka kualitas HD."),
        ("Apakah SplitCam gratis untuk MFC?", "Ya — SplitCam gratis, tanpa watermark, tanpa batas waktu. Kamu bisa kirim multi-kamera, beauty filter, dan overlay MFC Alerts ke MFC lewat jalur External Broadcaster.")],
       steps=[
           ("Pasang SplitCam", "SplitCam adalah software live-streaming gratis untuk Windows dan macOS — tanpa daftar, tanpa kartu, tanpa watermark. Ia adalah encoder yang mengirim siaranmu ke endpoint RTMP MFC."),
           ("Susun scene-mu", "Di SplitCam tambahkan webcam, tumpuk overlay, beauty filter, dan kamera kedua. Tambahkan <strong>mfcalerts.com</strong> sebagai layer Browser di atas kamera — alert tip dan goal bar muncul real-time di atas stream-mu."),
           ("Model Admin → Broadcaster → External Broadcaster", "Masuk ke MyFreeCams, buka <strong>Model Admin → Broadcaster</strong> dan ganti dari <strong>Web Broadcaster</strong> ke <strong>External Broadcaster</strong>. Halaman menampilkan URL server yang mengarah ke <strong>publish.myfreecams.com</strong> dan stream key unik akun — salin keduanya."),
           ("Hubungkan SplitCam ke MFC", "Di SplitCam buka <strong>Stream Settings</strong>, tempel URL server dan stream key MFC ke kolom RTMP kustom. Atur bitrate 3.500–6.000 Kbps di 1920×1080, 30 fps, dengan keyframe 2 detik."),
           ("Klik Go Live", "Tekan <strong>Go Live</strong> di SplitCam — MFC menerima stream dalam hitungan detik dan room-mu live di ekonomi token. Siaran berikutnya cukup satu klik."),
       ]),
    _p("cherry-tv", "Cherry.tv",
       "Cara siaran di Cherry.tv dengan SplitCam — encoder eksternal Web3-friendly",
       "Siaran di Cherry.tv dengan SplitCam gratis — encoder eksternal Streamer Dashboard, platform cam ramah kripto, scene multi-kamera. Tanpa watermark, tanpa daftar.",
       "siaran cherry tv, cherry.tv obs, cherry tv encoder eksternal, cherry.tv rtmp, cherry.tv stream key, cherry tv streamer, web3 cam",
       'Cara siaran di <span class="accent">Cherry.tv</span> dengan SplitCam',
       "Siaran Cherry.tv",
       "Setup encoder eksternal untuk Streamer Dashboard Cherry.tv.",
       "Cherry.tv adalah platform cam baru yang tumbuh cepat dengan pendekatan Web3 — payout ramah kripto dan barrier entry lebih rendah dibanding jaringan lama seperti LiveJasmin. Broadcaster default berbasis browser, tapi Streamer Dashboard membuka jalur encoder eksternal standar yang dihubungkan oleh <strong style='color:var(--text)'>SplitCam</strong> gratis.",
       "Siaran di Cherry.tv dengan SplitCam: pasang SplitCam, susun scene, Streamer Dashboard → Broadcast Settings → External Encoder, salin URL dan key, tempel di SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + scene.</li><li>Ambil URL dan key dari Streamer Dashboard.</li><li>Tempel di SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Masuk ke akun streamer Cherry.tv, buka <strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong>. URL server dan stream key terikat ke akun. Akun baru perlu verifikasi dasar (onboarding Cherry.tv lebih ringan dibanding jaringan lama).",
       [("Entry ringan, traffic tumbuh", "Tidak ada review 72 jam ala Docler — onboarding cepat dan basis pemirsa tumbuh. Tempat bagus untuk early-mover yang mau ambil posisi sebelum platform jadi crowded."),
        ("Payout kripto + fiat", "Cherry.tv menyediakan payout kripto di samping fiat — atur preferensi payout di dashboard jika kamu ingin earning masuk ke wallet."),
        ("Browser broadcaster vs eksternal", "Browser broadcaster cepat tapi satu-kamera. Hubungkan SplitCam lewat External Encoder dan kamu buka scene multi-kamera, overlay, beauty filter, dan latar AI — tampilan lebih bersih, sesi lebih panjang."),
        _T_ETH],
       [("Apakah Cherry.tv mendukung encoder eksternal?", "Ya — Streamer Dashboard punya jalur External Encoder RTMP standar. OBS, SplitCam, dan vMix terhubung ke jalur ini; cukup pilih External Encoder di Broadcast Settings."),
        ("Di mana saya ambil stream key Cherry.tv?", "Di dalam Streamer Dashboard → Broadcast Settings → External Encoder. URL server dan stream key unik akun muncul di sana — salin keduanya ke kolom RTMP kustom SplitCam."),
        ("Bitrate berapa untuk Cherry.tv?", "Targetkan 1920×1080 di 30 fps, 3.500–6.000 Kbps dengan interval keyframe 2 detik. Platform baru, audiens muda — kualitas HD diharapkan."),
        ("Apakah SplitCam gratis untuk Cherry.tv?", "Ya — SplitCam gratis, tanpa watermark, tanpa batas waktu. Kamu bisa kirim scene multi-kamera, overlay, dan beauty filter ke Cherry.tv tanpa biaya tambahan.")],
       steps=[
           ("Pasang SplitCam", "SplitCam adalah software live-streaming gratis untuk Windows dan macOS — tanpa daftar, tanpa kartu, tanpa watermark. Ia adalah encoder yang mengirim siaranmu ke endpoint RTMP Cherry.tv."),
           ("Susun scene-mu", "Di SplitCam tambahkan webcam, tumpuk overlay, beauty filter, dan kamera kedua — audiens Cherry.tv lebih muda dan paham platform; scene-mu harus terasa modern dan cepat."),
           ("Streamer Dashboard → Broadcast Settings → External Encoder", "Masuk ke Cherry.tv, buka <strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong>. Halaman menampilkan URL server dan stream key unik akun — salin keduanya."),
           ("Hubungkan SplitCam ke Cherry.tv", "Di SplitCam buka <strong>Stream Settings</strong>, tempel URL server dan stream key Cherry.tv ke kolom RTMP kustom. Atur bitrate 3.500–6.000 Kbps di 1920×1080, 30 fps."),
           ("Klik Go Live", "Tekan <strong>Go Live</strong> di SplitCam, lalu online dari Streamer Dashboard Cherry.tv. Dalam hitungan detik stream-mu sampai ke Cherry.tv dan pemirsa mulai masuk."),
       ]),
    _p("amateurtv", "AmateurTV",
       "Cara siaran di AmateurTV dengan SplitCam — jaringan cam berbahasa Spanyol",
       "Siaran di AmateurTV dengan SplitCam gratis — encoder eksternal Model Panel, jaringan cam Spanyol/Amerika Latin, scene multi-kamera. Tanpa watermark, tanpa daftar.",
       "siaran amateurtv, amateur.tv obs, amateurtv encoder eksternal, amateurtv rtmp, amateurtv stream key, modelos amateur tv",
       'Cara siaran di <span class="accent">AmateurTV</span> dengan SplitCam',
       "Siaran AmateurTV",
       "Setup encoder eksternal untuk jaringan AmateurTV berbahasa Spanyol.",
       "AmateurTV adalah jaringan cam terdepan untuk dunia berbahasa Spanyol — audiens kuat di Spanyol, Meksiko, Argentina, dan seluruh LatAm. Broadcaster Model Panel default jalan di browser, tapi ia juga membuka jalur <strong>External Encoder</strong> standar yang dihubungkan oleh <strong style='color:var(--text)'>SplitCam</strong> gratis — memungkinkan kamu siaran dengan scene multi-kamera, beauty filter, dan overlay ke audiens hispanofon yang tidak terlayani baik oleh jaringan US-centric.",
       "Siaran di AmateurTV dengan SplitCam: pasang SplitCam, susun scene, di Model Panel buka <em>Broadcast Settings → External Encoder</em>, salin URL server dan stream key, tempel di SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + scene.</li><li>Ambil URL dan key dari Model Panel.</li><li>Tempel di SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Masuk ke akun model AmateurTV, buka <strong>Model Panel</strong> dan ke <strong>Broadcast Settings → External Encoder</strong>. Halaman menampilkan <strong>URL server</strong> dan <strong>stream key</strong> terikat ke akunmu — salin keduanya ke kolom RTMP kustom SplitCam. Akun model baru butuh verifikasi ID sebelum bisa live.",
       [("Audiens hispanofon dulu", "Traffic AmateurTV sebagian besar berbahasa Spanyol — Spanyol di siang hari, LatAm di jam malam US. Judul stream, teks scene, dan overlay dalam bahasa Spanyol mengalahkan versi English-only di jaringan ini."),
        ("Zona waktu LatAm adalah prime-mu", "Traffic puncak berkorelasi dengan jam malam LatAm (UTC-3 sampai UTC-6). Kalau jadwalmu fleksibel, siaran larut malam CET / pagi jam Asia menangkap puncak Spanyol dan LatAm sekaligus."),
        ("Payout mid-tier yang stabil", "Bukan RPM tertinggi di industri, tapi stabil — AmateurTV membayar konsisten dan niche hispanofon punya kompetisi jauh lebih sedikit daripada jaringan top US."),
        _T_ETH],
       [("Apakah AmateurTV resmi mendukung encoder eksternal seperti SplitCam?", "Ya — Model Panel punya opsi External Encoder di bawah Broadcast Settings. AmateurTV menyediakan URL server RTMP standar dan stream key; OBS, SplitCam, vMix, dan encoder RTMP lainnya semua terhubung."),
        ("Di mana saya ambil stream key AmateurTV?", "Model Panel → Broadcast Settings → External Encoder. URL server dan stream key muncul di sana. Salin keduanya ke kolom RTMP kustom SplitCam. Key terikat akun."),
        ("Bitrate berapa untuk AmateurTV?", "Standar kualitas cam — 1920×1080 di 30 fps, 3.500–6.000 Kbps dengan interval keyframe 2 detik. Jalankan speed test bawaan SplitCam dulu."),
        ("Apakah SplitCam gratis untuk AmateurTV?", "Ya — SplitCam gratis, tanpa watermark, tanpa batas waktu. Opsi External Encoder AmateurTV juga gratis diaktifkan.")],
       steps=[
           ("Pasang SplitCam", "SplitCam adalah software live-streaming gratis untuk Windows dan macOS — tanpa daftar, tanpa kartu, tanpa watermark. Ia adalah encoder yang mengirim videomu ke AmateurTV."),
           ("Susun scene-mu", "Di SplitCam tambahkan webcam. Tumpuk overlay, teks, kamera kedua atau HP-mu, beauty filter atau latar AI. Pakai teks Spanyol di overlay untuk audiens hispanofon AmateurTV."),
           ("Ambil URL dan stream key AmateurTV", "Masuk ke akun model AmateurTV, buka <strong>Model Panel</strong>, ke <strong>Broadcast Settings → External Encoder</strong>. Halaman menampilkan <strong>URL server</strong> dan <strong>stream key</strong> unik. Salin keduanya."),
           ("Hubungkan SplitCam ke AmateurTV", "Di SplitCam buka <strong>Stream Settings</strong>, tempel URL server dan stream key AmateurTV ke kolom RTMP kustom. Atur bitrate 3.500–6.000 Kbps di 1920×1080, 30 fps, keyframe 2 detik. Jalankan speed test dulu."),
           ("Klik Go Live", "Tekan <strong>Go Live</strong> di SplitCam, lalu online dari Model Panel AmateurTV. Dalam ~10 detik stream-mu sampai ke jaringan. Siaran berikutnya tinggal sekali klik."),
       ]),
    _p("camster", "Camster",
       "Cara siaran di Camster dengan SplitCam — encoder eksternal Model Hub",
       "Siaran di Camster dengan SplitCam gratis — encoder eksternal Model Hub, platform cam mapan kelas menengah, scene multi-kamera dan overlay. Tanpa watermark, tanpa daftar.",
       "siaran camster, camster.com obs, camster encoder eksternal, camster rtmp, camster stream key, camster model hub",
       'Cara siaran di <span class="accent">Camster</span> dengan SplitCam',
       "Siaran Camster",
       "Setup encoder eksternal untuk Model Hub Camster.",
       "Camster adalah platform cam mapan kelas menengah — lebih kecil dari Chaturbate atau LiveJasmin tapi punya basis pengguna setia dan payout yang adil. Broadcaster Model Hub default jalan di browser, tapi ia juga membuka jalur <strong>External Encoder</strong> standar yang dihubungkan oleh <strong style='color:var(--text)'>SplitCam</strong> gratis — memungkinkan kamu siaran dengan scene multi-kamera, overlay, dan filter yang tidak bisa diberikan broadcaster bawaan.",
       "Siaran di Camster dengan SplitCam: pasang SplitCam, susun scene, di Model Hub buka <em>Broadcast Settings → External Encoder</em>, salin URL server dan stream key, tempel di SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + scene.</li><li>Ambil URL dan key dari Model Hub.</li><li>Tempel di SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Masuk ke akun model Camster, buka <strong>Model Hub</strong> dan ke <strong>Broadcast Settings → External Encoder</strong>. Halaman menampilkan <strong>URL server</strong> dan <strong>stream key</strong> terikat akun — salin keduanya ke kolom RTMP kustom SplitCam. Key terikat akun; perlakukan seperti password.",
       [("Mid-tier berarti kompetisi lebih sedikit", "Traffic Camster stabil tapi jumlah broadcaster lebih sedikit dibanding jaringan top — lebih mudah masuk halaman depan dengan scene yang rapi dan jadwal konsisten."),
        ("Browser broadcaster vs eksternal", "Browser broadcaster default single-source. SplitCam lewat External Encoder membuka scene multi-kamera, overlay, beauty filter, dan latar AI."),
        ("Payout stabil, split adil", "Revenue split Camster adil untuk kelas mid-tier — bukan tertinggi di industri, tapi payout bulanan andal dan sedikit keluhan model tentang keterlambatan bayar."),
        _T_ETH],
       [("Apakah Camster resmi mendukung encoder eksternal seperti SplitCam?", "Ya — Model Hub punya opsi External Encoder di bawah Broadcast Settings. URL server RTMP standar dan stream key; OBS, SplitCam, dan encoder RTMP lain semua terhubung."),
        ("Di mana saya ambil stream key Camster?", "Model Hub → Broadcast Settings → External Encoder. URL server dan stream key muncul di sana. Salin keduanya ke kolom RTMP kustom SplitCam."),
        ("Bitrate berapa untuk Camster?", "Standar kualitas cam — 1920×1080 di 30 fps, 3.500–6.000 Kbps dengan interval keyframe 2 detik. Jalankan speed test bawaan SplitCam dulu."),
        ("Apakah SplitCam gratis untuk Camster?", "Ya — SplitCam gratis, tanpa watermark, tanpa batas waktu. Opsi External Encoder Camster juga gratis.")],
       steps=[
           ("Pasang SplitCam", "SplitCam adalah software live-streaming gratis untuk Windows dan macOS — tanpa daftar, tanpa kartu, tanpa watermark."),
           ("Susun scene-mu", "Di SplitCam tambahkan webcam. Tumpuk overlay, teks, kamera kedua atau HP-mu, beauty filter atau latar AI — semuanya diterapkan live."),
           ("Ambil URL dan stream key Camster", "Masuk ke akun model Camster, buka <strong>Model Hub</strong>, ke <strong>Broadcast Settings → External Encoder</strong>. Halaman menampilkan <strong>URL server</strong> dan <strong>stream key</strong> unik. Salin keduanya."),
           ("Hubungkan SplitCam ke Camster", "Di SplitCam buka <strong>Stream Settings</strong>, tempel URL server dan stream key Camster ke kolom RTMP kustom. Atur bitrate 3.500–6.000 Kbps di 1920×1080, 30 fps, keyframe 2 detik. Jalankan speed test dulu."),
           ("Klik Go Live", "Tekan <strong>Go Live</strong> di SplitCam, lalu online dari Model Hub Camster. Dalam ~10 detik stream-mu sampai ke Camster."),
       ]),
    _p("camversity", "Camversity",
       "Cara siaran di Camversity dengan SplitCam — encoder eksternal Performer Dashboard",
       "Siaran di Camversity dengan SplitCam gratis — encoder eksternal Performer Dashboard, platform cam independen yang berkembang, scene multi-kamera. Tanpa watermark, tanpa daftar.",
       "siaran camversity, camversity obs, camversity encoder eksternal, camversity rtmp, camversity stream key, camversity performer",
       'Cara siaran di <span class="accent">Camversity</span> dengan SplitCam',
       "Siaran Camversity",
       "Setup encoder eksternal untuk Performer Dashboard Camversity.",
       "Camversity adalah platform cam independen yang sedang tumbuh dengan fokus ke tools ramah performer dan komisi lebih rendah dari jaringan lama. Broadcaster Performer Dashboard default jalan di browser, tapi ia juga membuka jalur <strong>External Encoder</strong> standar yang dihubungkan oleh <strong style='color:var(--text)'>SplitCam</strong> gratis — memungkinkan kamu siaran dengan scene multi-kamera, overlay, dan filter.",
       "Siaran di Camversity dengan SplitCam: pasang SplitCam, susun scene, di Performer Dashboard buka <em>Stream Settings → External Encoder</em>, salin URL server dan stream key, tempel di SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + scene.</li><li>Ambil URL dan key dari Performer Dashboard.</li><li>Tempel di SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Masuk ke akun performer Camversity, buka <strong>Performer Dashboard</strong> dan ke <strong>Stream Settings → External Encoder</strong>. Halaman menampilkan <strong>URL server</strong> dan <strong>stream key</strong> terikat akun — salin keduanya ke kolom RTMP kustom SplitCam. Akun baru butuh verifikasi ID standar sebelum bisa live.",
       [("Split ramah performer", "Revenue split Camversity lebih menguntungkan performer daripada jaringan lama — layak dibandingkan dengan platform utamamu sekarang kalau kamu masih awal di karier cam."),
        ("Onboarding lebih ringan dari Docler", "Verifikasi Camversity lebih cepat dari approval 48–72 jam LiveJasmin, tapi tetap legit (bukan model random / unverified). Jalan tengah yang bagus."),
        ("Bangun scene, bukan sekadar webcam", "Broadcaster Performer Dashboard default Camversity single-source. SplitCam lewat External Encoder membuka multi-kamera, overlay, dan beauty filter."),
        _T_ETH],
       [("Apakah Camversity resmi mendukung encoder eksternal seperti SplitCam?", "Ya — Performer Dashboard punya opsi External Encoder di bawah Stream Settings. URL server RTMP standar dan stream key; OBS, SplitCam, vMix semua terhubung."),
        ("Di mana saya ambil stream key Camversity?", "Performer Dashboard → Stream Settings → External Encoder. URL server dan stream key muncul di sana."),
        ("Bitrate berapa untuk Camversity?", "Targetkan 1920×1080 di 30 fps, 3.500–6.000 Kbps dengan interval keyframe 2 detik. Jalankan speed test bawaan SplitCam dulu."),
        ("Apakah SplitCam gratis untuk Camversity?", "Ya — SplitCam gratis, tanpa watermark, tanpa batas waktu. Opsi External Encoder Camversity juga gratis.")],
       steps=[
           ("Pasang SplitCam", "SplitCam adalah software live-streaming gratis untuk Windows dan macOS — tanpa daftar, tanpa kartu, tanpa watermark."),
           ("Susun scene-mu", "Di SplitCam tambahkan webcam. Tumpuk overlay, teks, kamera kedua atau HP-mu, beauty filter atau latar AI."),
           ("Ambil URL dan stream key Camversity", "Masuk ke akun performer Camversity, buka <strong>Performer Dashboard</strong>, ke <strong>Stream Settings → External Encoder</strong>. Halaman menampilkan <strong>URL server</strong> dan <strong>stream key</strong> unik. Salin keduanya."),
           ("Hubungkan SplitCam ke Camversity", "Di SplitCam buka <strong>Stream Settings</strong>, tempel URL server dan stream key Camversity ke kolom RTMP kustom. Atur bitrate 3.500–6.000 Kbps di 1920×1080, 30 fps, keyframe 2 detik."),
           ("Klik Go Live", "Tekan <strong>Go Live</strong> di SplitCam, lalu online dari Performer Dashboard. Dalam ~10 detik stream-mu sampai ke Camversity."),
       ]),
]
