# -*- coding: utf-8 -*-
"""Japanese (ja) content for cam-streaming-guides."""

_T_ETH = ("有線接続を使用", "長い配信ではEthernetがWi-Fiに勝つ — 失われたフレームは失われたチップ。配信PCまでケーブルを引きましょう。")
_T_TEST = ("まず非公開テストを実施", "観客に部屋を開く前に、カメラ、音声、構図、オーバーレイをチェックする短いテスト配信を実行。")

def _p(slug, name, title, desc, kw, h1html, h1short, card, intro, quick, key_how, tips, faq, steps=None):
    d = {"slug": slug, "name": name, "title": title, "desc": desc, "kw": kw,
         "h1html": h1html, "h1short": h1short, "card": card, "intro": intro,
         "quick": quick, "key_how": key_how, "tips": tips, "faq": faq}
    if steps: d["steps"] = steps
    return d

PLATFORMS_JA = [
    _p("chaturbate", "Chaturbate",
       "ChaturbateでSplitCam配信 — Token & RTMP",
       "無料SplitCamでChaturbate配信 — broadcast token、RTMP、マルチカメラシーンとオーバーレイ。透かしなし。",
       "chaturbate 配信, chaturbate broadcast token, chaturbate rtmp obs, chaturbate external encoder, chaturbate live",
       'SplitCamで<span class="accent">Chaturbate</span>配信する方法',
       "Chaturbate配信",
       "Chaturbateでの外部エンコーダーによるトークンベース設定。",
       "Chaturbateはトークン経済で構築された最大級のcamプラットフォームの一つ。ブラウザブロードキャスターはフラットなシングルカメラツール — 無料の<strong style='color:var(--text)'>SplitCam</strong>で<strong style='color:var(--text)'>外部エンコーダー</strong>に切り替えると、同じトークンベースのストリームでマルチカメラシーン、オーバーレイ、フィルターが使えます。",
       "SplitCamでChaturbate配信：SplitCamをインストール、シーンを構築、Chaturbateで<em>Broadcast Yourself → My Broadcast</em>を開き、broadcast tokenをコピー、SplitCamに貼り付け、Go Live。"
       "<ol><li>SplitCamをインストール。</li><li>カメラ+シーンを追加。</li><li>Chaturbateからbroadcast tokenをコピー。</li><li>SplitCamに貼り付け。</li><li>Go Liveを押す。</li></ol>",
       "Chaturbateで<strong>Broadcast Yourself</strong>をクリックして<strong>My Broadcast</strong>ページを開き、<strong>View RTMP/OBS broadcast information and stream key</strong>を選択。キーは<strong>broadcast token</strong>として表示 — コピーしてください。パスワードのように扱い、公開しないでください。",
       [("トークンが鍵", "Chaturbateは汎用ストリームキーの代わりにbroadcast tokenを使用。パスワードとして扱い、漏洩したらリセット。"),
        ("余裕は十分", "ChaturbateのRTMP ingestは4K、60 fps、高ビットレートまで受け入れ — 制限はアップロード、プラットフォームではない。キーフレームは2秒ごと。"),
        _T_ETH, _T_TEST],
       [("ChaturbateはOBS / 外部エンコーダーを許可？", "はい — Chaturbateは外部エンコーダーを公式にサポート、独自の「How do I set up OBS?」記事あり。配信設定で「Use External Encoder to Broadcast」で有効化。"),
        ("Chaturbateのストリームキーはどこ？", "Broadcast Yourself → My Broadcast → View RTMP/OBS broadcast information and stream key。キーはbroadcast token。"),
        ("Chaturbateのビットレートは？", "1080pで3,500–6,000 Kbpsで十分。Chaturbateの上限は高い — 実際の制限はアップロード；最初にSplitCamの速度テストを実行。"),
        ("SplitCamはChaturbateで無料？", "はい — 完全無料、透かしなし、時間制限なし：エンコーダーがトークン収入を食べることはない。")]),
    _p("cam4", "CAM4",
       "CAM4でSplitCam配信 — External Encoder",
       "無料SplitCamでCAM4配信 — External Encoder、ストリームキー、地域ブロック、オーバーレイ。透かしなし。",
       "cam4 配信, cam4.com, cam4 external encoder, cam4 stream key, cam4 rtmp obs",
       'SplitCamで<span class="accent">CAM4</span>配信する方法',
       "CAM4配信",
       "地域コントロール付きCAM4 External Encoder。",
       "CAM4は地域コントロール内蔵のグローバルcam-and-earnプラットフォーム — 選択した国で配信を隠せる。無料<strong style='color:var(--text)'>SplitCam</strong>を外部エンコーダーとして配信すると、基本ブロードキャスターでは不可能なシーン切替やオーバーレイが開く。",
       "SplitCamでCAM4配信：SplitCamをインストール、シーンを構築、CAM4で<em>Broadcast &amp; Earn Money → Start Broadcast → External Encoder</em>へ、Get Stream Key、SplitCamに貼り付け、Go Live。"
       "<ol><li>SplitCamをインストール。</li><li>カメラ+シーンを追加。</li><li>CAM4からストリームキーを取得。</li><li>SplitCamに貼り付け。</li><li>Go Liveを押す。</li></ol>",
       "CAM4で<strong>Broadcast</strong> → <strong>Broadcast &amp; Earn Money</strong> → <strong>Start Broadcast</strong>、上部の<strong>External Encoder</strong>。生年月日、性別、国を入力、<strong>Get Stream Key</strong>でコピー。SplitCam Stream Settingsの緑のスライダーが接続を確認。",
       [("地域制限を設定", "CAM4は特定の国・地域で配信を隠せる — go-live前にCAM4側で設定。"),
        ("緑のスライダーを見る", "CAM4設定はキーが受け入れられるとSplitCam Stream Settingsに緑のスライダーを表示 — 赤 = キーをチェック。"),
        ("通常より低いビットレート", "CAM4のingestは動画ビットレートを約3,000 Kbpsに制限 — 大半のcamサイトより低い。より高く押さない。"),
        _T_ETH],
       [("CAM4はOBS / 外部エンコーダーを公式サポート？", "はい — CAM4はサポートサイトに公式OBS Guideがあり、最高の体験のためにExternal Encoderを推奨。SplitCamは同じRTMPルートを使用。"),
        ("CAM4ストリームを地域ブロックできる？", "はい — CAM4は特定の国で配信を隠す地域制限が内蔵。CAM4で設定、SplitCamではない。"),
        ("CAM4のストリームキーは？", "Broadcast → Broadcast & Earn Money → Start Broadcast → External Encoder → Get Stream Key。"),
        ("CAM4のビットレートは？", "平均より低い — CAM4 ingestは30 fps、1秒キーフレームで~3,000 Kbpsに制限。公式テーブルは~3,000を超えないことを推奨。")]),
    _p("bongacams", "BongaCams",
       "BongaCamsでSplitCam配信 — External Encoder",
       "無料SplitCamでBongaCams配信 — External Encoder、マルチカメラシーン、オーバーレイ、AI背景。透かしなし。",
       "bongacams, bongcams, bongacams 配信, bongacams external encoder, bongacams rtmp obs",
       'SplitCamで<span class="accent">BongaCams</span>配信する方法',
       "BongaCams配信",
       "BongaCams用External Encoder設定。",
       "BongaCamsはグローバルcamプラットフォーム。外部エンコーダー配信は常に有効ではない — 有効化されると、無料<strong style='color:var(--text)'>SplitCam</strong>がマルチカメラシーン、オーバーレイ、AI背景で配信を駆動。",
       "SplitCamでBongaCams配信：SplitCamをインストール、シーンを構築、BongaCamsで<em>Options → Broadcast settings → Select Encoder → External Encoder</em>へ、URLとキーをコピー、SplitCamに貼り付け、Go Live。"
       "<ol><li>SplitCamをインストール。</li><li>カメラ+シーンを追加。</li><li>BongaCamsからURLとキーを取得。</li><li>SplitCamに貼り付け。</li><li>Go Liveを押す。</li></ol>",
       "BongaCamsで<strong>Options</strong> → <strong>Broadcast settings</strong> → <strong>Select Encoder</strong> → <strong>External Encoder</strong>を開き、表示されるサーバーURLとストリームキーをコピー。<strong>External Encoderボタンが見つからない場合</strong>、BongaCamsサポートに連絡してアカウントで外部エンコーディングを有効にするよう依頼。",
       [("External Encoderボタンなし？サポート", "BongaCamsはアカウントごとに外部エンコーディングを有効化 — Broadcast settingsにオプションがない場合、サポートが有効化。"),
        ("解像度を合わせる", "BongaCamsはウェブカメラの解像度と配信の解像度の一致を推奨 — 例：両方1280×720。"),
        _T_ETH, _T_TEST],
       [("BongaCamsでExternal Encoderボタンが表示されないのはなぜ？", "外部エンコーディングはすべてのアカウントでデフォルトで有効ではない — BongaCamsサポートに連絡して有効化し、ボタンがBroadcast settingsに表示される。"),
        ("BongaCamsアカウントを認証する必要は？", "はい — 配信には18+、年齢確認用の公式ID、ライブ前のアカウント承認が必要。"),
        ("BongaCamsのビットレートは？", "BongaCams RTMP ingestは動画ビットレートを約6,000 Kbps、2秒キーフレームに制限 — 1080pで3,500–6,000が理想ゾーン；最初にアップロードをテスト。"),
        ("SplitCamはBongaCamsで無料？", "はい — 完全無料、透かしなし、時間制限なし、エンコーダーがBongaCamsでのトークン収入を減らさない。")]),
    _p("stripchat", "Stripchat",
       "StripchatでSplitCam配信 — Strip Cam設定",
       "strip camプラットフォームStripchatで無料SplitCam配信。外部ソフトウェア、トークンキー、シーン、オーバーレイ。",
       "strip cam, stripchat live stream, stripchat 配信, stripchat external software, stripchat stream key, stripchat rtmp obs",
       'SplitCamで<span class="accent">Stripchat</span>配信する方法',
       "Stripchat配信",
       "Stripchat配信用外部ソフトウェア設定。",
       "Stripchatは双方向性に焦点を当てた大きなcamプラットフォーム。<em>external software</em>モードはトークンベースのキーを提供 — 無料<strong style='color:var(--text)'>SplitCam</strong>に入れて、フラットカメラの代わりにシーン、オーバーレイ、フィルターで配信。",
       "SplitCamでStripchat配信：SplitCamをインストール、シーンを構築、Stripchatで<em>Switch to external software</em>を選択、ストリームキーをコピー、SplitCamに貼り付け、Go Live。"
       "<ol><li>SplitCamをインストール。</li><li>カメラ+シーンを追加。</li><li>Stripchatからストリームキーを取得。</li><li>SplitCamに貼り付け。</li><li>Go Liveを押す。</li></ol>",
       "Stripchatで<strong>Switch to external software</strong>を選択、次に<strong>Show external software settings for the stream</strong>。ストリームキーをコピー — Stripchatはトークンとして表示。プライベートに保つ。",
       [("サイトと解像度を一致", "StripchatのFAQは警告：ソフトウェアの解像度はサイトと正確に一致しないと動画がピクセル化。両方同じに設定。"),
        ("2 Mbps最低限に注意", "Stripchatは2 Mbpsアップロードを最低限と記載 — そしてOBS配信やマルチ配信には不十分と明言。もっと高く狙う。"),
        ("キーはトークン", "Stripchatのストリームキーはトークン — 正確にコピー、共有しない、漏洩したらリセット。"),
        _T_ETH],
       [("StripchatはOBS / 外部ソフトウェアを推奨？", "はい — Stripchat公式FAQはOBSのような外部ブロードキャストソフトウェアを「最高のビデオ・オーディオ品質を達成するため」推奨。SplitCamも同様に動作。"),
        ("Stripchatを外部ソフトウェアに切り替える方法は？", "Broadcast CenterでSwitch to External Broadcast Software (OBS)を選択、その後external software settingsを開いてストリームキー（トークン）を表示。"),
        ("Stripchatのビットレートは？", "RTMP ingestは2秒キーフレームで~6,000 Kbpsまで受け入れ。1080pで3,500–6,000が理想 — ただし2 Mbps最低限を大きく超える必要があり、特にOBS配信。"),
        ("SplitCamはStripchatで無料？", "はい — ライセンス料なし、透かしなし、時間制限なし：長いインタラクティブなStripchatショーでもエンコーダー側で何もコストがない。")]),
    _p("onlyfans", "OnlyFans",
       "OnlyFansでSplitCamライブ — 認証またはキー",
       "無料SplitCamでOnlyFansライブ — 認証またはOBS Keyでログイン、マルチカメラシーン、オーバーレイ。透かしなし。",
       "onlyfans ライブ, onlyfans live stream, onlyfans 認証 splitcam, onlyfans obs key, onlyfans streaming software",
       'SplitCamで<span class="accent">OnlyFans</span>ライブする方法',
       "OnlyFansライブ",
       "一度認証またはキーを貼り付け — OnlyFansライブ。",
       "OnlyFansライブはサブスクライバー向け。SplitCamは<strong style='color:var(--text)'>2つの方法</strong>で接続 — OnlyFansアカウントで一度ログインしSplitCamが自動的にストリームキーを取得し同期、または手動でOBS Keyを貼り付け。どちらもマルチカメラシーン、オーバーレイ、フィルターで配信。",
       "SplitCamでOnlyFansライブ：SplitCamをインストール、シーンを構築、Stream Settings &rarr; Add Channel &rarr; OnlyFansを開き<em>認証</em>を選択 — OnlyFansアカウントでログイン、SplitCamが自動的にキーを取得 — Go Liveを押す。アカウント接続でOnlyFansサイトを開かずSplitCamからOnlyFansストリームパラメータを変更可能。",
       "OnlyFansで：<strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; <strong>Other</strong>セクションで<strong>OBS Key</strong>をコピー。またはSplitCamの<strong>認証</strong>オプションでアカウントログイン — キーが自動的に取得され同期される。",
       [("認証 vs Stream Key", "2つの接続方法：<strong>認証</strong>（一度ログイン、キーが取得され同期される — 最も簡単な方法）または<strong>Stream Key</strong>（OnlyFans → Profile → Settings → OtherでOBS Keyをコピーして貼り付け）。"),
        ("SplitCamを離れずに設定変更", "認証ではアカウントが接続されたまま、配信中または後にSplitCamからOnlyFansライブパラメータを調整 — OnlyFansサイトを経由しない。"),
        ("控えめなビットレート", "OnlyFansのRTMP ingestは動画ビットレートを約2,500 Kbpsに制限 — 大半のcamサイトより厳しい。720p–1080pで~2,000–2,500を狙う。"),
        _T_ETH],
       [("OnlyFansをSplitCamに接続する方法は？", "2つの方法。<strong>認証</strong> — Stream Settings → Add Channel → OnlyFans → OnlyFansアカウントでログイン、SplitCamが自動的にキーを取得。または<strong>Stream Key</strong> — OnlyFans → Profile → Settings → OtherでOBS Keyをコピーして貼り付け。"),
        ("サイトを開かずにOnlyFansライブ設定を変更できる？", "はい — 認証方法ではSplitCamがOnlyFansアカウントに接続されたまま、キーと設定が自動同期。"),
        ("OnlyFansのビットレートは？", "控えめ — OnlyFansのRTMP ingestはビットレートを約2,500 Kbpsに制限、他のcamプラットフォームより厳しい。720p–1080pで2,000–2,500 Kbps周辺を狙う。"),
        ("SplitCamはOnlyFansライブで無料？", "はい — 無料、透かしなし、時間制限なし。エンコーダー側でコストなし。")],
       steps=[
           ("SplitCamをダウンロードしてインストール", "SplitCamはWindowsとmacOS用の無料配信ソフトウェア — 登録不要、カード不要、透かしなし。OnlyFansにあなたのビデオを送るエンコーダーです。"),
           ("カメラとシーンをセットアップ", "SplitCamを開いてウェブカメラを追加。視聴者に見せたいようにシーンを構築 — オーバーレイ、テキスト、2台目のカメラ、ビューティーフィルター、AI背景、すべてライブで適用。"),
           ("接続 — 方法1：認証（推奨）", "SplitCamで<strong>Stream Settings</strong> &rarr; <strong>Add Channel</strong> &rarr; <strong>OnlyFans</strong>を開き<strong>認証</strong>を選択。OnlyFansのEmailとパスワードでログイン。SplitCamがアカウントをリンク、自動的にストリームキーを取得し同期 — SplitCam内でOnlyFansライブパラメータを管理でき、配信中または後にOnlyFansサイトを開かずに変更可能。"),
           ("接続 — 方法2：Stream Key（手動）", "ログインしたくない？キーを使用。OnlyFansで<strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; <strong>Other</strong>セクションへ行き<strong>OBS Key</strong>をコピー。SplitCamでAdd Channel &rarr; OnlyFans、キーフィールドに貼り付け。このキーは静的 — 後で設定を変更するにはOnlyFansサイトに戻る。"),
           ("Go Live", "どの方法でもSplitCamで<strong>Go Live</strong>を押す。方法1ではOnlyFansパラメータをSplitCamからリアルタイムで調整し続けられる；方法2ではキーは設定したまま。"),
       ]),
    _p("camplace", "CamPlace",
       "CamPlaceでSplitCam配信 — 無料ガイド",
       "無料SplitCamでCamPlace配信 — 外部エンコーダー、RTMPキー、シーン、オーバーレイ。ステップバイステップ、透かしなし。",
       "camplace 配信, camplace broadcasting software, camplace rtmp, camplace external encoder, camplace stream key",
       'SplitCamで<span class="accent">CamPlace</span>配信する方法',
       "CamPlace配信",
       "CamPlace配信用外部エンコーダー設定。",
       "CamPlaceはcam-streamingプラットフォーム。公開OBS記事がないため、<strong style='color:var(--text)'>上のビデオガイド</strong>が参照 — 無料<strong style='color:var(--text)'>SplitCam</strong>は標準RTMPで接続し、基本カメラにはないシーン、オーバーレイ、AI背景を追加。",
       "SplitCamでCamPlace配信：SplitCamをインストール、シーンを構築、CamPlaceで外部/RTMP配信を有効化、サーバーURLとストリームキーをコピー、SplitCamに貼り付け、Go Live。現在のルートはビデオに従う。"
       "<ol><li>SplitCamをインストール。</li><li>カメラ+シーンを追加。</li><li>CamPlaceからRTMPキーを取得。</li><li>SplitCamに貼り付け。</li><li>Go Liveを押す。</li></ol>",
       "CamPlaceにログインして配信設定を開く。外部エンコーダー / RTMP / OBSオプションに切り替えて<strong>サーバーURL</strong>と<strong>ストリームキー</strong>を表示、両方コピー。CamPlaceは公式OBSドキュメントを公開していない — <strong>上のビデオ</strong>が現在のインターフェースを通る最も信頼できるステップバイステップルート。",
       [("公式OBSガイドなし — ビデオを使用", "CamPlaceには外部エンコーダーに関する公開記事がない；上のビデオが現在のルートの参照。"),
        ("標準RTMPで動作", "未文書化だがCamPlaceは標準RTMPサーバーURLとキーを受け入れ — SplitCamはカスタムRTMP宛先として接続。"),
        _T_ETH, _T_TEST],
       [("CamPlaceに公式OBSガイドはある？", "外部エンコーダーに関する公開記事は見つからない。CamPlaceは標準RTMP URLとキーを受け入れるのでSplitCamは動作 — ビデオに従う。"),
        ("CamPlaceは外部エンコーダーをサポート？", "はい — 標準RTMPストリームキーを受け入れ、SplitCamはカスタムRTMP宛先として接続。"),
        ("CamPlaceのビットレートは？", "CamPlaceは公式数値を公開していない — 1080pで3,500–6,000 Kbpsを安全範囲として使用し、SplitCam速度テストに実際の上限を決めさせる。"),
        ("SplitCamはCamPlaceで無料？", "はい — 無料、透かしなし、時間制限なし。CamPlaceは独自のエンコーダーを提供しないので、無料RTMPツールが仕事をする。")]),
    _p("camsoda", "CamSoda",
       "CamSodaライブ × SplitCam — 無料設定",
       "無料SplitCamでCamSodaライブ — Use OBS Broadcaster、地域サーバー、シーン、オーバーレイ。透かしなし。",
       "camsoda live, camsoda 配信, camsoda obs broadcaster, camsoda rtmp obs, camsoda live broadcast",
       'SplitCamで<span class="accent">CamSoda</span>配信する方法',
       "CamSoda配信",
       "CamSodaのUse OBS Broadcaster設定。",
       "CamSodaはインタラクティブで独特なショー形式で知られる米国のcamプラットフォーム。OBS配信を公式サポート — Go Liveページに<strong style='color:var(--text)'>Use OBS Broadcaster</strong>ボタンがあり、CamSodaウィキに公式OBSガイドがある。無料<strong style='color:var(--text)'>SplitCam</strong>も同様に動作。",
       "SplitCamでCamSoda配信：SplitCamをインストール、シーンを構築、CamSodaのGo LiveページでUse OBS Broadcasterをクリック、サーバーURLとストリームキーをコピー、SplitCamに貼り付け、Go Live。"
       "<ol><li>SplitCamをインストール。</li><li>カメラ+シーンを追加。</li><li>CamSodaでUse OBS Broadcasterをクリック。</li><li>サーバーURL+キーをSplitCamに貼り付け。</li><li>Go Liveを押す。</li></ol>",
       "CamSodaの<strong>Go Live</strong>ページで<strong>Use OBS Broadcaster</strong>をクリック。CamSodaはRTMPサーバーURLとストリームキーを表示 — 両方コピー。最寄りの地域サーバー（北米、欧州、アジアなど）を選択。CamSodaウィキに詳細な完全OBSガイドあり。",
       [("チップ受け取りには認証", "CamSodaでは誰でも配信できるが、チップを受け取るにはCamSodaの認証プロセスを完了する必要がある。"),
        ("最寄りの地域サーバーを選択", "CamSodaは地域ingestサーバーを提供 — 最寄り（NA / 欧州 / アジア / 南米 / オセアニア）はレイテンシとドロップフレームを削減。"),
        ("1080p / 30 fpsの上限", "CamSodaのingestは約1080p、30 fps、~6,000 Kbpsまで — より高く押さない。"),
        _T_ETH],
       [("CamSodaはOBS / 外部エンコーダーをサポート？", "はい — 公式に。Go LiveページにUse OBS Broadcasterボタンがあり、CamSodaウィキにOBSガイドがあるので、SplitCamは動作。"),
        ("CamSodaで認証する必要は？", "配信には不要。チップを受け取るには必要 — CamSodaは最初に認証プロセスの完了を要求。"),
        ("CamSodaがサポートする解像度は？", "最大1920×1080、30 fps、RTMP ingestで最大約6,000 Kbps。"),
        ("SplitCamはCamSodaで無料？", "はい — 無料、透かしなし、時間制限なし。CamSodaの無料Use OBS Broadcasterモードと連携するので、チェーン全体に費用がない。")]),
    _p("streamate", "Streamate",
       "StreamateでSplitCam配信 — 統合チャンネル",
       "無料SplitCamでStreamate配信 — 統合チャンネル、SM Connectキー、シーン、オーバーレイ。透かしなし。",
       "streamate, streamate sm connect, streamate 配信, streamate broadcasting software, streamate rtmp",
       'SplitCamで<span class="accent">Streamate</span>配信する方法',
       "Streamate配信",
       "StreamateはSplitCamで統合チャンネル — 速い設定。",
       "Streamateは確立されたcamプラットフォーム — SplitCamのチャンネルリストで<strong style='color:var(--text)'>事前構成された宛先</strong>の一つ、設定は手動RTMP入力より速い：Streamateを選択、キーを貼り付け、完了。",
       "SplitCamでStreamate配信：SplitCamをインストール、シーンを構築、Streamateで<em>SM Connect → Start Show</em>を使用してキーをコピー、その後SplitCamで<em>Stream Settings → Add Channel → Streamate</em>を開いて貼り付け。"
       "<ol><li>SplitCamをインストール。</li><li>カメラ+シーンを追加。</li><li>SM Connect経由でStreamateキーを取得。</li><li>SplitCamでAdd Channel → Streamate。</li><li>Go Liveを押す。</li></ol>",
       "Streamateで<strong>SM Connect</strong>を開き、規約を承認、左の<strong>Start Show</strong>をクリックして開いたウィンドウを閉じる — その後ストリーミングキーをコピー。SplitCamで<strong>Stream Settings</strong> → <strong>Add Channel</strong>を開き、リストから<strong>Streamate</strong>を選択してキーを貼り付け。緑のスライダーが接続を確認。",
       [("Streamateは統合", "手動RTMP URL不要 — SplitCamのAdd ChannelリストにStreamateがある；選択してキーを貼り付けるだけ。"),
        ("SM Connectポップアップを閉じる", "Start Show後Streamateがウィンドウを開く — 閉じる；ストリーミングキーを表示するためだけ。"),
        ("解像度を1080pに固定", "SM ConnectのVideo Resolutionフィールドが静かに1440にジャンプすることがあり、実際には配信されず品質を黙って下げる — 手動で1080pに設定。静止画でビットレートが下がるのは正常：Streamateストリームは適応的。"),
        _T_ETH, _T_TEST],
       [("StreamateはSplitCamに統合されている？", "はい — StreamateはSplitCamのAdd Channelリストに表示 — RTMP URLを手動入力する代わりに選択。"),
        ("Streamateストリーミングキーはどこ？", "SM Connect → 規約承認 → Start Show → ポップアップを閉じる → キーをコピー。"),
        ("Streamateのビットレートは？", "Streamateはハード上限を設定しない — 1080pで3,500–6,000 Kbpsがうまく動作。ストリームは適応的なので、静止画で低いビットレートは正常、バグではない。"),
        ("SplitCamはStreamateで無料？", "はい — 無料、透かしなし、時間制限なし；StreamateはSplitCamで統合チャンネルなので、別途エンコーダーコストもない。")]),
    _p("streamray", "StreamRay",
       "StreamRay camでSplitCam配信 — チャットURL",
       "無料SplitCamでStreamRay cam配信 — チャットに投稿されるURL、OBS Broadcasterモード、シーン、オーバーレイ。透かしなし。",
       "streamray, streamray cam, streamray 配信, streamray obs broadcaster, streamray rtmp",
       'SplitCamで<span class="accent">StreamRay</span>配信する方法',
       "StreamRay配信",
       "StreamRayのURL-in-chat外部エンコーダー設定。",
       "StreamRayは独特な外部エンコーダー設定 — 配信の<strong style='color:var(--text)'>チャットウィンドウ</strong>でストリームURLを配信し、別途ストリームキーを使用しない。無料<strong style='color:var(--text)'>SplitCam</strong>はこのURL-onlyフローを処理。",
       "SplitCamでStreamRay配信：SplitCamをインストール、シーンを構築、StreamRayでOBS Broadcasterを有効化、チャットウィンドウからストリームURLをコピー、SplitCamに貼り付け（キーフィールドは空欄）、Go Live。"
       "<ol><li>SplitCamをインストール。</li><li>カメラ+シーンを追加。</li><li>チャットからStreamRay URLをコピー。</li><li>URLをSplitCamに貼り付け。</li><li>Go Liveを押す。</li></ol>",
       "StreamRayで<strong>Broadcast Now</strong>をダブルクリック、<strong>Other</strong>メニューを開き、<strong>OBS Broadcaster</strong>と<strong>Save and Close</strong>を選択。StreamRayは<strong>ストリームURLをチャットウィンドウに投稿</strong> — そこからコピー。SplitCamのストリームキーフィールドは<strong>空欄</strong>のまま；StreamRayはURLのみで認証。",
       [("URLはチャット内", "StreamRayは設定ボックスにストリームURLを表示しない — 配信のチャットウィンドウに投稿。そこからコピー。"),
        ("キーフィールドは空欄", "StreamRayは別途キーを使用しない — URLのみ。SplitCamのキーフィールドに何も入れない。"),
        _T_ETH, _T_TEST],
       [("StreamRayストリームURLはどこ？", "OBS Broadcaster有効化後、StreamRayはチャットウィンドウにURLを投稿 — チャットからコピー。"),
        ("StreamRayにストリームキーがないのはなぜ？", "StreamRayはURLのみで認証 — SplitCamキーフィールドは空欄のまま。"),
        ("StreamRayのビットレートは？", "StreamRayは公式上限を宣言しない — 1080pで3,500–6,000 Kbpsを狙ってSplitCam速度テストを実行、URL-onlyフローはビットレートフィードバックを与えないため。"),
        ("SplitCamはStreamRayで無料？", "はい — 無料、透かしなし、時間制限なし、StreamRayのURL-onlyフローと一致：リンクを貼り付ければライブ。")]),
    _p("xlovecam", "XLoveCam",
       "XLoveCamでSplitCam配信 — RTMPリンクとキー",
       "無料SplitCamでXLoveCam配信 — RTMPリンクとキー、地域サーバー、シーン、オーバーレイ。透かしなし。",
       "xlovecam, x love cam, xlovecam 配信, xlovecam rtmp link, xlovecam stream key",
       'SplitCamで<span class="accent">XLoveCam</span>配信する方法',
       "XLoveCam配信",
       "XLoveCam用RTMPリンク+キー設定。",
       "XLoveCamは欧州の多言語camプラットフォーム。アカウント設定は<strong style='color:var(--text)'>RTMPリンク</strong>と<strong style='color:var(--text)'>ストリームキー</strong>の両方を表示 — 無料<strong style='color:var(--text)'>SplitCam</strong>が両方を取得し、フルシーンとオーバーレイで配信。",
       "SplitCamでXLoveCam配信：SplitCamをインストール、シーンを構築、XLoveCamで<em>My Account → settings</em>を開き、RTMPリンクとストリームキーをコピー、両方をSplitCamに貼り付け、ショーを開始。"
       "<ol><li>SplitCamをインストール。</li><li>カメラ+シーンを追加。</li><li>XLoveCamからRTMPリンク+キーをコピー。</li><li>両方をSplitCamに貼り付け。</li><li>Go Liveを押す。</li></ol>",
       "XLoveCamで<strong>My Account</strong> → <strong>settings</strong>を開く。設定は<strong>RTMPリンク</strong>と<strong>ストリームキー</strong>の両方を表示 — 両方をSplitCamのサーバーURLとキーフィールドにコピー、その後XLoveCamで<strong>Start your show</strong>。",
       [("リンクとキーをコピー", "XLoveCamはRTMPリンクと別途ストリームキーを提供 — SplitCamで両方が必要、片方だけではない。"),
        ("多言語視聴者", "XLoveCamは欧州で多言語 — あなたの言語の明確なテキストオーバーレイは視聴者があなたを見つけるのに役立つ。"),
        ("最寄りのサーバーを選択", "XLoveCamは地域RTMPサーバーを提供 — 欧州、北米、南米、アジア。最寄りはレイテンシとドロップフレームを削減。"),
        _T_ETH],
       [("XLoveCamのRTMPデータはどこ？", "My Account → settings — RTMPリンクとキーの両方を表示。"),
        ("XLoveCamは外部エンコーダーをサポート？", "はい — RTMPリンクとキーを提供、SplitCamはエンコーダーとして動作。"),
        ("XLoveCamのビットレートは？", "XLoveCamは固定制限を公開しない；1080pで3,500–6,000 Kbpsが理想。最寄りの地域サーバー選択も同じ程度重要 — ドロップフレームを削減。"),
        ("SplitCamはXLoveCamで無料？", "はい — 無料、透かしなし、時間制限なし。XLoveCamの多言語欧州視聴者にリーチするのにソフトウェアコストはかからない。")]),
    _p("soulcams", "SoulCams",
       "SoulCamsでSplitCam配信 — OBS設定",
       "無料SplitCamでSoulCams配信 — OBS設定、RTMPサーバーとキー、マルチカメラシーン、オーバーレイ。",
       "soul cams, soulcams, soulcams 配信, soulcams obs, soulcams rtmp, soulcams broadcast",
       'SplitCamで<span class="accent">SoulCams</span>配信する方法',
       "SoulCams配信",
       "SoulCams用OBS設定。",
       "SoulCamsはOBS設定が<strong style='color:var(--text)'>RTMPサーバーとストリームキーを一緒に</strong>1つのウィンドウに表示するcamプラットフォーム。無料<strong style='color:var(--text)'>SplitCam</strong>に両方を貼り付けて、マルチカメラシーンとオーバーレイで配信。",
       "SplitCamでSoulCams配信：SplitCamをインストール、シーンを構築、SoulCamsでGo Online → Settings → OBSをクリック、サーバーとキーをコピー、両方をSplitCamに貼り付け、Go Live。"
       "<ol><li>SplitCamをインストール。</li><li>カメラ+シーンを追加。</li><li>SoulCams Settings → OBSを開く。</li><li>サーバー+キーをSplitCamに貼り付け。</li><li>Go Liveを押す。</li></ol>",
       "SoulCamsでログインして<strong>Go Online</strong>をクリック、その後<strong>Settings</strong> → <strong>OBS</strong>を開く。OBSウィンドウは<strong>RTMPサーバー</strong>と<strong>ストリームキー</strong>を一緒に表示 — 両方をSplitCamにコピー。",
       [("サーバーとキーが並んでいる", "SoulCamsはRTMPサーバーとキーを同じOBSウィンドウに表示 — 一度に両方を取る。"),
        ("先にGo Online", "OBS設定はSoulCamsでGo Onlineをクリックした後にのみ表示 — エンコーダーデータを探す前に行う。"),
        ("不要な地域をブロック", "SoulCamsはモデル側からの地域ブロックを許可 — Go Liveを押す前にどの国がストリームを見れないか選択。"),
        _T_ETH, _T_TEST],
       [("SoulCamsのOBS設定はどこ？", "ログイン、Go Liveをクリック、その後Settings → OBS — RTMPサーバーとストリームキーが一緒に表示。"),
        ("SoulCamsは外部エンコーダーをサポート？", "はい — OBS設定はRTMPサーバーとキーを提供、SplitCamは動作。"),
        ("SoulCamsのビットレートは？", "SoulCamsは公式数値を提供しない — 1080pで3,500–6,000 Kbpsを狙ってアップロードをテスト、OBSウィンドウはビットレートガイダンスを表示しないため。"),
        ("SplitCamはSoulCamsで無料？", "はい — 無料、透かしなし、時間制限なし、マルチカメラシーンとオーバーレイ付きの完全なSoulCamsショーがエンコーダー側で費用ゼロ。")]),
    _p("imlive", "ImLive",
       "ImLiveでSplitCam配信 — 仮想カメラ",
       "無料SplitCamでIm Live stream設定 — ImLiveはウェブカメラを直接使用（RTMPなし）、SplitCamをシーン付き仮想カメラとして接続。",
       "im live stream, imlive splitcam, imlive 配信, imlive 仮想カメラ, imlive webcam, im live cam",
       'SplitCamで<span class="accent">ImLive</span>を使用する方法',
       "ImLiveでのSplitCam",
       "ImLive用仮想カメラ設定 — RTMPなし。",
       "ImLiveはブラウザで直接ウェブカメラを使用 — <strong style='color:var(--text)'>RTMPもストリームキーもなし</strong>。無料<strong style='color:var(--text)'>SplitCam</strong>は<strong style='color:var(--text)'>仮想カメラ</strong>として接続：SplitCamでシーンを構築し、ImLiveでSplitCamをカメラとして選択。",
       "ImLiveでSplitCamを使用：SplitCamをインストール、メディアレイヤーでシーンを構築、ImLiveを開いてビデオチャットを開始、ImLive設定でSplitCamをウェブカメラとマイクとして選択。"
       "<ol><li>SplitCamをインストール。</li><li>SplitCamでシーンを構築。</li><li>ImLiveでビデオチャットを開始。</li><li>ImLiveカメラとしてSplitCamを選択。</li><li>チャットを開始。</li></ol>",
       "ImLiveサイトにログインして<strong>Start Video Chat</strong>をクリック、その後<strong>Go To Settings</strong>を開いてカメラとマイクのオプションにアクセス。ImLive設定で<strong>SplitCam</strong>をウェブカメラとマイクとして選択。",
       [("ストリームキー不要", "ImLiveにRTMPはない — サーバーURLやキーを探さない。SplitCamはカメラデバイスとして選択されるだけ。"),
        ("SplitCamをマイクにも設定", "カメラに加えてマイクにもSplitCamを選択して、オーディオミックスとノイズ抑制もライブに入るように。"),
        ("ライブ前にシーンを構築", "ImLiveはSplitCamが送信するものを表示 — チャット開始前にレイヤーを整理。"),
        _T_TEST],
       [("ImLiveはRTMPまたはストリームキーを使用？", "いいえ — ImLiveはブラウザで直接ウェブカメラを使用。SplitCamは仮想カメラとして接続、コピーするキーはない。"),
        ("ImLiveでSplitCamを選択する方法は？", "Start Video Chat → Go To Settings → SplitCamをウェブカメラとマイクとして選択。"),
        ("ImLiveでオーバーレイを使用できる？", "はい — SplitCamシーンで構築；ImLiveは合成結果を表示。"),
        ("SplitCamはImLiveで無料？", "はい — 無料、透かしなし、時間制限なし。ImLive用の仮想カメラとして、ビデオチャットにコストやブランディングを追加しない。")],
       steps=[
           ("SplitCamをインストール", "SplitCamはWindowsとmacOS用の無料ソフトウェア。インストール — 透かしなし、登録なし。ImLiveでは<strong>仮想カメラ</strong>として動作、RTMPエンコーダーではない。"),
           ("SplitCamでシーンを構築", "SplitCamを開いて<strong>Media Layers +</strong>を使ってウェブカメラとあらゆるオーバーレイ、テキスト、フィルター、AI背景を追加。この合成シーンがImLiveがあなたのカメラとして見るもの。"),
           ("ImLiveでビデオチャットを開始", "ImLiveサイトにログインして<strong>Start Video Chat</strong>をクリック、その後<strong>Go To Settings</strong>を開いてカメラとマイクのオプションにアクセス。"),
           ("SplitCamをカメラとして選択", "ImLive設定で<strong>SplitCam</strong>をウェブカメラとマイクとして選択。ImLiveはフラットなウェブカメラの代わりに完全なSplitCamシーンを表示。"),
           ("Free Live Chatを開始", "ImLiveで<strong>Free Live Chat</strong>をクリックしてライブに。セッション中に外観を変更するには、SplitCamでシーンを編集 — ImLiveは即座に更新。"),
       ]),
    _p("vxlive", "VXLive",
       "VXLiveでSplitCam配信 — 公式サポート",
       "無料SplitCamでVXLive（VXModels / VISIT-X）配信 — 公式VISIT-Xプリセット、サーバーとキー、シーン。透かしなし。",
       "vxlive, visit-x, vxmodels splitcam, vxlive 配信, visit-x stream, vxlive rtmp",
       'SplitCamで<span class="accent">VXLive</span>配信する方法',
       "VXLive配信",
       "VXLiveは公式にSplitCamをサポート（VISIT-Xプリセット）。",
       "VXLive（VXModels / VISIT-X）はドイツ市場のcamプラットフォーム — <strong style='color:var(--text)'>SplitCamを名前で公式サポート</strong>する数少ないものの一つ。VXModelsには<strong style='color:var(--text)'>SplitCam</strong>をVXLiveに接続するための専用ヘルプ記事があり、SplitCamはVISIT-Xを既製チャンネルプリセットとして提供。",
       "SplitCamでVXLive配信：SplitCamをインストール、シーンを構築、VXLiveで「Stream with third-party software」を選択、サーバーURLとキーをコピー、SplitCamでVISIT-Xプリセットを選択して貼り付け、SplitCamでGo Live、その後VXLiveでGO ONLINE。"
       "<ol><li>SplitCamをインストール。</li><li>カメラ+シーンを追加。</li><li>VXLiveからサーバーURL+キーを取得。</li><li>SplitCamでVISIT-Xプリセットを選択、貼り付け。</li><li>Go Live、その後VXLiveでGO ONLINE。</li></ol>",
       "VXLiveで<strong>Stream with third-party software</strong>を選択し、<strong>OBS、SplitCam、またはXSplit</strong>のオプションを選択。VXLiveは<strong>サーバーURL</strong>と<strong>ストリームキー</strong>を提供。SplitCamで<strong>VISIT-X</strong>をストリーミングプラットフォームとして選択、両方を貼り付け、SplitCamで<strong>Go Live</strong>を押し、その後VXLiveで<strong>GO ONLINE</strong>。",
       [("VISIT-Xは統合プリセット", "生RTMP URLを入力しない — SplitCamのプラットフォームリストにVISIT-Xがある；選択してサーバーURLとキーを貼り付けるだけ。"),
        ("2段階のgo-live", "VXLiveではSplitCamでGo Liveを最初に押し、その後VXLiveでGO ONLINE — この順序で両方。"),
        ("ドイツ市場", "VXLive視聴者は主にドイツ語圏 — ドイツ語のテキストオーバーレイやタイトルは視聴者とのつながりに役立つ。"),
        _T_ETH],
       [("VXLiveはSplitCamを公式サポート？", "はい — VXModels（VXLive）はSplitCam設定専用の公式ヘルプ記事を維持し、SplitCamをOBSとXSplitと並んでサポートする配信ソフトウェアとしてリスト。"),
        ("SplitCamをVXLiveに接続する方法は？", "VXLiveで「Stream with third-party software」を選択、その後SplitCamでVISIT-XプリセットとVXLiveが提供するサーバーURLとストリームキーを貼り付け。"),
        ("SplitCamまたはVXLiveでライブに行く？", "両方 — まずSplitCamでGo Live、その後VXLiveでGO ONLINE。"),
        ("VXModelsがSplitCamを推奨する理由は？", "VXModelsの公式ヘルプ記事はウェブカメラの画像アーティファクトとピクセル化を排除し接続を安定させるために特にSplitCamを推奨 — 単なる汎用エンコーダーではない。")]),
    _p("virtwish", "VirtWish",
       "VirtWishでSplitCam配信 — ストリームURLとキー",
       "無料SplitCamでVirtWish配信 — Profile → Start Broadcast OBSセクション、ストリームURLとキー、シーン、オーバーレイ。",
       "virtwish, virtwish 配信, virtwish broadcasting software, virtwish rtmp, virtwish stream key, virtwish obs",
       'SplitCamで<span class="accent">VirtWish</span>配信する方法',
       "VirtWish配信",
       "VirtWish用ストリームURL+キー設定。",
       "VirtWishはインタラクティブなcamプラットフォーム。配信設定はOBSセクションで<strong style='color:var(--text)'>ストリームURLと別途ストリームキー</strong>を提供 — 無料<strong style='color:var(--text)'>SplitCam</strong>が両方を取得し、シーンとオーバーレイでショーを実行。",
       "SplitCamでVirtWish配信：SplitCamをインストール、シーンを構築、VirtWishで<em>Profile → Start Broadcast</em>を開いてOBSセクションへ、リンクとキーをコピー、両方をSplitCamに貼り付け、Go Live。"
       "<ol><li>SplitCamをインストール。</li><li>カメラ+シーンを追加。</li><li>VirtWishからURL+キーを取得。</li><li>両方をSplitCamに貼り付け。</li><li>Go Liveを押す。</li></ol>",
       "VirtWishで右上のアイコンをクリック → <strong>Profile</strong> → <strong>Start Broadcast</strong>、その後再度<strong>Start Broadcast</strong>でOBSセクションに到達。<strong>最初の行のリンクをコピー</strong>してSplitCam Stream URLフィールドへ、<strong>Stream Key</strong>を別途キーフィールドへ。",
       [("最初の行のリンク", "VirtWish OBSセクションはストリームURLを最初の行に配置 — SplitCam Stream URLにコピー、その後別途キー。"),
        ("Start Broadcastを2回クリック", "VirtWishでStart Broadcastを2回クリックしてOBSセクションに到達 — 想定通り、バグではない。"),
        _T_ETH, _T_TEST],
       [("VirtWishのRTMPデータはどこ？", "右上のアイコン → Profile → Start Broadcast 2回 → OBSセクションがリンクとストリームキーを表示。"),
        ("VirtWishは外部エンコーダーをサポート？", "はい — OBSセクションはストリームURLとキーを提供、SplitCamは動作。"),
        ("VirtWishのビットレートは？", "VirtWishは公式上限を公開しない；1080pで3,500–6,000 Kbpsが安全。再スケーリングを避けるためSplitCam解像度をVirtWishで設定したものと一致させる。"),
        ("SplitCamはVirtWishで無料？", "はい — 無料、透かしなし、時間制限なし。VirtWishのURLとキー設定は必要な数分だけかかる。")]),
    _p("xmodels", "XModels",
       "XModelsでSplitCam配信 — 無料ガイド",
       "無料SplitCamでXModels配信 — モデルアカウント設定の外部エンコーダーオプション、RTMPキー、シーン、オーバーレイ。",
       "xmodels, xmodels 配信, xmodels broadcasting software, xmodels rtmp, xmodels external encoder",
       'SplitCamで<span class="accent">XModels</span>配信する方法',
       "XModels配信",
       "XModels配信用外部エンコーダー設定。",
       "XModelsはモデルアカウント設定に内蔵された<strong style='color:var(--text)'>外部エンコーダーオプション</strong>を持つcam-streamingプラットフォーム。無料<strong style='color:var(--text)'>SplitCam</strong>はそこで単一のフラットカメラの代わりにマルチカメラシーン、オーバーレイ、フィルターで配信。",
       "SplitCamでXModels配信：SplitCamをインストール、シーンを構築、XModelsモデルアカウントで外部エンコーダーオプションを有効化、サーバーURLとストリームキーをコピー、SplitCamに貼り付け、Go Live。"
       "<ol><li>SplitCamをインストール。</li><li>カメラ+シーンを追加。</li><li>XModels設定で外部エンコーダーを有効化。</li><li>サーバーURL+キーをSplitCamに貼り付け。</li><li>Go Liveを押す。</li></ol>",
       "XModels<strong>モデルアカウント設定</strong>で<strong>外部エンコーダー経由配信</strong>オプションを有効化。XModelsは<strong>ストリームキー</strong>を提供 — SplitCamにコピー。期待する場所にオプションがない場合、XModelsサポートはサイトのFAQチャットと<strong>info@xmodels.com</strong>；上のビデオもそれを示す。",
       [("アカウント設定にある", "XModelsは外部エンコーダーオプションをモデルアカウント設定に配置、別途配信画面ではない。"),
        ("サポート：チャット+メール", "XModelsには大きな公開ヘルプセンターはない — サイトFAQチャットとinfo@xmodels.comが公式サポートチャンネル。"),
        ("SplitCamでオーバーレイをスタック", "チップ目標、名前、SNSハンドルをシーンレイヤーとして — XModelsの基本カメラはこのようなものを追加しない。"),
        _T_ETH],
       [("XModelsは外部エンコーダーをサポート？", "はい — モデルアカウント設定にストリームキーを提供する外部エンコーダー配信オプションが含まれ、SplitCamは動作。"),
        ("XModelsヘルプはどこで得られる？", "XModelsサポートはサイトFAQチャットとinfo@xmodels.comメール経由 — 大きな公開ヘルプセンターはない。"),
        ("XModelsのビットレートは？", "XModelsは公式数値を文書化していない — 1080pで3,500–6,000 KbpsとSplitCam速度テストを使用、XModelsサポートはチャットとメールのみのため。"),
        ("SplitCamはXModelsで無料？", "はい — 無料、透かしなし、時間制限なし、XModelsの欧州ネットワークへの配信にソフトウェアコストを追加しない。")]),
    _p("flirt4free", "Flirt4Free",
       "Flirt for Free camでSplitCam配信 — 無料ガイド",
       "無料SplitCamでFlirt for Free cam配信 — External Broadcast Form、RTMP URLとStream Name、シーン、オーバーレイ。",
       "flirt for free cam, flirt 4 free cam, flirt4free, flirt4free 配信, flirt4free external broadcast, flirt4free rtmp",
       'SplitCamで<span class="accent">Flirt4Free</span>配信する方法',
       "Flirt4Free配信",
       "Flirt4Free用External Broadcast Form設定。",
       "Flirt4Freeは最古のcamプラットフォームの一つ、90年代から放送中。<strong style='color:var(--text)'>External Broadcast Form</strong>経由で外部配信を公式サポート — 無料<strong style='color:var(--text)'>SplitCam</strong>がストリームを送信し、フォームが解像度とビットレートを設定。",
       "SplitCamでFlirt4Free配信：SplitCamをインストール、シーンを構築、Flirt4Free External Broadcast Formを開き、RTMP URLとStream Nameをコピーして解像度/ビットレートを設定、SplitCamに貼り付け、Go Live。"
       "<ol><li>SplitCamをインストール。</li><li>カメラ+シーンを追加。</li><li>Flirt4Free External Broadcast Formを開く。</li><li>RTMP URL+Stream NameをSplitCamに貼り付け。</li><li>Go Liveを押す。</li></ol>",
       "Flirt4Freeモデルエリアで<strong>External Broadcast Form</strong>を開く。大半のcamサイトと異なり、Flirt4Freeは<strong>RTMP URL</strong>と<strong>Stream Name</strong>（「キー」ではない）、加えてフォーム自体に入力する解像度とビットレートフィールドを提供。URLとStream NameをSplitCamサーバーとキーフィールドにコピー。",
       [("Stream Name、キーではない", "Flirt4Freeは認証情報をStream Nameと呼ぶ。SplitCamストリームキーフィールドに貼り付け — 同じ役割。"),
        ("フォームで解像度/ビットレートを設定", "Flirt4FreeのExternal Broadcast Formは独自の解像度とビットレートフィールドを持つ — 画像が再スケーリングされないようSplitCam設定と整合。"),
        ("歴史的プラットフォーム", "Flirt4Freeは90年代から稼働 — モデルツールは成熟し、External Broadcast Formはそれの文書化された部分。"),
        _T_ETH],
       [("Flirt4Freeは外部エンコーダーをサポート？", "はい — 公式に、External Broadcast Form経由、RTMP URLとStream Nameを提供。SplitCamはエンコーダーとして動作。"),
        ("Flirt4FreeのRTMPデータはどこで取得？", "モデルエリアのExternal Broadcast Formから — RTMP URL、Stream Name、解像度/ビットレートフィールドを表示。"),
        ("Flirt4Freeのビットレートは？", "1080pで3,500–6,000 Kbps — External Broadcast FormとSplitCamで同じ値を設定。"),
        ("SplitCamはFlirt4Freeで無料？", "はい — 無料、透かしなし、時間制限なし、ショーが長くなる可能性のあるFlirt4Freeのような歴史的プラットフォームに合う。")]),
    _p("mfc-alerts", "MFC Alerts",
       "SplitCamでMFC Alertsをストリームに追加",
       "MyFreeCamsストリームにアニメーションチップアラートを表示 — 無料SplitCamでウェブカメラの上にmfcalerts.com URLをBrowserレイヤーとして。",
       "mfc alerts, myfreecams alerts, mfc alerts 追加, mfcalerts splitcam, myfreecams tip alerts, myfreecams alerts overlay",
       '<span class="accent">MFC Alerts</span>をストリームに追加する方法',
       "MFC Alerts追加",
       "MyFreeCamsストリームにアニメーションチップアラートを表示。",
       "MFC Alertsは視聴者がチップを送るたびにMyFreeCamsストリームにアニメーション効果を表示。無料<strong style='color:var(--text)'>SplitCam</strong>内で<strong style='color:var(--text)'>Browserレイヤー</strong>として動作 — 一度設定すれば、チップが画面上の反応をライブでトリガー。",
       "SplitCamでMFC Alertsを追加：SplitCamをインストール、ウェブカメラを追加、Browserタブを開いてmfcalerts.comをロード、アラートURLをコピー、ウェブカメラの上にBrowserレイヤーとして追加、テストチップでテスト。"
       "<ol><li>SplitCamをインストール。</li><li>ウェブカメラを追加。</li><li>mfcalerts.comでURLを取得。</li><li>ウェブカメラの上にBrowserレイヤーとして追加。</li><li>テストチップを送信。</li></ol>",
       "SplitCamで<strong>Browser</strong>タブを開き<strong>www.mfcalerts.com</strong>に移動。ログインまたは登録。<strong>Copy to clipboard</strong>を使って個人のアラートURLをコピー。SplitCam Browserウィンドウに貼り付けて<strong>Add</strong>をクリック。ソースリストを並び替えて<strong>MFC Alertsをウェブカメラの上</strong>に（3点メニュー → Move Up）。",
       [("MFC Alertsはウェブカメラの上にある必要", "最も一般的なエラー：MFC Alertsレイヤーがソースリストでウェブカメラの下にあると、効果は隠れたまま。上に移動。"),
        ("mfcalerts.comアカウントが必要", "アラートURLは個人的 — アカウントがない場合は最初にmfcalerts.comに登録。"),
        ("ライブ前にテストチップを送信", "Settings → Send test tipを使用してオーバーレイが動作することを確認 — ショーの途中でエラーを発見しない。"),
        _T_ETH],
       [("MFC Alertsとは？", "視聴者がチップを送るときにストリームにビデオ効果を表示するMyFreeCams用通知システム — SplitCamにBrowserオーバーレイとして追加。"),
        ("MFC Alertsが表示されないのはなぜ？", "ほぼ常にレイヤー順序 — MFC Alerts BrowserレイヤーはSplitCamソースリストでウェブカメラの上にある必要。"),
        ("MFC Alertsにアカウントが必要？", "はい — mfcalerts.comに登録して個人のアラートURLを取得。"),
        ("SplitCamはこれで無料？", "はい — SplitCamは無料、透かしなし、時間制限なし、MFC Alerts browserオーバーレイは追加コストなしで内部で実行。")],
       steps=[
           ("SplitCamをインストールしてウェブカメラを追加", "WindowsまたはmacOS用の無料SplitCamをインストール、その後<strong>ウェブカメラ</strong>をソースとして追加。MFC Alertsはこのカメラの上のレイヤーとして座る。"),
           ("Browserタブを開いてmfcalerts.comに移動", "SplitCamで<strong>Browser</strong>タブを開き<strong>www.mfcalerts.com</strong>に移動。ログインまたはmfcalerts.comアカウントをまだ持っていない場合は登録。"),
           ("アラートURLをコピー", "mfcalerts.comで<strong>Copy to clipboard</strong>を使って個人のアラートURLをコピー — それはチップアニメーションをレンダリングするページ。"),
           ("URLをBrowserレイヤーとして追加 — ウェブカメラの上", "URLをSplitCam Browserウィンドウに貼り付けて<strong>Add</strong>をクリック。その後ソースリストを並び替えて<strong>MFC Alertsをウェブカメラの上</strong>に（3点メニュー → Move Up）。下にあると効果は隠れたまま。"),
           ("テストチップでテスト", "<strong>Settings → Send test tip</strong>を開いてアラート効果がカメラの上に表示されることを確認。その後MyFreeCamsで通常通り配信 — 実際のチップが今アニメーションをトリガー。"),
       ]),
    _p("lovense", "Lovense",
       "SplitCamでLovenseおもちゃをストリームに追加",
       "無料SplitCamでインタラクティブなLovenseおもちゃをcamストリームに接続 — Lovense SplitCam Toolset、画面上のチップアラート、反応。",
       "lovense ストリームに追加, lovense cam stream, lovense splitcam, lovense splitcam toolset, lovense interactive toy streaming",
       '<span class="accent">Lovenseおもちゃ</span>をストリームに追加する方法',
       "Lovenseおもちゃ追加",
       "インタラクティブなLovenseおもちゃをcamストリームに接続。",
       "無料<strong style='color:var(--text)'>SplitCam</strong>でcamストリームを実行し、トークンに反応する<strong style='color:var(--text)'>Lovense</strong>おもちゃをペアリング。Lovenseは公式<strong style='color:var(--text)'>Lovense SplitCam Toolset</strong>を文書化し、SplitCamは公式Lovenseプラグインを提供 — 統合は両側からサポート。",
       "Lovenseおもちゃをストリームに追加：SplitCamとLovenseソフトウェアをインストール、おもちゃをペアリング、Lovenseをcamプラットフォームにリンク、SplitCamにLovenseステータスをBrowserレイヤーとして追加、その後通常通り配信。"
       "<ol><li>SplitCamをインストール。</li><li>Lovenseソフトウェアをインストールしておもちゃをペアリング。</li><li>Lovenseをcamサイトにリンク。</li><li>SplitCamにLovenseオーバーレイを追加。</li><li>Go Liveを押す。</li></ol>",
       "Lovense Connect / Lovense Stream（公式デスクトップアプリ）をインストール。おもちゃをオンにしてBluetoothでペアリング、アプリが接続済みを表示するように。Lovenseアプリでcamアカウントをリンクして、おもちゃが視聴者のトークン/チップに反応するように。Lovenseはオーバーレイ/ウィジェットURLを提供 — SplitCamシーンに<strong>Browser</strong>レイヤーとして追加。",
       [("公式Lovense SplitCam Toolsetを使用", "LovenseはSplitCam固有のtoolsetを独自のインストールガイドと共に公開 — SplitCam用に作られたおもちゃのアクティビティオーバーレイとチップアラートを追加。"),
        ("Lovense Cam Extensionを更新", "toolsetは最近のLovense Cam Extension（30.1.4以降）を要求 — ライブ前に更新。"),
        ("おもちゃを充電しておく", "ショーの途中でバッテリーがほぼ切れるとインタラクティブな側面が死ぬ — ライブ前にフル充電。"),
        ("トークンへの反応をテスト", "ルームを開く前におもちゃが反応することを確認するため小さなテストチップを送信。"),
        ("バージョン要件を確認", "Lovense SplitCam ToolsetはSplitCam 10.4.5以降を要求。Lovense Cam Extensionは公式にChaturbate、Stripchat、BongaCams、MyFreeCams、CamSodaをカバー — 他のサイトにはLovenseのGeneric URL統合を使用。")],
       [("LovenseはSplitCamを公式サポート？", "はい — Lovenseは独自のインストールガイドと共に公式「Lovense SplitCam Toolset」を文書化し、SplitCamは公式Lovenseプラグインを提供。統合は両側からサポート。"),
        ("おもちゃはSplitCamに直接接続？", "いいえ — おもちゃはLovenseアプリとペアリング；SplitCamはLovenseオーバーレイを表示しカメラを配信。"),
        ("どのcamサイトがLovenseをサポート？", "Lovense Cam ExtensionはChaturbate、Stripchat、BongaCams、MyFreeCams、CamSodaを公式サポート、他は様々 — Lovenseアプリで現在のリストを確認。"),
        ("最近のチップを画面に表示できる？", "はい — SplitCamにLovenseウィジェットURLをBrowserレイヤーとして追加。")],
       steps=[
           ("SplitCamをインストール", "SplitCamはWindowsとmacOS用の無料配信ソフトウェア — あなたのビデオをcamプラットフォームに送るエンコーダー。インストール；透かしなし。"),
           ("Lovenseソフトウェアをインストールしておもちゃをペアリング", "Lovense Connect / Lovense Stream（公式デスクトップアプリ）をインストール。おもちゃをオンにしてBluetoothでペアリング、アプリが接続済みを表示するように。"),
           ("Lovenseをcamプラットフォームにリンク", "Lovenseアプリでcamアカウントをリンクして、おもちゃが視聴者のトークン/チップに反応するように。ほとんどの主要camプラットフォームがサポート。"),
           ("SplitCamにLovenseオーバーレイを追加", "Lovenseはオーバーレイ/ウィジェットURLを提供。SplitCamシーンに<strong>Browser</strong>レイヤーとして追加、視聴者がおもちゃのステータスと最近のチップを画面で見えるように。"),
           ("シーンを構築してGo Live", "カメラと他のオーバーレイを追加、camプラットフォームのRTMPキーをSplitCamに貼り付けて<strong>Go Live</strong>をクリック。おもちゃはチップにリアルタイムで反応。"),
       ]),
    _p("multistream-cams", "複数のcamサイト",
       "SplitCamで複数のcamサイトに同時配信",
       "SplitCamの無料マルチストリーミングでMyFreeCams、Chaturbate、BongaCams、CAM4、Stripchatなどに同時配信。ワンクリック、透かしなし。",
       "複数のcamサイトに配信, multistream cam sites, chaturbateとbongacamsに同時配信, multistream cam ソフトウェア",
       '<span class="accent">複数のcamサイト</span>に同時配信する方法',
       "Camマルチストリーミング",
       "複数のcamサイトに同時配信。",
       "無料<strong style='color:var(--text)'>SplitCam</strong>は1つのエンコーディングを<strong style='color:var(--text)'>複数のcamサイトに同時配信</strong>可能 — MyFreeCams、Chaturbate、BongaCams、CAM4、Stripchatなど。透かしなし、ワンクリック。",
       "複数のcamサイトに一度に配信するには：SplitCamをインストール、シーンを構築、各camサイトのRTMPサーバーURLとストリームキーを取得、すべてをSplitCamマルチストリーミング設定に追加、Go Liveを一度クリック。"
       "<ol><li>SplitCamをインストール。</li><li>カメラ+シーンを追加。</li><li>各camサイトからRTMPキーを取得。</li><li>すべてのキーをSplitCam multistreamに追加。</li><li>Go Liveを一度押す。</li></ol>",
       "各camプラットフォームで外部 / RTMP配信を有効化し、<strong>サーバーURL</strong>と<strong>ストリームキー</strong>をコピー。SplitCamで<strong>Stream Settings</strong>を開いて各camサイトをカスタムRTMP宛先として追加 — サーバーURLとキーを貼り付け。ライブにしたいすべてをチェック。<strong>Go Live</strong>を押す。",
       [("アップロードを監視", "マルチストリーミングはアップロード負荷を倍増。各宛先は独自のビットレートを消費 — 接続が合計を処理できることを確認。"),
        ("プラットフォームルールを確認", "一部のcamサイトは他の場所での同時配信を禁止 — マルチストリーミング前に確認。"),
        ("ケーブル — ここでドロップは許されない", "マルチストリーミングはアップロード負荷を倍増、wi-fiドロップ1つですべての宛先を一度に倒す可能性。ケーブルはここでオプションではない。"),
        ("ヘルスモニターを監視", "SplitCamは宛先ごとにステータスを表示 — アップロードが対応できない場合はサイトをドロップ。")],
       [("SplitCamマルチストリーミングは無料？", "はい — マルチストリーミングは内蔵で無料、宛先ごとの料金なし、透かしなし。"),
        ("同時に何個のcamサイトに配信できる？", "アップロード帯域幅が処理できる数 — 各宛先は独自のビットレートを消費。"),
        ("クラウドリレーを使用？", "いいえ — SplitCamはストリームをピアツーピアでPCから各プラットフォームのingestに直接送信。"),
        ("マルチストリーミングはPCを遅くする？", "エンコーディングは一度行われ再利用；ハードウェアエンコーディングはCPU負荷を低く保つ。アップロード帯域幅が実際の制限。")],
       steps=[
           ("SplitCamをインストール", "SplitCamはマルチストリーミング内蔵のWindowsとmacOS用の無料配信ソフトウェア。インストール — 透かしなし、登録なし。"),
           ("カメラとシーンをセットアップ", "SplitCamを開いてウェブカメラを追加し、オーバーレイとフィルターでシーンを構築。1つのシーンが各宛先に供給。"),
           ("各camサイトからRTMPキーを取得", "各camプラットフォームで外部 / RTMP配信を有効化し、<strong>サーバーURL</strong>と<strong>ストリームキー</strong>をコピー。配信したい各サイトで繰り返し — 正確なルートは個別のプラットフォームガイドを参照。"),
           ("各宛先をSplitCamに追加", "<strong>Stream Settings</strong>を開いて各camサイトをカスタムRTMP宛先として追加 — サーバーURLとキーを貼り付け。ライブにしたいすべてをチェック。"),
           ("Go Liveを一度クリック", "<strong>Go Live</strong>を押す。SplitCamはストリームを各選択されたcamサイトに同時に、ピアツーピアで、単一のエンコーディングから送信 — 追加料金なし。"),
       ]),
    _p("livejasmin", "LiveJasmin",
       "LiveJasminでSplitCam配信 — HD External Encoder",
       "無料SplitCamでLiveJasmin配信 — Model Center External Encoder、HD 1080pセットアップ、マルチカメラシーンとオーバーレイ。透かしなし、登録不要。",
       "livejasmin 配信, livejasmin obs, livejasmin external encoder, livejasmin rtmp, livejasmin stream key, livejasmin モデル設定",
       'SplitCamで<span class="accent">LiveJasmin</span>配信する方法',
       "LiveJasmin配信",
       "LiveJasminのHD-only Model Center向け外部エンコーダー設定。",
       "LiveJasminはDocler Holdingの旗艦 — 世界最大級のcamネットワークの一つで、HD-onlyのプラットフォームです。推奨ブロードキャスターは独自の<strong>JasminCAM</strong>クライアントですが、Model Centerは標準の<strong>External Encoder</strong>経路も公開しており、無料の<strong style='color:var(--text)'>SplitCam</strong>がそこに接続 — 同じHDストリーム上でマルチカメラシーン、美肌フィルター、オーバーレイを使えます。",
       "SplitCamでLiveJasmin配信：SplitCamをインストール、HDシーンを構築、Model Centerで<em>Settings → Broadcast → External Encoder</em>を開き、サーバーURLとstream keyをコピー、SplitCamに貼り付け、Go Live。"
       "<ol><li>SplitCamをインストール。</li><li>カメラ+HDシーンを追加。</li><li>Model CenterからURLとstream keyを取得。</li><li>SplitCamに貼り付け。</li><li>Go Liveを押す。</li></ol>",
       "<strong>modelcenter.livejasmin.com</strong>にログインし、<strong>Settings → Broadcast → External Encoder</strong>を開きます。Model Centerはアカウントに紐づいた<strong>サーバーURL</strong>と<strong>stream key</strong>を表示 — 両方をSplitCamのカスタムRTMPフィールドにコピー。<strong>注意：</strong>新規アカウントは承認（48〜72時間）後にExternal Encoderオプションが現れ、プラットフォームはHD-only出力を強制します。",
       [("HDを外すとランクが落ちる", "LiveJasminはHD-only — 1280×720未満は低単価のリストにしか出ず、1080p未満は「Premium」資格を失います。1920×1080、30 fps、4,000〜6,000 Kbpsを狙いましょう。"),
        ("JasminCAM vs 外部エンコーダー", "Docler純正のJasminCAMクライアントが最もHD準拠がクリーンですが、アカウント承認後はOBS、SplitCam、vMixなどの外部エンコーダーも公式サポート — JasminCAMでは出来ないマルチカメラシーンとオーバーレイが解禁されます。"),
        ("Free chat ≠ Private show", "Free chatはプレビュー専用 — 露出は不可。モデルが稼ぐのはPrivateとGold showです。着衣でもショーモードでも見栄えするシーンを設計しましょう。"),
        _T_ETH],
       [("LiveJasminはSplitCamのような外部エンコーダーを公式サポートしている？", "はい — Model CenterはSettings → BroadcastにExternal Encoderオプションを備えています。JasminCAMが推奨クライアントですが、モデルアカウントが承認されればOBS、SplitCam、その他のRTMPエンコーダーが明確にサポート対象として記載されています。"),
        ("LiveJasminのstream keyはどこ？", "Model Center内：Settings → Broadcast → External Encoder。サーバーURLと固有のstream keyの両方がここに表示 — どちらもSplitCamのカスタムRTMPフィールドにコピー。keyはアカウントに紐づいているので、パスワード同様に扱ってください。"),
        ("LiveJasminのビットレートは？", "LiveJasminはHD-only — 1920×1080、30 fps、4,000〜6,000 Kbps、キーフレーム2秒間隔を狙います。明らかにそれを下回るとPremiumラベルを失いランクが落ちます。"),
        ("LiveJasminでSplitCamは無料？", "はい — SplitCamは無料、透かしなし、時間制限なし。唯一の「コスト」はLiveJasminのHD要件を満たすことですが、SplitCamは1080pシーン合成と美肌フィルターでネイティブに対応します。")],
       steps=[
           ("SplitCamをダウンロード・インストール", "SplitCamはWindowsとmacOS向けの無料ライブ配信ソフト — 登録なし、カードなし、透かしなし。HD映像をLiveJasminに送るエンコーダーです。"),
           ("HDシーンを構築", "SplitCamを開いてウェブカメラを1080pモードで追加。オーバーレイ、テキスト、二台目のカメラやスマホ、美肌フィルターやAI背景を重ねます — LiveJasminはHD品質を要求するので、合成済みシーンはfree chatでもprivate showでも常にプレミアムに見える必要があります。"),
           ("LiveJasminのURLとstream keyを取得", "<strong>modelcenter.livejasmin.com</strong>にログイン（アカウントは先に承認される必要があります — 通常は登録後48〜72時間）。<strong>Settings → Broadcast → External Encoder</strong>を開きます。ページに<strong>サーバーURL</strong>と固有の<strong>stream key</strong>が表示されるので、両方をコピー。"),
           ("SplitCamをLiveJasminに接続", "SplitCamで<strong>Stream Settings</strong>を開き、LiveJasminのサーバーURLとstream keyをカスタムRTMPフィールドに貼り付け。ビットレートを4,000〜6,000 Kbps、1920×1080、30 fps、キーフレーム2秒に設定。先に内蔵のスピードテストを実行 — HDストリームは帯域要求が厳しいです。"),
           ("Go Liveをクリック", "SplitCamで<strong>Go Live</strong>を押し、LiveJasmin Model Centerでオンラインにします。約10秒以内にHD映像がLiveJasminのネットワークに到達します。次回以降の配信はワンクリック — SplitCamを開いてGo Live、その後LiveJasminでオンラインに。"),
       ]),
    _p("myfreecams", "MyFreeCams",
       "SplitCamでMyFreeCams（MFC）配信する方法 — Model Web Broadcasterを回避",
       "無料SplitCamでMyFreeCams配信 — Model Admin External Broadcaster、MFCトークン経済、マルチカメラシーン、オーバーレイ。透かしなし、登録不要。",
       "myfreecams 配信, mfc external broadcaster, myfreecams obs, mfc rtmp, mfc stream key, model admin, mfc トークン",
       'SplitCamで<span class="accent">MyFreeCams</span>配信する方法',
       "MyFreeCams配信",
       "MFCのトークン制Model Admin向け外部ブロードキャスター設定。",
       "MFCは最も歴史の長いcamプラットフォームの一つ — 純粋なトークン経済で、モデル審査の関門もゆるく、Premium会員の固定客が厚いのが特長です。デフォルトのModel Web Broadcasterはブラウザ内の単一カメラツールですが、Model Adminはもう一つExternal Broadcasterの経路を公開しています — 無料の<strong style='color:var(--text)'>SplitCam</strong>がここに接続することで、マルチカメラシーン、オーバーレイ、美肌フィルターが解禁されます。",
       "SplitCamでMyFreeCams配信：SplitCamをインストール、シーンを構築、Model Admin → Broadcasterに進み、Web BroadcasterをExternal Broadcasterに切り替え、サーバーURLとstream keyをコピー、SplitCamに貼り付け、Go Live。"
       "<ol><li>SplitCamをインストール。</li><li>カメラ＋シーンを追加。</li><li>Model AdminでExternal Broadcasterに切替。</li><li>URLとstream keyをSplitCamに貼り付け。</li><li>Go Liveを押す。</li></ol>",
       "MyFreeCamsにログインし、<strong>Model Admin → Broadcaster</strong>を開き、<strong>Web Broadcaster</strong>から<strong>External Broadcaster</strong>に切り替えます。ページにモデルアカウントに紐づいたサーバーURL（rtmp://publish.myfreecams.com…）とstream keyが表示されるので、両方をSplitCamのカスタムRTMPフィールドにコピー。keyはアカウント紐付けなので、パスワード同様に扱ってください。",
       [("MFCはチップ／トークン経済 — サブスクではない", "MFCの主軸はサブスクではなく、free chat内のチップ — Premium会員はprivateにも飛べますが、日銭は服を着たままのfree chatで稼ぐ構造です。カジュアルな状態でも稼ぎ続けられるシーン設計を意識してください。"),
        ("Web Broadcaster vs External Broadcaster", "デフォルトのWeb Broadcasterは単一ソース。External BroadcasterはSplitCam／OBS経由でマルチシーン、オーバーレイ、美肌フィルターを解禁 — トップモデルと駆け出しの差はここに出ます。"),
        ("mfcalerts.comでチップアラートを画面に乗せる", "SplitCamでmfcalerts.comをBrowserレイヤーとしてカメラの上に追加 — チップアニメーションと会員名が映像に直接出るので、free chatのチップ率が目に見えて上がります。"),
        _T_ETH],
       [("MFCはSplitCamのような外部ブロードキャスターをサポートしている？", "はい — Model AdminにExternal Broadcasterオプションがあり、標準RTMPです。OBS、SplitCam、vMix どれも使えます。"),
        ("MFCのstream keyはどこ？", "Model Admin → Broadcaster → External Broadcaster — サーバーURLとstream keyが同じページに表示されます。両方をSplitCamにコピー。"),
        ("MFCのビットレートは？", "MFCは約6,000 Kbpsまで、キーフレーム2秒間隔に対応。1920×1080、30 fps、3,500〜6,000 Kbpsが安定圏です。"),
        ("MFCでSplitCamは無料？", "はい — SplitCamは完全無料、透かしなし、時間制限なし。")],
       steps=[
           ("SplitCamをダウンロード・インストール", "SplitCamはWindowsとmacOS向けの無料配信エンコーダー — 登録なし、カードなし、透かしなし。"),
           ("シーンを構築", "SplitCamでウェブカメラを追加し、オーバーレイ、テキスト、二台目のカメラやスマホ、美肌フィルターやAI背景を重ねます。<strong>mfcalerts.com</strong>をBrowserレイヤーとしてカメラの上に追加すると、チップアニメーションがfree chatの映像内に直接表示されます。"),
           ("Model AdminでExternal Broadcasterに切替", "MFCにログインし、<strong>Model Admin → Broadcaster</strong>を開き、Web Broadcasterから<strong>External Broadcaster</strong>に切り替えます。表示されるサーバーURL（rtmp://publish.myfreecams.com…）とstream keyをコピー。"),
           ("SplitCamにURLとkeyを貼り付け", "SplitCamの<strong>Stream Settings</strong>を開き、URLとstream keyをカスタムRTMPフィールドに貼り付け。ビットレートは3,500〜6,000 Kbps、1920×1080、30 fps、キーフレーム2秒に設定。"),
           ("Go Liveをクリック", "SplitCamで<strong>Go Live</strong>を押すと、約10秒以内に映像がMFCに到達し、ルーム内でオンラインになります。"),
       ]),
    _p("cherry-tv", "Cherry.tv",
       "SplitCamでCherry.tv配信する方法 — Web3フレンドリーな外部エンコーダー",
       "無料SplitCamでCherry.tv配信 — Streamer Dashboardの外部エンコーダー、暗号通貨フレンドリーなcamプラットフォーム、マルチカメラシーン。透かしなし、登録不要。",
       "cherry tv 配信, cherry.tv obs, cherry tv 外部エンコーダー, cherry.tv rtmp, cherry.tv stream key, cherry tv ストリーマー, web3 cam",
       'SplitCamで<span class="accent">Cherry.tv</span>配信する方法',
       "Cherry.tv配信",
       "Cherry.tvのStreamer Dashboard向け外部エンコーダー設定。",
       "Cherry.tvは比較的新しく急成長中のcamプラットフォームで、Web3寄りの仕組み — 暗号通貨での出金が可能で、LiveJasminのような老舗ネットワークよりも参入障壁が低いのが特徴です。デフォルトはブラウザ配信ですが、Streamer Dashboardは標準のExternal Encoder経路も提供 — 無料の<strong style='color:var(--text)'>SplitCam</strong>はそこに接続します。",
       "SplitCamでCherry.tv配信：SplitCamをインストール、シーンを構築、Streamer Dashboard → Broadcast Settings → External Encoderを開き、URLとstream keyをコピー、SplitCamに貼り付け、Go Live。"
       "<ol><li>SplitCamをインストール。</li><li>カメラ＋シーンを追加。</li><li>Streamer DashboardでExternal Encoderを開く。</li><li>URLとstream keyをSplitCamに貼り付け。</li><li>Go Liveを押す。</li></ol>",
       "Cherry.tvのストリーマーアカウントにログインし、<strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong>を開きます。サーバーURLとstream keyはアカウントに紐づいています。新規アカウントは基本的な本人確認が必要ですが、Cherry.tvのオンボーディングは老舗camネットワークよりも軽量です。",
       [("参入障壁が低く、トラフィックは伸び盛り", "72時間のDocler式審査がない — Cherry.tvは早期参入で固定ファンを取りに行ける良いポジションです。"),
        ("暗号通貨と法定通貨の両方で受け取れる", "Cherry.tvは暗号通貨での出金にも対応 — 従来の決済が遅い／制限される地域では特に有利です。"),
        ("ブラウザ配信 vs 外部エンコーダー", "Cherry.tvのブラウザ配信は単一カメラのみ。SplitCamならマルチカメラシーン、オーバーレイ、美肌フィルター、AI背景まで解禁され、画面の作り込みで一段抜けます。"),
        _T_ETH],
       [("Cherry.tvは外部エンコーダーをサポートしている？", "はい — Streamer DashboardのBroadcast Settings配下にExternal Encoderオプションがあり、標準RTMPです。OBS／SplitCamがそのまま使えます。"),
        ("Cherry.tvのstream keyはどこ？", "Streamer Dashboard → Broadcast Settings → External Encoder — URLとstream keyが同じページに表示されます。"),
        ("Cherry.tvのビットレートは？", "1920×1080、30 fps、3,500〜6,000 Kbps、キーフレーム2秒を狙ってください。"),
        ("Cherry.tvでSplitCamは無料？", "はい — SplitCamは完全無料、透かしなし、時間制限なし。")],
       steps=[
           ("SplitCamをダウンロード・インストール", "SplitCamはWindowsとmacOS向けの無料配信エンコーダー — 登録なし、カードなし、透かしなし。"),
           ("シーンを構築", "ウェブカメラとオーバーレイを追加 — Cherry.tvの視聴者は若くプラットフォーム慣れしているので、画面のデザイン感と空気感が重要です。カラフルなオーバーレイ、動くテキスト、AI背景を組み合わせましょう。"),
           ("URLとstream keyを取得", "<strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong>でサーバーURLとstream keyをコピー。"),
           ("SplitCamに貼り付け", "SplitCamの<strong>Stream Settings</strong>を開き、URLとstream keyを貼り付け。ビットレートは3,500〜6,000 Kbps、1920×1080、30 fps、キーフレーム2秒に。"),
           ("Go Liveをクリック", "SplitCamで<strong>Go Live</strong>を押した後、Streamer Dashboardでオンラインに切り替え — Cherry.tv上で即配信開始です。"),
       ]),
    _p("amateurtv", "AmateurTV",
       "SplitCamでAmateurTV配信する方法 — スペイン語圏のcamネットワーク",
       "無料SplitCamでAmateurTV配信 — Model Panelの外部エンコーダー、スペインとLatAmのスペイン語camネットワーク、マルチカメラシーン。透かしなし、登録不要。",
       "amateurtv 配信, amateur.tv obs, amateurtv 外部エンコーダー, amateurtv rtmp, amateurtv stream key, modelos amateur tv",
       'SplitCamで<span class="accent">AmateurTV</span>配信する方法',
       "AmateurTV配信",
       "AmateurTVのスペイン語圏ネットワーク向け外部エンコーダー設定。",
       "AmateurTVはスペイン語圏で最大のcamネットワーク — スペイン、メキシコ、アルゼンチン、LatAm全域に厚いオーディエンスを持っています。デフォルトのModel Panel配信はブラウザ内で動きますが、標準の<strong>外部エンコーダー</strong>経路も併設 — 無料の<strong style='color:var(--text)'>SplitCam</strong>はそこに接続し、マルチカメラシーン、美肌フィルター、オーバーレイで、米国系ネットワークでは手薄なスペイン語圏オーディエンスに届けられます。",
       "SplitCamでAmateurTV配信：SplitCamをインストール、シーンを構築、Model Panelの<em>Broadcast Settings → External Encoder</em>を開く、サーバーURLとstream keyをコピー、SplitCamに貼り付け、Go Live。"
       "<ol><li>SplitCamをインストール。</li><li>カメラ＋シーンを追加。</li><li>Model PanelからURLとstream keyを取得。</li><li>SplitCamに貼り付け。</li><li>Go Liveを押す。</li></ol>",
       "AmateurTVのモデルアカウントにログインし、<strong>Model Panel</strong>を開いて<strong>Broadcast Settings → External Encoder</strong>に進みます。サーバーURLとstream keyはアカウントに紐づき表示されます — SplitCamのカスタムRTMPフィールドに両方コピー。新規モデルアカウントは配信前にID認証が必要です。",
       [("まずスペイン語圏ファースト", "AmateurTVのトラフィックは圧倒的にスペイン語 — 日中はスペイン、米国夕方以降はLatAmが中心。タイトル、シーンテキスト、オーバーレイをスペイン語にすると、英語オンリーより明らかに刺さります。"),
        ("LatAmの時間帯がゴールデン", "ピークトラフィックはLatAm夕方（UTC-3〜UTC-6）に集中。スケジュールが柔軟なら、欧州深夜／アジア早朝帯にあてるとスペインとLatAmの両ピークを取れます。"),
        ("中堅レンジで安定した分配", "業界トップRPMではないものの安定した分配で、米国系トップネットワークよりスペイン語圏ニッチの方が競争は少なめです。"),
        _T_ETH],
       [("AmateurTVはSplitCamのような外部エンコーダーを公式サポート？", "はい — Model PanelのBroadcast Settings配下にExternal Encoderオプションがあります。標準RTMPのサーバーURLとstream keyで、OBS、SplitCam、vMixなどがそのまま接続できます。"),
        ("AmateurTVのstream keyはどこ？", "Model Panel → Broadcast Settings → External Encoder。サーバーURLとstream keyが同じページに表示されます。SplitCamのカスタムRTMPフィールドに両方貼り付け。keyはアカウントに紐づきます。"),
        ("AmateurTVのビットレートは？", "標準的なcam画質 — 1920×1080、30 fps、3,500〜6,000 Kbps、キーフレーム2秒。先にSplitCam内蔵のスピードテストを実行してください。"),
        ("AmateurTVでSplitCamは無料？", "はい — SplitCamは完全無料、透かしなし、時間制限なし。AmateurTVのExternal Encoderオプションも無料で有効化できます。")],
       steps=[
           ("SplitCamをダウンロード・インストール", "SplitCamはWindowsとmacOS向けの無料配信ソフト — 登録なし、カードなし、透かしなし。AmateurTVへ映像を送るエンコーダーです。"),
           ("シーンを構築", "SplitCamでウェブカメラを追加し、オーバーレイ、テキスト、サブカメラやスマホ、美肌フィルター、AI背景を重ねます。AmateurTVのスペイン語圏オーディエンス向けに、オーバーレイのテキストはスペイン語で。"),
           ("AmateurTVのURLとstream keyを取得", "AmateurTVのモデルアカウントにログインし、<strong>Model Panel</strong>を開いて<strong>Broadcast Settings → External Encoder</strong>へ。サーバーURLと固有のstream keyが表示されます。両方コピー。"),
           ("SplitCamをAmateurTVへ接続", "SplitCamの<strong>Stream Settings</strong>を開き、AmateurTVのサーバーURLとstream keyをカスタムRTMPフィールドに貼り付け。ビットレートは3,500〜6,000 Kbps、1920×1080、30 fps、キーフレーム2秒に。内蔵のスピードテストも先に。"),
           ("Go Liveをクリック", "SplitCamで<strong>Go Live</strong>を押し、AmateurTVのModel Panelからオンラインに切り替え。約10秒以内に映像がネットワークへ届きます。2回目以降はワンクリック — SplitCamを開いてGo Liveだけ。"),
       ]),
    _p("camster", "Camster",
       "SplitCamでCamster配信する方法 — Model Hubの外部エンコーダー",
       "無料SplitCamでCamster配信 — Model Hubの外部エンコーダー、老舗中堅camプラットフォーム、マルチカメラシーンとオーバーレイ。透かしなし、登録不要。",
       "camster 配信, camster.com obs, camster 外部エンコーダー, camster rtmp, camster stream key, camster model hub",
       'SplitCamで<span class="accent">Camster</span>配信する方法',
       "Camster配信",
       "CamsterのModel Hub向け外部エンコーダー設定。",
       "Camsterは老舗の中堅camプラットフォーム — ChaturbateやLiveJasminより小規模ですが、固定ユーザーが厚く分配も公正です。デフォルトのModel Hub配信はブラウザ内で動きますが、標準の<strong>外部エンコーダー</strong>経路も併設 — 無料の<strong style='color:var(--text)'>SplitCam</strong>はそこに接続し、内蔵配信では出せないマルチカメラシーン、オーバーレイ、フィルターで配信できます。",
       "SplitCamでCamster配信：SplitCamをインストール、シーンを構築、Model Hubの<em>Broadcast Settings → External Encoder</em>を開く、サーバーURLとstream keyをコピー、SplitCamに貼り付け、Go Live。"
       "<ol><li>SplitCamをインストール。</li><li>カメラ＋シーンを追加。</li><li>Model HubでURLとstream keyを取得。</li><li>SplitCamに貼り付け。</li><li>Go Liveを押す。</li></ol>",
       "Camsterのモデルアカウントにログインし、<strong>Model Hub</strong>を開いて<strong>Broadcast Settings → External Encoder</strong>に進みます。サーバーURLとstream keyはアカウントに紐づきます — SplitCamのカスタムRTMPフィールドに両方コピー。keyはアカウントバインドなので、パスワード同様に扱ってください。",
       [("中堅は競争が少ないという強み", "Camsterはトラフィックは安定しつつ、トップネットワークよりブロードキャスター総数は少なめ — 作り込んだシーンと安定スケジュールでフロントページに乗りやすい環境です。"),
        ("ブラウザ配信 vs 外部エンコーダー", "デフォルトのブラウザ配信は単一ソース。SplitCam経由のExternal Encoderならマルチカメラシーン、オーバーレイ、美肌フィルター、AI背景まで使えます。"),
        ("公正な分配で支払いが安定", "Camsterの分配は中堅レンジでフェアな部類 — 業界最高ではないですが、月次の支払いは確実で、支払い遅延に関するモデルからの不満も少ないです。"),
        _T_ETH],
       [("CamsterはSplitCamのような外部エンコーダーを公式サポート？", "はい — Model HubのBroadcast Settings配下にExternal Encoderオプションがあります。標準RTMPのサーバーURLとstream keyで、OBS／SplitCamなどがそのまま接続できます。"),
        ("Camsterのstream keyはどこ？", "Model Hub → Broadcast Settings → External Encoder。サーバーURLとstream keyが同じページに表示されます。SplitCamのカスタムRTMPフィールドに両方貼り付け。"),
        ("Camsterのビットレートは？", "標準的なcam画質 — 1920×1080、30 fps、3,500〜6,000 Kbps、キーフレーム2秒。先にSplitCam内蔵のスピードテストを実行してください。"),
        ("CamsterでSplitCamは無料？", "はい — SplitCamは完全無料、透かしなし、時間制限なし。CamsterのExternal Encoderオプションも無料です。")],
       steps=[
           ("SplitCamをダウンロード・インストール", "SplitCamはWindowsとmacOS向けの無料配信ソフト — 登録なし、カードなし、透かしなし。"),
           ("シーンを構築", "SplitCamでウェブカメラを追加し、オーバーレイ、テキスト、サブカメラやスマホ、美肌フィルター、AI背景をライブで重ねます。"),
           ("CamsterのURLとstream keyを取得", "Camsterのモデルアカウントにログインし、<strong>Model Hub</strong>を開いて<strong>Broadcast Settings → External Encoder</strong>へ。サーバーURLと固有のstream keyが表示されます。両方コピー。"),
           ("SplitCamをCamsterへ接続", "SplitCamの<strong>Stream Settings</strong>を開き、CamsterのサーバーURLとstream keyをカスタムRTMPフィールドに貼り付け。ビットレートは3,500〜6,000 Kbps、1920×1080、30 fps、キーフレーム2秒。内蔵のスピードテストも先に。"),
           ("Go Liveをクリック", "SplitCamで<strong>Go Live</strong>を押し、CamsterのModel Hubからオンラインに切り替え。約10秒以内に映像がCamsterへ届きます。"),
       ]),
    _p("camversity", "Camversity",
       "SplitCamでCamversity配信する方法 — Performer Dashboardの外部エンコーダー",
       "無料SplitCamでCamversity配信 — Performer Dashboardの外部エンコーダー、パフォーマー寄りで伸び盛りの独立系camプラットフォーム、マルチカメラシーン。透かしなし、登録不要。",
       "camversity 配信, camversity obs, camversity 外部エンコーダー, camversity rtmp, camversity stream key, camversity performer",
       'SplitCamで<span class="accent">Camversity</span>配信する方法',
       "Camversity配信",
       "CamversityのPerformer Dashboard向け外部エンコーダー設定。",
       "Camversityは成長中の独立系camプラットフォーム — パフォーマー寄りのツールと、老舗ネットワークより低い手数料が特徴です。デフォルトのPerformer Dashboard配信はブラウザ内で動きますが、標準の<strong>外部エンコーダー</strong>経路も併設 — 無料の<strong style='color:var(--text)'>SplitCam</strong>はそこに接続し、マルチカメラシーン、オーバーレイ、フィルターで配信できます。",
       "SplitCamでCamversity配信：SplitCamをインストール、シーンを構築、Performer Dashboardの<em>Stream Settings → External Encoder</em>を開く、サーバーURLとstream keyをコピー、SplitCamに貼り付け、Go Live。"
       "<ol><li>SplitCamをインストール。</li><li>カメラ＋シーンを追加。</li><li>Performer DashboardでURLとstream keyを取得。</li><li>SplitCamに貼り付け。</li><li>Go Liveを押す。</li></ol>",
       "Camversityのパフォーマーアカウントにログインし、<strong>Performer Dashboard</strong>を開いて<strong>Stream Settings → External Encoder</strong>に進みます。サーバーURLとstream keyはアカウントに紐づき表示 — SplitCamのカスタムRTMPフィールドに両方コピー。新規アカウントは配信前に標準的なID認証が必要です。",
       [("パフォーマー寄りの分配", "Camversityの分配は老舗ネットワークよりパフォーマー側に有利 — cam活動の初期段階なら、現在のメイン平台と比較してみる価値があります。"),
        ("Docler系より軽いオンボーディング", "Camversityの認証はLiveJasminの48〜72時間審査より速く、それでいて適正（無認証のモデルが混ざることはない）。良い中間ゾーンです。"),
        ("ウェブカメラだけでなくシーンを作る", "CamversityのデフォルトPerformer Dashboard配信は単一ソース。SplitCam経由のExternal Encoderならマルチカメラ、オーバーレイ、美肌フィルターまで使えます。"),
        _T_ETH],
       [("CamversityはSplitCamのような外部エンコーダーを公式サポート？", "はい — Performer DashboardのStream Settings配下にExternal Encoderオプションがあります。標準RTMPのサーバーURLとstream keyで、OBS、SplitCam、vMixがそのまま接続できます。"),
        ("Camversityのstream keyはどこ？", "Performer Dashboard → Stream Settings → External Encoder。サーバーURLとstream keyが同じページに表示されます。"),
        ("Camversityのビットレートは？", "1920×1080、30 fps、3,500〜6,000 Kbps、キーフレーム2秒を狙ってください。先にSplitCam内蔵のスピードテストを実行。"),
        ("CamversityでSplitCamは無料？", "はい — SplitCamは完全無料、透かしなし、時間制限なし。CamversityのExternal Encoderオプションも無料です。")],
       steps=[
           ("SplitCamをダウンロード・インストール", "SplitCamはWindowsとmacOS向けの無料配信ソフト — 登録なし、カードなし、透かしなし。"),
           ("シーンを構築", "SplitCamでウェブカメラを追加し、オーバーレイ、テキスト、サブカメラやスマホ、美肌フィルター、AI背景を重ねます。"),
           ("CamversityのURLとstream keyを取得", "Camversityのパフォーマーアカウントにログインし、<strong>Performer Dashboard</strong>を開いて<strong>Stream Settings → External Encoder</strong>へ。サーバーURLと固有のstream keyが表示されます。両方コピー。"),
           ("SplitCamをCamversityへ接続", "SplitCamの<strong>Stream Settings</strong>を開き、CamversityのサーバーURLとstream keyをカスタムRTMPフィールドに貼り付け。ビットレートは3,500〜6,000 Kbps、1920×1080、30 fps、キーフレーム2秒に。"),
           ("Go Liveをクリック", "SplitCamで<strong>Go Live</strong>を押し、Performer Dashboardからオンラインに切り替え。約10秒以内に映像がCamversityへ届きます。"),
       ]),
]
