# -*- coding: utf-8 -*-
"""Malay (ms) content for cam-streaming-guides. Native Malay, 19 platforms."""

_T_ETH = ("Guna sambungan berwayar", "Ethernet mengatasi Wi-Fi semasa siaran panjang — bingkai yang "
          "hilang bermakna tip yang hilang. Sambungkan kabel ke PC yang menyiar.")
_T_TEST = ("Buat ujian peribadi dahulu", "Jalankan siaran ujian ringkas untuk menyemak kamera, audio, "
           "rangka dan tindihan sebelum membuka bilik kepada penonton.")

def _p(slug, name, title, desc, kw, h1html, h1short, card, intro, quick, key_how, tips, faq, steps=None):
    d = {"slug": slug, "name": name, "title": title, "desc": desc, "kw": kw,
         "h1html": h1html, "h1short": h1short, "card": card, "intro": intro,
         "quick": quick, "key_how": key_how, "tips": tips, "faq": faq}
    if steps: d["steps"] = steps
    return d

PLATFORMS_MS = [
    _p("chaturbate", "Chaturbate",
       "Siar di Chaturbate dengan SplitCam — Token & RTMP",
       "Siar di Chaturbate dengan SplitCam percuma — broadcast token, RTMP, adegan berbilang kamera dan tindihan. Tiada tera air, tiada pendaftaran.",
       "siaran chaturbate, chaturbate broadcast token, chaturbate rtmp obs, chaturbate pengekod luaran, chaturbate live",
       'Cara siar di <span class="accent">Chaturbate</span> dengan SplitCam',
       "Siaran Chaturbate",
       "Persediaan berasaskan token dengan pengekod luaran di Chaturbate.",
       "Chaturbate ialah salah satu platform cam terbesar, dibina atas ekonomi token. Penyiar pelayarnya hanyalah alat satu kamera yang rata — beralih kepada <strong style='color:var(--text)'>pengekod luaran</strong> dengan SplitCam percuma membuka adegan berbilang kamera, tindihan dan penapis dalam siaran berasaskan token yang sama.",
       "Siar di Chaturbate dengan SplitCam: pasang SplitCam, bina adegan, di Chaturbate buka <em>Broadcast Yourself → My Broadcast</em>, salin broadcast token, tampal dalam SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + adegan.</li><li>Salin broadcast token dari Chaturbate.</li><li>Tampal dalam SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di Chaturbate klik <strong>Broadcast Yourself</strong> untuk ke halaman <strong>My Broadcast</strong>, kemudian <strong>View RTMP/OBS broadcast information and stream key</strong>. Kunci muncul sebagai <strong>broadcast token</strong> — salinnya. Anggap ia seperti kata laluan; jangan sekali-kali kongsi.",
       [("Token ialah kuncinya", "Chaturbate menggunakan broadcast token anda, bukan kunci strim umum. Anggap ia seperti kata laluan dan set semula jika bocor."),
        ("Ruang luas", "RTMP ingest Chaturbate menerima sehingga 4K, 60 fps dan bitrate tinggi — hadnya ialah muat naik anda, bukan platform. Bingkai kunci setiap 2 saat."),
        _T_ETH, _T_TEST],
       [("Adakah Chaturbate membenarkan OBS / pengekod luaran?", "Ya — Chaturbate menyokong pengekod luaran secara rasmi dengan artikel «How do I set up OBS?» sendiri. Hidupkan melalui «Use External Encoder to Broadcast» dalam tetapan siaran."),
        ("Di mana kunci strim Chaturbate saya?", "Broadcast Yourself → My Broadcast → View RTMP/OBS broadcast information and stream key. Kuncinya ialah broadcast token anda."),
        ("Bitrate berapa untuk Chaturbate?", "3,500–6,000 Kbps pada 1080p sudah lebih daripada cukup. Siling Chaturbate tinggi — had sebenar ialah muat naik anda; jalankan ujian kelajuan terbina SplitCam dahulu."),
        ("Adakah SplitCam percuma untuk Chaturbate?", "Ya — percuma sepenuhnya, tiada tera air dan tiada had masa: pengekod tidak memakan pendapatan token anda.")]),
    _p("cam4", "CAM4",
       "Siar di CAM4 dengan SplitCam — External Encoder",
       "Siar di CAM4 dengan SplitCam percuma — External Encoder, kunci strim, sekatan geo dan tindihan. Tiada tera air.",
       "siaran cam4, cam4.com, cam4 external encoder, cam4 kunci strim, cam4 rtmp obs",
       'Cara siar di <span class="accent">CAM4</span> dengan SplitCam',
       "Siaran CAM4",
       "External Encoder di CAM4 dengan kawalan geo.",
       "CAM4 ialah platform cam-and-earn global dengan kawalan geo terbina — anda boleh sembunyikan siaran di negara tertentu. Menyiar melalui SplitCam percuma sebagai pengekod luaran membuka pertukaran adegan dan tindihan yang tiada pada penyiar asas.",
       "Siar di CAM4 dengan SplitCam: pasang SplitCam, bina adegan, di CAM4 buka <em>Broadcast &amp; Earn Money → Start Broadcast → External Encoder</em>, Get Stream Key, tampal dalam SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + adegan.</li><li>Dapatkan kunci strim dari CAM4.</li><li>Tampal dalam SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di CAM4 klik <strong>Broadcast</strong> → <strong>Broadcast &amp; Earn Money</strong> → <strong>Start Broadcast</strong>, kemudian <strong>External Encoder</strong> di atas. Isi tarikh lahir, jantina dan negara, guna <strong>Get Stream Key</strong> dan salin. Peluncur hijau dalam Stream Settings SplitCam menandakan sambungan.",
       [("Tetapkan sekatan geo", "CAM4 membenarkan menyembunyikan siaran di negara dan rantau tertentu — tetapkan di pihak CAM4 sebelum go-live."),
        ("Perhati peluncur hijau", "Persediaan CAM4 menunjukkan peluncur hijau dalam Stream Settings SplitCam apabila kunci diterima — merah = semak kunci."),
        ("Bitrate lebih rendah daripada biasa", "RTMP ingest CAM4 mengehadkan bitrate video kira-kira 3,000 Kbps — lebih rendah daripada kebanyakan tapak cam. Jangan paksa lebih tinggi."),
        _T_ETH],
       [("Adakah CAM4 menyokong OBS / pengekod luaran secara rasmi?", "Ya — CAM4 mempunyai OBS Guide rasmi di tapak sokongan dan mengesyorkan External Encoder untuk pengalaman terbaik. SplitCam menggunakan laluan RTMP yang sama."),
        ("Boleh saya sekat geo siaran CAM4?", "Ya — CAM4 mempunyai sekatan geo terbina untuk menyembunyikan siaran di negara tertentu. Tetapkan di CAM4, bukan dalam SplitCam."),
        ("Di mana kunci strim CAM4?", "Broadcast → Broadcast & Earn Money → Start Broadcast → External Encoder → Get Stream Key."),
        ("Bitrate berapa untuk CAM4?", "Lebih rendah daripada purata — RTMP ingest CAM4 mengehadkan ~3,000 Kbps pada 30 fps dengan bingkai kunci 1 saat. Jadual rasmi menasihatkan jangan melebihi ~3,000.")]),
    _p("bongacams", "BongaCams",
       "Siar di BongaCams dengan SplitCam — External Encoder",
       "Siar di BongaCams dengan SplitCam percuma — External Encoder, adegan berbilang kamera, tindihan dan latar AI. Tiada tera air.",
       "bongacams, bongcams, siaran bongacams, bongacams external encoder, bongacams rtmp obs",
       'Cara siar di <span class="accent">BongaCams</span> dengan SplitCam',
       "Siaran BongaCams",
       "Persediaan External Encoder untuk BongaCams.",
       "BongaCams ialah platform cam global. Siaran pengekod luaran tidak sentiasa dihidupkan — selepas diaktifkan, SplitCam percuma mengawal siaran dengan adegan berbilang kamera, tindihan dan latar AI.",
       "Siar di BongaCams dengan SplitCam: pasang SplitCam, bina adegan, di BongaCams buka <em>Options → Broadcast settings → Select Encoder → External Encoder</em>, salin URL dan kunci, tampal dalam SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + adegan.</li><li>Dapatkan URL dan kunci dari BongaCams.</li><li>Tampal dalam SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di BongaCams buka <strong>Options</strong> → <strong>Broadcast settings</strong> → <strong>Select Encoder</strong> → <strong>External Encoder</strong> dan salin URL pelayan serta kunci strim yang dipaparkan. <strong>Jika butang External Encoder tiada</strong>, hubungi sokongan BongaCams dan minta pengekodan luaran dihidupkan pada akaun anda.",
       [("Tiada butang External Encoder? Sokongan", "BongaCams menghidupkan pengekodan luaran bagi setiap akaun — jika pilihan tiada dalam Broadcast settings, sokongan mengaktifkannya."),
        ("Padankan resolusi", "BongaCams mengesyorkan resolusi kamera web dan siaran sepadan — contohnya kedua-duanya 1280×720."),
        _T_ETH, _T_TEST],
       [("Mengapa butang External Encoder tidak muncul di BongaCams?", "Pengekodan luaran tidak dihidupkan secara lalai pada setiap akaun — hubungi sokongan BongaCams untuk menghidupkannya, kemudian butang muncul dalam Broadcast settings."),
        ("Perlukah saya sahkan akaun BongaCams?", "Ya — siaran memerlukan 18+, ID rasmi untuk pengesahan umur dan kelulusan akaun sebelum live."),
        ("Bitrate berapa untuk BongaCams?", "RTMP ingest BongaCams mengehadkan bitrate video kira-kira 6,000 Kbps dengan bingkai kunci 2 saat — 3,500–6,000 pada 1080p ialah zon ideal; uji muat naik dahulu."),
        ("Adakah SplitCam percuma untuk BongaCams?", "Ya — percuma sepenuhnya, tiada tera air dan tiada had masa, jadi pengekod tidak mengurangkan pendapatan token anda di BongaCams.")]),
    _p("stripchat", "Stripchat",
       "Siar di Stripchat dengan SplitCam — Persediaan strip cam",
       "Siar di Stripchat — platform strip cam — dengan SplitCam percuma. Perisian luaran, kunci berasaskan token, adegan dan tindihan.",
       "strip cam, stripchat live stream, siaran stripchat, stripchat external software, stripchat kunci strim, stripchat rtmp obs",
       'Cara siar di <span class="accent">Stripchat</span> dengan SplitCam',
       "Siaran Stripchat",
       "Persediaan perisian luaran untuk siaran Stripchat.",
       "Stripchat ialah platform cam besar yang fokus pada interaktiviti. Mod <em>external software</em> memberi anda kunci berasaskan token — masukkan ke dalam SplitCam percuma untuk menyiar dengan adegan, tindihan dan penapis, bukan kamera rata.",
       "Siar di Stripchat dengan SplitCam: pasang SplitCam, bina adegan, di Stripchat pilih <em>Switch to external software</em>, salin kunci strim, tampal dalam SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + adegan.</li><li>Dapatkan kunci strim dari Stripchat.</li><li>Tampal dalam SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di Stripchat pilih <strong>Switch to external software</strong>, kemudian <strong>Show external software settings for the stream</strong>. Salin kunci strim — Stripchat memaparkannya sebagai token. Rahsiakannya.",
       [("Padankan resolusi dengan tapak", "FAQ Stripchat memberi amaran: resolusi dalam perisian anda mesti sepadan tepat dengan tapak, jika tidak video pecah. Tetapkan kedua-duanya sama."),
        ("Awas had minimum 2 Mbps", "Stripchat menyenaraikan 2 Mbps muat naik sebagai minimum — dan menyatakan terus terang ia tidak cukup untuk siaran OBS atau multistream. Sasarkan jauh lebih tinggi."),
        ("Kunci ialah token", "Kunci strim Stripchat ialah token — salin tepat, jangan kongsi, set semula jika bocor."),
        _T_ETH],
       [("Adakah Stripchat mengesyorkan OBS / perisian luaran?", "Ya — FAQ rasmi Stripchat mengesyorkan perisian siaran luaran seperti OBS «untuk mencapai kualiti video dan audio terbaik». SplitCam berfungsi dengan cara yang sama."),
        ("Bagaimana menukar Stripchat ke perisian luaran?", "Dalam Broadcast Center pilih Switch to External Broadcast Software (OBS), kemudian buka external software settings untuk memaparkan kunci strim (token)."),
        ("Bitrate berapa untuk Stripchat?", "RTMP ingest menerima sehingga ~6,000 Kbps dengan bingkai kunci 2 saat. 3,500–6,000 pada 1080p ideal — tetapi mesti jauh melebihi minimum 2 Mbps, terutama untuk siaran OBS."),
        ("Adakah SplitCam percuma untuk Stripchat?", "Ya — tiada yuran lesen, tiada tera air, tiada had masa: walaupun rancangan Stripchat interaktif yang panjang tidak berkos di pihak pengekod.")]),
    _p("onlyfans", "OnlyFans",
       "Live di OnlyFans dengan SplitCam — Kebenaran atau kunci",
       "Live di OnlyFans dengan SplitCam percuma — log masuk melalui kebenaran atau OBS Key, adegan berbilang kamera, tindihan. Tiada tera air.",
       "live onlyfans, onlyfans live stream, onlyfans kebenaran splitcam, onlyfans obs key, onlyfans perisian siaran",
       'Cara live di <span class="accent">OnlyFans</span> dengan SplitCam',
       "Live OnlyFans",
       "Beri kebenaran sekali atau tampal kunci — live di OnlyFans.",
       "Live OnlyFans untuk pelanggan anda. SplitCam menyambung dalam <strong style='color:var(--text)'>dua cara</strong> — log masuk sekali dengan akaun OnlyFans dan SplitCam mengambil kunci strim secara automatik serta menyegerakkannya, atau tampal OBS Key secara manual. Kedua-duanya membenarkan anda menyiar dengan adegan berbilang kamera, tindihan dan penapis.",
       "Live di OnlyFans dengan SplitCam: pasang SplitCam, bina adegan, buka Stream Settings &rarr; Add Channel &rarr; OnlyFans dan pilih <em>Kebenaran</em> — log masuk dengan akaun OnlyFans, SplitCam mengambil kunci automatik — kemudian tekan Go Live. Dengan akaun bersambung, anda boleh tukar parameter siaran OnlyFans dalam SplitCam tanpa membuka tapak OnlyFans.",
       "Di OnlyFans: <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; bahagian <strong>Other</strong>, salin <strong>OBS Key</strong>. Atau guna pilihan <strong>Kebenaran</strong> dalam SplitCam untuk log masuk — kunci diambil automatik dan kekal segerak.",
       [("Kebenaran vs Stream Key", "Dua cara menyambung: <strong>Kebenaran</strong> (log masuk sekali, kunci diambil dan disegerakkan — laluan termudah) atau <strong>Stream Key</strong> (salin OBS Key di OnlyFans → Profile → Settings → Other dan tampal)."),
        ("Tukar tetapan tanpa keluar dari SplitCam", "Dengan kebenaran, akaun kekal bersambung, jadi anda tetapkan parameter live OnlyFans dari SplitCam semasa atau selepas siaran — tanpa melawat tapak OnlyFans."),
        ("Bitrate sederhana", "RTMP ingest OnlyFans mengehadkan bitrate video kira-kira 2,500 Kbps — lebih ketat daripada kebanyakan tapak cam. Sasarkan 720p–1080p pada ~2,000–2,500."),
        _T_ETH],
       [("Bagaimana menyambung OnlyFans ke SplitCam?", "Dua cara. <strong>Kebenaran</strong> — Stream Settings → Add Channel → OnlyFans → log masuk dengan akaun OnlyFans dan SplitCam mengambil kunci automatik. Atau <strong>Stream Key</strong> — salin OBS Key di OnlyFans → Profile → Settings → Other dan tampal."),
        ("Boleh saya tukar tetapan live OnlyFans tanpa buka tapak?", "Ya — dengan kaedah Kebenaran, SplitCam kekal bersambung ke akaun OnlyFans, jadi kunci dan tetapan disegerakkan automatik. Anda tukar semua dari SplitCam semasa atau selepas siaran, tanpa melawat onlyfans.com."),
        ("Bitrate berapa untuk OnlyFans?", "Sederhana — RTMP ingest OnlyFans mengehadkan bitrate kira-kira 2,500 Kbps, jauh lebih ketat daripada platform cam lain. Sasarkan 720p–1080p sekitar 2,000–2,500 Kbps."),
        ("Adakah SplitCam percuma untuk live OnlyFans?", "Ya — percuma, tiada tera air dan tiada had masa. Tiada kos di pihak pengekod.")],
       steps=[
           ("Muat turun dan pasang SplitCam", "SplitCam ialah perisian penstriman langsung percuma untuk Windows dan macOS — tiada pendaftaran, tiada kad, tiada tera air. Ia pengekod yang menghantar video anda ke OnlyFans."),
           ("Tetapkan kamera dan adegan", "Buka SplitCam dan tambah kamera web. Bina adegan seperti yang anda mahu penonton lihat — tindihan, teks, kamera kedua, penapis kecantikan atau latar AI, semua dikenakan secara langsung."),
           ("Sambungan — Cara 1: Kebenaran (disyorkan)", "Dalam SplitCam buka <strong>Stream Settings</strong> &rarr; <strong>Add Channel</strong> &rarr; <strong>OnlyFans</strong> dan pilih <strong>Kebenaran</strong>. Log masuk dengan e-mel dan kata laluan OnlyFans. SplitCam memautkan akaun, mengambil kunci strim automatik dan menyegerakkannya — serta membenarkan anda menguruskan parameter live OnlyFans dalam SplitCam, menukarnya semasa atau selepas siaran tanpa membuka tapak OnlyFans."),
           ("Sambungan — Cara 2: Stream Key (manual)", "Tak mahu log masuk? Guna kunci. Di OnlyFans buka <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; bahagian <strong>Other</strong> dan salin <strong>OBS Key</strong>. Dalam SplitCam, Add Channel &rarr; OnlyFans, tampal ke medan kunci. Kunci ini statik — untuk tukar tetapan kemudian, kembali ke tapak OnlyFans."),
           ("Go Live", "Apa pun caranya, tekan <strong>Go Live</strong> dalam SplitCam. Dengan Cara 1 anda boleh terus melaras parameter OnlyFans dari SplitCam secara masa nyata; dengan Cara 2 kunci kekal tepat seperti yang anda tetapkan."),
       ]),
    _p("camplace", "CamPlace",
       "Siar di CamPlace dengan SplitCam — Panduan percuma",
       "Siar di CamPlace dengan SplitCam percuma — pengekod luaran, kunci RTMP, adegan dan tindihan. Langkah demi langkah, tiada tera air.",
       "siaran camplace, camplace broadcasting software, camplace rtmp, camplace pengekod luaran, camplace kunci strim",
       'Cara siar di <span class="accent">CamPlace</span> dengan SplitCam',
       "Siaran CamPlace",
       "Persediaan pengekod luaran untuk siaran CamPlace.",
       "CamPlace ialah platform cam-streaming. Tiada artikel OBS awam, jadi <strong style='color:var(--text)'>panduan video di atas</strong> ialah rujukan anda — SplitCam percuma menyambung melalui RTMP standard dan menambah adegan, tindihan serta latar AI yang tiada pada kamera asas.",
       "Siar di CamPlace dengan SplitCam: pasang SplitCam, bina adegan, hidupkan siaran luaran/RTMP di CamPlace, salin URL pelayan dan kunci strim, tampal dalam SplitCam, Go Live. Ikut video untuk laluan terkini."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + adegan.</li><li>Dapatkan kunci RTMP dari CamPlace.</li><li>Tampal dalam SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Log masuk ke CamPlace dan buka tetapan siaran. Tukar ke pilihan pengekod luaran / RTMP / OBS untuk memaparkan <strong>URL pelayan</strong> dan <strong>kunci strim</strong>, salin kedua-duanya. CamPlace tidak menerbitkan dokumentasi OBS rasmi — <strong>video di atas</strong> ialah laluan langkah demi langkah paling boleh dipercayai melalui antara muka semasa.",
       [("Tiada panduan OBS rasmi — guna video", "CamPlace tiada artikel awam tentang pengekod luaran; video di atas ialah rujukan laluan semasa."),
        ("RTMP standard berfungsi", "Walaupun tidak didokumentasi, CamPlace menerima URL pelayan RTMP standard dan kunci — SplitCam menyambung sebagai destinasi RTMP tersuai."),
        ("Susun tindihan dalam SplitCam", "Sasaran tip, nama dan pemegang media sosial ditambah sebagai lapisan adegan — kamera asas CamPlace tidak menambahnya."),
        _T_ETH],
       [("Adakah CamPlace mempunyai panduan OBS rasmi?", "Tiada artikel awam tentang pengekod luaran ditemui. CamPlace menerima URL RTMP standard dan kunci, jadi SplitCam berfungsi — ikut video."),
        ("Adakah CamPlace menyokong pengekod luaran?", "Ya — menerima kunci strim RTMP standard, jadi SplitCam menyambung sebagai destinasi RTMP tersuai."),
        ("Bitrate berapa untuk CamPlace?", "CamPlace tidak menerbitkan angka rasmi — guna 3,500–6,000 Kbps pada 1080p sebagai julat selamat dan biar ujian kelajuan SplitCam menentukan siling sebenar."),
        ("Adakah SplitCam percuma untuk CamPlace?", "Ya — percuma, tiada tera air dan tiada had masa. Kerana CamPlace tiada pengekod sendiri, alat RTMP percuma menyelesaikannya.")]),
    _p("camsoda", "CamSoda",
       "CamSoda live dengan SplitCam — Persediaan percuma",
       "CamSoda live dengan SplitCam percuma — Use OBS Broadcaster, pelayan serantau, adegan dan tindihan. Tiada tera air.",
       "camsoda live, siaran camsoda, camsoda obs broadcaster, camsoda rtmp obs, camsoda live broadcast",
       'Cara siar di <span class="accent">CamSoda</span> dengan SplitCam',
       "Siaran CamSoda",
       "Persediaan Use OBS Broadcaster di CamSoda.",
       "CamSoda ialah platform cam dari AS yang terkenal dengan format rancangan interaktif dan luar biasa. Ia menyokong siaran OBS secara rasmi — ada butang <strong style='color:var(--text)'>Use OBS Broadcaster</strong> di halaman Go Live dan panduan OBS rasmi di wiki CamSoda. SplitCam percuma berfungsi dengan cara yang sama.",
       "Siar di CamSoda dengan SplitCam: pasang SplitCam, bina adegan, klik Use OBS Broadcaster di halaman Go Live CamSoda, salin URL pelayan dan kunci strim, tampal dalam SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + adegan.</li><li>Klik Use OBS Broadcaster di CamSoda.</li><li>Tampal URL pelayan + kunci dalam SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di halaman <strong>Go Live</strong> CamSoda klik <strong>Use OBS Broadcaster</strong>. CamSoda memaparkan URL pelayan RTMP dan kunci strim — salin kedua-duanya. Pilih pelayan serantau (Amerika Utara, Eropah, Asia, dll.) terdekat. Wiki CamSoda mempunyai panduan OBS penuh untuk butiran.",
       [("Sahkan untuk menerima tip", "Di CamSoda sesiapa boleh menyiar, tetapi untuk menerima tip anda mesti melengkapkan proses pengesahan CamSoda."),
        ("Pilih pelayan serantau terdekat", "CamSoda menawarkan pelayan ingest serantau — terdekat (AU / Eropah / Asia / Amerika Selatan / Oceania) mengurangkan kelewatan dan bingkai hilang."),
        ("Siling pada 1080p / 30 fps", "Ingest CamSoda mencapai kira-kira 1080p, 30 fps dan ~6,000 Kbps — jangan paksa lebih tinggi."),
        _T_ETH],
       [("Adakah CamSoda menyokong OBS / pengekod luaran?", "Ya — secara rasmi. Ada butang Use OBS Broadcaster di halaman Go Live dan panduan OBS di wiki CamSoda, jadi SplitCam berfungsi."),
        ("Perlukah pengesahan di CamSoda?", "Untuk menyiar, tidak. Untuk menerima tip, ya — CamSoda memerlukan anda melalui proses pengesahan dahulu."),
        ("Resolusi apa yang disokong CamSoda?", "Sehingga 1920×1080 pada 30 fps, maksimum sekitar 6,000 Kbps dalam RTMP ingest."),
        ("Adakah SplitCam percuma untuk CamSoda?", "Ya — percuma, tiada tera air dan tiada had masa. Berfungsi dengan mod Use OBS Broadcaster percuma CamSoda, jadi keseluruhan persediaan tidak berkos.")]),
    _p("streamate", "Streamate",
       "Siar di Streamate dengan SplitCam — Saluran bersepadu",
       "Siar di Streamate dengan SplitCam percuma — saluran bersepadu, kunci SM Connect, adegan dan tindihan. Tiada tera air.",
       "streamate, streamate sm connect, siaran streamate, streamate broadcasting software, streamate rtmp",
       'Cara siar di <span class="accent">Streamate</span> dengan SplitCam',
       "Siaran Streamate",
       "Streamate ialah saluran bersepadu dalam SplitCam — persediaan pantas.",
       "Streamate ialah platform cam mapan — dan ialah <strong style='color:var(--text)'>destinasi prakonfigurasi dalam SplitCam</strong>, dalam senarai saluran, jadi persediaan lebih pantas daripada input RTMP manual: pilih Streamate, tampal kunci, selesai.",
       "Siar di Streamate dengan SplitCam: pasang SplitCam, bina adegan, di Streamate guna <em>SM Connect → Start Show</em> dan salin kunci, kemudian dalam SplitCam buka <em>Stream Settings → Add Channel → Streamate</em> dan tampal."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + adegan.</li><li>Dapatkan kunci Streamate melalui SM Connect.</li><li>Add Channel → Streamate dalam SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di Streamate buka <strong>SM Connect</strong>, setuju dengan terma, klik <strong>Start Show</strong> di kiri dan tutup tetingkap yang terbuka — kemudian salin kunci penstriman. Dalam SplitCam buka <strong>Stream Settings</strong> → <strong>Add Channel</strong>, pilih <strong>Streamate</strong> dari senarai dan tampal kunci. Peluncur hijau menandakan sambungan.",
       [("Streamate bersepadu", "Tiada URL RTMP manual — SplitCam mempunyai Streamate dalam senarai Add Channel; cuma pilih dan tampal kunci."),
        ("Tutup popup SM Connect", "Selepas Start Show, Streamate membuka tetingkap — tutupnya; ia hanya untuk memaparkan kunci penstriman."),
        ("Kunci resolusi ke 1080p", "Medan Video Resolution dalam SM Connect mungkin diam-diam melonjak ke 1440, yang sebenarnya tidak dihantar dan menurunkan kualiti anda secara senyap — tetapkan manual ke 1080p. Bitrate jatuh apabila imej statik adalah normal: strim Streamate adaptif."),
        _T_ETH, _T_TEST],
       [("Adakah Streamate bersepadu dalam SplitCam?", "Ya — Streamate muncul dalam senarai Add Channel SplitCam; anda pilih, bukan taip URL RTMP manual."),
        ("Di mana kunci penstriman Streamate?", "SM Connect → setuju dengan terma → Start Show → tutup popup → salin kunci."),
        ("Bitrate berapa untuk Streamate?", "Streamate tidak menetapkan siling keras — 3,500–6,000 Kbps pada 1080p berfungsi baik. Strim adaptif, jadi bitrate lebih rendah apabila imej statik adalah normal, bukan pepijat."),
        ("Adakah SplitCam percuma untuk Streamate?", "Ya — percuma, tiada tera air dan tiada had masa; dan kerana Streamate saluran bersepadu dalam SplitCam, tiada kos pengekod berasingan.")]),
    _p("streamray", "StreamRay",
       "Siar di StreamRay cam dengan SplitCam — URL dalam chat",
       "Siar di StreamRay cam dengan SplitCam percuma — URL disiarkan dalam chat, mod OBS Broadcaster, adegan dan tindihan. Tiada tera air.",
       "streamray, streamray cam, siaran streamray, streamray obs broadcaster, streamray rtmp",
       'Cara siar di <span class="accent">StreamRay</span> dengan SplitCam',
       "Siaran StreamRay",
       "Persediaan pengekod luaran jenis URL-dalam-chat untuk StreamRay.",
       "StreamRay mempunyai persediaan pengekod luaran luar biasa — ia menghantar URL strim dalam <strong style='color:var(--text)'>tetingkap chat siaran</strong> dan tidak menggunakan kunci strim berasingan. SplitCam percuma mengendalikan aliran hanya-URL ini.",
       "Siar di StreamRay dengan SplitCam: pasang SplitCam, bina adegan, di StreamRay hidupkan OBS Broadcaster, salin URL strim dari tetingkap chat, tampal dalam SplitCam (biar medan kunci kosong), Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + adegan.</li><li>Salin URL StreamRay dari chat.</li><li>Tampal URL dalam SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di StreamRay klik dua kali <strong>Broadcast Now</strong>, buka menu <strong>Other</strong>, pilih <strong>OBS Broadcaster</strong> dan <strong>Save and Close</strong>. StreamRay kemudian menyiarkan <strong>URL strim dalam tetingkap chat</strong> — salin dari sana. Biar medan kunci strim SplitCam <strong>kosong</strong>; StreamRay hanya mengesahkan melalui URL.",
       [("URL ada dalam chat", "StreamRay tidak memaparkan URL strim dalam kotak tetapan — ia menyiarkannya dalam tetingkap chat siaran. Salin dari sana."),
        ("Biar medan kunci kosong", "StreamRay tidak menggunakan kunci berasingan — hanya URL. Jangan masukkan apa-apa ke medan kunci SplitCam."),
        _T_ETH, _T_TEST],
       [("Di mana URL strim StreamRay?", "Selepas menghidupkan OBS Broadcaster, StreamRay menyiarkan URL dalam tetingkap chat — salin dari chat."),
        ("Mengapa tiada kunci strim di StreamRay?", "StreamRay hanya mengesahkan melalui URL — biar medan kunci SplitCam kosong."),
        ("Bitrate berapa untuk StreamRay?", "StreamRay tidak menyatakan siling rasmi — sasarkan 3,500–6,000 Kbps pada 1080p dan jalankan ujian kelajuan SplitCam, kerana aliran hanya-URL tidak memberi maklum balas bitrate."),
        ("Adakah SplitCam percuma untuk StreamRay?", "Ya — percuma, tiada tera air dan tiada had masa, sesuai dengan aliran hanya-URL StreamRay: tampal satu pautan dan anda live.")]),
    _p("xlovecam", "XLoveCam",
       "Siar di XLoveCam dengan SplitCam — Pautan RTMP & kunci",
       "Siar di XLoveCam dengan SplitCam percuma — pautan RTMP dan kunci, pelayan serantau, adegan dan tindihan. Tiada tera air.",
       "xlovecam, x love cam, siaran xlovecam, xlovecam rtmp link, xlovecam kunci strim",
       'Cara siar di <span class="accent">XLoveCam</span> dengan SplitCam',
       "Siaran XLoveCam",
       "Persediaan pautan RTMP + kunci untuk XLoveCam.",
       "XLoveCam ialah platform cam Eropah berbilang bahasa. Tetapan akaun memaparkan kedua-dua <strong style='color:var(--text)'>pautan RTMP</strong> dan <strong style='color:var(--text)'>kunci strim</strong> — SplitCam percuma mengambil kedua-duanya dan menyiar dengan adegan serta tindihan penuh.",
       "Siar di XLoveCam dengan SplitCam: pasang SplitCam, bina adegan, di XLoveCam buka <em>My Account → settings</em>, salin pautan RTMP dan kunci strim, tampal kedua-duanya dalam SplitCam, mula rancangan."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + adegan.</li><li>Salin pautan RTMP + kunci dari XLoveCam.</li><li>Tampal kedua-duanya dalam SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di XLoveCam buka <strong>My Account</strong> → <strong>settings</strong>. Tetapan memaparkan kedua-dua <strong>pautan RTMP</strong> dan <strong>kunci strim</strong> — salin kedua-duanya ke medan URL pelayan dan kunci SplitCam, kemudian <strong>Start your show</strong> di XLoveCam.",
       [("Salin pautan DAN kunci", "XLoveCam memberi pautan RTMP DAN kunci strim berasingan — anda perlukan kedua-duanya dalam SplitCam, bukan satu sahaja."),
        ("Penonton berbilang bahasa", "XLoveCam Eropah dan berbilang bahasa — tindihan teks jelas dalam bahasa anda membantu penonton menemui anda."),
        ("Pilih pelayan terdekat", "XLoveCam menawarkan pelayan RTMP serantau — Eropah, Amerika Utara, Amerika Selatan dan Asia. Terdekat mengurangkan kelewatan dan bingkai hilang."),
        _T_ETH],
       [("Di mana data RTMP XLoveCam?", "My Account → settings — memaparkan kedua-dua pautan RTMP dan kunci."),
        ("Adakah XLoveCam menyokong pengekod luaran?", "Ya — menyediakan pautan RTMP dan kunci, jadi SplitCam berfungsi sebagai pengekod."),
        ("Bitrate berapa untuk XLoveCam?", "XLoveCam tidak menerbitkan had tetap; 3,500–6,000 Kbps pada 1080p ideal. Memilih pelayan serantau terdekat sama penting — ia mengurangkan bingkai hilang."),
        ("Adakah SplitCam percuma untuk XLoveCam?", "Ya — percuma, tiada tera air dan tiada had masa. Mencapai penonton Eropah berbilang bahasa XLoveCam tidak memerlukan kos perisian.")]),
    _p("soulcams", "SoulCams",
       "Siar di SoulCams dengan SplitCam — Tetapan OBS",
       "Siar di SoulCams dengan SplitCam percuma — tetapan OBS, pelayan RTMP dan kunci, adegan berbilang kamera dan tindihan.",
       "soul cams, soulcams, siaran soulcams, soulcams obs, soulcams rtmp, soulcams broadcast",
       'Cara siar di <span class="accent">SoulCams</span> dengan SplitCam',
       "Siaran SoulCams",
       "Tetapan OBS untuk SoulCams.",
       "SoulCams ialah platform cam yang tetapan OBS-nya memaparkan <strong style='color:var(--text)'>pelayan RTMP dan kunci strim bersama</strong> dalam satu tetingkap. Tampal kedua-duanya dalam SplitCam percuma untuk menyiar dengan adegan berbilang kamera dan tindihan.",
       "Siar di SoulCams dengan SplitCam: pasang SplitCam, bina adegan, di SoulCams klik Go Online → Settings → OBS, salin pelayan dan kunci, tampal kedua-duanya dalam SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + adegan.</li><li>Buka SoulCams Settings → OBS.</li><li>Tampal pelayan + kunci dalam SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di SoulCams log masuk dan klik <strong>Go Online</strong>, kemudian buka <strong>Settings</strong> → <strong>OBS</strong>. Tetingkap OBS memaparkan <strong>pelayan RTMP</strong> dan <strong>kunci strim</strong> bersama — salin kedua-duanya ke SplitCam.",
       [("Pelayan dan kunci bersebelahan", "SoulCams memaparkan pelayan RTMP dan kunci dalam tetingkap OBS yang sama — ambil kedua-duanya sekali gus."),
        ("Go Online dahulu", "Tetapan OBS muncul hanya selepas klik Go Online di SoulCams — buat itu sebelum mencari data pengekod."),
        ("Sekat rantau yang tidak diingini", "SoulCams membenarkan sekatan geo dari pihak model — pilih negara mana yang tidak boleh lihat strim sebelum tekan Go Online."),
        _T_ETH, _T_TEST],
       [("Di mana tetapan OBS SoulCams?", "Log masuk, klik Go Online, kemudian Settings → OBS — pelayan RTMP dan kunci strim dipaparkan bersama."),
        ("Adakah SoulCams menyokong pengekod luaran?", "Ya — tetapan OBS memberi pelayan RTMP dan kunci, jadi SplitCam berfungsi."),
        ("Bitrate berapa untuk SoulCams?", "SoulCams tidak memberi angka rasmi — sasarkan 3,500–6,000 Kbps pada 1080p dan uji muat naik, kerana tetingkap OBS tidak memaparkan panduan bitrate."),
        ("Adakah SplitCam percuma untuk SoulCams?", "Ya — percuma, tiada tera air dan tiada had masa, jadi rancangan penuh di SoulCams dengan adegan berbilang kamera dan tindihan tidak berkos di pihak pengekod.")]),
    _p("imlive", "ImLive",
       "Guna ImLive dengan SplitCam — Kamera maya",
       "Persediaan Im Live stream dengan SplitCam percuma — ImLive guna kamera web langsung (tiada RTMP), sambung SplitCam sebagai kamera maya dengan adegan.",
       "im live stream, imlive splitcam, siaran imlive, imlive kamera maya, imlive webcam, im live cam",
       'Cara guna <span class="accent">ImLive</span> dengan SplitCam',
       "SplitCam di ImLive",
       "Persediaan kamera maya untuk ImLive — tiada RTMP.",
       "ImLive menggunakan kamera web langsung dalam pelayar — <strong style='color:var(--text)'>tiada RTMP atau kunci strim</strong>. SplitCam percuma menyambung sebagai <strong style='color:var(--text)'>kamera maya</strong>: bina adegan dalam SplitCam, kemudian pilih SplitCam sebagai kamera di ImLive.",
       "Guna SplitCam dengan ImLive: pasang SplitCam, bina adegan dengan lapisan media, buka ImLive dan mula chat video, dalam tetapan ImLive pilih SplitCam sebagai kamera web dan mikrofon."
       "<ol><li>Pasang SplitCam.</li><li>Bina adegan dalam SplitCam.</li><li>Mula chat video di ImLive.</li><li>Pilih SplitCam sebagai kamera ImLive.</li><li>Mula chat.</li></ol>",
       "Log masuk ke tapak ImLive dan klik <strong>Start Video Chat</strong>, kemudian buka <strong>Go To Settings</strong> untuk mencapai pilihan kamera dan mikrofon. Dalam tetapan ImLive pilih <strong>SplitCam</strong> sebagai kamera web dan mikrofon.",
       [("Tiada kunci strim diperlukan", "ImLive tiada RTMP — jangan cari URL pelayan atau kunci. SplitCam hanya dipilih sebagai peranti kamera."),
        ("Tetapkan SplitCam sebagai mikrofon juga", "Pilih SplitCam untuk mikrofon di samping kamera, supaya campuran audio dan penindasan bising turut masuk ke live."),
        ("Bina adegan sebelum live", "ImLive memaparkan apa yang SplitCam hantar — susun lapisan sebelum mula chat."),
        _T_TEST],
       [("Adakah ImLive guna RTMP atau kunci strim?", "Tiada satu pun — ImLive guna kamera web langsung melalui pelayar. SplitCam menyambung sebagai kamera maya, tiada kunci untuk disalin."),
        ("Bagaimana memilih SplitCam di ImLive?", "Start Video Chat → Go To Settings → pilih SplitCam sebagai kamera web dan mikrofon."),
        ("Boleh saya guna tindihan di ImLive?", "Ya — bina dalam adegan SplitCam; ImLive memaparkan hasil tergabung."),
        ("Adakah SplitCam percuma untuk ImLive?", "Ya — percuma, tiada tera air dan tiada had masa. Sebagai kamera maya untuk ImLive, ia tidak menambah kos atau penjenamaan pada chat video anda.")],
       steps=[
           ("Pasang SplitCam", "SplitCam ialah perisian percuma untuk Windows dan macOS. Pasangnya — tiada tera air, tiada pendaftaran. Untuk ImLive ia berfungsi sebagai <strong>kamera maya</strong>, bukan pengekod RTMP."),
           ("Bina adegan dalam SplitCam", "Buka SplitCam dan guna <strong>Media Layers +</strong> untuk menambah kamera web serta sebarang tindihan, teks, penapis atau latar AI. Adegan tergabung ini ialah yang ImLive lihat sebagai kamera anda."),
           ("Mula chat video di ImLive", "Log masuk ke tapak ImLive dan klik <strong>Start Video Chat</strong>, kemudian buka <strong>Go To Settings</strong> untuk mencapai pilihan kamera dan mikrofon."),
           ("Pilih SplitCam sebagai kamera", "Dalam tetapan ImLive pilih <strong>SplitCam</strong> sebagai kamera web DAN mikrofon. ImLive kini memaparkan adegan SplitCam penuh anda, bukan kamera web rata."),
           ("Mula Free Live Chat", "Klik <strong>Free Live Chat</strong> di ImLive untuk live. Untuk menukar rupa di tengah sesi, sunting adegan dalam SplitCam — ImLive mengemas kini serta-merta."),
       ]),
    _p("vxlive", "VXLive",
       "Siar di VXLive dengan SplitCam — Sokongan rasmi",
       "Siar di VXLive (VXModels / VISIT-X) dengan SplitCam percuma — praset VISIT-X rasmi, pelayan dan kunci, adegan. Tiada tera air.",
       "vxlive, visit-x, vxmodels splitcam, siaran vxlive, visit-x stream, vxlive rtmp",
       'Cara siar di <span class="accent">VXLive</span> dengan SplitCam',
       "Siaran VXLive",
       "VXLive menyokong SplitCam secara rasmi (praset VISIT-X).",
       "VXLive (VXModels / VISIT-X) ialah platform cam dari pasaran Jerman — dan salah satu daripada segelintir yang <strong style='color:var(--text)'>menyokong SplitCam secara rasmi dengan nama</strong>. VXModels mempunyai artikel bantuan khusus untuk menyambung <strong style='color:var(--text)'>SplitCam</strong> ke VXLive, dan SplitCam menawarkan VISIT-X sebagai praset saluran sedia guna.",
       "Siar di VXLive dengan SplitCam: pasang SplitCam, bina adegan, di VXLive pilih «Stream with third-party software», salin URL pelayan dan kunci, dalam SplitCam pilih praset VISIT-X dan tampal, Go Live dalam SplitCam, kemudian GO ONLINE di VXLive."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + adegan.</li><li>Dapatkan URL pelayan + kunci dari VXLive.</li><li>Pilih praset VISIT-X dalam SplitCam, tampal.</li><li>Go Live, kemudian GO ONLINE di VXLive.</li></ol>",
       "Di VXLive pilih <strong>Stream with third-party software</strong> dan pilihan <strong>OBS, SplitCam atau XSplit</strong>. VXLive menyediakan <strong>URL pelayan</strong> dan <strong>kunci strim</strong>. Dalam SplitCam pilih <strong>VISIT-X</strong> sebagai platform penstriman, tampal kedua-duanya, tekan <strong>Go Live</strong> dalam SplitCam, kemudian <strong>GO ONLINE</strong> di VXLive.",
       [("VISIT-X ialah praset bersepadu", "Jangan taip URL RTMP mentah — SplitCam mempunyai VISIT-X dalam senarai platform; cuma pilih dan tampal URL pelayan dan kunci."),
        ("Go-live dua langkah", "Di VXLive tekan Go Live dalam SplitCam dahulu, kemudian GO ONLINE di VXLive — kedua-duanya, dalam susunan itu."),
        ("Pasaran Jerman", "Penonton VXLive kebanyakannya berbahasa Jerman — tindihan teks atau tajuk Jerman membantu menghubungkan dengan penonton."),
        _T_ETH],
       [("Adakah VXLive menyokong SplitCam secara rasmi?", "Ya — VXModels (VXLive) menyelenggara artikel bantuan rasmi khusus untuk persediaan SplitCam dan menyenaraikan SplitCam bersama OBS dan XSplit sebagai perisian siaran yang disokong."),
        ("Bagaimana menyambung SplitCam ke VXLive?", "Di VXLive pilih «Stream with third-party software», kemudian dalam SplitCam pilih praset VISIT-X dan tampal URL pelayan dan kunci strim yang diberi VXLive."),
        ("Adakah saya live dalam SplitCam atau VXLive?", "Kedua-duanya — Go Live dalam SplitCam dahulu, kemudian GO ONLINE di VXLive."),
        ("Mengapa VXModels mengesyorkan SplitCam?", "Artikel bantuan rasmi VXModels mengesyorkan SplitCam khusus untuk menghapuskan artifak imej kamera web dan pikselasi serta menstabilkan sambungan — bukan sekadar pengekod umum.")]),
    _p("virtwish", "VirtWish",
       "Siar di VirtWish dengan SplitCam — URL strim & kunci",
       "Siar di VirtWish dengan SplitCam percuma — bahagian OBS Profile → Start Broadcast, URL strim dan kunci, adegan dan tindihan.",
       "virtwish, siaran virtwish, virtwish broadcasting software, virtwish rtmp, virtwish kunci strim, virtwish obs",
       'Cara siar di <span class="accent">VirtWish</span> dengan SplitCam',
       "Siaran VirtWish",
       "Persediaan URL strim + kunci untuk VirtWish.",
       "VirtWish ialah platform cam interaktif. Tetapan siaran memberi anda <strong style='color:var(--text)'>URL strim dan kunci strim berasingan</strong> dalam bahagian OBS — SplitCam percuma mengambil kedua-duanya dan menjalankan rancangan dengan adegan dan tindihan.",
       "Siar di VirtWish dengan SplitCam: pasang SplitCam, bina adegan, di VirtWish buka <em>Profile → Start Broadcast</em> hingga bahagian OBS, salin pautan dan kunci, tampal kedua-duanya dalam SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + adegan.</li><li>Dapatkan URL + kunci dari VirtWish.</li><li>Tampal kedua-duanya dalam SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Di VirtWish klik ikon di penjuru kanan atas → <strong>Profile</strong> → <strong>Start Broadcast</strong>, kemudian <strong>Start Broadcast</strong> sekali lagi untuk mencapai bahagian OBS. <strong>Salin pautan pada baris pertama</strong> ke medan Stream URL SplitCam, dan <strong>Stream Key</strong> berasingan ke medan kunci.",
       [("Pautan pada baris pertama", "Bahagian OBS VirtWish meletakkan URL strim pada baris pertama — salin ke Stream URL SplitCam, kemudian kunci berasingan."),
        ("Dua klik pada Start Broadcast", "Anda klik Start Broadcast dua kali di VirtWish untuk mencapai bahagian OBS — itu normal, bukan pepijat."),
        _T_ETH, _T_TEST],
       [("Di mana data RTMP VirtWish?", "Ikon kanan atas → Profile → Start Broadcast dua kali → bahagian OBS memaparkan pautan dan kunci strim."),
        ("Adakah VirtWish menyokong pengekod luaran?", "Ya — bahagian OBS menyediakan URL strim dan kunci, jadi SplitCam berfungsi."),
        ("Bitrate berapa untuk VirtWish?", "VirtWish tidak menerbitkan siling rasmi; 3,500–6,000 Kbps pada 1080p selamat. Padankan resolusi SplitCam dengan yang ditetapkan di VirtWish untuk elak penskalaan semula."),
        ("Adakah SplitCam percuma untuk VirtWish?", "Ya — percuma, tiada tera air dan tiada had masa. Persediaan URL-dan-kunci VirtWish hanya mengambil beberapa minit yang diperlukan.")]),
    _p("xmodels", "XModels",
       "Siar di XModels dengan SplitCam — Panduan percuma",
       "Siar di XModels dengan SplitCam percuma — pilihan pengekod luaran dalam tetapan akaun model, kunci RTMP, adegan dan tindihan.",
       "xmodels, siaran xmodels, xmodels broadcasting software, xmodels rtmp, xmodels pengekod luaran",
       'Cara siar di <span class="accent">XModels</span> dengan SplitCam',
       "Siaran XModels",
       "Persediaan pengekod luaran untuk siaran XModels.",
       "XModels ialah platform cam-streaming dengan <strong style='color:var(--text)'>pilihan pengekod luaran</strong> terbina dalam tetapan akaun model. SplitCam percuma menyiar di sana dengan adegan berbilang kamera, tindihan dan penapis, bukan satu kamera rata.",
       "Siar di XModels dengan SplitCam: pasang SplitCam, bina adegan, dalam akaun model XModels hidupkan pilihan pengekod luaran, salin URL pelayan dan kunci strim, tampal dalam SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + adegan.</li><li>Hidupkan pengekod luaran dalam tetapan XModels.</li><li>Tampal URL pelayan + kunci dalam SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Dalam <strong>tetapan akaun model</strong> XModels, hidupkan pilihan <strong>siar melalui pengekod luaran</strong>. XModels menyediakan <strong>kunci strim</strong> — salinnya ke SplitCam. Jika pilihan tiada di tempat yang anda jangka, sokongan XModels melalui chat FAQ di tapak dan <strong>info@xmodels.com</strong>; video di atas turut menunjukkannya.",
       [("Ia dalam tetapan akaun", "XModels meletakkan pilihan pengekod luaran dalam tetapan akaun model, bukan skrin siaran berasingan."),
        ("Sokongan: chat + e-mel", "XModels tiada pusat bantuan awam besar — chat FAQ di tapak dan info@xmodels.com ialah saluran sokongan rasmi."),
        ("Susun tindihan dalam SplitCam", "Sasaran tip, nama dan pemegang media sosial ditambah sebagai lapisan adegan — kamera asas XModels tidak menambahnya."),
        _T_ETH],
       [("Adakah XModels menyokong pengekod luaran?", "Ya — tetapan akaun model mempunyai pilihan siaran pengekod luaran yang menyediakan kunci strim, jadi SplitCam berfungsi."),
        ("Di mana mendapat bantuan XModels?", "Sokongan XModels melalui chat FAQ di tapak dan e-mel info@xmodels.com — tiada pusat bantuan awam besar."),
        ("Bitrate berapa untuk XModels?", "XModels tidak mendokumentasi angka rasmi — guna 3,500–6,000 Kbps pada 1080p dan jalankan ujian kelajuan SplitCam, kerana sokongan XModels hanya melalui chat dan e-mel."),
        ("Adakah SplitCam percuma untuk XModels?", "Ya — percuma, tiada tera air dan tiada had masa, jadi menyiar ke rangkaian Eropah XModels tidak menambah kos perisian.")]),
    _p("flirt4free", "Flirt4Free",
       "Siar di Flirt for Free cam dengan SplitCam — Panduan percuma",
       "Siar di Flirt for Free cam dengan SplitCam percuma — External Broadcast Form, RTMP URL dan Stream Name, adegan dan tindihan.",
       "flirt for free cam, flirt 4 free cam, flirt4free, siaran flirt4free, flirt4free external broadcast, flirt4free rtmp",
       'Cara siar di <span class="accent">Flirt4Free</span> dengan SplitCam',
       "Siaran Flirt4Free",
       "Persediaan External Broadcast Form untuk Flirt4Free.",
       "Flirt4Free ialah salah satu platform cam tertua, di udara sejak 90-an. Ia menyokong siaran luaran secara rasmi melalui <strong style='color:var(--text)'>External Broadcast Form</strong> — SplitCam percuma menghantar strim manakala borang menetapkan resolusi dan bitrate.",
       "Siar di Flirt4Free dengan SplitCam: pasang SplitCam, bina adegan, buka External Broadcast Form Flirt4Free, salin RTMP URL dan Stream Name serta tetapkan resolusi/bitrate, tampal dalam SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + adegan.</li><li>Buka External Broadcast Form Flirt4Free.</li><li>Tampal RTMP URL + Stream Name dalam SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Dalam zon model Flirt4Free buka <strong>External Broadcast Form</strong>. Berbeza daripada kebanyakan tapak cam, Flirt4Free memberi <strong>RTMP URL</strong> dan <strong>Stream Name</strong> (bukan «kunci»), serta medan resolusi dan bitrate yang anda isi dalam borang itu sendiri. Salin URL dan Stream Name ke medan pelayan dan kunci SplitCam.",
       [("Ia Stream Name, bukan kunci", "Flirt4Free memanggil kelayakannya Stream Name. Anda tampal ke medan kunci strim SplitCam — fungsinya sama."),
        ("Tetapkan resolusi/bitrate dalam borang", "External Broadcast Form Flirt4Free mempunyai medan resolusi dan bitrate sendiri — selaraskan dengan tetapan SplitCam supaya imej tidak diskala semula."),
        ("Platform bersejarah", "Flirt4Free berjalan sejak 90-an — alat modelnya matang, dan External Broadcast Form ialah bahagian terdokumentasinya."),
        _T_ETH],
       [("Adakah Flirt4Free menyokong pengekod luaran?", "Ya — secara rasmi, melalui External Broadcast Form yang menyediakan RTMP URL dan Stream Name. SplitCam berfungsi sebagai pengekod."),
        ("Di mana mendapat data RTMP Flirt4Free?", "Dari External Broadcast Form dalam zon model — memaparkan RTMP URL, Stream Name dan medan resolusi/bitrate."),
        ("Bitrate berapa untuk Flirt4Free?", "3,500–6,000 Kbps pada 1080p — tetapkan nilai sama dalam External Broadcast Form dan dalam SplitCam."),
        ("Adakah SplitCam percuma untuk Flirt4Free?", "Ya — percuma, tiada tera air dan tiada had masa, sesuai dengan platform bersejarah seperti Flirt4Free yang rancangannya boleh panjang.")]),
    _p("mfc-alerts", "MFC Alerts",
       "Tambah MFC Alerts ke siaran dengan SplitCam",
       "Paparkan amaran tip beranimasi dalam siaran MyFreeCams — URL mfcalerts.com sebagai lapisan Browser dalam SplitCam percuma, di atas kamera web.",
       "mfc alerts, myfreecams alerts, tambah mfc alerts, mfcalerts splitcam, myfreecams tip alerts, myfreecams alerts overlay",
       'Cara tambah <span class="accent">MFC Alerts</span> ke siaran anda',
       "Tambah MFC Alerts",
       "Paparkan amaran tip beranimasi dalam siaran MyFreeCams.",
       "MFC Alerts memaparkan kesan beranimasi dalam siaran MyFreeCams anda setiap kali penonton menghantar tip. Ia berjalan sebagai <strong style='color:var(--text)'>lapisan Browser</strong> dalam SplitCam percuma — tetapkan sekali dan tip mencetuskan reaksi pada skrin secara masa nyata.",
       "Tambah MFC Alerts dengan SplitCam: pasang SplitCam, tambah kamera web, buka tab Browser dan muat mfcalerts.com, salin URL amaran anda, tambah sebagai lapisan Browser di atas kamera web, kemudian uji dengan tip ujian."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera web.</li><li>Dapatkan URL di mfcalerts.com.</li><li>Tambah sebagai lapisan Browser di atas kamera web.</li><li>Hantar tip ujian.</li></ol>",
       "Dalam SplitCam buka tab <strong>Browser</strong> dan pergi ke <strong>www.mfcalerts.com</strong>. Log masuk atau daftar. Guna <strong>Copy to clipboard</strong> untuk menyalin URL amaran peribadi anda. Tampal URL ke tetingkap Browser SplitCam dan klik <strong>Add</strong>. Kemudian susun semula senarai sumber supaya <strong>MFC Alerts di atas kamera web</strong> (menu 3 titik → Move Up).",
       [("MFC Alerts mesti di atas kamera web", "Kesilapan paling biasa: jika lapisan MFC Alerts di bawah kamera web dalam senarai sumber, kesan kekal tersembunyi. Alihkan ia ke atas."),
        ("Akaun mfcalerts.com diperlukan", "URL amaran adalah peribadi — daftar di mfcalerts.com dahulu jika tiada akaun."),
        ("Hantar tip ujian sebelum live", "Guna Settings → Send test tip untuk memastikan tindihan berfungsi — jangan temui ralat di tengah rancangan."),
        _T_ETH],
       [("Apa itu MFC Alerts?", "Sistem pemberitahuan untuk MyFreeCams yang memaparkan kesan video dalam siaran anda apabila penonton menghantar tip — ditambah sebagai tindihan Browser dalam SplitCam."),
        ("Mengapa MFC Alerts saya tidak muncul?", "Hampir sentiasa susunan lapisan — lapisan Browser MFC Alerts mesti di atas kamera web dalam senarai sumber SplitCam."),
        ("Perlukah akaun untuk MFC Alerts?", "Ya — daftar di mfcalerts.com untuk mendapat URL amaran peribadi anda."),
        ("Adakah SplitCam percuma untuk ini?", "Ya — SplitCam percuma, tiada tera air dan tiada had masa, dan tindihan pelayar MFC Alerts berjalan dalamnya tanpa kos tambahan.")],
       steps=[
           ("Pasang SplitCam dan tambah kamera web", "Pasang SplitCam percuma untuk Windows atau macOS, kemudian tambah <strong>kamera web</strong> sebagai sumber. MFC Alerts terletak sebagai lapisan di atas kamera ini."),
           ("Buka tab Browser dan ke mfcalerts.com", "Dalam SplitCam buka tab <strong>Browser</strong> dan pergi ke <strong>www.mfcalerts.com</strong>. Log masuk, atau daftar jika belum ada akaun mfcalerts.com."),
           ("Salin URL amaran anda", "Di mfcalerts.com guna <strong>Copy to clipboard</strong> untuk menyalin URL amaran peribadi anda — itu halaman yang memaparkan animasi tip."),
           ("Tambah URL sebagai lapisan Browser — di atas kamera web", "Tampal URL ke tetingkap Browser SplitCam dan klik <strong>Add</strong>. Kemudian susun semula senarai sumber supaya <strong>MFC Alerts di atas kamera web</strong> (menu 3 titik → Move Up). Jika di bawah, kesan kekal tersembunyi."),
           ("Uji dengan tip ujian", "Buka <strong>Settings → Send test tip</strong> dan pastikan kesan amaran muncul di atas kamera. Kemudian siar seperti biasa di MyFreeCams — tip sebenar kini mencetuskan animasi."),
       ]),
    _p("lovense", "Lovense",
       "Tambah alat permainan Lovense ke siaran dengan SplitCam",
       "Sambung alat permainan Lovense interaktif ke siaran cam dengan SplitCam percuma — Lovense SplitCam Toolset, amaran tip pada skrin, reaksi.",
       "tambah lovense ke siaran, lovense cam stream, lovense splitcam, lovense splitcam toolset, lovense interactive toy streaming",
       'Cara tambah <span class="accent">alat permainan Lovense</span> ke siaran',
       "Tambah alat Lovense",
       "Sambung alat permainan Lovense interaktif ke siaran cam anda.",
       "Anda menjalankan siaran cam melalui SplitCam percuma dan memasangkan alat permainan <strong style='color:var(--text)'>Lovense</strong> yang bertindak balas kepada token. Lovense mendokumentasi <strong style='color:var(--text)'>Lovense SplitCam Toolset</strong> rasmi, dan SplitCam menawarkan plugin Lovense rasmi — penyepaduan disokong dari kedua-dua pihak.",
       "Untuk menambah alat Lovense ke siaran: pasang SplitCam dan perisian Lovense, pasangkan alat, sambung Lovense ke platform cam anda, tambah status Lovense sebagai lapisan Browser dalam SplitCam, kemudian siar seperti biasa."
       "<ol><li>Pasang SplitCam.</li><li>Pasang perisian Lovense dan pasangkan alat.</li><li>Sambung Lovense ke tapak cam anda.</li><li>Tambah tindihan Lovense dalam SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Pasang Lovense Connect / Lovense Stream (apl desktop rasmi). Hidupkan alat dan pasangkan melalui Bluetooth supaya apl menunjukkan tersambung. Dalam apl Lovense sambungkan akaun cam anda supaya alat bertindak balas kepada token / tip penonton. Lovense menyediakan URL tindihan / widget — tambah sebagai lapisan <strong>Browser</strong> dalam adegan SplitCam.",
       [("Guna Lovense SplitCam Toolset rasmi", "Lovense menerbitkan toolset khusus SplitCam dengan panduan pemasangan sendiri — menambah tindihan aktiviti alat dan amaran tip yang dibuat untuk SplitCam."),
        ("Kemas kini Lovense Cam Extension", "Toolset memerlukan Lovense Cam Extension terkini (30.1.4 atau lebih baru) — kemas kini sebelum live."),
        ("Pastikan alat dicas", "Bateri lemah di tengah rancangan merosakkan bahagian interaktif — cas penuh sebelum live."),
        ("Uji reaksi token", "Hantar tip ujian kecil untuk memastikan alat bertindak balas sebelum membuka bilik."),
        ("Semak keperluan versi", "Lovense SplitCam Toolset memerlukan SplitCam 10.4.5 atau lebih baru. Lovense Cam Extension secara rasmi merangkumi Chaturbate, Stripchat, BongaCams, MyFreeCams dan CamSoda — untuk tapak lain, guna penyepaduan Generic URL Lovense.")],
       [("Adakah Lovense menyokong SplitCam secara rasmi?", "Ya — Lovense mendokumentasi «Lovense SplitCam Toolset» rasmi dengan panduan pemasangan sendiri, dan SplitCam menawarkan plugin Lovense rasmi. Penyepaduan disokong dari kedua-dua pihak."),
        ("Adakah alat menyambung terus ke SplitCam?", "Tidak — alat dipasangkan dengan apl Lovense; SplitCam memaparkan tindihan Lovense dan menyiar kamera."),
        ("Tapak cam mana menyokong Lovense?", "Lovense Cam Extension secara rasmi menyokong Chaturbate, Stripchat, BongaCams, MyFreeCams dan CamSoda, dengan sokongan berbeza untuk lain — semak senarai terkini dalam apl Lovense."),
        ("Boleh saya paparkan tip terkini pada skrin?", "Ya — tambah URL widget Lovense sebagai lapisan Browser dalam SplitCam.")],
       steps=[
           ("Pasang SplitCam", "SplitCam ialah perisian penstriman langsung percuma untuk Windows dan macOS — pengekod yang menghantar video anda ke platform cam. Pasangnya; tiada tera air."),
           ("Pasang perisian Lovense dan pasangkan alat", "Pasang Lovense Connect / Lovense Stream (apl desktop rasmi). Hidupkan alat dan pasangkan melalui Bluetooth supaya apl menunjukkan tersambung."),
           ("Sambung Lovense ke platform cam", "Dalam apl Lovense sambungkan akaun cam anda supaya alat bertindak balas kepada token / tip penonton. Kebanyakan platform cam besar disokong."),
           ("Tambah tindihan Lovense dalam SplitCam", "Lovense menyediakan URL tindihan / widget. Tambah sebagai lapisan <strong>Browser</strong> dalam adegan SplitCam supaya penonton lihat status alat dan tip terkini pada skrin."),
           ("Bina adegan dan Go Live", "Tambah kamera dan tindihan lain, tampal kunci RTMP platform cam ke SplitCam dan klik <strong>Go Live</strong>. Alat bertindak balas kepada tip secara masa nyata."),
       ]),
    _p("multistream-cams", "Beberapa tapak cam",
       "Siar ke beberapa tapak cam serentak dengan SplitCam",
       "Siar ke MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat dan lain-lain serentak dengan multistream percuma SplitCam. Satu klik, tiada tera air.",
       "siar ke beberapa tapak cam, multistream cam sites, siar chaturbate dan bongacams serentak, perisian multistream cam",
       'Cara siar ke <span class="accent">beberapa tapak cam</span> serentak',
       "Multistream cam",
       "Siar ke beberapa tapak cam serentak.",
       "SplitCam percuma boleh menyiar satu pengekodan ke <strong style='color:var(--text)'>beberapa tapak cam serentak</strong> — MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat dan lain-lain. Tiada tera air, satu klik.",
       "Untuk siar ke beberapa tapak cam serentak: pasang SplitCam, bina adegan, dapatkan URL pelayan RTMP dan kunci strim setiap tapak cam, tambah semua ke tetapan multistream SplitCam, klik Go Live sekali."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + adegan.</li><li>Dapatkan kunci RTMP dari setiap tapak cam.</li><li>Tambah semua kunci ke multistream SplitCam.</li><li>Tekan Go Live sekali.</li></ol>",
       "Pada setiap platform cam hidupkan siaran luaran / RTMP dan salin <strong>URL pelayan</strong> dan <strong>kunci strim</strong>. Dalam SplitCam buka <strong>Stream Settings</strong> dan tambah setiap tapak cam sebagai destinasi RTMP tersuai — tampal URL pelayan dan kunci. Tanda semua yang anda mahu live. Tekan <strong>Go Live</strong>.",
       [("Perhati muat naik anda", "Multistream mendarabkan beban muat naik. Setiap destinasi guna bitrate sendiri — pastikan talian anda mampu menanggung jumlahnya."),
        ("Semak peraturan platform", "Sesetengah tapak cam melarang siaran serentak di tempat lain — semak sebelum multistream."),
        ("Kabel — di sini tak boleh putus", "Multistream mendarabkan beban muat naik, jadi satu putus wi-fi boleh menjatuhkan semua destinasi serentak. Kabel di sini bukan pilihan."),
        ("Pantau monitor kesihatan", "SplitCam memaparkan status setiap destinasi — lepaskan satu tapak jika muat naik tak mampu.")],
       [("Adakah multistream SplitCam percuma?", "Ya — multistream terbina dan percuma, tiada yuran per destinasi, tiada tera air."),
        ("Berapa tapak cam boleh saya siar serentak?", "Sebanyak yang lebar jalur muat naik anda mampu — setiap destinasi guna bitrate sendiri."),
        ("Adakah ia guna relay awan?", "Tidak — SplitCam menghantar strim peer-to-peer terus dari PC ke ingest setiap platform."),
        ("Adakah multistream melambatkan PC saya?", "Pengekodan dibuat sekali dan diguna semula; pengekodan perkakasan memastikan beban CPU rendah. Lebar jalur muat naik ialah had sebenar.")],
       steps=[
           ("Pasang SplitCam", "SplitCam ialah perisian penstriman langsung percuma untuk Windows dan macOS dengan multistream terbina. Pasangnya — tiada tera air, tiada pendaftaran."),
           ("Tetapkan kamera dan adegan", "Buka SplitCam, tambah kamera web dan bina adegan dengan tindihan dan penapis. Satu adegan menyuap setiap destinasi."),
           ("Dapatkan kunci RTMP dari setiap tapak cam", "Pada setiap platform cam hidupkan siaran luaran / RTMP dan salin <strong>URL pelayan</strong> dan <strong>kunci strim</strong>. Ulang untuk setiap tapak yang anda mahu siar — lihat panduan platform masing-masing untuk laluan tepat."),
           ("Tambah setiap destinasi dalam SplitCam", "Buka <strong>Stream Settings</strong> dan tambah setiap tapak cam sebagai destinasi RTMP tersuai — tampal URL pelayan dan kunci. Tanda semua yang anda mahu live."),
           ("Klik Go Live sekali", "Tekan <strong>Go Live</strong>. SplitCam menghantar strim ke setiap tapak cam terpilih serentak, peer-to-peer, dari satu pengekodan — tanpa kos tambahan."),
       ]),
    _p("livejasmin", "LiveJasmin",
       "Siar di LiveJasmin dengan SplitCam — Pengekod luaran HD",
       "Siar di LiveJasmin dengan SplitCam percuma — pengekod luaran Model Center, persediaan HD 1080p, adegan berbilang kamera dan tindihan. Tiada tera air, tiada pendaftaran.",
       "siaran livejasmin, livejasmin obs, livejasmin pengekod luaran, livejasmin rtmp, livejasmin stream key, persediaan model livejasmin",
       'Cara siar di <span class="accent">LiveJasmin</span> dengan SplitCam',
       "Siaran LiveJasmin",
       "Persediaan pengekod luaran untuk Model Center LiveJasmin yang HD-sahaja.",
       "LiveJasmin ialah utusan Docler Holding — salah satu rangkaian cam terbesar di dunia dan platform HD-sahaja. Penyiar pilihan ialah klien <strong>JasminCAM</strong> milik sendiri, tetapi Model Center juga mendedahkan laluan <strong>External Encoder</strong> standard — <strong style='color:var(--text)'>SplitCam</strong> percuma menyambung kepadanya, membolehkan anda menyiar dengan adegan berbilang kamera, penapis kecantikan dan tindihan dalam strim HD yang sama.",
       "Siar di LiveJasmin dengan SplitCam: pasang SplitCam, bina adegan HD, dalam Model Center pergi ke <em>Settings → Broadcast → External Encoder</em>, salin URL pelayan dan stream key, tampal dalam SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + adegan HD.</li><li>Dapatkan URL dan stream key dari Model Center.</li><li>Tampal dalam SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Log masuk ke <strong>modelcenter.livejasmin.com</strong>, buka <strong>Settings → Broadcast → External Encoder</strong>. Model Center mendedahkan <strong>URL pelayan</strong> dan <strong>stream key</strong> yang terikat pada akaun anda — salin kedua-duanya ke medan RTMP tersuai SplitCam. <strong>Nota:</strong> akaun baharu perlu diluluskan (48–72 jam) sebelum pilihan External Encoder muncul, dan platform menguatkuasakan output HD-sahaja.",
       [("HD atau kedudukan anda jatuh", "LiveJasmin HD-sahaja — apa-apa di bawah 1280×720 berisiko hanya ditunjukkan dalam senarai berbayar rendah, di bawah 1080p hilang kelayakan 'Premium'. Sasarkan 1920×1080 pada 30 fps, 4,000–6,000 Kbps."),
        ("JasminCAM lawan pengekod luaran", "Klien JasminCAM milik Docler memberi pematuhan HD paling bersih, tetapi pengekod luaran (OBS, SplitCam, vMix) disokong secara rasmi sebaik akaun anda diluluskan — ia membuka adegan berbilang kamera dan tindihan yang JasminCAM tak boleh buat."),
        ("Free chat ≠ private show", "Free chat ialah pratonton sahaja — tiada bogel. Private dan Gold show ialah tempat model menjana pendapatan. Rancang adegan anda supaya nampak kuat semasa berpakaian DAN dalam mod show."),
        _T_ETH],
       [("Adakah LiveJasmin secara rasmi menyokong pengekod luaran seperti SplitCam?", "Ya — Model Center memasukkan pilihan External Encoder dalam Settings → Broadcast. JasminCAM ialah klien yang disyorkan, tetapi OBS, SplitCam dan pengekod RTMP lain disenaraikan secara jelas sebagai disokong sebaik akaun model anda diluluskan."),
        ("Di mana saya dapatkan stream key LiveJasmin?", "Dalam Model Center: Settings → Broadcast → External Encoder. URL pelayan dan stream key unik muncul di sana — salin kedua-duanya ke medan RTMP tersuai SplitCam. Kunci itu terikat pada akaun anda; layan ia seperti kata laluan."),
        ("Bitrate berapa untuk LiveJasmin?", "LiveJasmin HD-sahaja — sasarkan 1920×1080 pada 30 fps, 4,000–6,000 Kbps dengan selang keyframe 2 saat. Sebarang yang jauh di bawah itu akan hilang label Premium dan turun ranking."),
        ("Adakah SplitCam percuma untuk LiveJasmin?", "Ya — SplitCam percuma, tiada tera air dan tiada had masa. Satu-satunya 'kos' ialah memenuhi syarat HD LiveJasmin, yang dikendalikan SplitCam secara native dengan komposisi adegan 1080p dan penapis kecantikan.")],
       steps=[
           ("Muat turun dan pasang SplitCam", "SplitCam ialah perisian penstriman langsung percuma untuk Windows dan macOS — tiada pendaftaran, tiada kad, tiada tera air. Ia ialah pengekod yang menghantar video HD anda ke LiveJasmin."),
           ("Bina adegan HD anda", "Buka SplitCam dan tambah kamera web dalam mod 1080p. Lapisi tindihan, teks, kamera kedua atau telefon, penapis kecantikan atau latar AI — LiveJasmin memerlukan kualiti HD dan adegan yang anda susun perlu kelihatan premium sepanjang free chat DAN private show."),
           ("Dapatkan URL dan stream key LiveJasmin", "Log masuk ke <strong>modelcenter.livejasmin.com</strong> (akaun anda perlu diluluskan dahulu — biasanya 48–72 jam selepas pendaftaran). Buka <strong>Settings → Broadcast → External Encoder</strong>. Halaman mendedahkan <strong>URL pelayan</strong> dan <strong>stream key</strong> unik. Salin kedua-duanya."),
           ("Sambungkan SplitCam ke LiveJasmin", "Dalam SplitCam buka <strong>Stream Settings</strong>, tampal URL pelayan LiveJasmin dan stream key ke medan RTMP tersuai. Tetapkan bitrate kepada 4,000–6,000 Kbps pada 1920×1080, 30 fps, dengan keyframe 2 saat. Jalankan ujian kelajuan terbina dahulu — strim HD menuntut bandwidth."),
           ("Klik Go Live", "Tekan <strong>Go Live</strong> dalam SplitCam, kemudian online dalam LiveJasmin Model Center. Dalam ~10 saat suapan HD anda sampai ke rangkaian LiveJasmin. Siaran seterusnya hanya satu klik — buka SplitCam, Go Live, kemudian online di LiveJasmin."),
       ]),
    _p("myfreecams", "MyFreeCams",
       "Cara siar di MyFreeCams (MFC) dengan SplitCam — pintasan Model Web Broadcaster",
       "Siar di MyFreeCams dengan SplitCam percuma — Model Admin external broadcaster, ekonomi token MFC, adegan berbilang kamera, tindihan. Tiada tera air, tiada pendaftaran.",
       "siaran myfreecams, mfc external broadcaster, myfreecams obs, mfc rtmp, mfc stream key, model admin, mfc token",
       'Cara siar di <span class="accent">MyFreeCams</span> dengan SplitCam',
       "Siaran MyFreeCams",
       "Persediaan external broadcaster untuk Model Admin MFC yang berasaskan token.",
       "MyFreeCams (MFC) ialah salah satu platform cam tertua — ekonomi token tulen, tanpa proses kelulusan model yang berat, dan asas ahli Premium yang setia. Model Web Broadcaster lalainya ialah alat pelayar satu-kamera, tetapi Model Admin juga mendedahkan pilihan <strong>External Broadcaster</strong> yang disambungkan oleh <strong style='color:var(--text)'>SplitCam</strong> percuma — membuka adegan berbilang kamera, tindihan, dan penapis dalam strim token yang sama.",
       "Siar di MFC dengan SplitCam: pasang SplitCam, bina adegan, Model Admin → Broadcaster, tukar dari Web Broadcaster ke External Broadcaster, salin URL pelayan dan key, tampal dalam SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Bina adegan.</li><li>Model Admin → Broadcaster, tukar ke External Broadcaster.</li><li>Salin URL + key, tampal dalam SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Log masuk ke MyFreeCams, buka <strong>Model Admin → Broadcaster</strong>, tukar dari <strong>Web Broadcaster</strong> ke <strong>External Broadcaster</strong>. Halaman mendedahkan <strong>URL pelayan</strong> (<strong>rtmp://publish.myfreecams.com…</strong>) dan <strong>stream key</strong> yang terikat pada akaun model — salin kedua-duanya ke medan RTMP tersuai SplitCam. Key terikat pada akaun.",
       [("MFC ialah ekonomi tip/token tulen", "MFC tidak berjalan atas langganan — ia tulen tip dan token. Rancang adegan anda untuk menyokong aliran tip: kaunter sasaran di skrin, menu tip, dan call-to-action yang jelas."),
        ("Web Broadcaster vs External — pilih sekali", "Di Model Admin → Broadcaster anda pilih Web Broadcaster (satu kamera, pelayar) atau External Broadcaster (RTMP). Tukar ke External sebelum go live — di sinilah SplitCam, OBS, dan vMix bersambung."),
        ("Tambah MFC Alerts sebagai lapisan Browser", "Tambah URL <strong>mfcalerts.com</strong> sebagai lapisan Browser dalam SplitCam di atas kamera — amaran tip, bar matlamat, dan notifikasi muncul masa nyata di atas siaran, mendorong ahli untuk menyumbang."),
        _T_ETH],
       [("Adakah MFC menyokong pengekod luaran seperti SplitCam?", "Ya — melalui External Broadcaster dalam Model Admin. Siaran RTMP standard berfungsi secara rasmi dengan OBS, SplitCam, dan vMix; cukup pilih External Broadcaster (bukan Web Broadcaster) di Model Admin → Broadcaster."),
        ("Di mana saya dapatkan stream key MFC?", "Dalam Model Admin → Broadcaster → External Broadcaster. Halaman mendedahkan URL pelayan yang menghala ke <strong>publish.myfreecams.com</strong> dan stream key yang terikat pada akaun model — tampal kedua-duanya ke medan RTMP tersuai SplitCam."),
        ("Bitrate berapa untuk MFC?", "MFC menyokong sehingga ~6,000 Kbps dengan keyframe push 2 saat. Sasarkan 1920×1080 pada 30 fps, 3,500–6,000 Kbps — kekalkan setinggi yang dibenarkan oleh sambungan anda; asas Premium peka pada kualiti HD."),
        ("Adakah SplitCam percuma untuk MFC?", "Ya — SplitCam percuma, tiada tera air, tiada had masa. Anda boleh menghantar berbilang kamera, penapis kecantikan, dan tindihan MFC Alerts ke MFC melalui laluan External Broadcaster.")],
       steps=[
           ("Pasang SplitCam", "SplitCam ialah perisian penstriman langsung percuma untuk Windows dan macOS — tiada pendaftaran, tiada kad, tiada tera air. Ia ialah pengekod yang menghantar siaran anda ke endpoint RTMP MFC."),
           ("Bina adegan anda", "Dalam SplitCam tambah kamera web, lapisi tindihan, penapis kecantikan, dan kamera kedua. Tambah <strong>mfcalerts.com</strong> sebagai lapisan Browser di atas kamera — amaran tip dan bar matlamat muncul masa nyata di atas strim anda."),
           ("Model Admin → Broadcaster → External Broadcaster", "Log masuk ke MyFreeCams, buka <strong>Model Admin → Broadcaster</strong> dan tukar dari <strong>Web Broadcaster</strong> ke <strong>External Broadcaster</strong>. Halaman mendedahkan URL pelayan yang menghala ke <strong>publish.myfreecams.com</strong> dan stream key unik akaun — salin kedua-duanya."),
           ("Sambungkan SplitCam ke MFC", "Dalam SplitCam buka <strong>Stream Settings</strong>, tampal URL pelayan dan stream key MFC ke medan RTMP tersuai. Tetapkan bitrate 3,500–6,000 Kbps pada 1920×1080, 30 fps, dengan keyframe 2 saat."),
           ("Klik Go Live", "Tekan <strong>Go Live</strong> dalam SplitCam — MFC menerima strim dalam beberapa saat dan bilik anda hidup dalam ekonomi token. Siaran seterusnya hanya satu klik."),
       ]),
    _p("cherry-tv", "Cherry.tv",
       "Cara siar di Cherry.tv dengan SplitCam — pengekod luaran mesra Web3",
       "Siar di Cherry.tv dengan SplitCam percuma — pengekod luaran Streamer Dashboard, platform cam mesra kripto, adegan berbilang kamera. Tiada tera air, tiada pendaftaran.",
       "siaran cherry tv, cherry.tv obs, cherry tv pengekod luaran, cherry.tv rtmp, cherry.tv stream key, cherry tv streamer, web3 cam",
       'Cara siar di <span class="accent">Cherry.tv</span> dengan SplitCam',
       "Siaran Cherry.tv",
       "Persediaan pengekod luaran untuk Streamer Dashboard Cherry.tv.",
       "Cherry.tv ialah platform cam yang lebih baharu dan berkembang pesat dengan sudut Web3 — bayaran mesra kripto dan halangan masuk yang lebih rendah berbanding rangkaian lama seperti LiveJasmin. Penyiar lalainya berasaskan pelayar, tetapi Streamer Dashboard mendedahkan laluan pengekod luaran standard yang disambungkan oleh <strong style='color:var(--text)'>SplitCam</strong> percuma.",
       "Siar di Cherry.tv dengan SplitCam: pasang SplitCam, bina adegan, Streamer Dashboard → Broadcast Settings → External Encoder, salin URL dan key, tampal dalam SplitCam, Go Live."
       "<ol><li>Pasang SplitCam.</li><li>Tambah kamera + adegan.</li><li>Dapatkan URL dan key dari Streamer Dashboard.</li><li>Tampal dalam SplitCam.</li><li>Tekan Go Live.</li></ol>",
       "Log masuk ke akaun streamer Cherry.tv, buka <strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong>. URL pelayan dan stream key terikat pada akaun. Akaun baharu perlu pengesahan asas (onboarding Cherry.tv lebih ringan daripada rangkaian lama).",
       [("Masuk ringan, trafik berkembang", "Tiada semakan 72-jam seperti Docler — onboarding cepat dan asas penonton berkembang. Tempat yang baik untuk early-mover yang mahu mengambil kedudukan sebelum platform jadi sesak."),
        ("Bayaran kripto + fiat", "Cherry.tv menyediakan bayaran kripto bersama fiat — tetapkan keutamaan bayaran dalam dashboard jika anda mahu pendapatan masuk ke wallet."),
        ("Penyiar pelayar vs luaran", "Penyiar pelayar pantas tetapi satu-kamera. Sambungkan SplitCam melalui External Encoder dan anda buka adegan berbilang kamera, tindihan, penapis kecantikan, dan latar AI — paparan lebih bersih, sesi lebih panjang."),
        _T_ETH],
       [("Adakah Cherry.tv menyokong pengekod luaran?", "Ya — Streamer Dashboard mempunyai laluan External Encoder RTMP standard. OBS, SplitCam, dan vMix bersambung ke laluan ini; cukup pilih External Encoder dalam Broadcast Settings."),
        ("Di mana saya dapatkan stream key Cherry.tv?", "Dalam Streamer Dashboard → Broadcast Settings → External Encoder. URL pelayan dan stream key unik akaun muncul di sana — salin kedua-duanya ke medan RTMP tersuai SplitCam."),
        ("Bitrate berapa untuk Cherry.tv?", "Sasarkan 1920×1080 pada 30 fps, 3,500–6,000 Kbps dengan selang keyframe 2 saat. Platform baharu, audiens muda — kualiti HD dijangkakan."),
        ("Adakah SplitCam percuma untuk Cherry.tv?", "Ya — SplitCam percuma, tiada tera air, tiada had masa. Anda boleh menghantar adegan berbilang kamera, tindihan, dan penapis kecantikan ke Cherry.tv tanpa kos tambahan.")],
       steps=[
           ("Pasang SplitCam", "SplitCam ialah perisian penstriman langsung percuma untuk Windows dan macOS — tiada pendaftaran, tiada kad, tiada tera air. Ia ialah pengekod yang menghantar siaran anda ke endpoint RTMP Cherry.tv."),
           ("Bina adegan anda", "Dalam SplitCam tambah kamera web, lapisi tindihan, penapis kecantikan, dan kamera kedua — audiens Cherry.tv lebih muda dan mahir platform; adegan anda perlu terasa moden dan pantas."),
           ("Streamer Dashboard → Broadcast Settings → External Encoder", "Log masuk ke Cherry.tv, buka <strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong>. Halaman mendedahkan URL pelayan dan stream key unik akaun — salin kedua-duanya."),
           ("Sambungkan SplitCam ke Cherry.tv", "Dalam SplitCam buka <strong>Stream Settings</strong>, tampal URL pelayan dan stream key Cherry.tv ke medan RTMP tersuai. Tetapkan bitrate 3,500–6,000 Kbps pada 1920×1080, 30 fps."),
           ("Klik Go Live", "Tekan <strong>Go Live</strong> dalam SplitCam, kemudian online dari Streamer Dashboard Cherry.tv. Dalam beberapa saat strim anda sampai ke Cherry.tv dan penonton mula masuk."),
       ]),
]
