# -*- coding: utf-8 -*-
"""Turkish (tr) content for cam-streaming-guides. Native Turkish for all 19 platforms."""

_T_ETH = ("Kablolu bağlantı kullan", "Uzun yayında Ethernet, Wi-Fi'ı yener — kaybolan bir kare "
          "kaybolan bir bahşiştir. Yayın bilgisayarına kablo çek.")
_T_TEST = ("Önce özel bir test yap", "Odayı izleyicilere açmadan önce kamerayı, sesi, kadrajı ve "
           "katmanları kontrol etmek için kısa bir test yayını yap.")

def _p(slug, name, title, desc, kw, h1html, h1short, card, intro, quick, key_how, tips, faq, steps=None):
    d = {"slug": slug, "name": name, "title": title, "desc": desc, "kw": kw,
         "h1html": h1html, "h1short": h1short, "card": card, "intro": intro,
         "quick": quick, "key_how": key_how, "tips": tips, "faq": faq}
    if steps: d["steps"] = steps
    return d

PLATFORMS_TR = [
    _p("chaturbate", "Chaturbate",
       "Chaturbate'te SplitCam ile yayın — Token & RTMP",
       "Ücretsiz SplitCam ile Chaturbate'te yayın yap — broadcast token, RTMP, çoklu kamera sahneleri ve katmanlar. Filigran yok, kayıt yok.",
       "chaturbate yayın, chaturbate broadcast token, chaturbate rtmp obs, chaturbate harici kodlayıcı, chaturbate canlı",
       'SplitCam ile <span class="accent">Chaturbate</span>\'te nasıl yayın yapılır',
       "Chaturbate yayını",
       "Chaturbate'te harici kodlayıcı ile token tabanlı kurulum.",
       "Chaturbate, token ekonomisi üzerine kurulu en büyük cam platformlarından biri. Tarayıcı yayıncısı düz, tek kameralı bir araç — ücretsiz <strong style='color:var(--text)'>SplitCam</strong> ile <strong style='color:var(--text)'>harici kodlayıcıya</strong> geçmek, aynı token tabanlı yayında çoklu kamera sahneleri, katmanlar ve filtreler açar.",
       "SplitCam ile Chaturbate'te yayın: SplitCam'i kur, sahneyi oluştur, Chaturbate'te <em>Broadcast Yourself → My Broadcast</em>'i aç, broadcast token'ı kopyala, SplitCam'e yapıştır, Go Live."
       "<ol><li>SplitCam'i kur.</li><li>Kamera + sahne ekle.</li><li>Chaturbate'ten broadcast token'ı kopyala.</li><li>SplitCam'e yapıştır.</li><li>Go Live'a bas.</li></ol>",
       "Chaturbate'te <strong>Broadcast Yourself</strong>'e tıklayıp <strong>My Broadcast</strong> sayfasını aç, sonra <strong>View RTMP/OBS broadcast information and stream key</strong>. Anahtar <strong>broadcast token</strong> olarak görünür — kopyala. Şifre gibi davran; asla paylaşma.",
       [("Token anahtardır", "Chaturbate, genel bir yayın anahtarı yerine broadcast token'ını kullanır. Şifre gibi davran ve sızarsa sıfırla."),
        ("Bol pay", "Chaturbate'in RTMP girişi 4K'ya, 60 fps'ye ve yüksek bitrate'e kadar kabul eder — sınır senin yüklemen, platform değil. Her 2 saniyede bir keyframe."),
        _T_ETH, _T_TEST],
       [("Chaturbate OBS / harici kodlayıcılara izin veriyor mu?", "Evet — Chaturbate harici kodlayıcıları resmi olarak destekler ve kendi «How do I set up OBS?» makalesi vardır. Yayın ayarlarında «Use External Encoder to Broadcast» ile etkinleştir."),
        ("Chaturbate yayın anahtarım nerede?", "Broadcast Yourself → My Broadcast → View RTMP/OBS broadcast information and stream key. Anahtar, broadcast token'ındır."),
        ("Chaturbate için hangi bitrate?", "1080p'de 3.500–6.000 Kbps fazlasıyla yeterli. Chaturbate'in tavanı yüksek — gerçek sınır yüklemen; önce SplitCam'in yerleşik hız testini çalıştır."),
        ("SplitCam Chaturbate için ücretsiz mi?", "Evet — tamamen ücretsiz, filigransız ve süre sınırı yok: kodlayıcı token kazancından yemez.")]),
    _p("cam4", "CAM4",
       "CAM4'te SplitCam ile yayın — External Encoder",
       "Ücretsiz SplitCam ile CAM4'te yayın yap — External Encoder, yayın anahtarı, coğrafi engelleme ve katmanlar. Filigran yok.",
       "cam4 yayın, cam4.com, cam4 external encoder, cam4 stream key, cam4 rtmp obs",
       'SplitCam ile <span class="accent">CAM4</span>\'te nasıl yayın yapılır',
       "CAM4 yayını",
       "CAM4'te coğrafi kontrollü External Encoder.",
       "CAM4, yerleşik coğrafi kontrollü küresel bir cam-and-earn platformudur — yayınını seçili ülkelerde gizleyebilirsin. Ücretsiz <strong style='color:var(--text)'>SplitCam</strong> ile harici kodlayıcı olarak yayın yapmak, temel yayıncının yapmadığı sahne geçişleri ve katmanlar açar.",
       "SplitCam ile CAM4'te yayın: SplitCam'i kur, sahneyi oluştur, CAM4'te <em>Broadcast &amp; Earn Money → Start Broadcast → External Encoder</em>'a git, Get Stream Key, SplitCam'e yapıştır, Go Live."
       "<ol><li>SplitCam'i kur.</li><li>Kamera + sahne ekle.</li><li>CAM4'ten yayın anahtarını al.</li><li>SplitCam'e yapıştır.</li><li>Go Live'a bas.</li></ol>",
       "CAM4'te <strong>Broadcast</strong> → <strong>Broadcast &amp; Earn Money</strong> → <strong>Start Broadcast</strong>, sonra üstte <strong>External Encoder</strong>'a tıkla. Doğum tarihi, cinsiyet ve ülkeyi doldur, <strong>Get Stream Key</strong> ile kopyala. SplitCam'in Stream Settings'indeki yeşil kaydırıcı bağlantıyı onaylar.",
       [("Coğrafi kısıtlamaları ayarla", "CAM4, yayını belirli ülke ve bölgelerde gizlemene izin verir — go-live'dan önce CAM4 tarafında ayarla."),
        ("Yeşil kaydırıcıyı izle", "CAM4 kurulumu, anahtar kabul edildiğinde SplitCam'in Stream Settings'inde yeşil bir kaydırıcı gösterir — kırmızı = anahtarı kontrol et."),
        ("Normalden düşük bitrate", "CAM4'ün girişi video bitrate'ini yaklaşık 3.000 Kbps ile sınırlar — çoğu cam sitesinden düşük. Daha yükseğe zorlama."),
        _T_ETH],
       [("CAM4 OBS / harici kodlayıcıları resmi destekliyor mu?", "Evet — CAM4'ün destek sitesinde resmi OBS Guide var ve en iyi deneyim için External Encoder önerir. SplitCam aynı RTMP yolunu kullanır."),
        ("CAM4 yayınımı coğrafi engelleyebilir miyim?", "Evet — CAM4'te yayını belirli ülkelerde gizleyen yerleşik coğrafi kısıtlama var. SplitCam'de değil, CAM4'te ayarla."),
        ("CAM4 yayın anahtarı nerede?", "Broadcast → Broadcast & Earn Money → Start Broadcast → External Encoder → Get Stream Key."),
        ("CAM4 için hangi bitrate?", "Ortalamadan düşük — CAM4 girişi 30 fps'de 1 saniyelik keyframe ile ~3.000 Kbps ile sınırlar. Resmi tablo ~3.000'i aşmamayı önerir.")]),
    _p("bongacams", "BongaCams",
       "BongaCams'te SplitCam ile yayın — External Encoder",
       "Ücretsiz SplitCam ile BongaCams'te yayın yap — External Encoder, çoklu kamera sahneleri, katmanlar ve AI arka plan. Filigran yok.",
       "bongacams, bongcams, bongacams yayın, bongacams external encoder, bongacams rtmp obs",
       'SplitCam ile <span class="accent">BongaCams</span>\'te nasıl yayın yapılır',
       "BongaCams yayını",
       "BongaCams için External Encoder kurulumu.",
       "BongaCams küresel bir cam platformudur. Harici kodlayıcı yayını her zaman etkin gelmez — etkinleştirildiğinde ücretsiz <strong style='color:var(--text)'>SplitCam</strong> yayını çoklu kamera sahneleri, katmanlar ve AI arka plan ile yönetir.",
       "SplitCam ile BongaCams'te yayın: SplitCam'i kur, sahneyi oluştur, BongaCams'te <em>Options → Broadcast settings → Select Encoder → External Encoder</em>'a git, URL ve anahtarı kopyala, SplitCam'e yapıştır, Go Live."
       "<ol><li>SplitCam'i kur.</li><li>Kamera + sahne ekle.</li><li>BongaCams'ten URL ve anahtarı al.</li><li>SplitCam'e yapıştır.</li><li>Go Live'a bas.</li></ol>",
       "BongaCams'te <strong>Options</strong> → <strong>Broadcast settings</strong> → <strong>Select Encoder</strong> → <strong>External Encoder</strong>'ı aç ve gösterilen sunucu URL'sini ve yayın anahtarını kopyala. <strong>External Encoder düğmesi yoksa</strong>, BongaCams desteğine yaz ve hesabında harici kodlamanın açılmasını iste.",
       [("External Encoder düğmesi yok mu? Destek", "BongaCams harici kodlamayı hesap bazında açar — seçenek Broadcast settings'te yoksa destek etkinleştirir."),
        ("Çözünürlüğü eşle", "BongaCams, web kamerasının ve yayının çözünürlüğünün eşleşmesini önerir — örneğin ikisi de 1280×720."),
        _T_ETH, _T_TEST],
       [("BongaCams'te External Encoder düğmesi neden çıkmıyor?", "Harici kodlama her hesapta varsayılan açık değildir — etkinleştirmek için BongaCams desteğine yaz, düğme Broadcast settings'te belirir."),
        ("BongaCams hesabımı doğrulamam gerekir mi?", "Evet — yayın 18+, yaş doğrulaması için resmi kimlik ve canlı öncesi hesap onayı gerektirir."),
        ("BongaCams için hangi bitrate?", "BongaCams'in RTMP girişi video bitrate'ini 2 saniyelik keyframe ile ~6.000 Kbps ile sınırlar — 1080p'de 3.500–6.000 ideal bölge; önce yüklemeyi test et."),
        ("SplitCam BongaCams için ücretsiz mi?", "Evet — tamamen ücretsiz, filigransız ve süre sınırı yok, böylece kodlayıcı BongaCams token kazancını azaltmaz.")]),
    _p("stripchat", "Stripchat",
       "Stripchat'te SplitCam ile yayın — Strip Cam kurulumu",
       "Strip cam platformu Stripchat'te ücretsiz SplitCam ile yayın yap. Harici yazılım, token anahtarı, sahneler ve katmanlar.",
       "strip cam, stripchat canlı yayın, stripchat yayın, stripchat external software, stripchat stream key, stripchat rtmp obs",
       'SplitCam ile <span class="accent">Stripchat</span>\'te nasıl yayın yapılır',
       "Stripchat yayını",
       "Stripchat yayınları için harici yazılım kurulumu.",
       "Stripchat, etkileşime odaklı büyük bir cam platformudur. <em>External software</em> modu sana token tabanlı bir anahtar verir — düz kamera yerine sahneler, katmanlar ve filtrelerle yayın yapmak için ücretsiz <strong style='color:var(--text)'>SplitCam</strong>'e koy.",
       "SplitCam ile Stripchat'te yayın: SplitCam'i kur, sahneyi oluştur, Stripchat'te <em>Switch to external software</em>'i seç, yayın anahtarını kopyala, SplitCam'e yapıştır, Go Live."
       "<ol><li>SplitCam'i kur.</li><li>Kamera + sahne ekle.</li><li>Stripchat'ten yayın anahtarını al.</li><li>SplitCam'e yapıştır.</li><li>Go Live'a bas.</li></ol>",
       "Stripchat'te <strong>Switch to external software</strong>'i seç, sonra <strong>Show external software settings for the stream</strong>. Yayın anahtarını kopyala — Stripchat onu token olarak gösterir. Gizli tut.",
       [("Çözünürlüğü siteyle eşle", "Stripchat'in SSS'i uyarır: yazılımındaki çözünürlük sitenin çözünürlüğüyle tam eşleşmeli, yoksa video pikselleşir. İkisini aynı ayarla."),
        ("2 Mbps alt sınırına dikkat", "Stripchat alt sınır olarak 2 Mbps yükleme belirtir — ve OBS yayını veya çoklu yayın için yeterli olmadığını açıkça söyler. Çok daha yükseği hedefle."),
        ("Anahtar bir token'dır", "Stripchat'in yayın anahtarı bir token'dır — tam kopyala, asla paylaşma, sızarsa sıfırla."),
        _T_ETH],
       [("Stripchat OBS / harici yazılım öneriyor mu?", "Evet — Stripchat'in resmi SSS'i «en iyi video ve ses kalitesini elde etmek için» OBS gibi harici yayın yazılımı önerir. SplitCam aynı şekilde çalışır."),
        ("Stripchat'i harici yazılıma nasıl geçiririm?", "Broadcast Center'da Switch to External Broadcast Software (OBS)'i seç, sonra yayın anahtarını (token) açığa çıkarmak için external software settings'i aç."),
        ("Stripchat için hangi bitrate?", "RTMP girişi 2 saniyelik keyframe ile ~6.000 Kbps'ye kadar kabul eder. 1080p'de 3.500–6.000 ideal — ama özellikle OBS yayını için 2 Mbps alt sınırının çok üstünde olmalı."),
        ("SplitCam Stripchat için ücretsiz mi?", "Evet — lisans ücreti yok, filigran yok, süre sınırı yok: uzun etkileşimli Stripchat şovları bile kodlayıcı tarafında hiçbir şeye mal olmaz.")]),
    _p("onlyfans", "OnlyFans",
       "OnlyFans'te SplitCam ile canlı yayın — Yetkilendirme veya anahtar",
       "Ücretsiz SplitCam ile OnlyFans'te canlı yayın yap — yetkilendirme veya OBS Key ile giriş, çoklu kamera sahneleri, katmanlar. Filigran yok.",
       "onlyfans canlı yayın, onlyfans live stream, onlyfans yetkilendirme splitcam, onlyfans obs key, onlyfans yayın yazılımı",
       'SplitCam ile <span class="accent">OnlyFans</span>\'te nasıl canlı yayın yapılır',
       "OnlyFans canlı",
       "Bir kez yetkilendir veya anahtarı yapıştır — OnlyFans'te canlı.",
       "OnlyFans canlı yayını abonelerin içindir. SplitCam <strong style='color:var(--text)'>iki şekilde</strong> bağlanır — OnlyFans hesabınla bir kez giriş yaparsın ve SplitCam yayın anahtarını otomatik alıp eşitler tutar, ya da OBS Key'i elle yapıştırırsın. İki durumda da çoklu kamera sahneleri, katmanlar ve filtrelerle yayın yaparsın.",
       "SplitCam ile OnlyFans canlı: SplitCam'i kur, sahneyi oluştur, Stream Settings &rarr; Add Channel &rarr; OnlyFans'i aç ve <em>Yetkilendirme</em>'yi seç — OnlyFans hesabıyla giriş yap, SplitCam anahtarı otomatik alır — ve Go Live'a bas. Hesap bağlıyken OnlyFans yayın parametrelerini OnlyFans sitesini açmadan SplitCam'de değiştirebilirsin.",
       "OnlyFans'te: <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; <strong>Other</strong> bölümü, <strong>OBS Key</strong>'i kopyala. Ya da hesap girişi için SplitCam'deki <strong>Yetkilendirme</strong> seçeneğini kullan — anahtar otomatik alınır ve eşitlenir.",
       [("Yetkilendirme vs Stream Key", "İki bağlanma yolu: <strong>Yetkilendirme</strong> (bir kez giriş, anahtar alınır ve eşitlenir — en kolay yol) ya da <strong>Stream Key</strong> (OnlyFans → Profile → Settings → Other'da OBS Key'i kopyala ve yapıştır)."),
        ("SplitCam'den çıkmadan ayarları değiştir", "Yetkilendirmeyle hesap bağlı kalır, böylece OnlyFans canlı parametrelerini yayın sırasında veya sonrasında SplitCam'den ayarlarsın — OnlyFans sitesinden geçmeden."),
        ("Mütevazı bitrate", "OnlyFans'in RTMP girişi video bitrate'ini ~2.500 Kbps ile sınırlar — çoğu cam sitesinden dar. 720p–1080p, ~2.000–2.500 hedefle."),
        _T_ETH],
       [("OnlyFans'i SplitCam'e nasıl bağlarım?", "İki şekilde. <strong>Yetkilendirme</strong> — Stream Settings → Add Channel → OnlyFans → OnlyFans hesabıyla giriş yap, SplitCam anahtarı otomatik alır. Ya da <strong>Stream Key</strong> — OnlyFans → Profile → Settings → Other'da OBS Key'i kopyala ve yapıştır."),
        ("OnlyFans canlı ayarlarını siteyi açmadan değiştirebilir miyim?", "Evet — Yetkilendirme yöntemiyle SplitCam OnlyFans hesabına bağlı kalır, böylece anahtar ve ayarlar otomatik eşitlenir. Her şeyi yayın sırasında veya sonrasında SplitCam'den, onlyfans.com'a girmeden değiştirirsin."),
        ("OnlyFans için hangi bitrate?", "Mütevazı — OnlyFans'in RTMP girişi bitrate'i ~2.500 Kbps ile sınırlar, diğer cam platformlarından çok dar. 720p–1080p, ~2.000–2.500 Kbps hedefle."),
        ("SplitCam OnlyFans canlı için ücretsiz mi?", "Evet — ücretsiz, filigransız ve süre sınırı yok. Kodlayıcı tarafında hiçbir maliyet yok.")],
       steps=[
           ("SplitCam'i indir ve kur", "SplitCam, Windows ve macOS için ücretsiz bir yayın yazılımıdır — kayıt yok, kart yok, filigran yok. Videonu OnlyFans'e gönderen kodlayıcıdır."),
           ("Kamera ve sahneyi ayarla", "SplitCam'i aç ve web kameranı ekle. İzleyicilerin göreceği sahneyi oluştur — katmanlar, metin, ikinci kamera, güzellik filtreleri veya AI arka plan, hepsi canlı uygulanır."),
           ("Bağlantı — Yöntem 1: Yetkilendirme (önerilir)", "SplitCam'de <strong>Stream Settings</strong> &rarr; <strong>Add Channel</strong> &rarr; <strong>OnlyFans</strong>'i aç ve <strong>Yetkilendirme</strong>'yi seç. OnlyFans e-posta ve şifrenle giriş yap. SplitCam hesabını bağlar, yayın anahtarını otomatik alır ve eşitler tutar — ve OnlyFans canlı parametrelerini SplitCam içinde yönetmeni sağlar, yayın sırasında veya sonrasında OnlyFans sitesini açmadan değiştirirsin."),
           ("Bağlantı — Yöntem 2: Stream Key (elle)", "Giriş yapmamayı mı tercih edersin? Anahtarı kullan. OnlyFans'te <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; <strong>Other</strong> bölümüne git ve <strong>OBS Key</strong>'i kopyala. SplitCam'de Add Channel &rarr; OnlyFans, anahtar alanına yapıştır. Bu anahtar statiktir — sonra ayar değiştirmek için OnlyFans sitesine dönersin."),
           ("Go Live", "Hangi yöntem olursa olsun, SplitCam'de <strong>Go Live</strong>'a bas. Yöntem 1 ile OnlyFans parametrelerini SplitCam'den gerçek zamanlı ayarlamaya devam edebilirsin; Yöntem 2 ile anahtar tam ayarladığın gibi kalır."),
       ]),
    _p("camplace", "CamPlace",
       "CamPlace'te SplitCam ile yayın — Ücretsiz rehber",
       "Ücretsiz SplitCam ile CamPlace'te yayın yap — harici kodlayıcı, RTMP anahtarı, sahneler ve katmanlar. Adım adım, filigran yok.",
       "camplace yayın, camplace broadcasting software, camplace rtmp, camplace harici kodlayıcı, camplace stream key",
       'SplitCam ile <span class="accent">CamPlace</span>\'te nasıl yayın yapılır',
       "CamPlace yayını",
       "CamPlace yayınları için harici kodlayıcı kurulumu.",
       "CamPlace bir cam-streaming platformudur. Herkese açık OBS makalesi yok, bu yüzden <strong style='color:var(--text)'>yukarıdaki video rehber</strong> referansın — ücretsiz <strong style='color:var(--text)'>SplitCam</strong> standart RTMP ile bağlanır ve temel kameranın yapmadığı sahneler, katmanlar ve AI arka plan ekler.",
       "SplitCam ile CamPlace'te yayın: SplitCam'i kur, sahneyi oluştur, CamPlace'te harici/RTMP yayını etkinleştir, sunucu URL'si ve yayın anahtarını kopyala, SplitCam'e yapıştır, Go Live. Güncel yol için videoyu izle."
       "<ol><li>SplitCam'i kur.</li><li>Kamera + sahne ekle.</li><li>CamPlace'ten RTMP anahtarını al.</li><li>SplitCam'e yapıştır.</li><li>Go Live'a bas.</li></ol>",
       "CamPlace'e giriş yap ve yayın ayarlarını aç. <strong>Sunucu URL'sini</strong> ve <strong>yayın anahtarını</strong> açığa çıkarmak için harici kodlayıcı / RTMP / OBS seçeneğine geç, ikisini de kopyala. CamPlace resmi OBS belgesi yayınlamaz — <strong>yukarıdaki video</strong> güncel arayüzdeki en güvenilir adım adım yoldur.",
       [("Resmi OBS rehberi yok — videoyu kullan", "CamPlace'in harici kodlayıcılar hakkında herkese açık makalesi yok; yukarıdaki video güncel yolun referansıdır."),
        ("Standart RTMP çalışır", "Belgelenmemiş olsa da CamPlace standart RTMP sunucu URL'si ve anahtar kabul eder — SplitCam özel RTMP hedefi olarak bağlanır."),
        ("Katmanları SplitCam'de yığ", "Bahşiş hedefleri, isim ve sosyal medya sahne katmanları olarak — CamPlace'in temel kamerası bunları eklemez."),
        _T_ETH],
       [("CamPlace'in resmi OBS rehberi var mı?", "Harici kodlayıcılar hakkında herkese açık makale bulunamadı. CamPlace standart RTMP URL ve anahtar kabul eder, böylece SplitCam çalışır — videoyu izle."),
        ("CamPlace harici kodlayıcıları destekliyor mu?", "Evet — standart bir RTMP yayın anahtarı kabul eder, böylece SplitCam özel RTMP hedefi olarak bağlanır."),
        ("CamPlace için hangi bitrate?", "CamPlace resmi bir sayı yayınlamaz — güvenli aralık olarak 1080p'de 3.500–6.000 Kbps kullan ve gerçek tavanını SplitCam'in hız testi belirlesin."),
        ("SplitCam CamPlace için ücretsiz mi?", "Evet — ücretsiz, filigransız ve süre sınırı yok. CamPlace kendi kodlayıcısıyla gelmediğinden ücretsiz bir RTMP aracı işi görür.")]),
    _p("camsoda", "CamSoda",
       "CamSoda canlı — SplitCam ile ücretsiz kurulum",
       "Ücretsiz SplitCam ile CamSoda canlı — Use OBS Broadcaster, bölgesel sunucular, sahneler ve katmanlar. Filigran yok.",
       "camsoda canlı, camsoda yayın, camsoda obs broadcaster, camsoda rtmp obs, camsoda live broadcast",
       'SplitCam ile <span class="accent">CamSoda</span>\'da nasıl yayın yapılır',
       "CamSoda yayını",
       "CamSoda'da Use OBS Broadcaster kurulumu.",
       "CamSoda, etkileşimli ve sıra dışı şov formatlarıyla bilinen ABD'li bir cam platformudur. OBS yayınını resmi destekler — Go Live sayfasında <strong style='color:var(--text)'>Use OBS Broadcaster</strong> düğmesi ve CamSoda wiki'sinde resmi OBS rehberi var. Ücretsiz <strong style='color:var(--text)'>SplitCam</strong> aynı şekilde çalışır.",
       "SplitCam ile CamSoda'da yayın: SplitCam'i kur, sahneyi oluştur, CamSoda Go Live sayfasında Use OBS Broadcaster'a tıkla, sunucu URL'si ve yayın anahtarını kopyala, SplitCam'e yapıştır, Go Live."
       "<ol><li>SplitCam'i kur.</li><li>Kamera + sahne ekle.</li><li>CamSoda'da Use OBS Broadcaster'a tıkla.</li><li>Sunucu URL'si + anahtarı SplitCam'e yapıştır.</li><li>Go Live'a bas.</li></ol>",
       "CamSoda'nın <strong>Go Live</strong> sayfasında <strong>Use OBS Broadcaster</strong>'a tıkla. CamSoda RTMP sunucu URL'sini ve yayın anahtarını gösterir — ikisini de kopyala. Sana en yakın bölgesel sunucuyu (Kuzey Amerika, Avrupa, Asya vb.) seç. Ayrıntı için CamSoda wiki'sinde tam OBS rehberi var.",
       [("Bahşiş için doğrula", "CamSoda'da herkes yayın yapabilir ama bahşiş almak için CamSoda doğrulama sürecini tamamlamalısın."),
        ("En yakın bölgesel sunucuyu seç", "CamSoda bölgesel giriş sunucuları sunar — en yakını (NA / Avrupa / Asya / Güney Amerika / Okyanusya) gecikmeyi ve kare kaybını azaltır."),
        ("1080p / 30 fps tavanı", "CamSoda'nın girişi ~1080p, 30 fps ve ~6.000 Kbps'ye kadar gider — daha yükseğe zorlama."),
        _T_ETH],
       [("CamSoda OBS / harici kodlayıcıları destekliyor mu?", "Evet — resmi olarak. Go Live sayfasında Use OBS Broadcaster düğmesi ve CamSoda wiki'sinde OBS rehberi var, böylece SplitCam çalışır."),
        ("CamSoda'da kendimi doğrulamam gerekir mi?", "Yayın için hayır. Bahşiş almak için evet — CamSoda önce doğrulama sürecini gerektirir."),
        ("CamSoda hangi çözünürlüğü destekler?", "30 fps'de 1920×1080'e kadar, RTMP girişinde maksimum ~6.000 Kbps."),
        ("SplitCam CamSoda için ücretsiz mi?", "Evet — ücretsiz, filigransız ve süre sınırı yok. CamSoda'nın ücretsiz Use OBS Broadcaster moduyla çalışır, böylece tüm zincir hiçbir şeye mal olmaz.")]),
    _p("streamate", "Streamate",
       "Streamate'te SplitCam ile yayın — Entegre kanal",
       "Ücretsiz SplitCam ile Streamate'te yayın yap — entegre kanal, SM Connect anahtarı, sahneler ve katmanlar. Filigran yok.",
       "streamate, streamate sm connect, streamate yayın, streamate broadcasting software, streamate rtmp",
       'SplitCam ile <span class="accent">Streamate</span>\'te nasıl yayın yapılır',
       "Streamate yayını",
       "Streamate, SplitCam'de entegre bir kanaldır — hızlı kurulum.",
       "Streamate köklü bir cam platformudur — ve SplitCam'in kanal listesindeki <strong style='color:var(--text)'>önceden yapılandırılmış hedeflerden biridir</strong>, böylece kurulum elle RTMP girişinden hızlıdır: Streamate'i seç, anahtarı yapıştır, bitti.",
       "SplitCam ile Streamate'te yayın: SplitCam'i kur, sahneyi oluştur, Streamate'te <em>SM Connect → Start Show</em> kullan ve anahtarı kopyala, sonra SplitCam'de <em>Stream Settings → Add Channel → Streamate</em>'i aç ve yapıştır."
       "<ol><li>SplitCam'i kur.</li><li>Kamera + sahne ekle.</li><li>SM Connect ile Streamate anahtarını al.</li><li>SplitCam'de Add Channel → Streamate.</li><li>Go Live'a bas.</li></ol>",
       "Streamate'te <strong>SM Connect</strong>'i aç, koşulları kabul et, solda <strong>Start Show</strong>'a tıkla ve açılan pencereyi kapat — sonra yayın anahtarını kopyala. SplitCam'de <strong>Stream Settings</strong> → <strong>Add Channel</strong>'ı aç, listeden <strong>Streamate</strong>'i seç ve anahtarı yapıştır. Yeşil bir kaydırıcı bağlantıyı onaylar.",
       [("Streamate entegredir", "Elle RTMP URL'si yok — SplitCam'in Add Channel listesinde Streamate var; sadece seç ve anahtarı yapıştır."),
        ("SM Connect penceresini kapat", "Start Show'dan sonra Streamate bir pencere açar — kapat; sadece yayın anahtarını göstermek içindi."),
        ("Çözünürlüğü 1080p'ye sabitle", "SM Connect'teki Video Resolution alanı sessizce 1440'a atlayabilir; bu pratikte iletilmez ve kaliteni sessizce düşürür — elle 1080p ayarla. Durağan görüntüde düşen bitrate normaldir: Streamate akışı uyarlanabilir."),
        _T_ETH, _T_TEST],
       [("Streamate SplitCam'de entegre mi?", "Evet — Streamate SplitCam'in Add Channel listesinde görünür; elle RTMP URL'si yazmak yerine seçersin."),
        ("Streamate yayın anahtarı nerede?", "SM Connect → koşulları kabul et → Start Show → pencereyi kapat → anahtarı kopyala."),
        ("Streamate için hangi bitrate?", "Streamate kesin tavan koymaz — 1080p'de 3.500–6.000 Kbps iyi çalışır. Akış uyarlanabilir, böylece durağan görüntüde düşük bitrate normaldir, hata değil."),
        ("SplitCam Streamate için ücretsiz mi?", "Evet — ücretsiz, filigransız ve süre sınırı yok; ve Streamate SplitCam'de entegre kanal olduğundan ayrı kodlayıcı maliyeti de yok.")]),
    _p("streamray", "StreamRay",
       "StreamRay cam'de SplitCam ile yayın — Chat URL'si",
       "Ücretsiz SplitCam ile StreamRay cam'de yayın yap — sohbete gönderilen URL, OBS Broadcaster modu, sahneler ve katmanlar. Filigran yok.",
       "streamray, streamray cam, streamray yayın, streamray obs broadcaster, streamray rtmp",
       'SplitCam ile <span class="accent">StreamRay</span>\'de nasıl yayın yapılır',
       "StreamRay yayını",
       "StreamRay için chat-içi-URL harici kodlayıcı kurulumu.",
       "StreamRay sıra dışı bir harici kodlayıcı kurulumuna sahip — yayın URL'sini <strong style='color:var(--text)'>yayının sohbet penceresinde</strong> iletir ve ayrı yayın anahtarı kullanmaz. Ücretsiz <strong style='color:var(--text)'>SplitCam</strong> bu yalnızca-URL akışını yönetir.",
       "SplitCam ile StreamRay'de yayın: SplitCam'i kur, sahneyi oluştur, StreamRay'de OBS Broadcaster'ı etkinleştir, yayın URL'sini sohbet penceresinden kopyala, SplitCam'e yapıştır (anahtar alanını boş bırak), Go Live."
       "<ol><li>SplitCam'i kur.</li><li>Kamera + sahne ekle.</li><li>StreamRay URL'sini sohbetten kopyala.</li><li>URL'yi SplitCam'e yapıştır.</li><li>Go Live'a bas.</li></ol>",
       "StreamRay'de <strong>Broadcast Now</strong>'a çift tıkla, <strong>Other</strong> menüsünü aç, <strong>OBS Broadcaster</strong> ve <strong>Save and Close</strong>'u seç. StreamRay sonra <strong>yayın URL'sini sohbet penceresine</strong> gönderir — oradan kopyala. SplitCam'in yayın anahtarı alanını <strong>boş</strong> bırak; StreamRay yalnızca URL ile doğrular.",
       [("URL sohbette", "StreamRay yayın URL'sini bir ayar kutusunda göstermez — yayının sohbet penceresine gönderir. Oradan kopyala."),
        ("Anahtar alanını boş bırak", "StreamRay ayrı anahtar kullanmaz — sadece URL. SplitCam'in anahtar alanına hiçbir şey koyma."),
        _T_ETH, _T_TEST],
       [("StreamRay yayın URL'si nerede?", "OBS Broadcaster'ı etkinleştirdikten sonra StreamRay URL'yi sohbet penceresine gönderir — sohbetten kopyala."),
        ("StreamRay'de neden yayın anahtarı yok?", "StreamRay yalnızca URL ile doğrular — SplitCam'in anahtar alanını boş bırak."),
        ("StreamRay için hangi bitrate?", "StreamRay resmi tavan belirtmez — 1080p'de 3.500–6.000 Kbps hedefle ve SplitCam'in hız testini çalıştır, çünkü yalnızca-URL akışı bitrate geri bildirimi vermez."),
        ("SplitCam StreamRay için ücretsiz mi?", "Evet — ücretsiz, filigransız ve süre sınırı yok, bu da StreamRay'in yalnızca-URL akışına uyar: bir bağlantı yapıştır ve canlısın.")]),
    _p("xlovecam", "XLoveCam",
       "XLoveCam'de SplitCam ile yayın — RTMP bağlantısı & anahtar",
       "Ücretsiz SplitCam ile XLoveCam'de yayın yap — RTMP bağlantısı ve anahtar, bölgesel sunucular, sahneler ve katmanlar. Filigran yok.",
       "xlovecam, x love cam, xlovecam yayın, xlovecam rtmp link, xlovecam stream key",
       'SplitCam ile <span class="accent">XLoveCam</span>\'de nasıl yayın yapılır',
       "XLoveCam yayını",
       "XLoveCam için RTMP bağlantısı + anahtar kurulumu.",
       "XLoveCam, Avrupalı çok dilli bir cam platformudur. Hesap ayarları hem <strong style='color:var(--text)'>RTMP bağlantısını</strong> hem de <strong style='color:var(--text)'>yayın anahtarını</strong> gösterir — ücretsiz <strong style='color:var(--text)'>SplitCam</strong> ikisini de alır ve tam sahneler ile katmanlarla yayın yapar.",
       "SplitCam ile XLoveCam'de yayın: SplitCam'i kur, sahneyi oluştur, XLoveCam'de <em>My Account → settings</em>'i aç, RTMP bağlantısı ve yayın anahtarını kopyala, ikisini de SplitCam'e yapıştır, şovu başlat."
       "<ol><li>SplitCam'i kur.</li><li>Kamera + sahne ekle.</li><li>XLoveCam'den RTMP bağlantısı + anahtarı kopyala.</li><li>İkisini de SplitCam'e yapıştır.</li><li>Go Live'a bas.</li></ol>",
       "XLoveCam'de <strong>My Account</strong> → <strong>settings</strong>'i aç. Ayarlar hem <strong>RTMP bağlantısını</strong> hem de <strong>yayın anahtarını</strong> gösterir — ikisini de SplitCam'in sunucu URL'si ve anahtar alanlarına kopyala, sonra XLoveCam'de <strong>Start your show</strong>.",
       [("Bağlantıyı VE anahtarı kopyala", "XLoveCam bir RTMP bağlantısı VE ayrı yayın anahtarı verir — SplitCam'de ikisi de gerekir, tek başına değil."),
        ("Çok dilli kitle", "XLoveCam Avrupalı ve çok dillidir — kendi dilinde net bir metin katmanı izleyicilerin seni bulmasına yardım eder."),
        ("En yakın sunucuyu seç", "XLoveCam bölgesel RTMP sunucuları sunar — Avrupa, Kuzey Amerika, Güney Amerika ve Asya. En yakını gecikmeyi ve kare kaybını azaltır."),
        _T_ETH],
       [("XLoveCam RTMP verileri nerede?", "My Account → settings — hem RTMP bağlantısını hem anahtarı gösterir."),
        ("XLoveCam harici kodlayıcıları destekliyor mu?", "Evet — RTMP bağlantısı ve anahtar sağlar, böylece SplitCam kodlayıcı olarak çalışır."),
        ("XLoveCam için hangi bitrate?", "XLoveCam sabit sınır yayınlamaz; 1080p'de 3.500–6.000 Kbps ideal. En yakın bölgesel sunucuyu seçmek de bir o kadar önemli — kare kaybını azaltır."),
        ("SplitCam XLoveCam için ücretsiz mi?", "Evet — ücretsiz, filigransız ve süre sınırı yok. XLoveCam'in çok dilli Avrupa kitlesine ulaşmak yazılım maliyeti gerektirmez.")]),
    _p("soulcams", "SoulCams",
       "SoulCams'te SplitCam ile yayın — OBS ayarları",
       "Ücretsiz SplitCam ile SoulCams'te yayın yap — OBS ayarları, RTMP sunucusu ve anahtar, çoklu kamera sahneleri ve katmanlar.",
       "soul cams, soulcams, soulcams yayın, soulcams obs, soulcams rtmp, soulcams broadcast",
       'SplitCam ile <span class="accent">SoulCams</span>\'te nasıl yayın yapılır',
       "SoulCams yayını",
       "SoulCams için OBS ayarları kurulumu.",
       "SoulCams, OBS ayarları <strong style='color:var(--text)'>RTMP sunucusunu ve yayın anahtarını birlikte</strong> tek pencerede gösteren bir cam platformudur. İkisini de ücretsiz <strong style='color:var(--text)'>SplitCam</strong>'e yapıştırıp çoklu kamera sahneleri ve katmanlarla yayın yap.",
       "SplitCam ile SoulCams'te yayın: SplitCam'i kur, sahneyi oluştur, SoulCams'te Go Online → Settings → OBS'e tıkla, sunucu ve anahtarı kopyala, ikisini de SplitCam'e yapıştır, Go Live."
       "<ol><li>SplitCam'i kur.</li><li>Kamera + sahne ekle.</li><li>SoulCams Settings → OBS'i aç.</li><li>Sunucu + anahtarı SplitCam'e yapıştır.</li><li>Go Live'a bas.</li></ol>",
       "SoulCams'te giriş yap ve <strong>Go Online</strong>'a tıkla, sonra <strong>Settings</strong> → <strong>OBS</strong>'i aç. OBS penceresi <strong>RTMP sunucusunu</strong> ve <strong>yayın anahtarını</strong> birlikte gösterir — ikisini de SplitCam'e kopyala.",
       [("Sunucu ve anahtar yan yana", "SoulCams RTMP sunucusunu ve anahtarı aynı OBS penceresinde gösterir — ikisini tek hamlede alırsın."),
        ("Önce Go Online", "OBS ayarları yalnızca SoulCams'te Go Online'a tıkladıktan sonra görünür — kodlayıcı verilerini aramadan önce bunu yap."),
        ("İstenmeyen bölgeleri engelle", "SoulCams model tarafından coğrafi engellemeye izin verir — Go Online'a basmadan önce hangi ülkelerin yayını göremeyeceğini seç."),
        _T_ETH, _T_TEST],
       [("SoulCams OBS ayarları nerede?", "Giriş yap, Go Online'a tıkla, sonra Settings → OBS — RTMP sunucusu ve yayın anahtarı birlikte gösterilir."),
        ("SoulCams harici kodlayıcıları destekliyor mu?", "Evet — OBS ayarları RTMP sunucusu ve anahtar verir, böylece SplitCam çalışır."),
        ("SoulCams için hangi bitrate?", "SoulCams resmi sayı vermez — 1080p'de 3.500–6.000 Kbps hedefle ve yüklemeyi test et, çünkü OBS penceresi bitrate rehberi göstermez."),
        ("SplitCam SoulCams için ücretsiz mi?", "Evet — ücretsiz, filigransız ve süre sınırı yok, böylece çoklu kamera sahneleri ve katmanlarla tam bir SoulCams şovu kodlayıcı tarafında hiçbir şeye mal olmaz.")]),
    _p("imlive", "ImLive",
       "ImLive'de SplitCam ile yayın — Sanal kamera",
       "Ücretsiz SplitCam ile Im Live stream kurulumu — ImLive web kamerasını doğrudan kullanır (RTMP yok), SplitCam'i sahnelerle sanal kamera olarak bağla.",
       "im live stream, imlive splitcam, imlive yayın, imlive sanal kamera, imlive webcam, im live cam",
       'SplitCam ile <span class="accent">ImLive</span> nasıl kullanılır',
       "ImLive'de SplitCam",
       "ImLive için sanal kamera kurulumu — RTMP yok.",
       "ImLive web kamerasını tarayıcıda doğrudan kullanır — <strong style='color:var(--text)'>ne RTMP ne de yayın anahtarı vardır</strong>. Ücretsiz <strong style='color:var(--text)'>SplitCam</strong> <strong style='color:var(--text)'>sanal kamera</strong> olarak bağlanır: sahneyi SplitCam'de oluştur, sonra ImLive'de SplitCam'i kamera olarak seç.",
       "ImLive ile SplitCam kullanımı: SplitCam'i kur, medya katmanlarıyla sahneyi oluştur, ImLive'i aç ve görüntülü sohbet başlat, ImLive ayarlarında SplitCam'i web kamerası ve mikrofon olarak seç."
       "<ol><li>SplitCam'i kur.</li><li>SplitCam'de sahneyi oluştur.</li><li>ImLive'de görüntülü sohbet başlat.</li><li>ImLive kamerası olarak SplitCam'i seç.</li><li>Sohbeti başlat.</li></ol>",
       "ImLive sitesine giriş yap ve <strong>Start Video Chat</strong>'e tıkla, sonra kamera ve mikrofon seçeneklerine ulaşmak için <strong>Go To Settings</strong>'i aç. ImLive ayarlarında <strong>SplitCam</strong>'i web kamerası ve mikrofon olarak seç.",
       [("Yayın anahtarı gerekmez", "ImLive'de RTMP yok — sunucu URL'si veya anahtar arama. SplitCam yalnızca kamera aygıtı olarak seçilir."),
        ("SplitCam'i mikrofon olarak da ayarla", "Kameranın yanında mikrofon için de SplitCam'i seç, böylece ses miksin ve gürültü engelleme de canlıya geçer."),
        ("Sahneyi canlıdan önce oluştur", "ImLive SplitCam'in gönderdiğini gösterir — sohbeti başlatmadan önce katmanları düzenle."),
        _T_TEST],
       [("ImLive RTMP mi yoksa yayın anahtarı mı kullanır?", "Hiçbiri — ImLive web kamerasını tarayıcı üzerinden doğrudan kullanır. SplitCam sanal kamera olarak bağlanır, kopyalanacak anahtar yok."),
        ("ImLive'de SplitCam'i nasıl seçerim?", "Start Video Chat → Go To Settings → SplitCam'i web kamerası ve mikrofon olarak seç."),
        ("ImLive'de katman kullanabilir miyim?", "Evet — SplitCam sahnesinde oluştur; ImLive birleştirilmiş sonucu gösterir."),
        ("SplitCam ImLive için ücretsiz mi?", "Evet — ücretsiz, filigransız ve süre sınırı yok. ImLive için sanal kamera olarak görüntülü sohbetine maliyet veya markalama eklemez.")],
       steps=[
           ("SplitCam'i kur", "SplitCam, Windows ve macOS için ücretsiz bir yazılımdır. Kur — filigran yok, kayıt yok. ImLive için RTMP kodlayıcısı değil, <strong>sanal kamera</strong> olarak çalışır."),
           ("SplitCam'de sahneyi oluştur", "SplitCam'i aç ve web kameranı artı katmanlar, metin, filtreler veya AI arka planı eklemek için <strong>Media Layers +</strong>'yı kullan. Bu birleştirilmiş sahne, ImLive'in kameran olarak göreceği şeydir."),
           ("ImLive'de görüntülü sohbet başlat", "ImLive sitesine giriş yap ve <strong>Start Video Chat</strong>'e tıkla, sonra kamera ve mikrofon seçeneklerine ulaşmak için <strong>Go To Settings</strong>'i aç."),
           ("SplitCam'i kamera olarak seç", "ImLive ayarlarında <strong>SplitCam</strong>'i web kamerası VE mikrofon olarak seç. ImLive artık düz web kamerası yerine tam SplitCam sahneni gösterir."),
           ("Free Live Chat'i başlat", "Canlıya geçmek için ImLive'de <strong>Free Live Chat</strong>'e tıkla. Oturum ortasında görünümü değiştirmek için sahneyi SplitCam'de düzenle — ImLive anında güncellenir."),
       ]),
    _p("vxlive", "VXLive",
       "VXLive'de SplitCam ile yayın — Resmi destek",
       "Ücretsiz SplitCam ile VXLive (VXModels / VISIT-X) yayını — resmi VISIT-X ön ayarı, sunucu ve anahtar, sahneler. Filigran yok.",
       "vxlive, visit-x, vxmodels splitcam, vxlive yayın, visit-x stream, vxlive rtmp",
       'SplitCam ile <span class="accent">VXLive</span>\'de nasıl yayın yapılır',
       "VXLive yayını",
       "VXLive SplitCam'i resmi destekler (VISIT-X ön ayarı).",
       "VXLive (VXModels / VISIT-X), Alman pazarından bir cam platformudur — ve <strong style='color:var(--text)'>SplitCam'i resmi olarak adıyla destekleyen</strong> az sayıdaki platformdan biri. VXModels'in <strong style='color:var(--text)'>SplitCam</strong>'i VXLive'e bağlamak için özel bir yardım makalesi var ve SplitCam VISIT-X'i hazır kanal ön ayarı olarak sunar.",
       "SplitCam ile VXLive'de yayın: SplitCam'i kur, sahneyi oluştur, VXLive'de «Stream with third-party software»'i seç, sunucu URL'si ve anahtarı kopyala, SplitCam'de VISIT-X ön ayarını seç ve yapıştır, SplitCam'de Go Live, sonra VXLive'de GO ONLINE."
       "<ol><li>SplitCam'i kur.</li><li>Kamera + sahne ekle.</li><li>VXLive'den sunucu URL'si + anahtarı al.</li><li>SplitCam'de VISIT-X ön ayarını seç, yapıştır.</li><li>Go Live, sonra VXLive'de GO ONLINE.</li></ol>",
       "VXLive'de <strong>Stream with third-party software</strong>'i seç ve <strong>OBS, SplitCam veya XSplit</strong> seçeneğini seç. VXLive bir <strong>sunucu URL'si</strong> ve bir <strong>yayın anahtarı</strong> sağlar. SplitCam'de yayın platformu olarak <strong>VISIT-X</strong>'i seç, ikisini de yapıştır, SplitCam'de <strong>Go Live</strong>'a bas, sonra VXLive'de <strong>GO ONLINE</strong>.",
       [("VISIT-X entegre ön ayardır", "Ham RTMP URL'si yazma — SplitCam'in platform listesinde VISIT-X var; sadece seç ve sunucu URL'si ile anahtarı yapıştır."),
        ("İki adımlı go-live", "VXLive'de önce SplitCam'de Go Live'a bas, sonra VXLive'de GO ONLINE — ikisi de, bu sırayla."),
        ("Alman pazarı", "VXLive kitlesi ağırlıklı Almanca konuşur — Almanca bir metin katmanı veya başlık izleyicilerle bağ kurmaya yardım eder."),
        _T_ETH],
       [("VXLive SplitCam'i resmi destekliyor mu?", "Evet — VXModels (VXLive) SplitCam kurulumuna özel resmi bir yardım makalesi tutar ve SplitCam'i OBS ve XSplit ile birlikte desteklenen yayın yazılımı olarak listeler."),
        ("SplitCam'i VXLive'e nasıl bağlarım?", "VXLive'de «Stream with third-party software»'i seçersin, sonra SplitCam'de VISIT-X ön ayarını seçer ve VXLive'in verdiği sunucu URL'si ile yayın anahtarını yapıştırırsın."),
        ("SplitCam'de mi VXLive'de mi canlıya geçerim?", "İkisinde de — önce SplitCam'de Go Live, sonra VXLive'de GO ONLINE."),
        ("VXModels neden SplitCam öneriyor?", "VXModels'in resmi yardım makalesi SplitCam'i özellikle web kamerası görüntü bozulmalarını ve pikselleşmeyi gidermek ve bağlantıyı sabitlemek için önerir — sadece genel bir kodlayıcı olarak değil.")]),
    _p("virtwish", "VirtWish",
       "VirtWish'te SplitCam ile yayın — Yayın URL'si & anahtar",
       "Ücretsiz SplitCam ile VirtWish'te yayın yap — Profile → Start Broadcast OBS bölümü, yayın URL'si ve anahtar, sahneler ve katmanlar.",
       "virtwish, virtwish yayın, virtwish broadcasting software, virtwish rtmp, virtwish stream key, virtwish obs",
       'SplitCam ile <span class="accent">VirtWish</span>\'te nasıl yayın yapılır',
       "VirtWish yayını",
       "VirtWish için yayın URL'si + anahtar kurulumu.",
       "VirtWish etkileşimli bir cam platformudur. Yayın ayarları sana bir OBS bölümünde <strong style='color:var(--text)'>yayın URL'si ve ayrı bir yayın anahtarı</strong> verir — ücretsiz <strong style='color:var(--text)'>SplitCam</strong> ikisini de alır ve şovu sahneler ile katmanlarla yürütür.",
       "SplitCam ile VirtWish'te yayın: SplitCam'i kur, sahneyi oluştur, VirtWish'te <em>Profile → Start Broadcast</em>'i OBS bölümüne kadar aç, bağlantı ve anahtarı kopyala, ikisini de SplitCam'e yapıştır, Go Live."
       "<ol><li>SplitCam'i kur.</li><li>Kamera + sahne ekle.</li><li>VirtWish'ten URL + anahtarı al.</li><li>İkisini de SplitCam'e yapıştır.</li><li>Go Live'a bas.</li></ol>",
       "VirtWish'te sağ üst köşedeki simgeye tıkla → <strong>Profile</strong> → <strong>Start Broadcast</strong>, sonra OBS bölümüne ulaşmak için tekrar <strong>Start Broadcast</strong>. <strong>İlk satırdaki bağlantıyı</strong> SplitCam'in Stream URL alanına, <strong>Stream Key</strong>'i ayrıca anahtar alanına kopyala.",
       [("Bağlantı ilk satırda", "VirtWish'in OBS bölümü yayın URL'sini ilk satıra koyar — SplitCam Stream URL'ye kopyala, sonra ayrı anahtarı."),
        ("Start Broadcast'e iki tıklama", "OBS bölümüne ulaşmak için VirtWish'te Start Broadcast'e iki kez tıklarsın — beklenen, hata değil."),
        _T_ETH, _T_TEST],
       [("VirtWish RTMP verileri nerede?", "Sağ üst simge → Profile → Start Broadcast iki kez → OBS bölümü bağlantıyı ve yayın anahtarını gösterir."),
        ("VirtWish harici kodlayıcıları destekliyor mu?", "Evet — OBS bölümü yayın URL'si ve anahtar sağlar, böylece SplitCam çalışır."),
        ("VirtWish için hangi bitrate?", "VirtWish resmi tavan yayınlamaz; 1080p'de 3.500–6.000 Kbps güvenli. Yeniden ölçeklemeyi önlemek için SplitCam çözünürlüğünü VirtWish'te ayarlananla eşle."),
        ("SplitCam VirtWish için ücretsiz mi?", "Evet — ücretsiz, filigransız ve süre sınırı yok. VirtWish'in URL-ve-anahtar kurulumu sadece gereken dakikalara mal olur.")]),
    _p("xmodels", "XModels",
       "XModels'te SplitCam ile yayın — Ücretsiz rehber",
       "Ücretsiz SplitCam ile XModels'te yayın yap — model hesabı ayarlarında harici kodlayıcı seçeneği, RTMP anahtarı, sahneler ve katmanlar.",
       "xmodels, xmodels yayın, xmodels broadcasting software, xmodels rtmp, xmodels harici kodlayıcı",
       'SplitCam ile <span class="accent">XModels</span>\'te nasıl yayın yapılır',
       "XModels yayını",
       "XModels yayınları için harici kodlayıcı kurulumu.",
       "XModels, model hesabı ayarlarında yerleşik bir <strong style='color:var(--text)'>harici kodlayıcı seçeneği</strong> olan bir cam-streaming platformudur. Ücretsiz <strong style='color:var(--text)'>SplitCam</strong> orada tek düz kamera yerine çoklu kamera sahneleri, katmanlar ve filtrelerle yayın yapar.",
       "SplitCam ile XModels'te yayın: SplitCam'i kur, sahneyi oluştur, XModels model hesabında harici kodlayıcı seçeneğini etkinleştir, sunucu URL'si ve yayın anahtarını kopyala, SplitCam'e yapıştır, Go Live."
       "<ol><li>SplitCam'i kur.</li><li>Kamera + sahne ekle.</li><li>XModels ayarlarında harici kodlayıcıyı etkinleştir.</li><li>Sunucu URL'si + anahtarı SplitCam'e yapıştır.</li><li>Go Live'a bas.</li></ol>",
       "XModels <strong>model hesabı ayarlarında</strong> <strong>harici kodlayıcı ile yayın</strong> seçeneğini etkinleştir. XModels bir <strong>yayın anahtarı</strong> sağlar — SplitCam'e kopyala. Seçenek beklediğin yerde değilse, XModels desteği sitedeki SSS sohbeti ve <strong>info@xmodels.com</strong>'dur; yukarıdaki video da gösterir.",
       [("Hesap ayarlarında", "XModels harici kodlayıcı seçeneğini ayrı bir yayın ekranında değil, model hesabı ayarlarına koyar."),
        ("Destek: sohbet + e-posta", "XModels'in büyük bir herkese açık yardım merkezi yok — sitedeki SSS sohbeti ve info@xmodels.com resmi destek kanallarıdır."),
        ("Katmanları SplitCam'de yığ", "Bahşiş hedefleri, isim ve sosyal medya sahne katmanları olarak — XModels'in temel kamerası bunları eklemez."),
        _T_ETH],
       [("XModels harici kodlayıcıları destekliyor mu?", "Evet — model hesabı ayarları, yayın anahtarı sağlayan harici kodlayıcı yayın seçeneği içerir, böylece SplitCam çalışır."),
        ("XModels yardımını nereden alırım?", "XModels desteği sitedeki SSS sohbeti ve info@xmodels.com e-postası üzerindendir — büyük bir herkese açık yardım merkezi yok."),
        ("XModels için hangi bitrate?", "XModels resmi bir sayı belgelemez — 1080p'de 3.500–6.000 Kbps kullan ve SplitCam'in hız testini çalıştır, çünkü XModels desteği sadece sohbet ve e-posta."),
        ("SplitCam XModels için ücretsiz mi?", "Evet — ücretsiz, filigransız ve süre sınırı yok, böylece XModels'in Avrupa ağına yayın yazılım maliyeti eklemez.")]),
    _p("flirt4free", "Flirt4Free",
       "Flirt for Free cam'de SplitCam ile yayın — Ücretsiz rehber",
       "Ücretsiz SplitCam ile Flirt for Free cam'de yayın yap — External Broadcast Form, RTMP URL ve Stream Name, sahneler ve katmanlar.",
       "flirt for free cam, flirt 4 free cam, flirt4free, flirt4free yayın, flirt4free external broadcast, flirt4free rtmp",
       'SplitCam ile <span class="accent">Flirt4Free</span>\'de nasıl yayın yapılır',
       "Flirt4Free yayını",
       "Flirt4Free için External Broadcast Form kurulumu.",
       "Flirt4Free, 90'lardan beri yayında olan en eski cam platformlarından biridir. Bir <strong style='color:var(--text)'>External Broadcast Form</strong> aracılığıyla harici yayını resmi destekler — ücretsiz <strong style='color:var(--text)'>SplitCam</strong> yayını gönderirken form çözünürlüğü ve bitrate'i ayarlar.",
       "SplitCam ile Flirt4Free'de yayın: SplitCam'i kur, sahneyi oluştur, Flirt4Free External Broadcast Form'u aç, RTMP URL ve Stream Name'i kopyala ve çözünürlük/bitrate ayarla, SplitCam'e yapıştır, Go Live."
       "<ol><li>SplitCam'i kur.</li><li>Kamera + sahne ekle.</li><li>Flirt4Free External Broadcast Form'u aç.</li><li>RTMP URL + Stream Name'i SplitCam'e yapıştır.</li><li>Go Live'a bas.</li></ol>",
       "Flirt4Free model alanında <strong>External Broadcast Form</strong>'u aç. Çoğu cam sitesinin aksine Flirt4Free sana bir <strong>RTMP URL</strong> ve bir <strong>Stream Name</strong> (bir «anahtar» değil) verir, ayrıca formun kendisinde doldurduğun çözünürlük ve bitrate alanları. URL ve Stream Name'i SplitCam'in sunucu ve anahtar alanlarına kopyala.",
       [("Anahtar değil, Stream Name", "Flirt4Free kimlik bilgisine Stream Name der. Onu SplitCam'in yayın anahtarı alanına yapıştır — aynı işi görür."),
        ("Çözünürlük/bitrate'i formda ayarla", "Flirt4Free'nin External Broadcast Form'unun kendi çözünürlük ve bitrate alanları var — görüntünün yeniden ölçeklenmemesi için SplitCam ayarlarıyla hizala."),
        ("Tarihi platform", "Flirt4Free 90'lardan beri çalışır — model araçları olgun ve External Broadcast Form bunun belgelenmiş bir parçasıdır."),
        _T_ETH],
       [("Flirt4Free harici kodlayıcıları destekliyor mu?", "Evet — resmi olarak, RTMP URL ve Stream Name sağlayan External Broadcast Form aracılığıyla. SplitCam kodlayıcı olarak çalışır."),
        ("Flirt4Free RTMP verilerini nereden alırım?", "Model alanındaki External Broadcast Form'dan — RTMP URL, Stream Name ve çözünürlük/bitrate alanlarını gösterir."),
        ("Flirt4Free için hangi bitrate?", "1080p'de 3.500–6.000 Kbps — External Broadcast Form'da ve SplitCam'de aynı değeri ayarla."),
        ("SplitCam Flirt4Free için ücretsiz mi?", "Evet — ücretsiz, filigransız ve süre sınırı yok, bu da şovların uzun olabildiği Flirt4Free gibi tarihi bir platforma uyar.")]),
    _p("mfc-alerts", "MFC Alerts",
       "SplitCam ile yayına MFC Alerts ekle",
       "MyFreeCams yayınında animasyonlu bahşiş uyarıları göster — ücretsiz SplitCam'de web kamerasının üstünde Browser katmanı olarak mfcalerts.com URL'si.",
       "mfc alerts, myfreecams alerts, mfc alerts ekle, mfcalerts splitcam, myfreecams tip alerts, myfreecams alerts overlay",
       'Yayınına <span class="accent">MFC Alerts</span> nasıl eklenir',
       "MFC Alerts ekle",
       "MyFreeCams yayınında animasyonlu bahşiş uyarıları göster.",
       "MFC Alerts, bir izleyici bahşiş gönderdiğinde MyFreeCams yayınında animasyonlu efektler gösterir. Ücretsiz <strong style='color:var(--text)'>SplitCam</strong> içinde <strong style='color:var(--text)'>Browser katmanı</strong> olarak çalışır — bir kez ayarlarsın ve bahşişler ekranda canlı tepkileri tetikler.",
       "SplitCam ile MFC Alerts ekleme: SplitCam'i kur, web kamerasını ekle, Browser sekmesini aç ve mfcalerts.com'u yükle, alerts URL'ni kopyala, web kamerasının üstüne Browser katmanı olarak ekle, sonra test bahşişiyle dene."
       "<ol><li>SplitCam'i kur.</li><li>Web kamerasını ekle.</li><li>mfcalerts.com'dan URL'yi al.</li><li>Web kamerasının üstüne Browser katmanı olarak ekle.</li><li>Test bahşişi gönder.</li></ol>",
       "SplitCam'de <strong>Browser</strong> sekmesini aç ve <strong>www.mfcalerts.com</strong>'a git. Giriş yap veya kaydol. Kişisel alerts URL'ni kopyalamak için <strong>Copy to clipboard</strong>'u kullan. URL'yi SplitCam Browser penceresine yapıştır ve <strong>Add</strong>'a tıkla. Sonra kaynak listesini, <strong>MFC Alerts web kamerasının üstünde</strong> olacak şekilde yeniden düzenle (3 nokta menüsü → Move Up).",
       [("MFC Alerts web kamerasının üstünde olmalı", "En sık hata: MFC Alerts katmanı kaynak listesinde web kamerasının altındaysa efektler gizli kalır. Yukarı taşı."),
        ("mfcalerts.com hesabı gerekir", "Alerts URL'si kişiseldir — hesabın yoksa önce mfcalerts.com'da kaydol."),
        ("Canlıdan önce test bahşişi gönder", "Katmanın çalıştığını doğrulamak için Settings → Send test tip kullan — hatayı şovun ortasında keşfetme."),
        _T_ETH],
       [("MFC Alerts nedir?", "İzleyiciler bahşiş gönderdiğinde yayınında video efektleri gösteren MyFreeCams için bir bildirim sistemi — SplitCam'de Browser katmanı olarak eklenir."),
        ("MFC Alerts'lerim neden görünmüyor?", "Neredeyse her zaman katman sırası — MFC Alerts Browser katmanı SplitCam kaynak listesinde web kamerasının üstünde olmalı."),
        ("MFC Alerts için hesap gerekir mi?", "Evet — kişisel alerts URL'ni almak için mfcalerts.com'da kaydol."),
        ("SplitCam bunun için ücretsiz mi?", "Evet — SplitCam ücretsiz, filigransız ve süre sınırı yok ve MFC Alerts browser katmanı ek maliyetsiz içinde çalışır.")],
       steps=[
           ("SplitCam'i kur ve web kamerasını ekle", "Windows veya macOS için ücretsiz SplitCam'i kur, sonra <strong>web kameranı</strong> kaynak olarak ekle. MFC Alerts bu kameranın üstünde katman olarak durur."),
           ("Browser sekmesini aç ve mfcalerts.com'a git", "SplitCam'de <strong>Browser</strong> sekmesini aç ve <strong>www.mfcalerts.com</strong>'a git. Giriş yap veya henüz mfcalerts.com hesabın yoksa kaydol."),
           ("Alerts URL'ni kopyala", "mfcalerts.com'da kişisel alerts URL'ni kopyalamak için <strong>Copy to clipboard</strong>'u kullan — bahşiş animasyonlarını işleyen sayfa budur."),
           ("URL'yi Browser katmanı olarak ekle — web kamerasının üstüne", "URL'yi SplitCam Browser penceresine yapıştır ve <strong>Add</strong>'a tıkla. Sonra kaynak listesini <strong>MFC Alerts web kamerasının üstünde</strong> olacak şekilde yeniden düzenle (3 nokta menüsü → Move Up). Altta durursa efektler gizli kalır."),
           ("Test bahşişiyle dene", "<strong>Settings → Send test tip</strong>'i aç ve uyarı efektinin kameranın üstünde göründüğünü doğrula. Sonra MyFreeCams'te normal yayın yap — gerçek bahşişler artık animasyonları tetikler."),
       ]),
    _p("lovense", "Lovense",
       "SplitCam ile yayına Lovense oyuncağı ekle",
       "Ücretsiz SplitCam ile cam yayınına etkileşimli Lovense oyuncağı bağla — Lovense SplitCam Toolset, ekranda bahşiş uyarıları, tepkiler.",
       "lovense yayına ekle, lovense cam stream, lovense splitcam, lovense splitcam toolset, lovense interactive toy streaming",
       'Yayınına <span class="accent">Lovense oyuncağı</span> nasıl eklenir',
       "Lovense oyuncağı ekle",
       "Cam yayınına etkileşimli Lovense oyuncağı bağla.",
       "Cam yayınını ücretsiz <strong style='color:var(--text)'>SplitCam</strong> ile yürütürsün ve token'lara tepki veren bir <strong style='color:var(--text)'>Lovense</strong> oyuncağını eşlersin. Lovense resmi bir <strong style='color:var(--text)'>Lovense SplitCam Toolset</strong> belgeler ve SplitCam resmi bir Lovense eklentisi sunar — entegrasyon iki taraftan da desteklenir.",
       "Yayına Lovense oyuncağı eklemek için: SplitCam ve Lovense yazılımını kur, oyuncağı eşle, Lovense'i cam platformuna bağla, SplitCam'e Lovense durumunu Browser katmanı olarak ekle, sonra normal yayın yap."
       "<ol><li>SplitCam'i kur.</li><li>Lovense yazılımını kur ve oyuncağı eşle.</li><li>Lovense'i cam sitesine bağla.</li><li>SplitCam'e Lovense katmanı ekle.</li><li>Go Live'a bas.</li></ol>",
       "Lovense Connect / Lovense Stream'i (resmi masaüstü uygulaması) kur. Oyuncağı aç ve Bluetooth ile eşle, böylece uygulama bağlı gösterir. Lovense uygulamasında cam hesabını bağla, böylece oyuncak izleyici token'larına / bahşişlerine tepki verir. Lovense bir katman / widget URL'si sağlar — SplitCam sahnesine <strong>Browser</strong> katmanı olarak ekle.",
       [("Resmi Lovense SplitCam Toolset'i kullan", "Lovense, kendi kurulum rehberiyle SplitCam'e özel bir toolset yayınlar — SplitCam için yapılmış oyuncak etkinliği katmanı ve bahşiş uyarıları ekler."),
        ("Lovense Cam Extension'ı güncelle", "Toolset güncel bir Lovense Cam Extension gerektirir (30.1.4 veya üstü) — canlıdan önce güncelle."),
        ("Oyuncağı şarjlı tut", "Şovun ortasında neredeyse boş pil etkileşimli tarafı öldürür — canlıdan önce tam şarj et."),
        ("Token tepkisini test et", "Odayı açmadan önce oyuncağın tepki verdiğini doğrulamak için küçük bir test bahşişi gönder."),
        ("Sürüm gereksinimlerini kontrol et", "Lovense SplitCam Toolset, SplitCam 10.4.5 veya üstünü gerektirir. Lovense Cam Extension resmi olarak Chaturbate, Stripchat, BongaCams, MyFreeCams ve CamSoda'yı kapsar — başka site için Lovense'in Generic URL entegrasyonunu kullan.")],
       [("Lovense SplitCam'i resmi destekliyor mu?", "Evet — Lovense kendi kurulum rehberiyle resmi bir «Lovense SplitCam Toolset» belgeler ve SplitCam resmi bir Lovense eklentisi sunar. Entegrasyon iki taraftan da desteklenir."),
        ("Oyuncak doğrudan SplitCam'e mi bağlanır?", "Hayır — oyuncak Lovense uygulamasıyla eşlenir; SplitCam Lovense katmanını gösterir ve kamerayı yayınlar."),
        ("Hangi cam siteleri Lovense'i destekler?", "Lovense Cam Extension resmi olarak Chaturbate, Stripchat, BongaCams, MyFreeCams ve CamSoda'yı destekler, diğerleri için değişken destek — güncel listeyi Lovense uygulamasında kontrol et."),
        ("Son bahşişleri ekranda gösterebilir miyim?", "Evet — Lovense widget URL'sini SplitCam'e Browser katmanı olarak ekle.")],
       steps=[
           ("SplitCam'i kur", "SplitCam, Windows ve macOS için ücretsiz bir yayın yazılımıdır — videonu cam platformuna gönderen kodlayıcı. Kur; filigran yok."),
           ("Lovense yazılımını kur ve oyuncağı eşle", "Lovense Connect / Lovense Stream'i (resmi masaüstü uygulaması) kur. Oyuncağı aç ve Bluetooth ile eşle, böylece uygulama bağlı gösterir."),
           ("Lovense'i cam platformuna bağla", "Lovense uygulamasında cam hesabını bağla, böylece oyuncak izleyici token'larına / bahşişlerine tepki verir. Çoğu büyük cam platformu desteklenir."),
           ("SplitCam'e Lovense katmanı ekle", "Lovense bir katman / widget URL'si sağlar. SplitCam sahnesine <strong>Browser</strong> katmanı olarak ekle, böylece izleyiciler oyuncak durumunu ve son bahşişleri ekranda görür."),
           ("Sahneyi oluştur ve Go Live", "Kamerayı ve diğer katmanları ekle, cam platformunun RTMP anahtarını SplitCam'e yapıştır ve <strong>Go Live</strong>'a tıkla. Oyuncak bahşişlere gerçek zamanlı tepki verir."),
       ]),
    _p("multistream-cams", "Birden fazla cam sitesi",
       "SplitCam ile aynı anda birden fazla cam sitesinde yayın",
       "SplitCam'in ücretsiz çoklu yayınıyla aynı anda MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat ve daha fazlasında yayın yap. Tek tık, filigran yok.",
       "birden fazla cam sitesinde yayın, multistream cam sites, aynı anda chaturbate ve bongacams yayını, çoklu yayın cam yazılımı",
       'Aynı anda <span class="accent">birden fazla cam sitesinde</span> nasıl yayın yapılır',
       "Cam çoklu yayını",
       "Aynı anda birden fazla cam sitesinde yayın.",
       "Ücretsiz <strong style='color:var(--text)'>SplitCam</strong> tek bir kodlamayı aynı anda <strong style='color:var(--text)'>birden fazla cam sitesine</strong> yayınlayabilir — MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat ve daha fazlası. Filigran yok, tek tık.",
       "Aynı anda birden fazla cam sitesinde yayın için: SplitCam'i kur, sahneyi oluştur, her cam sitesinin RTMP sunucu URL'si ve yayın anahtarını al, hepsini SplitCam çoklu yayın ayarlarına ekle, Go Live'a bir kez tıkla."
       "<ol><li>SplitCam'i kur.</li><li>Kamera + sahne ekle.</li><li>Her cam sitesinden RTMP anahtarı al.</li><li>Tüm anahtarları SplitCam multistream'e ekle.</li><li>Go Live'a bir kez bas.</li></ol>",
       "Her cam platformunda harici / RTMP yayını etkinleştir ve <strong>sunucu URL'si</strong> ile <strong>yayın anahtarını</strong> kopyala. SplitCam'de <strong>Stream Settings</strong>'i aç ve her cam sitesini özel RTMP hedefi olarak ekle — sunucu URL'si ve anahtarı yapıştır. Canlıya almak istediğin her şeyi işaretle. <strong>Go Live</strong>'a bas.",
       [("Yüklemeni izle", "Çoklu yayın yükleme yükünü çoğaltır. Her hedef kendi bitrate'ini tüketir — bağlantının toplamı kaldırabildiğinden emin ol."),
        ("Platform kurallarını kontrol et", "Bazı cam siteleri başka yerde aynı anda yayını yasaklar — çoklu yayından önce doğrula."),
        ("Kablo — burada düşüşe yer yok", "Çoklu yayın yükleme yükünü çoğaltır, böylece tek bir wi-fi düşüşü tüm hedefleri aynı anda düşürebilir. Kablo burada isteğe bağlı değil."),
        ("Sağlık monitörünü izle", "SplitCam hedef bazında durumu gösterir — yükleme kaldırmıyorsa bir siteyi bırak.")],
       [("SplitCam çoklu yayını ücretsiz mi?", "Evet — çoklu yayın yerleşik ve ücretsiz, hedef başına ücret yok, filigran yok."),
        ("Aynı anda kaç cam sitesinde yayın yapabilirim?", "Yükleme bant genişliğinin kaldırabildiği kadar — her hedef kendi bitrate'ini tüketir."),
        ("Bulut röle kullanır mı?", "Hayır — SplitCam yayınları PC'den her platformun girişine doğrudan peer-to-peer gönderir."),
        ("Çoklu yayın PC'mi yavaşlatır mı?", "Kodlama bir kez yapılır ve yeniden kullanılır; donanım kodlaması CPU yükünü düşük tutar. Gerçek sınır yükleme bant genişliğidir.")],
       steps=[
           ("SplitCam'i kur", "SplitCam, yerleşik çoklu yayınlı, Windows ve macOS için ücretsiz bir yayın yazılımıdır. Kur — filigran yok, kayıt yok."),
           ("Kamera ve sahneyi ayarla", "SplitCam'i aç, web kameranı ekle ve sahneyi katmanlar ve filtrelerle oluştur. Tek sahne her hedefi besler."),
           ("Her cam sitesinden RTMP anahtarı al", "Her cam platformunda harici / RTMP yayını etkinleştir ve <strong>sunucu URL'si</strong> ile <strong>yayın anahtarını</strong> kopyala. Yayın yapmak istediğin her site için tekrarla — kesin yollar için tek tek platform rehberlerine bak."),
           ("Her hedefi SplitCam'e ekle", "<strong>Stream Settings</strong>'i aç ve her cam sitesini özel RTMP hedefi olarak ekle — sunucu URL'si ve anahtarı yapıştır. Canlıya almak istediğin her şeyi işaretle."),
           ("Go Live'a bir kez tıkla", "<strong>Go Live</strong>'a bas. SplitCam yayını seçili her cam sitesine aynı anda, peer-to-peer, tek bir kodlamadan gönderir — ek ücret yok."),
       ]),
    _p("livejasmin", "LiveJasmin",
       "LiveJasmin'de SplitCam ile yayın — HD harici kodlayıcı",
       "Ücretsiz SplitCam ile LiveJasmin'de yayın yap — Model Center harici kodlayıcı, HD 1080p kurulum, çoklu kamera sahneleri ve katmanlar. Filigran yok, kayıt yok.",
       "livejasmin yayın, livejasmin obs, livejasmin harici kodlayıcı, livejasmin rtmp, livejasmin stream key, livejasmin model kurulumu",
       'SplitCam ile <span class="accent">LiveJasmin</span>\'de nasıl yayın yapılır',
       "LiveJasmin yayını",
       "LiveJasmin'in yalnızca-HD Model Center'ı için harici kodlayıcı kurulumu.",
       "LiveJasmin, Docler Holding'in amiral gemisidir — dünyanın en büyük cam ağlarından biri ve yalnızca-HD bir platform. Tercih edilen yayıncı, kendi <strong>JasminCAM</strong> istemcisidir; ama Model Center standart bir <strong>External Encoder</strong> yolu da sunar — ücretsiz <strong style='color:var(--text)'>SplitCam</strong> buna bağlanır ve aynı HD yayında çoklu kamera sahneleri, güzellik filtreleri ve katmanlarla yayın yapmana izin verir.",
       "SplitCam ile LiveJasmin'de yayın: SplitCam'i kur, HD sahneyi oluştur, Model Center'da <em>Settings → Broadcast → External Encoder</em>'a git, sunucu URL'si ve yayın anahtarını kopyala, SplitCam'e yapıştır, Go Live."
       "<ol><li>SplitCam'i kur.</li><li>Kamera + HD sahne ekle.</li><li>Model Center'dan URL ve yayın anahtarını al.</li><li>SplitCam'e yapıştır.</li><li>Go Live'a bas.</li></ol>",
       "<strong>modelcenter.livejasmin.com</strong>'a giriş yap, <strong>Settings → Broadcast → External Encoder</strong>'ı aç. Model Center hesabına bağlı bir <strong>sunucu URL'si</strong> ve <strong>yayın anahtarı</strong> gösterir — ikisini de SplitCam'in özel RTMP alanlarına kopyala. <strong>Not:</strong> External Encoder seçeneği görünmeden önce yeni hesapların onaylanması gerekir (48–72 saat) ve platform yalnızca-HD çıkışı zorunlu kılar.",
       [("HD ya da sıralaman düşer", "LiveJasmin yalnızca-HD'dir — 1280×720 altı sadece daha az ödeyen listelerde gösterilme riski taşır, 1080p altı 'Premium' uygunluğunu kaybeder. 30 fps'de 1920×1080, 4.000–6.000 Kbps hedefle."),
        ("JasminCAM mı, harici kodlayıcı mı", "Docler'ın kendi JasminCAM istemcisi en temiz HD uyumluluğu verir; ama hesabın onaylandıktan sonra OBS, SplitCam ve vMix gibi harici kodlayıcılar resmi olarak desteklenir — JasminCAM'in yapamadığı çoklu kamera sahnelerini ve katmanları açarlar."),
        ("Free chat ≠ private show", "Free chat yalnızca önizlemedir — çıplaklık yok. Modelin kazandığı yer Private ve Gold show. Sahneni hem giyinikken hem de show modunda güçlü görünecek şekilde tasarla."),
        _T_ETH],
       [("LiveJasmin, SplitCam gibi harici kodlayıcıları resmi olarak destekliyor mu?", "Evet — Model Center'da Settings → Broadcast altında External Encoder seçeneği var. Önerilen istemci JasminCAM'dir; ama model hesabın onaylandıktan sonra OBS, SplitCam ve diğer RTMP kodlayıcılar açıkça desteklenenler listesindedir."),
        ("LiveJasmin yayın anahtarımı nereden alırım?", "Model Center içinde: Settings → Broadcast → External Encoder. Sunucu URL'si ve hesaba özel yayın anahtarı orada görünür — ikisini de SplitCam'in özel RTMP alanlarına kopyala. Anahtar hesabına bağlı; şifre gibi davran."),
        ("LiveJasmin için hangi bitrate?", "LiveJasmin yalnızca-HD'dir — 30 fps'de 1920×1080, 4.000–6.000 Kbps ve 2 saniyelik keyframe aralığı hedefle. Bunun belirgin altı Premium etiketini kaybeder ve sıralamayı düşürür."),
        ("SplitCam LiveJasmin için ücretsiz mi?", "Evet — SplitCam ücretsizdir, filigransızdır ve süre sınırı yoktur. Tek 'maliyet' LiveJasmin'in HD gereksinimlerini karşılamaktır; SplitCam bunu yerel olarak 1080p sahne kompozisyonu ve güzellik filtreleriyle halleder.")],
       steps=[
           ("SplitCam'i indir ve kur", "SplitCam, Windows ve macOS için ücretsiz canlı yayın yazılımıdır — kayıt yok, kart yok, filigran yok. HD videonu LiveJasmin'e gönderen kodlayıcıdır."),
           ("HD sahneni oluştur", "SplitCam'i aç ve webcam'ini 1080p modunda ekle. Katmanları, metni, ikinci bir kamerayı veya telefonunu, güzellik filtrelerini ya da AI arka planı bindir — LiveJasmin HD kalite ister ve oluşturduğun sahne hem free chat'te hem de private show'larda premium görünmeli."),
           ("LiveJasmin URL'si ve yayın anahtarını al", "<strong>modelcenter.livejasmin.com</strong>'a giriş yap (hesabının önce onaylanması gerekir — kayıttan sonra genellikle 48–72 saat). <strong>Settings → Broadcast → External Encoder</strong>'ı aç. Sayfa bir <strong>sunucu URL'si</strong> ve hesaba özel <strong>yayın anahtarı</strong> gösterir. İkisini de kopyala."),
           ("SplitCam'i LiveJasmin'e bağla", "SplitCam'de <strong>Stream Settings</strong>'i aç, LiveJasmin sunucu URL'sini ve yayın anahtarını özel RTMP alanlarına yapıştır. Bitrate'i 30 fps'de 1920×1080'de 4.000–6.000 Kbps'ye, keyframe'i 2 saniyeye ayarla. Önce yerleşik hız testini çalıştır — HD yayınlar yorucudur."),
           ("Go Live'a tıkla", "SplitCam'de <strong>Go Live</strong>'a bas, ardından LiveJasmin Model Center'da çevrimiçi ol. ~10 saniye içinde HD akışın LiveJasmin ağına ulaşır. Sonraki yayınlar tek tıktır — SplitCam'i aç, Go Live, sonra LiveJasmin'de çevrimiçi ol."),
       ]),
]
