# -*- coding: utf-8 -*-
"""Hebrew (he) content for cam-streaming-guides. Native Hebrew (RTL), 19 platforms."""

_T_ETH = ("השתמשו בחיבור קווי", "Ethernet מנצח את ה-Wi-Fi בשידורים ארוכים — פריימים שאבדו "
          "פירושם טיפים שאבדו. חברו כבל למחשב המשדר.")
_T_TEST = ("עשו בדיקה פרטית קודם", "הריצו שידור בדיקה קצר כדי לבדוק מצלמה, אודיו, "
           "מסגור ושכבות לפני שאתם פותחים את החדר לצופים.")

def _p(slug, name, title, desc, kw, h1html, h1short, card, intro, quick, key_how, tips, faq, steps=None):
    d = {"slug": slug, "name": name, "title": title, "desc": desc, "kw": kw,
         "h1html": h1html, "h1short": h1short, "card": card, "intro": intro,
         "quick": quick, "key_how": key_how, "tips": tips, "faq": faq}
    if steps: d["steps"] = steps
    return d

PLATFORMS_HE = [
    _p("chaturbate", "Chaturbate",
       "שידור ב-Chaturbate עם SplitCam — טוקן ו-RTMP",
       "שידור ב-Chaturbate עם SplitCam בחינם — broadcast token, RTMP, סצנות מרובות מצלמות ושכבות. ללא סימן מים, ללא הרשמה.",
       "שידור chaturbate, chaturbate broadcast token, chaturbate rtmp obs, chaturbate מקודד חיצוני, chaturbate live",
       'איך לשדר ב-<span class="accent">Chaturbate</span> עם SplitCam',
       "שידור Chaturbate",
       "הגדרה מבוססת טוקן עם מקודד חיצוני ב-Chaturbate.",
       "‏Chaturbate היא אחת מפלטפורמות הקאם הגדולות ביותר, הבנויה על כלכלת טוקנים. כלי השידור בדפדפן שלה הוא רק כלי שטוח עם מצלמה אחת — מעבר ל<strong style='color:var(--text)'>מקודד חיצוני</strong> עם <strong style='color:var(--text)'>SplitCam</strong> החינמי פותח סצנות מרובות מצלמות, שכבות ומסננים באותו שידור מבוסס טוקנים.",
       "שידור ב-Chaturbate עם SplitCam: התקינו SplitCam, בנו סצנה, ב-Chaturbate פתחו <em>Broadcast Yourself → My Broadcast</em>, העתיקו את ה-broadcast token, הדביקו ב-SplitCam, Go Live."
       "<ol><li>התקינו SplitCam.</li><li>הוסיפו מצלמה + סצנה.</li><li>העתיקו broadcast token מ-Chaturbate.</li><li>הדביקו ב-SplitCam.</li><li>לחצו Go Live.</li></ol>",
       "ב-Chaturbate לחצו <strong>Broadcast Yourself</strong> כדי להגיע לעמוד <strong>My Broadcast</strong>, ואז <strong>View RTMP/OBS broadcast information and stream key</strong>. המפתח מופיע כ-<strong>broadcast token</strong> — העתיקו אותו. התייחסו אליו כמו לסיסמה; לעולם אל תשתפו.",
       [("הטוקן הוא המפתח", "‏Chaturbate משתמשת ב-broadcast token שלכם, לא במפתח שידור כללי. התייחסו אליו כמו לסיסמה ואפסו אותו אם דלף."),
        ("הרבה מרווח", "‏RTMP ingest של Chaturbate מקבל עד 4K, 60 fps וביטרייט גבוה — המגבלה היא ההעלאה שלכם, לא הפלטפורמה. פריים מפתח כל 2 שניות."),
        _T_ETH, _T_TEST],
       [("האם Chaturbate מתירה OBS / מקודד חיצוני?", "כן — Chaturbate תומכת במקודדים חיצוניים רשמית עם מאמר «How do I set up OBS?» משלה. הפעילו דרך «Use External Encoder to Broadcast» בהגדרות השידור."),
        ("איפה מפתח השידור שלי ב-Chaturbate?", "‏Broadcast Yourself → My Broadcast → View RTMP/OBS broadcast information and stream key. המפתח הוא ה-broadcast token שלכם."),
        ("איזה ביטרייט ל-Chaturbate?", "‏3,500–6,000 Kbps ב-1080p זה יותר מספיק. התקרה של Chaturbate גבוהה — המגבלה האמיתית היא ההעלאה שלכם; הריצו קודם את בדיקת המהירות המובנית של SplitCam."),
        ("האם SplitCam חינמי ל-Chaturbate?", "כן — חינמי לחלוטין, ללא סימן מים וללא הגבלת זמן: המקודד לא אוכל מההכנסות שלכם בטוקנים.")]),
    _p("cam4", "CAM4",
       "שידור ב-CAM4 עם SplitCam — External Encoder",
       "שידור ב-CAM4 עם SplitCam בחינם — External Encoder, מפתח שידור, חסימה גאוגרפית ושכבות. ללא סימן מים.",
       "שידור cam4, cam4.com, cam4 external encoder, cam4 מפתח שידור, cam4 rtmp obs",
       'איך לשדר ב-<span class="accent">CAM4</span> עם SplitCam',
       "שידור CAM4",
       "‏External Encoder ב-CAM4 עם שליטה גאוגרפית.",
       "‏CAM4 היא פלטפורמת cam-and-earn גלובלית עם שליטה גאוגרפית מובנית — אפשר להסתיר את השידור במדינות מסוימות. שידור דרך <strong style='color:var(--text)'>SplitCam</strong> החינמי כמקודד חיצוני פותח החלפת סצנות ושכבות שאין בכלי הבסיסי.",
       "שידור ב-CAM4 עם SplitCam: התקינו SplitCam, בנו סצנה, ב-CAM4 פתחו <em>Broadcast &amp; Earn Money → Start Broadcast → External Encoder</em>, Get Stream Key, הדביקו ב-SplitCam, Go Live."
       "<ol><li>התקינו SplitCam.</li><li>הוסיפו מצלמה + סצנה.</li><li>קבלו מפתח שידור מ-CAM4.</li><li>הדביקו ב-SplitCam.</li><li>לחצו Go Live.</li></ol>",
       "ב-CAM4 לחצו <strong>Broadcast</strong> → <strong>Broadcast &amp; Earn Money</strong> → <strong>Start Broadcast</strong>, ואז <strong>External Encoder</strong> למעלה. מלאו תאריך לידה, מין ומדינה, השתמשו ב-<strong>Get Stream Key</strong> והעתיקו. המחוון הירוק ב-Stream Settings של SplitCam מסמן חיבור.",
       [("הגדירו הגבלות גאוגרפיות", "‏CAM4 מאפשרת להסתיר את השידור במדינות ואזורים מסוימים — הגדירו זאת בצד של CAM4 לפני go-live."),
        ("שימו לב למחוון הירוק", "הגדרת CAM4 מציגה מחוון ירוק ב-Stream Settings של SplitCam כשהמפתח מתקבל — אדום = בדקו את המפתח."),
        ("ביטרייט נמוך מהרגיל", "‏RTMP ingest של CAM4 מגביל את ביטרייט הווידאו לכ-3,000 Kbps — נמוך מרוב אתרי הקאם. אל תכפו גבוה יותר."),
        _T_ETH],
       [("האם CAM4 תומכת ב-OBS / מקודד חיצוני רשמית?", "כן — ל-CAM4 יש OBS Guide רשמי בעמוד התמיכה והיא ממליצה על External Encoder לחוויה הטובה ביותר. SplitCam משתמש באותו נתיב RTMP."),
        ("אפשר לחסום גאוגרפית את השידור ב-CAM4?", "כן — ל-CAM4 יש הגבלות גאוגרפיות מובנות להסתרת השידור במדינות מסוימות. הגדירו זאת ב-CAM4, לא ב-SplitCam."),
        ("איפה מפתח השידור של CAM4?", "‏Broadcast → Broadcast & Earn Money → Start Broadcast → External Encoder → Get Stream Key."),
        ("איזה ביטרייט ל-CAM4?", "נמוך מהממוצע — RTMP ingest של CAM4 מגביל לכ-3,000 Kbps ב-30 fps עם פריים מפתח כל שנייה. הטבלה הרשמית מייעצת לא לעבור ~3,000.")]),
    _p("bongacams", "BongaCams",
       "שידור ב-BongaCams עם SplitCam — External Encoder",
       "שידור ב-BongaCams עם SplitCam בחינם — External Encoder, סצנות מרובות מצלמות, שכבות ורקעי AI. ללא סימן מים.",
       "bongacams, bongcams, שידור bongacams, bongacams external encoder, bongacams rtmp obs",
       'איך לשדר ב-<span class="accent">BongaCams</span> עם SplitCam',
       "שידור BongaCams",
       "הגדרת External Encoder ל-BongaCams.",
       "‏BongaCams היא פלטפורמת קאם גלובלית. שידור במקודד חיצוני לא תמיד מופעל — לאחר הפעלה, <strong style='color:var(--text)'>SplitCam</strong> החינמי שולט בשידור עם סצנות מרובות מצלמות, שכבות ורקעי AI.",
       "שידור ב-BongaCams עם SplitCam: התקינו SplitCam, בנו סצנה, ב-BongaCams פתחו <em>Options → Broadcast settings → Select Encoder → External Encoder</em>, העתיקו URL ומפתח, הדביקו ב-SplitCam, Go Live."
       "<ol><li>התקינו SplitCam.</li><li>הוסיפו מצלמה + סצנה.</li><li>קבלו URL ומפתח מ-BongaCams.</li><li>הדביקו ב-SplitCam.</li><li>לחצו Go Live.</li></ol>",
       "ב-BongaCams פתחו <strong>Options</strong> → <strong>Broadcast settings</strong> → <strong>Select Encoder</strong> → <strong>External Encoder</strong> והעתיקו את כתובת השרת ומפתח השידור המוצגים. <strong>אם כפתור ה-External Encoder חסר</strong>, פנו לתמיכת BongaCams ובקשו להפעיל קידוד חיצוני בחשבון.",
       [("אין כפתור External Encoder? תמיכה", "‏BongaCams מפעילה קידוד חיצוני לכל חשבון בנפרד — אם האפשרות חסרה ב-Broadcast settings, התמיכה מפעילה אותה."),
        ("התאימו רזולוציה", "‏BongaCams ממליצה שרזולוציית המצלמה והשידור יתאימו — למשל שתיהן 1280×720."),
        _T_ETH, _T_TEST],
       [("למה כפתור ה-External Encoder לא מופיע ב-BongaCams?", "קידוד חיצוני אינו מופעל כברירת מחדל בכל חשבון — פנו לתמיכת BongaCams כדי להפעיל אותו, ואז הכפתור יופיע ב-Broadcast settings."),
        ("האם צריך לאמת את חשבון BongaCams?", "כן — שידור דורש 18+, תעודה רשמית לאימות גיל ואישור חשבון לפני שידור חי."),
        ("איזה ביטרייט ל-BongaCams?", "‏RTMP ingest של BongaCams מגביל את ביטרייט הווידאו לכ-6,000 Kbps עם פריים מפתח כל 2 שניות — 3,500–6,000 ב-1080p זה אזור אידיאלי; בדקו העלאה קודם."),
        ("האם SplitCam חינמי ל-BongaCams?", "כן — חינמי לחלוטין, ללא סימן מים וללא הגבלת זמן, כך שהמקודד לא מקטין את הכנסות הטוקנים שלכם ב-BongaCams.")]),
    _p("stripchat", "Stripchat",
       "שידור ב-Stripchat עם SplitCam — הגדרת strip cam",
       "שידור ב-Stripchat — פלטפורמת strip cam — עם SplitCam בחינם. תוכנה חיצונית, מפתח מבוסס טוקן, סצנות ושכבות.",
       "strip cam, stripchat live stream, שידור stripchat, stripchat external software, stripchat מפתח שידור, stripchat rtmp obs",
       'איך לשדר ב-<span class="accent">Stripchat</span> עם SplitCam',
       "שידור Stripchat",
       "הגדרת תוכנה חיצונית לשידור Stripchat.",
       "‏Stripchat היא פלטפורמת קאם גדולה המתמקדת באינטראקטיביות. מצב <em>external software</em> נותן לכם מפתח מבוסס טוקן — הזינו אותו ל-<strong style='color:var(--text)'>SplitCam</strong> החינמי כדי לשדר עם סצנות, שכבות ומסננים במקום מצלמה שטוחה.",
       "שידור ב-Stripchat עם SplitCam: התקינו SplitCam, בנו סצנה, ב-Stripchat בחרו <em>Switch to external software</em>, העתיקו מפתח שידור, הדביקו ב-SplitCam, Go Live."
       "<ol><li>התקינו SplitCam.</li><li>הוסיפו מצלמה + סצנה.</li><li>קבלו מפתח שידור מ-Stripchat.</li><li>הדביקו ב-SplitCam.</li><li>לחצו Go Live.</li></ol>",
       "ב-Stripchat בחרו <strong>Switch to external software</strong>, ואז <strong>Show external software settings for the stream</strong>. העתיקו את מפתח השידור — Stripchat מציגה אותו כטוקן. שמרו אותו בסוד.",
       [("התאימו רזולוציה לאתר", "ה-FAQ של Stripchat מזהיר: הרזולוציה בתוכנה שלכם חייבת להתאים בדיוק לאתר, אחרת הווידאו מתפרק. הגדירו את שתיהן זהות."),
        ("היזהרו ממינימום 2 Mbps", "‏Stripchat מציינת 2 Mbps העלאה כמינימום — ואומרת בפירוש שזה לא מספיק לשידור OBS או מולטיסטרים. כוונו הרבה יותר גבוה."),
        ("המפתח הוא טוקן", "מפתח השידור של Stripchat הוא טוקן — העתיקו במדויק, לעולם אל תשתפו, אפסו אם דלף."),
        _T_ETH],
       [("האם Stripchat ממליצה על OBS / תוכנה חיצונית?", "כן — ה-FAQ הרשמי של Stripchat ממליץ על תוכנת שידור חיצונית כמו OBS «להשגת איכות הווידאו והאודיו הטובה ביותר». SplitCam עובד באותו אופן."),
        ("איך מעבירים את Stripchat לתוכנה חיצונית?", "ב-Broadcast Center בחרו Switch to External Broadcast Software (OBS), ואז פתחו external software settings כדי להציג את מפתח השידור (טוקן)."),
        ("איזה ביטרייט ל-Stripchat?", "‏RTMP ingest מקבל עד ~6,000 Kbps עם פריים מפתח כל 2 שניות. 3,500–6,000 ב-1080p זה אידיאלי — אך חייב להיות הרבה מעל המינימום של 2 Mbps, במיוחד לשידור OBS."),
        ("האם SplitCam חינמי ל-Stripchat?", "כן — ללא דמי רישיון, ללא סימן מים, ללא הגבלת זמן: גם מופעי Stripchat אינטראקטיביים ארוכים לא עולים כלום בצד המקודד.")]),
    _p("onlyfans", "OnlyFans",
       "לייב ב-OnlyFans עם SplitCam — הרשאה או מפתח",
       "לייב ב-OnlyFans עם SplitCam בחינם — התחברות דרך הרשאה או OBS Key, סצנות מרובות מצלמות, שכבות. ללא סימן מים.",
       "לייב onlyfans, onlyfans live stream, onlyfans הרשאה splitcam, onlyfans obs key, onlyfans תוכנת שידור",
       'איך לעשות <span class="accent">לייב ב-OnlyFans</span> עם SplitCam',
       "לייב OnlyFans",
       "הרשו פעם אחת או הדביקו מפתח — לייב ב-OnlyFans.",
       "לייב OnlyFans למנויים שלכם. SplitCam מתחבר ב<strong style='color:var(--text)'>שתי דרכים</strong> — התחברו פעם אחת עם חשבון OnlyFans ו-SplitCam שולף את מפתח השידור אוטומטית ומסנכרן אותו, או הדביקו OBS Key ידנית. שתיהן מאפשרות לשדר עם סצנות מרובות מצלמות, שכבות ומסננים.",
       "לייב ב-OnlyFans עם SplitCam: התקינו SplitCam, בנו סצנה, פתחו Stream Settings &rarr; Add Channel &rarr; OnlyFans ובחרו <em>הרשאה</em> — התחברו עם חשבון OnlyFans, SplitCam שולף את המפתח אוטומטית — ולחצו Go Live. עם חשבון מחובר אפשר לשנות פרמטרים של שידור OnlyFans ב-SplitCam בלי לפתוח את אתר OnlyFans.",
       "ב-OnlyFans: <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; מקטע <strong>Other</strong>, העתיקו <strong>OBS Key</strong>. או השתמשו באפשרות <strong>הרשאה</strong> ב-SplitCam כדי להתחבר — המפתח נשלף אוטומטית ונשאר מסונכרן.",
       [("הרשאה מול Stream Key", "שתי דרכי חיבור: <strong>הרשאה</strong> (התחברו פעם אחת, המפתח נשלף ומסונכרן — הדרך הקלה ביותר) או <strong>Stream Key</strong> (העתיקו OBS Key ב-OnlyFans → Profile → Settings → Other והדביקו)."),
        ("שנו הגדרות בלי לצאת מ-SplitCam", "עם הרשאה החשבון נשאר מחובר, כך שאתם מגדירים פרמטרים של לייב OnlyFans מ-SplitCam במהלך או אחרי השידור — בלי לבקר באתר OnlyFans."),
        ("ביטרייט צנוע", "‏RTMP ingest של OnlyFans מגביל את ביטרייט הווידאו לכ-2,500 Kbps — מחמיר יותר מרוב אתרי הקאם. כוונו ל-720p–1080p ב-~2,000–2,500."),
        _T_ETH],
       [("איך מחברים OnlyFans ל-SplitCam?", "בשתי דרכים. <strong>הרשאה</strong> — Stream Settings → Add Channel → OnlyFans → התחברו עם חשבון OnlyFans ו-SplitCam שולף את המפתח אוטומטית. או <strong>Stream Key</strong> — העתיקו OBS Key ב-OnlyFans → Profile → Settings → Other והדביקו."),
        ("אפשר לשנות הגדרות לייב של OnlyFans בלי לפתוח את האתר?", "כן — בשיטת ההרשאה SplitCam נשאר מחובר לחשבון OnlyFans, כך שהמפתח וההגדרות מסתנכרנים אוטומטית. אתם משנים הכול מ-SplitCam במהלך או אחרי השידור, בלי לבקר ב-onlyfans.com."),
        ("איזה ביטרייט ל-OnlyFans?", "צנוע — RTMP ingest של OnlyFans מגביל את הביטרייט לכ-2,500 Kbps, מחמיר בהרבה מפלטפורמות קאם אחרות. כוונו ל-720p–1080p סביב 2,000–2,500 Kbps."),
        ("האם SplitCam חינמי ללייב ב-OnlyFans?", "כן — חינמי, ללא סימן מים וללא הגבלת זמן. אין עלויות בצד המקודד.")],
       steps=[
           ("הורידו והתקינו SplitCam", "‏SplitCam היא תוכנת שידור חי חינמית ל-Windows ו-macOS — ללא הרשמה, ללא כרטיס, ללא סימן מים. זה המקודד ששולח את הווידאו שלכם ל-OnlyFans."),
           ("הגדירו מצלמה וסצנה", "פתחו SplitCam והוסיפו את המצלמה. בנו את הסצנה כפי שאתם רוצים שהצופים יראו — שכבות, טקסט, מצלמה שנייה, מסנני יופי או רקע AI, הכול מוחל בזמן אמת."),
           ("חיבור — דרך 1: הרשאה (מומלץ)", "ב-SplitCam פתחו <strong>Stream Settings</strong> &rarr; <strong>Add Channel</strong> &rarr; <strong>OnlyFans</strong> ובחרו <strong>הרשאה</strong>. התחברו עם אימייל וסיסמה של OnlyFans. SplitCam מקשר את החשבון, שולף את מפתח השידור אוטומטית ומסנכרן אותו — וגם מאפשר לנהל פרמטרים של לייב OnlyFans בתוך SplitCam, לשנות אותם במהלך או אחרי השידור בלי לפתוח את אתר OnlyFans."),
           ("חיבור — דרך 2: Stream Key (ידני)", "לא רוצים להתחבר? השתמשו במפתח. ב-OnlyFans פתחו <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; מקטע <strong>Other</strong> והעתיקו <strong>OBS Key</strong>. ב-SplitCam, Add Channel &rarr; OnlyFans, הדביקו בשדה המפתח. המפתח הזה סטטי — לשינוי הגדרות בהמשך חזרו לאתר OnlyFans."),
           ("Go Live", "בכל דרך, לחצו <strong>Go Live</strong> ב-SplitCam. בדרך 1 אפשר להמשיך לכוונן פרמטרים של OnlyFans מ-SplitCam בזמן אמת; בדרך 2 המפתח נשאר בדיוק כפי שהגדרתם."),
       ]),
    _p("camplace", "CamPlace",
       "שידור ב-CamPlace עם SplitCam — מדריך חינמי",
       "שידור ב-CamPlace עם SplitCam בחינם — מקודד חיצוני, מפתח RTMP, סצנות ושכבות. שלב אחר שלב, ללא סימן מים.",
       "שידור camplace, camplace broadcasting software, camplace rtmp, camplace מקודד חיצוני, camplace מפתח שידור",
       'איך לשדר ב-<span class="accent">CamPlace</span> עם SplitCam',
       "שידור CamPlace",
       "הגדרת מקודד חיצוני לשידור CamPlace.",
       "‏CamPlace היא פלטפורמת cam-streaming. אין מאמר OBS ציבורי, כך ש<strong style='color:var(--text)'>מדריך הווידאו למעלה</strong> הוא ההפניה שלכם — <strong style='color:var(--text)'>SplitCam</strong> החינמי מתחבר דרך RTMP סטנדרטי ומוסיף סצנות, שכבות ורקעי AI שאין במצלמה הבסיסית.",
       "שידור ב-CamPlace עם SplitCam: התקינו SplitCam, בנו סצנה, הפעילו שידור חיצוני/RTMP ב-CamPlace, העתיקו URL שרת ומפתח שידור, הדביקו ב-SplitCam, Go Live. עקבו אחרי הווידאו לנתיב העדכני."
       "<ol><li>התקינו SplitCam.</li><li>הוסיפו מצלמה + סצנה.</li><li>קבלו מפתח RTMP מ-CamPlace.</li><li>הדביקו ב-SplitCam.</li><li>לחצו Go Live.</li></ol>",
       "התחברו ל-CamPlace ופתחו את הגדרות השידור. עברו לאפשרות מקודד חיצוני / RTMP / OBS כדי להציג <strong>URL שרת</strong> ו<strong>מפתח שידור</strong>, העתיקו את שניהם. CamPlace לא מפרסמת תיעוד OBS רשמי — <strong>הווידאו למעלה</strong> הוא הנתיב האמין ביותר שלב אחר שלב דרך הממשק הנוכחי.",
       [("אין מדריך OBS רשמי — השתמשו בווידאו", "ל-CamPlace אין מאמר ציבורי על מקודד חיצוני; הווידאו למעלה הוא ההפניה לנתיב הנוכחי."),
        ("RTMP סטנדרטי עובד", "למרות שאינו מתועד, CamPlace מקבלת URL שרת RTMP סטנדרטי ומפתח — SplitCam מתחבר כיעד RTMP מותאם."),
        ("ערמו שכבות ב-SplitCam", "יעדי טיפים, שם וכינויי רשתות חברתיות הוסיפו כשכבות סצנה — המצלמה הבסיסית של CamPlace לא מוסיפה אותן."),
        _T_ETH],
       [("האם ל-CamPlace יש מדריך OBS רשמי?", "לא נמצא מאמר ציבורי על מקודד חיצוני. CamPlace מקבלת URL RTMP סטנדרטי ומפתח, כך ש-SplitCam עובד — עקבו אחרי הווידאו."),
        ("האם CamPlace תומכת במקודד חיצוני?", "כן — מקבלת מפתח שידור RTMP סטנדרטי, כך ש-SplitCam מתחבר כיעד RTMP מותאם."),
        ("איזה ביטרייט ל-CamPlace?", "‏CamPlace לא מפרסמת מספרים רשמיים — השתמשו ב-3,500–6,000 Kbps ב-1080p כטווח בטוח ותנו לבדיקת המהירות של SplitCam לקבוע את התקרה האמיתית."),
        ("האם SplitCam חינמי ל-CamPlace?", "כן — חינמי, ללא סימן מים וללא הגבלת זמן. מכיוון של-CamPlace אין מקודד משלה, כלי RTMP חינמי פותר זאת.")]),
    _p("camsoda", "CamSoda",
       "‏CamSoda לייב עם SplitCam — הגדרה חינמית",
       "‏CamSoda לייב עם SplitCam בחינם — Use OBS Broadcaster, שרתים אזוריים, סצנות ושכבות. ללא סימן מים.",
       "camsoda live, שידור camsoda, camsoda obs broadcaster, camsoda rtmp obs, camsoda live broadcast",
       'איך לשדר ב-<span class="accent">CamSoda</span> עם SplitCam',
       "שידור CamSoda",
       "הגדרת Use OBS Broadcaster ב-CamSoda.",
       "‏CamSoda היא פלטפורמת קאם אמריקאית הידועה בפורמטי מופע אינטראקטיביים ויוצאי דופן. היא תומכת בשידור OBS רשמית — יש כפתור <strong style='color:var(--text)'>Use OBS Broadcaster</strong> בעמוד Go Live ומדריך OBS רשמי בוויקי של CamSoda. <strong style='color:var(--text)'>SplitCam</strong> החינמי עובד באותו אופן.",
       "שידור ב-CamSoda עם SplitCam: התקינו SplitCam, בנו סצנה, לחצו Use OBS Broadcaster בעמוד Go Live של CamSoda, העתיקו URL שרת ומפתח שידור, הדביקו ב-SplitCam, Go Live."
       "<ol><li>התקינו SplitCam.</li><li>הוסיפו מצלמה + סצנה.</li><li>לחצו Use OBS Broadcaster ב-CamSoda.</li><li>הדביקו URL שרת + מפתח ב-SplitCam.</li><li>לחצו Go Live.</li></ol>",
       "בעמוד <strong>Go Live</strong> של CamSoda לחצו <strong>Use OBS Broadcaster</strong>. CamSoda מציגה URL שרת RTMP ומפתח שידור — העתיקו את שניהם. בחרו את השרת האזורי הקרוב ביותר (צפון אמריקה, אירופה, אסיה וכו'). בוויקי של CamSoda יש מדריך OBS מלא לפרטים.",
       [("אמתו כדי לקבל טיפים", "ב-CamSoda כל אחד יכול לשדר, אך כדי לקבל טיפים עליכם להשלים את תהליך האימות של CamSoda."),
        ("בחרו את השרת האזורי הקרוב", "‏CamSoda מציעה שרתי ingest אזוריים — הקרוב ביותר (צ\"א / אירופה / אסיה / דרום אמריקה / אוקיאניה) מפחית עיכוב ופריימים שאבדו."),
        ("תקרה ב-1080p / 30 fps", "‏ingest של CamSoda מגיע לכ-1080p, 30 fps ו-~6,000 Kbps — אל תכפו גבוה יותר."),
        _T_ETH],
       [("האם CamSoda תומכת ב-OBS / מקודד חיצוני?", "כן — רשמית. יש כפתור Use OBS Broadcaster בעמוד Go Live ומדריך OBS בוויקי של CamSoda, כך ש-SplitCam עובד."),
        ("האם צריך אימות ב-CamSoda?", "לשידור, לא. לקבלת טיפים, כן — CamSoda דורשת לעבור קודם תהליך אימות."),
        ("איזו רזולוציה CamSoda תומכת?", "עד 1920×1080 ב-30 fps, מקסימום סביב 6,000 Kbps ב-RTMP ingest."),
        ("האם SplitCam חינמי ל-CamSoda?", "כן — חינמי, ללא סימן מים וללא הגבלת זמן. עובד עם מצב Use OBS Broadcaster החינמי של CamSoda, כך שכל המערך לא עולה כלום.")]),
    _p("streamate", "Streamate",
       "שידור ב-Streamate עם SplitCam — ערוץ משולב",
       "שידור ב-Streamate עם SplitCam בחינם — ערוץ משולב, מפתח SM Connect, סצנות ושכבות. ללא סימן מים.",
       "streamate, streamate sm connect, שידור streamate, streamate broadcasting software, streamate rtmp",
       'איך לשדר ב-<span class="accent">Streamate</span> עם SplitCam',
       "שידור Streamate",
       "‏Streamate הוא ערוץ משולב ב-SplitCam — הגדרה מהירה.",
       "‏Streamate היא פלטפורמת קאם ותיקה — והיא <strong style='color:var(--text)'>יעד מוגדר מראש ב-SplitCam</strong>, ברשימת הערוצים, כך שההגדרה מהירה יותר מהזנת RTMP ידנית: בחרו Streamate, הדביקו מפתח, סיימתם.",
       "שידור ב-Streamate עם SplitCam: התקינו SplitCam, בנו סצנה, ב-Streamate השתמשו ב-<em>SM Connect → Start Show</em> והעתיקו מפתח, ואז ב-SplitCam פתחו <em>Stream Settings → Add Channel → Streamate</em> והדביקו."
       "<ol><li>התקינו SplitCam.</li><li>הוסיפו מצלמה + סצנה.</li><li>קבלו מפתח Streamate דרך SM Connect.</li><li>Add Channel → Streamate ב-SplitCam.</li><li>לחצו Go Live.</li></ol>",
       "ב-Streamate פתחו <strong>SM Connect</strong>, אשרו את התנאים, לחצו <strong>Start Show</strong> משמאל וסגרו את החלון שנפתח — ואז העתיקו את מפתח השידור. ב-SplitCam פתחו <strong>Stream Settings</strong> → <strong>Add Channel</strong>, בחרו <strong>Streamate</strong> מהרשימה והדביקו את המפתח. המחוון הירוק מסמן חיבור.",
       [("Streamate משולב", "ללא URL RTMP ידני — ל-SplitCam יש Streamate ברשימת Add Channel; פשוט בחרו והדביקו מפתח."),
        ("סגרו את חלון SM Connect", "אחרי Start Show, Streamate פותחת חלון — סגרו אותו; הוא רק להצגת מפתח השידור."),
        ("נעלו רזולוציה ל-1080p", "שדה Video Resolution ב-SM Connect עלול לקפוץ בשקט ל-1440, שלמעשה לא נשלח ומוריד את האיכות שלכם בשקט — הגדירו ידנית 1080p. ירידת ביטרייט בתמונה סטטית היא נורמלית: הזרם של Streamate אדפטיבי."),
        _T_ETH, _T_TEST],
       [("האם Streamate משולב ב-SplitCam?", "כן — Streamate מופיע ברשימת Add Channel של SplitCam; אתם בוחרים אותו, לא מקלידים URL RTMP ידנית."),
        ("איפה מפתח השידור של Streamate?", "‏SM Connect → אשרו תנאים → Start Show → סגרו את החלון → העתיקו מפתח."),
        ("איזה ביטרייט ל-Streamate?", "‏Streamate לא קובעת תקרה קשיחה — 3,500–6,000 Kbps ב-1080p עובד טוב. הזרם אדפטיבי, כך שביטרייט נמוך יותר בתמונה סטטית הוא נורמלי, לא תקלה."),
        ("האם SplitCam חינמי ל-Streamate?", "כן — חינמי, ללא סימן מים וללא הגבלת זמן; ומכיוון ש-Streamate הוא ערוץ משולב ב-SplitCam, אין עלויות מקודד נפרדות.")]),
    _p("streamray", "StreamRay",
       "שידור ב-StreamRay cam עם SplitCam — URL בצ'אט",
       "שידור ב-StreamRay cam עם SplitCam בחינם — URL מתפרסם בצ'אט, מצב OBS Broadcaster, סצנות ושכבות. ללא סימן מים.",
       "streamray, streamray cam, שידור streamray, streamray obs broadcaster, streamray rtmp",
       'איך לשדר ב-<span class="accent">StreamRay</span> עם SplitCam',
       "שידור StreamRay",
       "הגדרת מקודד חיצוני מסוג URL-בצ'אט ל-StreamRay.",
       "ל-StreamRay יש הגדרת מקודד חיצוני יוצאת דופן — היא שולחת את ה-URL של הזרם ב<strong style='color:var(--text)'>חלון הצ'אט של השידור</strong> ולא משתמשת במפתח נפרד. <strong style='color:var(--text)'>SplitCam</strong> החינמי מטפל בזרימת ה-URL-בלבד הזו.",
       "שידור ב-StreamRay עם SplitCam: התקינו SplitCam, בנו סצנה, הפעילו OBS Broadcaster ב-StreamRay, העתיקו URL זרם מחלון הצ'אט, הדביקו ב-SplitCam (השאירו את שדה המפתח ריק), Go Live."
       "<ol><li>התקינו SplitCam.</li><li>הוסיפו מצלמה + סצנה.</li><li>העתיקו URL StreamRay מהצ'אט.</li><li>הדביקו URL ב-SplitCam.</li><li>לחצו Go Live.</li></ol>",
       "ב-StreamRay לחצו פעמיים על <strong>Broadcast Now</strong>, פתחו את התפריט <strong>Other</strong>, בחרו <strong>OBS Broadcaster</strong> ו-<strong>Save and Close</strong>. StreamRay אז מפרסמת את <strong>URL הזרם בחלון הצ'אט</strong> — העתיקו משם. השאירו את שדה מפתח השידור של SplitCam <strong>ריק</strong>; StreamRay מאמתת רק דרך URL.",
       [("ה-URL נמצא בצ'אט", "‏StreamRay לא מציגה את ה-URL של הזרם בתיבת ההגדרות — היא מפרסמת אותו בחלון הצ'אט של השידור. העתיקו משם."),
        ("השאירו את שדה המפתח ריק", "‏StreamRay לא משתמשת במפתח נפרד — רק URL. אל תזינו דבר בשדה המפתח של SplitCam."),
        _T_ETH, _T_TEST],
       [("איפה ה-URL של הזרם ב-StreamRay?", "אחרי הפעלת OBS Broadcaster, StreamRay מפרסמת את ה-URL בחלון הצ'אט — העתיקו מהצ'אט."),
        ("למה אין מפתח שידור ב-StreamRay?", "‏StreamRay מאמתת רק דרך URL — השאירו את שדה המפתח של SplitCam ריק."),
        ("איזה ביטרייט ל-StreamRay?", "‏StreamRay לא מציינת תקרה רשמית — כוונו ל-3,500–6,000 Kbps ב-1080p והריצו את בדיקת המהירות של SplitCam, מכיוון שזרימת ה-URL-בלבד לא נותנת משוב ביטרייט."),
        ("האם SplitCam חינמי ל-StreamRay?", "כן — חינמי, ללא סימן מים וללא הגבלת זמן, מתאים לזרימת ה-URL-בלבד של StreamRay: הדביקו קישור אחד ואתם בלייב.")]),
    _p("xlovecam", "XLoveCam",
       "שידור ב-XLoveCam עם SplitCam — קישור RTMP ומפתח",
       "שידור ב-XLoveCam עם SplitCam בחינם — קישור RTMP ומפתח, שרתים אזוריים, סצנות ושכבות. ללא סימן מים.",
       "xlovecam, x love cam, שידור xlovecam, xlovecam rtmp link, xlovecam מפתח שידור",
       'איך לשדר ב-<span class="accent">XLoveCam</span> עם SplitCam',
       "שידור XLoveCam",
       "הגדרת קישור RTMP + מפתח ל-XLoveCam.",
       "‏XLoveCam היא פלטפורמת קאם אירופית רב-לשונית. הגדרות החשבון מציגות גם <strong style='color:var(--text)'>קישור RTMP</strong> וגם <strong style='color:var(--text)'>מפתח שידור</strong> — <strong style='color:var(--text)'>SplitCam</strong> החינמי לוקח את שניהם ומשדר עם סצנות ושכבות מלאות.",
       "שידור ב-XLoveCam עם SplitCam: התקינו SplitCam, בנו סצנה, ב-XLoveCam פתחו <em>My Account → settings</em>, העתיקו קישור RTMP ומפתח שידור, הדביקו את שניהם ב-SplitCam, התחילו מופע."
       "<ol><li>התקינו SplitCam.</li><li>הוסיפו מצלמה + סצנה.</li><li>העתיקו קישור RTMP + מפתח מ-XLoveCam.</li><li>הדביקו את שניהם ב-SplitCam.</li><li>לחצו Go Live.</li></ol>",
       "ב-XLoveCam פתחו <strong>My Account</strong> → <strong>settings</strong>. ההגדרות מציגות גם <strong>קישור RTMP</strong> וגם <strong>מפתח שידור</strong> — העתיקו את שניהם לשדות URL השרת והמפתח של SplitCam, ואז <strong>Start your show</strong> ב-XLoveCam.",
       [("העתיקו גם קישור וגם מפתח", "‏XLoveCam נותנת קישור RTMP וגם מפתח שידור נפרד — אתם צריכים את שניהם ב-SplitCam, לא רק אחד."),
        ("קהל רב-לשוני", "‏XLoveCam אירופית ורב-לשונית — שכבות טקסט ברורות בשפה שלכם עוזרות לצופים למצוא אתכם."),
        ("בחרו את השרת הקרוב", "‏XLoveCam מציעה שרתי RTMP אזוריים — אירופה, צפון אמריקה, דרום אמריקה ואסיה. הקרוב ביותר מפחית עיכוב ופריימים שאבדו."),
        _T_ETH],
       [("איפה נתוני ה-RTMP של XLoveCam?", "‏My Account → settings — מציג גם קישור RTMP וגם מפתח."),
        ("האם XLoveCam תומכת במקודד חיצוני?", "כן — מספקת קישור RTMP ומפתח, כך ש-SplitCam עובד כמקודד."),
        ("איזה ביטרייט ל-XLoveCam?", "‏XLoveCam לא מפרסמת מגבלה קבועה; 3,500–6,000 Kbps ב-1080p אידיאלי. בחירת השרת האזורי הקרוב חשובה לא פחות — היא מפחיתה פריימים שאבדו."),
        ("האם SplitCam חינמי ל-XLoveCam?", "כן — חינמי, ללא סימן מים וללא הגבלת זמן. להגיע לקהל האירופי הרב-לשוני של XLoveCam לא עולה דמי תוכנה.")]),
    _p("soulcams", "SoulCams",
       "שידור ב-SoulCams עם SplitCam — הגדרות OBS",
       "שידור ב-SoulCams עם SplitCam בחינם — הגדרות OBS, שרת RTMP ומפתח, סצנות מרובות מצלמות ושכבות.",
       "soul cams, soulcams, שידור soulcams, soulcams obs, soulcams rtmp, soulcams broadcast",
       'איך לשדר ב-<span class="accent">SoulCams</span> עם SplitCam',
       "שידור SoulCams",
       "הגדרות OBS ל-SoulCams.",
       "‏SoulCams היא פלטפורמת קאם שהגדרות ה-OBS שלה מציגות <strong style='color:var(--text)'>שרת RTMP ומפתח שידור יחד</strong> בחלון אחד. הדביקו את שניהם ב-<strong style='color:var(--text)'>SplitCam</strong> החינמי כדי לשדר עם סצנות מרובות מצלמות ושכבות.",
       "שידור ב-SoulCams עם SplitCam: התקינו SplitCam, בנו סצנה, ב-SoulCams לחצו Go Online → Settings → OBS, העתיקו שרת ומפתח, הדביקו את שניהם ב-SplitCam, Go Live."
       "<ol><li>התקינו SplitCam.</li><li>הוסיפו מצלמה + סצנה.</li><li>פתחו SoulCams Settings → OBS.</li><li>הדביקו שרת + מפתח ב-SplitCam.</li><li>לחצו Go Live.</li></ol>",
       "ב-SoulCams התחברו ולחצו <strong>Go Online</strong>, ואז פתחו <strong>Settings</strong> → <strong>OBS</strong>. חלון ה-OBS מציג <strong>שרת RTMP</strong> ו<strong>מפתח שידור</strong> יחד — העתיקו את שניהם ל-SplitCam.",
       [("שרת ומפתח זה ליד זה", "‏SoulCams מציגה את שרת ה-RTMP והמפתח באותו חלון OBS — קחו את שניהם בבת אחת."),
        ("Go Online קודם", "הגדרות ה-OBS מופיעות רק אחרי לחיצה על Go Online ב-SoulCams — עשו זאת לפני חיפוש נתוני המקודד."),
        ("חסמו אזורים לא רצויים", "‏SoulCams מאפשרת חסימה גאוגרפית מצד הדוגמנית — בחרו אילו מדינות לא יראו את הזרם לפני לחיצה על Go Online."),
        _T_ETH, _T_TEST],
       [("איפה הגדרות ה-OBS של SoulCams?", "התחברו, לחצו Go Online, ואז Settings → OBS — שרת RTMP ומפתח שידור מוצגים יחד."),
        ("האם SoulCams תומכת במקודד חיצוני?", "כן — הגדרות ה-OBS נותנות שרת RTMP ומפתח, כך ש-SplitCam עובד."),
        ("איזה ביטרייט ל-SoulCams?", "‏SoulCams לא נותנת מספרים רשמיים — כוונו ל-3,500–6,000 Kbps ב-1080p ובדקו העלאה, מכיוון שחלון ה-OBS לא מציג הנחיות ביטרייט."),
        ("האם SplitCam חינמי ל-SoulCams?", "כן — חינמי, ללא סימן מים וללא הגבלת זמן, כך שמופעים מלאים ב-SoulCams עם סצנות מרובות מצלמות ושכבות לא עולים כלום בצד המקודד.")]),
    _p("imlive", "ImLive",
       "שימוש ב-ImLive עם SplitCam — מצלמה וירטואלית",
       "הגדרת Im Live stream עם SplitCam בחינם — ImLive משתמשת במצלמה חיה (ללא RTMP), חברו את SplitCam כמצלמה וירטואלית עם סצנות.",
       "im live stream, imlive splitcam, שידור imlive, imlive מצלמה וירטואלית, imlive webcam, im live cam",
       'איך להשתמש ב-<span class="accent">ImLive</span> עם SplitCam',
       "SplitCam ב-ImLive",
       "הגדרת מצלמה וירטואלית ל-ImLive — ללא RTMP.",
       "‏ImLive משתמשת במצלמת אינטרנט חיה בדפדפן — <strong style='color:var(--text)'>ללא RTMP או מפתח שידור</strong>. <strong style='color:var(--text)'>SplitCam</strong> החינמי מתחבר כ<strong style='color:var(--text)'>מצלמה וירטואלית</strong>: בנו סצנה ב-SplitCam, ואז בחרו את SplitCam כמצלמה ב-ImLive.",
       "שימוש ב-SplitCam עם ImLive: התקינו SplitCam, בנו סצנה עם שכבות מדיה, פתחו ImLive והתחילו צ'אט וידאו, בהגדרות ImLive בחרו SplitCam כמצלמה ומיקרופון."
       "<ol><li>התקינו SplitCam.</li><li>בנו סצנה ב-SplitCam.</li><li>התחילו צ'אט וידאו ב-ImLive.</li><li>בחרו SplitCam כמצלמת ImLive.</li><li>התחילו צ'אט.</li></ol>",
       "התחברו לאתר ImLive ולחצו <strong>Start Video Chat</strong>, ואז פתחו <strong>Go To Settings</strong> לגישה לאפשרויות המצלמה והמיקרופון. בהגדרות ImLive בחרו <strong>SplitCam</strong> כמצלמה ומיקרופון.",
       [("מפתח שידור לא נדרש", "ל-ImLive אין RTMP — אל תחפשו URL שרת או מפתח. SplitCam רק נבחר כהתקן מצלמה."),
        ("הגדירו SplitCam גם כמיקרופון", "בחרו SplitCam למיקרופון בנוסף למצלמה, כדי שגם מיקס האודיו והפחתת הרעש ייכנסו ללייב."),
        ("בנו סצנה לפני הלייב", "‏ImLive מציגה את מה ש-SplitCam שולח — סדרו את השכבות לפני התחלת הצ'אט."),
        _T_TEST],
       [("האם ImLive משתמשת ב-RTMP או מפתח שידור?", "באף אחד — ImLive משתמשת במצלמה חיה דרך הדפדפן. SplitCam מתחבר כמצלמה וירטואלית, אין מפתח להעתיק."),
        ("איך בוחרים SplitCam ב-ImLive?", "‏Start Video Chat → Go To Settings → בחרו SplitCam כמצלמה ומיקרופון."),
        ("אפשר להשתמש בשכבות ב-ImLive?", "כן — בנו אותן בסצנת SplitCam; ImLive מציגה את התוצאה המורכבת."),
        ("האם SplitCam חינמי ל-ImLive?", "כן — חינמי, ללא סימן מים וללא הגבלת זמן. כמצלמה וירטואלית ל-ImLive, הוא לא מוסיף עלויות או מיתוג לצ'אט הווידאו שלכם.")],
       steps=[
           ("התקינו SplitCam", "‏SplitCam היא תוכנה חינמית ל-Windows ו-macOS. התקינו אותה — ללא סימן מים, ללא הרשמה. עבור ImLive היא עובדת כ<strong>מצלמה וירטואלית</strong>, לא כמקודד RTMP."),
           ("בנו סצנה ב-SplitCam", "פתחו SplitCam והשתמשו ב-<strong>Media Layers +</strong> כדי להוסיף את המצלמה בתוספת שכבות, טקסט, מסננים או רקע AI כלשהם. הסצנה המורכבת הזו היא מה ש-ImLive תראה כמצלמה שלכם."),
           ("התחילו צ'אט וידאו ב-ImLive", "התחברו לאתר ImLive ולחצו <strong>Start Video Chat</strong>, ואז פתחו <strong>Go To Settings</strong> לגישה לאפשרויות המצלמה והמיקרופון."),
           ("בחרו SplitCam כמצלמה", "בהגדרות ImLive בחרו <strong>SplitCam</strong> כמצלמה וגם מיקרופון. ImLive מציגה כעת את סצנת SplitCam המלאה שלכם, לא מצלמה שטוחה."),
           ("התחילו Free Live Chat", "לחצו <strong>Free Live Chat</strong> ב-ImLive כדי לעלות ללייב. כדי לשנות מראה באמצע הסשן, ערכו את הסצנה ב-SplitCam — ImLive מתעדכנת מיד."),
       ]),
    _p("vxlive", "VXLive",
       "שידור ב-VXLive עם SplitCam — תמיכה רשמית",
       "שידור ב-VXLive (VXModels / VISIT-X) עם SplitCam בחינם — preset VISIT-X רשמי, שרת ומפתח, סצנות. ללא סימן מים.",
       "vxlive, visit-x, vxmodels splitcam, שידור vxlive, visit-x stream, vxlive rtmp",
       'איך לשדר ב-<span class="accent">VXLive</span> עם SplitCam',
       "שידור VXLive",
       "‏VXLive תומכת ב-SplitCam רשמית (preset VISIT-X).",
       "‏VXLive (VXModels / VISIT-X) היא פלטפורמת קאם מהשוק הגרמני — ואחת המעטות ש<strong style='color:var(--text)'>תומכות ב-SplitCam רשמית בשמו</strong>. ל-VXModels יש מאמר עזרה ייעודי על חיבור <strong style='color:var(--text)'>SplitCam</strong> ל-VXLive, ו-SplitCam מציע את VISIT-X כ-preset ערוץ מוכן.",
       "שידור ב-VXLive עם SplitCam: התקינו SplitCam, בנו סצנה, ב-VXLive בחרו «Stream with third-party software», העתיקו URL שרת ומפתח, ב-SplitCam בחרו preset VISIT-X והדביקו, Go Live ב-SplitCam, ואז GO ONLINE ב-VXLive."
       "<ol><li>התקינו SplitCam.</li><li>הוסיפו מצלמה + סצנה.</li><li>קבלו URL שרת + מפתח מ-VXLive.</li><li>בחרו preset VISIT-X ב-SplitCam, הדביקו.</li><li>Go Live, ואז GO ONLINE ב-VXLive.</li></ol>",
       "ב-VXLive בחרו <strong>Stream with third-party software</strong> ואת האפשרות <strong>OBS, SplitCam או XSplit</strong>. VXLive מספקת <strong>URL שרת</strong> ו<strong>מפתח שידור</strong>. ב-SplitCam בחרו <strong>VISIT-X</strong> כפלטפורמת השידור, הדביקו את שניהם, לחצו <strong>Go Live</strong> ב-SplitCam, ואז <strong>GO ONLINE</strong> ב-VXLive.",
       [("VISIT-X הוא preset משולב", "אל תקלידו URL RTMP גולמי — ל-SplitCam יש VISIT-X ברשימת הפלטפורמות; פשוט בחרו והדביקו URL שרת ומפתח."),
        ("go-live בשני שלבים", "ב-VXLive לחצו קודם Go Live ב-SplitCam, ואז GO ONLINE ב-VXLive — שניהם, בסדר הזה."),
        ("שוק גרמני", "קהל VXLive ברובו דובר גרמנית — שכבות טקסט או כותרות בגרמנית עוזרות להתחבר לצופים."),
        _T_ETH],
       [("האם VXLive תומכת ב-SplitCam רשמית?", "כן — VXModels (VXLive) מתחזקת מאמר עזרה רשמי ייעודי להגדרת SplitCam ומציינת את SplitCam לצד OBS ו-XSplit כתוכנת שידור נתמכת."),
        ("איך מחברים SplitCam ל-VXLive?", "ב-VXLive בחרו «Stream with third-party software», ואז ב-SplitCam בחרו preset VISIT-X והדביקו את URL השרת ומפתח השידור ש-VXLive נותנת."),
        ("האם אני בלייב ב-SplitCam או ב-VXLive?", "בשניהם — Go Live ב-SplitCam קודם, ואז GO ONLINE ב-VXLive."),
        ("למה VXModels ממליצה על SplitCam?", "מאמר העזרה הרשמי של VXModels ממליץ על SplitCam במיוחד להסרת ארטיפקטים בתמונת המצלמה ופיקסול ולייצוב החיבור — לא רק כמקודד כללי.")]),
    _p("virtwish", "VirtWish",
       "שידור ב-VirtWish עם SplitCam — URL זרם ומפתח",
       "שידור ב-VirtWish עם SplitCam בחינם — מקטע OBS Profile → Start Broadcast, URL זרם ומפתח, סצנות ושכבות.",
       "virtwish, שידור virtwish, virtwish broadcasting software, virtwish rtmp, virtwish מפתח שידור, virtwish obs",
       'איך לשדר ב-<span class="accent">VirtWish</span> עם SplitCam',
       "שידור VirtWish",
       "הגדרת URL זרם + מפתח ל-VirtWish.",
       "‏VirtWish היא פלטפורמת קאם אינטראקטיבית. הגדרות השידור נותנות לכם <strong style='color:var(--text)'>URL זרם ומפתח שידור נפרדים</strong> במקטע ה-OBS — <strong style='color:var(--text)'>SplitCam</strong> החינמי לוקח את שניהם ומריץ את המופע עם סצנות ושכבות.",
       "שידור ב-VirtWish עם SplitCam: התקינו SplitCam, בנו סצנה, ב-VirtWish פתחו <em>Profile → Start Broadcast</em> עד מקטע ה-OBS, העתיקו קישור ומפתח, הדביקו את שניהם ב-SplitCam, Go Live."
       "<ol><li>התקינו SplitCam.</li><li>הוסיפו מצלמה + סצנה.</li><li>קבלו URL + מפתח מ-VirtWish.</li><li>הדביקו את שניהם ב-SplitCam.</li><li>לחצו Go Live.</li></ol>",
       "ב-VirtWish לחצו על האייקון בפינה הימנית העליונה → <strong>Profile</strong> → <strong>Start Broadcast</strong>, ואז <strong>Start Broadcast</strong> שוב כדי להגיע למקטע ה-OBS. <strong>העתיקו את הקישור בשורה הראשונה</strong> לשדה Stream URL של SplitCam, ואת ה-<strong>Stream Key</strong> הנפרד לשדה המפתח.",
       [("הקישור בשורה הראשונה", "מקטע ה-OBS של VirtWish שם את ה-URL של הזרם בשורה הראשונה — העתיקו אותו ל-Stream URL של SplitCam, ואז את המפתח הנפרד."),
        ("שתי לחיצות על Start Broadcast", "אתם לוחצים על Start Broadcast פעמיים ב-VirtWish כדי להגיע למקטע ה-OBS — זה נורמלי, לא תקלה."),
        _T_ETH, _T_TEST],
       [("איפה נתוני ה-RTMP של VirtWish?", "אייקון פינה ימנית עליונה → Profile → Start Broadcast פעמיים → מקטע ה-OBS מציג קישור ומפתח שידור."),
        ("האם VirtWish תומכת במקודד חיצוני?", "כן — מקטע ה-OBS מספק URL זרם ומפתח, כך ש-SplitCam עובד."),
        ("איזה ביטרייט ל-VirtWish?", "‏VirtWish לא מפרסמת תקרה רשמית; 3,500–6,000 Kbps ב-1080p בטוח. התאימו את רזולוציית SplitCam לזו שהוגדרה ב-VirtWish כדי למנוע שינוי גודל."),
        ("האם SplitCam חינמי ל-VirtWish?", "כן — חינמי, ללא סימן מים וללא הגבלת זמן. הגדרת ה-URL-ומפתח של VirtWish לוקחת רק את כמה הדקות הנדרשות.")]),
    _p("xmodels", "XModels",
       "שידור ב-XModels עם SplitCam — מדריך חינמי",
       "שידור ב-XModels עם SplitCam בחינם — אפשרות מקודד חיצוני בהגדרות חשבון הדוגמנית, מפתח RTMP, סצנות ושכבות.",
       "xmodels, שידור xmodels, xmodels broadcasting software, xmodels rtmp, xmodels מקודד חיצוני",
       'איך לשדר ב-<span class="accent">XModels</span> עם SplitCam',
       "שידור XModels",
       "הגדרת מקודד חיצוני לשידור XModels.",
       "‏XModels היא פלטפורמת cam-streaming עם <strong style='color:var(--text)'>אפשרות מקודד חיצוני</strong> מובנית בהגדרות חשבון הדוגמנית. <strong style='color:var(--text)'>SplitCam</strong> החינמי משדר שם עם סצנות מרובות מצלמות, שכבות ומסננים, במקום מצלמה שטוחה אחת.",
       "שידור ב-XModels עם SplitCam: התקינו SplitCam, בנו סצנה, בחשבון הדוגמנית של XModels הפעילו את אפשרות המקודד החיצוני, העתיקו URL שרת ומפתח שידור, הדביקו ב-SplitCam, Go Live."
       "<ol><li>התקינו SplitCam.</li><li>הוסיפו מצלמה + סצנה.</li><li>הפעילו מקודד חיצוני בהגדרות XModels.</li><li>הדביקו URL שרת + מפתח ב-SplitCam.</li><li>לחצו Go Live.</li></ol>",
       "ב<strong>הגדרות חשבון הדוגמנית</strong> של XModels הפעילו את אפשרות <strong>שידור דרך מקודד חיצוני</strong>. XModels מספקת <strong>מפתח שידור</strong> — העתיקו אותו ל-SplitCam. אם האפשרות לא נמצאת היכן שאתם מצפים, התמיכה של XModels דרך צ'אט FAQ באתר ו-<strong>info@xmodels.com</strong>; הווידאו למעלה גם מראה זאת.",
       [("זה בהגדרות החשבון", "‏XModels ממקמת את אפשרות המקודד החיצוני בהגדרות חשבון הדוגמנית, לא במסך שידור נפרד."),
        ("תמיכה: צ'אט + אימייל", "ל-XModels אין מרכז עזרה ציבורי גדול — צ'אט FAQ באתר ו-info@xmodels.com הם ערוצי התמיכה הרשמיים."),
        ("ערמו שכבות ב-SplitCam", "יעדי טיפים, שם וכינויי רשתות חברתיות הוסיפו כשכבות סצנה — המצלמה הבסיסית של XModels לא מוסיפה אותן."),
        _T_ETH],
       [("האם XModels תומכת במקודד חיצוני?", "כן — הגדרות חשבון הדוגמנית כוללות אפשרות שידור במקודד חיצוני שמספקת מפתח שידור, כך ש-SplitCam עובד."),
        ("איפה מקבלים עזרה ב-XModels?", "התמיכה של XModels דרך צ'אט FAQ באתר ואימייל info@xmodels.com — אין מרכז עזרה ציבורי גדול."),
        ("איזה ביטרייט ל-XModels?", "‏XModels לא מתעדת מספרים רשמיים — השתמשו ב-3,500–6,000 Kbps ב-1080p והריצו את בדיקת המהירות של SplitCam, מכיוון שהתמיכה של XModels רק דרך צ'אט ואימייל."),
        ("האם SplitCam חינמי ל-XModels?", "כן — חינמי, ללא סימן מים וללא הגבלת זמן, כך ששידור לרשת האירופית של XModels לא מוסיף עלויות תוכנה.")]),
    _p("flirt4free", "Flirt4Free",
       "שידור ב-Flirt for Free cam עם SplitCam — מדריך חינמי",
       "שידור ב-Flirt for Free cam עם SplitCam בחינם — External Broadcast Form, RTMP URL ו-Stream Name, סצנות ושכבות.",
       "flirt for free cam, flirt 4 free cam, flirt4free, שידור flirt4free, flirt4free external broadcast, flirt4free rtmp",
       'איך לשדר ב-<span class="accent">Flirt4Free</span> עם SplitCam',
       "שידור Flirt4Free",
       "הגדרת External Broadcast Form ל-Flirt4Free.",
       "‏Flirt4Free היא אחת מפלטפורמות הקאם הוותיקות, באוויר מאז שנות ה-90. היא תומכת בשידור חיצוני רשמית דרך <strong style='color:var(--text)'>External Broadcast Form</strong> — <strong style='color:var(--text)'>SplitCam</strong> החינמי שולח את הזרם בעוד הטופס מגדיר רזולוציה וביטרייט.",
       "שידור ב-Flirt4Free עם SplitCam: התקינו SplitCam, בנו סצנה, פתחו את External Broadcast Form של Flirt4Free, העתיקו RTMP URL ו-Stream Name והגדירו רזולוציה/ביטרייט, הדביקו ב-SplitCam, Go Live."
       "<ol><li>התקינו SplitCam.</li><li>הוסיפו מצלמה + סצנה.</li><li>פתחו External Broadcast Form של Flirt4Free.</li><li>הדביקו RTMP URL + Stream Name ב-SplitCam.</li><li>לחצו Go Live.</li></ol>",
       "באזור הדוגמנית של Flirt4Free פתחו <strong>External Broadcast Form</strong>. בניגוד לרוב אתרי הקאם, Flirt4Free נותנת <strong>RTMP URL</strong> ו-<strong>Stream Name</strong> (לא «מפתח»), בתוספת שדות רזולוציה וביטרייט שאתם ממלאים בטופס עצמו. העתיקו את ה-URL וה-Stream Name לשדות השרת והמפתח של SplitCam.",
       [("זה Stream Name, לא מפתח", "‏Flirt4Free קוראת לפרטים שלה Stream Name. אתם מדביקים אותו בשדה מפתח השידור של SplitCam — הפונקציה זהה."),
        ("הגדירו רזולוציה/ביטרייט בטופס", "ל-External Broadcast Form של Flirt4Free יש שדות רזולוציה וביטרייט משלו — התאימו אותם להגדרות SplitCam כדי שהתמונה לא תשתנה בגודל."),
        ("פלטפורמה עם היסטוריה", "‏Flirt4Free פועלת מאז שנות ה-90 — כלי הדוגמניות שלה בשלים, וה-External Broadcast Form הוא חלק מתועד מהם."),
        _T_ETH],
       [("האם Flirt4Free תומכת במקודד חיצוני?", "כן — רשמית, דרך External Broadcast Form שמספק RTMP URL ו-Stream Name. SplitCam עובד כמקודד."),
        ("איפה מקבלים נתוני RTMP של Flirt4Free?", "מה-External Broadcast Form באזור הדוגמנית — מציג RTMP URL, Stream Name ושדות רזולוציה/ביטרייט."),
        ("איזה ביטרייט ל-Flirt4Free?", "‏3,500–6,000 Kbps ב-1080p — הגדירו אותם ערכים ב-External Broadcast Form וב-SplitCam."),
        ("האם SplitCam חינמי ל-Flirt4Free?", "כן — חינמי, ללא סימן מים וללא הגבלת זמן, מתאים לפלטפורמה היסטורית כמו Flirt4Free שבה המופעים יכולים להיות ארוכים.")]),
    _p("mfc-alerts", "MFC Alerts",
       "הוספת MFC Alerts לשידור עם SplitCam",
       "הציגו התראות טיפים מונפשות בשידור MyFreeCams — URL של mfcalerts.com כשכבת Browser ב-SplitCam החינמי, מעל המצלמה.",
       "mfc alerts, myfreecams alerts, הוספת mfc alerts, mfcalerts splitcam, myfreecams tip alerts, myfreecams alerts overlay",
       'איך להוסיף <span class="accent">MFC Alerts</span> לשידור שלכם',
       "הוספת MFC Alerts",
       "הציגו התראות טיפים מונפשות בשידור MyFreeCams.",
       "‏MFC Alerts מציג אפקטים מונפשים בשידור MyFreeCams שלכם בכל פעם שצופה שולח טיפ. הוא פועל כ<strong style='color:var(--text)'>שכבת Browser</strong> בתוך <strong style='color:var(--text)'>SplitCam</strong> החינמי — הגדירו פעם אחת והטיפים מפעילים תגובות על המסך בזמן אמת.",
       "הוספת MFC Alerts עם SplitCam: התקינו SplitCam, הוסיפו מצלמה, פתחו את לשונית Browser וטענו mfcalerts.com, העתיקו את ה-URL של ההתראות, הוסיפו כשכבת Browser מעל המצלמה, ואז בדקו עם טיפ בדיקה."
       "<ol><li>התקינו SplitCam.</li><li>הוסיפו מצלמה.</li><li>קבלו URL ב-mfcalerts.com.</li><li>הוסיפו כשכבת Browser מעל המצלמה.</li><li>שלחו טיפ בדיקה.</li></ol>",
       "ב-SplitCam פתחו את לשונית <strong>Browser</strong> ועברו ל-<strong>www.mfcalerts.com</strong>. התחברו או הירשמו. השתמשו ב-<strong>Copy to clipboard</strong> כדי להעתיק את ה-URL הפרטי של ההתראות. הדביקו את ה-URL בחלון ה-Browser של SplitCam ולחצו <strong>Add</strong>. ואז סדרו את רשימת המקורות כך ש<strong>MFC Alerts מעל המצלמה</strong> (תפריט 3 הנקודות → Move Up).",
       [("MFC Alerts חייב להיות מעל המצלמה", "הטעות הנפוצה ביותר: אם שכבת MFC Alerts מתחת למצלמה ברשימת המקורות, האפקט נשאר מוסתר. הזיזו אותו למעלה."),
        ("נדרש חשבון mfcalerts.com", "ה-URL של ההתראות פרטי — הירשמו תחילה ב-mfcalerts.com אם אין לכם חשבון."),
        ("שלחו טיפ בדיקה לפני הלייב", "השתמשו ב-Settings → Send test tip כדי לוודא שהשכבה עובדת — אל תגלו תקלה באמצע המופע."),
        _T_ETH],
       [("מה זה MFC Alerts?", "מערכת התראות ל-MyFreeCams שמציגה אפקטי וידאו בשידור שלכם כשצופים שולחים טיפים — נוסף כשכבת Browser ב-SplitCam."),
        ("למה ה-MFC Alerts שלי לא מופיע?", "כמעט תמיד זה סדר השכבות — שכבת ה-Browser של MFC Alerts חייבת להיות מעל המצלמה ברשימת המקורות של SplitCam."),
        ("האם צריך חשבון ל-MFC Alerts?", "כן — הירשמו ב-mfcalerts.com כדי לקבל את ה-URL הפרטי של ההתראות."),
        ("האם SplitCam חינמי לזה?", "כן — SplitCam חינמי, ללא סימן מים וללא הגבלת זמן, ושכבת הדפדפן של MFC Alerts פועלת בתוכו ללא עלות נוספת.")],
       steps=[
           ("התקינו SplitCam והוסיפו מצלמה", "התקינו SplitCam חינם ל-Windows או macOS, ואז הוסיפו <strong>מצלמה</strong> כמקור. MFC Alerts יושב כשכבה מעל המצלמה הזו."),
           ("פתחו את לשונית Browser ועברו ל-mfcalerts.com", "ב-SplitCam פתחו את לשונית <strong>Browser</strong> ועברו ל-<strong>www.mfcalerts.com</strong>. התחברו, או הירשמו אם עדיין אין לכם חשבון mfcalerts.com."),
           ("העתיקו את ה-URL של ההתראות", "ב-mfcalerts.com השתמשו ב-<strong>Copy to clipboard</strong> כדי להעתיק את ה-URL הפרטי של ההתראות — זה העמוד שמרנדר את אנימציות הטיפים."),
           ("הוסיפו את ה-URL כשכבת Browser — מעל המצלמה", "הדביקו את ה-URL בחלון ה-Browser של SplitCam ולחצו <strong>Add</strong>. ואז סדרו את רשימת המקורות כך ש<strong>MFC Alerts מעל המצלמה</strong> (תפריט 3 הנקודות → Move Up). אם מתחת, האפקט נשאר מוסתר."),
           ("בדקו עם טיפ בדיקה", "פתחו <strong>Settings → Send test tip</strong> וודאו שאפקט ההתראה מופיע מעל המצלמה. ואז שדרו רגיל ב-MyFreeCams — טיפים אמיתיים מפעילים כעת אנימציות."),
       ]),
    _p("lovense", "Lovense",
       "הוספת צעצועי Lovense לשידור עם SplitCam",
       "חברו צעצועי Lovense אינטראקטיביים לשידור קאם עם SplitCam בחינם — Lovense SplitCam Toolset, התראות טיפים על המסך, תגובות.",
       "הוספת lovense לשידור, lovense cam stream, lovense splitcam, lovense splitcam toolset, lovense interactive toy streaming",
       'איך להוסיף <span class="accent">צעצועי Lovense</span> לשידור',
       "הוספת צעצועי Lovense",
       "חברו צעצועי Lovense אינטראקטיביים לשידור הקאם שלכם.",
       "אתם מנהלים שידור קאם דרך <strong style='color:var(--text)'>SplitCam</strong> החינמי ומצמדים צעצוע <strong style='color:var(--text)'>Lovense</strong> שמגיב לטוקנים. Lovense מתעדת <strong style='color:var(--text)'>Lovense SplitCam Toolset</strong> רשמי, ו-SplitCam מציע תוסף Lovense רשמי — האינטגרציה נתמכת משני הצדדים.",
       "כדי להוסיף צעצועי Lovense לשידור: התקינו SplitCam ותוכנת Lovense, צמדו את הצעצוע, חברו את Lovense לפלטפורמת הקאם, הוסיפו את סטטוס Lovense כשכבת Browser ב-SplitCam, ואז שדרו רגיל."
       "<ol><li>התקינו SplitCam.</li><li>התקינו תוכנת Lovense וצמדו את הצעצוע.</li><li>חברו Lovense לאתר הקאם שלכם.</li><li>הוסיפו שכבת Lovense ב-SplitCam.</li><li>לחצו Go Live.</li></ol>",
       "התקינו Lovense Connect / Lovense Stream (אפליקציית הדסקטופ הרשמית). הדליקו את הצעצוע וצמדו דרך Bluetooth כך שהאפליקציה תציג מחובר. באפליקציית Lovense חברו את חשבון הקאם כך שהצעצוע יגיב לטוקנים / טיפים של צופים. Lovense מספקת URL של שכבה / ווידג'ט — הוסיפו כשכבת <strong>Browser</strong> בסצנת SplitCam.",
       [("השתמשו ב-Lovense SplitCam Toolset הרשמי", "‏Lovense מפרסמת toolset ייעודי ל-SplitCam עם מדריך התקנה משלו — מוסיף שכבות פעילות צעצוע והתראות טיפים שנבנו ל-SplitCam."),
        ("עדכנו את Lovense Cam Extension", "ה-toolset דורש את Lovense Cam Extension העדכני (30.1.4 ומעלה) — עדכנו לפני הלייב."),
        ("שמרו על הצעצוע טעון", "סוללה חלשה באמצע המופע הורסת את הצד האינטראקטיבי — טענו במלואו לפני הלייב."),
        ("בדקו תגובה לטוקנים", "שלחו טיפ בדיקה קטן כדי לוודא שהצעצוע מגיב לפני פתיחת החדר."),
        ("בדקו דרישות גרסה", "‏Lovense SplitCam Toolset דורש SplitCam 10.4.5 ומעלה. Lovense Cam Extension כולל רשמית את Chaturbate, Stripchat, BongaCams, MyFreeCams ו-CamSoda — לאתרים אחרים, השתמשו באינטגרציית Generic URL של Lovense.")],
       [("האם Lovense תומכת ב-SplitCam רשמית?", "כן — Lovense מתעדת «Lovense SplitCam Toolset» רשמי עם מדריך התקנה משלו, ו-SplitCam מציע תוסף Lovense רשמי. האינטגרציה נתמכת משני הצדדים."),
        ("האם הצעצוע מתחבר ישירות ל-SplitCam?", "לא — הצעצוע מצומד לאפליקציית Lovense; SplitCam מציג את שכבת Lovense ומשדר את המצלמה."),
        ("אילו אתרי קאם תומכים ב-Lovense?", "‏Lovense Cam Extension תומך רשמית ב-Chaturbate, Stripchat, BongaCams, MyFreeCams ו-CamSoda, עם תמיכה משתנה באחרים — בדקו את הרשימה העדכנית באפליקציית Lovense."),
        ("אפשר להציג טיפים אחרונים על המסך?", "כן — הוסיפו את ה-URL של ווידג'ט Lovense כשכבת Browser ב-SplitCam.")],
       steps=[
           ("התקינו SplitCam", "‏SplitCam היא תוכנת שידור חי חינמית ל-Windows ו-macOS — המקודד ששולח את הווידאו שלכם לפלטפורמת הקאם. התקינו אותה; ללא סימן מים."),
           ("התקינו תוכנת Lovense וצמדו את הצעצוע", "התקינו Lovense Connect / Lovense Stream (אפליקציית הדסקטופ הרשמית). הדליקו את הצעצוע וצמדו דרך Bluetooth כך שהאפליקציה תציג מחובר."),
           ("חברו Lovense לפלטפורמת הקאם", "באפליקציית Lovense חברו את חשבון הקאם כך שהצעצוע יגיב לטוקנים / טיפים של צופים. רוב פלטפורמות הקאם הגדולות נתמכות."),
           ("הוסיפו שכבת Lovense ב-SplitCam", "‏Lovense מספקת URL של שכבה / ווידג'ט. הוסיפו כשכבת <strong>Browser</strong> בסצנת SplitCam כך שהצופים יראו את סטטוס הצעצוע והטיפים האחרונים על המסך."),
           ("בנו סצנה ו-Go Live", "הוסיפו מצלמה ושכבות נוספות, הדביקו את מפתח ה-RTMP של פלטפורמת הקאם ל-SplitCam ולחצו <strong>Go Live</strong>. הצעצוע מגיב לטיפים בזמן אמת."),
       ]),
    _p("multistream-cams", "כמה אתרי קאם",
       "שידור לכמה אתרי קאם בו-זמנית עם SplitCam",
       "שדרו ל-MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat ועוד בו-זמנית עם המולטיסטרים החינמי של SplitCam. לחיצה אחת, ללא סימן מים.",
       "שידור לכמה אתרי קאם, multistream cam sites, שידור chaturbate ו-bongacams בו-זמנית, תוכנת מולטיסטרים קאם",
       'איך לשדר ל-<span class="accent">כמה אתרי קאם</span> בו-זמנית',
       "מולטיסטרים קאם",
       "שדרו לכמה אתרי קאם בו-זמנית.",
       "‏<strong style='color:var(--text)'>SplitCam</strong> החינמי יכול לשדר קידוד אחד ל<strong style='color:var(--text)'>כמה אתרי קאם בו-זמנית</strong> — MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat ועוד. ללא סימן מים, לחיצה אחת.",
       "כדי לשדר לכמה אתרי קאם בו-זמנית: התקינו SplitCam, בנו סצנה, קבלו URL שרת RTMP ומפתח שידור של כל אתר קאם, הוסיפו את כולם להגדרות המולטיסטרים של SplitCam, לחצו Go Live פעם אחת."
       "<ol><li>התקינו SplitCam.</li><li>הוסיפו מצלמה + סצנה.</li><li>קבלו מפתחות RTMP מכל אתר קאם.</li><li>הוסיפו את כל המפתחות למולטיסטרים של SplitCam.</li><li>לחצו Go Live פעם אחת.</li></ol>",
       "בכל פלטפורמת קאם הפעילו שידור חיצוני / RTMP והעתיקו <strong>URL שרת</strong> ו<strong>מפתח שידור</strong>. ב-SplitCam פתחו <strong>Stream Settings</strong> והוסיפו כל אתר קאם כיעד RTMP מותאם — הדביקו URL שרת ומפתח. סמנו את כל אלה שאתם רוצים לשדר אליהם. לחצו <strong>Go Live</strong>.",
       [("שימו לב להעלאה שלכם", "מולטיסטרים מכפיל את עומס ההעלאה. כל יעד משתמש בביטרייט משלו — ודאו שהקו שלכם נושא את הסכום."),
        ("בדקו את כללי הפלטפורמות", "חלק מאתרי הקאם אוסרים שידור בו-זמני במקום אחר — בדקו לפני מולטיסטרים."),
        ("כבל — כאן אסור שיפול", "מולטיסטרים מכפיל את עומס ההעלאה, כך שנפילת wi-fi אחת יכולה להפיל את כל היעדים בו-זמנית. כבל כאן אינו אופציה."),
        ("עקבו אחר מוניטור הבריאות", "‏SplitCam מציג סטטוס לכל יעד — נתקו אתר אחד אם ההעלאה לא עומדת בעומס.")],
       [("האם המולטיסטרים של SplitCam חינמי?", "כן — מולטיסטרים מובנה וחינמי, ללא תשלום ליעד, ללא סימן מים."),
        ("לכמה אתרי קאם אפשר לשדר בו-זמנית?", "לכמה שרוחב פס ההעלאה שלכם נושא — כל יעד משתמש בביטרייט משלו."),
        ("האם הוא משתמש ב-relay ענן?", "לא — SplitCam שולח את הזרם peer-to-peer ישירות מהמחשב ל-ingest של כל פלטפורמה."),
        ("האם מולטיסטרים מאט את המחשב שלי?", "הקידוד נעשה פעם אחת ומשמש מחדש; קידוד חומרה שומר על עומס CPU נמוך. רוחב פס ההעלאה הוא המגבלה האמיתית.")],
       steps=[
           ("התקינו SplitCam", "‏SplitCam היא תוכנת שידור חי חינמית ל-Windows ו-macOS עם מולטיסטרים מובנה. התקינו אותה — ללא סימן מים, ללא הרשמה."),
           ("הגדירו מצלמה וסצנה", "פתחו SplitCam, הוסיפו את המצלמה ובנו סצנה עם שכבות ומסננים. סצנה אחת מזינה כל יעד."),
           ("קבלו מפתחות RTMP מכל אתר קאם", "בכל פלטפורמת קאם הפעילו שידור חיצוני / RTMP והעתיקו <strong>URL שרת</strong> ו<strong>מפתח שידור</strong>. חזרו על כך לכל אתר שאתם רוצים לשדר אליו — ראו את המדריך של כל פלטפורמה לנתיב המדויק."),
           ("הוסיפו כל יעד ב-SplitCam", "פתחו <strong>Stream Settings</strong> והוסיפו כל אתר קאם כיעד RTMP מותאם — הדביקו URL שרת ומפתח. סמנו את כל אלה שאתם רוצים לשדר אליהם."),
           ("לחצו Go Live פעם אחת", "לחצו <strong>Go Live</strong>. SplitCam שולח את הזרם לכל אתר קאם נבחר בו-זמנית, peer-to-peer, מקידוד אחד — ללא עלות נוספת."),
       ]),
]
