# -*- coding: utf-8 -*-
"""Arabic (ar) content for cam-streaming-guides. RTL language."""

_T_ETH = ("استخدم اتصال سلكي", "الإيثرنت يتفوق على Wi-Fi في البث الطويل — إطار مفقود يعني إكرامية مفقودة. مدّ كابلاً إلى كمبيوتر البث.")
_T_TEST = ("قم باختبار خاص أولاً", "شغّل بثاً تجريبياً قصيراً للتحقق من الكاميرا والصوت والتأطير والتراكبات قبل فتح الغرفة للجمهور.")

def _p(slug, name, title, desc, kw, h1html, h1short, card, intro, quick, key_how, tips, faq, steps=None):
    d = {"slug": slug, "name": name, "title": title, "desc": desc, "kw": kw,
         "h1html": h1html, "h1short": h1short, "card": card, "intro": intro,
         "quick": quick, "key_how": key_how, "tips": tips, "faq": faq}
    if steps: d["steps"] = steps
    return d

PLATFORMS_AR = [
    _p("chaturbate", "Chaturbate",
       "البث على Chaturbate باستخدام SplitCam — Token & RTMP",
       "البث على Chaturbate مع SplitCam المجاني — broadcast token، RTMP، مشاهد متعددة الكاميرات وتراكبات. بدون علامة مائية.",
       "chaturbate بث, chaturbate broadcast token, chaturbate rtmp obs, chaturbate external encoder, chaturbate live",
       'كيفية البث على <span class="accent">Chaturbate</span> باستخدام SplitCam',
       "البث Chaturbate",
       "إعداد قائم على Token مع مُشفِّر خارجي على Chaturbate.",
       "Chaturbate هي إحدى أكبر منصات cam، مبنية على اقتصاد الرموز. مذيع المتصفح هو أداة مسطحة بكاميرا واحدة — التبديل إلى <strong style='color:var(--text)'>المُشفِّر الخارجي</strong> مع <strong style='color:var(--text)'>SplitCam</strong> المجاني يفتح مشاهد متعددة الكاميرات وتراكبات وفلاتر على نفس بث الرموز.",
       "البث على Chaturbate باستخدام SplitCam: ثبّت SplitCam، أنشئ المشهد، في Chaturbate افتح <em>Broadcast Yourself → My Broadcast</em>، انسخ broadcast token، الصقه في SplitCam، Go Live."
       "<ol><li>ثبّت SplitCam.</li><li>أضف الكاميرا + المشهد.</li><li>انسخ broadcast token من Chaturbate.</li><li>الصق في SplitCam.</li><li>اضغط Go Live.</li></ol>",
       "في Chaturbate انقر على <strong>Broadcast Yourself</strong> لصفحة <strong>My Broadcast</strong>، ثم <strong>View RTMP/OBS broadcast information and stream key</strong>. يظهر المفتاح كـ <strong>broadcast token</strong> — انسخه. تعامل معه ككلمة مرور؛ ليس عاماً أبداً.",
       [("Token هو المفتاح", "Chaturbate يستخدم broadcast token الخاص بك بدلاً من stream key عام. تعامل معه ككلمة مرور وأعد التعيين عند التسريب."),
        ("مساحة كبيرة", "Chaturbate RTMP ingest يقبل حتى 4K، 60 fps ومعدل بت عالٍ — الحد هو الرفع، وليس المنصة. Keyframe كل ثانيتين."),
        _T_ETH, _T_TEST],
       [("هل يسمح Chaturbate بـ OBS / مُشفِّرات خارجية؟", "نعم — Chaturbate يدعم المُشفِّرات الخارجية رسمياً مع مقاله الخاص «How do I set up OBS?». التفعيل عبر «Use External Encoder to Broadcast» في إعدادات البث."),
        ("أين stream key الخاص بـ Chaturbate؟", "Broadcast Yourself → My Broadcast → View RTMP/OBS broadcast information and stream key. المفتاح هو broadcast token."),
        ("ما معدل البت لـ Chaturbate؟", "3500–6000 Kbps في 1080p كافٍ. سقف Chaturbate مرتفع — الحد الفعلي هو الرفع؛ شغّل اختبار السرعة المدمج في SplitCam أولاً."),
        ("هل SplitCam مجاني لـ Chaturbate؟", "نعم — مجاني تماماً، بدون علامة مائية وبدون حد زمني: المُشفِّر لا يأكل أرباحك من الرموز.")]),
    _p("cam4", "CAM4",
       "البث على CAM4 باستخدام SplitCam — External Encoder",
       "البث على CAM4 مع SplitCam المجاني — External Encoder، stream key، حجب جغرافي وتراكبات. بدون علامة مائية.",
       "cam4 بث, cam4.com, cam4 external encoder, cam4 stream key, cam4 rtmp obs",
       'كيفية البث على <span class="accent">CAM4</span> باستخدام SplitCam',
       "البث CAM4",
       "External Encoder على CAM4 مع ضوابط جغرافية.",
       "CAM4 هي منصة cam-and-earn عالمية بضوابط جغرافية مدمجة — يمكنك إخفاء البث في بلدان مختارة. البث عبر <strong style='color:var(--text)'>SplitCam</strong> المجاني كمُشفِّر خارجي يفتح تبديل المشاهد والتراكبات التي لا يقدمها المذيع الأساسي.",
       "البث على CAM4 باستخدام SplitCam: ثبّت SplitCam، أنشئ المشهد، في CAM4 اذهب إلى <em>Broadcast &amp; Earn Money → Start Broadcast → External Encoder</em>، Get Stream Key، الصقه في SplitCam، Go Live."
       "<ol><li>ثبّت SplitCam.</li><li>أضف الكاميرا + المشهد.</li><li>احصل على stream key من CAM4.</li><li>الصق في SplitCam.</li><li>اضغط Go Live.</li></ol>",
       "في CAM4 انقر <strong>Broadcast</strong> → <strong>Broadcast &amp; Earn Money</strong> → <strong>Start Broadcast</strong>، ثم <strong>External Encoder</strong> في الأعلى. املأ تاريخ الميلاد والجنس والبلد، استخدم <strong>Get Stream Key</strong> وانسخه. شريط أخضر في Stream Settings SplitCam يؤكد الاتصال.",
       [("اضبط القيود الجغرافية", "CAM4 يسمح بإخفاء البث في دول ومناطق محددة — اضبط على جانب CAM4 قبل البث المباشر."),
        ("راقب الشريط الأخضر", "إعداد CAM4 يُظهر شريطاً أخضر في Stream Settings SplitCam عند قبول المفتاح — أحمر = تحقق من المفتاح."),
        ("معدل بت أقل من المعتاد", "CAM4 ingest يحد من معدل بت الفيديو عند حوالي 3000 Kbps — أقل من معظم مواقع cam. لا تدفع أعلى."),
        _T_ETH],
       [("هل CAM4 يدعم OBS / المُشفِّرات الخارجية رسمياً؟", "نعم — لدى CAM4 OBS Guide رسمي على موقع الدعم ويوصي بـ External Encoder للحصول على أفضل تجربة. SplitCam يستخدم نفس مسار RTMP."),
        ("هل يمكنني الحجب الجغرافي لبث CAM4؟", "نعم — لدى CAM4 تقييد جغرافي مدمج لإخفاء البث في بلدان معينة. اضبط في CAM4، ليس في SplitCam."),
        ("أين stream key الخاص بـ CAM4؟", "Broadcast → Broadcast & Earn Money → Start Broadcast → External Encoder → Get Stream Key."),
        ("ما معدل البت لـ CAM4؟", "أقل من المتوسط — CAM4 ingest يحد عند ~3000 Kbps عند 30 fps مع keyframe 1 ثانية. الجدول الرسمي يوصي بعدم تجاوز ~3000.")]),
    _p("bongacams", "BongaCams",
       "البث على BongaCams باستخدام SplitCam — External Encoder",
       "البث على BongaCams مع SplitCam المجاني — External Encoder، مشاهد متعددة الكاميرات، تراكبات وخلفية AI. بدون علامة مائية.",
       "bongacams, bongcams, bongacams بث, bongacams external encoder, bongacams rtmp obs",
       'كيفية البث على <span class="accent">BongaCams</span> باستخدام SplitCam',
       "البث BongaCams",
       "إعداد External Encoder لـ BongaCams.",
       "BongaCams هي منصة cam عالمية. البث عبر مُشفِّر خارجي ليس نشطاً دائماً — بمجرد تفعيله، يقود <strong style='color:var(--text)'>SplitCam</strong> المجاني البث بمشاهد متعددة الكاميرات وتراكبات وخلفية AI.",
       "البث على BongaCams باستخدام SplitCam: ثبّت SplitCam، أنشئ المشهد، في BongaCams اذهب إلى <em>Options → Broadcast settings → Select Encoder → External Encoder</em>، انسخ URL والمفتاح، الصقهما في SplitCam، Go Live."
       "<ol><li>ثبّت SplitCam.</li><li>أضف الكاميرا + المشهد.</li><li>احصل على URL والمفتاح من BongaCams.</li><li>الصق في SplitCam.</li><li>اضغط Go Live.</li></ol>",
       "في BongaCams افتح <strong>Options</strong> → <strong>Broadcast settings</strong> → <strong>Select Encoder</strong> → <strong>External Encoder</strong> وانسخ URL الخادم وstream key المعروض. <strong>إذا كان زر External Encoder مفقوداً</strong>، اتصل بدعم BongaCams واطلب تفعيل التشفير الخارجي على حسابك.",
       [("لا يوجد زر External Encoder؟ الدعم", "BongaCams يفعّل التشفير الخارجي لكل حساب — إذا كان الخيار مفقوداً من Broadcast settings، الدعم يفعّله."),
        ("طابق الدقة", "BongaCams يوصي بأن تتطابق دقة كاميرا الويب ودقة البث — مثلاً كلاهما 1280×720."),
        _T_ETH, _T_TEST],
       [("لماذا لا يظهر زر External Encoder في BongaCams؟", "التشفير الخارجي ليس نشطاً افتراضياً على كل حساب — اتصل بدعم BongaCams لتفعيله، وسيظهر الزر في Broadcast settings."),
        ("هل أحتاج للتحقق من حساب BongaCams؟", "نعم — البث يتطلب 18+، هوية رسمية للتحقق من العمر وموافقة الحساب قبل المباشر."),
        ("ما معدل البت لـ BongaCams؟", "BongaCams RTMP ingest يحد من معدل بت الفيديو عند حوالي 6000 Kbps مع keyframe 2 ثانية — 3500–6000 في 1080p هي المنطقة المثالية؛ اختبر الرفع أولاً."),
        ("هل SplitCam مجاني لـ BongaCams؟", "نعم — مجاني تماماً، بدون علامة مائية وبدون حد زمني، لذلك المُشفِّر لا يقلل من أرباحك من الرموز على BongaCams.")]),
    _p("stripchat", "Stripchat",
       "البث على Stripchat باستخدام SplitCam — Strip Cam Setup",
       "البث على Stripchat — منصة strip cam — مع SplitCam المجاني. برنامج خارجي، مفتاح token، مشاهد وتراكبات.",
       "strip cam, stripchat live stream, stripchat بث, stripchat external software, stripchat stream key, stripchat rtmp obs",
       'كيفية البث على <span class="accent">Stripchat</span> باستخدام SplitCam',
       "البث Stripchat",
       "إعداد برنامج خارجي لبث Stripchat.",
       "Stripchat هي منصة cam كبيرة مع تركيز على التفاعل. وضع <em>external software</em> يوفر لك مفتاحاً قائماً على token — ضعه في <strong style='color:var(--text)'>SplitCam</strong> المجاني للبث بمشاهد وتراكبات وفلاتر بدلاً من كاميرا مسطحة.",
       "البث على Stripchat باستخدام SplitCam: ثبّت SplitCam، أنشئ المشهد، في Stripchat اختر <em>Switch to external software</em>، انسخ stream key، الصقه في SplitCam، Go Live."
       "<ol><li>ثبّت SplitCam.</li><li>أضف الكاميرا + المشهد.</li><li>احصل على stream key من Stripchat.</li><li>الصق في SplitCam.</li><li>اضغط Go Live.</li></ol>",
       "في Stripchat اختر <strong>Switch to external software</strong>، ثم <strong>Show external software settings for the stream</strong>. انسخ stream key — Stripchat يعرضه كـ token. احتفظ به خاصاً.",
       [("طابق الدقة مع الموقع", "أسئلة Stripchat الشائعة تحذر: يجب أن تتطابق الدقة في برنامجك تماماً مع دقة الموقع، وإلا يصبح الفيديو متعرجاً. اضبط كليهما بشكل متماثل."),
        ("انتبه للحد الأدنى 2 Mbps", "Stripchat يدرج 2 Mbps رفعاً كحد أدنى — ويقول مباشرة إنه غير كافٍ لبث OBS أو متعدد البث. استهدف أعلى بكثير."),
        ("المفتاح هو token", "stream key الخاص بـ Stripchat هو token — انسخ بدقة، لا تشاركه أبداً، أعد التعيين عند التسريب."),
        _T_ETH],
       [("هل يوصي Stripchat بـ OBS / برنامج خارجي؟", "نعم — أسئلة Stripchat الشائعة الرسمية توصي ببرنامج بث خارجي مثل OBS «لتحقيق أفضل جودة فيديو وصوت». SplitCam يعمل بنفس الطريقة."),
        ("كيف أبدّل Stripchat إلى برنامج خارجي؟", "في Broadcast Center اختر Switch to External Broadcast Software (OBS)، ثم افتح external software settings للكشف عن stream key (token)."),
        ("ما معدل البت لـ Stripchat؟", "RTMP ingest يقبل حتى ~6000 Kbps مع keyframe 2 ثانية. 3500–6000 في 1080p مثالي — لكن يجب أن تكون فوق الحد الأدنى 2 Mbps بشكل ملحوظ، خاصة لبث OBS."),
        ("هل SplitCam مجاني لـ Stripchat؟", "نعم — بدون رسوم ترخيص، بدون علامة مائية، بدون حد زمني: حتى عروض Stripchat التفاعلية الطويلة لا تكلف شيئاً على جانب المُشفِّر.")]),
    _p("onlyfans", "OnlyFans",
       "البث المباشر على OnlyFans باستخدام SplitCam — تفويض أو مفتاح",
       "البث المباشر على OnlyFans مع SplitCam المجاني — تسجيل دخول عبر التفويض أو OBS Key، مشاهد متعددة الكاميرات، تراكبات. بدون علامة مائية.",
       "onlyfans مباشر, onlyfans live stream, onlyfans تفويض splitcam, onlyfans obs key, onlyfans streaming software",
       'كيف تبث مباشراً على <span class="accent">OnlyFans</span> باستخدام SplitCam',
       "Live OnlyFans",
       "فوّض مرة واحدة أو الصق المفتاح — مباشر على OnlyFans.",
       "OnlyFans live للمشتركين لديك. SplitCam يتصل بطريقتين — تسجل الدخول مرة واحدة بحساب OnlyFans وSplitCam يحصل على stream key تلقائياً ويبقيه متزامناً، أو تلصق OBS Key يدوياً. في كلتا الحالتين تبث بمشاهد متعددة الكاميرات وتراكبات وفلاتر.",
       "Live على OnlyFans مع SplitCam: ثبّت SplitCam، أنشئ المشهد، افتح Stream Settings &rarr; Add Channel &rarr; OnlyFans واختر <em>تفويض</em> — سجل الدخول بحساب OnlyFans، SplitCam يحصل على المفتاح تلقائياً — واضغط Go Live. مع الحساب المتصل يمكنك تغيير معلمات بث OnlyFans في SplitCam، دون فتح موقع OnlyFans.",
       "على OnlyFans: <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; قسم <strong>Other</strong>، انسخ <strong>OBS Key</strong>. أو استخدم خيار <strong>التفويض</strong> في SplitCam لتسجيل دخول الحساب — يتم الحصول على المفتاح تلقائياً وإبقاؤه متزامناً.",
       [("التفويض vs Stream Key", "طريقتان للاتصال: <strong>التفويض</strong> (تسجيل دخول مرة واحدة، يتم الحصول على المفتاح ومزامنته — أسهل طريق) أو <strong>Stream Key</strong> (انسخ OBS Key على OnlyFans → Profile → Settings → Other والصقه)."),
        ("غيّر الإعدادات دون مغادرة SplitCam", "مع التفويض يبقى الحساب متصلاً، لذا تضبط معلمات OnlyFans المباشرة من SplitCam أثناء البث أو بعده — دون المرور عبر موقع OnlyFans."),
        ("معدل بت متواضع", "OnlyFans RTMP ingest يحد من معدل بت الفيديو عند حوالي 2500 Kbps — أكثر صرامة من معظم مواقع cam. استهدف 720p–1080p عند ~2000–2500."),
        _T_ETH],
       [("كيف أربط OnlyFans بـ SplitCam؟", "بطريقتين. <strong>تفويض</strong> — Stream Settings → Add Channel → OnlyFans → سجل الدخول بحساب OnlyFans وSplitCam يحصل على المفتاح تلقائياً. أو <strong>Stream Key</strong> — انسخ OBS Key على OnlyFans → Profile → Settings → Other والصقه."),
        ("هل يمكنني تغيير إعدادات OnlyFans المباشرة دون فتح الموقع؟", "نعم — مع طريقة التفويض يبقى SplitCam متصلاً بحساب OnlyFans، لذا يتزامن المفتاح والإعدادات تلقائياً."),
        ("ما معدل البت لـ OnlyFans؟", "متواضع — OnlyFans RTMP ingest يحد من معدل البت عند حوالي 2500 Kbps، أكثر صرامة من منصات cam الأخرى. استهدف 720p–1080p حوالي 2000–2500 Kbps."),
        ("هل SplitCam مجاني لـ OnlyFans live؟", "نعم — مجاني، بدون علامة مائية وبدون حد زمني. لا توجد تكاليف على جانب المُشفِّر.")],
       steps=[
           ("قم بتنزيل وتثبيت SplitCam", "SplitCam هو برنامج بث مباشر مجاني لـ Windows وmacOS — بدون تسجيل، بدون بطاقة، بدون علامة مائية. إنه المُشفِّر الذي يرسل الفيديو الخاص بك إلى OnlyFans."),
           ("إعداد الكاميرا والمشهد", "افتح SplitCam وأضف كاميرا الويب. أنشئ المشهد بالطريقة التي تريد أن يراه بها المشاهدون — تراكبات، نصوص، كاميرا ثانية، مرشحات الجمال أو خلفية AI، كل شيء مطبق مباشراً."),
           ("الاتصال — الطريقة 1: التفويض (موصى به)", "في SplitCam افتح <strong>Stream Settings</strong> &rarr; <strong>Add Channel</strong> &rarr; <strong>OnlyFans</strong> واختر <strong>تفويض</strong>. سجل الدخول بـ Email وكلمة مرور OnlyFans. SplitCam يربط حسابك، يحصل على stream key تلقائياً ويبقيه متزامناً — ويتيح لك إدارة معلمات OnlyFans live داخل SplitCam، تغييرها أثناء البث أو بعده دون فتح موقع OnlyFans."),
           ("الاتصال — الطريقة 2: Stream Key (يدوياً)", "تفضل عدم تسجيل الدخول؟ استخدم المفتاح. على OnlyFans اذهب إلى <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; قسم <strong>Other</strong> وانسخ <strong>OBS Key</strong>. في SplitCam، Add Channel &rarr; OnlyFans، الصق في حقل المفتاح. هذا المفتاح ثابت — لتغيير الإعدادات لاحقاً ترجع إلى موقع OnlyFans."),
           ("Go Live", "أياً كانت الطريقة، اضغط <strong>Go Live</strong> في SplitCam. مع الطريقة 1 يمكنك الاستمرار في ضبط معلمات OnlyFans من SplitCam في الوقت الفعلي؛ مع الطريقة 2 يبقى المفتاح كما ضبطته."),
       ]),
    _p("camplace", "CamPlace",
       "البث على CamPlace باستخدام SplitCam — دليل مجاني",
       "البث على CamPlace مع SplitCam المجاني — مُشفِّر خارجي، مفتاح RTMP، مشاهد وتراكبات. خطوة بخطوة، بدون علامة مائية.",
       "camplace بث, camplace broadcasting software, camplace rtmp, camplace external encoder, camplace stream key",
       'كيفية البث على <span class="accent">CamPlace</span> باستخدام SplitCam',
       "البث CamPlace",
       "إعداد مُشفِّر خارجي لبث CamPlace.",
       "CamPlace هي منصة بث cam. لا توجد مقالة OBS عامة، لذا <strong style='color:var(--text)'>دليل الفيديو أعلاه</strong> هو مرجعك — <strong style='color:var(--text)'>SplitCam</strong> المجاني يتصل عبر RTMP قياسي ويضيف مشاهد وتراكبات وخلفية AI لا تقدمها الكاميرا الأساسية.",
       "البث على CamPlace مع SplitCam: ثبّت SplitCam، أنشئ المشهد، فعّل البث الخارجي/RTMP على CamPlace، انسخ URL الخادم وstream key، الصقهما في SplitCam، Go Live. اتبع الفيديو للمسار الحالي."
       "<ol><li>ثبّت SplitCam.</li><li>أضف الكاميرا + المشهد.</li><li>احصل على مفتاح RTMP من CamPlace.</li><li>الصق في SplitCam.</li><li>اضغط Go Live.</li></ol>",
       "سجل الدخول إلى CamPlace وافتح إعدادات البث. بدّل إلى خيار مُشفِّر خارجي / RTMP / OBS للكشف عن <strong>URL الخادم</strong> و<strong>stream key</strong>، انسخ كليهما. CamPlace لا ينشر وثائق OBS رسمية — <strong>الفيديو أعلاه</strong> هو المسار خطوة بخطوة الأكثر موثوقية عبر الواجهة الحالية.",
       [("لا يوجد دليل OBS رسمي — استخدم الفيديو", "CamPlace ليس لديها مقالة عامة عن المُشفِّرات الخارجية؛ الفيديو أعلاه هو المرجع للمسار الحالي."),
        ("RTMP القياسي يعمل", "رغم أنه غير موثق، CamPlace يقبل URL خادم RTMP قياسي ومفتاح — SplitCam يتصل كوجهة RTMP مخصصة."),
        _T_ETH, _T_TEST],
       [("هل CamPlace لديه دليل OBS رسمي؟", "لم يتم العثور على مقالة عامة عن المُشفِّرات الخارجية. CamPlace يقبل URL RTMP قياسي ومفتاح، لذا SplitCam يعمل — اتبع الفيديو."),
        ("هل CamPlace يدعم المُشفِّرات الخارجية؟", "نعم — يقبل stream key RTMP قياسي، لذا SplitCam يتصل كوجهة RTMP مخصصة."),
        ("ما معدل البت لـ CamPlace؟", "CamPlace لا ينشر رقماً رسمياً — استخدم 3500–6000 Kbps في 1080p كنطاق آمن ودع اختبار سرعة SplitCam يحدد سقفك الحقيقي."),
        ("هل SplitCam مجاني لـ CamPlace؟", "نعم — مجاني، بدون علامة مائية وبدون حد زمني. بما أن CamPlace لا يأتي بمُشفِّر خاص به، أداة RTMP مجانية تقوم بالعمل.")]),
    _p("camsoda", "CamSoda",
       "CamSoda live مع SplitCam — إعداد مجاني",
       "CamSoda live مع SplitCam المجاني — Use OBS Broadcaster، خوادم إقليمية، مشاهد وتراكبات. بدون علامة مائية.",
       "camsoda live, camsoda بث, camsoda obs broadcaster, camsoda rtmp obs, camsoda live broadcast",
       'كيفية البث على <span class="accent">CamSoda</span> باستخدام SplitCam',
       "البث CamSoda",
       "إعداد Use OBS Broadcaster على CamSoda.",
       "CamSoda هي منصة cam أمريكية معروفة بأشكال عروض تفاعلية وغير عادية. تدعم بث OBS رسمياً — هناك زر <strong style='color:var(--text)'>Use OBS Broadcaster</strong> على صفحة Go Live ودليل OBS رسمي على ويكي CamSoda. <strong style='color:var(--text)'>SplitCam</strong> المجاني يعمل بنفس الطريقة.",
       "البث على CamSoda مع SplitCam: ثبّت SplitCam، أنشئ المشهد، انقر على Use OBS Broadcaster في صفحة Go Live CamSoda، انسخ URL الخادم وstream key، الصقهما في SplitCam، Go Live."
       "<ol><li>ثبّت SplitCam.</li><li>أضف الكاميرا + المشهد.</li><li>انقر Use OBS Broadcaster على CamSoda.</li><li>الصق URL الخادم + المفتاح في SplitCam.</li><li>اضغط Go Live.</li></ol>",
       "في صفحة <strong>Go Live</strong> الخاصة بـ CamSoda انقر <strong>Use OBS Broadcaster</strong>. CamSoda يعرض URL خادم RTMP وstream key — انسخ كليهما. اختر الخادم الإقليمي (أمريكا الشمالية، أوروبا، آسيا إلخ) الأقرب إليك. ويكي CamSoda لديه دليل OBS كامل للتفاصيل.",
       [("تحقق من نفسك للإكراميات", "في CamSoda يمكن لأي شخص أن يبث، لكن لتلقي الإكراميات يجب إكمال عملية التحقق من CamSoda."),
        ("اختر الخادم الإقليمي الأقرب", "CamSoda يقدم خوادم ingest إقليمية — الأقرب (NA / أوروبا / آسيا / أمريكا الجنوبية / أوقيانوسيا) يقلل من زمن الاستجابة والإطارات المفقودة."),
        ("سقف عند 1080p / 30 fps", "CamSoda ingest يصل إلى حوالي 1080p، 30 fps و~6000 Kbps — لا تدفع أعلى."),
        _T_ETH],
       [("هل CamSoda يدعم OBS / المُشفِّرات الخارجية؟", "نعم — رسمياً. هناك زر Use OBS Broadcaster على صفحة Go Live ودليل OBS على ويكي CamSoda، لذا SplitCam يعمل."),
        ("هل أحتاج للتحقق من نفسي على CamSoda؟", "للبث، لا. لتلقي الإكراميات، نعم — CamSoda يتطلب إكمال عملية التحقق أولاً."),
        ("ما الدقة التي يدعمها CamSoda؟", "حتى 1920×1080 عند 30 fps، حوالي 6000 Kbps كحد أقصى على RTMP ingest."),
        ("هل SplitCam مجاني لـ CamSoda؟", "نعم — مجاني، بدون علامة مائية وبدون حد زمني. يعمل مع وضع Use OBS Broadcaster المجاني من CamSoda، لذا السلسلة بأكملها لا تكلف شيئاً.")]),
    _p("streamate", "Streamate",
       "البث على Streamate باستخدام SplitCam — قناة متكاملة",
       "البث على Streamate مع SplitCam المجاني — قناة متكاملة، مفتاح SM Connect، مشاهد وتراكبات. بدون علامة مائية.",
       "streamate, streamate sm connect, streamate بث, streamate broadcasting software, streamate rtmp",
       'كيفية البث على <span class="accent">Streamate</span> باستخدام SplitCam',
       "البث Streamate",
       "Streamate قناة متكاملة في SplitCam — إعداد سريع.",
       "Streamate هي منصة cam راسخة — وهي إحدى <strong style='color:var(--text)'>الوجهات المُعدّة مسبقاً في SplitCam</strong>، في قائمة القنوات، لذا الإعداد أسرع من إدخال RTMP يدوي: تختار Streamate، تلصق المفتاح، تم.",
       "البث على Streamate مع SplitCam: ثبّت SplitCam، أنشئ المشهد، في Streamate استخدم <em>SM Connect → Start Show</em> وانسخ المفتاح، ثم في SplitCam افتح <em>Stream Settings → Add Channel → Streamate</em> والصقه."
       "<ol><li>ثبّت SplitCam.</li><li>أضف الكاميرا + المشهد.</li><li>احصل على مفتاح Streamate عبر SM Connect.</li><li>Add Channel → Streamate في SplitCam.</li><li>اضغط Go Live.</li></ol>",
       "في Streamate افتح <strong>SM Connect</strong>، اقبل الشروط، انقر <strong>Start Show</strong> على اليسار وأغلق النافذة المفتوحة — ثم انسخ مفتاح البث. في SplitCam افتح <strong>Stream Settings</strong> → <strong>Add Channel</strong>، اختر <strong>Streamate</strong> من القائمة والصق المفتاح. شريط أخضر يؤكد الاتصال.",
       [("Streamate متكامل", "لا يوجد URL RTMP يدوي — SplitCam لديه Streamate في قائمة Add Channel؛ فقط اختر والصق المفتاح."),
        ("أغلق نافذة SM Connect", "بعد Start Show يفتح Streamate نافذة — أغلقها؛ كانت فقط للكشف عن مفتاح البث."),
        ("اقفل الدقة على 1080p", "حقل Video Resolution في SM Connect قد يقفز بصمت إلى 1440، وهو ما لا يتم تسليمه فعلياً ويقلل من جودتك بصمت — اضبط يدوياً على 1080p. معدل البت الذي ينخفض مع الصورة الثابتة طبيعي: بث Streamate تكيفي."),
        _T_ETH, _T_TEST],
       [("هل Streamate متكامل في SplitCam؟", "نعم — يظهر Streamate في قائمة Add Channel في SplitCam؛ تختار بدلاً من كتابة URL RTMP يدوياً."),
        ("أين مفتاح بث Streamate؟", "SM Connect → اقبل الشروط → Start Show → أغلق النافذة المنبثقة → انسخ المفتاح."),
        ("ما معدل البت لـ Streamate؟", "Streamate لا يضع سقفاً صارماً — 3500–6000 Kbps في 1080p يعمل بشكل جيد. البث تكيفي، لذا معدل البت الأقل في الصورة الثابتة طبيعي، ليس خطأ."),
        ("هل SplitCam مجاني لـ Streamate؟", "نعم — مجاني، بدون علامة مائية وبدون حد زمني؛ ولأن Streamate قناة متكاملة في SplitCam، لا توجد تكلفة مُشفِّر منفصلة.")]),
    _p("streamray", "StreamRay",
       "البث على StreamRay cam باستخدام SplitCam — URL الدردشة",
       "البث على StreamRay cam مع SplitCam المجاني — URL منشور في الدردشة، وضع OBS Broadcaster، مشاهد وتراكبات. بدون علامة مائية.",
       "streamray, streamray cam, streamray بث, streamray obs broadcaster, streamray rtmp",
       'كيفية البث على <span class="accent">StreamRay</span> باستخدام SplitCam',
       "البث StreamRay",
       "إعداد مُشفِّر خارجي URL-in-chat لـ StreamRay.",
       "StreamRay لديه إعداد مُشفِّر خارجي غير عادي — يسلم URL البث في <strong style='color:var(--text)'>نافذة دردشة البث</strong> ولا يستخدم stream key منفصل. <strong style='color:var(--text)'>SplitCam</strong> المجاني يتعامل مع هذا التدفق URL-only.",
       "البث على StreamRay مع SplitCam: ثبّت SplitCam، أنشئ المشهد، في StreamRay فعّل OBS Broadcaster، انسخ URL البث من نافذة الدردشة، الصقه في SplitCam (اترك حقل المفتاح فارغاً)، Go Live."
       "<ol><li>ثبّت SplitCam.</li><li>أضف الكاميرا + المشهد.</li><li>انسخ URL StreamRay من الدردشة.</li><li>الصق URL في SplitCam.</li><li>اضغط Go Live.</li></ol>",
       "في StreamRay انقر نقراً مزدوجاً على <strong>Broadcast Now</strong>، افتح قائمة <strong>Other</strong>، اختر <strong>OBS Broadcaster</strong> و<strong>Save and Close</strong>. ثم ينشر StreamRay <strong>URL البث في نافذة الدردشة</strong> — انسخه من هناك. اترك حقل stream key في SplitCam <strong>فارغاً</strong>؛ StreamRay يصادق فقط عبر URL.",
       [("URL في الدردشة", "StreamRay لا يعرض URL البث في مربع إعدادات — ينشره في نافذة دردشة البث. انسخه من هناك."),
        ("اترك حقل المفتاح فارغاً", "StreamRay لا يستخدم مفتاحاً منفصلاً — URL فقط. لا تضع شيئاً في حقل المفتاح في SplitCam."),
        _T_ETH, _T_TEST],
       [("أين URL بث StreamRay؟", "بعد تفعيل OBS Broadcaster، StreamRay ينشر URL في نافذة الدردشة — انسخ من الدردشة."),
        ("لماذا لا يوجد stream key على StreamRay؟", "StreamRay يصادق فقط عبر URL — اترك حقل المفتاح في SplitCam فارغاً."),
        ("ما معدل البت لـ StreamRay؟", "StreamRay لا يعلن عن سقف رسمي — استهدف 3500–6000 Kbps في 1080p وشغّل اختبار سرعة SplitCam، لأن تدفق URL-only لا يقدم تعليقات حول معدل البت."),
        ("هل SplitCam مجاني لـ StreamRay؟", "نعم — مجاني، بدون علامة مائية وبدون حد زمني، مما يتطابق مع تدفق URL-only الخاص بـ StreamRay: تلصق رابطاً وأنت مباشر.")]),
    _p("xlovecam", "XLoveCam",
       "البث على XLoveCam باستخدام SplitCam — رابط RTMP ومفتاح",
       "البث على XLoveCam مع SplitCam المجاني — رابط RTMP ومفتاح، خوادم إقليمية، مشاهد وتراكبات. بدون علامة مائية.",
       "xlovecam, x love cam, xlovecam بث, xlovecam rtmp link, xlovecam stream key",
       'كيفية البث على <span class="accent">XLoveCam</span> باستخدام SplitCam',
       "البث XLoveCam",
       "إعداد رابط RTMP + مفتاح لـ XLoveCam.",
       "XLoveCam هي منصة cam أوروبية متعددة اللغات. إعدادات الحساب تعرض كلاً من <strong style='color:var(--text)'>رابط RTMP</strong> و<strong style='color:var(--text)'>stream key</strong> — <strong style='color:var(--text)'>SplitCam</strong> المجاني يأخذ كليهما ويبث بمشاهد وتراكبات كاملة.",
       "البث على XLoveCam مع SplitCam: ثبّت SplitCam، أنشئ المشهد، في XLoveCam افتح <em>My Account → settings</em>، انسخ رابط RTMP وstream key، الصق كليهما في SplitCam، ابدأ العرض."
       "<ol><li>ثبّت SplitCam.</li><li>أضف الكاميرا + المشهد.</li><li>انسخ رابط RTMP + المفتاح من XLoveCam.</li><li>الصق كليهما في SplitCam.</li><li>اضغط Go Live.</li></ol>",
       "في XLoveCam افتح <strong>My Account</strong> → <strong>settings</strong>. تعرض الإعدادات كلاً من <strong>رابط RTMP</strong> و<strong>stream key</strong> — انسخ كليهما في حقول URL الخادم والمفتاح في SplitCam، ثم <strong>Start your show</strong> في XLoveCam.",
       [("انسخ الرابط والمفتاح", "XLoveCam يعطيك رابط RTMP ومفتاح stream منفصلاً — تحتاج كليهما في SplitCam، ليس واحداً فقط."),
        ("جمهور متعدد اللغات", "XLoveCam أوروبي ومتعدد اللغات — تراكب نص واضح بلغتك يساعد المشاهدين على إيجادك."),
        ("اختر الخادم الأقرب", "XLoveCam يقدم خوادم RTMP إقليمية — أوروبا وأمريكا الشمالية وأمريكا الجنوبية وآسيا. الأقرب يقلل من زمن الاستجابة والإطارات المفقودة."),
        _T_ETH],
       [("أين بيانات RTMP الخاصة بـ XLoveCam؟", "My Account → settings — يعرض كلاً من رابط RTMP والمفتاح."),
        ("هل XLoveCam يدعم المُشفِّرات الخارجية؟", "نعم — يوفر رابط RTMP ومفتاح، لذا SplitCam يعمل كمُشفِّر."),
        ("ما معدل البت لـ XLoveCam؟", "XLoveCam لا ينشر حداً ثابتاً؛ 3500–6000 Kbps في 1080p مثالي. اختيار الخادم الإقليمي الأقرب يهم بنفس القدر — يقلل من الإطارات المفقودة."),
        ("هل SplitCam مجاني لـ XLoveCam؟", "نعم — مجاني، بدون علامة مائية وبدون حد زمني. الوصول إلى جمهور XLoveCam الأوروبي متعدد اللغات لا يكلف برنامجاً.")]),
    _p("soulcams", "SoulCams",
       "البث على SoulCams باستخدام SplitCam — إعدادات OBS",
       "البث على SoulCams مع SplitCam المجاني — إعدادات OBS، خادم RTMP ومفتاح، مشاهد متعددة الكاميرات وتراكبات.",
       "soul cams, soulcams, soulcams بث, soulcams obs, soulcams rtmp, soulcams broadcast",
       'كيفية البث على <span class="accent">SoulCams</span> باستخدام SplitCam',
       "البث SoulCams",
       "إعدادات OBS لـ SoulCams.",
       "SoulCams هي منصة cam تعرض إعدادات OBS الخاصة بها <strong style='color:var(--text)'>خادم RTMP وstream key معاً</strong> في نافذة واحدة. الصق كليهما في <strong style='color:var(--text)'>SplitCam</strong> المجاني للبث بمشاهد متعددة الكاميرات وتراكبات.",
       "البث على SoulCams مع SplitCam: ثبّت SplitCam، أنشئ المشهد، في SoulCams انقر Go Online → Settings → OBS، انسخ الخادم والمفتاح، الصق كليهما في SplitCam، Go Live."
       "<ol><li>ثبّت SplitCam.</li><li>أضف الكاميرا + المشهد.</li><li>افتح SoulCams Settings → OBS.</li><li>الصق الخادم + المفتاح في SplitCam.</li><li>اضغط Go Live.</li></ol>",
       "في SoulCams سجل الدخول وانقر <strong>Go Online</strong>، ثم افتح <strong>Settings</strong> → <strong>OBS</strong>. تعرض نافذة OBS <strong>خادم RTMP</strong> و<strong>stream key</strong> معاً — انسخ كليهما في SplitCam.",
       [("الخادم والمفتاح جنباً إلى جنب", "SoulCams يعرض خادم RTMP والمفتاح في نفس نافذة OBS — تأخذ كليهما في خطوة واحدة."),
        ("Go Online أولاً", "تظهر إعدادات OBS فقط بعد النقر على Go Online في SoulCams — افعل ذلك قبل البحث عن بيانات المُشفِّر."),
        ("احجب المناطق غير المرغوب فيها", "SoulCams يسمح بالحجب الجغرافي من جانب العارضة — اختر البلدان التي لا يمكنها رؤية البث قبل الضغط على Go Online."),
        _T_ETH, _T_TEST],
       [("أين إعدادات OBS في SoulCams؟", "سجل الدخول، انقر Go Online، ثم Settings → OBS — يتم عرض خادم RTMP وstream key معاً."),
        ("هل SoulCams يدعم المُشفِّرات الخارجية؟", "نعم — إعدادات OBS تعطي خادم RTMP ومفتاح، لذا SplitCam يعمل."),
        ("ما معدل البت لـ SoulCams؟", "SoulCams لا يعطي رقماً رسمياً — استهدف 3500–6000 Kbps في 1080p واختبر الرفع، لأن نافذة OBS لا تعرض إرشادات معدل البت."),
        ("هل SplitCam مجاني لـ SoulCams؟", "نعم — مجاني، بدون علامة مائية وبدون حد زمني، لذا عرض SoulCams كامل بمشاهد متعددة الكاميرات وتراكبات لا يكلف شيئاً على جانب المُشفِّر.")]),
    _p("imlive", "ImLive",
       "البث على ImLive باستخدام SplitCam — كاميرا افتراضية",
       "إعداد Im Live stream مع SplitCam المجاني — ImLive يستخدم كاميرا الويب مباشرة (بدون RTMP)، اربط SplitCam ككاميرا افتراضية بمشاهد.",
       "im live stream, imlive splitcam, imlive بث, imlive كاميرا افتراضية, imlive webcam, im live cam",
       'كيفية استخدام <span class="accent">ImLive</span> مع SplitCam',
       "SplitCam على ImLive",
       "إعداد كاميرا افتراضية لـ ImLive — بدون RTMP.",
       "ImLive يستخدم كاميرا الويب مباشرة في المتصفح — <strong style='color:var(--text)'>لا يوجد RTMP ولا stream key</strong>. <strong style='color:var(--text)'>SplitCam</strong> المجاني يتصل كـ <strong style='color:var(--text)'>كاميرا افتراضية</strong>: تنشئ المشهد في SplitCam، ثم تختار SplitCam ككاميرا في ImLive.",
       "استخدام SplitCam مع ImLive: ثبّت SplitCam، أنشئ المشهد بطبقات الوسائط، افتح ImLive وابدأ محادثة فيديو، في إعدادات ImLive اختر SplitCam ككاميرا ويب وميكروفون."
       "<ol><li>ثبّت SplitCam.</li><li>أنشئ المشهد في SplitCam.</li><li>ابدأ محادثة فيديو على ImLive.</li><li>اختر SplitCam ككاميرا ImLive.</li><li>ابدأ المحادثة.</li></ol>",
       "سجل الدخول إلى موقع ImLive وانقر <strong>Start Video Chat</strong>، ثم افتح <strong>Go To Settings</strong> للوصول إلى خيارات الكاميرا والميكروفون. في إعدادات ImLive اختر <strong>SplitCam</strong> ككاميرا ويب وميكروفون.",
       [("لا حاجة لـ stream key", "ImLive لا يحتوي على RTMP — لا تبحث عن URL خادم أو مفتاح. SplitCam مختار فقط كجهاز كاميرا."),
        ("اضبط SplitCam كميكروفون أيضاً", "اختر SplitCam للميكروفون إلى جانب الكاميرا، حتى يدخل مزج الصوت وقمع الضوضاء أيضاً إلى البث المباشر."),
        ("أنشئ المشهد قبل البث المباشر", "ImLive يعرض ما يرسله SplitCam — رتب الطبقات قبل بدء المحادثة."),
        _T_TEST],
       [("هل ImLive يستخدم RTMP أم stream key؟", "لا — ImLive يستخدم كاميرا الويب مباشرة عبر المتصفح. SplitCam يتصل ككاميرا افتراضية، لا يوجد مفتاح للنسخ."),
        ("كيف أختار SplitCam على ImLive؟", "Start Video Chat → Go To Settings → اختر SplitCam ككاميرا ويب وميكروفون."),
        ("هل يمكنني استخدام التراكبات على ImLive؟", "نعم — أنشئها في مشهد SplitCam؛ ImLive يعرض النتيجة المركبة."),
        ("هل SplitCam مجاني لـ ImLive؟", "نعم — مجاني، بدون علامة مائية وبدون حد زمني. ككاميرا افتراضية لـ ImLive لا يضيف تكلفة أو علامة تجارية لمحادثة الفيديو الخاصة بك.")],
       steps=[
           ("ثبّت SplitCam", "SplitCam هو برنامج مجاني لـ Windows وmacOS. ثبّته — بدون علامة مائية، بدون تسجيل. لـ ImLive يعمل كـ <strong>كاميرا افتراضية</strong>، وليس كمُشفِّر RTMP."),
           ("أنشئ المشهد في SplitCam", "افتح SplitCam واستخدم <strong>Media Layers +</strong> لإضافة كاميرا الويب بالإضافة إلى أي تراكبات ونصوص ومرشحات أو خلفية AI. هذا المشهد المركب هو ما سيراه ImLive ككاميرتك."),
           ("ابدأ محادثة فيديو على ImLive", "سجل الدخول إلى موقع ImLive وانقر <strong>Start Video Chat</strong>، ثم افتح <strong>Go To Settings</strong> للوصول إلى خيارات الكاميرا والميكروفون."),
           ("اختر SplitCam ككاميرا", "في إعدادات ImLive اختر <strong>SplitCam</strong> ككاميرا ويب وميكروفون. ImLive يعرض الآن مشهد SplitCam الكامل بدلاً من كاميرا ويب مسطحة."),
           ("ابدأ Free Live Chat", "انقر <strong>Free Live Chat</strong> على ImLive للبث المباشر. لتغيير المظهر في منتصف الجلسة، حرر المشهد في SplitCam — ImLive يُحدّث على الفور."),
       ]),
    _p("vxlive", "VXLive",
       "البث على VXLive باستخدام SplitCam — دعم رسمي",
       "البث على VXLive (VXModels / VISIT-X) مع SplitCam المجاني — VISIT-X preset رسمي، خادم ومفتاح، مشاهد. بدون علامة مائية.",
       "vxlive, visit-x, vxmodels splitcam, vxlive بث, visit-x stream, vxlive rtmp",
       'كيفية البث على <span class="accent">VXLive</span> باستخدام SplitCam',
       "البث VXLive",
       "VXLive يدعم SplitCam رسمياً (VISIT-X preset).",
       "VXLive (VXModels / VISIT-X) هي منصة cam من السوق الألمانية — وإحدى المنصات القليلة التي <strong style='color:var(--text)'>تدعم SplitCam رسمياً بالاسم</strong>. لدى VXModels مقالة مساعدة مخصصة لربط <strong style='color:var(--text)'>SplitCam</strong> بـ VXLive، وSplitCam يوفر VISIT-X كقناة preset جاهزة.",
       "البث على VXLive مع SplitCam: ثبّت SplitCam، أنشئ المشهد، في VXLive اختر «Stream with third-party software»، انسخ URL الخادم والمفتاح، في SplitCam اختر VISIT-X preset والصقه، Go Live في SplitCam، ثم GO ONLINE على VXLive."
       "<ol><li>ثبّت SplitCam.</li><li>أضف الكاميرا + المشهد.</li><li>احصل على URL الخادم + المفتاح من VXLive.</li><li>اختر VISIT-X preset في SplitCam، الصق.</li><li>Go Live، ثم GO ONLINE على VXLive.</li></ol>",
       "في VXLive اختر <strong>Stream with third-party software</strong> واختر خيار <strong>OBS أو SplitCam أو XSplit</strong>. VXLive يوفر <strong>URL الخادم</strong> و<strong>stream key</strong>. في SplitCam اختر <strong>VISIT-X</strong> كمنصة بث، الصق كليهما، اضغط <strong>Go Live</strong> في SplitCam، ثم <strong>GO ONLINE</strong> على VXLive.",
       [("VISIT-X preset متكامل", "لا تدخل URL RTMP خام — SplitCam لديه VISIT-X في قائمة المنصات؛ فقط اختر والصق URL الخادم والمفتاح."),
        ("بث مباشر من خطوتين", "في VXLive اضغط Go Live في SplitCam أولاً، ثم GO ONLINE على VXLive — كلاهما بهذا الترتيب."),
        ("السوق الألمانية", "جمهور VXLive في الغالب ناطق بالألمانية — تراكب نص أو عنوان ألماني يساعد في التواصل مع المشاهدين."),
        _T_ETH],
       [("هل VXLive يدعم SplitCam رسمياً؟", "نعم — VXModels (VXLive) يحتفظ بمقالة مساعدة رسمية مخصصة لإعداد SplitCam ويسرد SplitCam جنباً إلى جنب مع OBS وXSplit كبرنامج بث مدعوم."),
        ("كيف أربط SplitCam بـ VXLive؟", "في VXLive تختار «Stream with third-party software»، ثم في SplitCam تختار VISIT-X preset وتلصق URL الخادم وstream key من VXLive."),
        ("هل أبث مباشراً في SplitCam أم على VXLive؟", "كلاهما — أولاً Go Live في SplitCam، ثم GO ONLINE على VXLive."),
        ("لماذا توصي VXModels بـ SplitCam؟", "مقالة المساعدة الرسمية من VXModels توصي بـ SplitCam على وجه التحديد للقضاء على عيوب صورة كاميرا الويب والتجزئة وتثبيت الاتصال — وليس فقط كمُشفِّر عام.")]),
    _p("virtwish", "VirtWish",
       "البث على VirtWish باستخدام SplitCam — URL البث والمفتاح",
       "البث على VirtWish مع SplitCam المجاني — Profile → Start Broadcast قسم OBS، URL البث ومفتاح، مشاهد وتراكبات.",
       "virtwish, virtwish بث, virtwish broadcasting software, virtwish rtmp, virtwish stream key, virtwish obs",
       'كيفية البث على <span class="accent">VirtWish</span> باستخدام SplitCam',
       "البث VirtWish",
       "إعداد URL البث + المفتاح لـ VirtWish.",
       "VirtWish هي منصة cam تفاعلية. إعدادات البث تعطيك <strong style='color:var(--text)'>URL البث وstream key منفصل</strong> في قسم OBS — <strong style='color:var(--text)'>SplitCam</strong> المجاني يأخذ كليهما ويدير العرض بمشاهد وتراكبات.",
       "البث على VirtWish مع SplitCam: ثبّت SplitCam، أنشئ المشهد، في VirtWish افتح <em>Profile → Start Broadcast</em> حتى قسم OBS، انسخ الرابط والمفتاح، الصق كليهما في SplitCam، Go Live."
       "<ol><li>ثبّت SplitCam.</li><li>أضف الكاميرا + المشهد.</li><li>احصل على URL + المفتاح من VirtWish.</li><li>الصق كليهما في SplitCam.</li><li>اضغط Go Live.</li></ol>",
       "في VirtWish انقر على رمز الزاوية اليمنى العليا → <strong>Profile</strong> → <strong>Start Broadcast</strong>، ثم <strong>Start Broadcast</strong> مرة أخرى للوصول إلى قسم OBS. <strong>انسخ الرابط من السطر الأول</strong> في حقل Stream URL في SplitCam، و<strong>Stream Key</strong> منفصلاً في حقل المفتاح.",
       [("الرابط على السطر الأول", "قسم OBS في VirtWish يضع URL البث على السطر الأول — انسخه إلى Stream URL في SplitCam، ثم المفتاح المنفصل."),
        ("نقرتان على Start Broadcast", "تنقر Start Broadcast مرتين على VirtWish للوصول إلى قسم OBS — متوقع، ليس خطأ."),
        _T_ETH, _T_TEST],
       [("أين بيانات RTMP الخاصة بـ VirtWish؟", "رمز أعلى اليمين → Profile → Start Broadcast مرتين → قسم OBS يعرض الرابط وstream key."),
        ("هل VirtWish يدعم المُشفِّرات الخارجية؟", "نعم — قسم OBS يوفر URL البث ومفتاح، لذا SplitCam يعمل."),
        ("ما معدل البت لـ VirtWish؟", "VirtWish لا ينشر سقفاً رسمياً؛ 3500–6000 Kbps في 1080p آمن. طابق دقة SplitCam مع المضبوطة في VirtWish لتجنب إعادة القياس."),
        ("هل SplitCam مجاني لـ VirtWish؟", "نعم — مجاني، بدون علامة مائية وبدون حد زمني. إعداد URL والمفتاح في VirtWish يكلف فقط الدقائق المطلوبة.")]),
    _p("xmodels", "XModels",
       "البث على XModels باستخدام SplitCam — دليل مجاني",
       "البث على XModels مع SplitCam المجاني — خيار المُشفِّر الخارجي في إعدادات حساب العارضة، مفتاح RTMP، مشاهد وتراكبات.",
       "xmodels, xmodels بث, xmodels broadcasting software, xmodels rtmp, xmodels external encoder",
       'كيفية البث على <span class="accent">XModels</span> باستخدام SplitCam',
       "البث XModels",
       "إعداد المُشفِّر الخارجي لبث XModels.",
       "XModels هي منصة بث cam بـ <strong style='color:var(--text)'>خيار مُشفِّر خارجي</strong> مدمج في إعدادات حساب العارضة. <strong style='color:var(--text)'>SplitCam</strong> المجاني يبث هناك بمشاهد متعددة الكاميرات وتراكبات ومرشحات بدلاً من كاميرا مسطحة واحدة.",
       "البث على XModels مع SplitCam: ثبّت SplitCam، أنشئ المشهد، في حساب عارضة XModels فعّل خيار المُشفِّر الخارجي، انسخ URL الخادم وstream key، الصقهما في SplitCam، Go Live."
       "<ol><li>ثبّت SplitCam.</li><li>أضف الكاميرا + المشهد.</li><li>فعّل المُشفِّر الخارجي في إعدادات XModels.</li><li>الصق URL الخادم + المفتاح في SplitCam.</li><li>اضغط Go Live.</li></ol>",
       "في <strong>إعدادات حساب العارضة</strong> في XModels، فعّل خيار <strong>البث عبر مُشفِّر خارجي</strong>. XModels يوفر <strong>stream key</strong> — انسخه إلى SplitCam. إذا لم يكن الخيار في المكان الذي تتوقعه، فإن دعم XModels عبر دردشة الأسئلة الشائعة على الموقع و<strong>info@xmodels.com</strong>؛ الفيديو أعلاه يعرضه أيضاً.",
       [("إنه في إعدادات الحساب", "XModels يضع خيار المُشفِّر الخارجي في إعدادات حساب العارضة، وليس على شاشة بث منفصلة."),
        ("الدعم: دردشة + بريد إلكتروني", "XModels ليس لديه مركز مساعدة عام كبير — دردشة الأسئلة الشائعة على الموقع وinfo@xmodels.com هي قنوات الدعم الرسمية."),
        ("كدّس التراكبات في SplitCam", "أهداف الإكراميات والاسم ومقابض التواصل الاجتماعي كطبقات مشهد — كاميرا XModels الأساسية لا تضيف مثل هذه."),
        _T_ETH],
       [("هل XModels يدعم المُشفِّرات الخارجية؟", "نعم — إعدادات حساب العارضة تتضمن خيار بث مُشفِّر خارجي يوفر stream key، لذا SplitCam يعمل."),
        ("أين أحصل على مساعدة XModels؟", "دعم XModels عبر دردشة الأسئلة الشائعة على الموقع وبريد info@xmodels.com — لا يوجد مركز مساعدة عام كبير."),
        ("ما معدل البت لـ XModels؟", "XModels لا يوثق رقماً رسمياً — استخدم 3500–6000 Kbps في 1080p وشغّل اختبار سرعة SplitCam، لأن دعم XModels مجرد دردشة وبريد إلكتروني."),
        ("هل SplitCam مجاني لـ XModels؟", "نعم — مجاني، بدون علامة مائية وبدون حد زمني، لذا البث إلى شبكة XModels الأوروبية لا يضيف تكلفة برنامج.")]),
    _p("flirt4free", "Flirt4Free",
       "البث على Flirt for Free cam باستخدام SplitCam — دليل مجاني",
       "البث على Flirt for Free cam مع SplitCam المجاني — External Broadcast Form، RTMP URL وStream Name، مشاهد وتراكبات.",
       "flirt for free cam, flirt 4 free cam, flirt4free, flirt4free بث, flirt4free external broadcast, flirt4free rtmp",
       'كيفية البث على <span class="accent">Flirt4Free</span> باستخدام SplitCam',
       "البث Flirt4Free",
       "إعداد External Broadcast Form لـ Flirt4Free.",
       "Flirt4Free هي إحدى أقدم منصات cam، تبث منذ التسعينيات. تدعم البث الخارجي رسمياً عبر <strong style='color:var(--text)'>External Broadcast Form</strong> — <strong style='color:var(--text)'>SplitCam</strong> المجاني يرسل البث بينما يضبط النموذج الدقة ومعدل البت.",
       "البث على Flirt4Free مع SplitCam: ثبّت SplitCam، أنشئ المشهد، افتح Flirt4Free External Broadcast Form، انسخ RTMP URL وStream Name واضبط الدقة/معدل البت، الصق في SplitCam، Go Live."
       "<ol><li>ثبّت SplitCam.</li><li>أضف الكاميرا + المشهد.</li><li>افتح Flirt4Free External Broadcast Form.</li><li>الصق RTMP URL + Stream Name في SplitCam.</li><li>اضغط Go Live.</li></ol>",
       "في منطقة عارضة Flirt4Free افتح <strong>External Broadcast Form</strong>. على عكس معظم مواقع cam، Flirt4Free يعطيك <strong>RTMP URL</strong> و<strong>Stream Name</strong> (وليس «مفتاحاً»)، بالإضافة إلى حقول الدقة ومعدل البت التي تملأها في النموذج نفسه. انسخ URL وStream Name في حقول الخادم والمفتاح في SplitCam.",
       [("إنه Stream Name، وليس مفتاحاً", "Flirt4Free يسمي بيانات الاعتماد Stream Name. تلصقه في حقل stream key في SplitCam — نفس الدور."),
        ("اضبط الدقة/معدل البت في النموذج", "External Broadcast Form الخاص بـ Flirt4Free لديه حقول دقة ومعدل بت خاصة به — قم بمحاذاتها مع إعدادات SplitCam حتى لا يتم إعادة قياس الصورة."),
        ("منصة تاريخية", "Flirt4Free يعمل منذ التسعينيات — أدوات العارضة ناضجة، وExternal Broadcast Form جزء موثق منها."),
        _T_ETH],
       [("هل Flirt4Free يدعم المُشفِّرات الخارجية؟", "نعم — رسمياً، عبر External Broadcast Form، الذي يوفر RTMP URL وStream Name. SplitCam يعمل كمُشفِّر."),
        ("من أين أحصل على بيانات RTMP الخاصة بـ Flirt4Free؟", "من External Broadcast Form في منطقة العارضة — يعرض RTMP URL وStream Name وحقول الدقة/معدل البت."),
        ("ما معدل البت لـ Flirt4Free؟", "3500–6000 Kbps في 1080p — اضبط نفس القيمة في External Broadcast Form وفي SplitCam."),
        ("هل SplitCam مجاني لـ Flirt4Free؟", "نعم — مجاني، بدون علامة مائية وبدون حد زمني، مما يتطابق مع منصة تاريخية مثل Flirt4Free حيث يمكن أن تكون العروض طويلة.")]),
    _p("mfc-alerts", "MFC Alerts",
       "إضافة MFC Alerts إلى البث باستخدام SplitCam",
       "عرض تنبيهات إكرامية متحركة في بث MyFreeCams — mfcalerts.com URL كطبقة Browser في SplitCam المجاني، فوق كاميرا الويب.",
       "mfc alerts, myfreecams alerts, إضافة mfc alerts, mfcalerts splitcam, myfreecams tip alerts, myfreecams alerts overlay",
       'كيفية إضافة <span class="accent">MFC Alerts</span> إلى البث',
       "إضافة MFC Alerts",
       "عرض تنبيهات إكرامية متحركة في بث MyFreeCams.",
       "MFC Alerts يعرض تأثيرات متحركة في بث MyFreeCams الخاص بك في كل مرة يرسل فيها مشاهد إكرامية. يعمل كـ <strong style='color:var(--text)'>طبقة Browser</strong> داخل <strong style='color:var(--text)'>SplitCam</strong> المجاني — تضبط مرة واحدة والإكراميات تشغل تفاعلات على الشاشة مباشراً.",
       "إضافة MFC Alerts باستخدام SplitCam: ثبّت SplitCam، أضف كاميرا الويب، افتح علامة تبويب Browser وحمّل mfcalerts.com، انسخ URL التنبيهات، أضفه كطبقة Browser فوق كاميرا الويب، ثم اختبر بإكرامية اختبار."
       "<ol><li>ثبّت SplitCam.</li><li>أضف كاميرا الويب.</li><li>احصل على URL من mfcalerts.com.</li><li>أضفه كطبقة Browser فوق كاميرا الويب.</li><li>أرسل إكرامية اختبار.</li></ol>",
       "في SplitCam افتح علامة تبويب <strong>Browser</strong> وانتقل إلى <strong>www.mfcalerts.com</strong>. سجل الدخول أو سجل. استخدم <strong>Copy to clipboard</strong> لنسخ URL التنبيهات الشخصي. الصق URL في نافذة Browser في SplitCam وانقر <strong>Add</strong>. ثم أعد ترتيب قائمة المصادر بحيث يكون <strong>MFC Alerts فوق كاميرا الويب</strong> (قائمة 3 نقاط → Move Up).",
       [("MFC Alerts يجب أن يكون فوق كاميرا الويب", "الخطأ الأكثر شيوعاً: إذا كانت طبقة MFC Alerts أسفل كاميرا الويب في قائمة المصادر، تبقى التأثيرات مخفية. حركها لأعلى."),
        ("حساب mfcalerts.com مطلوب", "URL التنبيهات شخصي — سجل في mfcalerts.com أولاً إذا لم يكن لديك حساب."),
        ("أرسل إكرامية اختبار قبل البث المباشر", "استخدم Settings → Send test tip لتأكيد أن التراكب يعمل — لا تكتشف الخطأ في منتصف العرض."),
        _T_ETH],
       [("ما هو MFC Alerts؟", "نظام إشعارات لـ MyFreeCams يعرض تأثيرات فيديو في بثك عندما يرسل المشاهدون إكراميات — يُضاف كتراكب Browser في SplitCam."),
        ("لماذا لا تظهر MFC Alerts الخاصة بي؟", "ترتيب الطبقات تقريباً دائماً — طبقة MFC Alerts Browser يجب أن تكون فوق كاميرا الويب في قائمة مصادر SplitCam."),
        ("هل أحتاج حساباً لـ MFC Alerts؟", "نعم — سجل في mfcalerts.com للحصول على URL التنبيهات الشخصي."),
        ("هل SplitCam مجاني لهذا؟", "نعم — SplitCam مجاني، بدون علامة مائية وبدون حد زمني، وتراكب browser الخاص بـ MFC Alerts يعمل بداخله دون تكلفة إضافية.")],
       steps=[
           ("ثبّت SplitCam وأضف كاميرا الويب", "ثبّت SplitCam المجاني لـ Windows أو macOS، ثم أضف <strong>كاميرا الويب</strong> كمصدر. MFC Alerts تجلس كطبقة فوق هذه الكاميرا."),
           ("افتح علامة تبويب Browser واذهب إلى mfcalerts.com", "في SplitCam افتح علامة تبويب <strong>Browser</strong> وانتقل إلى <strong>www.mfcalerts.com</strong>. سجل الدخول، أو سجل إذا لم يكن لديك حساب mfcalerts.com بعد."),
           ("انسخ URL التنبيهات", "على mfcalerts.com استخدم <strong>Copy to clipboard</strong> لنسخ URL التنبيهات الشخصي — إنها الصفحة التي تعرض رسوم متحركة للإكراميات."),
           ("أضف URL كطبقة Browser — فوق كاميرا الويب", "الصق URL في نافذة Browser في SplitCam وانقر <strong>Add</strong>. ثم أعد ترتيب قائمة المصادر بحيث يكون <strong>MFC Alerts فوق كاميرا الويب</strong> (قائمة 3 نقاط → Move Up). إذا كانت أسفل، تبقى التأثيرات مخفية."),
           ("اختبر بإكرامية اختبار", "افتح <strong>Settings → Send test tip</strong> وأكد ظهور تأثير التنبيه فوق كاميرتك. ثم ابث بشكل طبيعي على MyFreeCams — الإكراميات الحقيقية الآن تشغل الرسوم المتحركة."),
       ]),
    _p("lovense", "Lovense",
       "إضافة لعبة Lovense إلى البث باستخدام SplitCam",
       "توصيل لعبة Lovense تفاعلية ببث cam مع SplitCam المجاني — Lovense SplitCam Toolset، تنبيهات إكرامية على الشاشة، تفاعلات.",
       "إضافة lovense إلى البث, lovense cam stream, lovense splitcam, lovense splitcam toolset, lovense interactive toy streaming",
       'كيفية إضافة <span class="accent">لعبة Lovense</span> إلى البث',
       "إضافة لعبة Lovense",
       "وصّل لعبة Lovense تفاعلية ببث cam.",
       "تشغل بث cam الخاص بك عبر <strong style='color:var(--text)'>SplitCam</strong> المجاني وتقرن لعبة <strong style='color:var(--text)'>Lovense</strong> تتفاعل مع الرموز. Lovense يوثق <strong style='color:var(--text)'>Lovense SplitCam Toolset</strong> رسمياً، وSplitCam يوفر مكون Lovense الإضافي الرسمي — التكامل مدعوم من الجانبين.",
       "لإضافة لعبة Lovense إلى البث: ثبّت SplitCam وبرنامج Lovense، اقرن اللعبة، اربط Lovense بمنصة cam، أضف حالة Lovense كطبقة Browser في SplitCam، ثم ابث بشكل طبيعي."
       "<ol><li>ثبّت SplitCam.</li><li>ثبّت برنامج Lovense واقرن اللعبة.</li><li>اربط Lovense بموقع cam.</li><li>أضف تراكب Lovense في SplitCam.</li><li>اضغط Go Live.</li></ol>",
       "ثبّت Lovense Connect / Lovense Stream (التطبيق الرسمي لسطح المكتب). شغّل اللعبة وأقرنها عبر Bluetooth بحيث يعرض التطبيق متصلاً. في تطبيق Lovense اربط حساب cam الخاص بك بحيث تتفاعل اللعبة مع رموز/إكراميات المشاهدين. Lovense يوفر URL تراكب/أداة — أضفه كطبقة <strong>Browser</strong> في مشهد SplitCam.",
       [("استخدم Lovense SplitCam Toolset الرسمي", "Lovense ينشر toolset مخصصاً لـ SplitCam بدليل تثبيت خاص به — يضيف تراكب نشاط اللعبة وتنبيهات إكرامية مصنوعة لـ SplitCam."),
        ("حدّث Lovense Cam Extension", "يتطلب toolset Lovense Cam Extension حديث (30.1.4 أو أحدث) — حدّث قبل البث المباشر."),
        ("أبقِ اللعبة مشحونة", "بطارية شبه فارغة في منتصف العرض تقتل الجانب التفاعلي — اشحن بالكامل قبل البث المباشر."),
        ("اختبر التفاعل مع الرموز", "أرسل إكرامية اختبار صغيرة لتأكيد أن اللعبة تتفاعل قبل فتح الغرفة."),
        ("تحقق من متطلبات الإصدار", "Lovense SplitCam Toolset يتطلب SplitCam 10.4.5 أو أحدث. Lovense Cam Extension يغطي رسمياً Chaturbate وStripchat وBongaCams وMyFreeCams وCamSoda — لأي موقع آخر، استخدم تكامل Generic URL من Lovense.")],
       [("هل Lovense يدعم SplitCam رسمياً؟", "نعم — Lovense يوثق «Lovense SplitCam Toolset» رسمياً بدليل تثبيت خاص به، وSplitCam يوفر مكون Lovense الإضافي الرسمي. التكامل مدعوم من الجانبين."),
        ("هل تتصل اللعبة مباشرة بـ SplitCam؟", "لا — تقترن اللعبة بتطبيق Lovense؛ SplitCam يعرض تراكب Lovense ويبث الكاميرا."),
        ("ما مواقع cam التي تدعم Lovense؟", "Lovense Cam Extension يدعم رسمياً Chaturbate وStripchat وBongaCams وMyFreeCams وCamSoda، بدعم متغير للآخرين — تحقق من القائمة الحالية في تطبيق Lovense."),
        ("هل يمكنني عرض الإكراميات الأخيرة على الشاشة؟", "نعم — أضف URL أداة Lovense كطبقة Browser في SplitCam.")],
       steps=[
           ("ثبّت SplitCam", "SplitCam هو برنامج بث مجاني لـ Windows وmacOS — المُشفِّر الذي يرسل الفيديو الخاص بك إلى منصة cam. ثبّته؛ بدون علامة مائية."),
           ("ثبّت برنامج Lovense واقرن اللعبة", "ثبّت Lovense Connect / Lovense Stream (التطبيق الرسمي لسطح المكتب). شغّل اللعبة وأقرنها عبر Bluetooth بحيث يعرض التطبيق متصلاً."),
           ("اربط Lovense بمنصة cam", "في تطبيق Lovense اربط حساب cam الخاص بك بحيث تتفاعل اللعبة مع رموز/إكراميات المشاهدين. معظم منصات cam الرئيسية مدعومة."),
           ("أضف تراكب Lovense في SplitCam", "Lovense يوفر URL تراكب/أداة. أضفه كطبقة <strong>Browser</strong> في مشهد SplitCam بحيث يرى المشاهدون حالة اللعبة والإكراميات الأخيرة على الشاشة."),
           ("أنشئ المشهد وGo Live", "أضف الكاميرا والتراكبات الأخرى، الصق مفتاح RTMP لمنصة cam في SplitCam وانقر <strong>Go Live</strong>. تتفاعل اللعبة مع الإكراميات في الوقت الفعلي."),
       ]),
    _p("multistream-cams", "مواقع cam متعددة",
       "البث على مواقع cam متعددة في وقت واحد باستخدام SplitCam",
       "البث على MyFreeCams وChaturbate وBongaCams وCAM4 وStripchat والمزيد في وقت واحد مع البث المتعدد المجاني لـ SplitCam. نقرة واحدة، بدون علامة مائية.",
       "البث على مواقع cam متعددة, multistream cam sites, البث على chaturbate وbongacams في وقت واحد, multistream cam برنامج",
       'كيفية البث على <span class="accent">مواقع cam متعددة</span> في وقت واحد',
       "بث Cam متعدد",
       "البث على مواقع cam متعددة في وقت واحد.",
       "<strong style='color:var(--text)'>SplitCam</strong> المجاني يمكنه بث ترميز واحد إلى <strong style='color:var(--text)'>مواقع cam متعددة في وقت واحد</strong> — MyFreeCams وChaturbate وBongaCams وCAM4 وStripchat والمزيد. بدون علامة مائية، نقرة واحدة.",
       "للبث على مواقع cam متعددة دفعة واحدة: ثبّت SplitCam، أنشئ المشهد، احصل على URL خادم RTMP وstream key لكل موقع cam، أضف الجميع في إعدادات البث المتعدد لـ SplitCam، انقر Go Live مرة واحدة."
       "<ol><li>ثبّت SplitCam.</li><li>أضف الكاميرا + المشهد.</li><li>احصل على مفتاح RTMP من كل موقع cam.</li><li>أضف جميع المفاتيح في SplitCam multistream.</li><li>اضغط Go Live مرة واحدة.</li></ol>",
       "على كل منصة cam فعّل البث الخارجي / RTMP وانسخ <strong>URL الخادم</strong> و<strong>stream key</strong>. في SplitCam افتح <strong>Stream Settings</strong> وأضف كل موقع cam كوجهة RTMP مخصصة — الصق URL الخادم والمفتاح. تحقق من كل ما تريد بثه مباشراً. اضغط <strong>Go Live</strong>.",
       [("راقب الرفع الخاص بك", "البث المتعدد يضاعف حمل الرفع. كل وجهة تستهلك معدل البت الخاص بها — تأكد من أن اتصالك يمكنه التعامل مع المجموع."),
        ("تحقق من قواعد المنصة", "بعض مواقع cam تحظر البث في وقت واحد في مكان آخر — أكد قبل البث المتعدد."),
        ("كابل — لا يمكنك تحمل الإسقاطات هنا", "البث المتعدد يضاعف حمل الرفع، لذا إسقاط wi-fi واحد يمكن أن يطيح بجميع الوجهات في وقت واحد. الكابل ليس اختيارياً هنا."),
        ("راقب مراقب الصحة", "SplitCam يعرض الحالة لكل وجهة — أسقط موقعاً إذا كان الرفع لا يستطيع التعامل معه.")],
       [("هل البث المتعدد لـ SplitCam مجاني؟", "نعم — البث المتعدد مدمج ومجاني، لا توجد رسوم لكل وجهة، لا توجد علامة مائية."),
        ("كم عدد مواقع cam التي يمكنني البث إليها في وقت واحد؟", "بقدر ما يستطيع عرض النطاق الترددي للرفع التعامل معه — كل وجهة تستهلك معدل البت الخاص بها."),
        ("هل يستخدم cloud relay؟", "لا — SplitCam يرسل البثات نظير إلى نظير مباشرة من الكمبيوتر إلى ingest كل منصة."),
        ("هل البث المتعدد يبطئ الكمبيوتر؟", "الترميز يتم مرة واحدة ويُعاد استخدامه؛ الترميز بالأجهزة يبقي حمل وحدة المعالجة المركزية منخفضاً. عرض النطاق الترددي للرفع هو الحد الفعلي.")],
       steps=[
           ("ثبّت SplitCam", "SplitCam هو برنامج بث مجاني لـ Windows وmacOS مع بث متعدد مدمج. ثبّته — بدون علامة مائية، بدون تسجيل."),
           ("اضبط الكاميرا والمشهد", "افتح SplitCam، أضف كاميرا الويب وأنشئ المشهد بالتراكبات والمرشحات. مشهد واحد يغذي كل وجهة."),
           ("احصل على مفتاح RTMP من كل موقع cam", "على كل منصة cam فعّل البث الخارجي / RTMP وانسخ <strong>URL الخادم</strong> و<strong>stream key</strong>. كرر لكل موقع تريد البث إليه — انظر أدلة المنصات الفردية للمسارات الدقيقة."),
           ("أضف كل وجهة في SplitCam", "افتح <strong>Stream Settings</strong> وأضف كل موقع cam كوجهة RTMP مخصصة — الصق URL الخادم والمفتاح. تحقق من كل ما تريد بثه مباشراً."),
           ("انقر Go Live مرة واحدة", "اضغط <strong>Go Live</strong>. SplitCam يرسل البث إلى كل موقع cam مختار في وقت واحد، نظير إلى نظير، من ترميز واحد — بدون رسوم إضافية."),
       ]),
]
