# -*- coding: utf-8 -*-
"""Hindi (hi) content for cam-streaming-guides. Native Hindi (Devanagari), 19 platforms."""

_T_ETH = ("वायर्ड कनेक्शन का उपयोग करें", "लंबे लाइव के दौरान Ethernet, Wi-Fi से बेहतर है — "
          "खोए हुए फ्रेम का मतलब खोई हुई टिप्स है। स्ट्रीमिंग PC से केबल कनेक्ट करें।")
_T_TEST = ("पहले एक प्राइवेट टेस्ट करें", "दर्शकों के लिए रूम खोलने से पहले कैमरा, ऑडियो, "
           "फ्रेमिंग और ओवरले चेक करने के लिए एक छोटा टेस्ट स्ट्रीम चलाएं।")

def _p(slug, name, title, desc, kw, h1html, h1short, card, intro, quick, key_how, tips, faq, steps=None):
    d = {"slug": slug, "name": name, "title": title, "desc": desc, "kw": kw,
         "h1html": h1html, "h1short": h1short, "card": card, "intro": intro,
         "quick": quick, "key_how": key_how, "tips": tips, "faq": faq}
    if steps: d["steps"] = steps
    return d

PLATFORMS_HI = [
    _p("chaturbate", "Chaturbate",
       "Chaturbate पर SplitCam से स्ट्रीम करें — टोकन और RTMP",
       "Chaturbate पर मुफ़्त SplitCam से स्ट्रीम करें — broadcast token, RTMP, मल्टी-कैमरा सीन और ओवरले। कोई वॉटरमार्क नहीं, कोई रजिस्ट्रेशन नहीं।",
       "chaturbate स्ट्रीम, chaturbate broadcast token, chaturbate rtmp obs, chaturbate एक्सटर्नल एन्कोडर, chaturbate live",
       '<span class="accent">Chaturbate</span> पर SplitCam से स्ट्रीम कैसे करें',
       "Chaturbate स्ट्रीम",
       "Chaturbate पर टोकन-बेस्ड सेटअप और एक्सटर्नल एन्कोडर।",
       "Chaturbate टोकन इकॉनमी पर बनी सबसे बड़ी कैम प्लेटफ़ॉर्म में से एक है। इसका ब्राउज़र स्ट्रीमर सिर्फ एक फ्लैट सिंगल-कैमरा टूल है — मुफ़्त <strong style='color:var(--text)'>SplitCam</strong> के साथ <strong style='color:var(--text)'>एक्सटर्नल एन्कोडर</strong> पर स्विच करने से उसी टोकन-बेस्ड स्ट्रीम में मल्टी-कैमरा सीन, ओवरले और फ़िल्टर मिलते हैं।",
       "SplitCam से Chaturbate स्ट्रीम: SplitCam इंस्टॉल करें, सीन बनाएं, Chaturbate पर <em>Broadcast Yourself → My Broadcast</em> खोलें, broadcast token कॉपी करें, SplitCam में पेस्ट करें, Go Live दबाएं।"
       "<ol><li>SplitCam इंस्टॉल करें।</li><li>कैमरा + सीन जोड़ें।</li><li>Chaturbate से broadcast token कॉपी करें।</li><li>SplitCam में पेस्ट करें।</li><li>Go Live दबाएं।</li></ol>",
       "Chaturbate पर <strong>Broadcast Yourself</strong> क्लिक करें, फिर <strong>View RTMP/OBS broadcast information and stream key</strong>। कुंजी <strong>broadcast token</strong> के रूप में दिखती है — इसे कॉपी करें। इसे पासवर्ड की तरह रखें; कभी शेयर न करें।",
       [("टोकन ही कुंजी है", "Chaturbate आपका broadcast token उपयोग करता है, कोई सामान्य स्ट्रीम की नहीं। इसे पासवर्ड की तरह रखें और लीक होने पर रीसेट करें।"),
        ("पर्याप्त मार्जिन", "Chaturbate का RTMP ingest 4K, 60 fps और हाई बिटरेट स्वीकार करता है — लिमिट आपका अपलोड है, प्लेटफ़ॉर्म नहीं। हर 2 सेकंड में कीफ्रेम।"),
        _T_ETH, _T_TEST],
       [("क्या Chaturbate OBS / एक्सटर्नल एन्कोडर की अनुमति देता है?", "हाँ — Chaturbate आधिकारिक रूप से एक्सटर्नल एन्कोडर को सपोर्ट करता है और इसका «How do I set up OBS?» आर्टिकल भी है।"),
        ("मेरी Chaturbate स्ट्रीम की कहाँ है?", "Broadcast Yourself → My Broadcast → View RTMP/OBS broadcast information and stream key। की आपका broadcast token है।"),
        ("Chaturbate के लिए बिटरेट?", "1080p पर 3500–6000 Kbps काफी है। Chaturbate की सीमा ऊँची है — असली लिमिट आपका अपलोड है; पहले SplitCam का बिल्ट-इन स्पीड टेस्ट चलाएं।"),
        ("क्या SplitCam Chaturbate के लिए मुफ़्त है?", "हाँ — पूरी तरह मुफ़्त, कोई वॉटरमार्क नहीं, कोई समय सीमा नहीं।")]),
    _p("cam4", "CAM4",
       "CAM4 पर SplitCam से स्ट्रीम — External Encoder",
       "मुफ़्त SplitCam से CAM4 पर स्ट्रीम — External Encoder, स्ट्रीम की, जियो-ब्लॉकिंग और ओवरले। कोई वॉटरमार्क नहीं।",
       "cam4 स्ट्रीम, cam4.com, cam4 external encoder, cam4 stream key, cam4 rtmp obs",
       '<span class="accent">CAM4</span> पर SplitCam से स्ट्रीम कैसे करें',
       "CAM4 स्ट्रीम",
       "CAM4 पर जियो-कंट्रोल के साथ External Encoder।",
       "CAM4 एक ग्लोबल cam-and-earn प्लेटफ़ॉर्म है जिसमें बिल्ट-इन जियो-कंट्रोल है। मुफ़्त <strong style='color:var(--text)'>SplitCam</strong> से एक्सटर्नल एन्कोडर के रूप में स्ट्रीम करने से सीन स्विचिंग और ओवरले मिलते हैं।",
       "SplitCam से CAM4 स्ट्रीम: SplitCam इंस्टॉल करें, सीन बनाएं, CAM4 पर <em>Broadcast &amp; Earn Money → Start Broadcast → External Encoder</em> खोलें, Get Stream Key, SplitCam में पेस्ट करें, Go Live।"
       "<ol><li>SplitCam इंस्टॉल करें।</li><li>कैमरा + सीन जोड़ें।</li><li>CAM4 से स्ट्रीम की प्राप्त करें।</li><li>SplitCam में पेस्ट करें।</li><li>Go Live दबाएं।</li></ol>",
       "CAM4 पर <strong>Broadcast</strong> → <strong>Broadcast &amp; Earn Money</strong> → <strong>Start Broadcast</strong> → <strong>External Encoder</strong> क्लिक करें। जन्म तिथि, लिंग और देश भरें, <strong>Get Stream Key</strong> से की कॉपी करें।",
       [("जियो-प्रतिबंध सेट करें", "CAM4 कुछ देशों में स्ट्रीम छिपाने की अनुमति देता है — go-live से पहले CAM4 की साइड पर सेट करें।"),
        ("बिटरेट सामान्य से कम", "CAM4 का RTMP ingest लगभग 3000 Kbps पर वीडियो बिटरेट सीमित करता है — ज़्यादातर कैम साइट्स से कम।"),
        _T_ETH],
       [("क्या CAM4 आधिकारिक रूप से OBS / एक्सटर्नल एन्कोडर को सपोर्ट करता है?", "हाँ — CAM4 के सपोर्ट पेज पर Official OBS Guide है।"),
        ("CAM4 की स्ट्रीम की कहाँ है?", "Broadcast → Broadcast & Earn Money → Start Broadcast → External Encoder → Get Stream Key।"),
        ("CAM4 के लिए बिटरेट?", "औसत से कम — CAM4 का RTMP ingest ~3000 Kbps पर सीमित है।"),
        ("क्या SplitCam CAM4 के लिए मुफ़्त है?", "हाँ — पूरी तरह मुफ़्त, कोई वॉटरमार्क नहीं।")]),
    _p("bongacams", "BongaCams",
       "BongaCams पर SplitCam से स्ट्रीम — External Encoder",
       "मुफ़्त SplitCam से BongaCams पर स्ट्रीम — External Encoder, मल्टी-कैमरा सीन, ओवरले और AI बैकग्राउंड।",
       "bongacams स्ट्रीम, bongacams external encoder, bongacams rtmp obs",
       '<span class="accent">BongaCams</span> पर SplitCam से स्ट्रीम कैसे करें',
       "BongaCams स्ट्रीम",
       "BongaCams के लिए External Encoder सेटअप।",
       "BongaCams एक ग्लोबल कैम प्लेटफ़ॉर्म है। एक्सटर्नल एन्कोडर स्ट्रीमिंग हमेशा ऑन नहीं होती — एक्टिवेट होने पर, मुफ़्त <strong style='color:var(--text)'>SplitCam</strong> मल्टी-कैमरा सीन, ओवरले और AI बैकग्राउंड के साथ स्ट्रीम कंट्रोल करता है।",
       "SplitCam से BongaCams स्ट्रीम: SplitCam इंस्टॉल करें, सीन बनाएं, BongaCams पर <em>Options → Broadcast settings → Select Encoder → External Encoder</em> खोलें, URL और की कॉपी करें, SplitCam में पेस्ट करें, Go Live।"
       "<ol><li>SplitCam इंस्टॉल करें।</li><li>कैमरा + सीन जोड़ें।</li><li>BongaCams से URL और की प्राप्त करें।</li><li>SplitCam में पेस्ट करें।</li><li>Go Live दबाएं।</li></ol>",
       "BongaCams पर <strong>Options → Broadcast settings → Select Encoder → External Encoder</strong> खोलें और दिखाई गई सर्वर URL और स्ट्रीम की कॉपी करें। <strong>अगर External Encoder बटन नहीं है</strong>, BongaCams सपोर्ट से संपर्क करें।",
       [("External Encoder बटन नहीं? सपोर्ट", "BongaCams एक्सटर्नल एन्कोडिंग प्रति-अकाउंट एनेबल करता है।"),
        ("रेज़ॉल्यूशन मैच करें", "BongaCams वेबकैम और स्ट्रीम रेज़ॉल्यूशन मिलाने की सलाह देता है।"),
        _T_ETH, _T_TEST],
       [("BongaCams पर External Encoder बटन क्यों नहीं दिखता?", "एक्सटर्नल एन्कोडिंग डिफ़ॉल्ट रूप से चालू नहीं है — BongaCams सपोर्ट से संपर्क करें।"),
        ("क्या BongaCams अकाउंट वेरिफाई करना ज़रूरी है?", "हाँ — स्ट्रीमिंग के लिए 18+, आयु सत्यापन के लिए सरकारी ID चाहिए।"),
        ("BongaCams के लिए बिटरेट?", "1080p पर 3500–6000 Kbps आदर्श है।"),
        ("क्या SplitCam BongaCams के लिए मुफ़्त है?", "हाँ — पूरी तरह मुफ़्त, कोई वॉटरमार्क नहीं।")]),
    _p("stripchat", "Stripchat",
       "Stripchat पर SplitCam से स्ट्रीम — strip cam सेटअप",
       "मुफ़्त SplitCam से Stripchat पर स्ट्रीम। एक्सटर्नल सॉफ़्टवेयर, टोकन-बेस्ड की, सीन और ओवरले।",
       "strip cam, stripchat live stream, stripchat external software, stripchat rtmp obs",
       '<span class="accent">Stripchat</span> पर SplitCam से स्ट्रीम कैसे करें',
       "Stripchat स्ट्रीम",
       "Stripchat स्ट्रीमिंग के लिए एक्सटर्नल सॉफ़्टवेयर सेटअप।",
       "Stripchat इंटरएक्टिविटी पर फ़ोकस करने वाला बड़ा कैम प्लेटफ़ॉर्म है। <em>external software</em> मोड आपको टोकन-बेस्ड की देता है — इसे मुफ़्त <strong style='color:var(--text)'>SplitCam</strong> में डालें और सीन, ओवरले और फ़िल्टर के साथ स्ट्रीम करें।",
       "SplitCam से Stripchat स्ट्रीम: SplitCam इंस्टॉल करें, सीन बनाएं, Stripchat पर <em>Switch to external software</em> चुनें, स्ट्रीम की कॉपी करें, SplitCam में पेस्ट करें, Go Live।"
       "<ol><li>SplitCam इंस्टॉल करें।</li><li>कैमरा + सीन जोड़ें।</li><li>Stripchat से स्ट्रीम की प्राप्त करें।</li><li>SplitCam में पेस्ट करें।</li><li>Go Live दबाएं।</li></ol>",
       "Stripchat पर <strong>Switch to external software</strong> चुनें, फिर <strong>Show external software settings for the stream</strong>। स्ट्रीम की कॉपी करें — Stripchat इसे टोकन के रूप में दिखाता है।",
       [("साइट से रेज़ॉल्यूशन मिलाएं", "Stripchat FAQ चेतावनी देता है: आपके सॉफ़्टवेयर में रेज़ॉल्यूशन साइट से बिल्कुल मेल खाना चाहिए।"),
        ("न्यूनतम 2 Mbps का ध्यान रखें", "Stripchat 2 Mbps अपलोड को न्यूनतम बताता है — OBS स्ट्रीमिंग के लिए बहुत अधिक लक्ष्य रखें।"),
        ("की एक टोकन है", "Stripchat का स्ट्रीम की एक टोकन है — सटीक कॉपी करें, कभी शेयर न करें।"),
        _T_ETH],
       [("क्या Stripchat OBS / एक्सटर्नल सॉफ़्टवेयर की सिफ़ारिश करता है?", "हाँ — Stripchat का FAQ «सर्वोत्तम वीडियो और ऑडियो गुणवत्ता» के लिए एक्सटर्नल सॉफ़्टवेयर की सिफ़ारिश करता है।"),
        ("Stripchat को एक्सटर्नल सॉफ़्टवेयर पर कैसे स्विच करें?", "Broadcast Center में Switch to External Broadcast Software (OBS) चुनें।"),
        ("Stripchat के लिए बिटरेट?", "1080p पर 3500–6000 Kbps आदर्श है।"),
        ("क्या SplitCam Stripchat के लिए मुफ़्त है?", "हाँ — कोई लाइसेंस शुल्क नहीं, कोई वॉटरमार्क नहीं।")]),
    _p("onlyfans", "OnlyFans",
       "OnlyFans पर SplitCam से लाइव — Authorization या की",
       "मुफ़्त SplitCam से OnlyFans लाइव — Authorization या OBS Key से लॉगिन, मल्टी-कैमरा सीन, ओवरले।",
       "onlyfans live stream, onlyfans authorization splitcam, onlyfans obs key",
       '<span class="accent">OnlyFans</span> पर SplitCam से लाइव कैसे जाएं',
       "OnlyFans लाइव",
       "एक बार Authorization दें या की पेस्ट करें — OnlyFans पर लाइव।",
       "अपने सब्सक्राइबर्स के लिए OnlyFans लाइव। SplitCam <strong style='color:var(--text)'>दो तरीकों</strong> से कनेक्ट होता है — OnlyFans अकाउंट से एक बार लॉगिन करें और SplitCam ऑटोमेटिकली स्ट्रीम की ले लेगा, या OBS Key मैन्युअली पेस्ट करें।",
       "SplitCam से OnlyFans लाइव: SplitCam इंस्टॉल करें, सीन बनाएं, Stream Settings &rarr; Add Channel &rarr; OnlyFans खोलें और <em>Authorization</em> चुनें — OnlyFans अकाउंट से लॉगिन करें, SplitCam की ऑटो प्राप्त करेगा — Go Live दबाएं।",
       "OnlyFans पर: <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; <strong>Other</strong> सेक्शन, <strong>OBS Key</strong> कॉपी करें। या SplitCam में <strong>Authorization</strong> से लॉगिन करें — की ऑटो सिंक होती है।",
       [("Authorization बनाम Stream Key", "<strong>Authorization</strong> (एक बार लॉगिन, की ऑटो सिंक — सबसे आसान) या <strong>Stream Key</strong> (OnlyFans → Profile → Settings → Other से OBS Key कॉपी और पेस्ट)।"),
        ("SplitCam छोड़े बिना सेटिंग्स बदलें", "Authorization के साथ, अकाउंट कनेक्टेड रहता है।"),
        ("मध्यम बिटरेट", "OnlyFans का RTMP ingest लगभग 2500 Kbps पर सीमित है।"),
        _T_ETH],
       [("OnlyFans को SplitCam से कैसे कनेक्ट करें?", "<strong>Authorization</strong> — Stream Settings → Add Channel → OnlyFans → लॉगिन। या <strong>Stream Key</strong> — OBS Key कॉपी और पेस्ट।"),
        ("क्या OnlyFans लाइव सेटिंग्स साइट खोले बिना बदल सकते हैं?", "हाँ — Authorization विधि से SplitCam अकाउंट से जुड़ा रहता है।"),
        ("OnlyFans के लिए बिटरेट?", "~2000–2500 Kbps पर 720p–1080p।"),
        ("क्या SplitCam OnlyFans के लिए मुफ़्त है?", "हाँ — मुफ़्त, कोई वॉटरमार्क नहीं।")],
       steps=[
           ("SplitCam डाउनलोड और इंस्टॉल करें", "SplitCam Windows और macOS के लिए मुफ़्त लाइव स्ट्रीमिंग सॉफ़्टवेयर है — कोई रजिस्ट्रेशन नहीं, कोई वॉटरमार्क नहीं।"),
           ("कैमरा और सीन सेट करें", "SplitCam खोलें और अपना वेबकैम जोड़ें। सीन बनाएं — ओवरले, टेक्स्ट, दूसरा कैमरा, ब्यूटी फ़िल्टर या AI बैकग्राउंड।"),
           ("कनेक्शन — तरीका 1: Authorization (अनुशंसित)", "SplitCam में <strong>Stream Settings → Add Channel → OnlyFans → Authorization</strong> चुनें। OnlyFans से लॉगिन करें। SplitCam अकाउंट लिंक करेगा और की ऑटो प्राप्त करेगा।"),
           ("कनेक्शन — तरीका 2: Stream Key (मैन्युअल)", "OnlyFans पर <strong>Profile → Settings → Other</strong> से <strong>OBS Key</strong> कॉपी करें। SplitCam में Add Channel → OnlyFans, की फ़ील्ड में पेस्ट करें।"),
           ("Go Live", "SplitCam में <strong>Go Live</strong> दबाएं।"),
       ]),
    _p("camplace", "CamPlace",
       "CamPlace पर SplitCam से स्ट्रीम — मुफ़्त गाइड",
       "मुफ़्त SplitCam से CamPlace पर स्ट्रीम — एक्सटर्नल एन्कोडर, RTMP की, सीन और ओवरले।",
       "camplace स्ट्रीम, camplace rtmp, camplace एक्सटर्नल एन्कोडर",
       '<span class="accent">CamPlace</span> पर SplitCam से स्ट्रीम कैसे करें',
       "CamPlace स्ट्रीम",
       "CamPlace स्ट्रीमिंग के लिए एक्सटर्नल एन्कोडर सेटअप।",
       "CamPlace एक कैम-स्ट्रीमिंग प्लेटफ़ॉर्म है। कोई पब्लिक OBS आर्टिकल नहीं है, इसलिए <strong style='color:var(--text)'>ऊपर का वीडियो गाइड</strong> आपका संदर्भ है — मुफ़्त <strong style='color:var(--text)'>SplitCam</strong> स्टैंडर्ड RTMP के ज़रिए कनेक्ट होता है।",
       "SplitCam से CamPlace स्ट्रीम: SplitCam इंस्टॉल करें, सीन बनाएं, CamPlace पर एक्सटर्नल/RTMP स्ट्रीमिंग चालू करें, सर्वर URL और स्ट्रीम की कॉपी करें, SplitCam में पेस्ट करें, Go Live।"
       "<ol><li>SplitCam इंस्टॉल करें।</li><li>कैमरा + सीन जोड़ें।</li><li>CamPlace से RTMP की प्राप्त करें।</li><li>SplitCam में पेस्ट करें।</li><li>Go Live दबाएं।</li></ol>",
       "CamPlace में लॉगिन करें और ब्रॉडकास्ट सेटिंग्स खोलें। एक्सटर्नल एन्कोडर / RTMP / OBS ऑप्शन पर स्विच करें।",
       [("कोई ऑफ़िशियल OBS गाइड नहीं — वीडियो उपयोग करें", "CamPlace का कोई एक्सटर्नल एन्कोडर आर्टिकल नहीं है।"),
        ("स्टैंडर्ड RTMP काम करता है", "CamPlace स्टैंडर्ड RTMP सर्वर URL और की स्वीकार करता है।"),
        ("SplitCam में ओवरले लगाएं", "टिप गोल्स, नाम और सोशल मीडिया हैंडल सीन लेयर के रूप में जोड़ें।"),
        _T_ETH],
       [("क्या CamPlace का ऑफ़िशियल OBS गाइड है?", "एक्सटर्नल एन्कोडर पर कोई पब्लिक आर्टिकल नहीं मिला। वीडियो फ़ॉलो करें।"),
        ("क्या CamPlace एक्सटर्नल एन्कोडर सपोर्ट करता है?", "हाँ — स्टैंडर्ड RTMP स्ट्रीम की स्वीकार करता है।"),
        ("CamPlace के लिए बिटरेट?", "1080p पर 3500–6000 Kbps सुरक्षित रेंज है।"),
        ("क्या SplitCam CamPlace के लिए मुफ़्त है?", "हाँ — मुफ़्त, कोई वॉटरमार्क नहीं।")]),
    _p("camsoda", "CamSoda",
       "CamSoda पर SplitCam से लाइव — मुफ़्त सेटअप",
       "मुफ़्त SplitCam से CamSoda लाइव — Use OBS Broadcaster, रीजनल सर्वर, सीन और ओवरले।",
       "camsoda live, camsoda obs broadcaster, camsoda rtmp obs",
       '<span class="accent">CamSoda</span> पर SplitCam से स्ट्रीम कैसे करें',
       "CamSoda स्ट्रीम",
       "CamSoda पर Use OBS Broadcaster सेटअप।",
       "CamSoda एक US-बेस्ड कैम प्लेटफ़ॉर्म है जो इंटरएक्टिव, अनोखे शो फ़ॉर्मेट के लिए जाना जाता है। यह OBS ब्रॉडकास्टिंग को आधिकारिक रूप से सपोर्ट करता है — Go Live पेज पर <strong style='color:var(--text)'>Use OBS Broadcaster</strong> बटन है।",
       "SplitCam से CamSoda स्ट्रीम: SplitCam इंस्टॉल करें, सीन बनाएं, CamSoda के Go Live पेज पर Use OBS Broadcaster क्लिक करें, सर्वर URL और की कॉपी करें, SplitCam में पेस्ट करें, Go Live।"
       "<ol><li>SplitCam इंस्टॉल करें।</li><li>कैमरा + सीन जोड़ें।</li><li>CamSoda पर Use OBS Broadcaster क्लिक करें।</li><li>SplitCam में सर्वर URL + की पेस्ट करें।</li><li>Go Live दबाएं।</li></ol>",
       "CamSoda के <strong>Go Live</strong> पेज पर <strong>Use OBS Broadcaster</strong> क्लिक करें। CamSoda RTMP सर्वर URL और की दिखाता है।",
       [("टिप्स पाने के लिए वेरिफ़ाई करें", "CamSoda पर कोई भी स्ट्रीम कर सकता है, लेकिन टिप्स पाने के लिए CamSoda का वेरिफ़िकेशन पूरा करना होगा।"),
        ("सबसे नज़दीकी रीजनल सर्वर चुनें", "CamSoda रीजनल ingest सर्वर ऑफ़र करता है।"),
        ("1080p / 30 fps पर सीमा", "CamSoda का ingest ~6000 Kbps तक जाता है।"),
        _T_ETH],
       [("क्या CamSoda OBS / एक्सटर्नल एन्कोडर को सपोर्ट करता है?", "हाँ — आधिकारिक रूप से। Go Live पेज पर Use OBS Broadcaster बटन है।"),
        ("क्या CamSoda पर वेरिफ़िकेशन ज़रूरी है?", "स्ट्रीमिंग के लिए नहीं। टिप्स के लिए हाँ।"),
        ("CamSoda के लिए बिटरेट?", "30 fps पर 1080p तक, ~6000 Kbps RTMP ingest में।"),
        ("क्या SplitCam CamSoda के लिए मुफ़्त है?", "हाँ — मुफ़्त, कोई वॉटरमार्क नहीं।")]),
    _p("streamate", "Streamate",
       "Streamate पर SplitCam से स्ट्रीम — इंटीग्रेटेड चैनल",
       "मुफ़्त SplitCam से Streamate स्ट्रीम — इंटीग्रेटेड चैनल, SM Connect की, सीन और ओवरले।",
       "streamate, streamate sm connect, streamate rtmp",
       '<span class="accent">Streamate</span> पर SplitCam से स्ट्रीम कैसे करें',
       "Streamate स्ट्रीम",
       "Streamate, SplitCam में इंटीग्रेटेड चैनल है — फ़ास्ट सेटअप।",
       "Streamate एक स्थापित कैम प्लेटफ़ॉर्म है — और <strong style='color:var(--text)'>SplitCam में प्री-कॉन्फ़िगर्ड डेस्टिनेशन</strong> है, चैनल लिस्ट में, इसलिए मैन्युअल RTMP एंट्री से सेटअप तेज़ है।",
       "SplitCam से Streamate स्ट्रीम: SplitCam इंस्टॉल करें, सीन बनाएं, Streamate पर <em>SM Connect → Start Show</em> से की कॉपी करें, SplitCam में <em>Stream Settings → Add Channel → Streamate</em> खोलें और पेस्ट करें।"
       "<ol><li>SplitCam इंस्टॉल करें।</li><li>कैमरा + सीन जोड़ें।</li><li>SM Connect से Streamate की प्राप्त करें।</li><li>SplitCam में Add Channel → Streamate।</li><li>Go Live दबाएं।</li></ol>",
       "Streamate पर <strong>SM Connect</strong> खोलें, शर्तें स्वीकार करें, <strong>Start Show</strong> क्लिक करें और खुली विंडो बंद करें — फिर स्ट्रीमिंग की कॉपी करें।",
       [("Streamate इंटीग्रेटेड है", "कोई मैन्युअल RTMP URL नहीं — SplitCam की Add Channel लिस्ट में Streamate है।"),
        ("SM Connect पॉपअप बंद करें", "Start Show के बाद Streamate एक विंडो खोलता है — बंद करें; यह सिर्फ़ की दिखाने के लिए है।"),
        ("रेज़ॉल्यूशन 1080p पर लॉक करें", "SM Connect में Video Resolution फ़ील्ड चुपचाप 1440 पर जा सकता है — मैन्युअली 1080p सेट करें।"),
        _T_ETH, _T_TEST],
       [("क्या Streamate SplitCam में इंटीग्रेटेड है?", "हाँ — Streamate SplitCam की Add Channel लिस्ट में दिखता है।"),
        ("Streamate की स्ट्रीमिंग की कहाँ है?", "SM Connect → शर्तें स्वीकार करें → Start Show → पॉपअप बंद करें → की कॉपी करें।"),
        ("Streamate के लिए बिटरेट?", "1080p पर 3500–6000 Kbps अच्छा काम करता है।"),
        ("क्या SplitCam Streamate के लिए मुफ़्त है?", "हाँ — मुफ़्त, कोई वॉटरमार्क नहीं।")]),
    _p("streamray", "StreamRay",
       "StreamRay cam पर SplitCam से स्ट्रीम — चैट में URL",
       "मुफ़्त SplitCam से StreamRay cam स्ट्रीम — URL चैट में पोस्ट होता है, OBS Broadcaster मोड।",
       "streamray cam, streamray obs broadcaster, streamray rtmp",
       '<span class="accent">StreamRay</span> पर SplitCam से स्ट्रीम कैसे करें',
       "StreamRay स्ट्रीम",
       "StreamRay के लिए URL-इन-चैट एक्सटर्नल एन्कोडर सेटअप।",
       "StreamRay का असामान्य एक्सटर्नल एन्कोडर सेटअप है — यह स्ट्रीम URL <strong style='color:var(--text)'>ब्रॉडकास्ट चैट विंडो</strong> में भेजता है और अलग की उपयोग नहीं करता।",
       "SplitCam से StreamRay स्ट्रीम: SplitCam इंस्टॉल करें, सीन बनाएं, StreamRay पर OBS Broadcaster चालू करें, चैट विंडो से स्ट्रीम URL कॉपी करें, SplitCam में पेस्ट करें (की फ़ील्ड खाली रखें), Go Live।"
       "<ol><li>SplitCam इंस्टॉल करें।</li><li>कैमरा + सीन जोड़ें।</li><li>StreamRay URL चैट से कॉपी करें।</li><li>SplitCam में URL पेस्ट करें।</li><li>Go Live दबाएं।</li></ol>",
       "StreamRay पर <strong>Broadcast Now</strong> डबल-क्लिक करें, <strong>Other</strong> मेनू खोलें, <strong>OBS Broadcaster</strong> और <strong>Save and Close</strong> चुनें। StreamRay फिर <strong>चैट विंडो में स्ट्रीम URL पोस्ट</strong> करता है।",
       [("URL चैट में है", "StreamRay सेटिंग बॉक्स में URL नहीं दिखाता — चैट में पोस्ट करता है।"),
        ("की फ़ील्ड खाली रखें", "StreamRay अलग की उपयोग नहीं करता — SplitCam की फ़ील्ड में कुछ न डालें।"),
        _T_ETH, _T_TEST],
       [("StreamRay का स्ट्रीम URL कहाँ है?", "OBS Broadcaster चालू करने के बाद StreamRay चैट विंडो में URL पोस्ट करता है।"),
        ("StreamRay पर स्ट्रीम की क्यों नहीं है?", "StreamRay सिर्फ़ URL से वेरिफ़ाई करता है — SplitCam की फ़ील्ड खाली रखें।"),
        ("StreamRay के लिए बिटरेट?", "1080p पर 3500–6000 Kbps लक्ष्य रखें।"),
        ("क्या SplitCam StreamRay के लिए मुफ़्त है?", "हाँ — मुफ़्त, कोई वॉटरमार्क नहीं।")]),
    _p("xlovecam", "XLoveCam",
       "XLoveCam पर SplitCam से स्ट्रीम — RTMP लिंक और की",
       "मुफ़्त SplitCam से XLoveCam स्ट्रीम — RTMP लिंक और की, रीजनल सर्वर, सीन और ओवरले।",
       "xlovecam, xlovecam rtmp link, xlovecam stream key",
       '<span class="accent">XLoveCam</span> पर SplitCam से स्ट्रीम कैसे करें',
       "XLoveCam स्ट्रीम",
       "XLoveCam के लिए RTMP लिंक + की सेटअप।",
       "XLoveCam एक यूरोपीय मल्टी-लैंग्वेज कैम प्लेटफ़ॉर्म है। अकाउंट सेटिंग्स दोनों <strong style='color:var(--text)'>RTMP लिंक</strong> और <strong style='color:var(--text)'>स्ट्रीम की</strong> दिखाती हैं।",
       "SplitCam से XLoveCam स्ट्रीम: SplitCam इंस्टॉल करें, सीन बनाएं, XLoveCam पर <em>My Account → settings</em> खोलें, RTMP लिंक और की कॉपी करें, दोनों SplitCam में पेस्ट करें, शो शुरू करें।"
       "<ol><li>SplitCam इंस्टॉल करें।</li><li>कैमरा + सीन जोड़ें।</li><li>XLoveCam से RTMP लिंक + की कॉपी करें।</li><li>दोनों SplitCam में पेस्ट करें।</li><li>Go Live दबाएं।</li></ol>",
       "XLoveCam पर <strong>My Account → settings</strong> खोलें। सेटिंग्स दोनों <strong>RTMP लिंक</strong> और <strong>की</strong> दिखाती हैं।",
       [("लिंक और की दोनों कॉपी करें", "XLoveCam RTMP लिंक और अलग की दोनों देता है — SplitCam में दोनों चाहिए।"),
        ("मल्टी-लैंग्वेज ऑडियंस", "XLoveCam यूरोपीय और मल्टी-लैंग्वेज है।"),
        ("सबसे नज़दीकी सर्वर चुनें", "XLoveCam रीजनल RTMP सर्वर ऑफ़र करता है।"),
        _T_ETH],
       [("XLoveCam का RTMP डेटा कहाँ है?", "My Account → settings — RTMP लिंक और की दोनों दिखाता है।"),
        ("क्या XLoveCam एक्सटर्नल एन्कोडर सपोर्ट करता है?", "हाँ — RTMP लिंक और की प्रदान करता है।"),
        ("XLoveCam के लिए बिटरेट?", "1080p पर 3500–6000 Kbps आदर्श है।"),
        ("क्या SplitCam XLoveCam के लिए मुफ़्त है?", "हाँ — मुफ़्त, कोई वॉटरमार्क नहीं।")]),
    _p("soulcams", "SoulCams",
       "SoulCams पर SplitCam से स्ट्रीम — OBS सेटिंग्स",
       "मुफ़्त SplitCam से SoulCams स्ट्रीम — OBS सेटिंग्स, RTMP सर्वर और की, मल्टी-कैमरा सीन।",
       "soul cams, soulcams obs, soulcams rtmp",
       '<span class="accent">SoulCams</span> पर SplitCam से स्ट्रीम कैसे करें',
       "SoulCams स्ट्रीम",
       "SoulCams के लिए OBS सेटिंग्स।",
       "SoulCams वह प्लेटफ़ॉर्म है जिसकी OBS सेटिंग्स <strong style='color:var(--text)'>RTMP सर्वर और की एक साथ</strong> एक विंडो में दिखाती हैं।",
       "SplitCam से SoulCams स्ट्रीम: SplitCam इंस्टॉल करें, सीन बनाएं, SoulCams पर Go Online → Settings → OBS क्लिक करें, सर्वर और की कॉपी करें, दोनों SplitCam में पेस्ट करें, Go Live।"
       "<ol><li>SplitCam इंस्टॉल करें।</li><li>कैमरा + सीन जोड़ें।</li><li>SoulCams Settings → OBS खोलें।</li><li>SplitCam में सर्वर + की पेस्ट करें।</li><li>Go Live दबाएं।</li></ol>",
       "SoulCams में लॉगिन करें, <strong>Go Online</strong> क्लिक करें, फिर <strong>Settings → OBS</strong> खोलें।",
       [("सर्वर और की एक साथ हैं", "SoulCams RTMP सर्वर और की एक ही OBS विंडो में दिखाता है।"),
        ("पहले Go Online", "OBS सेटिंग्स SoulCams पर Go Online क्लिक करने के बाद ही दिखती हैं।"),
        ("अनचाहे रीजन ब्लॉक करें", "SoulCams मॉडल की तरफ से जियो-ब्लॉकिंग की अनुमति देता है।"),
        _T_ETH, _T_TEST],
       [("SoulCams की OBS सेटिंग्स कहाँ हैं?", "लॉगिन करें, Go Online क्लिक करें, फिर Settings → OBS।"),
        ("क्या SoulCams एक्सटर्नल एन्कोडर सपोर्ट करता है?", "हाँ — OBS सेटिंग्स RTMP सर्वर और की देती हैं।"),
        ("SoulCams के लिए बिटरेट?", "1080p पर 3500–6000 Kbps।"),
        ("क्या SplitCam SoulCams के लिए मुफ़्त है?", "हाँ — मुफ़्त, कोई वॉटरमार्क नहीं।")]),
    _p("imlive", "ImLive",
       "SplitCam से ImLive उपयोग करें — वर्चुअल कैमरा",
       "मुफ़्त SplitCam से Im Live सेटअप — ImLive लाइव वेबकैम उपयोग करता है (RTMP नहीं), SplitCam को वर्चुअल कैमरा के रूप में कनेक्ट करें।",
       "im live stream, imlive splitcam, imlive webcam",
       'SplitCam के साथ <span class="accent">ImLive</span> कैसे उपयोग करें',
       "ImLive पर SplitCam",
       "ImLive के लिए वर्चुअल कैमरा सेटअप — RTMP नहीं।",
       "ImLive ब्राउज़र में लाइव वेबकैम उपयोग करता है — <strong style='color:var(--text)'>RTMP या स्ट्रीम की नहीं</strong>। मुफ़्त <strong style='color:var(--text)'>SplitCam</strong> <strong style='color:var(--text)'>वर्चुअल कैमरा</strong> के रूप में कनेक्ट होता है।",
       "SplitCam से ImLive: SplitCam इंस्टॉल करें, मीडिया लेयर के साथ सीन बनाएं, ImLive खोलें और वीडियो चैट शुरू करें, ImLive सेटिंग्स में SplitCam को वेबकैम और माइक्रोफ़ोन चुनें।"
       "<ol><li>SplitCam इंस्टॉल करें।</li><li>SplitCam में सीन बनाएं।</li><li>ImLive पर वीडियो चैट शुरू करें।</li><li>SplitCam को ImLive कैमरा चुनें।</li><li>चैट शुरू करें।</li></ol>",
       "ImLive साइट पर लॉगिन करें, <strong>Start Video Chat</strong> क्लिक करें, फिर <strong>Go To Settings</strong> खोलें। ImLive सेटिंग्स में <strong>SplitCam</strong> को वेबकैम और माइक्रोफ़ोन चुनें।",
       [("स्ट्रीम की ज़रूरी नहीं", "ImLive में RTMP नहीं है — सर्वर URL या की न ढूंढें।"),
        ("SplitCam को माइक्रोफ़ोन भी सेट करें", "कैमरे के अलावा माइक्रोफ़ोन के लिए भी SplitCam चुनें।"),
        ("लाइव से पहले सीन बनाएं", "ImLive वही दिखाता है जो SplitCam भेजता है।"),
        _T_TEST],
       [("क्या ImLive RTMP या स्ट्रीम की उपयोग करता है?", "कोई नहीं — ImLive ब्राउज़र से लाइव वेबकैम उपयोग करता है।"),
        ("ImLive में SplitCam कैसे चुनें?", "Start Video Chat → Go To Settings → SplitCam को वेबकैम और माइक्रोफ़ोन चुनें।"),
        ("क्या ImLive में ओवरले उपयोग कर सकते हैं?", "हाँ — SplitCam सीन में बनाएं।"),
        ("क्या SplitCam ImLive के लिए मुफ़्त है?", "हाँ — मुफ़्त, कोई वॉटरमार्क नहीं।")],
       steps=[
           ("SplitCam इंस्टॉल करें", "SplitCam Windows और macOS के लिए मुफ़्त सॉफ़्टवेयर है — कोई वॉटरमार्क नहीं, कोई रजिस्ट्रेशन नहीं।"),
           ("SplitCam में सीन बनाएं", "SplitCam खोलें और <strong>Media Layers +</strong> से वेबकैम के साथ ओवरले, टेक्स्ट, फ़िल्टर या AI बैकग्राउंड जोड़ें।"),
           ("ImLive पर वीडियो चैट शुरू करें", "ImLive साइट पर लॉगिन करें, <strong>Start Video Chat</strong> क्लिक करें, फिर <strong>Go To Settings</strong> खोलें।"),
           ("SplitCam को कैमरा चुनें", "ImLive सेटिंग्स में <strong>SplitCam</strong> को वेबकैम और माइक्रोफ़ोन चुनें।"),
           ("Free Live Chat शुरू करें", "ImLive पर <strong>Free Live Chat</strong> क्लिक करें।"),
       ]),
    _p("vxlive", "VXLive",
       "VXLive पर SplitCam से स्ट्रीम — ऑफ़िशियल सपोर्ट",
       "मुफ़्त SplitCam से VXLive (VXModels / VISIT-X) स्ट्रीम — ऑफ़िशियल VISIT-X प्रीसेट, सर्वर और की।",
       "vxlive, visit-x, vxmodels splitcam, vxlive rtmp",
       '<span class="accent">VXLive</span> पर SplitCam से स्ट्रीम कैसे करें',
       "VXLive स्ट्रीम",
       "VXLive, SplitCam को ऑफ़िशियली सपोर्ट करता है (VISIT-X प्रीसेट)।",
       "VXLive (VXModels / VISIT-X) जर्मन मार्केट का कैम प्लेटफ़ॉर्म है — और उन कुछ प्लेटफ़ॉर्म में से एक जो <strong style='color:var(--text)'>SplitCam को नाम से ऑफ़िशियली सपोर्ट करता है</strong>।",
       "SplitCam से VXLive स्ट्रीम: SplitCam इंस्टॉल करें, सीन बनाएं, VXLive पर «Stream with third-party software» चुनें, सर्वर URL और की कॉपी करें, SplitCam में VISIT-X प्रीसेट चुनें और पेस्ट करें, SplitCam में Go Live, फिर VXLive पर GO ONLINE।"
       "<ol><li>SplitCam इंस्टॉल करें।</li><li>कैमरा + सीन जोड़ें।</li><li>VXLive से सर्वर URL + की प्राप्त करें।</li><li>SplitCam में VISIT-X प्रीसेट चुनें, पेस्ट करें।</li><li>Go Live, फिर VXLive पर GO ONLINE।</li></ol>",
       "VXLive पर <strong>Stream with third-party software</strong> और <strong>OBS, SplitCam या XSplit</strong> ऑप्शन चुनें।",
       [("VISIT-X एक इंटीग्रेटेड प्रीसेट है", "रॉ RTMP URL न डालें — SplitCam की प्लेटफ़ॉर्म लिस्ट में VISIT-X है।"),
        ("दो-चरणीय go-live", "VXLive पर पहले SplitCam में Go Live, फिर VXLive पर GO ONLINE।"),
        ("जर्मन मार्केट", "VXLive की ऑडियंस मुख्यतः जर्मन-भाषी है।"),
        _T_ETH],
       [("क्या VXLive, SplitCam को ऑफ़िशियली सपोर्ट करता है?", "हाँ — VXModels का SplitCam सेटअप के लिए डेडिकेटेड हेल्प आर्टिकल है।"),
        ("SplitCam को VXLive से कैसे कनेक्ट करें?", "VXLive पर «Stream with third-party software» चुनें, फिर SplitCam में VISIT-X प्रीसेट।"),
        ("क्या मैं SplitCam या VXLive में लाइव हूँ?", "दोनों में — पहले SplitCam में Go Live, फिर VXLive पर GO ONLINE।"),
        ("VXModels SplitCam क्यों सुझाता है?", "VXModels का हेल्प आर्टिकल वेबकैम इमेज आर्टिफैक्ट हटाने के लिए SplitCam सुझाता है।")]),
    _p("virtwish", "VirtWish",
       "VirtWish पर SplitCam से स्ट्रीम — स्ट्रीम URL और की",
       "मुफ़्त SplitCam से VirtWish स्ट्रीम — OBS Profile → Start Broadcast सेक्शन, स्ट्रीम URL और की।",
       "virtwish, virtwish rtmp, virtwish stream key, virtwish obs",
       '<span class="accent">VirtWish</span> पर SplitCam से स्ट्रीम कैसे करें',
       "VirtWish स्ट्रीम",
       "VirtWish के लिए स्ट्रीम URL + की सेटअप।",
       "VirtWish एक इंटरएक्टिव कैम प्लेटफ़ॉर्म है। ब्रॉडकास्ट सेटिंग्स OBS सेक्शन में <strong style='color:var(--text)'>अलग स्ट्रीम URL और की</strong> देती हैं।",
       "SplitCam से VirtWish स्ट्रीम: SplitCam इंस्टॉल करें, सीन बनाएं, VirtWish पर <em>Profile → Start Broadcast</em> से OBS सेक्शन तक जाएं, लिंक और की कॉपी करें, दोनों SplitCam में पेस्ट करें, Go Live।"
       "<ol><li>SplitCam इंस्टॉल करें।</li><li>कैमरा + सीन जोड़ें।</li><li>VirtWish से URL + की प्राप्त करें।</li><li>दोनों SplitCam में पेस्ट करें।</li><li>Go Live दबाएं।</li></ol>",
       "VirtWish पर ऊपर-दाएं आइकन → <strong>Profile</strong> → <strong>Start Broadcast</strong> क्लिक करें, फिर OBS सेक्शन तक पहुँचने के लिए <strong>Start Broadcast</strong> फिर क्लिक करें।",
       [("लिंक पहली पंक्ति में है", "VirtWish का OBS सेक्शन स्ट्रीम URL पहली पंक्ति में रखता है।"),
        ("Start Broadcast के दो क्लिक", "OBS सेक्शन तक पहुँचने के लिए VirtWish पर Start Broadcast दो बार क्लिक करते हैं।"),
        _T_ETH, _T_TEST],
       [("VirtWish का RTMP डेटा कहाँ है?", "ऊपर-दाएं आइकन → Profile → Start Broadcast दो बार → OBS सेक्शन।"),
        ("क्या VirtWish एक्सटर्नल एन्कोडर सपोर्ट करता है?", "हाँ — OBS सेक्शन स्ट्रीम URL और की देता है।"),
        ("VirtWish के लिए बिटरेट?", "1080p पर 3500–6000 Kbps सुरक्षित है।"),
        ("क्या SplitCam VirtWish के लिए मुफ़्त है?", "हाँ — मुफ़्त, कोई वॉटरमार्क नहीं।")]),
    _p("xmodels", "XModels",
       "XModels पर SplitCam से स्ट्रीम — मुफ़्त गाइड",
       "मुफ़्त SplitCam से XModels स्ट्रीम — मॉडल अकाउंट सेटिंग में एक्सटर्नल एन्कोडर ऑप्शन, RTMP की।",
       "xmodels, xmodels rtmp, xmodels एक्सटर्नल एन्कोडर",
       '<span class="accent">XModels</span> पर SplitCam से स्ट्रीम कैसे करें',
       "XModels स्ट्रीम",
       "XModels स्ट्रीमिंग के लिए एक्सटर्नल एन्कोडर सेटअप।",
       "XModels एक cam-streaming प्लेटफ़ॉर्म है जिसमें मॉडल अकाउंट सेटिंग्स में बिल्ट-इन <strong style='color:var(--text)'>एक्सटर्नल एन्कोडर ऑप्शन</strong> है।",
       "SplitCam से XModels स्ट्रीम: SplitCam इंस्टॉल करें, सीन बनाएं, XModels मॉडल अकाउंट में एक्सटर्नल एन्कोडर ऑप्शन चालू करें, सर्वर URL और की कॉपी करें, SplitCam में पेस्ट करें, Go Live।"
       "<ol><li>SplitCam इंस्टॉल करें।</li><li>कैमरा + सीन जोड़ें।</li><li>XModels सेटिंग्स में एक्सटर्नल एन्कोडर चालू करें।</li><li>SplitCam में सर्वर URL + की पेस्ट करें।</li><li>Go Live दबाएं।</li></ol>",
       "XModels के <strong>मॉडल अकाउंट सेटिंग्स</strong> में <strong>एक्सटर्नल एन्कोडर से स्ट्रीम</strong> ऑप्शन चालू करें।",
       [("यह अकाउंट सेटिंग्स में है", "XModels एक्सटर्नल एन्कोडर ऑप्शन मॉडल अकाउंट सेटिंग्स में रखता है।"),
        ("सपोर्ट: चैट + ईमेल", "XModels के पास बड़ा पब्लिक हेल्प सेंटर नहीं है — साइट पर FAQ चैट और info@xmodels.com।"),
        ("SplitCam में ओवरले लगाएं", "टिप गोल्स, नाम और सोशल मीडिया हैंडल सीन लेयर के रूप में जोड़ें।"),
        _T_ETH],
       [("क्या XModels एक्सटर्नल एन्कोडर सपोर्ट करता है?", "हाँ — मॉडल अकाउंट सेटिंग्स में एक्सटर्नल एन्कोडर ब्रॉडकास्टिंग ऑप्शन है।"),
        ("XModels की मदद कहाँ मिलेगी?", "साइट पर FAQ चैट और ईमेल info@xmodels.com।"),
        ("XModels के लिए बिटरेट?", "1080p पर 3500–6000 Kbps।"),
        ("क्या SplitCam XModels के लिए मुफ़्त है?", "हाँ — मुफ़्त, कोई वॉटरमार्क नहीं।")]),
    _p("flirt4free", "Flirt4Free",
       "Flirt for Free cam पर SplitCam से स्ट्रीम — मुफ़्त गाइड",
       "मुफ़्त SplitCam से Flirt for Free cam स्ट्रीम — External Broadcast Form, RTMP URL और Stream Name।",
       "flirt for free cam, flirt4free, flirt4free external broadcast, flirt4free rtmp",
       '<span class="accent">Flirt4Free</span> पर SplitCam से स्ट्रीम कैसे करें',
       "Flirt4Free स्ट्रीम",
       "Flirt4Free के लिए External Broadcast Form सेटअप।",
       "Flirt4Free सबसे पुराने कैम प्लेटफ़ॉर्म में से एक है, 90 के दशक से चल रहा है। <strong style='color:var(--text)'>External Broadcast Form</strong> के ज़रिए एक्सटर्नल ब्रॉडकास्टिंग को ऑफ़िशियली सपोर्ट करता है।",
       "SplitCam से Flirt4Free स्ट्रीम: SplitCam इंस्टॉल करें, सीन बनाएं, Flirt4Free का External Broadcast Form खोलें, RTMP URL और Stream Name कॉपी करें, रेज़ॉल्यूशन/बिटरेट सेट करें, SplitCam में पेस्ट करें, Go Live।"
       "<ol><li>SplitCam इंस्टॉल करें।</li><li>कैमरा + सीन जोड़ें।</li><li>Flirt4Free का External Broadcast Form खोलें।</li><li>SplitCam में RTMP URL + Stream Name पेस्ट करें।</li><li>Go Live दबाएं।</li></ol>",
       "Flirt4Free के मॉडल एरिया में <strong>External Broadcast Form</strong> खोलें।",
       [("यह Stream Name है, की नहीं", "Flirt4Free अपनी क्रेडेंशियल्स को Stream Name कहता है।"),
        ("फ़ॉर्म में रेज़ॉल्यूशन/बिटरेट सेट करें", "External Broadcast Form के अपने रेज़ॉल्यूशन और बिटरेट फ़ील्ड हैं।"),
        ("ऐतिहासिक प्लेटफ़ॉर्म", "Flirt4Free 90 के दशक से चल रहा है।"),
        _T_ETH],
       [("क्या Flirt4Free एक्सटर्नल एन्कोडर सपोर्ट करता है?", "हाँ — ऑफ़िशियली, External Broadcast Form के ज़रिए।"),
        ("Flirt4Free का RTMP डेटा कहाँ मिलेगा?", "मॉडल एरिया में External Broadcast Form से।"),
        ("Flirt4Free के लिए बिटरेट?", "1080p पर 3500–6000 Kbps।"),
        ("क्या SplitCam Flirt4Free के लिए मुफ़्त है?", "हाँ — मुफ़्त, कोई वॉटरमार्क नहीं।")]),
    _p("mfc-alerts", "MFC Alerts",
       "SplitCam से स्ट्रीम में MFC Alerts जोड़ें",
       "MyFreeCams स्ट्रीम में एनिमेटेड टिप अलर्ट दिखाएं — मुफ़्त SplitCam में Browser लेयर के रूप में mfcalerts.com URL।",
       "mfc alerts, myfreecams alerts, mfcalerts splitcam, myfreecams tip alerts",
       'अपनी स्ट्रीम में <span class="accent">MFC Alerts</span> कैसे जोड़ें',
       "MFC Alerts जोड़ें",
       "MyFreeCams स्ट्रीम में एनिमेटेड टिप अलर्ट दिखाएं।",
       "MFC Alerts आपकी MyFreeCams स्ट्रीम में हर बार जब कोई दर्शक टिप भेजता है तो एनिमेटेड इफ़ेक्ट दिखाता है। यह मुफ़्त <strong style='color:var(--text)'>SplitCam</strong> के अंदर <strong style='color:var(--text)'>Browser लेयर</strong> के रूप में चलता है।",
       "SplitCam से MFC Alerts जोड़ें: SplitCam इंस्टॉल करें, वेबकैम जोड़ें, Browser टैब खोलें और mfcalerts.com लोड करें, अपना अलर्ट URL कॉपी करें, वेबकैम के ऊपर Browser लेयर के रूप में जोड़ें, फिर टेस्ट टिप से चेक करें।"
       "<ol><li>SplitCam इंस्टॉल करें।</li><li>वेबकैम जोड़ें।</li><li>mfcalerts.com पर URL प्राप्त करें।</li><li>वेबकैम के ऊपर Browser लेयर के रूप में जोड़ें।</li><li>टेस्ट टिप भेजें।</li></ol>",
       "SplitCam में <strong>Browser</strong> टैब खोलें और <strong>www.mfcalerts.com</strong> पर जाएं। लॉगिन या रजिस्टर करें। <strong>Copy to clipboard</strong> से अपना प्राइवेट अलर्ट URL कॉपी करें।",
       [("MFC Alerts वेबकैम के ऊपर होना चाहिए", "सबसे आम गलती: अगर MFC Alerts लेयर सोर्स लिस्ट में वेबकैम के नीचे है, इफ़ेक्ट छिपा रहता है। इसे ऊपर ले जाएं।"),
        ("mfcalerts.com अकाउंट ज़रूरी है", "अलर्ट URL प्राइवेट है — अगर अकाउंट नहीं है तो पहले mfcalerts.com पर रजिस्टर करें।"),
        ("लाइव से पहले टेस्ट टिप भेजें", "Settings → Send test tip से चेक करें।"),
        _T_ETH],
       [("MFC Alerts क्या है?", "MyFreeCams के लिए नोटिफ़िकेशन सिस्टम जो दर्शक टिप भेजने पर आपकी स्ट्रीम में वीडियो इफ़ेक्ट दिखाता है।"),
        ("मेरा MFC Alerts क्यों नहीं दिख रहा?", "लगभग हमेशा लेयर ऑर्डर की समस्या होती है।"),
        ("क्या MFC Alerts के लिए अकाउंट चाहिए?", "हाँ — mfcalerts.com पर रजिस्टर करें।"),
        ("क्या SplitCam इसके लिए मुफ़्त है?", "हाँ — मुफ़्त, कोई वॉटरमार्क नहीं।")],
       steps=[
           ("SplitCam इंस्टॉल करें और वेबकैम जोड़ें", "Windows या macOS के लिए मुफ़्त SplitCam इंस्टॉल करें, फिर <strong>वेबकैम</strong> सोर्स के रूप में जोड़ें।"),
           ("Browser टैब खोलें और mfcalerts.com पर जाएं", "SplitCam में <strong>Browser</strong> टैब खोलें और <strong>www.mfcalerts.com</strong> पर जाएं।"),
           ("अपना अलर्ट URL कॉपी करें", "mfcalerts.com पर <strong>Copy to clipboard</strong> से अपना प्राइवेट अलर्ट URL कॉपी करें।"),
           ("URL को Browser लेयर के रूप में जोड़ें — वेबकैम के ऊपर", "URL SplitCam की Browser विंडो में पेस्ट करें और <strong>Add</strong> क्लिक करें। सोर्स लिस्ट में <strong>MFC Alerts वेबकैम से ऊपर</strong> रखें।"),
           ("टेस्ट टिप से चेक करें", "<strong>Settings → Send test tip</strong> खोलें।"),
       ]),
    _p("lovense", "Lovense",
       "SplitCam से स्ट्रीम में Lovense टॉय जोड़ें",
       "मुफ़्त SplitCam के साथ इंटरएक्टिव Lovense टॉय कनेक्ट करें — Lovense SplitCam Toolset, टिप अलर्ट।",
       "lovense cam stream, lovense splitcam, lovense splitcam toolset",
       'अपनी स्ट्रीम में <span class="accent">Lovense टॉय</span> कैसे जोड़ें',
       "Lovense टॉय जोड़ें",
       "इंटरएक्टिव Lovense टॉय को अपनी कैम स्ट्रीम से कनेक्ट करें।",
       "आप मुफ़्त <strong style='color:var(--text)'>SplitCam</strong> से कैम स्ट्रीम चला रहे हैं और एक <strong style='color:var(--text)'>Lovense</strong> टॉय पेयर करना चाहते हैं जो टोकन पर रिएक्ट करे। Lovense आधिकारिक <strong style='color:var(--text)'>Lovense SplitCam Toolset</strong> डॉक्युमेंट करता है।",
       "Lovense टॉय स्ट्रीम में जोड़ने के लिए: SplitCam और Lovense सॉफ़्टवेयर इंस्टॉल करें, टॉय पेयर करें, Lovense को कैम प्लेटफ़ॉर्म से कनेक्ट करें, SplitCam में Lovense स्टेटस को Browser लेयर के रूप में जोड़ें, फिर सामान्य रूप से स्ट्रीम करें।"
       "<ol><li>SplitCam इंस्टॉल करें।</li><li>Lovense सॉफ़्टवेयर इंस्टॉल करें और टॉय पेयर करें।</li><li>Lovense को कैम साइट से कनेक्ट करें।</li><li>SplitCam में Lovense ओवरले जोड़ें।</li><li>Go Live दबाएं।</li></ol>",
       "Lovense Connect / Lovense Stream (ऑफ़िशियल डेस्कटॉप ऐप) इंस्टॉल करें।",
       [("ऑफ़िशियल Lovense SplitCam Toolset उपयोग करें", "Lovense SplitCam के लिए अपने इंस्टॉलेशन गाइड के साथ डेडिकेटेड toolset पब्लिश करता है।"),
        ("Lovense Cam Extension अपडेट करें", "Toolset को Lovense Cam Extension (30.1.4 या नया) चाहिए।"),
        ("टॉय को चार्ज रखें", "शो के बीच में कमज़ोर बैटरी इंटरएक्टिव पार्ट खराब करती है।"),
        ("टोकन रिएक्शन टेस्ट करें", "रूम खोलने से पहले एक छोटा टेस्ट टिप भेजें।"),
        ("वर्शन ज़रूरतें जांचें", "Lovense SplitCam Toolset को SplitCam 10.4.5 या नया चाहिए।")],
       [("क्या Lovense, SplitCam को ऑफ़िशियली सपोर्ट करता है?", "हाँ — Lovense ऑफ़िशियल «Lovense SplitCam Toolset» डॉक्युमेंट करता है।"),
        ("क्या टॉय सीधे SplitCam से कनेक्ट होता है?", "नहीं — टॉय Lovense ऐप से पेयर होता है; SplitCam Lovense ओवरले दिखाता है।"),
        ("कौन सी कैम साइट्स Lovense सपोर्ट करती हैं?", "Lovense Cam Extension आधिकारिक रूप से Chaturbate, Stripchat, BongaCams, MyFreeCams और CamSoda को सपोर्ट करता है।"),
        ("क्या स्क्रीन पर लेटेस्ट टिप दिखा सकते हैं?", "हाँ — SplitCam में Lovense widget URL को Browser लेयर के रूप में जोड़ें।")],
       steps=[
           ("SplitCam इंस्टॉल करें", "SplitCam Windows और macOS के लिए मुफ़्त लाइव स्ट्रीमिंग सॉफ़्टवेयर है।"),
           ("Lovense सॉफ़्टवेयर इंस्टॉल करें और टॉय पेयर करें", "Lovense Connect / Lovense Stream इंस्टॉल करें। टॉय ऑन करें और Bluetooth से पेयर करें।"),
           ("Lovense को कैम प्लेटफ़ॉर्म से कनेक्ट करें", "Lovense ऐप में अपना कैम अकाउंट कनेक्ट करें।"),
           ("SplitCam में Lovense ओवरले जोड़ें", "Lovense, overlay/widget URL देता है। SplitCam सीन में <strong>Browser</strong> लेयर के रूप में जोड़ें।"),
           ("सीन बनाएं और Go Live", "कैमरा और ओवरले जोड़ें, SplitCam में कैम प्लेटफ़ॉर्म का RTMP की पेस्ट करें और <strong>Go Live</strong> क्लिक करें।"),
       ]),
    _p("multistream-cams", "कई कैम साइट्स",
       "SplitCam से एक साथ कई कैम साइट्स पर स्ट्रीम करें",
       "MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat और अधिक पर एक साथ मुफ़्त SplitCam के multistream से स्ट्रीम करें। एक क्लिक, कोई वॉटरमार्क नहीं।",
       "कई कैम साइट्स पर स्ट्रीम, multistream cam sites, chaturbate और bongacams एक साथ स्ट्रीम",
       'एक साथ <span class="accent">कई कैम साइट्स</span> पर स्ट्रीम कैसे करें',
       "Multistream कैम",
       "एक साथ कई कैम साइट्स पर स्ट्रीम करें।",
       "मुफ़्त <strong style='color:var(--text)'>SplitCam</strong> एक एन्कोडिंग को <strong style='color:var(--text)'>एक साथ कई कैम साइट्स</strong> पर स्ट्रीम कर सकता है — MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat और अधिक। कोई वॉटरमार्क नहीं, एक क्लिक।",
       "एक साथ कई कैम साइट्स पर स्ट्रीम करने के लिए: SplitCam इंस्टॉल करें, सीन बनाएं, हर कैम साइट का RTMP सर्वर URL और की प्राप्त करें, सभी को SplitCam के multistream सेटिंग में जोड़ें, एक बार Go Live क्लिक करें।"
       "<ol><li>SplitCam इंस्टॉल करें।</li><li>कैमरा + सीन जोड़ें।</li><li>हर कैम साइट से RTMP की प्राप्त करें।</li><li>SplitCam multistream में सभी की जोड़ें।</li><li>एक बार Go Live दबाएं।</li></ol>",
       "हर कैम प्लेटफ़ॉर्म पर एक्सटर्नल / RTMP ब्रॉडकास्टिंग चालू करें और <strong>सर्वर URL</strong> और <strong>स्ट्रीम की</strong> कॉपी करें।",
       [("अपना अपलोड देखें", "Multistream अपलोड लोड को गुणा करता है। हर डेस्टिनेशन अपना बिटरेट उपयोग करता है।"),
        ("प्लेटफ़ॉर्म नियम जांचें", "कुछ कैम साइट्स दूसरी जगह एक साथ स्ट्रीमिंग प्रतिबंधित करती हैं।"),
        ("केबल — यहाँ गिरना नहीं चाहिए", "Multistream अपलोड लोड गुणा करता है, इसलिए एक Wi-Fi कट सभी डेस्टिनेशन एक साथ गिरा सकता है।"),
        ("हेल्थ मॉनिटर देखें", "SplitCam हर डेस्टिनेशन का स्टेटस दिखाता है।")],
       [("क्या SplitCam का multistream मुफ़्त है?", "हाँ — multistream बिल्ट-इन और मुफ़्त है, प्रति-डेस्टिनेशन कोई शुल्क नहीं।"),
        ("एक साथ कितनी कैम साइट्स पर स्ट्रीम कर सकते हैं?", "जितना आपका अपलोड बैंडविड्थ संभाल सके।"),
        ("क्या यह क्लाउड रिले उपयोग करता है?", "नहीं — SplitCam PC से हर प्लेटफ़ॉर्म के ingest तक सीधे peer-to-peer भेजता है।"),
        ("क्या multistream PC धीमा करता है?", "एन्कोडिंग एक बार होती है और दोबारा उपयोग होती है; हार्डवेयर एन्कोडिंग CPU लोड कम रखता है।")],
       steps=[
           ("SplitCam इंस्टॉल करें", "SplitCam Windows और macOS के लिए मुफ़्त लाइव स्ट्रीमिंग सॉफ़्टवेयर है जिसमें multistream बिल्ट-इन है।"),
           ("कैमरा और सीन सेट करें", "SplitCam खोलें, वेबकैम जोड़ें और ओवरले और फ़िल्टर के साथ सीन बनाएं।"),
           ("हर कैम साइट से RTMP की प्राप्त करें", "हर कैम प्लेटफ़ॉर्म पर <strong>सर्वर URL</strong> और <strong>स्ट्रीम की</strong> कॉपी करें।"),
           ("SplitCam में हर डेस्टिनेशन जोड़ें", "<strong>Stream Settings</strong> खोलें और हर कैम साइट को कस्टम RTMP डेस्टिनेशन के रूप में जोड़ें।"),
           ("एक बार Go Live क्लिक करें", "<strong>Go Live</strong> दबाएं। SplitCam एक एन्कोडिंग से हर चुनी हुई कैम साइट पर एक साथ स्ट्रीम भेजता है।"),
       ]),
]
