# -*- coding: utf-8 -*-
"""Korean (ko) content for cam-streaming-guides. Native Korean, 19 platforms."""

_T_ETH = ("유선 연결을 쓰세요", "긴 방송에서는 이더넷이 와이파이를 이깁니다 — 프레임이 끊기면 팁도 끊깁니다. "
          "방송 PC에 랜선을 연결하세요.")
_T_TEST = ("먼저 비공개로 테스트하세요", "시청자에게 방을 열기 전에 짧은 테스트 방송으로 카메라, 오디오, "
           "화면 구도, 오버레이를 점검하세요.")

def _p(slug, name, title, desc, kw, h1html, h1short, card, intro, quick, key_how, tips, faq, steps=None):
    d = {"slug": slug, "name": name, "title": title, "desc": desc, "kw": kw,
         "h1html": h1html, "h1short": h1short, "card": card, "intro": intro,
         "quick": quick, "key_how": key_how, "tips": tips, "faq": faq}
    if steps: d["steps"] = steps
    return d

PLATFORMS_KO = [
    _p("chaturbate", "Chaturbate",
       "SplitCam으로 Chaturbate 방송하기 — 토큰 & RTMP",
       "무료 SplitCam으로 Chaturbate 방송하기 — broadcast token, RTMP, 멀티캠 장면, 오버레이. 워터마크 없음, 가입 불필요.",
       "chaturbate 방송, chaturbate broadcast token, chaturbate rtmp obs, chaturbate 외부 인코더, chaturbate 라이브",
       'SplitCam으로 <span class="accent">Chaturbate</span> 방송하는 방법',
       "Chaturbate 방송",
       "외부 인코더를 쓰는 토큰 기반 Chaturbate 설정.",
       "Chaturbate는 토큰 경제 위에 세워진 최대 규모의 캠 플랫폼 중 하나입니다. 브라우저 방송 도구는 단조로운 단일 카메라일 뿐 — 무료 <strong style='color:var(--text)'>SplitCam</strong>으로 <strong style='color:var(--text)'>외부 인코더</strong>로 전환하면 같은 토큰 기반 방송에서 멀티캠 장면, 오버레이, 필터를 쓸 수 있습니다.",
       "SplitCam으로 Chaturbate 방송: SplitCam 설치, 장면 구성, Chaturbate에서 <em>Broadcast Yourself → My Broadcast</em> 열기, broadcast token 복사, SplitCam에 붙여넣기, Go Live."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>Chaturbate에서 broadcast token 복사.</li><li>SplitCam에 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "Chaturbate에서 <strong>Broadcast Yourself</strong>를 눌러 <strong>My Broadcast</strong> 페이지로 가서 <strong>View RTMP/OBS broadcast information and stream key</strong>를 엽니다. 키는 <strong>broadcast token</strong>으로 표시됩니다 — 복사하세요. 비밀번호처럼 취급하고 절대 공유하지 마세요.",
       [("토큰이 곧 키", "Chaturbate는 일반 스트림 키가 아니라 당신의 broadcast token을 씁니다. 비밀번호처럼 다루고 유출되면 재설정하세요."),
        ("여유가 넉넉함", "Chaturbate RTMP ingest는 최대 4K, 60fps, 높은 비트레이트를 받습니다 — 한계는 플랫폼이 아니라 당신의 업로드입니다. 키프레임은 2초마다."),
        _T_ETH, _T_TEST],
       [("Chaturbate는 OBS / 외부 인코더를 허용하나요?", "네 — Chaturbate는 외부 인코더를 공식 지원하며 «How do I set up OBS?» 전용 문서도 있습니다. 방송 설정의 «Use External Encoder to Broadcast»로 켜세요."),
        ("내 Chaturbate 스트림 키는 어디 있나요?", "Broadcast Yourself → My Broadcast → View RTMP/OBS broadcast information and stream key. 키가 곧 당신의 broadcast token입니다."),
        ("Chaturbate에 비트레이트는 얼마?", "1080p에서 3,500–6,000 Kbps면 충분합니다. Chaturbate 상한은 높아서 실제 한계는 업로드입니다 — 먼저 SplitCam 내장 속도 테스트를 돌리세요."),
        ("Chaturbate에 SplitCam은 무료인가요?", "네 — 완전 무료, 워터마크 없음, 시간 제한 없음: 인코더가 토큰 수익을 갉아먹지 않습니다.")]),
    _p("cam4", "CAM4",
       "SplitCam으로 CAM4 방송하기 — External Encoder",
       "무료 SplitCam으로 CAM4 방송하기 — External Encoder, 스트림 키, 지역 차단, 오버레이. 워터마크 없음.",
       "cam4 방송, cam4.com, cam4 external encoder, cam4 스트림 키, cam4 rtmp obs",
       'SplitCam으로 <span class="accent">CAM4</span> 방송하는 방법',
       "CAM4 방송",
       "지역 제어가 있는 CAM4 External Encoder.",
       "CAM4는 지역 제어가 내장된 글로벌 cam-and-earn 플랫폼으로 특정 국가에서 방송을 숨길 수 있습니다. 무료 <strong style='color:var(--text)'>SplitCam</strong>을 외부 인코더로 방송하면 기본 도구에 없는 장면 전환과 오버레이를 쓸 수 있습니다.",
       "SplitCam으로 CAM4 방송: SplitCam 설치, 장면 구성, CAM4에서 <em>Broadcast &amp; Earn Money → Start Broadcast → External Encoder</em> 열기, Get Stream Key, SplitCam에 붙여넣기, Go Live."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>CAM4에서 스트림 키 받기.</li><li>SplitCam에 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "CAM4에서 <strong>Broadcast</strong> → <strong>Broadcast &amp; Earn Money</strong> → <strong>Start Broadcast</strong>, 그다음 위쪽의 <strong>External Encoder</strong>를 누릅니다. 생년월일, 성별, 국가를 입력하고 <strong>Get Stream Key</strong>로 복사하세요. SplitCam Stream Settings의 초록 슬라이더가 연결을 의미합니다.",
       [("지역 제한을 설정하세요", "CAM4는 특정 국가·지역에서 방송을 숨길 수 있습니다 — go-live 전에 CAM4 쪽에서 설정하세요."),
        ("초록 슬라이더를 보세요", "CAM4 설정은 키가 수락되면 SplitCam Stream Settings에 초록 슬라이더를 표시합니다 — 빨강 = 키 확인."),
        ("평소보다 낮은 비트레이트", "CAM4 RTMP ingest는 영상 비트레이트를 약 3,000 Kbps로 제한합니다 — 대부분의 캠 사이트보다 낮습니다. 더 높이 강제하지 마세요."),
        _T_ETH],
       [("CAM4는 OBS / 외부 인코더를 공식 지원하나요?", "네 — CAM4는 지원 페이지에 공식 OBS Guide가 있고 최상의 경험을 위해 External Encoder를 권장합니다. SplitCam도 같은 RTMP 경로를 씁니다."),
        ("CAM4 방송을 지역 차단할 수 있나요?", "네 — CAM4에는 특정 국가에서 방송을 숨기는 지역 제한이 내장돼 있습니다. SplitCam이 아니라 CAM4에서 설정하세요."),
        ("CAM4 스트림 키는 어디 있나요?", "Broadcast → Broadcast & Earn Money → Start Broadcast → External Encoder → Get Stream Key."),
        ("CAM4에 비트레이트는 얼마?", "평균보다 낮습니다 — CAM4 RTMP ingest는 30fps에서 키프레임 1초로 약 3,000 Kbps로 제한합니다. 공식 표는 ~3,000을 넘기지 말라고 권합니다.")]),
    _p("bongacams", "BongaCams",
       "SplitCam으로 BongaCams 방송하기 — External Encoder",
       "무료 SplitCam으로 BongaCams 방송하기 — External Encoder, 멀티캠 장면, 오버레이, AI 배경. 워터마크 없음.",
       "bongacams, bongcams, bongacams 방송, bongacams external encoder, bongacams rtmp obs",
       'SplitCam으로 <span class="accent">BongaCams</span> 방송하는 방법',
       "BongaCams 방송",
       "BongaCams를 위한 External Encoder 설정.",
       "BongaCams는 글로벌 캠 플랫폼입니다. 외부 인코더 방송이 항상 켜져 있지는 않습니다 — 활성화하면 무료 <strong style='color:var(--text)'>SplitCam</strong>이 멀티캠 장면, 오버레이, AI 배경으로 방송을 제어합니다.",
       "SplitCam으로 BongaCams 방송: SplitCam 설치, 장면 구성, BongaCams에서 <em>Options → Broadcast settings → Select Encoder → External Encoder</em> 열기, URL과 키 복사, SplitCam에 붙여넣기, Go Live."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>BongaCams에서 URL과 키 받기.</li><li>SplitCam에 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "BongaCams에서 <strong>Options</strong> → <strong>Broadcast settings</strong> → <strong>Select Encoder</strong> → <strong>External Encoder</strong>를 열고 표시된 서버 URL과 스트림 키를 복사하세요. <strong>External Encoder 버튼이 없다면</strong> BongaCams 지원에 연락해 계정에 외부 인코딩을 켜달라고 요청하세요.",
       [("External Encoder 버튼이 없나요? 지원에 문의", "BongaCams는 계정별로 외부 인코딩을 켭니다 — Broadcast settings에 옵션이 없으면 지원이 활성화합니다."),
        ("해상도를 맞추세요", "BongaCams는 웹캠과 방송 해상도를 같게 맞추기를 권합니다 — 예: 둘 다 1280×720."),
        _T_ETH, _T_TEST],
       [("BongaCams에 External Encoder 버튼이 왜 안 보이나요?", "외부 인코딩은 모든 계정에서 기본으로 켜져 있지 않습니다 — BongaCams 지원에 연락해 켜면 Broadcast settings에 버튼이 나타납니다."),
        ("BongaCams 계정을 인증해야 하나요?", "네 — 방송에는 18세 이상, 나이 인증용 공식 신분증, 라이브 전 계정 승인이 필요합니다."),
        ("BongaCams에 비트레이트는 얼마?", "BongaCams RTMP ingest는 키프레임 2초로 영상 비트레이트를 약 6,000 Kbps로 제한합니다 — 1080p에서 3,500–6,000이 이상적이며 먼저 업로드를 테스트하세요."),
        ("BongaCams에 SplitCam은 무료인가요?", "네 — 완전 무료, 워터마크 없음, 시간 제한 없음이라 인코더가 BongaCams 토큰 수익을 줄이지 않습니다.")]),
    _p("stripchat", "Stripchat",
       "SplitCam으로 Stripchat 방송하기 — strip cam 설정",
       "strip cam 플랫폼 Stripchat을 무료 SplitCam으로 방송하기. 외부 소프트웨어, 토큰 기반 키, 장면, 오버레이.",
       "strip cam, stripchat live stream, stripchat 방송, stripchat external software, stripchat 스트림 키, stripchat rtmp obs",
       'SplitCam으로 <span class="accent">Stripchat</span> 방송하는 방법',
       "Stripchat 방송",
       "Stripchat 방송을 위한 외부 소프트웨어 설정.",
       "Stripchat은 상호작용에 집중한 대형 캠 플랫폼입니다. <em>external software</em> 모드는 토큰 기반 키를 줍니다 — 무료 <strong style='color:var(--text)'>SplitCam</strong>에 입력하면 단조로운 카메라 대신 장면, 오버레이, 필터로 방송할 수 있습니다.",
       "SplitCam으로 Stripchat 방송: SplitCam 설치, 장면 구성, Stripchat에서 <em>Switch to external software</em> 선택, 스트림 키 복사, SplitCam에 붙여넣기, Go Live."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>Stripchat에서 스트림 키 받기.</li><li>SplitCam에 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "Stripchat에서 <strong>Switch to external software</strong>를 선택하고 <strong>Show external software settings for the stream</strong>을 누르세요. 스트림 키를 복사합니다 — Stripchat은 이를 토큰으로 표시합니다. 비밀로 유지하세요.",
       [("사이트와 해상도를 맞추세요", "Stripchat FAQ는 경고합니다: 소프트웨어 해상도가 사이트와 정확히 같아야 하며 아니면 영상이 깨집니다. 둘을 같게 설정하세요."),
        ("최소 2 Mbps 주의", "Stripchat은 업로드 최소치로 2 Mbps를 표기하지만 — OBS 방송이나 멀티스트림에는 부족하다고 솔직히 말합니다. 훨씬 높게 잡으세요."),
        ("키는 토큰입니다", "Stripchat 스트림 키는 토큰입니다 — 정확히 복사하고 절대 공유하지 말며 유출되면 재설정하세요."),
        _T_ETH],
       [("Stripchat은 OBS / 외부 소프트웨어를 권장하나요?", "네 — 공식 Stripchat FAQ는 «최상의 영상·오디오 품질을 위해» OBS 같은 외부 방송 소프트웨어를 권장합니다. SplitCam도 같은 방식으로 작동합니다."),
        ("Stripchat을 외부 소프트웨어로 어떻게 전환하나요?", "Broadcast Center에서 Switch to External Broadcast Software (OBS)를 선택한 뒤 external software settings를 열어 스트림 키(토큰)를 표시하세요."),
        ("Stripchat에 비트레이트는 얼마?", "RTMP ingest는 키프레임 2초로 최대 ~6,000 Kbps를 받습니다. 1080p에서 3,500–6,000이 이상적이지만 — 특히 OBS 방송에서는 최소 2 Mbps보다 훨씬 높아야 합니다."),
        ("Stripchat에 SplitCam은 무료인가요?", "네 — 라이선스 비용 없음, 워터마크 없음, 시간 제한 없음: 긴 상호작용 Stripchat 쇼도 인코더 쪽 비용이 없습니다.")]),
    _p("onlyfans", "OnlyFans",
       "SplitCam으로 OnlyFans 라이브 — 인증 또는 키",
       "무료 SplitCam으로 OnlyFans 라이브 — 인증 로그인 또는 OBS Key, 멀티캠 장면, 오버레이. 워터마크 없음.",
       "onlyfans 라이브, onlyfans live stream, onlyfans 인증 splitcam, onlyfans obs key, onlyfans 방송 소프트웨어",
       'SplitCam으로 <span class="accent">OnlyFans</span> 라이브 하는 방법',
       "OnlyFans 라이브",
       "한 번 인증하거나 키를 붙여넣어 — OnlyFans 라이브.",
       "구독자를 위한 OnlyFans 라이브. SplitCam은 <strong style='color:var(--text)'>두 가지 방법</strong>으로 연결합니다 — OnlyFans 계정으로 한 번 로그인하면 SplitCam이 스트림 키를 자동으로 가져와 동기화하거나, OBS Key를 수동으로 붙여넣습니다. 둘 다 멀티캠 장면, 오버레이, 필터로 방송할 수 있습니다.",
       "SplitCam으로 OnlyFans 라이브: SplitCam 설치, 장면 구성, Stream Settings &rarr; Add Channel &rarr; OnlyFans 열고 <em>인증</em> 선택 — OnlyFans 계정으로 로그인하면 SplitCam이 키를 자동으로 가져옴 — 그다음 Go Live. 계정이 연결되면 OnlyFans 사이트를 열지 않고도 SplitCam에서 방송 매개변수를 바꿀 수 있습니다.",
       "OnlyFans에서: <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; <strong>Other</strong> 섹션에서 <strong>OBS Key</strong>를 복사하세요. 또는 SplitCam의 <strong>인증</strong> 옵션으로 로그인하면 — 키가 자동으로 가져와지고 계속 동기화됩니다.",
       [("인증 vs 스트림 키", "두 가지 연결 방법: <strong>인증</strong> (한 번 로그인, 키 자동 획득·동기화 — 가장 쉬움) 또는 <strong>스트림 키</strong> (OnlyFans → Profile → Settings → Other에서 OBS Key 복사 후 붙여넣기)."),
        ("SplitCam을 떠나지 않고 설정 변경", "인증을 쓰면 계정이 연결된 상태라 방송 중이나 후에도 SplitCam에서 OnlyFans 라이브 매개변수를 설정합니다 — OnlyFans 사이트에 들어갈 필요 없음."),
        ("소박한 비트레이트", "OnlyFans RTMP ingest는 영상 비트레이트를 약 2,500 Kbps로 제한합니다 — 대부분의 캠 사이트보다 빡빡합니다. ~2,000–2,500에서 720p–1080p를 노리세요."),
        _T_ETH],
       [("OnlyFans를 SplitCam에 어떻게 연결하나요?", "두 가지. <strong>인증</strong> — Stream Settings → Add Channel → OnlyFans → OnlyFans 계정으로 로그인하면 SplitCam이 키를 자동 획득. 또는 <strong>스트림 키</strong> — OnlyFans → Profile → Settings → Other에서 OBS Key 복사 후 붙여넣기."),
        ("사이트를 열지 않고 OnlyFans 라이브 설정을 바꿀 수 있나요?", "네 — 인증 방식에서는 SplitCam이 OnlyFans 계정에 계속 연결돼 키와 설정이 자동 동기화됩니다. onlyfans.com에 들어가지 않고 방송 중·후에 SplitCam에서 모두 바꿉니다."),
        ("OnlyFans에 비트레이트는 얼마?", "소박합니다 — OnlyFans RTMP ingest는 비트레이트를 약 2,500 Kbps로 제한해 다른 캠 플랫폼보다 훨씬 빡빡합니다. 약 2,000–2,500 Kbps에서 720p–1080p를 노리세요."),
        ("OnlyFans 라이브에 SplitCam은 무료인가요?", "네 — 무료, 워터마크 없음, 시간 제한 없음. 인코더 쪽 비용이 없습니다.")],
       steps=[
           ("SplitCam 다운로드 및 설치", "SplitCam은 Windows와 macOS용 무료 라이브 방송 소프트웨어입니다 — 가입 없음, 카드 없음, 워터마크 없음. 당신의 영상을 OnlyFans로 보내는 인코더입니다."),
           ("카메라와 장면 설정", "SplitCam을 열고 웹캠을 추가하세요. 시청자가 볼 모습대로 장면을 구성하세요 — 오버레이, 텍스트, 두 번째 카메라, 뷰티 필터나 AI 배경 모두 실시간으로 적용됩니다."),
           ("연결 — 방법 1: 인증 (권장)", "SplitCam에서 <strong>Stream Settings</strong> &rarr; <strong>Add Channel</strong> &rarr; <strong>OnlyFans</strong>를 열고 <strong>인증</strong>을 선택하세요. OnlyFans 이메일과 비밀번호로 로그인합니다. SplitCam이 계정을 연결해 스트림 키를 자동으로 가져와 동기화하고 — OnlyFans 사이트를 열지 않고도 방송 중·후에 SplitCam 안에서 OnlyFans 라이브 매개변수를 관리·변경할 수 있게 합니다."),
           ("연결 — 방법 2: 스트림 키 (수동)", "로그인하기 싫으세요? 키를 쓰세요. OnlyFans에서 <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; <strong>Other</strong> 섹션을 열고 <strong>OBS Key</strong>를 복사하세요. SplitCam에서 Add Channel &rarr; OnlyFans, 키 입력란에 붙여넣기. 이 키는 정적입니다 — 나중에 설정을 바꾸려면 OnlyFans 사이트로 돌아가세요."),
           ("Go Live", "어느 방법이든 SplitCam에서 <strong>Go Live</strong>를 누르세요. 방법 1에서는 SplitCam에서 OnlyFans 매개변수를 실시간으로 계속 조정할 수 있고, 방법 2에서는 키가 설정한 그대로 유지됩니다."),
       ]),
    _p("camplace", "CamPlace",
       "SplitCam으로 CamPlace 방송하기 — 무료 가이드",
       "무료 SplitCam으로 CamPlace 방송하기 — 외부 인코더, RTMP 키, 장면, 오버레이. 단계별, 워터마크 없음.",
       "camplace 방송, camplace broadcasting software, camplace rtmp, camplace 외부 인코더, camplace 스트림 키",
       'SplitCam으로 <span class="accent">CamPlace</span> 방송하는 방법',
       "CamPlace 방송",
       "CamPlace 방송을 위한 외부 인코더 설정.",
       "CamPlace는 캠 스트리밍 플랫폼입니다. 공개 OBS 문서가 없어서 <strong style='color:var(--text)'>위의 영상 가이드</strong>가 기준점입니다 — 무료 <strong style='color:var(--text)'>SplitCam</strong>은 표준 RTMP로 연결하고 기본 카메라에 없는 장면, 오버레이, AI 배경을 더합니다.",
       "SplitCam으로 CamPlace 방송: SplitCam 설치, 장면 구성, CamPlace에서 외부/RTMP 방송 켜기, 서버 URL과 스트림 키 복사, SplitCam에 붙여넣기, Go Live. 최신 경로는 영상을 따르세요."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>CamPlace에서 RTMP 키 받기.</li><li>SplitCam에 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "CamPlace에 로그인해 방송 설정을 여세요. 외부 인코더 / RTMP / OBS 옵션으로 전환하면 <strong>서버 URL</strong>과 <strong>스트림 키</strong>가 표시됩니다 — 둘 다 복사하세요. CamPlace는 공식 OBS 문서를 게시하지 않습니다 — <strong>위 영상</strong>이 현재 인터페이스를 통한 가장 믿을 만한 단계별 경로입니다.",
       [("공식 OBS 가이드 없음 — 영상을 쓰세요", "CamPlace에는 외부 인코더에 대한 공개 문서가 없습니다; 위 영상이 현재 경로의 기준점입니다."),
        ("표준 RTMP가 작동함", "문서화되지 않았어도 CamPlace는 표준 RTMP 서버 URL과 키를 받습니다 — SplitCam이 커스텀 RTMP 대상으로 연결합니다."),
        ("오버레이는 SplitCam에서 쌓으세요", "팁 목표, 이름, SNS 핸들을 장면 레이어로 — CamPlace 기본 카메라는 추가하지 않습니다."),
        _T_ETH],
       [("CamPlace에 공식 OBS 가이드가 있나요?", "외부 인코더에 대한 공개 문서를 찾지 못했습니다. CamPlace는 표준 RTMP URL과 키를 받으므로 SplitCam이 작동합니다 — 영상을 따르세요."),
        ("CamPlace는 외부 인코더를 지원하나요?", "네 — 표준 RTMP 스트림 키를 받으므로 SplitCam이 커스텀 RTMP 대상으로 연결합니다."),
        ("CamPlace에 비트레이트는 얼마?", "CamPlace는 공식 수치를 게시하지 않습니다 — 1080p에서 3,500–6,000 Kbps를 안전 범위로 쓰고 SplitCam 속도 테스트가 실제 상한을 정하게 하세요."),
        ("CamPlace에 SplitCam은 무료인가요?", "네 — 무료, 워터마크 없음, 시간 제한 없음. CamPlace에 자체 인코더가 없으므로 무료 RTMP 도구가 해결합니다.")]),
    _p("camsoda", "CamSoda",
       "SplitCam으로 CamSoda 라이브 — 무료 설정",
       "무료 SplitCam으로 CamSoda 라이브 — Use OBS Broadcaster, 지역 서버, 장면, 오버레이. 워터마크 없음.",
       "camsoda live, camsoda 방송, camsoda obs broadcaster, camsoda rtmp obs, camsoda live broadcast",
       'SplitCam으로 <span class="accent">CamSoda</span> 방송하는 방법',
       "CamSoda 방송",
       "CamSoda의 Use OBS Broadcaster 설정.",
       "CamSoda는 상호작용적이고 독특한 쇼 형식으로 유명한 미국 캠 플랫폼입니다. OBS 방송을 공식 지원합니다 — Go Live 페이지에 <strong style='color:var(--text)'>Use OBS Broadcaster</strong> 버튼이 있고 CamSoda 위키에 공식 OBS 가이드도 있습니다. 무료 <strong style='color:var(--text)'>SplitCam</strong>도 같은 방식으로 작동합니다.",
       "SplitCam으로 CamSoda 방송: SplitCam 설치, 장면 구성, CamSoda Go Live 페이지에서 Use OBS Broadcaster 클릭, 서버 URL과 스트림 키 복사, SplitCam에 붙여넣기, Go Live."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>CamSoda에서 Use OBS Broadcaster 클릭.</li><li>SplitCam에 서버 URL + 키 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "CamSoda <strong>Go Live</strong> 페이지에서 <strong>Use OBS Broadcaster</strong>를 클릭하세요. CamSoda가 RTMP 서버 URL과 스트림 키를 표시합니다 — 둘 다 복사하세요. 가장 가까운 지역 서버(북미, 유럽, 아시아 등)를 고르세요. 자세한 내용은 CamSoda 위키의 OBS 가이드에 있습니다.",
       [("팁을 받으려면 인증하세요", "CamSoda에서는 누구나 방송할 수 있지만, 팁을 받으려면 CamSoda 인증 절차를 마쳐야 합니다."),
        ("가장 가까운 지역 서버를 고르세요", "CamSoda는 지역 ingest 서버를 제공합니다 — 가장 가까운 곳(북미 / 유럽 / 아시아 / 남미 / 오세아니아)이 지연과 프레임 끊김을 줄입니다."),
        ("1080p / 30fps에서 상한", "CamSoda ingest는 약 1080p, 30fps, ~6,000 Kbps에 이릅니다 — 더 높이 강제하지 마세요."),
        _T_ETH],
       [("CamSoda는 OBS / 외부 인코더를 지원하나요?", "네 — 공식적으로. Go Live 페이지에 Use OBS Broadcaster 버튼이 있고 CamSoda 위키에 OBS 가이드가 있어 SplitCam이 작동합니다."),
        ("CamSoda에서 인증이 필요한가요?", "방송에는 아니오. 팁을 받으려면 예 — CamSoda는 먼저 인증 절차를 요구합니다."),
        ("CamSoda는 어떤 해상도를 지원하나요?", "30fps에서 최대 1920×1080, RTMP ingest에서 최대 약 6,000 Kbps."),
        ("CamSoda에 SplitCam은 무료인가요?", "네 — 무료, 워터마크 없음, 시간 제한 없음. CamSoda의 무료 Use OBS Broadcaster 모드와 작동하므로 전체 구성이 무료입니다.")]),
    _p("streamate", "Streamate",
       "SplitCam으로 Streamate 방송하기 — 통합 채널",
       "무료 SplitCam으로 Streamate 방송하기 — 통합 채널, SM Connect 키, 장면, 오버레이. 워터마크 없음.",
       "streamate, streamate sm connect, streamate 방송, streamate broadcasting software, streamate rtmp",
       'SplitCam으로 <span class="accent">Streamate</span> 방송하는 방법',
       "Streamate 방송",
       "Streamate는 SplitCam의 통합 채널 — 빠른 설정.",
       "Streamate는 자리 잡은 캠 플랫폼이며 — 채널 목록 안에 <strong style='color:var(--text)'>SplitCam의 사전 구성된 대상</strong>이라 수동 RTMP 입력보다 설정이 빠릅니다: Streamate 선택, 키 붙여넣기, 끝.",
       "SplitCam으로 Streamate 방송: SplitCam 설치, 장면 구성, Streamate에서 <em>SM Connect → Start Show</em>로 키 복사, SplitCam에서 <em>Stream Settings → Add Channel → Streamate</em> 열고 붙여넣기."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>SM Connect로 Streamate 키 받기.</li><li>SplitCam에서 Add Channel → Streamate.</li><li>Go Live 누르기.</li></ol>",
       "Streamate에서 <strong>SM Connect</strong>를 열고 약관에 동의한 뒤 왼쪽의 <strong>Start Show</strong>를 누르고 열린 창을 닫으세요 — 그다음 스트리밍 키를 복사합니다. SplitCam에서 <strong>Stream Settings</strong> → <strong>Add Channel</strong>을 열고 목록에서 <strong>Streamate</strong>를 골라 키를 붙여넣으세요. 초록 슬라이더가 연결을 의미합니다.",
       [("Streamate는 통합돼 있음", "수동 RTMP URL 없음 — SplitCam의 Add Channel 목록에 Streamate가 있습니다; 고르고 키만 붙여넣으세요."),
        ("SM Connect 팝업을 닫으세요", "Start Show 후 Streamate가 창을 엽니다 — 닫으세요; 스트리밍 키를 표시하는 용도일 뿐입니다."),
        ("해상도를 1080p로 고정", "SM Connect의 Video Resolution 칸이 슬그머니 1440으로 튈 수 있는데 실제로 전송되지 않고 조용히 품질을 떨어뜨립니다 — 수동으로 1080p로 설정하세요. 화면이 정지일 때 비트레이트가 떨어지는 건 정상입니다: Streamate 스트림은 적응형입니다."),
        _T_ETH, _T_TEST],
       [("Streamate는 SplitCam에 통합돼 있나요?", "네 — Streamate가 SplitCam의 Add Channel 목록에 나타납니다; 수동으로 RTMP URL을 입력하는 대신 고르면 됩니다."),
        ("Streamate 스트리밍 키는 어디 있나요?", "SM Connect → 약관 동의 → Start Show → 팝업 닫기 → 키 복사."),
        ("Streamate에 비트레이트는 얼마?", "Streamate는 하드 상한을 두지 않습니다 — 1080p에서 3,500–6,000 Kbps가 잘 작동합니다. 스트림이 적응형이라 화면 정지 시 비트레이트가 낮아지는 건 정상이며 버그가 아닙니다."),
        ("Streamate에 SplitCam은 무료인가요?", "네 — 무료, 워터마크 없음, 시간 제한 없음; Streamate가 SplitCam의 통합 채널이라 별도 인코더 비용이 없습니다.")]),
    _p("streamray", "StreamRay",
       "SplitCam으로 StreamRay cam 방송하기 — 채팅 URL",
       "무료 SplitCam으로 StreamRay cam 방송하기 — 채팅에 게시되는 URL, OBS Broadcaster 모드, 장면, 오버레이. 워터마크 없음.",
       "streamray, streamray cam, streamray 방송, streamray obs broadcaster, streamray rtmp",
       'SplitCam으로 <span class="accent">StreamRay</span> 방송하는 방법',
       "StreamRay 방송",
       "StreamRay를 위한 URL-인-채팅 외부 인코더 설정.",
       "StreamRay는 독특한 외부 인코더 설정을 씁니다 — 스트림 URL을 <strong style='color:var(--text)'>방송 채팅 창</strong>에 보내고 별도의 스트림 키를 쓰지 않습니다. 무료 <strong style='color:var(--text)'>SplitCam</strong>이 이 URL-only 흐름을 처리합니다.",
       "SplitCam으로 StreamRay 방송: SplitCam 설치, 장면 구성, StreamRay에서 OBS Broadcaster 켜기, 채팅 창에서 스트림 URL 복사, SplitCam에 붙여넣기(키 칸은 비움), Go Live."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>채팅에서 StreamRay URL 복사.</li><li>SplitCam에 URL 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "StreamRay에서 <strong>Broadcast Now</strong>를 더블클릭하고 <strong>Other</strong> 메뉴를 열어 <strong>OBS Broadcaster</strong>를 고른 뒤 <strong>Save and Close</strong>를 누르세요. 그러면 StreamRay가 <strong>스트림 URL을 채팅 창에 게시</strong>합니다 — 거기서 복사하세요. SplitCam 스트림 키 칸은 <strong>비워두세요</strong>; StreamRay는 URL로만 인증합니다.",
       [("URL은 채팅에 있음", "StreamRay는 설정 상자에 스트림 URL을 표시하지 않습니다 — 방송 채팅 창에 게시합니다. 거기서 복사하세요."),
        ("키 칸은 비워두세요", "StreamRay는 별도 키를 쓰지 않습니다 — URL만. SplitCam 키 칸에는 아무것도 입력하지 마세요."),
        _T_ETH, _T_TEST],
       [("StreamRay 스트림 URL은 어디 있나요?", "OBS Broadcaster를 켜면 StreamRay가 채팅 창에 URL을 게시합니다 — 채팅에서 복사하세요."),
        ("StreamRay에 왜 스트림 키가 없나요?", "StreamRay는 URL로만 인증합니다 — SplitCam 키 칸은 비워두세요."),
        ("StreamRay에 비트레이트는 얼마?", "StreamRay는 공식 상한을 명시하지 않습니다 — 1080p에서 3,500–6,000 Kbps를 노리고 SplitCam 속도 테스트를 돌리세요, URL-only 흐름은 비트레이트 피드백을 주지 않으니까요."),
        ("StreamRay에 SplitCam은 무료인가요?", "네 — 무료, 워터마크 없음, 시간 제한 없음, StreamRay의 URL-only 흐름에 맞습니다: 링크 하나 붙여넣으면 라이브입니다.")]),
    _p("xlovecam", "XLoveCam",
       "SplitCam으로 XLoveCam 방송하기 — RTMP 링크 & 키",
       "무료 SplitCam으로 XLoveCam 방송하기 — RTMP 링크와 키, 지역 서버, 장면, 오버레이. 워터마크 없음.",
       "xlovecam, x love cam, xlovecam 방송, xlovecam rtmp link, xlovecam 스트림 키",
       'SplitCam으로 <span class="accent">XLoveCam</span> 방송하는 방법',
       "XLoveCam 방송",
       "XLoveCam을 위한 RTMP 링크 + 키 설정.",
       "XLoveCam은 유럽의 다국어 캠 플랫폼입니다. 계정 설정은 <strong style='color:var(--text)'>RTMP 링크</strong>와 <strong style='color:var(--text)'>스트림 키</strong>를 모두 표시합니다 — 무료 <strong style='color:var(--text)'>SplitCam</strong>이 둘 다 받아 전체 장면과 오버레이로 방송합니다.",
       "SplitCam으로 XLoveCam 방송: SplitCam 설치, 장면 구성, XLoveCam에서 <em>My Account → settings</em> 열기, RTMP 링크와 스트림 키 복사, SplitCam에 둘 다 붙여넣기, 쇼 시작."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>XLoveCam에서 RTMP 링크 + 키 복사.</li><li>SplitCam에 둘 다 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "XLoveCam에서 <strong>My Account</strong> → <strong>settings</strong>를 열면 <strong>RTMP 링크</strong>와 <strong>스트림 키</strong>가 모두 표시됩니다 — 둘 다 SplitCam의 서버 URL과 키 칸에 복사하고 XLoveCam에서 <strong>Start your show</strong>를 누르세요.",
       [("링크 그리고 키를 복사하세요", "XLoveCam은 RTMP 링크 그리고 별도의 스트림 키를 줍니다 — 하나만이 아니라 SplitCam에 둘 다 필요합니다."),
        ("다국어 시청자", "XLoveCam은 유럽적이고 다국어입니다 — 당신의 언어로 된 또렷한 텍스트 오버레이가 시청자가 당신을 찾는 데 도움이 됩니다."),
        ("가장 가까운 서버를 고르세요", "XLoveCam은 지역 RTMP 서버를 제공합니다 — 유럽, 북미, 남미, 아시아. 가장 가까운 곳이 지연과 프레임 끊김을 줄입니다."),
        _T_ETH],
       [("XLoveCam RTMP 데이터는 어디 있나요?", "My Account → settings — RTMP 링크와 키를 모두 표시합니다."),
        ("XLoveCam은 외부 인코더를 지원하나요?", "네 — RTMP 링크와 키를 제공하므로 SplitCam이 인코더로 작동합니다."),
        ("XLoveCam에 비트레이트는 얼마?", "XLoveCam은 고정 한계를 게시하지 않습니다; 1080p에서 3,500–6,000 Kbps가 이상적입니다. 가장 가까운 지역 서버 선택도 똑같이 중요합니다 — 프레임 끊김을 줄입니다."),
        ("XLoveCam에 SplitCam은 무료인가요?", "네 — 무료, 워터마크 없음, 시간 제한 없음. XLoveCam의 다국어 유럽 시청자에 닿는 데 소프트웨어 비용이 들지 않습니다.")]),
    _p("soulcams", "SoulCams",
       "SplitCam으로 SoulCams 방송하기 — OBS 설정",
       "무료 SplitCam으로 SoulCams 방송하기 — OBS 설정, RTMP 서버와 키, 멀티캠 장면, 오버레이.",
       "soul cams, soulcams, soulcams 방송, soulcams obs, soulcams rtmp, soulcams broadcast",
       'SplitCam으로 <span class="accent">SoulCams</span> 방송하는 방법',
       "SoulCams 방송",
       "SoulCams를 위한 OBS 설정.",
       "SoulCams는 OBS 설정이 <strong style='color:var(--text)'>RTMP 서버와 스트림 키를 한 창에 함께</strong> 표시하는 캠 플랫폼입니다. 둘 다 무료 <strong style='color:var(--text)'>SplitCam</strong>에 붙여넣어 멀티캠 장면과 오버레이로 방송하세요.",
       "SplitCam으로 SoulCams 방송: SplitCam 설치, 장면 구성, SoulCams에서 Go Online → Settings → OBS 클릭, 서버와 키 복사, SplitCam에 둘 다 붙여넣기, Go Live."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>SoulCams Settings → OBS 열기.</li><li>SplitCam에 서버 + 키 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "SoulCams에 로그인해 <strong>Go Online</strong>을 누른 뒤 <strong>Settings</strong> → <strong>OBS</strong>를 여세요. OBS 창에 <strong>RTMP 서버</strong>와 <strong>스트림 키</strong>가 함께 표시됩니다 — 둘 다 SplitCam에 복사하세요.",
       [("서버와 키가 나란히", "SoulCams는 RTMP 서버와 키를 같은 OBS 창에 표시합니다 — 한 번에 둘 다 가져가세요."),
        ("먼저 Go Online", "OBS 설정은 SoulCams에서 Go Online을 누른 뒤에야 나타납니다 — 인코더 데이터를 찾기 전에 먼저 하세요."),
        ("원치 않는 지역을 차단하세요", "SoulCams는 모델 쪽 지역 차단을 허용합니다 — Go Online 전에 어느 국가가 스트림을 못 보게 할지 고르세요."),
        _T_ETH, _T_TEST],
       [("SoulCams OBS 설정은 어디 있나요?", "로그인, Go Online 클릭, 그다음 Settings → OBS — RTMP 서버와 스트림 키가 함께 표시됩니다."),
        ("SoulCams는 외부 인코더를 지원하나요?", "네 — OBS 설정이 RTMP 서버와 키를 주므로 SplitCam이 작동합니다."),
        ("SoulCams에 비트레이트는 얼마?", "SoulCams는 공식 수치를 주지 않습니다 — 1080p에서 3,500–6,000 Kbps를 노리고 업로드를 테스트하세요, OBS 창이 비트레이트 가이드를 표시하지 않으니까요."),
        ("SoulCams에 SplitCam은 무료인가요?", "네 — 무료, 워터마크 없음, 시간 제한 없음이라 멀티캠 장면과 오버레이가 있는 완전한 SoulCams 쇼도 인코더 쪽 비용이 없습니다.")]),
    _p("imlive", "ImLive",
       "SplitCam으로 ImLive 쓰기 — 가상 카메라",
       "무료 SplitCam으로 Im Live 스트림 설정 — ImLive는 라이브 웹캠을 씁니다(RTMP 없음), SplitCam을 장면이 있는 가상 카메라로 연결.",
       "im live stream, imlive splitcam, imlive 방송, imlive 가상 카메라, imlive webcam, im live cam",
       'SplitCam과 함께 <span class="accent">ImLive</span> 쓰는 방법',
       "ImLive의 SplitCam",
       "ImLive를 위한 가상 카메라 설정 — RTMP 없음.",
       "ImLive는 브라우저에서 라이브 웹캠을 씁니다 — <strong style='color:var(--text)'>RTMP나 스트림 키가 없습니다</strong>. 무료 <strong style='color:var(--text)'>SplitCam</strong>은 <strong style='color:var(--text)'>가상 카메라</strong>로 연결합니다: SplitCam에서 장면을 구성한 뒤 ImLive에서 카메라로 SplitCam을 고르세요.",
       "SplitCam으로 ImLive 쓰기: SplitCam 설치, 미디어 레이어로 장면 구성, ImLive 열고 영상 채팅 시작, ImLive 설정에서 SplitCam을 웹캠과 마이크로 선택."
       "<ol><li>SplitCam 설치.</li><li>SplitCam에서 장면 구성.</li><li>ImLive에서 영상 채팅 시작.</li><li>ImLive 카메라로 SplitCam 선택.</li><li>채팅 시작.</li></ol>",
       "ImLive 사이트에 로그인해 <strong>Start Video Chat</strong>를 누른 뒤 <strong>Go To Settings</strong>를 열어 카메라와 마이크 옵션에 접근하세요. ImLive 설정에서 <strong>SplitCam</strong>을 웹캠과 마이크로 고르세요.",
       [("스트림 키 불필요", "ImLive는 RTMP가 없습니다 — 서버 URL이나 키를 찾지 마세요. SplitCam은 카메라 장치로만 선택됩니다."),
        ("SplitCam을 마이크로도 설정하세요", "카메라 외에 마이크용으로도 SplitCam을 골라 오디오 믹스와 소음 억제도 라이브에 들어가게 하세요."),
        ("라이브 전에 장면을 구성하세요", "ImLive는 SplitCam이 보내는 것을 표시합니다 — 채팅 시작 전에 레이어를 정리하세요."),
        _T_TEST],
       [("ImLive는 RTMP나 스트림 키를 쓰나요?", "둘 다 아닙니다 — ImLive는 브라우저로 라이브 웹캠을 씁니다. SplitCam이 가상 카메라로 연결되며 복사할 키가 없습니다."),
        ("ImLive에서 SplitCam을 어떻게 고르나요?", "Start Video Chat → Go To Settings → SplitCam을 웹캠과 마이크로 선택."),
        ("ImLive에서 오버레이를 쓸 수 있나요?", "네 — SplitCam 장면에서 구성하면 ImLive가 합성된 결과를 표시합니다."),
        ("ImLive에 SplitCam은 무료인가요?", "네 — 무료, 워터마크 없음, 시간 제한 없음. ImLive용 가상 카메라로서 영상 채팅에 비용이나 브랜딩을 더하지 않습니다.")],
       steps=[
           ("SplitCam 설치", "SplitCam은 Windows와 macOS용 무료 소프트웨어입니다. 설치하세요 — 워터마크 없음, 가입 없음. ImLive에서는 RTMP 인코더가 아니라 <strong>가상 카메라</strong>로 작동합니다."),
           ("SplitCam에서 장면 구성", "SplitCam을 열고 <strong>Media Layers +</strong>로 웹캠과 함께 오버레이, 텍스트, 필터, AI 배경을 추가하세요. 이 합성 장면이 ImLive가 당신의 카메라로 볼 화면입니다."),
           ("ImLive에서 영상 채팅 시작", "ImLive 사이트에 로그인해 <strong>Start Video Chat</strong>를 누른 뒤 <strong>Go To Settings</strong>를 열어 카메라와 마이크 옵션에 접근하세요."),
           ("카메라로 SplitCam 선택", "ImLive 설정에서 <strong>SplitCam</strong>을 웹캠과 마이크로 고르세요. 이제 ImLive는 단조로운 웹캠이 아니라 당신의 완전한 SplitCam 장면을 표시합니다."),
           ("Free Live Chat 시작", "ImLive에서 <strong>Free Live Chat</strong>를 눌러 라이브로 가세요. 도중에 모습을 바꾸려면 SplitCam에서 장면을 편집하세요 — ImLive가 즉시 업데이트됩니다."),
       ]),
    _p("vxlive", "VXLive",
       "SplitCam으로 VXLive 방송하기 — 공식 지원",
       "무료 SplitCam으로 VXLive (VXModels / VISIT-X) 방송하기 — 공식 VISIT-X 프리셋, 서버와 키, 장면. 워터마크 없음.",
       "vxlive, visit-x, vxmodels splitcam, vxlive 방송, visit-x stream, vxlive rtmp",
       'SplitCam으로 <span class="accent">VXLive</span> 방송하는 방법',
       "VXLive 방송",
       "VXLive는 SplitCam을 공식 지원(VISIT-X 프리셋).",
       "VXLive (VXModels / VISIT-X)는 독일 시장의 캠 플랫폼이며 — <strong style='color:var(--text)'>SplitCam을 이름으로 공식 지원</strong>하는 몇 안 되는 곳 중 하나입니다. VXModels는 <strong style='color:var(--text)'>SplitCam</strong>을 VXLive에 연결하는 전용 도움말 문서를 두고 있고, SplitCam은 VISIT-X를 바로 쓸 수 있는 채널 프리셋으로 제공합니다.",
       "SplitCam으로 VXLive 방송: SplitCam 설치, 장면 구성, VXLive에서 «Stream with third-party software» 선택, 서버 URL과 키 복사, SplitCam에서 VISIT-X 프리셋 선택 후 붙여넣기, SplitCam에서 Go Live, 그다음 VXLive에서 GO ONLINE."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>VXLive에서 서버 URL + 키 받기.</li><li>SplitCam에서 VISIT-X 프리셋 선택, 붙여넣기.</li><li>Go Live, 그다음 VXLive에서 GO ONLINE.</li></ol>",
       "VXLive에서 <strong>Stream with third-party software</strong>를 선택하고 <strong>OBS, SplitCam 또는 XSplit</strong> 옵션을 고르세요. VXLive가 <strong>서버 URL</strong>과 <strong>스트림 키</strong>를 줍니다. SplitCam에서 스트리밍 플랫폼으로 <strong>VISIT-X</strong>를 골라 둘 다 붙여넣고 SplitCam에서 <strong>Go Live</strong>를 누른 뒤 VXLive에서 <strong>GO ONLINE</strong>을 누르세요.",
       [("VISIT-X는 통합 프리셋", "원시 RTMP URL을 입력하지 마세요 — SplitCam의 플랫폼 목록에 VISIT-X가 있습니다; 골라서 서버 URL과 키를 붙여넣으면 됩니다."),
        ("2단계 go-live", "VXLive에서는 먼저 SplitCam에서 Go Live, 그다음 VXLive에서 GO ONLINE — 둘 다, 이 순서로."),
        ("독일 시장", "VXLive 시청자는 대부분 독일어 사용자입니다 — 독일어 텍스트 오버레이나 제목이 시청자와 연결되는 데 도움이 됩니다."),
        _T_ETH],
       [("VXLive는 SplitCam을 공식 지원하나요?", "네 — VXModels (VXLive)는 SplitCam 설정 전용 공식 도움말 문서를 유지하며 SplitCam을 OBS, XSplit과 함께 지원 방송 소프트웨어로 명시합니다."),
        ("SplitCam을 VXLive에 어떻게 연결하나요?", "VXLive에서 «Stream with third-party software»를 선택한 뒤 SplitCam에서 VISIT-X 프리셋을 골라 VXLive가 준 서버 URL과 스트림 키를 붙여넣으세요."),
        ("SplitCam에서 라이브하나요, VXLive에서 하나요?", "둘 다 — 먼저 SplitCam에서 Go Live, 그다음 VXLive에서 GO ONLINE."),
        ("VXModels는 왜 SplitCam을 권하나요?", "VXModels 공식 도움말은 웹캠 이미지 아티팩트와 픽셀화를 없애고 연결을 안정화하기 위해 SplitCam을 특정해 권합니다 — 단순한 범용 인코더가 아닙니다.")]),
    _p("virtwish", "VirtWish",
       "SplitCam으로 VirtWish 방송하기 — 스트림 URL & 키",
       "무료 SplitCam으로 VirtWish 방송하기 — OBS Profile → Start Broadcast 섹션, 스트림 URL과 키, 장면, 오버레이.",
       "virtwish, virtwish 방송, virtwish broadcasting software, virtwish rtmp, virtwish 스트림 키, virtwish obs",
       'SplitCam으로 <span class="accent">VirtWish</span> 방송하는 방법',
       "VirtWish 방송",
       "VirtWish를 위한 스트림 URL + 키 설정.",
       "VirtWish는 상호작용 캠 플랫폼입니다. 방송 설정은 OBS 섹션에서 <strong style='color:var(--text)'>별도의 스트림 URL과 스트림 키</strong>를 줍니다 — 무료 <strong style='color:var(--text)'>SplitCam</strong>이 둘 다 받아 장면과 오버레이로 쇼를 진행합니다.",
       "SplitCam으로 VirtWish 방송: SplitCam 설치, 장면 구성, VirtWish에서 <em>Profile → Start Broadcast</em>로 OBS 섹션까지 가기, 링크와 키 복사, SplitCam에 둘 다 붙여넣기, Go Live."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>VirtWish에서 URL + 키 받기.</li><li>SplitCam에 둘 다 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "VirtWish에서 오른쪽 위 아이콘 → <strong>Profile</strong> → <strong>Start Broadcast</strong>를 누른 뒤 OBS 섹션에 닿도록 <strong>Start Broadcast</strong>를 한 번 더 누르세요. <strong>첫 줄의 링크</strong>를 SplitCam의 Stream URL 칸에, 별도의 <strong>Stream Key</strong>를 키 칸에 복사하세요.",
       [("링크는 첫 줄에 있음", "VirtWish OBS 섹션은 스트림 URL을 첫 줄에 둡니다 — SplitCam Stream URL에 복사한 뒤 별도 키를 복사하세요."),
        ("Start Broadcast 두 번 클릭", "OBS 섹션에 닿으려면 VirtWish에서 Start Broadcast를 두 번 누릅니다 — 정상이며 버그가 아닙니다."),
        _T_ETH, _T_TEST],
       [("VirtWish RTMP 데이터는 어디 있나요?", "오른쪽 위 아이콘 → Profile → Start Broadcast 두 번 → OBS 섹션이 링크와 스트림 키를 표시합니다."),
        ("VirtWish는 외부 인코더를 지원하나요?", "네 — OBS 섹션이 스트림 URL과 키를 제공하므로 SplitCam이 작동합니다."),
        ("VirtWish에 비트레이트는 얼마?", "VirtWish는 공식 상한을 게시하지 않습니다; 1080p에서 3,500–6,000 Kbps가 안전합니다. 재스케일을 피하려면 SplitCam 해상도를 VirtWish에 설정한 값과 맞추세요."),
        ("VirtWish에 SplitCam은 무료인가요?", "네 — 무료, 워터마크 없음, 시간 제한 없음. VirtWish의 URL-과-키 설정은 필요한 몇 분만 걸립니다.")]),
    _p("xmodels", "XModels",
       "SplitCam으로 XModels 방송하기 — 무료 가이드",
       "무료 SplitCam으로 XModels 방송하기 — 모델 계정 설정의 외부 인코더 옵션, RTMP 키, 장면, 오버레이.",
       "xmodels, xmodels 방송, xmodels broadcasting software, xmodels rtmp, xmodels 외부 인코더",
       'SplitCam으로 <span class="accent">XModels</span> 방송하는 방법',
       "XModels 방송",
       "XModels 방송을 위한 외부 인코더 설정.",
       "XModels는 모델 계정 설정에 <strong style='color:var(--text)'>외부 인코더 옵션</strong>이 내장된 캠 스트리밍 플랫폼입니다. 무료 <strong style='color:var(--text)'>SplitCam</strong>은 단조로운 단일 카메라 대신 멀티캠 장면, 오버레이, 필터로 방송합니다.",
       "SplitCam으로 XModels 방송: SplitCam 설치, 장면 구성, XModels 모델 계정에서 외부 인코더 옵션 켜기, 서버 URL과 스트림 키 복사, SplitCam에 붙여넣기, Go Live."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>XModels 설정에서 외부 인코더 켜기.</li><li>SplitCam에 서버 URL + 키 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "XModels <strong>모델 계정 설정</strong>에서 <strong>외부 인코더로 방송</strong> 옵션을 켜세요. XModels가 <strong>스트림 키</strong>를 제공합니다 — SplitCam에 복사하세요. 예상한 곳에 옵션이 없으면 XModels 지원은 사이트의 FAQ 채팅과 <strong>info@xmodels.com</strong>으로 받으세요; 위 영상도 보여줍니다.",
       [("계정 설정에 있음", "XModels는 외부 인코더 옵션을 별도 방송 화면이 아니라 모델 계정 설정에 둡니다."),
        ("지원: 채팅 + 이메일", "XModels에는 큰 공개 도움말 센터가 없습니다 — 사이트의 FAQ 채팅과 info@xmodels.com이 공식 지원 채널입니다."),
        ("오버레이는 SplitCam에서 쌓으세요", "팁 목표, 이름, SNS 핸들을 장면 레이어로 — XModels 기본 카메라는 추가하지 않습니다."),
        _T_ETH],
       [("XModels는 외부 인코더를 지원하나요?", "네 — 모델 계정 설정에 스트림 키를 제공하는 외부 인코더 방송 옵션이 있어 SplitCam이 작동합니다."),
        ("XModels 도움은 어디서 받나요?", "XModels 지원은 사이트의 FAQ 채팅과 이메일 info@xmodels.com으로 받습니다 — 큰 공개 도움말 센터는 없습니다."),
        ("XModels에 비트레이트는 얼마?", "XModels는 공식 수치를 문서화하지 않습니다 — 1080p에서 3,500–6,000 Kbps를 쓰고 SplitCam 속도 테스트를 돌리세요, 지원이 채팅과 이메일뿐이니까요."),
        ("XModels에 SplitCam은 무료인가요?", "네 — 무료, 워터마크 없음, 시간 제한 없음이라 XModels 유럽 네트워크로 방송하는 데 소프트웨어 비용이 더해지지 않습니다.")]),
    _p("flirt4free", "Flirt4Free",
       "SplitCam으로 Flirt for Free cam 방송하기 — 무료 가이드",
       "무료 SplitCam으로 Flirt for Free cam 방송하기 — External Broadcast Form, RTMP URL과 Stream Name, 장면, 오버레이.",
       "flirt for free cam, flirt 4 free cam, flirt4free, flirt4free 방송, flirt4free external broadcast, flirt4free rtmp",
       'SplitCam으로 <span class="accent">Flirt4Free</span> 방송하는 방법',
       "Flirt4Free 방송",
       "Flirt4Free를 위한 External Broadcast Form 설정.",
       "Flirt4Free는 90년대부터 방송한 가장 오래된 캠 플랫폼 중 하나입니다. <strong style='color:var(--text)'>External Broadcast Form</strong>으로 외부 방송을 공식 지원합니다 — 무료 <strong style='color:var(--text)'>SplitCam</strong>이 스트림을 보내고 폼이 해상도와 비트레이트를 설정합니다.",
       "SplitCam으로 Flirt4Free 방송: SplitCam 설치, 장면 구성, Flirt4Free External Broadcast Form 열기, RTMP URL과 Stream Name 복사 및 해상도/비트레이트 설정, SplitCam에 붙여넣기, Go Live."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>Flirt4Free External Broadcast Form 열기.</li><li>SplitCam에 RTMP URL + Stream Name 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "Flirt4Free 모델 영역에서 <strong>External Broadcast Form</strong>을 여세요. 대부분의 캠 사이트와 달리 Flirt4Free는 («키»가 아니라) <strong>RTMP URL</strong>과 <strong>Stream Name</strong>을 주고 폼 자체에서 채우는 해상도·비트레이트 칸도 있습니다. URL과 Stream Name을 SplitCam의 서버와 키 칸에 복사하세요.",
       [("키가 아니라 Stream Name", "Flirt4Free는 자격 정보를 Stream Name이라 부릅니다. SplitCam 스트림 키 칸에 붙여넣습니다 — 기능은 같습니다."),
        ("폼에서 해상도/비트레이트를 설정하세요", "Flirt4Free External Broadcast Form에는 자체 해상도·비트레이트 칸이 있습니다 — 화면이 재스케일되지 않도록 SplitCam 설정과 맞추세요."),
        ("역사 있는 플랫폼", "Flirt4Free는 90년대부터 운영됐습니다 — 모델 도구가 성숙했고 External Broadcast Form은 문서화된 일부입니다."),
        _T_ETH],
       [("Flirt4Free는 외부 인코더를 지원하나요?", "네 — RTMP URL과 Stream Name을 제공하는 External Broadcast Form으로 공식 지원합니다. SplitCam이 인코더로 작동합니다."),
        ("Flirt4Free RTMP 데이터는 어디서 받나요?", "모델 영역의 External Broadcast Form에서 — RTMP URL, Stream Name, 해상도/비트레이트 칸을 표시합니다."),
        ("Flirt4Free에 비트레이트는 얼마?", "1080p에서 3,500–6,000 Kbps — External Broadcast Form과 SplitCam에 같은 값을 설정하세요."),
        ("Flirt4Free에 SplitCam은 무료인가요?", "네 — 무료, 워터마크 없음, 시간 제한 없음이라 쇼가 길어질 수 있는 Flirt4Free 같은 역사적 플랫폼에 맞습니다.")]),
    _p("mfc-alerts", "MFC Alerts",
       "SplitCam으로 방송에 MFC Alerts 추가하기",
       "MyFreeCams 방송에 애니메이션 팁 알림 표시 — 무료 SplitCam에서 mfcalerts.com URL을 웹캠 위 Browser 레이어로.",
       "mfc alerts, myfreecams alerts, mfc alerts 추가, mfcalerts splitcam, myfreecams tip alerts, myfreecams alerts overlay",
       '방송에 <span class="accent">MFC Alerts</span> 추가하는 방법',
       "MFC Alerts 추가",
       "MyFreeCams 방송에 애니메이션 팁 알림 표시.",
       "MFC Alerts는 시청자가 팁을 보낼 때마다 MyFreeCams 방송에 애니메이션 효과를 표시합니다. 무료 <strong style='color:var(--text)'>SplitCam</strong> 안의 <strong style='color:var(--text)'>Browser 레이어</strong>로 작동합니다 — 한 번 설정하면 팁이 실시간으로 화면 반응을 일으킵니다.",
       "SplitCam으로 MFC Alerts 추가: SplitCam 설치, 웹캠 추가, Browser 탭 열고 mfcalerts.com 로드, 알림 URL 복사, 웹캠 위 Browser 레이어로 추가, 테스트 팁으로 점검."
       "<ol><li>SplitCam 설치.</li><li>웹캠 추가.</li><li>mfcalerts.com에서 URL 받기.</li><li>웹캠 위 Browser 레이어로 추가.</li><li>테스트 팁 보내기.</li></ol>",
       "SplitCam에서 <strong>Browser</strong> 탭을 열고 <strong>www.mfcalerts.com</strong>에 접속하세요. 로그인하거나 가입합니다. <strong>Copy to clipboard</strong>로 개인 알림 URL을 복사하세요. URL을 SplitCam Browser 창에 붙여넣고 <strong>Add</strong>를 누른 뒤 소스 목록을 정리해 <strong>MFC Alerts가 웹캠 위</strong>에 오게 하세요(점 3개 메뉴 → Move Up).",
       [("MFC Alerts는 웹캠 위에 있어야 함", "가장 흔한 실수: 소스 목록에서 MFC Alerts 레이어가 웹캠 아래에 있으면 효과가 숨겨집니다. 위로 옮기세요."),
        ("mfcalerts.com 계정 필요", "알림 URL은 개인용입니다 — 계정이 없으면 먼저 mfcalerts.com에 가입하세요."),
        ("라이브 전에 테스트 팁을 보내세요", "Settings → Send test tip으로 오버레이가 작동하는지 확인하세요 — 쇼 도중에 오류를 발견하지 마세요."),
        _T_ETH],
       [("MFC Alerts가 무엇인가요?", "MyFreeCams용 알림 시스템으로 시청자가 팁을 보낼 때 방송에 영상 효과를 표시합니다 — SplitCam에 Browser 오버레이로 추가됩니다."),
        ("내 MFC Alerts가 왜 안 보이나요?", "거의 항상 레이어 순서입니다 — MFC Alerts Browser 레이어가 SplitCam 소스 목록에서 웹캠 위에 있어야 합니다."),
        ("MFC Alerts에 계정이 필요한가요?", "네 — 개인 알림 URL을 받으려면 mfcalerts.com에 가입하세요."),
        ("이걸 위해 SplitCam은 무료인가요?", "네 — SplitCam은 무료, 워터마크 없음, 시간 제한 없음이고 MFC Alerts 브라우저 오버레이가 그 안에서 추가 비용 없이 작동합니다.")],
       steps=[
           ("SplitCam 설치 및 웹캠 추가", "Windows나 macOS용 무료 SplitCam을 설치한 뒤 <strong>웹캠</strong>을 소스로 추가하세요. MFC Alerts는 이 카메라 위 레이어로 놓입니다."),
           ("Browser 탭 열고 mfcalerts.com 접속", "SplitCam에서 <strong>Browser</strong> 탭을 열고 <strong>www.mfcalerts.com</strong>에 접속하세요. 로그인하거나, mfcalerts.com 계정이 없으면 가입하세요."),
           ("알림 URL 복사", "mfcalerts.com에서 <strong>Copy to clipboard</strong>로 개인 알림 URL을 복사하세요 — 팁 애니메이션을 렌더링하는 페이지입니다."),
           ("URL을 Browser 레이어로 추가 — 웹캠 위", "URL을 SplitCam Browser 창에 붙여넣고 <strong>Add</strong>를 누르세요. 그다음 소스 목록을 정리해 <strong>MFC Alerts가 웹캠 위</strong>에 오게 하세요(점 3개 메뉴 → Move Up). 아래에 있으면 효과가 숨겨집니다."),
           ("테스트 팁으로 점검", "<strong>Settings → Send test tip</strong>을 열어 알림 효과가 카메라 위에 나타나는지 확인하세요. 그다음 MyFreeCams에서 평소처럼 방송하면 — 실제 팁이 애니메이션을 일으킵니다."),
       ]),
    _p("lovense", "Lovense",
       "SplitCam으로 방송에 Lovense 토이 추가하기",
       "무료 SplitCam으로 상호작용 Lovense 토이를 캠 방송에 연결 — Lovense SplitCam Toolset, 화면 팁 알림, 반응.",
       "방송에 lovense 추가, lovense cam stream, lovense splitcam, lovense splitcam toolset, lovense interactive toy streaming",
       '방송에 <span class="accent">Lovense 토이</span> 추가하는 방법',
       "Lovense 토이 추가",
       "상호작용 Lovense 토이를 캠 방송에 연결.",
       "무료 <strong style='color:var(--text)'>SplitCam</strong>으로 캠 방송을 하면서 토큰에 반응하는 <strong style='color:var(--text)'>Lovense</strong> 토이를 페어링합니다. Lovense는 공식 <strong style='color:var(--text)'>Lovense SplitCam Toolset</strong>을 문서화하고, SplitCam은 공식 Lovense 플러그인을 제공합니다 — 통합이 양쪽에서 지원됩니다.",
       "방송에 Lovense 토이 추가: SplitCam과 Lovense 소프트웨어 설치, 토이 페어링, Lovense를 캠 플랫폼에 연결, SplitCam에 Lovense 상태를 Browser 레이어로 추가, 평소처럼 방송."
       "<ol><li>SplitCam 설치.</li><li>Lovense 소프트웨어 설치 및 토이 페어링.</li><li>Lovense를 캠 사이트에 연결.</li><li>SplitCam에 Lovense 오버레이 추가.</li><li>Go Live 누르기.</li></ol>",
       "Lovense Connect / Lovense Stream(공식 데스크톱 앱)을 설치하세요. 토이를 켜고 블루투스로 페어링해 앱이 연결됨을 표시하게 하세요. Lovense 앱에서 캠 계정을 연결해 토이가 시청자의 토큰 / 팁에 반응하게 하세요. Lovense가 오버레이 / 위젯 URL을 제공합니다 — SplitCam 장면에 <strong>Browser</strong> 레이어로 추가하세요.",
       [("공식 Lovense SplitCam Toolset을 쓰세요", "Lovense는 SplitCam 전용 toolset을 자체 설치 가이드와 함께 게시합니다 — SplitCam용으로 만든 토이 활동 오버레이와 팁 알림을 더합니다."),
        ("Lovense Cam Extension을 업데이트하세요", "Toolset은 최신 Lovense Cam Extension(30.1.4 이상)이 필요합니다 — 라이브 전에 업데이트하세요."),
        ("토이를 충전해 두세요", "쇼 도중 배터리가 떨어지면 상호작용이 망가집니다 — 라이브 전에 완충하세요."),
        ("토큰 반응을 테스트하세요", "방을 열기 전에 작은 테스트 팁을 보내 토이가 반응하는지 확인하세요."),
        ("버전 요구사항을 확인하세요", "Lovense SplitCam Toolset은 SplitCam 10.4.5 이상이 필요합니다. Lovense Cam Extension은 Chaturbate, Stripchat, BongaCams, MyFreeCams, CamSoda를 공식 포함합니다 — 다른 사이트는 Lovense Generic URL 통합을 쓰세요.")],
       [("Lovense는 SplitCam을 공식 지원하나요?", "네 — Lovense는 자체 설치 가이드가 있는 공식 «Lovense SplitCam Toolset»을 문서화하고, SplitCam은 공식 Lovense 플러그인을 제공합니다. 통합이 양쪽에서 지원됩니다."),
        ("토이가 SplitCam에 직접 연결되나요?", "아니오 — 토이는 Lovense 앱과 페어링되고, SplitCam은 Lovense 오버레이를 표시하며 카메라를 방송합니다."),
        ("어떤 캠 사이트가 Lovense를 지원하나요?", "Lovense Cam Extension은 Chaturbate, Stripchat, BongaCams, MyFreeCams, CamSoda를 공식 지원하며 다른 곳은 지원이 다릅니다 — Lovense 앱에서 최신 목록을 확인하세요."),
        ("최근 팁을 화면에 표시할 수 있나요?", "네 — Lovense 위젯 URL을 SplitCam에 Browser 레이어로 추가하세요.")],
       steps=[
           ("SplitCam 설치", "SplitCam은 Windows와 macOS용 무료 라이브 방송 소프트웨어입니다 — 당신의 영상을 캠 플랫폼으로 보내는 인코더입니다. 설치하세요; 워터마크 없음."),
           ("Lovense 소프트웨어 설치 및 토이 페어링", "Lovense Connect / Lovense Stream(공식 데스크톱 앱)을 설치하세요. 토이를 켜고 블루투스로 페어링해 앱이 연결됨을 표시하게 하세요."),
           ("Lovense를 캠 플랫폼에 연결", "Lovense 앱에서 캠 계정을 연결해 토이가 시청자의 토큰 / 팁에 반응하게 하세요. 대부분의 주요 캠 플랫폼이 지원됩니다."),
           ("SplitCam에 Lovense 오버레이 추가", "Lovense가 오버레이 / 위젯 URL을 제공합니다. SplitCam 장면에 <strong>Browser</strong> 레이어로 추가해 시청자가 토이 상태와 최근 팁을 화면에서 보게 하세요."),
           ("장면 구성 후 Go Live", "카메라와 다른 오버레이를 추가하고 캠 플랫폼의 RTMP 키를 SplitCam에 붙여넣은 뒤 <strong>Go Live</strong>를 누르세요. 토이가 팁에 실시간으로 반응합니다."),
       ]),
    _p("multistream-cams", "여러 캠 사이트",
       "SplitCam으로 여러 캠 사이트에 동시 방송하기",
       "SplitCam 무료 멀티스트림으로 MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat 등에 동시 방송. 한 번 클릭, 워터마크 없음.",
       "여러 캠 사이트에 방송, multistream cam sites, chaturbate와 bongacams 동시 방송, 멀티스트림 캠 소프트웨어",
       '<span class="accent">여러 캠 사이트</span>에 동시 방송하는 방법',
       "멀티스트림 캠",
       "여러 캠 사이트에 동시 방송.",
       "무료 <strong style='color:var(--text)'>SplitCam</strong>은 하나의 인코딩을 <strong style='color:var(--text)'>여러 캠 사이트에 동시</strong>로 방송할 수 있습니다 — MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat 등. 워터마크 없음, 한 번 클릭.",
       "여러 캠 사이트에 동시 방송: SplitCam 설치, 장면 구성, 각 캠 사이트의 RTMP 서버 URL과 스트림 키 받기, SplitCam 멀티스트림 설정에 모두 추가, Go Live 한 번 클릭."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>각 캠 사이트에서 RTMP 키 받기.</li><li>SplitCam 멀티스트림에 모든 키 추가.</li><li>Go Live 한 번 누르기.</li></ol>",
       "각 캠 플랫폼에서 외부 / RTMP 방송을 켜고 <strong>서버 URL</strong>과 <strong>스트림 키</strong>를 복사하세요. SplitCam에서 <strong>Stream Settings</strong>를 열고 각 캠 사이트를 커스텀 RTMP 대상으로 추가하세요 — 서버 URL과 키를 붙여넣습니다. 라이브할 곳을 모두 체크하세요. <strong>Go Live</strong>를 누르세요.",
       [("당신의 업로드를 주시하세요", "멀티스트림은 업로드 부하를 배가합니다. 각 대상이 자체 비트레이트를 씁니다 — 회선이 합계를 감당하는지 확인하세요."),
        ("플랫폼 규칙을 확인하세요", "일부 캠 사이트는 다른 곳에서 동시 방송을 금지합니다 — 멀티스트림 전에 확인하세요."),
        ("랜선 — 여기선 끊기면 안 됨", "멀티스트림은 업로드 부하를 배가하므로 와이파이가 한 번 끊기면 모든 대상이 동시에 떨어질 수 있습니다. 여기서 랜선은 선택이 아닙니다."),
        ("상태 모니터를 보세요", "SplitCam은 대상별 상태를 표시합니다 — 업로드가 못 버티면 한 사이트를 떼세요.")],
       [("SplitCam 멀티스트림은 무료인가요?", "네 — 멀티스트림은 내장이며 무료, 대상별 요금 없음, 워터마크 없음."),
        ("동시에 몇 개의 캠 사이트에 방송할 수 있나요?", "업로드 대역폭이 감당하는 만큼 — 각 대상이 자체 비트레이트를 씁니다."),
        ("클라우드 릴레이를 쓰나요?", "아니오 — SplitCam은 PC에서 각 플랫폼 ingest로 직접 peer-to-peer로 스트림을 보냅니다."),
        ("멀티스트림이 PC를 느리게 하나요?", "인코딩은 한 번 하고 재사용합니다; 하드웨어 인코딩이 CPU 부하를 낮게 유지합니다. 업로드 대역폭이 진짜 한계입니다.")],
       steps=[
           ("SplitCam 설치", "SplitCam은 멀티스트림이 내장된 Windows와 macOS용 무료 라이브 방송 소프트웨어입니다. 설치하세요 — 워터마크 없음, 가입 없음."),
           ("카메라와 장면 설정", "SplitCam을 열고 웹캠을 추가한 뒤 오버레이와 필터로 장면을 구성하세요. 한 장면이 모든 대상을 공급합니다."),
           ("각 캠 사이트에서 RTMP 키 받기", "각 캠 플랫폼에서 외부 / RTMP 방송을 켜고 <strong>서버 URL</strong>과 <strong>스트림 키</strong>를 복사하세요. 방송할 각 사이트마다 반복하세요 — 정확한 경로는 각 플랫폼 가이드를 보세요."),
           ("SplitCam에 각 대상 추가", "<strong>Stream Settings</strong>를 열고 각 캠 사이트를 커스텀 RTMP 대상으로 추가하세요 — 서버 URL과 키를 붙여넣습니다. 라이브할 곳을 모두 체크하세요."),
           ("Go Live 한 번 클릭", "<strong>Go Live</strong>를 누르세요. SplitCam이 하나의 인코딩에서 선택한 각 캠 사이트로 동시에, peer-to-peer로 스트림을 보냅니다 — 추가 비용 없이."),
       ]),
    _p("livejasmin", "LiveJasmin",
       "SplitCam으로 LiveJasmin 방송하기 — HD External Encoder",
       "무료 SplitCam으로 LiveJasmin 방송하기 — Model Center External Encoder, HD 1080p 설정, 멀티캠 장면과 오버레이. 워터마크 없음, 가입 불필요.",
       "livejasmin 방송, livejasmin obs, livejasmin external encoder, livejasmin rtmp, livejasmin stream key, livejasmin 모델 설정",
       'SplitCam으로 <span class="accent">LiveJasmin</span> 방송하는 방법',
       "LiveJasmin 방송",
       "LiveJasmin의 HD-only Model Center를 위한 외부 인코더 설정.",
       "LiveJasmin은 Docler Holding의 대표 플랫폼 — 세계 최대 규모의 캠 네트워크 중 하나이며 HD-only 플랫폼입니다. 추천 방송 도구는 자체 <strong>JasminCAM</strong> 클라이언트지만, Model Center는 표준 <strong>External Encoder</strong> 경로도 함께 제공합니다 — 무료 <strong style='color:var(--text)'>SplitCam</strong>이 여기에 연결되어 같은 HD 방송에서 멀티캠 장면, 뷰티 필터, 오버레이를 쓸 수 있게 해줍니다.",
       "SplitCam으로 LiveJasmin 방송: SplitCam 설치, HD 장면 구성, Model Center에서 <em>Settings → Broadcast → External Encoder</em> 열기, 서버 URL과 stream key 복사, SplitCam에 붙여넣기, Go Live."
       "<ol><li>SplitCam 설치.</li><li>카메라 + HD 장면 추가.</li><li>Model Center에서 URL과 stream key 받기.</li><li>SplitCam에 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "<strong>modelcenter.livejasmin.com</strong>에 로그인하고 <strong>Settings → Broadcast → External Encoder</strong>를 엽니다. Model Center가 계정에 묶인 <strong>서버 URL</strong>과 <strong>stream key</strong>를 표시합니다 — 둘 다 SplitCam의 커스텀 RTMP 필드에 복사하세요. <strong>참고:</strong> 신규 계정은 승인(48–72시간)이 끝나야 External Encoder 옵션이 나타나며, 플랫폼은 HD-only 출력을 강제합니다.",
       [("HD가 아니면 랭킹이 떨어집니다", "LiveJasmin은 HD-only — 1280×720 미만이면 저단가 리스트에만 노출되고, 1080p 미만이면 «Premium» 자격을 잃습니다. 1920×1080, 30 fps, 4,000–6,000 Kbps를 목표로."),
        ("JasminCAM vs 외부 인코더", "Docler 자체 JasminCAM 클라이언트가 HD 준수 면에서 가장 깔끔하지만, 계정이 승인되면 OBS, SplitCam, vMix 같은 외부 인코더도 공식 지원됩니다 — JasminCAM이 못 하는 멀티캠 장면과 오버레이가 풀립니다."),
        ("Free chat ≠ Private show", "Free chat은 미리보기 전용 — 노출 금지입니다. 모델이 실제로 버는 곳은 Private과 Gold show입니다. 옷을 입은 상태와 쇼 모드 양쪽에서 강해 보이도록 장면을 설계하세요."),
        _T_ETH],
       [("LiveJasmin은 SplitCam 같은 외부 인코더를 공식 지원하나요?", "네 — Model Center는 Settings → Broadcast에 External Encoder 옵션이 있습니다. JasminCAM이 추천 클라이언트이지만, 모델 계정이 승인되면 OBS, SplitCam, 기타 RTMP 인코더가 명시적으로 지원 대상에 포함됩니다."),
        ("내 LiveJasmin stream key는 어디 있나요?", "Model Center 안: Settings → Broadcast → External Encoder. 서버 URL과 고유 stream key가 모두 여기 표시됩니다 — 둘 다 SplitCam의 커스텀 RTMP 필드에 복사하세요. 이 key는 계정에 묶여 있으니 비밀번호처럼 다루세요."),
        ("LiveJasmin에 비트레이트는 얼마?", "LiveJasmin은 HD-only — 1920×1080, 30 fps, 4,000–6,000 Kbps, 키프레임 2초 간격을 목표로 하세요. 눈에 띄게 이보다 낮으면 Premium 라벨을 잃고 랭킹이 떨어집니다."),
        ("LiveJasmin에 SplitCam은 무료인가요?", "네 — SplitCam은 무료, 워터마크 없음, 시간 제한 없음. 유일한 «비용»은 LiveJasmin의 HD 요건을 충족하는 것인데, SplitCam의 1080p 장면 합성과 뷰티 필터가 네이티브로 처리합니다.")],
       steps=[
           ("SplitCam 다운로드 및 설치", "SplitCam은 Windows와 macOS용 무료 라이브 방송 소프트웨어 — 가입 없음, 카드 없음, 워터마크 없음. HD 영상을 LiveJasmin으로 보내는 인코더입니다."),
           ("HD 장면 구성", "SplitCam을 열고 웹캠을 1080p 모드로 추가하세요. 오버레이, 텍스트, 두 번째 카메라나 폰, 뷰티 필터나 AI 배경을 얹으세요 — LiveJasmin은 HD 품질을 요구하므로, 합성된 장면이 free chat과 private show 내내 프리미엄해 보여야 합니다."),
           ("LiveJasmin URL과 stream key 받기", "<strong>modelcenter.livejasmin.com</strong>에 로그인하세요(계정이 먼저 승인되어야 합니다 — 보통 가입 후 48–72시간). <strong>Settings → Broadcast → External Encoder</strong>를 여세요. 페이지에 <strong>서버 URL</strong>과 고유 <strong>stream key</strong>가 표시됩니다. 둘 다 복사하세요."),
           ("SplitCam을 LiveJasmin에 연결", "SplitCam에서 <strong>Stream Settings</strong>를 열고 LiveJasmin 서버 URL과 stream key를 커스텀 RTMP 필드에 붙여넣으세요. 비트레이트를 4,000–6,000 Kbps, 1920×1080, 30 fps, 2초 키프레임으로 설정하세요. 먼저 내장 속도 테스트를 돌리세요 — HD 스트림은 회선 요구가 큽니다."),
           ("Go Live 클릭", "SplitCam에서 <strong>Go Live</strong>를 누른 뒤 LiveJasmin Model Center에서 온라인으로 전환하세요. 약 10초 안에 HD 피드가 LiveJasmin 네트워크에 도달합니다. 이후 방송은 한 번의 클릭 — SplitCam 열기, Go Live, 그다음 LiveJasmin에서 온라인."),
       ]),
    _p("myfreecams", "MyFreeCams",
       "SplitCam으로 MyFreeCams(MFC) 방송하는 방법 — Model Web Broadcaster 우회",
       "무료 SplitCam으로 MyFreeCams 방송 — Model Admin External Broadcaster, MFC 토큰 경제, 멀티캠 장면, 오버레이. 워터마크 없음, 가입 불필요.",
       "myfreecams 방송, mfc external broadcaster, myfreecams obs, mfc rtmp, mfc stream key, model admin, mfc 토큰",
       'SplitCam으로 <span class="accent">MyFreeCams</span> 방송하는 방법',
       "MyFreeCams 방송",
       "MFC의 토큰제 Model Admin을 위한 외부 브로드캐스터 설정.",
       "MFC는 가장 오래된 캠 플랫폼 중 하나입니다 — 순수 토큰 경제, 모델 심사 장벽이 낮고, 충성도 높은 Premium 회원층이 강점입니다. 기본 Model Web Broadcaster는 브라우저 안에서 도는 단일 카메라 도구지만, Model Admin은 External Broadcaster 경로도 함께 노출합니다 — 무료 <strong style='color:var(--text)'>SplitCam</strong>이 여기에 붙으면 멀티캠 장면, 오버레이, 뷰티 필터가 모두 풀립니다.",
       "SplitCam으로 MyFreeCams 방송: SplitCam 설치, 장면 구성, Model Admin → Broadcaster에서 Web Broadcaster를 External Broadcaster로 전환, 서버 URL과 stream key 복사, SplitCam에 붙여넣기, Go Live."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>Model Admin에서 External Broadcaster로 전환.</li><li>URL과 stream key를 SplitCam에 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "MyFreeCams에 로그인하고 <strong>Model Admin → Broadcaster</strong>를 연 다음 <strong>Web Broadcaster</strong>에서 <strong>External Broadcaster</strong>로 전환하세요. 페이지에 모델 계정에 묶인 서버 URL(rtmp://publish.myfreecams.com…)과 stream key가 표시됩니다 — 둘 다 SplitCam의 커스텀 RTMP 필드에 복사하세요. key는 계정에 묶여 있으니 비밀번호처럼 다뤄야 합니다.",
       [("MFC는 순수 팁/토큰 경제 — 구독제가 아닙니다", "MFC의 핵심은 구독이 아니라 free chat 안의 팁입니다 — Premium 회원은 private도 갈 수 있지만, 일상 수익은 옷을 입은 free chat에서 나옵니다. 캐주얼한 상태에서도 팁이 계속 들어오는 장면 설계가 중요합니다."),
        ("Web Broadcaster vs External Broadcaster", "기본 Web Broadcaster는 단일 소스 도구입니다. External Broadcaster는 SplitCam/OBS로 멀티 장면, 오버레이, 뷰티 필터를 풉니다 — 상위 모델과 신인의 격차가 여기서 갈립니다."),
        ("mfcalerts.com으로 팁 알림을 영상에 얹기", "SplitCam에서 mfcalerts.com을 Browser 레이어로 카메라 위에 추가하세요 — 팁 애니메이션과 회원 닉네임이 영상 안에 직접 뜨면 free chat 팁 전환율이 눈에 띄게 올라갑니다."),
        _T_ETH],
       [("MFC는 SplitCam 같은 외부 방송 도구를 지원하나요?", "네 — Model Admin에 External Broadcaster 옵션이 있고 표준 RTMP라서 OBS, SplitCam, vMix 모두 사용 가능합니다."),
        ("MFC stream key는 어디 있나요?", "Model Admin → Broadcaster → External Broadcaster — 서버 URL과 stream key가 같은 페이지에 표시됩니다. 둘 다 SplitCam에 복사하세요."),
        ("MFC에 비트레이트는 얼마?", "MFC는 약 6,000 Kbps까지, 키프레임 2초 간격을 지원합니다. 1920×1080, 30 fps, 3,500–6,000 Kbps가 안정 구간입니다."),
        ("MFC에서 SplitCam은 무료인가요?", "네 — SplitCam은 완전 무료, 워터마크 없음, 시간 제한 없음.")],
       steps=[
           ("SplitCam 다운로드 및 설치", "SplitCam은 Windows와 macOS용 무료 방송 인코더 — 가입 없음, 카드 없음, 워터마크 없음."),
           ("장면 구성", "SplitCam에서 웹캠을 추가하고 오버레이, 텍스트, 두 번째 카메라나 폰, 뷰티 필터, AI 배경을 얹으세요. <strong>mfcalerts.com</strong>을 Browser 레이어로 카메라 위에 추가하면 팁 애니메이션이 free chat 영상 안에 직접 뜹니다."),
           ("Model Admin에서 External Broadcaster로 전환", "MFC에 로그인해 <strong>Model Admin → Broadcaster</strong>를 열고, Web Broadcaster에서 <strong>External Broadcaster</strong>로 전환하세요. 표시되는 서버 URL(rtmp://publish.myfreecams.com…)과 stream key를 복사."),
           ("SplitCam에 URL과 key 붙여넣기", "SplitCam의 <strong>Stream Settings</strong>를 열고 URL과 stream key를 커스텀 RTMP 필드에 붙여넣으세요. 비트레이트는 3,500–6,000 Kbps, 1920×1080, 30 fps, 키프레임 2초로 설정."),
           ("Go Live 클릭", "SplitCam에서 <strong>Go Live</strong>를 누르면 약 10초 안에 신호가 MFC에 도달해 방에서 온라인 상태가 됩니다."),
       ]),
    _p("cherry-tv", "Cherry.tv",
       "SplitCam으로 Cherry.tv 방송하는 방법 — Web3 친화 외부 인코더",
       "무료 SplitCam으로 Cherry.tv 방송 — Streamer Dashboard 외부 인코더, 암호화폐 친화 캠 플랫폼, 멀티캠 장면. 워터마크 없음, 가입 불필요.",
       "cherry tv 방송, cherry.tv obs, cherry tv 외부 인코더, cherry.tv rtmp, cherry.tv stream key, cherry tv 스트리머, web3 cam",
       'SplitCam으로 <span class="accent">Cherry.tv</span> 방송하는 방법',
       "Cherry.tv 방송",
       "Cherry.tv의 Streamer Dashboard를 위한 외부 인코더 설정.",
       "Cherry.tv는 비교적 새롭고 빠르게 성장 중인 캠 플랫폼으로 Web3 색채가 강합니다 — 암호화폐 정산이 가능하고, LiveJasmin 같은 기존 네트워크보다 진입 장벽이 낮습니다. 기본은 브라우저 방송이지만 Streamer Dashboard에서 표준 External Encoder 경로도 함께 노출합니다 — 무료 <strong style='color:var(--text)'>SplitCam</strong>이 여기에 붙습니다.",
       "SplitCam으로 Cherry.tv 방송: SplitCam 설치, 장면 구성, Streamer Dashboard → Broadcast Settings → External Encoder 열기, URL과 stream key 복사, SplitCam에 붙여넣기, Go Live."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>Streamer Dashboard에서 External Encoder 열기.</li><li>URL과 stream key를 SplitCam에 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "Cherry.tv 스트리머 계정으로 로그인하고 <strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong>를 여세요. 서버 URL과 stream key 모두 계정에 묶여 있습니다. 신규 계정은 기본 인증이 필요하지만, Cherry.tv의 온보딩은 기존 캠 네트워크보다 훨씬 가볍습니다.",
       [("진입 장벽이 낮고 트래픽이 성장 중", "72시간짜리 Docler식 심사가 없습니다 — Cherry.tv는 일찍 들어가서 팔로워 베이스를 선점하기 좋은 자리입니다."),
        ("암호화폐와 법정 화폐 모두 정산 가능", "Cherry.tv는 암호화폐 정산도 지원합니다 — 전통 결제가 느리거나 제한된 지역에서는 특히 유리합니다."),
        ("브라우저 방송 vs 외부 인코더", "Cherry.tv의 브라우저 방송 도구는 단일 카메라뿐입니다. SplitCam이면 멀티캠 장면, 오버레이, 뷰티 필터, AI 배경까지 풀려서 화면 완성도가 한 단계 올라갑니다."),
        _T_ETH],
       [("Cherry.tv는 외부 인코더를 지원하나요?", "네 — Streamer Dashboard의 Broadcast Settings 아래 External Encoder 옵션이 있고 표준 RTMP라서 OBS/SplitCam이 그대로 됩니다."),
        ("Cherry.tv stream key는 어디 있나요?", "Streamer Dashboard → Broadcast Settings → External Encoder — URL과 stream key가 같은 페이지에 표시됩니다."),
        ("Cherry.tv에 비트레이트는 얼마?", "1920×1080, 30 fps, 3,500–6,000 Kbps, 키프레임 2초를 목표로 하세요."),
        ("Cherry.tv에서 SplitCam은 무료인가요?", "네 — SplitCam은 완전 무료, 워터마크 없음, 시간 제한 없음.")],
       steps=[
           ("SplitCam 다운로드 및 설치", "SplitCam은 Windows와 macOS용 무료 방송 인코더 — 가입 없음, 카드 없음, 워터마크 없음."),
           ("장면 구성", "웹캠과 오버레이를 추가하세요 — Cherry.tv 시청자는 더 젊고 플랫폼에 익숙해서 화면의 디자인 감각과 분위기가 중요합니다. 컬러풀한 오버레이, 움직이는 텍스트, AI 배경을 조합해 보세요."),
           ("URL과 stream key 받기", "<strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong>에서 서버 URL과 stream key를 복사."),
           ("SplitCam에 붙여넣기", "SplitCam의 <strong>Stream Settings</strong>를 열고 URL과 stream key를 붙여넣으세요. 비트레이트는 3,500–6,000 Kbps, 1920×1080, 30 fps, 키프레임 2초."),
           ("Go Live 클릭", "SplitCam에서 <strong>Go Live</strong>를 누른 뒤 Streamer Dashboard에서 온라인 상태로 전환하세요 — 바로 Cherry.tv에 방송이 올라갑니다."),
       ]),
    _p("amateurtv", "AmateurTV",
       "SplitCam으로 AmateurTV 방송하는 방법 — 스페인어권 캠 네트워크",
       "무료 SplitCam으로 AmateurTV 방송 — Model Panel 외부 인코더, 스페인과 라틴아메리카를 아우르는 스페인어 캠 네트워크, 멀티캠 장면. 워터마크 없음, 가입 불필요.",
       "amateurtv 방송, amateur.tv obs, amateurtv 외부 인코더, amateurtv rtmp, amateurtv stream key, modelos amateur tv",
       'SplitCam으로 <span class="accent">AmateurTV</span> 방송하는 방법',
       "AmateurTV 방송",
       "AmateurTV의 스페인어권 네트워크를 위한 외부 인코더 설정.",
       "AmateurTV는 스페인어권 최대의 캠 네트워크 — 스페인, 멕시코, 아르헨티나, 라틴아메리카 전반에 두꺼운 시청자층을 가지고 있습니다. 기본 Model Panel 방송 도구는 브라우저에서 동작하지만, 표준 <strong>External Encoder</strong> 경로도 함께 노출 — 무료 <strong style='color:var(--text)'>SplitCam</strong>이 여기에 붙어서, 멀티캠 장면, 뷰티 필터, 오버레이로 미국 중심 네트워크에서 잘 다루지 않는 스페인어권 시청자를 잡을 수 있습니다.",
       "SplitCam으로 AmateurTV 방송: SplitCam 설치, 장면 구성, Model Panel에서 <em>Broadcast Settings → External Encoder</em> 열기, 서버 URL과 stream key 복사, SplitCam에 붙여넣기, Go Live."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>Model Panel에서 URL과 stream key 받기.</li><li>SplitCam에 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "AmateurTV 모델 계정으로 로그인하고 <strong>Model Panel</strong>을 열어 <strong>Broadcast Settings → External Encoder</strong>로 이동하세요. 계정에 묶인 서버 URL과 stream key가 표시됩니다 — 두 값을 SplitCam의 커스텀 RTMP 필드에 붙여넣으세요. 신규 모델 계정은 방송 전에 ID 인증을 마쳐야 합니다.",
       [("스페인어권 시청자가 1순위", "AmateurTV의 트래픽은 압도적으로 스페인어 — 낮 시간대는 스페인, 미국 저녁 이후는 라틴아메리카가 중심입니다. 방 제목, 장면 텍스트, 오버레이를 스페인어로 가면 영어 전용보다 성과가 훨씬 큽니다."),
        ("라틴아메리카 시간대가 황금 시간", "피크 트래픽은 라틴아메리카 저녁 시간대(UTC-3 ~ UTC-6)에 몰립니다. 스케줄이 유연하다면 유럽 늦은 밤 / 아시아 새벽 시간대에 잡으면 스페인과 라틴아메리카 피크를 동시에 잡을 수 있습니다."),
        ("중상위권의 안정적 분배", "업계 최고 RPM은 아니지만 분배가 안정적이고, 스페인어권 니치는 미국 메이저 네트워크보다 경쟁이 적습니다."),
        _T_ETH],
       [("AmateurTV는 SplitCam 같은 외부 인코더를 공식 지원하나요?", "네 — Model Panel의 Broadcast Settings 아래 External Encoder 옵션이 있습니다. 표준 RTMP 서버 URL과 stream key 방식이라 OBS, SplitCam, vMix 등 RTMP 인코더가 모두 붙습니다."),
        ("AmateurTV stream key는 어디 있나요?", "Model Panel → Broadcast Settings → External Encoder. 서버 URL과 stream key가 같은 페이지에 표시됩니다. 두 값을 SplitCam의 커스텀 RTMP 필드에 붙여넣으세요. key는 계정에 묶여 있습니다."),
        ("AmateurTV에 비트레이트는 얼마?", "일반 캠 품질 — 1920×1080, 30 fps, 3,500–6,000 Kbps, 키프레임 2초. SplitCam 내장 속도 테스트를 먼저 돌리세요."),
        ("AmateurTV에서 SplitCam은 무료인가요?", "네 — SplitCam은 완전 무료, 워터마크 없음, 시간 제한 없음. AmateurTV의 External Encoder 옵션도 무료로 켤 수 있습니다.")],
       steps=[
           ("SplitCam 다운로드 및 설치", "SplitCam은 Windows와 macOS용 무료 방송 소프트웨어 — 가입 없음, 카드 없음, 워터마크 없음. AmateurTV로 영상을 보내는 인코더 역할입니다."),
           ("장면 구성", "SplitCam에서 웹캠을 추가하고 오버레이, 텍스트, 두 번째 카메라나 폰, 뷰티 필터, AI 배경을 얹으세요. AmateurTV의 스페인어권 시청자를 위해 오버레이 텍스트는 스페인어로."),
           ("AmateurTV URL과 stream key 받기", "AmateurTV 모델 계정으로 로그인하고 <strong>Model Panel</strong>을 열어 <strong>Broadcast Settings → External Encoder</strong>로 이동. 서버 URL과 고유 stream key가 표시됩니다. 두 값을 복사."),
           ("SplitCam을 AmateurTV에 연결", "SplitCam의 <strong>Stream Settings</strong>를 열고 AmateurTV 서버 URL과 stream key를 커스텀 RTMP 필드에 붙여넣으세요. 비트레이트는 3,500–6,000 Kbps, 1920×1080, 30 fps, 키프레임 2초. 내장 속도 테스트도 먼저 한 번."),
           ("Go Live 클릭", "SplitCam에서 <strong>Go Live</strong>를 누른 뒤 AmateurTV의 Model Panel에서 온라인 상태로 전환. 약 10초 안에 신호가 네트워크에 도달합니다. 이후 방송은 원클릭 — SplitCam 열고 Go Live만 누르면 됩니다."),
       ]),
    _p("camster", "Camster",
       "SplitCam으로 Camster 방송하는 방법 — Model Hub 외부 인코더",
       "무료 SplitCam으로 Camster 방송 — Model Hub 외부 인코더, 자리 잡은 중급 캠 플랫폼, 멀티캠 장면과 오버레이. 워터마크 없음, 가입 불필요.",
       "camster 방송, camster.com obs, camster 외부 인코더, camster rtmp, camster stream key, camster model hub",
       'SplitCam으로 <span class="accent">Camster</span> 방송하는 방법',
       "Camster 방송",
       "Camster의 Model Hub를 위한 외부 인코더 설정.",
       "Camster는 자리 잡은 중급 캠 플랫폼 — Chaturbate나 LiveJasmin보다 규모는 작지만 충성도 높은 유저층과 공정한 분배가 강점입니다. 기본 Model Hub 방송 도구는 브라우저에서 동작하지만, 표준 <strong>External Encoder</strong> 경로도 함께 노출 — 무료 <strong style='color:var(--text)'>SplitCam</strong>이 여기에 붙어서 내장 방송 도구로는 만들 수 없는 멀티캠 장면, 오버레이, 필터로 방송할 수 있습니다.",
       "SplitCam으로 Camster 방송: SplitCam 설치, 장면 구성, Model Hub에서 <em>Broadcast Settings → External Encoder</em> 열기, 서버 URL과 stream key 복사, SplitCam에 붙여넣기, Go Live."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>Model Hub에서 URL과 stream key 받기.</li><li>SplitCam에 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "Camster 모델 계정으로 로그인하고 <strong>Model Hub</strong>를 열어 <strong>Broadcast Settings → External Encoder</strong>로 이동하세요. 계정에 묶인 서버 URL과 stream key가 표시됩니다 — 두 값을 SplitCam의 커스텀 RTMP 필드에 붙여넣으세요. key는 계정에 묶여 있으니 비밀번호처럼 다루세요.",
       [("중급은 곧 경쟁이 적다는 의미", "Camster는 트래픽이 꾸준하지만 톱티어 네트워크보다 방송자 수가 적어서 — 잘 만든 장면과 일관된 스케줄이면 메인 페이지에 올리기 쉬운 자리입니다."),
        ("브라우저 방송 vs 외부 인코더", "기본 브라우저 방송은 단일 소스. SplitCam 경유 External Encoder면 멀티캠 장면, 오버레이, 뷰티 필터, AI 배경까지 풀립니다."),
        ("분배 공정, 정산 안정", "Camster의 수익 분배는 중급 레인지에서 공정한 편 — 업계 최고는 아니지만 매달 정산이 확실하고 지급 지연에 대한 모델 불만이 거의 없습니다."),
        _T_ETH],
       [("Camster는 SplitCam 같은 외부 인코더를 공식 지원하나요?", "네 — Model Hub의 Broadcast Settings 아래 External Encoder 옵션이 있습니다. 표준 RTMP 서버 URL과 stream key 방식이라 OBS, SplitCam 등 RTMP 인코더가 모두 붙습니다."),
        ("Camster stream key는 어디 있나요?", "Model Hub → Broadcast Settings → External Encoder. 서버 URL과 stream key가 같은 페이지에 표시됩니다. 두 값을 SplitCam의 커스텀 RTMP 필드에 붙여넣으세요."),
        ("Camster에 비트레이트는 얼마?", "일반 캠 품질 — 1920×1080, 30 fps, 3,500–6,000 Kbps, 키프레임 2초. SplitCam 내장 속도 테스트를 먼저 돌리세요."),
        ("Camster에서 SplitCam은 무료인가요?", "네 — SplitCam은 완전 무료, 워터마크 없음, 시간 제한 없음. Camster의 External Encoder 옵션도 무료입니다.")],
       steps=[
           ("SplitCam 다운로드 및 설치", "SplitCam은 Windows와 macOS용 무료 방송 소프트웨어 — 가입 없음, 카드 없음, 워터마크 없음."),
           ("장면 구성", "SplitCam에서 웹캠을 추가하고 오버레이, 텍스트, 두 번째 카메라나 폰, 뷰티 필터, AI 배경을 라이브로 얹으세요."),
           ("Camster URL과 stream key 받기", "Camster 모델 계정으로 로그인하고 <strong>Model Hub</strong>를 열어 <strong>Broadcast Settings → External Encoder</strong>로 이동. 서버 URL과 고유 stream key가 표시됩니다. 두 값을 복사."),
           ("SplitCam을 Camster에 연결", "SplitCam의 <strong>Stream Settings</strong>를 열고 Camster 서버 URL과 stream key를 커스텀 RTMP 필드에 붙여넣으세요. 비트레이트는 3,500–6,000 Kbps, 1920×1080, 30 fps, 키프레임 2초. 내장 속도 테스트도 먼저."),
           ("Go Live 클릭", "SplitCam에서 <strong>Go Live</strong>를 누른 뒤 Camster의 Model Hub에서 온라인 상태로 전환. 약 10초 안에 신호가 Camster에 도달합니다."),
       ]),
    _p("camversity", "Camversity",
       "SplitCam으로 Camversity 방송하는 방법 — Performer Dashboard 외부 인코더",
       "무료 SplitCam으로 Camversity 방송 — Performer Dashboard 외부 인코더, 퍼포머 친화적인 성장형 캠 플랫폼, 멀티캠 장면. 워터마크 없음, 가입 불필요.",
       "camversity 방송, camversity obs, camversity 외부 인코더, camversity rtmp, camversity stream key, camversity performer",
       'SplitCam으로 <span class="accent">Camversity</span> 방송하는 방법',
       "Camversity 방송",
       "Camversity의 Performer Dashboard를 위한 외부 인코더 설정.",
       "Camversity는 성장 중인 독립 캠 플랫폼 — 퍼포머 친화 도구와 기존 네트워크보다 낮은 수수료가 특징입니다. 기본 Performer Dashboard 방송 도구는 브라우저에서 동작하지만, 표준 <strong>External Encoder</strong> 경로도 함께 노출 — 무료 <strong style='color:var(--text)'>SplitCam</strong>이 여기에 붙어서 멀티캠 장면, 오버레이, 필터로 방송할 수 있습니다.",
       "SplitCam으로 Camversity 방송: SplitCam 설치, 장면 구성, Performer Dashboard에서 <em>Stream Settings → External Encoder</em> 열기, 서버 URL과 stream key 복사, SplitCam에 붙여넣기, Go Live."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>Performer Dashboard에서 URL과 stream key 받기.</li><li>SplitCam에 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "Camversity 퍼포머 계정으로 로그인하고 <strong>Performer Dashboard</strong>를 열어 <strong>Stream Settings → External Encoder</strong>로 이동하세요. 계정에 묶인 서버 URL과 stream key가 표시됩니다 — 두 값을 SplitCam의 커스텀 RTMP 필드에 붙여넣으세요. 신규 계정은 방송 전에 표준 ID 인증을 마쳐야 합니다.",
       [("퍼포머 친화적인 분배", "Camversity의 수익 분배는 기존 네트워크보다 퍼포머 쪽에 더 유리합니다 — 캠 커리어 초반이라면 메인 플랫폼과 비교해 볼 만합니다."),
        ("Docler 계열보다 가벼운 온보딩", "Camversity의 인증은 LiveJasmin의 48–72시간 승인보다 빠르면서도 정상 — 무작위 / 미인증 모델이 섞일 일이 없는 안정적인 중간 지점입니다."),
        ("웹캠이 아니라 장면을 만드세요", "Camversity의 기본 Performer Dashboard 방송은 단일 소스. SplitCam 경유 External Encoder면 멀티캠, 오버레이, 뷰티 필터까지 풀립니다."),
        _T_ETH],
       [("Camversity는 SplitCam 같은 외부 인코더를 공식 지원하나요?", "네 — Performer Dashboard의 Stream Settings 아래 External Encoder 옵션이 있습니다. 표준 RTMP 서버 URL과 stream key 방식이라 OBS, SplitCam, vMix가 모두 붙습니다."),
        ("Camversity stream key는 어디 있나요?", "Performer Dashboard → Stream Settings → External Encoder. 서버 URL과 stream key가 같은 페이지에 표시됩니다."),
        ("Camversity에 비트레이트는 얼마?", "1920×1080, 30 fps, 3,500–6,000 Kbps, 키프레임 2초를 목표로 하세요. SplitCam 내장 속도 테스트를 먼저 돌리세요."),
        ("Camversity에서 SplitCam은 무료인가요?", "네 — SplitCam은 완전 무료, 워터마크 없음, 시간 제한 없음. Camversity의 External Encoder 옵션도 무료입니다.")],
       steps=[
           ("SplitCam 다운로드 및 설치", "SplitCam은 Windows와 macOS용 무료 방송 소프트웨어 — 가입 없음, 카드 없음, 워터마크 없음."),
           ("장면 구성", "SplitCam에서 웹캠을 추가하고 오버레이, 텍스트, 두 번째 카메라나 폰, 뷰티 필터, AI 배경을 얹으세요."),
           ("Camversity URL과 stream key 받기", "Camversity 퍼포머 계정으로 로그인하고 <strong>Performer Dashboard</strong>를 열어 <strong>Stream Settings → External Encoder</strong>로 이동. 서버 URL과 고유 stream key가 표시됩니다. 두 값을 복사."),
           ("SplitCam을 Camversity에 연결", "SplitCam의 <strong>Stream Settings</strong>를 열고 Camversity 서버 URL과 stream key를 커스텀 RTMP 필드에 붙여넣으세요. 비트레이트는 3,500–6,000 Kbps, 1920×1080, 30 fps, 키프레임 2초."),
           ("Go Live 클릭", "SplitCam에서 <strong>Go Live</strong>를 누른 뒤 Performer Dashboard에서 온라인 상태로 전환. 약 10초 안에 신호가 Camversity에 도달합니다."),
       ]),
    _p("skyprivate", "SkyPrivate",
       "SkyPrivate × SplitCam 사용법 — Skype 기반 분당 과금 프라이빗 콜",
       "무료 SplitCam을 가상 카메라로 SkyPrivate 운영 — Skype 분당 과금 프라이빗 콜, 멀티 카메라 장면, 뷰티 필터. 워터마크 없음, 가입 불필요.",
       "skyprivate, sky private cam, skype 프라이빗 캠, skyprivate splitcam, skyprivate 가상 카메라, 분당 과금 cam",
       'SplitCam으로 <span class="accent">SkyPrivate</span> 사용하기',
       "SplitCam × SkyPrivate",
       "SkyPrivate Skype 콜용 가상 카메라 세팅.",
       "SkyPrivate은 다른 cam 플랫폼과 결이 다릅니다 — RTMP 송출이 아니라 <strong>Skype를 통한 분당 과금 프라이빗 콜</strong>로 수익을 냅니다. 고객은 SkyPrivate 마켓에서 예약하고 분당 결제하며, 실제 영상 통화는 Skype로 진행됩니다. 무료 <strong style='color:var(--text)'>SplitCam</strong>은 <strong>가상 카메라</strong>로 들어옵니다 — SplitCam에서 장면을 만들고, Skype 카메라를 SplitCam으로 바꾼 뒤 SkyPrivate에서 예약된 콜을 받으면 됩니다.",
       "SkyPrivate × SplitCam 흐름: SplitCam 설치, 장면 구성, Skype와 SkyPrivate 애드온 설치, Skype의 <em>Video Settings</em>에서 카메라와 마이크를 SplitCam으로 설정, SkyPrivate 예약 콜 수신 — Skype가 합성된 장면을 고객에게 전달합니다."
       "<ol><li>SplitCam 설치.</li><li>SplitCam에서 장면 구성.</li><li>Skype + SkyPrivate 애드온 설치.</li><li>Skype 카메라를 SplitCam으로.</li><li>콜 수신.</li></ol>",
       "SkyPrivate은 RTMP도, stream key도 쓰지 않습니다 — Skype를 영상 전송 채널로 쓰고 그 위에 분당 과금 애드온이 얹히는 구조입니다. Skype를 설치하고 SkyPrivate 브라우저/데스크톱 애드온을 설치한 뒤, Skype의 <strong>Settings → Audio &amp; Video → Camera</strong>에서 일반 웹캠 대신 <strong>SplitCam</strong>을 선택하세요. SplitCam에서 합성된 장면(오버레이, 멀티 카메라, 뷰티 필터)이 그대로 Skype를 통해 SkyPrivate 고객에게 전달됩니다.",
       [("RTMP 없음 — 가상 카메라 방식", "서버 URL이나 stream key를 찾지 마세요. SkyPrivate은 Skype 위에서 돌고, Skype는 SplitCam을 그냥 웹캠 디바이스로 인식합니다. SplitCam에서 장면을 만든 뒤 Skype 카메라 설정에서 SplitCam을 고르면 끝."),
        ("마이크도 SplitCam으로", "Skype의 Audio 설정에서 마이크도 SplitCam으로 — 그래야 노이즈 억제, 믹스된 오디오, 인트로 음악까지 고객에게 전달됩니다."),
        ("Skype 테스트 콜로 사전 점검", "첫 유료 SkyPrivate 콜을 받기 전, Skype 무료 테스트 콜(Echo / Sound Test Service)로 SplitCam이 현재 카메라이고 구도도 정상인지 확인하세요."),
        _T_TEST],
       [("SkyPrivate은 RTMP나 stream key를 쓰나요?", "둘 다 안 씁니다. SkyPrivate은 결제와 예약만 담당하고 실제 영상은 Skype로 흐릅니다. RTMP 서버 URL이나 stream key 없이 Skype 안에서 SplitCam을 카메라로 지정하기만 하면 됩니다."),
        ("Skype에서 SkyPrivate용으로 SplitCam은 어떻게 선택하나요?", "Skype의 Settings → Audio &amp; Video → Camera에서 SplitCam을 선택하고 마이크도 동일하게 설정하세요. SkyPrivate 콜은 일반 Skype 콜로 들어오며, 카메라 피드로 SplitCam에서 합성한 장면이 나갑니다."),
        ("SkyPrivate에서 오버레이나 뷰티 필터를 쓸 수 있나요?", "쓸 수 있습니다 — SplitCam 장면 안에서 만들어 두면 됩니다. Skype는 합성된 한 개의 카메라 피드만 받기 때문에, SplitCam에서 얹은 모든 것(오버레이, 뷰티, AI 배경, 멀티 카메라)이 SkyPrivate 고객에게 그대로 보입니다."),
        ("SplitCam은 SkyPrivate에서 무료인가요?", "네 — SplitCam은 무료, 워터마크 없음, 시간 제한 없음. Skype 기반 SkyPrivate 콜의 가상 카메라로 동작하며 콜에 별도 비용이나 브랜딩을 더하지 않습니다.")],
       steps=[
           ("SplitCam 설치", "SplitCam은 Windows와 macOS용 무료 소프트웨어 — 가입 없음, 카드 없음, 워터마크 없음. SkyPrivate 흐름에서는 Skype가 일반 웹캠처럼 인식하는 <strong>가상 카메라</strong>로 동작합니다."),
           ("SplitCam에서 장면 구성", "SplitCam을 열고 <strong>Media Layers +</strong>로 웹캠을 추가한 뒤 오버레이, 텍스트, 뷰티 필터, AI 배경을 올리세요. 이 합성 장면이 Skype를 통해 SkyPrivate 고객에게 전달됩니다."),
           ("Skype와 SkyPrivate 애드온 설치", "같은 PC에 Skype를 설치해 로그인하고, SkyPrivate 온보딩을 따라 SkyPrivate 애드온 / 데스크톱 앱을 설치하세요. 애드온이 SkyPrivate 측 분당 과금을 담당합니다."),
           ("Skype 카메라와 마이크를 SplitCam으로", "Skype에서 <strong>Settings → Audio &amp; Video</strong>를 열고 <strong>Camera = SplitCam</strong>, <strong>Microphone = SplitCam</strong>으로 설정. Skype 테스트 콜(Echo / Sound Test Service)로 영상과 사운드를 확인하세요."),
           ("SkyPrivate 콜 받기", "SkyPrivate 고객이 유료 콜을 예약하면 Skype 콜로 수신됩니다 — 받으면 됩니다. 고객은 SplitCam에서 합성한 장면을 보고, SkyPrivate은 분당 과금합니다. 통화 중 장면 수정은 SplitCam에서 진행하면 Skype에 실시간 반영됩니다."),
       ]),
    _p("manyvids", "ManyVids",
       "MV Live(ManyVids)에서 SplitCam으로 방송하는 법 — Creator Studio 설정",
       "무료 SplitCam으로 ManyVids의 MV Live 송출 — Creator Studio external encoder, OnlyFans형 크리에이터 이코노미, 멀티 카메라. 워터마크 없음, 가입 불필요.",
       "manyvids 방송, mv live, manyvids live broadcast, manyvids obs, mv live external encoder, manyvids stream key, manyvids 크리에이터",
       'SplitCam으로 <span class="accent">MV Live</span> 방송하기',
       "MV Live 방송",
       "ManyVids MV Live의 Creator Studio external encoder 설정.",
       "ManyVids는 크리에이터 이코노미형 플랫폼 — 클립 판매, 커스텀 비디오, 팬클럽 구독에 더해 라이브 방송 제품 <strong>MV Live</strong>를 운영합니다. Creator Studio 내장 브라우저 방송기뿐 아니라 표준 <strong>External Encoder</strong> 경로도 열려 있어 무료 <strong style='color:var(--text)'>SplitCam</strong>이 그대로 접속됩니다 — 같은 크리에이터 친화 플랫폼에서 멀티 카메라, 오버레이, 필터로 방송할 수 있습니다.",
       "SplitCam으로 MV Live 방송: SplitCam 설치, 장면 구성, Creator Studio에서 <em>MV Live → Broadcast Settings → External Encoder</em> 열기, 서버 URL과 stream key 복사 후 SplitCam에 붙여넣기, Go Live."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>Creator Studio에서 URL과 stream key 받기.</li><li>SplitCam에 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "ManyVids 크리에이터 계정으로 로그인해 <strong>Creator Studio</strong>를 열고 <strong>MV Live → Broadcast Settings → External Encoder</strong>로 이동하세요. 계정에 묶인 <strong>서버 URL</strong>과 <strong>stream key</strong>가 표시됩니다 — 두 값을 SplitCam의 커스텀 RTMP 필드에 복사하세요. MV Live를 쓰려면 크리에이터 계정의 완전 인증(ID + 세금)이 필요합니다.",
       [("크리에이터 이코노미, 라이브만이 아닌", "ManyVids는 순수 cam 사이트가 아닙니다 — MV Live는 클립 판매, 커스텀 비디오, 팬클럽 구독과 나란히 가는 수익 채널 중 하나. 라이브는 다른 수익 상품으로 가는 깔때기로 설계하세요."),
        ("MV Live 안의 토큰 팁", "MV Live 룸은 자체 토큰 팁 시스템을 갖고 있습니다. Chaturbate / Stripchat과 비슷한 골 메뉴와 리워드 트리거를 설계 — ManyVids 기존 오디언스에서 전환이 잘 됩니다."),
        ("브라우저 vs 외부 인코더", "Creator Studio 내장 브라우저 방송은 싱글 카메라. SplitCam을 External Encoder로 연결해야 멀티 카메라 장면, 오버레이, 필터가 풀립니다."),
        _T_ETH],
       [("MV Live(ManyVids)는 SplitCam 같은 외부 인코더를 지원하나요?", "지원합니다 — Creator Studio의 MV Live 섹션 Broadcast Settings 아래에 External Encoder 옵션이 있습니다. 표준 RTMP 서버 URL과 stream key, OBS, SplitCam, vMix 모두 연결됩니다."),
        ("MV Live stream key는 어디 있나요?", "Creator Studio → MV Live → Broadcast Settings → External Encoder. 서버 URL과 stream key 둘 다 여기에 표시됩니다 — 둘 다 SplitCam의 커스텀 RTMP 필드에 복사."),
        ("MV Live 비트레이트는 얼마?", "1920×1080, 30 fps, 3,500–6,000 Kbps, 키프레임 2초. SplitCam 내장 속도 테스트를 먼저 돌리세요."),
        ("SplitCam은 MV Live에서 무료인가요?", "네 — SplitCam은 무료, 워터마크 없음, 시간 제한 없음. ManyVids의 Creator Studio에서 열어주는 외부 인코더 옵션도 무료입니다.")],
       steps=[
           ("SplitCam 다운로드 및 설치", "SplitCam은 Windows와 macOS용 무료 방송 소프트웨어 — 가입 없음, 카드 없음, 워터마크 없음."),
           ("장면 구성", "SplitCam에서 웹캠을 추가하고 오버레이, 텍스트, 두 번째 카메라나 폰, 뷰티 필터, AI 배경을 얹으세요 — MV Live 골 공개나 리워드 트리거에 잘 맞습니다."),
           ("MV Live URL과 stream key 받기", "ManyVids 크리에이터 계정으로 로그인해 <strong>Creator Studio</strong>를 열고 <strong>MV Live → Broadcast Settings → External Encoder</strong>로 이동. <strong>서버 URL</strong>과 고유 <strong>stream key</strong>가 표시됩니다. 두 값을 복사."),
           ("SplitCam을 MV Live에 연결", "SplitCam의 <strong>Stream Settings</strong>를 열고 MV Live 서버 URL과 stream key를 커스텀 RTMP 필드에 붙여넣으세요. 비트레이트는 3,500–6,000 Kbps, 1920×1080, 30 fps, 키프레임 2초."),
           ("Go Live 클릭", "SplitCam에서 <strong>Go Live</strong>를 누른 뒤 Creator Studio에서 MV Live 방송을 시작. 약 10초 안에 신호가 MV Live 오디언스에 도달합니다."),
       ]),
    _p("fansly", "Fansly",
       "Fansly Live에서 SplitCam으로 방송하는 법 — Creator Dashboard 외부 인코더",
       "무료 SplitCam으로 Fansly Live 송출 — Creator Dashboard external encoder, OnlyFans 직접 경쟁자, 멀티 카메라 장면, 뷰티 필터. 워터마크 없음, 가입 불필요.",
       "fansly 방송, fansly live, fansly broadcast, fansly obs, fansly external encoder, fansly rtmp, fansly stream key, fansly 크리에이터",
       'SplitCam으로 <span class="accent">Fansly Live</span> 방송하기',
       "Fansly 방송",
       "Fansly Creator Dashboard 외부 인코더 설정.",
       "Fansly는 OnlyFans의 직접 경쟁자 — 콘텐츠 룰이 더 느슨하고 크리에이터 베이스가 빠르게 성장 중이며, 구독, PPV 콘텐츠 그리고 라이브 방송 제품 <strong>Fansly Live</strong>를 제공합니다. 기본은 브라우저 방송기지만 <strong>Creator Dashboard</strong>에서 표준 <strong>External Encoder</strong> 경로도 열어줘 무료 <strong style='color:var(--text)'>SplitCam</strong>이 그대로 접속됩니다 — 구독자 베이스에 멀티 카메라, 오버레이, 필터 장착 방송을 송출할 수 있습니다.",
       "SplitCam으로 Fansly Live 방송: SplitCam 설치, 장면 구성, Creator Dashboard에서 <em>Live → Broadcast Settings → External Encoder</em> 열기, 서버 URL과 stream key 복사 후 SplitCam에 붙여넣기, Go Live."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>Creator Dashboard에서 URL과 stream key 받기.</li><li>SplitCam에 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "Fansly 크리에이터 계정으로 로그인해 <strong>Creator Dashboard</strong>를 열고 <strong>Live → Broadcast Settings → External Encoder</strong>로 이동하세요. 계정에 묶인 <strong>서버 URL</strong>과 <strong>stream key</strong>가 표시됩니다 — 두 값을 SplitCam의 커스텀 RTMP 필드에 복사하세요. Fansly Live를 활성화하려면 크리에이터 계정의 ID 인증이 필요합니다.",
       [("구독자 우선 오디언스", "Fansly의 오디언스는 구독 기반 — 라이브를 보는 사람은 이미 매달 결제하는 사람들입니다. 공개방 지표를 좇기보다 로열티를 보상하는 콘텐츠(독점 Q&amp;A, 비하인드, 커스텀 팁 골)를 설계하세요."),
        ("구독에 더해지는 팁", "Fansly Live는 기본 구독 위에 스트림 내 팁도 지원. 자리잡은 크리에이터에게는 구독 + 팁 합산 매출이 순 cam 플랫폼의 팁 단독보다 큰 경우가 많습니다."),
        ("브라우저 방송 vs 외부", "기본 브라우저 방송은 싱글 소스. SplitCam을 External Encoder로 연결하면 멀티 카메라, 오버레이, 뷰티 필터, AI 배경이 풀려 유료 구독 콘텐츠 퀄리티에 맞출 수 있습니다."),
        _T_ETH],
       [("Fansly Live는 SplitCam 같은 외부 인코더를 지원하나요?", "지원합니다 — Creator Dashboard의 Live 섹션 Broadcast Settings 아래에 External Encoder 옵션이 있습니다. 표준 RTMP 서버 URL과 stream key, OBS, SplitCam, vMix 모두 연결됩니다."),
        ("Fansly stream key는 어디 있나요?", "Creator Dashboard → Live → Broadcast Settings → External Encoder. 서버 URL과 stream key 둘 다 여기에 표시됩니다. 둘 다 SplitCam의 커스텀 RTMP 필드에 복사."),
        ("Fansly Live 비트레이트는 얼마?", "1920×1080, 30 fps, 3,500–6,000 Kbps, 키프레임 2초. SplitCam 내장 속도 테스트를 먼저 돌리세요."),
        ("SplitCam은 Fansly에서 무료인가요?", "네 — SplitCam은 무료, 워터마크 없음, 시간 제한 없음. Fansly의 Creator Dashboard에서 열어주는 외부 인코더 옵션도 무료입니다.")],
       steps=[
           ("SplitCam 다운로드 및 설치", "SplitCam은 Windows와 macOS용 무료 방송 소프트웨어 — 가입 없음, 카드 없음, 워터마크 없음."),
           ("장면 구성", "SplitCam에서 웹캠을 추가하고 오버레이, 텍스트, 두 번째 카메라나 폰, 뷰티 필터, AI 배경을 얹으세요 — 유료 구독자의 기대치에 맞는 정돈된 장면을 만들 수 있습니다."),
           ("Fansly URL과 stream key 받기", "Fansly 크리에이터 계정으로 로그인해 <strong>Creator Dashboard</strong>를 열고 <strong>Live → Broadcast Settings → External Encoder</strong>로 이동. <strong>서버 URL</strong>과 고유 <strong>stream key</strong>가 표시됩니다. 두 값을 복사."),
           ("SplitCam을 Fansly에 연결", "SplitCam의 <strong>Stream Settings</strong>를 열고 Fansly 서버 URL과 stream key를 커스텀 RTMP 필드에 붙여넣으세요. 비트레이트는 3,500–6,000 Kbps, 1920×1080, 30 fps, 키프레임 2초."),
           ("Go Live 클릭", "SplitCam에서 <strong>Go Live</strong>를 누른 뒤 Creator Dashboard에서 Fansly Live 방송을 시작. 약 10초 안에 신호가 Fansly 구독자에게 도달합니다."),
       ]),
    _p("ifriends", "iFriends",
       "SplitCam으로 iFriends 방송하는 법 — Model Center 외부 인코더",
       "무료 SplitCam으로 iFriends 송출 — Model Center external encoder, 오랜 역사의 독립 캠 네트워크, 멀티 카메라 장면. 워터마크 없음, 가입 불필요.",
       "ifriends 방송, ifriends obs, ifriends external encoder, ifriends rtmp, ifriends stream key, ifriends model center, ifriends.net",
       'SplitCam으로 <span class="accent">iFriends</span> 방송하기',
       "iFriends 방송",
       "iFriends의 오래된 Model Center를 위한 외부 인코더 설정.",
       "iFriends(WebPower)는 가장 오래 운영된 독립 캠 네트워크 중 하나입니다 — 조용히 수익을 내고, 충성도 높은 이용자 베이스를 가졌으며, 브라우저 방송이 흔해지기 전에 만들어진 성숙한 Model Center를 갖추고 있습니다. 이 플랫폼은 Model Center에서 표준 <strong>외부 인코더</strong> 경로를 열어줘 무료 <strong style='color:var(--text)'>SplitCam</strong>이 그대로 접속됩니다 — 자리잡은 이 네트워크에서 멀티 카메라 장면, 오버레이, 필터로 방송할 수 있습니다.",
       "SplitCam으로 iFriends 방송: SplitCam 설치, 장면 구성, Model Center에서 <em>Broadcast Settings → External Encoder</em> 열기, 서버 URL과 stream key 복사 후 SplitCam에 붙여넣기, Go Live."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>Model Center에서 URL과 stream key 받기.</li><li>SplitCam에 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "iFriends 모델 계정으로 로그인해 <strong>Model Center</strong>를 열고 <strong>Broadcast Settings → External Encoder</strong>로 이동하세요. 계정에 묶인 <strong>서버 URL</strong>과 <strong>stream key</strong>가 표시됩니다 — 두 값을 SplitCam의 커스텀 RTMP 필드에 복사하세요. 신규 모델 계정에 대한 iFriends 심사는 까다롭지만 정당한 절차이며, 한 번 인증되면 외부 인코더 옵션이 계속 열려 있습니다.",
       [("롱테일 오디언스, 성숙한 네트워크", "iFriends는 90년대 후반부터 충성도 높은 이용자 베이스와 함께 운영돼 왔습니다 — 처음 들른 방문객이 아니라 오래된 정기 구독자가 많습니다. 자리잡은 모델에게는 안정적인 수입, 신규에게는 더딘 성장입니다."),
        ("브라우저 방송 vs 외부", "iFriends의 레거시 방송기는 요즘의 멀티 카메라 UX가 나오기 전에 만들어졌습니다. External Encoder로 SplitCam에 전환하면 확연히 업그레이드됩니다 — 옛 도구가 못 주는 멀티 카메라 장면, 오버레이, 뷰티 필터가 풀립니다."),
        ("꾸준한 정산, 적은 변수", "iFriends의 모회사(WebPower)는 수십 년간 모델에게 안정적으로 정산해 왔습니다 — 신생 크립토 친화 플랫폼보다 정산 주기는 느리지만, 사고 사례는 거의 없습니다."),
        _T_ETH],
       [("iFriends는 SplitCam 같은 외부 인코더를 공식 지원하나요?", "지원합니다 — Model Center의 Broadcast Settings 아래에 External Encoder 옵션이 있습니다. 표준 RTMP 서버 URL과 stream key, 계정이 승인되면 OBS, SplitCam, vMix 모두 연결됩니다."),
        ("iFriends stream key는 어디 있나요?", "Model Center → Broadcast Settings → External Encoder. 서버 URL과 stream key 둘 다 여기에 표시됩니다 — 둘 다 SplitCam의 커스텀 RTMP 필드에 복사."),
        ("iFriends 비트레이트는 얼마?", "1920×1080, 30 fps, 3,500–6,000 Kbps, 키프레임 2초. SplitCam 내장 속도 테스트를 먼저 돌리세요."),
        ("SplitCam은 iFriends에서 무료인가요?", "네 — SplitCam은 무료, 워터마크 없음, 시간 제한 없음. iFriends의 Model Center에서 열어주는 외부 인코더 옵션도 무료입니다.")],
       steps=[
           ("SplitCam 다운로드 및 설치", "SplitCam은 Windows와 macOS용 무료 방송 소프트웨어 — 가입 없음, 카드 없음, 워터마크 없음."),
           ("장면 구성", "SplitCam에서 웹캠을 추가하고 오버레이, 텍스트, 두 번째 카메라나 폰, 뷰티 필터, AI 배경을 얹으세요 — 정돈된 요즘 장면은 이 성숙한 네트워크에서 눈에 띕니다."),
           ("iFriends URL과 stream key 받기", "iFriends 모델 계정으로 로그인해 <strong>Model Center</strong>를 열고 <strong>Broadcast Settings → External Encoder</strong>로 이동. <strong>서버 URL</strong>과 고유 <strong>stream key</strong>가 표시됩니다. 두 값을 복사."),
           ("SplitCam을 iFriends에 연결", "SplitCam의 <strong>Stream Settings</strong>를 열고 iFriends 서버 URL과 stream key를 커스텀 RTMP 필드에 붙여넣으세요. 비트레이트는 3,500–6,000 Kbps, 1920×1080, 30 fps, 키프레임 2초."),
           ("Go Live 클릭", "SplitCam에서 <strong>Go Live</strong>를 누른 뒤 iFriends Model Center에서 온라인으로 전환. 약 10초 안에 신호가 네트워크에 도달합니다."),
       ]),
    _p("babestation", "Babestation",
       "SplitCam으로 Babestation 방송하는 법 — UK 캠 네트워크 설정",
       "무료 SplitCam으로 Babestation 송출 — Performer Hub external encoder, UK 성인 TV / 캠 네트워크, 멀티 카메라 장면, 오버레이. 워터마크 없음, 가입 불필요.",
       "babestation 방송, babestation cam, babestation obs, babestation external encoder, babestation rtmp, babestation performer, uk cam network",
       'SplitCam으로 <span class="accent">Babestation</span> 방송하기',
       "Babestation 방송",
       "Babestation의 UK Performer Hub를 위한 외부 인코더 설정.",
       "Babestation은 영국을 대표하는 성인 TV / 캠 네트워크입니다 — 방송 TV 채널과, Performer Hub에 로그인한 퍼포머가 송출하는 라이브 캠 상품을 결합한 하이브리드 형태입니다. 이 플랫폼은 Performer Hub에서 표준 <strong>외부 인코더</strong> 경로를 열어줘 무료 <strong style='color:var(--text)'>SplitCam</strong>이 그대로 접속됩니다 — 독립 UK 퍼포머가 Babestation의 TV 스튜디오식 기본 방송기를 넘어 멀티 카메라 장면, 오버레이, 뷰티 필터로 송출할 수 있습니다.",
       "SplitCam으로 Babestation 방송: SplitCam 설치, 장면 구성, Performer Hub에서 <em>Broadcast Settings → External Encoder</em> 열기, 서버 URL과 stream key 복사 후 SplitCam에 붙여넣기, Go Live."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>Performer Hub에서 URL과 stream key 받기.</li><li>SplitCam에 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "Babestation 퍼포머 계정으로 로그인해 <strong>Performer Hub</strong>를 열고 <strong>Broadcast Settings → External Encoder</strong>로 이동하세요. 계정에 묶인 <strong>서버 URL</strong>과 <strong>stream key</strong>가 표시됩니다 — 두 값을 SplitCam의 커스텀 RTMP 필드에 복사하세요. Babestation의 UK 퍼포머 온보딩에는 영국 연령 인증 규정에 따른 신분 확인이 포함됩니다.",
       [("UK 우선 오디언스와 시간대", "Babestation의 핵심 트래픽은 영국 저녁 / 심야(GMT/BST)입니다. 다른 시간대에 있다면, 현지 황금시간대보다 영국 심야 시간에 방송하는 편이 이 네트워크에서 훨씬 잘 나옵니다."),
        ("TV 스튜디오급 완성도가 기대됨", "Babestation의 브랜드는 TV 채널과 묶여 있어, 시청자는 평범한 웹캠 방송보다 더 만들어진 세트와 조명을 기대합니다. SplitCam 장면(오버레이, 브랜드 텍스트, AI 배경)이 이 플랫폼 특유의 정돈된 미감에 맞추는 데 도움이 됩니다."),
        ("독립 퍼포머 vs 스튜디오 퍼포머", "Babestation은 UK 스튜디오와 독립 퍼포머 모두와 일합니다. External Encoder로 접속하는 독립 방송자도 스튜디오 카메라와 동일한 정산 모델을 적용받습니다."),
        _T_ETH],
       [("Babestation은 SplitCam 같은 외부 인코더를 지원하나요?", "지원합니다 — Performer Hub의 Broadcast Settings 아래에 External Encoder 옵션이 있습니다. 표준 RTMP 서버 URL과 stream key, 퍼포머 인증이 끝나면 OBS, SplitCam, vMix 모두 연결됩니다."),
        ("Babestation stream key는 어디 있나요?", "Performer Hub → Broadcast Settings → External Encoder. 서버 URL과 stream key 둘 다 여기에 표시됩니다 — 둘 다 SplitCam의 커스텀 RTMP 필드에 복사."),
        ("Babestation 비트레이트는 얼마?", "1920×1080, 30 fps, 3,500–6,000 Kbps, 키프레임 2초. 영국 업로드 대역폭은 대체로 넉넉하지만 SplitCam 속도 테스트를 먼저 돌리세요."),
        ("SplitCam은 Babestation에서 무료인가요?", "네 — SplitCam은 무료, 워터마크 없음, 시간 제한 없음. Babestation의 Performer Hub에서 열어주는 외부 인코더 옵션도 무료입니다.")],
       steps=[
           ("SplitCam 다운로드 및 설치", "SplitCam은 Windows와 macOS용 무료 방송 소프트웨어 — 가입 없음, 카드 없음, 워터마크 없음."),
           ("장면 구성", "SplitCam에서 웹캠을 추가하고 오버레이, 텍스트, 두 번째 카메라나 폰, 뷰티 필터, AI 배경을 얹으세요 — Babestation의 TV 스튜디오급 완성도에 맞춰 눈에 띄게 만드세요."),
           ("Babestation URL과 stream key 받기", "Babestation 퍼포머 계정으로 로그인해 <strong>Performer Hub</strong>를 열고 <strong>Broadcast Settings → External Encoder</strong>로 이동. <strong>서버 URL</strong>과 고유 <strong>stream key</strong>가 표시됩니다. 두 값을 복사."),
           ("SplitCam을 Babestation에 연결", "SplitCam의 <strong>Stream Settings</strong>를 열고 Babestation 서버 URL과 stream key를 커스텀 RTMP 필드에 붙여넣으세요. 비트레이트는 3,500–6,000 Kbps, 1920×1080, 30 fps, 키프레임 2초."),
           ("Go Live 클릭", "SplitCam에서 <strong>Go Live</strong>를 누른 뒤 Performer Hub에서 온라인으로 전환. 약 10초 안에 신호가 Babestation의 영국 오디언스에 도달합니다."),
       ]),
    _p("adultwork", "AdultWork",
       "SplitCam으로 AdultWork 방송하는 법 — Members Area 외부 인코더",
       "무료 SplitCam으로 AdultWork 송출 — Members Area external encoder, 캠 기능을 갖춘 UK 성인 서비스 마켓플레이스, 멀티 카메라 장면. 워터마크 없음, 가입 불필요.",
       "adultwork 방송, adultwork cam, adultwork obs, adultwork external encoder, adultwork rtmp, adultwork webcam, uk cam",
       'SplitCam으로 <span class="accent">AdultWork</span> 방송하기',
       "AdultWork 방송",
       "AdultWork의 UK Members Area 캠 기능을 위한 외부 인코더 설정.",
       "AdultWork는 자리잡은 영국 성인 서비스 마켓플레이스입니다 — 에스코트 예약, 사진 / 영상 판매, 전화 서비스로 주로 알려져 있으며, 라이브 <strong>웹캠 기능</strong>도 함께 제공합니다. 이 플랫폼은 Members Area에서 표준 <strong>외부 인코더</strong> 경로를 열어줘 무료 <strong style='color:var(--text)'>SplitCam</strong>이 그대로 접속됩니다 — 독립 UK 퍼포머가 멀티 카메라 장면, 오버레이, 필터로 라이브 캠 수익을 더할 수 있습니다.",
       "SplitCam으로 AdultWork 방송: SplitCam 설치, 장면 구성, Members Area에서 <em>Members → Broadcasting → External Encoder</em> 열기, 서버 URL과 stream key 복사 후 SplitCam에 붙여넣기, Go Live."
       "<ol><li>SplitCam 설치.</li><li>카메라 + 장면 추가.</li><li>Members Area에서 URL과 stream key 받기.</li><li>SplitCam에 붙여넣기.</li><li>Go Live 누르기.</li></ol>",
       "AdultWork 퍼포머 계정으로 로그인해 <strong>Members Area</strong>를 열고 <strong>Members → Broadcasting → External Encoder</strong>로 이동하세요. 계정에 묶인 <strong>서버 URL</strong>과 <strong>stream key</strong>가 표시됩니다 — 두 값을 SplitCam의 커스텀 RTMP 필드에 복사하세요. AdultWork 인증은 라이브 캠 기능에 필수이며, 영국 연령 인증 준수를 포함합니다.",
       [("AdultWork의 다른 서비스에서 교차 판매", "AdultWork의 강점은 기존 고객 베이스입니다 — 시청자가 이미 당신의 사진 / 영상 / 전화 서비스를 예약했을 수 있습니다. 라이브 캠은 낯선 사람을 쫓기보다, 아직 캠을 안 써본 기존 고객에게 교차 판매하는 데 쓰세요."),
        ("Members Area가 진입점", "방송기는 공개 사이트에서 찾지 마세요 — 퍼포머 쪽 기능은 전부 Members Area 안에 있습니다. 방송 설정, 정산, 콘텐츠 관리 모두 거기 있습니다."),
        ("UK 중심이지만 국제 정산", "트래픽 대부분은 영국 / EU입니다. 정산은 표준 은행 송금 / 전자지갑으로 국제적으로 가능하며, 이 플랫폼에서는 주간 정산 주기가 흔합니다."),
        _T_ETH],
       [("AdultWork는 SplitCam 같은 외부 인코더를 지원하나요?", "지원합니다 — Members Area의 Broadcasting 아래에 External Encoder 옵션이 있습니다. 표준 RTMP 서버 URL과 stream key, 퍼포머 인증 후 OBS, SplitCam, vMix 모두 연결됩니다."),
        ("AdultWork stream key는 어디 있나요?", "Members Area → Members → Broadcasting → External Encoder. 서버 URL과 stream key 둘 다 여기에 표시됩니다 — 둘 다 SplitCam의 커스텀 RTMP 필드에 복사."),
        ("AdultWork 비트레이트는 얼마?", "1920×1080, 30 fps, 3,500–6,000 Kbps, 키프레임 2초. SplitCam 내장 속도 테스트를 먼저 돌리세요."),
        ("SplitCam은 AdultWork에서 무료인가요?", "네 — SplitCam은 무료, 워터마크 없음, 시간 제한 없음. AdultWork의 Members Area에서 열어주는 외부 인코더 옵션도 무료입니다.")],
       steps=[
           ("SplitCam 다운로드 및 설치", "SplitCam은 Windows와 macOS용 무료 방송 소프트웨어 — 가입 없음, 카드 없음, 워터마크 없음."),
           ("장면 구성", "SplitCam에서 웹캠을 추가하고 오버레이, 텍스트, 두 번째 카메라나 폰, 뷰티 필터, AI 배경을 얹으세요 — 오버레이로 AdultWork 콘텐츠 / 전화 서비스를 홍보하고 라이브 중에 교차 판매하세요."),
           ("AdultWork URL과 stream key 받기", "AdultWork 퍼포머 계정으로 로그인해 <strong>Members Area</strong>를 열고 <strong>Members → Broadcasting → External Encoder</strong>로 이동. <strong>서버 URL</strong>과 고유 <strong>stream key</strong>가 표시됩니다. 두 값을 복사."),
           ("SplitCam을 AdultWork에 연결", "SplitCam의 <strong>Stream Settings</strong>를 열고 AdultWork 서버 URL과 stream key를 커스텀 RTMP 필드에 붙여넣으세요. 비트레이트는 3,500–6,000 Kbps, 1920×1080, 30 fps, 키프레임 2초."),
           ("Go Live 클릭", "SplitCam에서 <strong>Go Live</strong>를 누른 뒤 Members Area에서 온라인으로 전환. 약 10초 안에 신호가 AdultWork 오디언스에 도달합니다."),
       ]),
]
