# -*- coding: utf-8 -*-
"""Polish (pl) content for cam-streaming-guides. Native Polish, 20 platforms."""

_T_ETH = ("Użyj połączenia przewodowego", "Ethernet bije Wi-Fi przy długich transmisjach — zgubione "
          "klatki to zgubione napiwki. Podłącz kabel do komputera nadającego.")
_T_TEST = ("Najpierw zrób prywatny test", "Przeprowadź krótką transmisję testową, by sprawdzić kamerę, "
           "dźwięk, kadr i nakładki, zanim otworzysz pokój dla widzów.")

def _p(slug, name, title, desc, kw, h1html, h1short, card, intro, quick, key_how, tips, faq, steps=None):
    d = {"slug": slug, "name": name, "title": title, "desc": desc, "kw": kw,
         "h1html": h1html, "h1short": h1short, "card": card, "intro": intro,
         "quick": quick, "key_how": key_how, "tips": tips, "faq": faq}
    if steps: d["steps"] = steps
    return d

PLATFORMS_PL = [
    _p("chaturbate", "Chaturbate",
       "Transmisja na Chaturbate z SplitCam — Token i RTMP",
       "Transmisja na Chaturbate z darmowym SplitCam — broadcast token, RTMP, sceny wielokamerowe i nakładki. Bez znaku wodnego, bez rejestracji.",
       "transmisja chaturbate, chaturbate broadcast token, chaturbate rtmp obs, chaturbate enkoder zewnętrzny, chaturbate live",
       'Jak nadawać na <span class="accent">Chaturbate</span> z SplitCam',
       "Transmisja Chaturbate",
       "Konfiguracja oparta na tokenie z enkoderem zewnętrznym na Chaturbate.",
       "Chaturbate to jedna z największych platform cam, zbudowana na ekonomii tokenów. Jej przeglądarkowy nadajnik to tylko płaskie narzędzie jednokamerowe — przejście na <strong style='color:var(--text)'>enkoder zewnętrzny</strong> z darmowym <strong style='color:var(--text)'>SplitCam</strong> odblokowuje sceny wielokamerowe, nakładki i filtry w tej samej transmisji opartej na tokenach.",
       "Transmisja na Chaturbate z SplitCam: zainstaluj SplitCam, zbuduj scenę, na Chaturbate otwórz <em>Broadcast Yourself → My Broadcast</em>, skopiuj broadcast token, wklej w SplitCam, Go Live."
       "<ol><li>Zainstaluj SplitCam.</li><li>Dodaj kamerę + scenę.</li><li>Skopiuj broadcast token z Chaturbate.</li><li>Wklej w SplitCam.</li><li>Naciśnij Go Live.</li></ol>",
       "Na Chaturbate kliknij <strong>Broadcast Yourself</strong>, by przejść do strony <strong>My Broadcast</strong>, potem <strong>View RTMP/OBS broadcast information and stream key</strong>. Klucz pojawia się jako <strong>broadcast token</strong> — skopiuj go. Traktuj jak hasło; nigdy nie udostępniaj.",
       [("Token jest kluczem", "Chaturbate używa twojego broadcast tokena, nie ogólnego klucza streamu. Traktuj jak hasło i zresetuj, jeśli wycieknie."),
        ("Dużo zapasu", "RTMP ingest Chaturbate przyjmuje do 4K, 60 fps i wysoki bitrate — limitem jest twój upload, nie platforma. Klatka kluczowa co 2 sekundy."),
        _T_ETH, _T_TEST],
       [("Czy Chaturbate pozwala na OBS / enkoder zewnętrzny?", "Tak — Chaturbate oficjalnie wspiera enkodery zewnętrzne i ma własny artykuł «How do I set up OBS?». Włącz przez «Use External Encoder to Broadcast» w ustawieniach transmisji."),
        ("Gdzie jest mój klucz streamu Chaturbate?", "Broadcast Yourself → My Broadcast → View RTMP/OBS broadcast information and stream key. Kluczem jest twój broadcast token."),
        ("Jaki bitrate dla Chaturbate?", "3500–6000 Kbps w 1080p to aż nadto. Limit Chaturbate jest wysoki — realnym ograniczeniem jest twój upload; najpierw uruchom wbudowany test prędkości SplitCam."),
        ("Czy SplitCam jest darmowy dla Chaturbate?", "Tak — całkowicie darmowy, bez znaku wodnego i bez limitu czasu: enkoder nie zjada twoich zarobków w tokenach.")]),
    _p("cam4", "CAM4",
       "Transmisja na CAM4 z SplitCam — External Encoder",
       "Transmisja na CAM4 z darmowym SplitCam — External Encoder, klucz streamu, blokada geo i nakładki. Bez znaku wodnego.",
       "transmisja cam4, cam4.com, cam4 external encoder, cam4 klucz streamu, cam4 rtmp obs",
       'Jak nadawać na <span class="accent">CAM4</span> z SplitCam',
       "Transmisja CAM4",
       "External Encoder na CAM4 z kontrolą geo.",
       "CAM4 to globalna platforma cam-and-earn z wbudowaną kontrolą geo — możesz ukryć transmisję w wybranych krajach. Nadawanie przez darmowy <strong style='color:var(--text)'>SplitCam</strong> jako enkoder zewnętrzny odblokowuje przełączanie scen i nakładki, których podstawowy nadajnik nie ma.",
       "Transmisja na CAM4 z SplitCam: zainstaluj SplitCam, zbuduj scenę, na CAM4 otwórz <em>Broadcast &amp; Earn Money → Start Broadcast → External Encoder</em>, Get Stream Key, wklej w SplitCam, Go Live."
       "<ol><li>Zainstaluj SplitCam.</li><li>Dodaj kamerę + scenę.</li><li>Pobierz klucz streamu z CAM4.</li><li>Wklej w SplitCam.</li><li>Naciśnij Go Live.</li></ol>",
       "Na CAM4 kliknij <strong>Broadcast</strong> → <strong>Broadcast &amp; Earn Money</strong> → <strong>Start Broadcast</strong>, potem <strong>External Encoder</strong> u góry. Podaj datę urodzenia, płeć i kraj, użyj <strong>Get Stream Key</strong> i skopiuj. Zielony suwak w Stream Settings SplitCam oznacza połączenie.",
       [("Ustaw ograniczenia geo", "CAM4 pozwala ukryć transmisję w wybranych krajach i regionach — ustaw to po stronie CAM4 przed go-live."),
        ("Patrz na zielony suwak", "Konfiguracja CAM4 pokazuje zielony suwak w Stream Settings SplitCam, gdy klucz zostanie przyjęty — czerwony = sprawdź klucz."),
        ("Niższy bitrate niż zwykle", "RTMP ingest CAM4 ogranicza bitrate wideo do około 3000 Kbps — niżej niż większość serwisów cam. Nie wymuszaj wyższego."),
        _T_ETH],
       [("Czy CAM4 oficjalnie wspiera OBS / enkoder zewnętrzny?", "Tak — CAM4 ma oficjalny OBS Guide na stronie wsparcia i zaleca External Encoder dla najlepszego doświadczenia. SplitCam używa tej samej ścieżki RTMP."),
        ("Czy mogę zablokować geograficznie transmisję CAM4?", "Tak — CAM4 ma wbudowane ograniczenia geo, by ukryć transmisję w wybranych krajach. Ustaw to na CAM4, nie w SplitCam."),
        ("Gdzie jest klucz streamu CAM4?", "Broadcast → Broadcast & Earn Money → Start Broadcast → External Encoder → Get Stream Key."),
        ("Jaki bitrate dla CAM4?", "Niższy niż średnia — RTMP ingest CAM4 ogranicza ~3000 Kbps w 30 fps z klatką kluczową co 1 sekundę. Oficjalna tabela zaleca nie przekraczać ~3000.")]),
    _p("bongacams", "BongaCams",
       "Transmisja na BongaCams z SplitCam — External Encoder",
       "Transmisja na BongaCams z darmowym SplitCam — External Encoder, sceny wielokamerowe, nakładki i tła AI. Bez znaku wodnego.",
       "bongacams, bongcams, transmisja bongacams, bongacams external encoder, bongacams rtmp obs",
       'Jak nadawać na <span class="accent">BongaCams</span> z SplitCam',
       "Transmisja BongaCams",
       "Konfiguracja External Encoder dla BongaCams.",
       "BongaCams to globalna platforma cam. Nadawanie enkoderem zewnętrznym nie zawsze jest włączone — po aktywacji darmowy <strong style='color:var(--text)'>SplitCam</strong> przejmuje transmisję ze scenami wielokamerowymi, nakładkami i tłami AI.",
       "Transmisja na BongaCams z SplitCam: zainstaluj SplitCam, zbuduj scenę, na BongaCams otwórz <em>Options → Broadcast settings → Select Encoder → External Encoder</em>, skopiuj URL i klucz, wklej w SplitCam, Go Live."
       "<ol><li>Zainstaluj SplitCam.</li><li>Dodaj kamerę + scenę.</li><li>Pobierz URL i klucz z BongaCams.</li><li>Wklej w SplitCam.</li><li>Naciśnij Go Live.</li></ol>",
       "Na BongaCams otwórz <strong>Options</strong> → <strong>Broadcast settings</strong> → <strong>Select Encoder</strong> → <strong>External Encoder</strong> i skopiuj wyświetlony URL serwera oraz klucz streamu. <strong>Jeśli przycisku External Encoder nie ma</strong>, skontaktuj się ze wsparciem BongaCams i poproś o włączenie kodowania zewnętrznego na koncie.",
       [("Brak przycisku External Encoder? Wsparcie", "BongaCams włącza kodowanie zewnętrzne per konto — jeśli opcji nie ma w Broadcast settings, wsparcie ją aktywuje."),
        ("Dopasuj rozdzielczość", "BongaCams zaleca, by rozdzielczość kamery i transmisji się zgadzała — np. obie 1280×720."),
        _T_ETH, _T_TEST],
       [("Dlaczego przycisk External Encoder nie pojawia się na BongaCams?", "Kodowanie zewnętrzne nie jest domyślnie włączone na każdym koncie — skontaktuj się ze wsparciem BongaCams, by je włączyć, wtedy przycisk pojawi się w Broadcast settings."),
        ("Czy muszę zweryfikować konto BongaCams?", "Tak — transmisja wymaga 18+, oficjalnego dokumentu do weryfikacji wieku i zatwierdzenia konta przed live."),
        ("Jaki bitrate dla BongaCams?", "RTMP ingest BongaCams ogranicza bitrate wideo do około 6000 Kbps z klatką kluczową co 2 sekundy — 3500–6000 w 1080p to strefa idealna; najpierw przetestuj upload."),
        ("Czy SplitCam jest darmowy dla BongaCams?", "Tak — całkowicie darmowy, bez znaku wodnego i bez limitu czasu, więc enkoder nie uszczupla twoich zarobków w tokenach na BongaCams.")]),
    _p("stripchat", "Stripchat",
       "Transmisja na Stripchat z SplitCam — Konfiguracja strip cam",
       "Transmisja na Stripchat — platformie strip cam — z darmowym SplitCam. Oprogramowanie zewnętrzne, klucz oparty na tokenie, sceny i nakładki.",
       "strip cam, stripchat live stream, transmisja stripchat, stripchat external software, stripchat klucz streamu, stripchat rtmp obs",
       'Jak nadawać na <span class="accent">Stripchat</span> z SplitCam',
       "Transmisja Stripchat",
       "Konfiguracja oprogramowania zewnętrznego dla transmisji Stripchat.",
       "Stripchat to duża platforma cam skupiona na interaktywności. Tryb <em>external software</em> daje ci klucz oparty na tokenie — wprowadź go do darmowego <strong style='color:var(--text)'>SplitCam</strong>, by nadawać ze scenami, nakładkami i filtrami zamiast płaskiej kamery.",
       "Transmisja na Stripchat z SplitCam: zainstaluj SplitCam, zbuduj scenę, na Stripchat wybierz <em>Switch to external software</em>, skopiuj klucz streamu, wklej w SplitCam, Go Live."
       "<ol><li>Zainstaluj SplitCam.</li><li>Dodaj kamerę + scenę.</li><li>Pobierz klucz streamu ze Stripchat.</li><li>Wklej w SplitCam.</li><li>Naciśnij Go Live.</li></ol>",
       "Na Stripchat wybierz <strong>Switch to external software</strong>, potem <strong>Show external software settings for the stream</strong>. Skopiuj klucz streamu — Stripchat pokazuje go jako token. Zachowaj go w tajemnicy.",
       [("Dopasuj rozdzielczość do serwisu", "FAQ Stripchat ostrzega: rozdzielczość w twoim oprogramowaniu musi dokładnie pasować do serwisu, inaczej wideo się rozpada. Ustaw obie tak samo."),
        ("Uwaga na minimum 2 Mbps", "Stripchat podaje 2 Mbps uploadu jako minimum — i wprost mówi, że to za mało na transmisję OBS czy multistream. Celuj znacznie wyżej."),
        ("Klucz to token", "Klucz streamu Stripchat to token — skopiuj dokładnie, nigdy nie udostępniaj, zresetuj jeśli wycieknie."),
        _T_ETH],
       [("Czy Stripchat zaleca OBS / oprogramowanie zewnętrzne?", "Tak — oficjalne FAQ Stripchat zaleca zewnętrzne oprogramowanie do transmisji jak OBS «dla osiągnięcia najlepszej jakości obrazu i dźwięku». SplitCam działa tak samo."),
        ("Jak przełączyć Stripchat na oprogramowanie zewnętrzne?", "W Broadcast Center wybierz Switch to External Broadcast Software (OBS), potem otwórz external software settings, by pokazać klucz streamu (token)."),
        ("Jaki bitrate dla Stripchat?", "RTMP ingest przyjmuje do ~6000 Kbps z klatką kluczową co 2 sekundy. 3500–6000 w 1080p jest idealne — ale musi być znacznie powyżej minimum 2 Mbps, zwłaszcza przy transmisji OBS."),
        ("Czy SplitCam jest darmowy dla Stripchat?", "Tak — bez opłat licencyjnych, bez znaku wodnego, bez limitu czasu: nawet długie interaktywne show na Stripchat nic nie kosztują po stronie enkodera.")]),
    _p("onlyfans", "OnlyFans",
       "Live na OnlyFans z SplitCam — Autoryzacja lub klucz",
       "Live na OnlyFans z darmowym SplitCam — logowanie przez autoryzację lub OBS Key, sceny wielokamerowe, nakładki. Bez znaku wodnego.",
       "live onlyfans, onlyfans live stream, onlyfans autoryzacja splitcam, onlyfans obs key, onlyfans oprogramowanie do transmisji",
       'Jak prowadzić <span class="accent">live na OnlyFans</span> z SplitCam',
       "Live OnlyFans",
       "Autoryzuj raz lub wklej klucz — live na OnlyFans.",
       "Live OnlyFans dla twoich subskrybentów. SplitCam łączy się na <strong style='color:var(--text)'>dwa sposoby</strong> — zaloguj się raz kontem OnlyFans, a SplitCam automatycznie pobierze klucz streamu i będzie go synchronizować, albo wklej OBS Key ręcznie. Oba pozwalają nadawać ze scenami wielokamerowymi, nakładkami i filtrami.",
       "Live na OnlyFans z SplitCam: zainstaluj SplitCam, zbuduj scenę, otwórz Stream Settings &rarr; Add Channel &rarr; OnlyFans i wybierz <em>Autoryzacja</em> — zaloguj się kontem OnlyFans, SplitCam pobierze klucz automatycznie — i naciśnij Go Live. Przy połączonym koncie możesz zmieniać parametry transmisji OnlyFans w SplitCam bez otwierania strony OnlyFans.",
       "Na OnlyFans: <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; sekcja <strong>Other</strong>, skopiuj <strong>OBS Key</strong>. Albo użyj opcji <strong>Autoryzacja</strong> w SplitCam, by się zalogować — klucz zostanie pobrany automatycznie i pozostanie zsynchronizowany.",
       [("Autoryzacja vs Stream Key", "Dwa sposoby połączenia: <strong>Autoryzacja</strong> (zaloguj się raz, klucz pobierany i synchronizowany — najprostsza droga) lub <strong>Stream Key</strong> (skopiuj OBS Key w OnlyFans → Profile → Settings → Other i wklej)."),
        ("Zmieniaj ustawienia bez wychodzenia z SplitCam", "Przy autoryzacji konto pozostaje połączone, więc parametry live OnlyFans ustawiasz z poziomu SplitCam w trakcie lub po transmisji — bez wchodzenia na stronę OnlyFans."),
        ("Skromny bitrate", "RTMP ingest OnlyFans ogranicza bitrate wideo do około 2500 Kbps — ściślej niż większość serwisów cam. Celuj w 720p–1080p przy ~2000–2500."),
        _T_ETH],
       [("Jak połączyć OnlyFans ze SplitCam?", "Dwa sposoby. <strong>Autoryzacja</strong> — Stream Settings → Add Channel → OnlyFans → zaloguj się kontem OnlyFans, a SplitCam pobierze klucz automatycznie. Albo <strong>Stream Key</strong> — skopiuj OBS Key w OnlyFans → Profile → Settings → Other i wklej."),
        ("Czy mogę zmieniać ustawienia live OnlyFans bez otwierania strony?", "Tak — przy metodzie Autoryzacji SplitCam pozostaje połączony z kontem OnlyFans, więc klucz i ustawienia synchronizują się automatycznie. Wszystko zmieniasz z poziomu SplitCam w trakcie lub po transmisji, bez wchodzenia na onlyfans.com."),
        ("Jaki bitrate dla OnlyFans?", "Skromny — RTMP ingest OnlyFans ogranicza bitrate do około 2500 Kbps, znacznie ściślej niż inne platformy cam. Celuj w 720p–1080p przy około 2000–2500 Kbps."),
        ("Czy SplitCam jest darmowy dla live na OnlyFans?", "Tak — darmowy, bez znaku wodnego i bez limitu czasu. Żadnych kosztów po stronie enkodera.")],
       steps=[
           ("Pobierz i zainstaluj SplitCam", "SplitCam to darmowe oprogramowanie do transmisji na żywo dla Windows i macOS — bez rejestracji, bez karty, bez znaku wodnego. To enkoder, który wysyła twoje wideo do OnlyFans."),
           ("Skonfiguruj kamerę i scenę", "Otwórz SplitCam i dodaj kamerę. Zbuduj scenę tak, jak chcesz, by widzieli ją widzowie — nakładki, tekst, druga kamera, filtry upiększające lub tło AI, wszystko stosowane na żywo."),
           ("Połączenie — Sposób 1: Autoryzacja (zalecany)", "W SplitCam otwórz <strong>Stream Settings</strong> &rarr; <strong>Add Channel</strong> &rarr; <strong>OnlyFans</strong> i wybierz <strong>Autoryzacja</strong>. Zaloguj się e-mailem i hasłem OnlyFans. SplitCam połączy konto, automatycznie pobierze klucz streamu i będzie go synchronizować — a także pozwoli zarządzać parametrami live OnlyFans wewnątrz SplitCam, zmieniając je w trakcie lub po transmisji bez otwierania strony OnlyFans."),
           ("Połączenie — Sposób 2: Stream Key (ręczny)", "Wolisz się nie logować? Użyj klucza. Na OnlyFans otwórz <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; sekcja <strong>Other</strong> i skopiuj <strong>OBS Key</strong>. W SplitCam, Add Channel &rarr; OnlyFans, wklej w pole klucza. Ten klucz jest stały — by zmienić ustawienia później, wróć na stronę OnlyFans."),
           ("Go Live", "Niezależnie od sposobu, naciśnij <strong>Go Live</strong> w SplitCam. Przy Sposobie 1 możesz dalej dostrajać parametry OnlyFans z SplitCam w czasie rzeczywistym; przy Sposobie 2 klucz pozostaje dokładnie taki, jak ustawiłeś."),
       ]),
    _p("camplace", "CamPlace",
       "Transmisja na CamPlace z SplitCam — Darmowy poradnik",
       "Transmisja na CamPlace z darmowym SplitCam — enkoder zewnętrzny, klucz RTMP, sceny i nakładki. Krok po kroku, bez znaku wodnego.",
       "transmisja camplace, camplace broadcasting software, camplace rtmp, camplace enkoder zewnętrzny, camplace klucz streamu",
       'Jak nadawać na <span class="accent">CamPlace</span> z SplitCam',
       "Transmisja CamPlace",
       "Konfiguracja enkodera zewnętrznego dla transmisji CamPlace.",
       "CamPlace to platforma cam-streaming. Nie ma publicznego artykułu o OBS, więc <strong style='color:var(--text)'>poradnik wideo powyżej</strong> jest twoim punktem odniesienia — darmowy <strong style='color:var(--text)'>SplitCam</strong> łączy się przez standardowy RTMP i dodaje sceny, nakładki oraz tła AI, których podstawowa kamera nie ma.",
       "Transmisja na CamPlace z SplitCam: zainstaluj SplitCam, zbuduj scenę, włącz transmisję zewnętrzną/RTMP na CamPlace, skopiuj URL serwera i klucz streamu, wklej w SplitCam, Go Live. Podążaj za wideo dla aktualnej ścieżki."
       "<ol><li>Zainstaluj SplitCam.</li><li>Dodaj kamerę + scenę.</li><li>Pobierz klucz RTMP z CamPlace.</li><li>Wklej w SplitCam.</li><li>Naciśnij Go Live.</li></ol>",
       "Zaloguj się do CamPlace i otwórz ustawienia transmisji. Przełącz na opcję enkodera zewnętrznego / RTMP / OBS, by wyświetlić <strong>URL serwera</strong> i <strong>klucz streamu</strong>, skopiuj oba. CamPlace nie publikuje oficjalnej dokumentacji OBS — <strong>wideo powyżej</strong> to najpewniejsza ścieżka krok po kroku przez aktualny interfejs.",
       [("Brak oficjalnego poradnika OBS — użyj wideo", "CamPlace nie ma publicznego artykułu o enkoderze zewnętrznym; wideo powyżej jest punktem odniesienia dla aktualnej ścieżki."),
        ("Standardowy RTMP działa", "Choć nieudokumentowane, CamPlace przyjmuje standardowy URL serwera RTMP i klucz — SplitCam łączy się jako niestandardowy cel RTMP."),
        ("Układaj nakładki w SplitCam", "Cele napiwków, imię i uchwyty social media dodaj jako warstwy sceny — podstawowa kamera CamPlace ich nie doda."),
        _T_ETH],
       [("Czy CamPlace ma oficjalny poradnik OBS?", "Nie znaleziono publicznego artykułu o enkoderze zewnętrznym. CamPlace przyjmuje standardowy URL RTMP i klucz, więc SplitCam działa — podążaj za wideo."),
        ("Czy CamPlace wspiera enkoder zewnętrzny?", "Tak — przyjmuje standardowy klucz streamu RTMP, więc SplitCam łączy się jako niestandardowy cel RTMP."),
        ("Jaki bitrate dla CamPlace?", "CamPlace nie publikuje oficjalnych liczb — użyj 3500–6000 Kbps w 1080p jako bezpiecznego zakresu i pozwól, by test prędkości SplitCam ustalił realny limit."),
        ("Czy SplitCam jest darmowy dla CamPlace?", "Tak — darmowy, bez znaku wodnego i bez limitu czasu. Ponieważ CamPlace nie ma własnego enkodera, darmowe narzędzie RTMP rozwiązuje sprawę.")]),
    _p("camsoda", "CamSoda",
       "CamSoda live z SplitCam — Darmowa konfiguracja",
       "CamSoda live z darmowym SplitCam — Use OBS Broadcaster, serwery regionalne, sceny i nakładki. Bez znaku wodnego.",
       "camsoda live, transmisja camsoda, camsoda obs broadcaster, camsoda rtmp obs, camsoda live broadcast",
       'Jak nadawać na <span class="accent">CamSoda</span> z SplitCam',
       "Transmisja CamSoda",
       "Konfiguracja Use OBS Broadcaster na CamSoda.",
       "CamSoda to platforma cam z USA znana z interaktywnych, nietypowych formatów show. Oficjalnie wspiera transmisję OBS — jest przycisk <strong style='color:var(--text)'>Use OBS Broadcaster</strong> na stronie Go Live i oficjalny poradnik OBS na wiki CamSoda. Darmowy <strong style='color:var(--text)'>SplitCam</strong> działa tak samo.",
       "Transmisja na CamSoda z SplitCam: zainstaluj SplitCam, zbuduj scenę, kliknij Use OBS Broadcaster na stronie Go Live CamSoda, skopiuj URL serwera i klucz streamu, wklej w SplitCam, Go Live."
       "<ol><li>Zainstaluj SplitCam.</li><li>Dodaj kamerę + scenę.</li><li>Kliknij Use OBS Broadcaster na CamSoda.</li><li>Wklej URL serwera + klucz w SplitCam.</li><li>Naciśnij Go Live.</li></ol>",
       "Na stronie <strong>Go Live</strong> CamSoda kliknij <strong>Use OBS Broadcaster</strong>. CamSoda pokazuje URL serwera RTMP i klucz streamu — skopiuj oba. Wybierz najbliższy serwer regionalny (Ameryka Północna, Europa, Azja itd.). Wiki CamSoda ma pełny poradnik OBS po szczegóły.",
       [("Zweryfikuj się, by przyjmować napiwki", "Na CamSoda każdy może nadawać, ale by przyjmować napiwki, musisz ukończyć proces weryfikacji CamSoda."),
        ("Wybierz najbliższy serwer regionalny", "CamSoda oferuje regionalne serwery ingest — najbliższy (NA / Europa / Azja / Ameryka Południowa / Oceania) zmniejsza opóźnienie i zgubione klatki."),
        ("Limit w 1080p / 30 fps", "Ingest CamSoda sięga około 1080p, 30 fps i ~6000 Kbps — nie wymuszaj wyższego."),
        _T_ETH],
       [("Czy CamSoda wspiera OBS / enkoder zewnętrzny?", "Tak — oficjalnie. Jest przycisk Use OBS Broadcaster na stronie Go Live i poradnik OBS na wiki CamSoda, więc SplitCam działa."),
        ("Czy potrzebuję weryfikacji na CamSoda?", "Do nadawania nie. Do przyjmowania napiwków tak — CamSoda wymaga wcześniejszego procesu weryfikacji."),
        ("Jaką rozdzielczość wspiera CamSoda?", "Do 1920×1080 w 30 fps, maksymalnie około 6000 Kbps w RTMP ingest."),
        ("Czy SplitCam jest darmowy dla CamSoda?", "Tak — darmowy, bez znaku wodnego i bez limitu czasu. Działa z darmowym trybem Use OBS Broadcaster CamSoda, więc cały zestaw nic nie kosztuje.")]),
    _p("streamate", "Streamate",
       "Transmisja na Streamate z SplitCam — Zintegrowany kanał",
       "Transmisja na Streamate z darmowym SplitCam — zintegrowany kanał, klucz SM Connect, sceny i nakładki. Bez znaku wodnego.",
       "streamate, streamate sm connect, transmisja streamate, streamate broadcasting software, streamate rtmp",
       'Jak nadawać na <span class="accent">Streamate</span> z SplitCam',
       "Transmisja Streamate",
       "Streamate to zintegrowany kanał w SplitCam — szybka konfiguracja.",
       "Streamate to uznana platforma cam — i jest <strong style='color:var(--text)'>wstępnie skonfigurowanym celem w SplitCam</strong>, na liście kanałów, więc konfiguracja jest szybsza niż ręczne wprowadzanie RTMP: wybierz Streamate, wklej klucz, gotowe.",
       "Transmisja na Streamate z SplitCam: zainstaluj SplitCam, zbuduj scenę, na Streamate użyj <em>SM Connect → Start Show</em> i skopiuj klucz, potem w SplitCam otwórz <em>Stream Settings → Add Channel → Streamate</em> i wklej."
       "<ol><li>Zainstaluj SplitCam.</li><li>Dodaj kamerę + scenę.</li><li>Pobierz klucz Streamate przez SM Connect.</li><li>Add Channel → Streamate w SplitCam.</li><li>Naciśnij Go Live.</li></ol>",
       "Na Streamate otwórz <strong>SM Connect</strong>, zaakceptuj warunki, kliknij <strong>Start Show</strong> po lewej i zamknij otwarte okno — potem skopiuj klucz streamingu. W SplitCam otwórz <strong>Stream Settings</strong> → <strong>Add Channel</strong>, wybierz <strong>Streamate</strong> z listy i wklej klucz. Zielony suwak oznacza połączenie.",
       [("Streamate jest zintegrowany", "Bez ręcznego URL RTMP — SplitCam ma Streamate na liście Add Channel; po prostu wybierz i wklej klucz."),
        ("Zamknij popup SM Connect", "Po Start Show Streamate otwiera okno — zamknij je; służy tylko do pokazania klucza streamingu."),
        ("Zablokuj rozdzielczość na 1080p", "Pole Video Resolution w SM Connect może po cichu przeskoczyć na 1440, które realnie nie jest wysyłane i niezauważalnie obniża twoją jakość — ustaw ręcznie na 1080p. Spadek bitrate przy nieruchomym obrazie jest normalny: stream Streamate jest adaptacyjny."),
        _T_ETH, _T_TEST],
       [("Czy Streamate jest zintegrowany w SplitCam?", "Tak — Streamate pojawia się na liście Add Channel SplitCam; wybierasz go, a nie wpisujesz ręcznie URL RTMP."),
        ("Gdzie jest klucz streamingu Streamate?", "SM Connect → zaakceptuj warunki → Start Show → zamknij popup → skopiuj klucz."),
        ("Jaki bitrate dla Streamate?", "Streamate nie ustala twardego limitu — 3500–6000 Kbps w 1080p działa dobrze. Stream jest adaptacyjny, więc niższy bitrate przy nieruchomym obrazie jest normalny, nie jest błędem."),
        ("Czy SplitCam jest darmowy dla Streamate?", "Tak — darmowy, bez znaku wodnego i bez limitu czasu; a ponieważ Streamate to zintegrowany kanał w SplitCam, nie ma osobnych kosztów enkodera.")]),
    _p("streamray", "StreamRay",
       "Transmisja na StreamRay cam z SplitCam — URL na czacie",
       "Transmisja na StreamRay cam z darmowym SplitCam — URL publikowany na czacie, tryb OBS Broadcaster, sceny i nakładki. Bez znaku wodnego.",
       "streamray, streamray cam, transmisja streamray, streamray obs broadcaster, streamray rtmp",
       'Jak nadawać na <span class="accent">StreamRay</span> z SplitCam',
       "Transmisja StreamRay",
       "Konfiguracja enkodera zewnętrznego typu URL-na-czacie dla StreamRay.",
       "StreamRay ma nietypową konfigurację enkodera zewnętrznego — wysyła URL streamu w <strong style='color:var(--text)'>oknie czatu transmisji</strong> i nie używa osobnego klucza streamu. Darmowy <strong style='color:var(--text)'>SplitCam</strong> obsługuje ten przepływ oparty tylko na URL.",
       "Transmisja na StreamRay z SplitCam: zainstaluj SplitCam, zbuduj scenę, na StreamRay włącz OBS Broadcaster, skopiuj URL streamu z okna czatu, wklej w SplitCam (zostaw pole klucza puste), Go Live."
       "<ol><li>Zainstaluj SplitCam.</li><li>Dodaj kamerę + scenę.</li><li>Skopiuj URL StreamRay z czatu.</li><li>Wklej URL w SplitCam.</li><li>Naciśnij Go Live.</li></ol>",
       "Na StreamRay kliknij dwukrotnie <strong>Broadcast Now</strong>, otwórz menu <strong>Other</strong>, wybierz <strong>OBS Broadcaster</strong> i <strong>Save and Close</strong>. StreamRay następnie publikuje <strong>URL streamu w oknie czatu</strong> — skopiuj go stamtąd. Zostaw pole klucza streamu SplitCam <strong>puste</strong>; StreamRay weryfikuje tylko przez URL.",
       [("URL jest na czacie", "StreamRay nie pokazuje URL streamu w polu ustawień — publikuje go w oknie czatu transmisji. Skopiuj go stamtąd."),
        ("Zostaw pole klucza puste", "StreamRay nie używa osobnego klucza — tylko URL. Nie wpisuj nic w pole klucza SplitCam."),
        _T_ETH, _T_TEST],
       [("Gdzie jest URL streamu StreamRay?", "Po włączeniu OBS Broadcaster StreamRay publikuje URL w oknie czatu — skopiuj go z czatu."),
        ("Dlaczego nie ma klucza streamu na StreamRay?", "StreamRay weryfikuje tylko przez URL — zostaw pole klucza SplitCam puste."),
        ("Jaki bitrate dla StreamRay?", "StreamRay nie podaje oficjalnego limitu — celuj w 3500–6000 Kbps w 1080p i uruchom test prędkości SplitCam, bo przepływ oparty na URL nie daje informacji zwrotnej o bitrate."),
        ("Czy SplitCam jest darmowy dla StreamRay?", "Tak — darmowy, bez znaku wodnego i bez limitu czasu, pasuje do przepływu StreamRay opartego na URL: wklej jeden link i jesteś na żywo.")]),
    _p("xlovecam", "XLoveCam",
       "Transmisja na XLoveCam z SplitCam — Link RTMP i klucz",
       "Transmisja na XLoveCam z darmowym SplitCam — link RTMP i klucz, serwery regionalne, sceny i nakładki. Bez znaku wodnego.",
       "xlovecam, x love cam, transmisja xlovecam, xlovecam rtmp link, xlovecam klucz streamu",
       'Jak nadawać na <span class="accent">XLoveCam</span> z SplitCam',
       "Transmisja XLoveCam",
       "Konfiguracja link RTMP + klucz dla XLoveCam.",
       "XLoveCam to europejska, wielojęzyczna platforma cam. Ustawienia konta pokazują zarówno <strong style='color:var(--text)'>link RTMP</strong>, jak i <strong style='color:var(--text)'>klucz streamu</strong> — darmowy <strong style='color:var(--text)'>SplitCam</strong> pobiera oba i nadaje z pełnymi scenami oraz nakładkami.",
       "Transmisja na XLoveCam z SplitCam: zainstaluj SplitCam, zbuduj scenę, na XLoveCam otwórz <em>My Account → settings</em>, skopiuj link RTMP i klucz streamu, wklej oba w SplitCam, rozpocznij show."
       "<ol><li>Zainstaluj SplitCam.</li><li>Dodaj kamerę + scenę.</li><li>Skopiuj link RTMP + klucz z XLoveCam.</li><li>Wklej oba w SplitCam.</li><li>Naciśnij Go Live.</li></ol>",
       "Na XLoveCam otwórz <strong>My Account</strong> → <strong>settings</strong>. Ustawienia pokazują zarówno <strong>link RTMP</strong>, jak i <strong>klucz streamu</strong> — skopiuj oba w pola URL serwera i klucza SplitCam, potem <strong>Start your show</strong> na XLoveCam.",
       [("Skopiuj link I klucz", "XLoveCam daje link RTMP I osobny klucz streamu — potrzebujesz obu w SplitCam, nie tylko jednego."),
        ("Wielojęzyczna publiczność", "XLoveCam jest europejski i wielojęzyczny — czytelne nakładki tekstowe w twoim języku pomagają widzom cię znaleźć."),
        ("Wybierz najbliższy serwer", "XLoveCam oferuje regionalne serwery RTMP — Europa, Ameryka Północna, Ameryka Południowa i Azja. Najbliższy zmniejsza opóźnienie i zgubione klatki."),
        _T_ETH],
       [("Gdzie są dane RTMP XLoveCam?", "My Account → settings — pokazuje zarówno link RTMP, jak i klucz."),
        ("Czy XLoveCam wspiera enkoder zewnętrzny?", "Tak — udostępnia link RTMP i klucz, więc SplitCam działa jako enkoder."),
        ("Jaki bitrate dla XLoveCam?", "XLoveCam nie publikuje stałego limitu; 3500–6000 Kbps w 1080p jest idealne. Wybór najbliższego serwera regionalnego jest równie ważny — zmniejsza zgubione klatki."),
        ("Czy SplitCam jest darmowy dla XLoveCam?", "Tak — darmowy, bez znaku wodnego i bez limitu czasu. Dotarcie do wielojęzycznej europejskiej publiczności XLoveCam nie wymaga kosztów oprogramowania.")]),
    _p("soulcams", "SoulCams",
       "Transmisja na SoulCams z SplitCam — Konfiguracja OBS",
       "Transmisja na SoulCams z darmowym SplitCam — konfiguracja OBS, serwer RTMP i klucz, sceny wielokamerowe i nakładki.",
       "soul cams, soulcams, transmisja soulcams, soulcams obs, soulcams rtmp, soulcams broadcast",
       'Jak nadawać na <span class="accent">SoulCams</span> z SplitCam',
       "Transmisja SoulCams",
       "Konfiguracja OBS dla SoulCams.",
       "SoulCams to platforma cam, której konfiguracja OBS pokazuje <strong style='color:var(--text)'>serwer RTMP i klucz streamu razem</strong> w jednym oknie. Wklej oba do darmowego <strong style='color:var(--text)'>SplitCam</strong>, by nadawać ze scenami wielokamerowymi i nakładkami.",
       "Transmisja na SoulCams z SplitCam: zainstaluj SplitCam, zbuduj scenę, na SoulCams kliknij Go Online → Settings → OBS, skopiuj serwer i klucz, wklej oba w SplitCam, Go Live."
       "<ol><li>Zainstaluj SplitCam.</li><li>Dodaj kamerę + scenę.</li><li>Otwórz SoulCams Settings → OBS.</li><li>Wklej serwer + klucz w SplitCam.</li><li>Naciśnij Go Live.</li></ol>",
       "Na SoulCams zaloguj się i kliknij <strong>Go Online</strong>, potem otwórz <strong>Settings</strong> → <strong>OBS</strong>. Okno OBS pokazuje <strong>serwer RTMP</strong> i <strong>klucz streamu</strong> razem — skopiuj oba do SplitCam.",
       [("Serwer i klucz obok siebie", "SoulCams pokazuje serwer RTMP i klucz w tym samym oknie OBS — weź oba naraz."),
        ("Najpierw Go Online", "Ustawienia OBS pojawiają się dopiero po kliknięciu Go Online na SoulCams — zrób to przed szukaniem danych enkodera."),
        ("Zablokuj niechciane regiony", "SoulCams pozwala na blokadę geo po stronie modelki — wybierz, które kraje nie zobaczą streamu, przed kliknięciem Go Online."),
        _T_ETH, _T_TEST],
       [("Gdzie są ustawienia OBS SoulCams?", "Zaloguj się, kliknij Go Online, potem Settings → OBS — serwer RTMP i klucz streamu są pokazane razem."),
        ("Czy SoulCams wspiera enkoder zewnętrzny?", "Tak — ustawienia OBS dają serwer RTMP i klucz, więc SplitCam działa."),
        ("Jaki bitrate dla SoulCams?", "SoulCams nie podaje oficjalnych liczb — celuj w 3500–6000 Kbps w 1080p i przetestuj upload, bo okno OBS nie pokazuje wskazówek o bitrate."),
        ("Czy SplitCam jest darmowy dla SoulCams?", "Tak — darmowy, bez znaku wodnego i bez limitu czasu, więc pełne show na SoulCams ze scenami wielokamerowymi i nakładkami nic nie kosztują po stronie enkodera.")]),
    _p("imlive", "ImLive",
       "Użyj ImLive z SplitCam — Kamera wirtualna",
       "Konfiguracja Im Live stream z darmowym SplitCam — ImLive używa kamery na żywo (bez RTMP), podłącz SplitCam jako kamerę wirtualną ze scenami.",
       "im live stream, imlive splitcam, transmisja imlive, imlive kamera wirtualna, imlive webcam, im live cam",
       'Jak używać <span class="accent">ImLive</span> z SplitCam',
       "SplitCam na ImLive",
       "Konfiguracja kamery wirtualnej dla ImLive — bez RTMP.",
       "ImLive używa kamery na żywo w przeglądarce — <strong style='color:var(--text)'>bez RTMP i klucza streamu</strong>. Darmowy <strong style='color:var(--text)'>SplitCam</strong> łączy się jako <strong style='color:var(--text)'>kamera wirtualna</strong>: zbuduj scenę w SplitCam, potem wybierz SplitCam jako kamerę na ImLive.",
       "Użycie SplitCam z ImLive: zainstaluj SplitCam, zbuduj scenę z warstwami mediów, otwórz ImLive i rozpocznij wideoczat, w ustawieniach ImLive wybierz SplitCam jako kamerę i mikrofon."
       "<ol><li>Zainstaluj SplitCam.</li><li>Zbuduj scenę w SplitCam.</li><li>Rozpocznij wideoczat na ImLive.</li><li>Wybierz SplitCam jako kamerę ImLive.</li><li>Rozpocznij czat.</li></ol>",
       "Zaloguj się na stronę ImLive i kliknij <strong>Start Video Chat</strong>, potem otwórz <strong>Go To Settings</strong>, by uzyskać dostęp do opcji kamery i mikrofonu. W ustawieniach ImLive wybierz <strong>SplitCam</strong> jako kamerę i mikrofon.",
       [("Klucz streamu niepotrzebny", "ImLive nie ma RTMP — nie szukaj URL serwera ani klucza. SplitCam jest tylko wybierany jako urządzenie kamery."),
        ("Ustaw SplitCam też jako mikrofon", "Wybierz SplitCam dla mikrofonu obok kamery, by miks dźwięku i redukcja szumów też trafiały na live."),
        ("Zbuduj scenę przed live", "ImLive pokazuje to, co wysyła SplitCam — ułóż warstwy przed rozpoczęciem czatu."),
        _T_TEST],
       [("Czy ImLive używa RTMP lub klucza streamu?", "Żadnego — ImLive używa kamery na żywo przez przeglądarkę. SplitCam łączy się jako kamera wirtualna, nie ma klucza do skopiowania."),
        ("Jak wybrać SplitCam na ImLive?", "Start Video Chat → Go To Settings → wybierz SplitCam jako kamerę i mikrofon."),
        ("Czy mogę używać nakładek na ImLive?", "Tak — zbuduj je w scenie SplitCam; ImLive pokazuje złożony rezultat."),
        ("Czy SplitCam jest darmowy dla ImLive?", "Tak — darmowy, bez znaku wodnego i bez limitu czasu. Jako kamera wirtualna dla ImLive nie dodaje kosztów ani brandingu do twojego wideoczatu.")],
       steps=[
           ("Zainstaluj SplitCam", "SplitCam to darmowe oprogramowanie dla Windows i macOS. Zainstaluj — bez znaku wodnego, bez rejestracji. Dla ImLive działa jako <strong>kamera wirtualna</strong>, nie enkoder RTMP."),
           ("Zbuduj scenę w SplitCam", "Otwórz SplitCam i użyj <strong>Media Layers +</strong>, by dodać kamerę plus dowolne nakładki, tekst, filtry lub tło AI. Ta złożona scena to to, co ImLive zobaczy jako twoją kamerę."),
           ("Rozpocznij wideoczat na ImLive", "Zaloguj się na stronę ImLive i kliknij <strong>Start Video Chat</strong>, potem otwórz <strong>Go To Settings</strong>, by uzyskać dostęp do opcji kamery i mikrofonu."),
           ("Wybierz SplitCam jako kamerę", "W ustawieniach ImLive wybierz <strong>SplitCam</strong> jako kamerę I mikrofon. ImLive pokazuje teraz twoją pełną scenę SplitCam, nie płaską kamerę."),
           ("Rozpocznij Free Live Chat", "Kliknij <strong>Free Live Chat</strong> na ImLive, by wejść na żywo. By zmienić wygląd w trakcie sesji, edytuj scenę w SplitCam — ImLive aktualizuje się natychmiast."),
       ]),
    _p("vxlive", "VXLive",
       "Transmisja na VXLive z SplitCam — Oficjalne wsparcie",
       "Transmisja na VXLive (VXModels / VISIT-X) z darmowym SplitCam — oficjalny preset VISIT-X, serwer i klucz, sceny. Bez znaku wodnego.",
       "vxlive, visit-x, vxmodels splitcam, transmisja vxlive, visit-x stream, vxlive rtmp",
       'Jak nadawać na <span class="accent">VXLive</span> z SplitCam',
       "Transmisja VXLive",
       "VXLive oficjalnie wspiera SplitCam (preset VISIT-X).",
       "VXLive (VXModels / VISIT-X) to platforma cam z rynku niemieckiego — i jedna z niewielu, które <strong style='color:var(--text)'>oficjalnie wspierają SplitCam z nazwy</strong>. VXModels ma dedykowany artykuł pomocy o łączeniu <strong style='color:var(--text)'>SplitCam</strong> z VXLive, a SplitCam ma VISIT-X jako gotowy preset kanału.",
       "Transmisja na VXLive z SplitCam: zainstaluj SplitCam, zbuduj scenę, na VXLive wybierz «Stream with third-party software», skopiuj URL serwera i klucz, w SplitCam wybierz preset VISIT-X i wklej, Go Live w SplitCam, potem GO ONLINE na VXLive."
       "<ol><li>Zainstaluj SplitCam.</li><li>Dodaj kamerę + scenę.</li><li>Pobierz URL serwera + klucz z VXLive.</li><li>Wybierz preset VISIT-X w SplitCam, wklej.</li><li>Go Live, potem GO ONLINE na VXLive.</li></ol>",
       "Na VXLive wybierz <strong>Stream with third-party software</strong> i opcję <strong>OBS, SplitCam lub XSplit</strong>. VXLive udostępnia <strong>URL serwera</strong> i <strong>klucz streamu</strong>. W SplitCam wybierz <strong>VISIT-X</strong> jako platformę streamingu, wklej oba, naciśnij <strong>Go Live</strong> w SplitCam, potem <strong>GO ONLINE</strong> na VXLive.",
       [("VISIT-X to zintegrowany preset", "Nie wpisuj surowego URL RTMP — SplitCam ma VISIT-X na liście platform; po prostu wybierz i wklej URL serwera oraz klucz."),
        ("Dwuetapowe go-live", "Na VXLive naciśnij najpierw Go Live w SplitCam, potem GO ONLINE na VXLive — oba, w tej kolejności."),
        ("Rynek niemiecki", "Publiczność VXLive jest głównie niemieckojęzyczna — nakładki tekstowe lub tytuły po niemiecku pomagają połączyć się z widzami."),
        _T_ETH],
       [("Czy VXLive oficjalnie wspiera SplitCam?", "Tak — VXModels (VXLive) prowadzi dedykowany oficjalny artykuł pomocy o konfiguracji SplitCam i wymienia SplitCam obok OBS i XSplit jako wspierane oprogramowanie do transmisji."),
        ("Jak połączyć SplitCam z VXLive?", "Na VXLive wybierz «Stream with third-party software», potem w SplitCam wybierz preset VISIT-X i wklej URL serwera oraz klucz streamu, które daje VXLive."),
        ("Czy jestem na żywo w SplitCam czy VXLive?", "W obu — najpierw Go Live w SplitCam, potem GO ONLINE na VXLive."),
        ("Dlaczego VXModels zaleca SplitCam?", "Oficjalny artykuł pomocy VXModels zaleca SplitCam konkretnie, by usunąć artefakty obrazu kamery i pikselozę oraz ustabilizować połączenie — nie tylko jako ogólny enkoder.")]),
    _p("virtwish", "VirtWish",
       "Transmisja na VirtWish z SplitCam — URL streamu i klucz",
       "Transmisja na VirtWish z darmowym SplitCam — sekcja OBS Profile → Start Broadcast, URL streamu i klucz, sceny i nakładki.",
       "virtwish, transmisja virtwish, virtwish broadcasting software, virtwish rtmp, virtwish klucz streamu, virtwish obs",
       'Jak nadawać na <span class="accent">VirtWish</span> z SplitCam',
       "Transmisja VirtWish",
       "Konfiguracja URL streamu + klucz dla VirtWish.",
       "VirtWish to interaktywna platforma cam. Ustawienia transmisji dają ci <strong style='color:var(--text)'>osobny URL streamu i klucz streamu</strong> w sekcji OBS — darmowy <strong style='color:var(--text)'>SplitCam</strong> pobiera oba i prowadzi show ze scenami oraz nakładkami.",
       "Transmisja na VirtWish z SplitCam: zainstaluj SplitCam, zbuduj scenę, na VirtWish otwórz <em>Profile → Start Broadcast</em> do sekcji OBS, skopiuj link i klucz, wklej oba w SplitCam, Go Live."
       "<ol><li>Zainstaluj SplitCam.</li><li>Dodaj kamerę + scenę.</li><li>Pobierz URL + klucz z VirtWish.</li><li>Wklej oba w SplitCam.</li><li>Naciśnij Go Live.</li></ol>",
       "Na VirtWish kliknij ikonę w prawym górnym rogu → <strong>Profile</strong> → <strong>Start Broadcast</strong>, potem <strong>Start Broadcast</strong> ponownie, by dotrzeć do sekcji OBS. <strong>Skopiuj link z pierwszego wiersza</strong> w pole Stream URL SplitCam, a osobny <strong>Stream Key</strong> w pole klucza.",
       [("Link jest w pierwszym wierszu", "Sekcja OBS VirtWish umieszcza URL streamu w pierwszym wierszu — skopiuj go w Stream URL SplitCam, potem osobny klucz."),
        ("Dwa kliknięcia Start Broadcast", "Klikasz Start Broadcast dwa razy na VirtWish, by dotrzeć do sekcji OBS — to normalne, nie błąd."),
        _T_ETH, _T_TEST],
       [("Gdzie są dane RTMP VirtWish?", "Ikona w prawym górnym rogu → Profile → Start Broadcast dwa razy → sekcja OBS pokazuje link i klucz streamu."),
        ("Czy VirtWish wspiera enkoder zewnętrzny?", "Tak — sekcja OBS udostępnia URL streamu i klucz, więc SplitCam działa."),
        ("Jaki bitrate dla VirtWish?", "VirtWish nie publikuje oficjalnego limitu; 3500–6000 Kbps w 1080p jest bezpieczne. Dopasuj rozdzielczość SplitCam do tej ustawionej w VirtWish, by uniknąć przeskalowania."),
        ("Czy SplitCam jest darmowy dla VirtWish?", "Tak — darmowy, bez znaku wodnego i bez limitu czasu. Konfiguracja URL-i-klucz VirtWish zajmuje tylko potrzebne kilka minut.")]),
    _p("xmodels", "XModels",
       "Transmisja na XModels z SplitCam — Darmowy poradnik",
       "Transmisja na XModels z darmowym SplitCam — opcja enkodera zewnętrznego w ustawieniach konta modela, klucz RTMP, sceny i nakładki.",
       "xmodels, transmisja xmodels, xmodels broadcasting software, xmodels rtmp, xmodels enkoder zewnętrzny",
       'Jak nadawać na <span class="accent">XModels</span> z SplitCam',
       "Transmisja XModels",
       "Konfiguracja enkodera zewnętrznego dla transmisji XModels.",
       "XModels to platforma cam-streaming z wbudowaną <strong style='color:var(--text)'>opcją enkodera zewnętrznego</strong> w ustawieniach konta modela. Darmowy <strong style='color:var(--text)'>SplitCam</strong> nadaje tam ze scenami wielokamerowymi, nakładkami i filtrami, zamiast jednej płaskiej kamery.",
       "Transmisja na XModels z SplitCam: zainstaluj SplitCam, zbuduj scenę, na koncie modela XModels włącz opcję enkodera zewnętrznego, skopiuj URL serwera i klucz streamu, wklej w SplitCam, Go Live."
       "<ol><li>Zainstaluj SplitCam.</li><li>Dodaj kamerę + scenę.</li><li>Włącz enkoder zewnętrzny w ustawieniach XModels.</li><li>Wklej URL serwera + klucz w SplitCam.</li><li>Naciśnij Go Live.</li></ol>",
       "W <strong>ustawieniach konta modela</strong> XModels włącz opcję <strong>transmisji przez enkoder zewnętrzny</strong>. XModels udostępnia <strong>klucz streamu</strong> — skopiuj go do SplitCam. Jeśli opcji nie ma tam, gdzie się jej spodziewasz, wsparcie XModels jest przez czat FAQ na stronie i <strong>info@xmodels.com</strong>; wideo powyżej też to pokazuje.",
       [("Jest w ustawieniach konta", "XModels umieszcza opcję enkodera zewnętrznego w ustawieniach konta modela, nie na osobnym ekranie transmisji."),
        ("Wsparcie: czat + e-mail", "XModels nie ma dużego publicznego centrum pomocy — czat FAQ na stronie i info@xmodels.com to oficjalne kanały wsparcia."),
        ("Układaj nakładki w SplitCam", "Cele napiwków, imię i uchwyty social media dodaj jako warstwy sceny — podstawowa kamera XModels ich nie doda."),
        _T_ETH],
       [("Czy XModels wspiera enkoder zewnętrzny?", "Tak — ustawienia konta modela mają opcję transmisji enkoderem zewnętrznym, która udostępnia klucz streamu, więc SplitCam działa."),
        ("Gdzie uzyskać pomoc XModels?", "Wsparcie XModels jest przez czat FAQ na stronie i e-mail info@xmodels.com — nie ma dużego publicznego centrum pomocy."),
        ("Jaki bitrate dla XModels?", "XModels nie dokumentuje oficjalnych liczb — użyj 3500–6000 Kbps w 1080p i uruchom test prędkości SplitCam, bo wsparcie XModels jest tylko przez czat i e-mail."),
        ("Czy SplitCam jest darmowy dla XModels?", "Tak — darmowy, bez znaku wodnego i bez limitu czasu, więc nadawanie do europejskiej sieci XModels nie dodaje kosztów oprogramowania.")]),
    _p("flirt4free", "Flirt4Free",
       "Transmisja na Flirt for Free cam z SplitCam — Darmowy poradnik",
       "Transmisja na Flirt for Free cam z darmowym SplitCam — External Broadcast Form, RTMP URL i Stream Name, sceny i nakładki.",
       "flirt for free cam, flirt 4 free cam, flirt4free, transmisja flirt4free, flirt4free external broadcast, flirt4free rtmp",
       'Jak nadawać na <span class="accent">Flirt4Free</span> z SplitCam',
       "Transmisja Flirt4Free",
       "Konfiguracja External Broadcast Form dla Flirt4Free.",
       "Flirt4Free to jedna z najstarszych platform cam, na antenie od lat 90. Oficjalnie wspiera transmisję zewnętrzną przez <strong style='color:var(--text)'>External Broadcast Form</strong> — darmowy <strong style='color:var(--text)'>SplitCam</strong> wysyła stream, a formularz ustawia rozdzielczość i bitrate.",
       "Transmisja na Flirt4Free z SplitCam: zainstaluj SplitCam, zbuduj scenę, otwórz External Broadcast Form Flirt4Free, skopiuj RTMP URL i Stream Name oraz ustaw rozdzielczość/bitrate, wklej w SplitCam, Go Live."
       "<ol><li>Zainstaluj SplitCam.</li><li>Dodaj kamerę + scenę.</li><li>Otwórz External Broadcast Form Flirt4Free.</li><li>Wklej RTMP URL + Stream Name w SplitCam.</li><li>Naciśnij Go Live.</li></ol>",
       "W strefie modela Flirt4Free otwórz <strong>External Broadcast Form</strong>. Inaczej niż większość serwisów cam, Flirt4Free daje <strong>RTMP URL</strong> i <strong>Stream Name</strong> (nie «klucz»), plus pola rozdzielczości i bitrate, które wypełniasz w samym formularzu. Skopiuj URL i Stream Name w pola serwera i klucza SplitCam.",
       [("To Stream Name, nie klucz", "Flirt4Free nazywa swoje dane Stream Name. Wklejasz je w pole klucza streamu SplitCam — funkcja jest taka sama."),
        ("Ustaw rozdzielczość/bitrate w formularzu", "External Broadcast Form Flirt4Free ma własne pola rozdzielczości i bitrate — dopasuj je do ustawień SplitCam, by obraz nie był przeskalowany."),
        ("Platforma z historią", "Flirt4Free działa od lat 90 — jego narzędzia dla modeli są dojrzałe, a External Broadcast Form to udokumentowana ich część."),
        _T_ETH],
       [("Czy Flirt4Free wspiera enkoder zewnętrzny?", "Tak — oficjalnie, przez External Broadcast Form, który udostępnia RTMP URL i Stream Name. SplitCam działa jako enkoder."),
        ("Gdzie uzyskać dane RTMP Flirt4Free?", "Z External Broadcast Form w strefie modela — pokazuje RTMP URL, Stream Name i pola rozdzielczości/bitrate."),
        ("Jaki bitrate dla Flirt4Free?", "3500–6000 Kbps w 1080p — ustaw te same wartości w External Broadcast Form i w SplitCam."),
        ("Czy SplitCam jest darmowy dla Flirt4Free?", "Tak — darmowy, bez znaku wodnego i bez limitu czasu, pasuje do platformy z historią jak Flirt4Free, gdzie show bywają długie.")]),
    _p("mfc-alerts", "MFC Alerts",
       "Dodaj MFC Alerts do transmisji z SplitCam",
       "Pokaż animowane alerty napiwków w transmisji MyFreeCams — URL mfcalerts.com jako warstwa Browser w darmowym SplitCam, nad kamerą.",
       "mfc alerts, myfreecams alerts, dodaj mfc alerts, mfcalerts splitcam, myfreecams tip alerts, myfreecams alerts overlay",
       'Jak dodać <span class="accent">MFC Alerts</span> do transmisji',
       "Dodaj MFC Alerts",
       "Pokaż animowane alerty napiwków w transmisji MyFreeCams.",
       "MFC Alerts pokazuje animowane efekty w twojej transmisji MyFreeCams za każdym razem, gdy widz wyśle napiwek. Działa jako <strong style='color:var(--text)'>warstwa Browser</strong> wewnątrz darmowego <strong style='color:var(--text)'>SplitCam</strong> — skonfiguruj raz, a napiwki wyzwalają reakcje na ekranie w czasie rzeczywistym.",
       "Dodanie MFC Alerts z SplitCam: zainstaluj SplitCam, dodaj kamerę, otwórz zakładkę Browser i wczytaj mfcalerts.com, skopiuj swój URL alertu, dodaj jako warstwę Browser nad kamerą, potem przetestuj napiwkiem testowym."
       "<ol><li>Zainstaluj SplitCam.</li><li>Dodaj kamerę.</li><li>Pobierz URL na mfcalerts.com.</li><li>Dodaj jako warstwę Browser nad kamerą.</li><li>Wyślij napiwek testowy.</li></ol>",
       "W SplitCam otwórz zakładkę <strong>Browser</strong> i wejdź na <strong>www.mfcalerts.com</strong>. Zaloguj się lub zarejestruj. Użyj <strong>Copy to clipboard</strong>, by skopiować swój prywatny URL alertu. Wklej URL do okna Browser SplitCam i kliknij <strong>Add</strong>. Potem ułóż listę źródeł tak, by <strong>MFC Alerts było nad kamerą</strong> (menu 3 kropek → Move Up).",
       [("MFC Alerts musi być nad kamerą", "Najczęstszy błąd: jeśli warstwa MFC Alerts jest pod kamerą na liście źródeł, efekt pozostaje ukryty. Przesuń ją na górę."),
        ("Potrzebne konto mfcalerts.com", "URL alertu jest prywatny — najpierw zarejestruj się na mfcalerts.com, jeśli nie masz konta."),
        ("Wyślij napiwek testowy przed live", "Użyj Settings → Send test tip, by upewnić się, że nakładka działa — nie odkrywaj błędu w środku show."),
        _T_ETH],
       [("Czym jest MFC Alerts?", "System powiadomień dla MyFreeCams, który pokazuje efekty wideo w twojej transmisji, gdy widzowie wysyłają napiwki — dodawany jako nakładka Browser w SplitCam."),
        ("Dlaczego moje MFC Alerts się nie pokazują?", "Niemal zawsze to kolejność warstw — warstwa Browser MFC Alerts musi być nad kamerą na liście źródeł SplitCam."),
        ("Czy potrzebuję konta do MFC Alerts?", "Tak — zarejestruj się na mfcalerts.com, by otrzymać swój prywatny URL alertu."),
        ("Czy SplitCam jest darmowy do tego?", "Tak — SplitCam jest darmowy, bez znaku wodnego i bez limitu czasu, a nakładka przeglądarkowa MFC Alerts działa w nim bez dodatkowych kosztów.")],
       steps=[
           ("Zainstaluj SplitCam i dodaj kamerę", "Zainstaluj darmowy SplitCam dla Windows lub macOS, potem dodaj <strong>kamerę</strong> jako źródło. MFC Alerts leży jako warstwa nad tą kamerą."),
           ("Otwórz zakładkę Browser i wejdź na mfcalerts.com", "W SplitCam otwórz zakładkę <strong>Browser</strong> i wejdź na <strong>www.mfcalerts.com</strong>. Zaloguj się lub zarejestruj, jeśli nie masz jeszcze konta mfcalerts.com."),
           ("Skopiuj swój URL alertu", "Na mfcalerts.com użyj <strong>Copy to clipboard</strong>, by skopiować swój prywatny URL alertu — to strona, która renderuje animacje napiwków."),
           ("Dodaj URL jako warstwę Browser — nad kamerą", "Wklej URL do okna Browser SplitCam i kliknij <strong>Add</strong>. Potem ułóż listę źródeł tak, by <strong>MFC Alerts było nad kamerą</strong> (menu 3 kropek → Move Up). Jeśli jest pod, efekt pozostaje ukryty."),
           ("Przetestuj napiwkiem testowym", "Otwórz <strong>Settings → Send test tip</strong> i upewnij się, że efekt alertu pojawia się nad kamerą. Potem nadawaj normalnie na MyFreeCams — prawdziwe napiwki teraz wyzwalają animacje."),
       ]),
    _p("lovense", "Lovense",
       "Dodaj zabawki Lovense do transmisji z SplitCam",
       "Połącz interaktywne zabawki Lovense z transmisją cam za pomocą darmowego SplitCam — Lovense SplitCam Toolset, alerty napiwków na ekranie, reakcje.",
       "dodaj lovense do transmisji, lovense cam stream, lovense splitcam, lovense splitcam toolset, lovense interactive toy streaming",
       'Jak dodać <span class="accent">zabawki Lovense</span> do transmisji',
       "Dodaj zabawki Lovense",
       "Połącz interaktywne zabawki Lovense z transmisją cam.",
       "Prowadzisz transmisję cam przez darmowy <strong style='color:var(--text)'>SplitCam</strong> i parujesz zabawkę <strong style='color:var(--text)'>Lovense</strong>, która reaguje na tokeny. Lovense dokumentuje oficjalny <strong style='color:var(--text)'>Lovense SplitCam Toolset</strong>, a SplitCam ma oficjalny plugin Lovense — integracja jest wspierana z obu stron.",
       "By dodać zabawki Lovense do transmisji: zainstaluj SplitCam i oprogramowanie Lovense, sparuj zabawkę, połącz Lovense z platformą cam, dodaj status Lovense jako warstwę Browser w SplitCam, potem nadawaj normalnie."
       "<ol><li>Zainstaluj SplitCam.</li><li>Zainstaluj oprogramowanie Lovense i sparuj zabawkę.</li><li>Połącz Lovense ze swoim serwisem cam.</li><li>Dodaj nakładkę Lovense w SplitCam.</li><li>Naciśnij Go Live.</li></ol>",
       "Zainstaluj Lovense Connect / Lovense Stream (oficjalna aplikacja desktopowa). Włącz zabawkę i sparuj przez Bluetooth, by aplikacja pokazała połączenie. W aplikacji Lovense połącz swoje konto cam, by zabawka reagowała na tokeny / napiwki widzów. Lovense udostępnia URL nakładki / widżetu — dodaj jako warstwę <strong>Browser</strong> w scenie SplitCam.",
       [("Użyj oficjalnego Lovense SplitCam Toolset", "Lovense publikuje dedykowany toolset dla SplitCam z własnym poradnikiem instalacji — dodaje nakładki aktywności zabawki i alerty napiwków stworzone dla SplitCam."),
        ("Zaktualizuj Lovense Cam Extension", "Toolset wymaga najnowszego Lovense Cam Extension (30.1.4 lub nowszy) — zaktualizuj przed live."),
        ("Trzymaj zabawkę naładowaną", "Niski poziom baterii w środku show psuje stronę interaktywną — naładuj w pełni przed live."),
        ("Przetestuj reakcję na tokeny", "Wyślij mały napiwek testowy, by upewnić się, że zabawka reaguje, przed otwarciem pokoju."),
        ("Sprawdź wymagania wersji", "Lovense SplitCam Toolset wymaga SplitCam 10.4.5 lub nowszego. Lovense Cam Extension oficjalnie obejmuje Chaturbate, Stripchat, BongaCams, MyFreeCams i CamSoda — dla innych serwisów użyj integracji Generic URL Lovense.")],
       [("Czy Lovense oficjalnie wspiera SplitCam?", "Tak — Lovense dokumentuje oficjalny «Lovense SplitCam Toolset» z własnym poradnikiem instalacji, a SplitCam ma oficjalny plugin Lovense. Integracja jest wspierana z obu stron."),
        ("Czy zabawka łączy się bezpośrednio ze SplitCam?", "Nie — zabawka paruje się z aplikacją Lovense; SplitCam pokazuje nakładkę Lovense i nadaje kamerę."),
        ("Które serwisy cam wspierają Lovense?", "Lovense Cam Extension oficjalnie wspiera Chaturbate, Stripchat, BongaCams, MyFreeCams i CamSoda, z różnym wsparciem dla innych — sprawdź aktualną listę w aplikacji Lovense."),
        ("Czy mogę pokazać ostatnie napiwki na ekranie?", "Tak — dodaj URL widżetu Lovense jako warstwę Browser w SplitCam.")],
       steps=[
           ("Zainstaluj SplitCam", "SplitCam to darmowe oprogramowanie do transmisji na żywo dla Windows i macOS — enkoder, który wysyła twoje wideo do platformy cam. Zainstaluj; bez znaku wodnego."),
           ("Zainstaluj oprogramowanie Lovense i sparuj zabawkę", "Zainstaluj Lovense Connect / Lovense Stream (oficjalna aplikacja desktopowa). Włącz zabawkę i sparuj przez Bluetooth, by aplikacja pokazała połączenie."),
           ("Połącz Lovense z platformą cam", "W aplikacji Lovense połącz swoje konto cam, by zabawka reagowała na tokeny / napiwki widzów. Większość dużych platform cam jest wspierana."),
           ("Dodaj nakładkę Lovense w SplitCam", "Lovense udostępnia URL nakładki / widżetu. Dodaj jako warstwę <strong>Browser</strong> w scenie SplitCam, by widzowie widzieli status zabawki i ostatnie napiwki na ekranie."),
           ("Zbuduj scenę i Go Live", "Dodaj kamerę i inne nakładki, wklej klucz RTMP platformy cam w SplitCam i kliknij <strong>Go Live</strong>. Zabawka reaguje na napiwki w czasie rzeczywistym."),
       ]),
    _p("multistream-cams", "Wiele serwisów cam",
       "Nadawaj na wiele serwisów cam naraz z SplitCam",
       "Nadawaj na MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat i więcej jednocześnie z darmowym multistreamem SplitCam. Jedno kliknięcie, bez znaku wodnego.",
       "nadawaj na wiele serwisów cam, multistream cam sites, transmisja chaturbate i bongacams naraz, oprogramowanie multistream cam",
       'Jak nadawać na <span class="accent">wiele serwisów cam</span> naraz',
       "Multistream cam",
       "Nadawaj na wiele serwisów cam jednocześnie.",
       "Darmowy <strong style='color:var(--text)'>SplitCam</strong> może nadawać jedno kodowanie na <strong style='color:var(--text)'>wiele serwisów cam naraz</strong> — MyFreeCams, Chaturbate, BongaCams, CAM4, Stripchat i więcej. Bez znaku wodnego, jedno kliknięcie.",
       "By nadawać na wiele serwisów cam naraz: zainstaluj SplitCam, zbuduj scenę, pobierz URL serwera RTMP i klucz streamu każdego serwisu cam, dodaj wszystkie do ustawień multistream SplitCam, kliknij Go Live raz."
       "<ol><li>Zainstaluj SplitCam.</li><li>Dodaj kamerę + scenę.</li><li>Pobierz klucze RTMP z każdego serwisu cam.</li><li>Dodaj wszystkie klucze do multistream SplitCam.</li><li>Naciśnij Go Live raz.</li></ol>",
       "Na każdej platformie cam włącz transmisję zewnętrzną / RTMP i skopiuj <strong>URL serwera</strong> oraz <strong>klucz streamu</strong>. W SplitCam otwórz <strong>Stream Settings</strong> i dodaj każdy serwis cam jako niestandardowy cel RTMP — wklej URL serwera i klucz. Zaznacz wszystkie, na których chcesz być na żywo. Naciśnij <strong>Go Live</strong>.",
       [("Uważaj na swój upload", "Multistream zwielokrotnia obciążenie uploadu. Każdy cel używa własnego bitrate — upewnij się, że twoje łącze udźwignie sumę."),
        ("Sprawdź zasady platform", "Niektóre serwisy cam zakazują jednoczesnego nadawania gdzie indziej — sprawdź przed multistreamem."),
        ("Kabel — tu nie może paść", "Multistream zwielokrotnia obciążenie uploadu, więc jeden spadek wi-fi może zrzucić wszystkie cele naraz. Kabel tu nie jest opcją."),
        ("Monitoruj wskaźnik kondycji", "SplitCam pokazuje status każdego celu — odłącz jeden serwis, jeśli upload nie daje rady.")],
       [("Czy multistream SplitCam jest darmowy?", "Tak — multistream jest wbudowany i darmowy, bez opłat za cel, bez znaku wodnego."),
        ("Na ile serwisów cam mogę nadawać naraz?", "Na tyle, ile udźwignie pasmo twojego uploadu — każdy cel używa własnego bitrate."),
        ("Czy używa chmurowego relay?", "Nie — SplitCam wysyła stream peer-to-peer bezpośrednio z PC do ingest każdej platformy."),
        ("Czy multistream spowalnia mój PC?", "Kodowanie odbywa się raz i jest ponownie używane; kodowanie sprzętowe utrzymuje niskie obciążenie CPU. Pasmo uploadu to prawdziwy limit.")],
       steps=[
           ("Zainstaluj SplitCam", "SplitCam to darmowe oprogramowanie do transmisji na żywo dla Windows i macOS z wbudowanym multistreamem. Zainstaluj — bez znaku wodnego, bez rejestracji."),
           ("Skonfiguruj kamerę i scenę", "Otwórz SplitCam, dodaj kamerę i zbuduj scenę z nakładkami i filtrami. Jedna scena zasila każdy cel."),
           ("Pobierz klucze RTMP z każdego serwisu cam", "Na każdej platformie cam włącz transmisję zewnętrzną / RTMP i skopiuj <strong>URL serwera</strong> oraz <strong>klucz streamu</strong>. Powtórz dla każdego serwisu, na który chcesz nadawać — zobacz poradniki poszczególnych platform po dokładną ścieżkę."),
           ("Dodaj każdy cel w SplitCam", "Otwórz <strong>Stream Settings</strong> i dodaj każdy serwis cam jako niestandardowy cel RTMP — wklej URL serwera i klucz. Zaznacz wszystkie, na których chcesz być na żywo."),
           ("Kliknij Go Live raz", "Naciśnij <strong>Go Live</strong>. SplitCam wysyła stream na każdy wybrany serwis cam jednocześnie, peer-to-peer, z jednego kodowania — bez dodatkowych kosztów."),
       ]),
    _p("livejasmin", "LiveJasmin",
       "Transmisja na LiveJasmin z SplitCam — Enkoder zewnętrzny HD",
       "Transmisja na LiveJasmin z darmowym SplitCam — enkoder zewnętrzny w Model Center, konfiguracja HD 1080p, sceny wielokamerowe i nakładki. Bez znaku wodnego, bez rejestracji.",
       "transmisja livejasmin, livejasmin obs, livejasmin enkoder zewnętrzny, livejasmin rtmp, livejasmin klucz streamu, livejasmin konfiguracja modelki",
       'Jak nadawać na <span class="accent">LiveJasmin</span> z SplitCam',
       "Transmisja LiveJasmin",
       "Konfiguracja enkodera zewnętrznego dla Model Center LiveJasmin w trybie tylko HD.",
       "LiveJasmin to flagowa platforma Docler Holding — jedna z największych sieci cam na świecie i platforma działająca wyłącznie w HD. Jej preferowany nadajnik to autorski klient <strong>JasminCAM</strong>, ale Model Center udostępnia też standardową ścieżkę <strong>External Encoder</strong>, do której podłącza się darmowy <strong style='color:var(--text)'>SplitCam</strong> — co pozwala nadawać sceny wielokamerowe, filtry beauty i nakładki w tej samej transmisji HD.",
       "Transmisja na LiveJasmin z SplitCam: zainstaluj SplitCam, zbuduj scenę HD, w Model Center wejdź w <em>Settings → Broadcast → External Encoder</em>, skopiuj URL serwera i klucz streamu, wklej w SplitCam, Go Live."
       "<ol><li>Zainstaluj SplitCam.</li><li>Dodaj kamerę + scenę HD.</li><li>Pobierz URL i klucz streamu z Model Center.</li><li>Wklej w SplitCam.</li><li>Naciśnij Go Live.</li></ol>",
       "Zaloguj się na <strong>modelcenter.livejasmin.com</strong>, otwórz <strong>Settings → Broadcast → External Encoder</strong>. Model Center pokaże <strong>URL serwera</strong> i <strong>klucz streamu</strong> przypisane do twojego konta — skopiuj oba do niestandardowych pól RTMP w SplitCam. <strong>Uwaga:</strong> nowe konta muszą najpierw zostać zatwierdzone (48–72 godziny), zanim pojawi się opcja enkodera zewnętrznego, a platforma wymusza tryb wyłącznie HD.",
       [("HD albo lecisz w dół", "LiveJasmin to wyłącznie HD — wszystko poniżej 1280×720 grozi pokazywaniem cię tylko na gorzej płacących listach, a poniżej 1080p tracisz status «Premium». Celuj w 1920×1080 przy 30 fps i 4000–6000 Kbps."),
        ("JasminCAM vs enkoder zewnętrzny", "Autorski klient Doclera JasminCAM daje najczystszą zgodność z HD, ale enkodery zewnętrzne (OBS, SplitCam, vMix) są oficjalnie wspierane po zatwierdzeniu konta — odblokowują sceny wielokamerowe i nakładki, których JasminCAM nie potrafi."),
        ("Free chat ≠ pokaz prywatny", "Free chat jest tylko zajawką — bez nagości. Zarabiasz w pokazach Private i Gold show. Zaplanuj scenę tak, by wyglądała mocno w ubraniu I w trybie pokazu."),
        _T_ETH],
       [("Czy LiveJasmin oficjalnie wspiera enkodery zewnętrzne jak SplitCam?", "Tak — Model Center ma opcję External Encoder w Settings → Broadcast. JasminCAM to klient rekomendowany, ale OBS, SplitCam i inne enkodery RTMP są wprost wymienione jako wspierane po zatwierdzeniu konta modelki."),
        ("Gdzie znajdę mój klucz streamu LiveJasmin?", "W Model Center: Settings → Broadcast → External Encoder. Tam pojawia się zarówno URL serwera, jak i unikalny klucz streamu — skopiuj oba do niestandardowych pól RTMP w SplitCam. Klucz jest przypisany do twojego konta; traktuj jak hasło."),
        ("Jaki bitrate ustawić dla LiveJasmin?", "LiveJasmin to wyłącznie HD — celuj w 1920×1080 przy 30 fps, 4000–6000 Kbps i interwale klatki kluczowej 2 sekundy. Wszystko zauważalnie poniżej traci etykietę Premium i leci w dół rankingów."),
        ("Czy SplitCam jest darmowy do LiveJasmin?", "Tak — SplitCam jest darmowy, bez znaku wodnego i bez limitu czasu. Jedyny «koszt» to spełnienie wymagań HD LiveJasmin, które SplitCam ogarnia natywnie kompozycją sceny w 1080p i filtrami beauty.")],
       steps=[
           ("Pobierz i zainstaluj SplitCam", "SplitCam to darmowe oprogramowanie do transmisji na żywo dla Windows i macOS — bez rejestracji, bez karty, bez znaku wodnego. To enkoder, który wysyła twoje wideo HD do LiveJasmin."),
           ("Zbuduj scenę HD", "Otwórz SplitCam i dodaj kamerę w trybie 1080p. Dołóż nakładki, tekst, drugą kamerę albo telefon, filtry beauty albo tło AI — LiveJasmin wymaga jakości HD, a twoja gotowa scena musi wyglądać premium zarówno w free chat, JAK i w pokazach prywatnych."),
           ("Pobierz URL i klucz streamu LiveJasmin", "Zaloguj się na <strong>modelcenter.livejasmin.com</strong> (twoje konto musi być najpierw zatwierdzone — zwykle 48–72 godziny po rejestracji). Otwórz <strong>Settings → Broadcast → External Encoder</strong>. Strona pokaże <strong>URL serwera</strong> i unikalny <strong>klucz streamu</strong>. Skopiuj oba."),
           ("Podłącz SplitCam do LiveJasmin", "W SplitCam otwórz <strong>Stream Settings</strong>, wklej URL serwera i klucz streamu LiveJasmin w niestandardowych polach RTMP. Ustaw bitrate 4000–6000 Kbps przy 1920×1080, 30 fps, klatka kluczowa co 2 sekundy. Najpierw uruchom wbudowany test prędkości — streamy HD są wymagające."),
           ("Kliknij Go Live", "Naciśnij <strong>Go Live</strong> w SplitCam, potem przejdź online w Model Center LiveJasmin. W około 10 sekund twój sygnał HD dociera do sieci LiveJasmin. Kolejne transmisje to jeden klik — otwórz SplitCam, Go Live, potem przejdź online na LiveJasmin."),
       ]),
]
