# -*- coding: utf-8 -*-
"""Simplified Chinese (zh) content for cam-streaming-guides."""

_T_ETH = ("使用有线连接", "长时间直播时以太网比 Wi-Fi 更稳定 — 丢失的帧就是丢失的小费。把网线拉到直播电脑。")
_T_TEST = ("先做个私密测试", "正式开播前运行一个简短的测试直播，检查摄像头、音频、构图和叠加层。")

def _p(slug, name, title, desc, kw, h1html, h1short, card, intro, quick, key_how, tips, faq, steps=None):
    d = {"slug": slug, "name": name, "title": title, "desc": desc, "kw": kw,
         "h1html": h1html, "h1short": h1short, "card": card, "intro": intro,
         "quick": quick, "key_how": key_how, "tips": tips, "faq": faq}
    if steps: d["steps"] = steps
    return d

PLATFORMS_ZH = [
    _p("chaturbate", "Chaturbate",
       "在 Chaturbate 直播 — SplitCam Token & RTMP 设置",
       "使用免费 SplitCam 在 Chaturbate 直播 — 广播令牌、RTMP、多机位场景和叠加层。无水印。",
       "chaturbate 直播, chaturbate broadcast token, chaturbate rtmp obs, chaturbate 外部编码器, chaturbate live",
       '如何使用 SplitCam 在 <span class="accent">Chaturbate</span> 直播',
       "Chaturbate 直播",
       "Chaturbate 上基于令牌的外部编码器设置。",
       "Chaturbate 是建立在代币经济上的最大 cam 平台之一。浏览器广播器是平面单机位工具 — 通过免费 <strong style='color:var(--text)'>SplitCam</strong> 切换到<strong style='color:var(--text)'>外部编码器</strong>，可以在同一个基于令牌的直播流中获得多机位场景、叠加层和滤镜。",
       "使用 SplitCam 在 Chaturbate 直播：安装 SplitCam，构建场景，在 Chaturbate 打开 <em>Broadcast Yourself → My Broadcast</em>，复制广播令牌，粘贴到 SplitCam，点击 Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>从 Chaturbate 复制广播令牌。</li><li>粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "在 Chaturbate 点击 <strong>Broadcast Yourself</strong> 进入 <strong>My Broadcast</strong> 页面，然后点击 <strong>View RTMP/OBS broadcast information and stream key</strong>。密钥显示为<strong>广播令牌</strong> — 复制它。像对待密码一样对待它；切勿公开。",
       [("令牌就是密钥", "Chaturbate 使用您的广播令牌而不是通用直播密钥。像密码一样对待并在泄露时重置。"),
        ("空间很大", "Chaturbate 的 RTMP 摄取接受高达 4K、60 fps 和高比特率 — 限制是您的上传，不是平台。每 2 秒一个关键帧。"),
        _T_ETH, _T_TEST],
       [("Chaturbate 允许 OBS / 外部编码器吗？", "是 — Chaturbate 官方支持外部编码器，有自己的「How do I set up OBS?」文章。在广播设置中通过「Use External Encoder to Broadcast」激活。"),
        ("我的 Chaturbate 直播密钥在哪里？", "Broadcast Yourself → My Broadcast → View RTMP/OBS broadcast information and stream key。密钥是您的广播令牌。"),
        ("Chaturbate 用什么比特率？", "1080p 用 3,500–6,000 Kbps 完全够用。Chaturbate 上限很高 — 真正的限制是您的上传；先运行 SplitCam 内置速度测试。"),
        ("SplitCam 对 Chaturbate 免费吗？", "是 — 完全免费、无水印、无时间限制：编码器不会吃掉您的代币收入。")]),
    _p("cam4", "CAM4",
       "在 CAM4 直播 — SplitCam External Encoder",
       "使用免费 SplitCam 在 CAM4 直播 — External Encoder、直播密钥、地理封锁和叠加层。无水印。",
       "cam4 直播, cam4.com, cam4 external encoder, cam4 stream key, cam4 rtmp obs",
       '如何使用 SplitCam 在 <span class="accent">CAM4</span> 直播',
       "CAM4 直播",
       "CAM4 上带地理控制的 External Encoder。",
       "CAM4 是带内置地理控制的全球 cam-and-earn 平台 — 您可以在选定国家/地区隐藏直播。通过免费 <strong style='color:var(--text)'>SplitCam</strong> 作为外部编码器直播可以打开基础广播器不具备的场景切换和叠加层。",
       "使用 SplitCam 在 CAM4 直播：安装 SplitCam，构建场景，在 CAM4 转到 <em>Broadcast &amp; Earn Money → Start Broadcast → External Encoder</em>，Get Stream Key，粘贴到 SplitCam，Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>从 CAM4 获取直播密钥。</li><li>粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "在 CAM4 点击 <strong>Broadcast</strong> → <strong>Broadcast &amp; Earn Money</strong> → <strong>Start Broadcast</strong>，然后点击顶部 <strong>External Encoder</strong>。填写出生日期、性别和国家，使用 <strong>Get Stream Key</strong> 并复制。SplitCam Stream Settings 中的绿色滑块确认连接。",
       [("设置地理限制", "CAM4 允许在特定国家和地区隐藏直播 — 直播前在 CAM4 端配置。"),
        ("注意绿色滑块", "CAM4 设置在密钥被接受时在 SplitCam Stream Settings 中显示绿色滑块 — 红色 = 检查密钥。"),
        ("比特率比平时低", "CAM4 摄取将视频比特率限制在约 3,000 Kbps — 比大多数 cam 网站低。不要强推更高。"),
        _T_ETH],
       [("CAM4 官方支持 OBS / 外部编码器吗？", "是 — CAM4 在支持网站上有官方 OBS Guide，并推荐 External Encoder 以获得最佳体验。SplitCam 使用相同的 RTMP 路径。"),
        ("我可以地理封锁我的 CAM4 直播吗？", "是 — CAM4 有内置地理限制以在某些国家/地区隐藏直播。在 CAM4 设置，不是 SplitCam。"),
        ("CAM4 直播密钥在哪里？", "Broadcast → Broadcast & Earn Money → Start Broadcast → External Encoder → Get Stream Key。"),
        ("CAM4 用什么比特率？", "低于平均水平 — CAM4 摄取限制在 30 fps、1 秒关键帧下约 3,000 Kbps。官方表格建议不要超过约 3,000。")]),
    _p("bongacams", "BongaCams",
       "在 BongaCams 直播 — SplitCam External Encoder",
       "使用免费 SplitCam 在 BongaCams 直播 — External Encoder、多机位场景、叠加层和 AI 背景。无水印。",
       "bongacams, bongcams, bongacams 直播, bongacams external encoder, bongacams rtmp obs",
       '如何使用 SplitCam 在 <span class="accent">BongaCams</span> 直播',
       "BongaCams 直播",
       "BongaCams 的 External Encoder 设置。",
       "BongaCams 是一个全球 cam 平台。外部编码器直播并非总是激活 — 一旦激活，免费 <strong style='color:var(--text)'>SplitCam</strong> 使用多机位场景、叠加层和 AI 背景驱动直播。",
       "使用 SplitCam 在 BongaCams 直播：安装 SplitCam，构建场景，在 BongaCams 转到 <em>Options → Broadcast settings → Select Encoder → External Encoder</em>，复制 URL 和密钥，粘贴到 SplitCam，Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>从 BongaCams 获取 URL 和密钥。</li><li>粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "在 BongaCams 打开 <strong>Options</strong> → <strong>Broadcast settings</strong> → <strong>Select Encoder</strong> → <strong>External Encoder</strong>，复制显示的服务器 URL 和直播密钥。<strong>如果 External Encoder 按钮缺失</strong>，联系 BongaCams 支持并请求在您的账户上启用外部编码。",
       [("没有 External Encoder 按钮？支持", "BongaCams 按账户启用外部编码 — 如果该选项在 Broadcast settings 中缺失，支持人员会激活。"),
        ("匹配分辨率", "BongaCams 建议网络摄像头分辨率和直播分辨率匹配 — 例如都是 1280×720。"),
        _T_ETH, _T_TEST],
       [("为什么 External Encoder 按钮在 BongaCams 不显示？", "外部编码在每个账户上不是默认激活 — 联系 BongaCams 支持激活它，按钮会出现在 Broadcast settings 中。"),
        ("我需要验证我的 BongaCams 账户吗？", "是 — 直播需要 18+、年龄验证的官方 ID 和上线前的账户批准。"),
        ("BongaCams 用什么比特率？", "BongaCams RTMP 摄取将视频比特率限制在约 6,000 Kbps，2 秒关键帧 — 1080p 下 3,500–6,000 是理想区间；先测试上传。"),
        ("SplitCam 对 BongaCams 免费吗？", "是 — 完全免费、无水印、无时间限制，所以编码器不会减少您在 BongaCams 的代币收入。")]),
    _p("stripchat", "Stripchat",
       "在 Stripchat 直播 — SplitCam Strip Cam 设置",
       "在 strip cam 平台 Stripchat 上使用免费 SplitCam 直播。外部软件、令牌密钥、场景和叠加层。",
       "strip cam, stripchat live stream, stripchat 直播, stripchat external software, stripchat stream key, stripchat rtmp obs",
       '如何使用 SplitCam 在 <span class="accent">Stripchat</span> 直播',
       "Stripchat 直播",
       "Stripchat 直播的外部软件设置。",
       "Stripchat 是一个专注于互动性的大型 cam 平台。<em>external software</em> 模式为您提供基于令牌的密钥 — 将其放入免费 <strong style='color:var(--text)'>SplitCam</strong>，以使用场景、叠加层和滤镜直播，而不是平面摄像头。",
       "使用 SplitCam 在 Stripchat 直播：安装 SplitCam，构建场景，在 Stripchat 选择 <em>Switch to external software</em>，复制直播密钥，粘贴到 SplitCam，Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>从 Stripchat 获取直播密钥。</li><li>粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "在 Stripchat 选择 <strong>Switch to external software</strong>，然后 <strong>Show external software settings for the stream</strong>。复制直播密钥 — Stripchat 将其显示为令牌。保持私密。",
       [("与网站匹配分辨率", "Stripchat 的 FAQ 警告：您软件中的分辨率必须与网站完全匹配，否则视频会像素化。两者设置相同。"),
        ("注意 2 Mbps 最低限", "Stripchat 将 2 Mbps 上传列为最低 — 并直接表示这对 OBS 直播或多平台直播不够。瞄准更高。"),
        ("密钥是令牌", "Stripchat 的直播密钥是令牌 — 准确复制，永远不要分享，泄露时重置。"),
        _T_ETH],
       [("Stripchat 推荐 OBS / 外部软件吗？", "是 — Stripchat 的官方 FAQ 推荐外部广播软件如 OBS「以达到最佳视频和音频质量」。SplitCam 工作相同。"),
        ("如何将 Stripchat 切换到外部软件？", "在 Broadcast Center 选择 Switch to External Broadcast Software (OBS)，然后打开 external software settings 以显示直播密钥（令牌）。"),
        ("Stripchat 用什么比特率？", "RTMP 摄取接受高达约 6,000 Kbps，2 秒关键帧。1080p 下 3,500–6,000 理想 — 但必须远高于 2 Mbps 最低限，特别是 OBS 直播。"),
        ("SplitCam 对 Stripchat 免费吗？", "是 — 无许可费、无水印、无时间限制：即使是长时间的 Stripchat 互动节目，编码器端也没有任何费用。")]),
    _p("onlyfans", "OnlyFans",
       "在 OnlyFans 直播 — SplitCam 授权或密钥",
       "使用免费 SplitCam 在 OnlyFans 直播 — 通过授权或 OBS Key 登录、多机位场景、叠加层。无水印。",
       "onlyfans 直播, onlyfans live stream, onlyfans 授权 splitcam, onlyfans obs key, onlyfans streaming software",
       '如何使用 SplitCam 在 <span class="accent">OnlyFans</span> 直播',
       "OnlyFans 直播",
       "授权一次或粘贴密钥 — 在 OnlyFans 直播。",
       "OnlyFans 直播面向您的订阅者。SplitCam 通过<strong style='color:var(--text)'>两种方式</strong>连接 — 使用 OnlyFans 账户登录一次，SplitCam 自动获取直播密钥并保持同步，或手动粘贴 OBS Key。两种情况下您都可以使用多机位场景、叠加层和滤镜直播。",
       "使用 SplitCam 在 OnlyFans 直播：安装 SplitCam，构建场景，打开 Stream Settings &rarr; Add Channel &rarr; OnlyFans 并选择<em>授权</em> — 使用 OnlyFans 账户登录，SplitCam 自动获取密钥 — 然后按 Go Live。账户连接后，您可以在 SplitCam 中更改 OnlyFans 直播参数，无需打开 OnlyFans 网站。",
       "在 OnlyFans 上：<strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; <strong>Other</strong> 部分，复制 <strong>OBS Key</strong>。或者使用 SplitCam 中的 <strong>授权</strong>选项进行账户登录 — 这样密钥会自动获取并保持同步。",
       [("授权 vs Stream Key", "两种连接方式：<strong>授权</strong>（登录一次，密钥被获取并同步 — 最简单的路径）或 <strong>Stream Key</strong>（在 OnlyFans → Profile → Settings → Other 复制 OBS Key 并粘贴）。"),
        ("无需离开 SplitCam 即可更改设置", "使用授权时账户保持连接，因此在直播期间或之后从 SplitCam 调整 OnlyFans 直播参数 — 无需通过 OnlyFans 网站。"),
        ("适度的比特率", "OnlyFans 的 RTMP 摄取将视频比特率限制在约 2,500 Kbps — 比大多数 cam 网站更严格。瞄准 720p–1080p，约 2,000–2,500。"),
        _T_ETH],
       [("如何将 OnlyFans 连接到 SplitCam？", "两种方式。<strong>授权</strong> — Stream Settings → Add Channel → OnlyFans → 使用 OnlyFans 账户登录，SplitCam 自动获取密钥。或 <strong>Stream Key</strong> — 在 OnlyFans → Profile → Settings → Other 复制 OBS Key 并粘贴。"),
        ("我可以在不打开网站的情况下更改 OnlyFans 直播设置吗？", "是 — 使用授权方法 SplitCam 保持连接到您的 OnlyFans 账户，因此密钥和设置自动同步。"),
        ("OnlyFans 用什么比特率？", "适度 — OnlyFans 的 RTMP 摄取将比特率限制在约 2,500 Kbps，比其他 cam 平台严格得多。瞄准 720p–1080p，约 2,000–2,500 Kbps。"),
        ("SplitCam 对 OnlyFans 直播免费吗？", "是 — 免费、无水印、无时间限制。编码器端无成本。")],
       steps=[
           ("下载并安装 SplitCam", "SplitCam 是适用于 Windows 和 macOS 的免费直播软件 — 无注册、无信用卡、无水印。它是将您的视频发送到 OnlyFans 的编码器。"),
           ("设置摄像头和场景", "打开 SplitCam 并添加网络摄像头。按照您希望观众看到的方式构建场景 — 叠加层、文本、第二个摄像头、美颜滤镜或 AI 背景，全部实时应用。"),
           ("连接 — 方法 1：授权（推荐）", "在 SplitCam 中打开 <strong>Stream Settings</strong> &rarr; <strong>Add Channel</strong> &rarr; <strong>OnlyFans</strong> 并选择<strong>授权</strong>。使用 OnlyFans 电子邮件和密码登录。SplitCam 链接您的账户，自动获取直播密钥并保持同步 — 让您在 SplitCam 中管理 OnlyFans 直播参数，在直播期间或之后更改它们，无需打开 OnlyFans 网站。"),
           ("连接 — 方法 2：Stream Key（手动）", "不想登录？使用密钥。在 OnlyFans 转到 <strong>Profile</strong> &rarr; <strong>Settings</strong> &rarr; <strong>Other</strong> 部分并复制 <strong>OBS Key</strong>。在 SplitCam，Add Channel &rarr; OnlyFans，粘贴到密钥字段。此密钥是静态的 — 要稍后更改设置，返回 OnlyFans 网站。"),
           ("Go Live", "无论哪种方法，在 SplitCam 中按 <strong>Go Live</strong>。使用方法 1，您可以继续从 SplitCam 实时调整 OnlyFans 参数；使用方法 2，密钥保持您设置的状态。"),
       ]),
    _p("camplace", "CamPlace",
       "在 CamPlace 直播 — SplitCam 免费指南",
       "使用免费 SplitCam 在 CamPlace 直播 — 外部编码器、RTMP 密钥、场景和叠加层。分步骤、无水印。",
       "camplace 直播, camplace broadcasting software, camplace rtmp, camplace external encoder, camplace stream key",
       '如何使用 SplitCam 在 <span class="accent">CamPlace</span> 直播',
       "CamPlace 直播",
       "CamPlace 直播的外部编码器设置。",
       "CamPlace 是一个 cam-streaming 平台。没有公开的 OBS 文章，所以<strong style='color:var(--text)'>上面的视频指南</strong>是您的参考 — 免费 <strong style='color:var(--text)'>SplitCam</strong> 通过标准 RTMP 连接，并添加基础摄像头不具备的场景、叠加层和 AI 背景。",
       "使用 SplitCam 在 CamPlace 直播：安装 SplitCam，构建场景，在 CamPlace 激活外部/RTMP 直播，复制服务器 URL 和直播密钥，粘贴到 SplitCam，Go Live。跟随视频获取当前路径。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>从 CamPlace 获取 RTMP 密钥。</li><li>粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "登录 CamPlace 并打开直播设置。切换到外部编码器 / RTMP / OBS 选项以显示<strong>服务器 URL</strong> 和<strong>直播密钥</strong>，复制两者。CamPlace 不发布官方 OBS 文档 — <strong>上面的视频</strong>是通过当前界面最可靠的分步路径。",
       [("没有官方 OBS 指南 — 使用视频", "CamPlace 没有关于外部编码器的公开文章；上面的视频是当前路径的参考。"),
        ("标准 RTMP 工作", "虽然没有文档，CamPlace 接受标准 RTMP 服务器 URL 和密钥 — SplitCam 作为自定义 RTMP 目标连接。"),
        _T_ETH, _T_TEST],
       [("CamPlace 有官方 OBS 指南吗？", "未找到关于外部编码器的公开文章。CamPlace 接受标准 RTMP URL 和密钥，因此 SplitCam 工作 — 跟随视频。"),
        ("CamPlace 支持外部编码器吗？", "是 — 它接受标准 RTMP 直播密钥，因此 SplitCam 作为自定义 RTMP 目标连接。"),
        ("CamPlace 用什么比特率？", "CamPlace 不发布官方数字 — 使用 1080p 下 3,500–6,000 Kbps 作为安全范围，让 SplitCam 速度测试固定您的真实上限。"),
        ("SplitCam 对 CamPlace 免费吗？", "是 — 免费、无水印、无时间限制。由于 CamPlace 没有自己的编码器，免费的 RTMP 工具完成工作。")]),
    _p("camsoda", "CamSoda",
       "CamSoda 直播 — SplitCam 免费设置",
       "使用免费 SplitCam 进行 CamSoda 直播 — Use OBS Broadcaster、区域服务器、场景和叠加层。无水印。",
       "camsoda live, camsoda 直播, camsoda obs broadcaster, camsoda rtmp obs, camsoda live broadcast",
       '如何使用 SplitCam 在 <span class="accent">CamSoda</span> 直播',
       "CamSoda 直播",
       "CamSoda 上的 Use OBS Broadcaster 设置。",
       "CamSoda 是一个以互动和不寻常的节目格式而闻名的美国 cam 平台。它官方支持 OBS 直播 — Go Live 页面上有 <strong style='color:var(--text)'>Use OBS Broadcaster</strong> 按钮，CamSoda wiki 上有官方 OBS 指南。免费 <strong style='color:var(--text)'>SplitCam</strong> 工作相同。",
       "使用 SplitCam 在 CamSoda 直播：安装 SplitCam，构建场景，在 CamSoda Go Live 页面点击 Use OBS Broadcaster，复制服务器 URL 和直播密钥，粘贴到 SplitCam，Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>在 CamSoda 点击 Use OBS Broadcaster。</li><li>将服务器 URL + 密钥粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "在 CamSoda 的 <strong>Go Live</strong> 页面点击 <strong>Use OBS Broadcaster</strong>。CamSoda 显示 RTMP 服务器 URL 和直播密钥 — 复制两者。选择离您最近的区域服务器（北美、欧洲、亚洲等）。CamSoda wiki 有完整的 OBS 指南供详细参考。",
       [("验证以接收小费", "在 CamSoda，任何人都可以直播，但要接收小费您必须完成 CamSoda 的验证过程。"),
        ("选择最近的区域服务器", "CamSoda 提供区域摄取服务器 — 最近的（NA / 欧洲 / 亚洲 / 南美 / 大洋洲）减少延迟和丢帧。"),
        ("1080p / 30 fps 的上限", "CamSoda 的摄取最高约 1080p、30 fps 和约 6,000 Kbps — 不要强推更高。"),
        _T_ETH],
       [("CamSoda 支持 OBS / 外部编码器吗？", "是 — 官方支持。Go Live 页面上有 Use OBS Broadcaster 按钮，CamSoda wiki 上有 OBS 指南，因此 SplitCam 工作。"),
        ("我需要在 CamSoda 上验证自己吗？", "直播不需要。接收小费需要 — CamSoda 首先需要完成验证过程。"),
        ("CamSoda 支持什么分辨率？", "最高 1920×1080，30 fps，RTMP 摄取最大约 6,000 Kbps。"),
        ("SplitCam 对 CamSoda 免费吗？", "是 — 免费、无水印、无时间限制。与 CamSoda 的免费 Use OBS Broadcaster 模式一起工作，因此整个链条不花费任何费用。")]),
    _p("streamate", "Streamate",
       "在 Streamate 直播 — SplitCam 集成通道",
       "使用免费 SplitCam 在 Streamate 直播 — 集成通道、SM Connect 密钥、场景和叠加层。无水印。",
       "streamate, streamate sm connect, streamate 直播, streamate broadcasting software, streamate rtmp",
       '如何使用 SplitCam 在 <span class="accent">Streamate</span> 直播',
       "Streamate 直播",
       "Streamate 是 SplitCam 中的集成通道 — 快速设置。",
       "Streamate 是一个成熟的 cam 平台 — 它是 SplitCam 通道列表中<strong style='color:var(--text)'>预配置目的地之一</strong>，因此设置比手动 RTMP 输入更快：您选择 Streamate，粘贴密钥，完成。",
       "使用 SplitCam 在 Streamate 直播：安装 SplitCam，构建场景，在 Streamate 使用 <em>SM Connect → Start Show</em> 并复制密钥，然后在 SplitCam 打开 <em>Stream Settings → Add Channel → Streamate</em> 并粘贴。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>通过 SM Connect 获取 Streamate 密钥。</li><li>SplitCam 中的 Add Channel → Streamate。</li><li>按 Go Live。</li></ol>",
       "在 Streamate 打开 <strong>SM Connect</strong>，接受条款，点击左侧的 <strong>Start Show</strong>，关闭打开的窗口 — 然后复制直播密钥。在 SplitCam 打开 <strong>Stream Settings</strong> → <strong>Add Channel</strong>，从列表中选择 <strong>Streamate</strong> 并粘贴密钥。绿色滑块确认连接。",
       [("Streamate 已集成", "无需手动 RTMP URL — SplitCam 的 Add Channel 列表中有 Streamate；只需选择并粘贴密钥。"),
        ("关闭 SM Connect 弹出窗口", "Start Show 后 Streamate 打开一个窗口 — 关闭它；它只是为了显示直播密钥。"),
        ("将分辨率锁定到 1080p", "SM Connect 中的 Video Resolution 字段可能会悄悄跳到 1440，实际上不会传送，并会悄悄降低您的质量 — 手动设置为 1080p。静态图像下比特率下降是正常的：Streamate 流是自适应的。"),
        _T_ETH],
       [("Streamate 在 SplitCam 中集成了吗？", "是 — Streamate 出现在 SplitCam 的 Add Channel 列表中；您选择而不是手动输入 RTMP URL。"),
        ("Streamate 直播密钥在哪里？", "SM Connect → 接受条款 → Start Show → 关闭弹出窗口 → 复制密钥。"),
        ("Streamate 用什么比特率？", "Streamate 没有硬性上限 — 1080p 下 3,500–6,000 Kbps 工作良好。流是自适应的，因此静态图像下的较低比特率是正常的，不是 bug。"),
        ("SplitCam 对 Streamate 免费吗？", "是 — 免费、无水印、无时间限制；并且由于 Streamate 是 SplitCam 中的集成通道，也没有单独的编码器成本。")]),
    _p("streamray", "StreamRay",
       "在 StreamRay cam 直播 — SplitCam Chat URL",
       "使用免费 SplitCam 在 StreamRay cam 直播 — URL 在聊天中发布、OBS Broadcaster 模式、场景和叠加层。无水印。",
       "streamray, streamray cam, streamray 直播, streamray obs broadcaster, streamray rtmp",
       '如何使用 SplitCam 在 <span class="accent">StreamRay</span> 直播',
       "StreamRay 直播",
       "StreamRay 的 URL-in-chat 外部编码器设置。",
       "StreamRay 有一个不寻常的外部编码器设置 — 它在<strong style='color:var(--text)'>直播聊天窗口</strong>中传递直播 URL，不使用单独的直播密钥。免费 <strong style='color:var(--text)'>SplitCam</strong> 处理这个仅 URL 流程。",
       "使用 SplitCam 在 StreamRay 直播：安装 SplitCam，构建场景，在 StreamRay 激活 OBS Broadcaster，从聊天窗口复制直播 URL，粘贴到 SplitCam（密钥字段留空），Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>从聊天复制 StreamRay URL。</li><li>将 URL 粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "在 StreamRay 双击 <strong>Broadcast Now</strong>，打开 <strong>Other</strong> 菜单，选择 <strong>OBS Broadcaster</strong> 和 <strong>Save and Close</strong>。StreamRay 然后在<strong>聊天窗口中发布直播 URL</strong> — 从那里复制。<strong>留空</strong> SplitCam 直播密钥字段；StreamRay 仅通过 URL 认证。",
       [("URL 在聊天中", "StreamRay 不在设置框中显示直播 URL — 它在直播聊天窗口中发布。从那里复制。"),
        ("留空密钥字段", "StreamRay 不使用单独的密钥 — 仅 URL。在 SplitCam 密钥字段中不放任何内容。"),
        _T_ETH, _T_TEST],
       [("StreamRay 直播 URL 在哪里？", "激活 OBS Broadcaster 后，StreamRay 在聊天窗口中发布 URL — 从聊天复制。"),
        ("为什么 StreamRay 上没有直播密钥？", "StreamRay 仅通过 URL 认证 — 留空 SplitCam 密钥字段。"),
        ("StreamRay 用什么比特率？", "StreamRay 没有声明官方上限 — 瞄准 1080p 下 3,500–6,000 Kbps 并运行 SplitCam 速度测试，因为仅 URL 流不提供比特率反馈。"),
        ("SplitCam 对 StreamRay 免费吗？", "是 — 免费、无水印、无时间限制，这与 StreamRay 的仅 URL 流匹配：粘贴一个链接即可上线。")]),
    _p("xlovecam", "XLoveCam",
       "在 XLoveCam 直播 — SplitCam RTMP 链接和密钥",
       "使用免费 SplitCam 在 XLoveCam 直播 — RTMP 链接和密钥、区域服务器、场景和叠加层。无水印。",
       "xlovecam, x love cam, xlovecam 直播, xlovecam rtmp link, xlovecam stream key",
       '如何使用 SplitCam 在 <span class="accent">XLoveCam</span> 直播',
       "XLoveCam 直播",
       "XLoveCam 的 RTMP 链接 + 密钥设置。",
       "XLoveCam 是一个欧洲多语言 cam 平台。账户设置显示 <strong style='color:var(--text)'>RTMP 链接</strong>和<strong style='color:var(--text)'>直播密钥</strong> — 免费 <strong style='color:var(--text)'>SplitCam</strong> 同时获取两者，并以完整场景和叠加层直播。",
       "使用 SplitCam 在 XLoveCam 直播：安装 SplitCam，构建场景，在 XLoveCam 打开 <em>My Account → settings</em>，复制 RTMP 链接和直播密钥，将两者粘贴到 SplitCam，开始节目。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>从 XLoveCam 复制 RTMP 链接 + 密钥。</li><li>将两者粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "在 XLoveCam 打开 <strong>My Account</strong> → <strong>settings</strong>。设置同时显示 <strong>RTMP 链接</strong>和 <strong>直播密钥</strong> — 将两者复制到 SplitCam 的服务器 URL 和密钥字段，然后在 XLoveCam 上 <strong>Start your show</strong>。",
       [("复制链接和密钥", "XLoveCam 给您一个 RTMP 链接和一个单独的直播密钥 — 您在 SplitCam 中需要两者，不仅仅是一个。"),
        ("多语言观众", "XLoveCam 是欧洲多语言的 — 您语言的清晰文本叠加层有助于观众找到您。"),
        ("选择最近的服务器", "XLoveCam 提供区域 RTMP 服务器 — 欧洲、北美、南美和亚洲。最近的减少延迟和丢帧。"),
        _T_ETH],
       [("XLoveCam 的 RTMP 数据在哪里？", "My Account → settings — 同时显示 RTMP 链接和密钥。"),
        ("XLoveCam 支持外部编码器吗？", "是 — 它提供 RTMP 链接和密钥，因此 SplitCam 作为编码器工作。"),
        ("XLoveCam 用什么比特率？", "XLoveCam 不发布固定限制；1080p 下 3,500–6,000 Kbps 理想。选择最近的区域服务器同样重要 — 减少丢帧。"),
        ("SplitCam 对 XLoveCam 免费吗？", "是 — 免费、无水印、无时间限制。接触 XLoveCam 的多语言欧洲观众不需要软件成本。")]),
    _p("soulcams", "SoulCams",
       "在 SoulCams 直播 — SplitCam OBS 设置",
       "使用免费 SplitCam 在 SoulCams 直播 — OBS 设置、RTMP 服务器和密钥、多机位场景和叠加层。",
       "soul cams, soulcams, soulcams 直播, soulcams obs, soulcams rtmp, soulcams broadcast",
       '如何使用 SplitCam 在 <span class="accent">SoulCams</span> 直播',
       "SoulCams 直播",
       "SoulCams 的 OBS 设置。",
       "SoulCams 是一个 cam 平台，其 OBS 设置在一个窗口中显示 <strong style='color:var(--text)'>RTMP 服务器和直播密钥</strong>。将两者粘贴到免费 <strong style='color:var(--text)'>SplitCam</strong> 以使用多机位场景和叠加层直播。",
       "使用 SplitCam 在 SoulCams 直播：安装 SplitCam，构建场景，在 SoulCams 点击 Go Online → Settings → OBS，复制服务器和密钥，将两者粘贴到 SplitCam，Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>打开 SoulCams Settings → OBS。</li><li>将服务器 + 密钥粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "在 SoulCams 登录并点击 <strong>Go Online</strong>，然后打开 <strong>Settings</strong> → <strong>OBS</strong>。OBS 窗口同时显示 <strong>RTMP 服务器</strong>和 <strong>直播密钥</strong> — 将两者复制到 SplitCam。",
       [("服务器和密钥并排", "SoulCams 在同一个 OBS 窗口中显示 RTMP 服务器和密钥 — 一次性获取两者。"),
        ("先 Go Online", "OBS 设置只在 SoulCams 上点击 Go Online 后才出现 — 在寻找编码器数据之前先做。"),
        ("封锁不需要的地区", "SoulCams 允许从模特端进行地理封锁 — 在按 Go Online 之前选择哪些国家不能看到直播。"),
        _T_ETH],
       [("SoulCams 的 OBS 设置在哪里？", "登录，点击 Go Online，然后 Settings → OBS — RTMP 服务器和直播密钥一起显示。"),
        ("SoulCams 支持外部编码器吗？", "是 — OBS 设置提供 RTMP 服务器和密钥，因此 SplitCam 工作。"),
        ("SoulCams 用什么比特率？", "SoulCams 不给出官方数字 — 瞄准 1080p 下 3,500–6,000 Kbps 并测试上传，因为 OBS 窗口不显示比特率指导。"),
        ("SplitCam 对 SoulCams 免费吗？", "是 — 免费、无水印、无时间限制，因此具有多机位场景和叠加层的完整 SoulCams 节目在编码器端不花费任何费用。")]),
    _p("imlive", "ImLive",
       "在 ImLive 直播 — SplitCam 虚拟摄像头",
       "使用免费 SplitCam 进行 Im Live stream 设置 — ImLive 直接使用网络摄像头（无 RTMP），将 SplitCam 作为带场景的虚拟摄像头连接。",
       "im live stream, imlive splitcam, imlive 直播, imlive 虚拟摄像头, imlive webcam, im live cam",
       '如何使用 SplitCam 与 <span class="accent">ImLive</span>',
       "ImLive 上的 SplitCam",
       "ImLive 的虚拟摄像头设置 — 无 RTMP。",
       "ImLive 直接在浏览器中使用网络摄像头 — <strong style='color:var(--text)'>没有 RTMP 也没有直播密钥</strong>。免费 <strong style='color:var(--text)'>SplitCam</strong> 作为<strong style='color:var(--text)'>虚拟摄像头</strong>连接：在 SplitCam 中构建场景，然后在 ImLive 中将 SplitCam 选择为摄像头。",
       "在 ImLive 上使用 SplitCam：安装 SplitCam，构建带媒体层的场景，打开 ImLive 并开始视频聊天，在 ImLive 设置中将 SplitCam 选择为网络摄像头和麦克风。"
       "<ol><li>安装 SplitCam。</li><li>在 SplitCam 中构建场景。</li><li>在 ImLive 上开始视频聊天。</li><li>选择 SplitCam 作为 ImLive 摄像头。</li><li>开始聊天。</li></ol>",
       "登录 ImLive 网站并点击 <strong>Start Video Chat</strong>，然后打开 <strong>Go To Settings</strong> 以访问摄像头和麦克风选项。在 ImLive 设置中将 <strong>SplitCam</strong> 选择为网络摄像头和麦克风。",
       [("无需直播密钥", "ImLive 没有 RTMP — 不要寻找服务器 URL 或密钥。SplitCam 只是被选为摄像头设备。"),
        ("将 SplitCam 也设置为麦克风", "除了摄像头之外，将 SplitCam 选择为麦克风，以便您的音频混合和降噪也能进入直播。"),
        ("在直播前构建场景", "ImLive 显示 SplitCam 发送的内容 — 在开始聊天之前安排好图层。"),
        _T_TEST],
       [("ImLive 使用 RTMP 还是直播密钥？", "都不 — ImLive 通过浏览器直接使用网络摄像头。SplitCam 作为虚拟摄像头连接，没有要复制的密钥。"),
        ("如何在 ImLive 中选择 SplitCam？", "Start Video Chat → Go To Settings → 选择 SplitCam 作为网络摄像头和麦克风。"),
        ("我可以在 ImLive 中使用叠加层吗？", "是 — 在 SplitCam 场景中构建它们；ImLive 显示合成结果。"),
        ("SplitCam 对 ImLive 免费吗？", "是 — 免费、无水印、无时间限制。作为 ImLive 的虚拟摄像头，它不会给您的视频聊天添加成本或品牌。")],
       steps=[
           ("安装 SplitCam", "SplitCam 是适用于 Windows 和 macOS 的免费软件。安装它 — 无水印、无注册。对于 ImLive，它作为<strong>虚拟摄像头</strong>工作，而不是 RTMP 编码器。"),
           ("在 SplitCam 中构建场景", "打开 SplitCam 并使用 <strong>Media Layers +</strong> 添加网络摄像头以及任何叠加层、文本、滤镜或 AI 背景。这个合成场景就是 ImLive 将看到的您的摄像头。"),
           ("在 ImLive 上开始视频聊天", "登录 ImLive 网站并点击 <strong>Start Video Chat</strong>，然后打开 <strong>Go To Settings</strong> 以访问摄像头和麦克风选项。"),
           ("选择 SplitCam 作为摄像头", "在 ImLive 设置中将 <strong>SplitCam</strong> 选择为网络摄像头和麦克风。ImLive 现在显示您的完整 SplitCam 场景，而不是平面的网络摄像头。"),
           ("开始 Free Live Chat", "在 ImLive 上点击 <strong>Free Live Chat</strong> 进入直播。要在会话中途更改外观，请在 SplitCam 中编辑场景 — ImLive 立即更新。"),
       ]),
    _p("vxlive", "VXLive",
       "在 VXLive 直播 — SplitCam 官方支持",
       "使用免费 SplitCam 在 VXLive（VXModels / VISIT-X）直播 — 官方 VISIT-X 预设、服务器和密钥、场景。无水印。",
       "vxlive, visit-x, vxmodels splitcam, vxlive 直播, visit-x stream, vxlive rtmp",
       '如何使用 SplitCam 在 <span class="accent">VXLive</span> 直播',
       "VXLive 直播",
       "VXLive 官方支持 SplitCam（VISIT-X 预设）。",
       "VXLive（VXModels / VISIT-X）是来自德国市场的 cam 平台 — 也是少数几个<strong style='color:var(--text)'>官方按名称支持 SplitCam</strong> 的平台之一。VXModels 有一篇专门用于将 <strong style='color:var(--text)'>SplitCam</strong> 连接到 VXLive 的帮助文章，SplitCam 提供 VISIT-X 作为现成的通道预设。",
       "使用 SplitCam 在 VXLive 直播：安装 SplitCam，构建场景，在 VXLive 选择「Stream with third-party software」，复制服务器 URL 和密钥，在 SplitCam 选择 VISIT-X 预设并粘贴，在 SplitCam Go Live，然后在 VXLive GO ONLINE。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>从 VXLive 获取服务器 URL + 密钥。</li><li>在 SplitCam 选择 VISIT-X 预设，粘贴。</li><li>Go Live，然后在 VXLive GO ONLINE。</li></ol>",
       "在 VXLive 选择 <strong>Stream with third-party software</strong> 并选择 <strong>OBS、SplitCam 或 XSplit</strong> 的选项。VXLive 提供<strong>服务器 URL</strong> 和<strong>直播密钥</strong>。在 SplitCam 选择 <strong>VISIT-X</strong> 作为直播平台，粘贴两者，按 SplitCam 中的 <strong>Go Live</strong>，然后在 VXLive 上 <strong>GO ONLINE</strong>。",
       [("VISIT-X 是集成预设", "不要输入原始 RTMP URL — SplitCam 在平台列表中有 VISIT-X；只需选择并粘贴服务器 URL 和密钥。"),
        ("两步式上线", "在 VXLive 先在 SplitCam 中按 Go Live，然后在 VXLive 上 GO ONLINE — 按此顺序。"),
        ("德国市场", "VXLive 的观众主要是德语 — 您语言的德语文本叠加层或标题有助于与观众建立联系。"),
        _T_ETH],
       [("VXLive 官方支持 SplitCam 吗？", "是 — VXModels（VXLive）维护一篇专门用于 SplitCam 设置的官方帮助文章，并将 SplitCam 与 OBS 和 XSplit 一起列为支持的广播软件。"),
        ("如何将 SplitCam 连接到 VXLive？", "在 VXLive 选择「Stream with third-party software」，然后在 SplitCam 选择 VISIT-X 预设并粘贴 VXLive 给的服务器 URL 和直播密钥。"),
        ("我在 SplitCam 还是 VXLive 上 go live？", "两者都 — 先在 SplitCam Go Live，然后在 VXLive 上 GO ONLINE。"),
        ("为什么 VXModels 推荐 SplitCam？", "VXModels 的官方帮助文章专门推荐 SplitCam 用于消除网络摄像头图像伪影和像素化并稳定连接 — 不仅仅是作为通用编码器。")]),
    _p("virtwish", "VirtWish",
       "在 VirtWish 直播 — SplitCam 直播 URL 和密钥",
       "使用免费 SplitCam 在 VirtWish 直播 — Profile → Start Broadcast OBS 部分、直播 URL 和密钥、场景和叠加层。",
       "virtwish, virtwish 直播, virtwish broadcasting software, virtwish rtmp, virtwish stream key, virtwish obs",
       '如何使用 SplitCam 在 <span class="accent">VirtWish</span> 直播',
       "VirtWish 直播",
       "VirtWish 的直播 URL + 密钥设置。",
       "VirtWish 是一个互动 cam 平台。直播设置在一个 OBS 部分中为您提供<strong style='color:var(--text)'>直播 URL 和一个单独的直播密钥</strong> — 免费 <strong style='color:var(--text)'>SplitCam</strong> 获取两者并以场景和叠加层运行节目。",
       "使用 SplitCam 在 VirtWish 直播：安装 SplitCam，构建场景，在 VirtWish 打开 <em>Profile → Start Broadcast</em> 直到 OBS 部分，复制链接和密钥，将两者粘贴到 SplitCam，Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>从 VirtWish 获取 URL + 密钥。</li><li>将两者粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "在 VirtWish 点击右上角图标 → <strong>Profile</strong> → <strong>Start Broadcast</strong>，然后再次 <strong>Start Broadcast</strong> 到达 OBS 部分。<strong>从第一行复制链接</strong>到 SplitCam Stream URL 字段，将 <strong>Stream Key</strong> 单独复制到密钥字段。",
       [("链接在第一行", "VirtWish OBS 部分将直播 URL 放在第一行 — 复制到 SplitCam Stream URL，然后单独的密钥。"),
        ("两次点击 Start Broadcast", "您在 VirtWish 上两次点击 Start Broadcast 才能到达 OBS 部分 — 预期，不是 bug。"),
        _T_ETH, _T_TEST],
       [("VirtWish 的 RTMP 数据在哪里？", "右上角图标 → Profile → Start Broadcast 两次 → OBS 部分显示链接和直播密钥。"),
        ("VirtWish 支持外部编码器吗？", "是 — OBS 部分提供直播 URL 和密钥，因此 SplitCam 工作。"),
        ("VirtWish 用什么比特率？", "VirtWish 不发布官方上限；1080p 下 3,500–6,000 Kbps 安全。将 SplitCam 分辨率与 VirtWish 上设置的分辨率匹配以避免重新缩放。"),
        ("SplitCam 对 VirtWish 免费吗？", "是 — 免费、无水印、无时间限制。VirtWish 的 URL 和密钥设置只花费所需的几分钟。")]),
    _p("xmodels", "XModels",
       "在 XModels 直播 — SplitCam 免费指南",
       "使用免费 SplitCam 在 XModels 直播 — 模特账户设置中的外部编码器选项、RTMP 密钥、场景和叠加层。",
       "xmodels, xmodels 直播, xmodels broadcasting software, xmodels rtmp, xmodels external encoder",
       '如何使用 SplitCam 在 <span class="accent">XModels</span> 直播',
       "XModels 直播",
       "XModels 直播的外部编码器设置。",
       "XModels 是一个 cam-streaming 平台，在模特账户设置中内置了<strong style='color:var(--text)'>外部编码器选项</strong>。免费 <strong style='color:var(--text)'>SplitCam</strong> 在那里以多机位场景、叠加层和滤镜直播，而不是单个平面摄像头。",
       "使用 SplitCam 在 XModels 直播：安装 SplitCam，构建场景，在 XModels 模特账户中激活外部编码器选项，复制服务器 URL 和直播密钥，粘贴到 SplitCam，Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>在 XModels 设置中激活外部编码器。</li><li>将服务器 URL + 密钥粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "在 XModels <strong>模特账户设置</strong>中，激活<strong>通过外部编码器广播</strong>选项。XModels 提供<strong>直播密钥</strong> — 复制到 SplitCam。如果选项不在您期望的位置，XModels 支持通过网站上的 FAQ 聊天和 <strong>info@xmodels.com</strong>；上面的视频也展示了。",
       [("它在账户设置中", "XModels 将外部编码器选项放在模特账户设置中，不在单独的广播屏幕上。"),
        ("支持：聊天 + 电子邮件", "XModels 没有大型公共帮助中心 — 网站 FAQ 聊天和 info@xmodels.com 是官方支持渠道。"),
        ("在 SplitCam 中堆叠叠加层", "小费目标、姓名和社交媒体作为场景层 — XModels 的基础摄像头不会添加此类。"),
        _T_ETH],
       [("XModels 支持外部编码器吗？", "是 — 模特账户设置包括一个外部编码器广播选项，提供直播密钥，因此 SplitCam 工作。"),
        ("我在哪里获得 XModels 帮助？", "XModels 支持通过网站上的 FAQ 聊天和 info@xmodels.com 电子邮件 — 没有大型公共帮助中心。"),
        ("XModels 用什么比特率？", "XModels 没有记录官方数字 — 使用 1080p 下 3,500–6,000 Kbps 并运行 SplitCam 速度测试，因为 XModels 支持只是聊天和电子邮件。"),
        ("SplitCam 对 XModels 免费吗？", "是 — 免费、无水印、无时间限制，因此向 XModels 的欧洲网络直播不会增加软件成本。")]),
    _p("flirt4free", "Flirt4Free",
       "在 Flirt for Free cam 直播 — SplitCam 免费指南",
       "使用免费 SplitCam 在 Flirt for Free cam 直播 — External Broadcast Form、RTMP URL 和 Stream Name、场景和叠加层。",
       "flirt for free cam, flirt 4 free cam, flirt4free, flirt4free 直播, flirt4free external broadcast, flirt4free rtmp",
       '如何使用 SplitCam 在 <span class="accent">Flirt4Free</span> 直播',
       "Flirt4Free 直播",
       "Flirt4Free 的 External Broadcast Form 设置。",
       "Flirt4Free 是最古老的 cam 平台之一，自 90 年代以来一直在播。它通过 <strong style='color:var(--text)'>External Broadcast Form</strong>官方支持外部直播 — 免费 <strong style='color:var(--text)'>SplitCam</strong> 发送直播流，而表单设置分辨率和比特率。",
       "使用 SplitCam 在 Flirt4Free 直播：安装 SplitCam，构建场景，打开 Flirt4Free External Broadcast Form，复制 RTMP URL 和 Stream Name 并设置分辨率/比特率，粘贴到 SplitCam，Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>打开 Flirt4Free External Broadcast Form。</li><li>将 RTMP URL + Stream Name 粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "在 Flirt4Free 模特区域打开 <strong>External Broadcast Form</strong>。与大多数 cam 网站不同，Flirt4Free 给您一个 <strong>RTMP URL</strong> 和一个 <strong>Stream Name</strong>（不是「密钥」），加上您在表单本身中填写的分辨率和比特率字段。将 URL 和 Stream Name 复制到 SplitCam 服务器和密钥字段。",
       [("是 Stream Name，不是密钥", "Flirt4Free 称凭据为 Stream Name。您将它粘贴到 SplitCam 直播密钥字段 — 相同的作用。"),
        ("在表单中设置分辨率/比特率", "Flirt4Free 的 External Broadcast Form 有自己的分辨率和比特率字段 — 与 SplitCam 设置对齐，这样图像就不会被重新缩放。"),
        ("历史平台", "Flirt4Free 从 90 年代开始运行 — 模特工具成熟，External Broadcast Form 是其文档化的一部分。"),
        _T_ETH],
       [("Flirt4Free 支持外部编码器吗？", "是 — 官方，通过 External Broadcast Form，它提供 RTMP URL 和 Stream Name。SplitCam 作为编码器工作。"),
        ("我从哪里获取 Flirt4Free 的 RTMP 数据？", "从模特区域的 External Broadcast Form — 显示 RTMP URL、Stream Name 和分辨率/比特率字段。"),
        ("Flirt4Free 用什么比特率？", "1080p 下 3,500–6,000 Kbps — 在 External Broadcast Form 和 SplitCam 中设置相同的值。"),
        ("SplitCam 对 Flirt4Free 免费吗？", "是 — 免费、无水印、无时间限制，这与像 Flirt4Free 这样节目可能很长的历史平台匹配。")]),
    _p("mfc-alerts", "MFC Alerts",
       "使用 SplitCam 将 MFC Alerts 添加到您的直播",
       "在 MyFreeCams 直播中显示动画小费提醒 — mfcalerts.com URL 作为免费 SplitCam 中网络摄像头上方的浏览器层。",
       "mfc alerts, myfreecams alerts, 添加 mfc alerts, mfcalerts splitcam, myfreecams tip alerts, myfreecams alerts overlay",
       '如何将 <span class="accent">MFC Alerts</span> 添加到您的直播',
       "添加 MFC Alerts",
       "在 MyFreeCams 直播中显示动画小费提醒。",
       "MFC Alerts 在观众发送小费时在您的 MyFreeCams 直播中显示动画效果。它在免费 <strong style='color:var(--text)'>SplitCam</strong> 中作为<strong style='color:var(--text)'>浏览器层</strong>运行 — 设置一次，小费会实时触发屏幕上的反应。",
       "使用 SplitCam 添加 MFC Alerts：安装 SplitCam，添加网络摄像头，打开浏览器选项卡并加载 mfcalerts.com，复制您的 alerts URL，将其作为浏览器层添加在网络摄像头上方，然后用测试小费测试。"
       "<ol><li>安装 SplitCam。</li><li>添加网络摄像头。</li><li>从 mfcalerts.com 获取 URL。</li><li>作为浏览器层添加在网络摄像头上方。</li><li>发送测试小费。</li></ol>",
       "在 SplitCam 中打开<strong>浏览器</strong>选项卡并导航到 <strong>www.mfcalerts.com</strong>。登录或注册。使用 <strong>Copy to clipboard</strong> 复制您的个人 alerts URL。将 URL 粘贴到 SplitCam 浏览器窗口并点击 <strong>Add</strong>。然后重新排序源列表，使 <strong>MFC Alerts 在网络摄像头上方</strong>（3 点菜单 → Move Up）。",
       [("MFC Alerts 必须在网络摄像头上方", "最常见的错误：如果 MFC Alerts 层在源列表中的网络摄像头下方，效果将保持隐藏。向上移动。"),
        ("需要 mfcalerts.com 账户", "alerts URL 是个人的 — 如果您没有账户，请先在 mfcalerts.com 注册。"),
        ("在直播前发送测试小费", "使用 Settings → Send test tip 确认叠加层正在工作 — 不要在节目中途发现错误。"),
        _T_ETH],
       [("什么是 MFC Alerts？", "MyFreeCams 的通知系统，在观众发送小费时在您的直播中显示视频效果 — 在 SplitCam 中作为浏览器叠加层添加。"),
        ("为什么我的 MFC Alerts 不出现？", "几乎总是层顺序 — MFC Alerts 浏览器层必须在 SplitCam 源列表中的网络摄像头上方。"),
        ("我需要 MFC Alerts 的账户吗？", "是 — 在 mfcalerts.com 注册以获取您的个人 alerts URL。"),
        ("SplitCam 对此免费吗？", "是 — SplitCam 免费、无水印、无时间限制，MFC Alerts 浏览器叠加层在其中运行而无需额外成本。")],
       steps=[
           ("安装 SplitCam 并添加网络摄像头", "为 Windows 或 macOS 安装免费 SplitCam，然后将<strong>网络摄像头</strong>作为源添加。MFC Alerts 作为此摄像头上方的层。"),
           ("打开浏览器选项卡并转到 mfcalerts.com", "在 SplitCam 中打开<strong>浏览器</strong>选项卡并导航到 <strong>www.mfcalerts.com</strong>。登录，或在还没有 mfcalerts.com 账户的情况下注册。"),
           ("复制您的 alerts URL", "在 mfcalerts.com 上使用 <strong>Copy to clipboard</strong> 复制您的个人 alerts URL — 这是渲染小费动画的页面。"),
           ("将 URL 作为浏览器层添加 — 在网络摄像头上方", "将 URL 粘贴到 SplitCam 浏览器窗口并点击 <strong>Add</strong>。然后重新排序源列表，使 <strong>MFC Alerts 在网络摄像头上方</strong>（3 点菜单 → Move Up）。如果它在下面，效果将保持隐藏。"),
           ("用测试小费测试", "打开 <strong>Settings → Send test tip</strong> 并确认 alert 效果出现在您的摄像头上方。然后正常在 MyFreeCams 上直播 — 真实的小费现在触发动画。"),
       ]),
    _p("lovense", "Lovense",
       "使用 SplitCam 将 Lovense 玩具添加到您的直播",
       "使用免费 SplitCam 将互动 Lovense 玩具连接到 cam 直播 — Lovense SplitCam Toolset、屏幕小费提醒、反应。",
       "添加 lovense 到直播, lovense cam stream, lovense splitcam, lovense splitcam toolset, lovense interactive toy streaming",
       '如何将 <span class="accent">Lovense 玩具</span>添加到您的直播',
       "添加 Lovense 玩具",
       "将互动 Lovense 玩具连接到您的 cam 直播。",
       "您通过免费 <strong style='color:var(--text)'>SplitCam</strong> 运行 cam 直播并配对一个对代币做出反应的 <strong style='color:var(--text)'>Lovense</strong> 玩具。Lovense 记录了官方 <strong style='color:var(--text)'>Lovense SplitCam Toolset</strong>，SplitCam 提供官方 Lovense 插件 — 集成从两方面都得到支持。",
       "要将 Lovense 玩具添加到直播：安装 SplitCam 和 Lovense 软件，配对玩具，将 Lovense 链接到您的 cam 平台，在 SplitCam 中将 Lovense 状态添加为浏览器层，然后正常直播。"
       "<ol><li>安装 SplitCam。</li><li>安装 Lovense 软件并配对玩具。</li><li>将 Lovense 链接到您的 cam 网站。</li><li>在 SplitCam 中添加 Lovense 叠加层。</li><li>按 Go Live。</li></ol>",
       "安装 Lovense Connect / Lovense Stream（官方桌面应用）。打开玩具并通过蓝牙配对，使应用显示已连接。在 Lovense 应用中链接您的 cam 账户，使玩具对观众的代币/小费做出反应。Lovense 提供叠加层/小部件 URL — 在 SplitCam 场景中作为<strong>浏览器</strong>层添加。",
       [("使用官方 Lovense SplitCam Toolset", "Lovense 发布了带有自己安装指南的 SplitCam 特定工具集 — 它添加了为 SplitCam 制作的玩具活动叠加层和小费提醒。"),
        ("更新 Lovense Cam Extension", "工具集需要最新的 Lovense Cam Extension（30.1.4 或更新版本）— 在直播前更新。"),
        ("保持玩具充电", "节目中途几乎耗尽的电池会杀死互动方 — 在直播前充满电。"),
        ("测试代币反应", "发送一个小的测试小费以确认玩具在打开房间之前做出反应。"),
        ("检查版本要求", "Lovense SplitCam Toolset 需要 SplitCam 10.4.5 或更新版本。Lovense Cam Extension 官方涵盖 Chaturbate、Stripchat、BongaCams、MyFreeCams 和 CamSoda — 对于任何其他网站，使用 Lovense 的 Generic URL 集成。")],
       [("Lovense 官方支持 SplitCam 吗？", "是 — Lovense 记录了带有自己安装指南的官方「Lovense SplitCam Toolset」，SplitCam 提供官方 Lovense 插件。集成从两方面都得到支持。"),
        ("玩具直接连接到 SplitCam 吗？", "不 — 玩具与 Lovense 应用配对；SplitCam 显示 Lovense 叠加层并直播摄像头。"),
        ("哪些 cam 网站支持 Lovense？", "Lovense Cam Extension 官方支持 Chaturbate、Stripchat、BongaCams、MyFreeCams 和 CamSoda，对其他的支持不同 — 在 Lovense 应用中查看当前列表。"),
        ("我可以在屏幕上显示最近的小费吗？", "是 — 在 SplitCam 中将 Lovense 小部件 URL 添加为浏览器层。")],
       steps=[
           ("安装 SplitCam", "SplitCam 是适用于 Windows 和 macOS 的免费直播软件 — 将您的视频发送到 cam 平台的编码器。安装；无水印。"),
           ("安装 Lovense 软件并配对玩具", "安装 Lovense Connect / Lovense Stream（官方桌面应用）。打开玩具并通过蓝牙配对，使应用显示已连接。"),
           ("将 Lovense 链接到您的 cam 平台", "在 Lovense 应用中链接您的 cam 账户，使玩具对观众的代币/小费做出反应。大多数主要 cam 平台都受支持。"),
           ("在 SplitCam 中添加 Lovense 叠加层", "Lovense 提供叠加层/小部件 URL。在 SplitCam 场景中作为<strong>浏览器</strong>层添加，使观众在屏幕上看到玩具状态和最近的小费。"),
           ("构建场景和 Go Live", "添加摄像头和其他叠加层，将 cam 平台的 RTMP 密钥粘贴到 SplitCam 并点击 <strong>Go Live</strong>。玩具实时对小费做出反应。"),
       ]),
    _p("multistream-cams", "多个 cam 网站",
       "使用 SplitCam 同时直播到多个 cam 网站",
       "使用 SplitCam 的免费多平台直播同时直播到 MyFreeCams、Chaturbate、BongaCams、CAM4、Stripchat 等。一键、无水印。",
       "直播到多个 cam 网站, multistream cam sites, 同时直播到 chaturbate 和 bongacams, multistream cam 软件",
       '如何<span class="accent">同时直播到多个 cam 网站</span>',
       "Cam 多平台直播",
       "同时直播到多个 cam 网站。",
       "免费 <strong style='color:var(--text)'>SplitCam</strong> 可以将一个编码同时<strong style='color:var(--text)'>直播到多个 cam 网站</strong> — MyFreeCams、Chaturbate、BongaCams、CAM4、Stripchat 等。无水印，一键。",
       "要一次直播到多个 cam 网站：安装 SplitCam，构建场景，获取每个 cam 网站的 RTMP 服务器 URL 和直播密钥，将所有这些添加到 SplitCam 多平台直播设置中，一次点击 Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>从每个 cam 网站获取 RTMP 密钥。</li><li>在 SplitCam multistream 中添加所有密钥。</li><li>一次按 Go Live。</li></ol>",
       "在每个 cam 平台上激活外部 / RTMP 直播并复制<strong>服务器 URL</strong> 和<strong>直播密钥</strong>。在 SplitCam 打开 <strong>Stream Settings</strong> 并将每个 cam 网站作为自定义 RTMP 目标添加 — 粘贴服务器 URL 和密钥。检查所有要直播的内容。按 <strong>Go Live</strong>。",
       [("注意您的上传", "多平台直播会增加上传负载。每个目标消耗自己的比特率 — 确保您的连接可以处理总和。"),
        ("检查平台规则", "一些 cam 网站禁止同时在其他地方直播 — 在多平台直播之前确认。"),
        ("电缆 — 这里不能掉线", "多平台直播会增加上传负载，因此单个 wi-fi 掉线可能会一次性击倒所有目标。这里电缆不是可选的。"),
        ("观察健康监视器", "SplitCam 按目标显示状态 — 如果上传无法处理，放弃一个网站。")],
       [("SplitCam 多平台直播免费吗？", "是 — 多平台直播是内置的且免费，没有按目标的费用，没有水印。"),
        ("我可以同时直播到多少个 cam 网站？", "您的上传带宽可以处理的数量 — 每个目标消耗自己的比特率。"),
        ("它使用云中继吗？", "不 — SplitCam 通过对等方式直接从 PC 将直播流发送到每个平台的摄取。"),
        ("多平台直播会让我的 PC 变慢吗？", "编码完成一次并重用；硬件编码保持 CPU 负载低。上传带宽是真正的限制。")],
       steps=[
           ("安装 SplitCam", "SplitCam 是适用于 Windows 和 macOS 的免费直播软件，内置多平台直播。安装 — 无水印、无注册。"),
           ("设置摄像头和场景", "打开 SplitCam，添加网络摄像头并构建带叠加层和滤镜的场景。一个场景为每个目标提供信息。"),
           ("从每个 cam 网站获取 RTMP 密钥", "在每个 cam 平台上激活外部 / RTMP 直播并复制<strong>服务器 URL</strong> 和<strong>直播密钥</strong>。对您要直播的每个网站重复 — 请参阅各个平台指南以获取确切路径。"),
           ("在 SplitCam 中添加每个目标", "打开 <strong>Stream Settings</strong> 并将每个 cam 网站作为自定义 RTMP 目标添加 — 粘贴服务器 URL 和密钥。检查所有要直播的内容。"),
           ("一次点击 Go Live", "按 <strong>Go Live</strong>。SplitCam 同时将直播流发送到每个选定的 cam 网站，对等，从单个编码 — 无额外费用。"),
       ]),
    _p("livejasmin", "LiveJasmin",
       "在 LiveJasmin 直播 — SplitCam HD External Encoder",
       "使用免费 SplitCam 在 LiveJasmin 直播 — Model Center External Encoder、HD 1080p 设置、多机位场景和叠加层。无水印，无需注册。",
       "livejasmin 直播, livejasmin obs, livejasmin external encoder, livejasmin rtmp, livejasmin stream key, livejasmin 模特设置",
       '如何使用 SplitCam 在 <span class="accent">LiveJasmin</span> 直播',
       "LiveJasmin 直播",
       "LiveJasmin HD-only Model Center 的外部编码器设置。",
       "LiveJasmin 是 Docler Holding 的旗舰平台 — 全球最大的 cam 网络之一，且为 HD-only 平台。它推荐的直播工具是自研的 <strong>JasminCAM</strong> 客户端，但 Model Center 同时提供标准的 <strong>External Encoder</strong> 通道 — 免费 <strong style='color:var(--text)'>SplitCam</strong> 接入这里，让您在同一条 HD 直播流上使用多机位场景、美颜滤镜和叠加层。",
       "使用 SplitCam 在 LiveJasmin 直播：安装 SplitCam，构建 HD 场景，在 Model Center 进入 <em>Settings → Broadcast → External Encoder</em>，复制服务器 URL 和 stream key，粘贴到 SplitCam，Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + HD 场景。</li><li>从 Model Center 获取 URL 和 stream key。</li><li>粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "登录 <strong>modelcenter.livejasmin.com</strong>，打开 <strong>Settings → Broadcast → External Encoder</strong>。Model Center 显示与您的账号绑定的<strong>服务器 URL</strong> 和 <strong>stream key</strong> — 将两者粘贴到 SplitCam 的自定义 RTMP 字段。<strong>注意：</strong>新账号需要审核通过（48–72 小时）后才会出现 External Encoder 选项，且平台强制要求 HD-only 输出。",
       [("HD 不达标会被降权", "LiveJasmin 是 HD-only — 低于 1280×720 只会被推到低消费名单，低于 1080p 则失去 Premium 资格。瞄准 1920×1080、30 fps、4,000–6,000 Kbps。"),
        ("JasminCAM vs 外部编码器", "Docler 自家的 JasminCAM 客户端 HD 合规性最干净，但账号审核通过后官方同样支持外部编码器（OBS、SplitCam、vMix）— 它们解锁 JasminCAM 做不到的多机位场景和叠加层。"),
        ("Free chat ≠ Private show", "Free chat 是预览模式 — 不允许裸露。Private 和 Gold show 才是模特真正赚钱的地方。规划场景时要让自己穿着状态和秀场状态都能撑得住。"),
        _T_ETH],
       [("LiveJasmin 官方支持 SplitCam 这类外部编码器吗？", "是 — Model Center 在 Settings → Broadcast 下提供 External Encoder 选项。JasminCAM 是推荐客户端，但模特账号审核通过后，OBS、SplitCam 等 RTMP 编码器均被明确列为支持。"),
        ("我的 LiveJasmin stream key 在哪里？", "在 Model Center 内：Settings → Broadcast → External Encoder。服务器 URL 和唯一的 stream key 都显示在这里 — 都粘贴到 SplitCam 的自定义 RTMP 字段。该 key 绑定您的账号；请像密码一样保管。"),
        ("LiveJasmin 用什么比特率？", "LiveJasmin 是 HD-only — 瞄准 1920×1080、30 fps、4,000–6,000 Kbps，2 秒关键帧间隔。明显低于此就会失去 Premium 标签并被降权。"),
        ("SplitCam 在 LiveJasmin 上免费吗？", "是 — SplitCam 免费、无水印、无时间限制。唯一的「成本」是要满足 LiveJasmin 的 HD 要求，而 SplitCam 凭借原生 1080p 场景合成和美颜滤镜可以轻松做到。")],
       steps=[
           ("下载并安装 SplitCam", "SplitCam 是适用于 Windows 和 macOS 的免费直播软件 — 无需注册、无需信用卡、无水印。它是把您的 HD 视频送到 LiveJasmin 的编码器。"),
           ("构建您的 HD 场景", "打开 SplitCam，以 1080p 模式添加网络摄像头。叠加上叠加层、文字、第二个摄像头或手机、美颜滤镜或 AI 背景 — LiveJasmin 要求 HD 质量，您组合好的场景要在 free chat 和 private show 中始终看起来高端。"),
           ("获取您的 LiveJasmin URL 和 stream key", "登录 <strong>modelcenter.livejasmin.com</strong>（账号必须先审核通过 — 通常在注册后 48–72 小时）。打开 <strong>Settings → Broadcast → External Encoder</strong>。页面显示一个<strong>服务器 URL</strong> 和唯一的 <strong>stream key</strong>。两者都复制下来。"),
           ("将 SplitCam 连接到 LiveJasmin", "在 SplitCam 中打开 <strong>Stream Settings</strong>，将 LiveJasmin 服务器 URL 和 stream key 粘贴到自定义 RTMP 字段。设置比特率为 4,000–6,000 Kbps、1920×1080、30 fps，2 秒关键帧。先跑一次内置速度测试 — HD 流对带宽要求很高。"),
           ("点击 Go Live", "在 SplitCam 按 <strong>Go Live</strong>，然后在 LiveJasmin Model Center 上线。约 10 秒内您的 HD 信号就抵达 LiveJasmin 网络。之后每次开播都是一键 — 打开 SplitCam、Go Live，然后在 LiveJasmin 上线。"),
       ]),
    _p("myfreecams", "MyFreeCams",
       "如何使用 SplitCam 在 MyFreeCams（MFC）直播 — 绕过 Model Web Broadcaster",
       "使用免费 SplitCam 在 MyFreeCams 直播 — Model Admin External Broadcaster、MFC 代币经济、多机位场景、叠加层。无水印，无需注册。",
       "myfreecams 直播, mfc external broadcaster, myfreecams obs, mfc rtmp, mfc stream key, model admin, mfc 代币",
       '如何使用 SplitCam 在 <span class="accent">MyFreeCams</span> 直播',
       "MyFreeCams 直播",
       "MFC 代币制 Model Admin 的外部编码器设置。",
       "MFC 是历史最悠久的 cam 平台之一 — 纯代币经济，没有繁琐的模特审核流程，拥有忠诚的 Premium 会员群体。默认的 Model Web Broadcaster 是浏览器内的单机位工具，但 Model Admin 同时开放了 External Broadcaster 通道 — 免费 <strong style='color:var(--text)'>SplitCam</strong> 接入这里，解锁多机位场景、叠加层和美颜滤镜。",
       "使用 SplitCam 在 MyFreeCams 直播：安装 SplitCam，构建场景，进入 Model Admin → Broadcaster，将 Web Broadcaster 切换为 External Broadcaster，复制服务器 URL 和 stream key，粘贴到 SplitCam，Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>在 Model Admin 切换到 External Broadcaster。</li><li>将 URL 和 stream key 粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "登录 MyFreeCams，打开 <strong>Model Admin → Broadcaster</strong>，将 <strong>Web Broadcaster</strong> 切换为 <strong>External Broadcaster</strong>。页面会显示与您模特账号绑定的服务器 URL（rtmp://publish.myfreecams.com…）和 stream key — 将两者复制到 SplitCam 的自定义 RTMP 字段。该 key 与账号绑定，请像密码一样保管。",
       [("MFC 是纯小费/代币经济，不是订阅制", "MFC 的核心不是订阅，而是 free chat 中的小费 — Premium 会员可以发起 private，但日常收入来自衣着状态下的 free chat。规划场景时要保证穿着随意时也能持续赚到小费。"),
        ("Web Broadcaster vs External Broadcaster", "默认的 Web Broadcaster 是单信号源工具；External Broadcaster 通过 SplitCam/OBS 解锁多场景、叠加层和美颜滤镜 — 这是高收入模特和新人之间的明显差距。"),
        ("用 mfcalerts.com 做小费提醒", "在 SplitCam 中把 mfcalerts.com 作为 Browser 图层添加到摄像头之上 — 直接在视频里显示小费动画和会员名称，会显著提高 free chat 的小费转化率。"),
        _T_ETH],
       [("MFC 支持 SplitCam 这类外部直播软件吗？", "支持 — Model Admin 提供 External Broadcaster 选项，走标准 RTMP，OBS、SplitCam、vMix 都可以使用。"),
        ("我的 MFC stream key 在哪里？", "Model Admin → Broadcaster → External Broadcaster — 页面同时显示服务器 URL 和 stream key。两者都复制到 SplitCam。"),
        ("MFC 用什么比特率？", "MFC 支持最高约 6,000 Kbps、2 秒关键帧间隔。推 1920×1080、30 fps、3,500–6,000 Kbps 是稳妥配置。"),
        ("SplitCam 在 MFC 上免费吗？", "是 — SplitCam 完全免费，无水印，无时间限制。")],
       steps=[
           ("下载并安装 SplitCam", "SplitCam 是适用于 Windows 和 macOS 的免费直播编码器 — 无需注册、无需信用卡、无水印。"),
           ("构建您的场景", "在 SplitCam 中添加网络摄像头，叠加叠加层、文字、第二个摄像头或手机、美颜滤镜或 AI 背景。把 <strong>mfcalerts.com</strong> 作为 Browser 图层加到摄像头上方，让小费动画直接出现在 free chat 画面中。"),
           ("在 Model Admin 切换到 External Broadcaster", "登录 MFC，打开 <strong>Model Admin → Broadcaster</strong>，将 Web Broadcaster 切换为 <strong>External Broadcaster</strong>。复制显示的服务器 URL（rtmp://publish.myfreecams.com…）和 stream key。"),
           ("在 SplitCam 中粘贴 URL 和 key", "打开 SplitCam 的 <strong>Stream Settings</strong>，将 URL 和 stream key 粘贴到自定义 RTMP 字段。比特率设为 3,500–6,000 Kbps、1920×1080、30 fps、关键帧 2 秒。"),
           ("点击 Go Live", "在 SplitCam 按 <strong>Go Live</strong>。约 10 秒内信号就抵达 MFC，您在房间中正式上线。"),
       ]),
    _p("cherry-tv", "Cherry.tv",
       "如何使用 SplitCam 在 Cherry.tv 直播 — Web3 友好的外部编码器",
       "使用免费 SplitCam 在 Cherry.tv 直播 — Streamer Dashboard 外部编码器、加密货币友好的 cam 平台、多机位场景。无水印，无需注册。",
       "cherry tv 直播, cherry.tv obs, cherry tv 外部编码器, cherry.tv rtmp, cherry.tv stream key, cherry tv 主播, web3 cam",
       '如何使用 SplitCam 在 <span class="accent">Cherry.tv</span> 直播',
       "Cherry.tv 直播",
       "Cherry.tv 的 Streamer Dashboard 外部编码器设置。",
       "Cherry.tv 是较新、增长迅速的 cam 平台，主打 Web3 概念 — 支持加密货币结算，入门门槛比 LiveJasmin 等老牌网络低。默认走浏览器直播，但 Streamer Dashboard 也开放了标准的 External Encoder 通道 — 免费 <strong style='color:var(--text)'>SplitCam</strong> 接入这里即可。",
       "使用 SplitCam 在 Cherry.tv 直播：安装 SplitCam，构建场景，进入 Streamer Dashboard → Broadcast Settings → External Encoder，复制 URL 和 stream key，粘贴到 SplitCam，Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>在 Streamer Dashboard 找到 External Encoder。</li><li>将 URL 和 stream key 粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "登录 Cherry.tv 主播账号，进入 <strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong>。服务器 URL 和 stream key 都与账号绑定。新账号需要完成基础认证（Cherry.tv 的入驻流程比老牌 cam 网络更轻量）。",
       [("入门更轻、流量在增长", "没有 72 小时的 Docler 式审核 — 现在正是抢占 Cherry.tv 早期粉丝的好时机，先入场的人更容易建立稳定的 follower 群。"),
        ("加密货币与法币并行结算", "Cherry.tv 同时支持加密货币结算 — 对于传统结算渠道慢或受限的地区尤其有用，能更快拿到收入。"),
        ("浏览器直播 vs 外部编码器", "Cherry.tv 的浏览器内直播工具只能跑单一摄像头；SplitCam 解锁多机位场景、叠加层、美颜滤镜和 AI 背景 — 这正是观感拉开差距的关键。"),
        _T_ETH],
       [("Cherry.tv 支持外部编码器吗？", "支持 — Streamer Dashboard 在 Broadcast Settings 下提供 External Encoder 选项，走标准 RTMP，OBS、SplitCam 都可用。"),
        ("我的 Cherry.tv stream key 在哪里？", "Streamer Dashboard → Broadcast Settings → External Encoder — URL 和 stream key 都显示在这里。"),
        ("Cherry.tv 用什么比特率？", "推 3,500–6,000 Kbps、1920×1080、30 fps、关键帧 2 秒。"),
        ("SplitCam 在 Cherry.tv 上免费吗？", "是 — SplitCam 完全免费，无水印，无时间限制。")],
       steps=[
           ("下载并安装 SplitCam", "SplitCam 是适用于 Windows 和 macOS 的免费直播编码器 — 无需注册、无需信用卡、无水印。"),
           ("构建您的场景", "添加网络摄像头并叠加叠加层 — Cherry.tv 的观众更年轻、对平台更熟悉，画面的设计感和氛围非常重要。可以加入彩色叠加层、动态文字和 AI 背景。"),
           ("获取 URL 和 stream key", "在 <strong>Streamer Dashboard → Broadcast Settings → External Encoder</strong> 中复制服务器 URL 和 stream key。"),
           ("在 SplitCam 中粘贴", "打开 SplitCam 的 <strong>Stream Settings</strong>，粘贴 URL 和 stream key。比特率设为 3,500–6,000 Kbps、1920×1080、30 fps、关键帧 2 秒。"),
           ("点击 Go Live", "在 SplitCam 按 <strong>Go Live</strong>，然后在 Streamer Dashboard 中切到在线状态 — 您即刻在 Cherry.tv 上线。"),
       ]),
    _p("amateurtv", "AmateurTV",
       "如何使用 SplitCam 在 AmateurTV 直播 — 西班牙语 cam 网络",
       "使用免费 SplitCam 在 AmateurTV 直播 — Model Panel 外部编码器、面向西班牙和拉美的西语 cam 网络、多机位场景。无水印，无需注册。",
       "amateurtv 直播, amateur.tv obs, amateurtv 外部编码器, amateurtv rtmp, amateurtv stream key, modelos amateur tv",
       '如何使用 SplitCam 在 <span class="accent">AmateurTV</span> 直播',
       "AmateurTV 直播",
       "AmateurTV 西语网络的外部编码器设置。",
       "AmateurTV 是西语世界最大的 cam 网络 — 西班牙、墨西哥、阿根廷以及整个拉美都有稳定的观众群。默认的 Model Panel 浏览器直播工具可用，但同时开放了标准的 <strong>External Encoder</strong> 通道 — 免费 <strong style='color:var(--text)'>SplitCam</strong> 接入这里，让您用多机位场景、美颜滤镜和叠加层服务这片被美系网络忽视的西语观众。",
       "使用 SplitCam 在 AmateurTV 直播：安装 SplitCam，构建场景，在 Model Panel 打开 <em>Broadcast Settings → External Encoder</em>，复制服务器 URL 和 stream key，粘贴到 SplitCam，Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>在 Model Panel 获取 URL 和 stream key。</li><li>粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "登录 AmateurTV 模特账号，进入 <strong>Model Panel</strong>，导航到 <strong>Broadcast Settings → External Encoder</strong>。页面会显示与账号绑定的服务器 URL 和 stream key — 复制两者到 SplitCam 的自定义 RTMP 字段。新模特账号需要先完成身份认证才能开播。",
       [("西语观众优先", "AmateurTV 的流量绝大部分讲西班牙语 — 白天以西班牙为主，美东傍晚以后则切到拉美。房间标题、场景文字和叠加层用西语，效果远胜纯英文。"),
        ("拉美时区是您的黄金档", "高峰流量与拉美的傍晚时段（UTC-3 到 UTC-6）高度重合。如果时间灵活，欧洲深夜 / 亚洲清晨段能同时吃到西班牙和拉美两个高峰。"),
        ("中等但稳定的分成", "RPM 不算全行业最高，但分成稳定，西语细分市场的竞争也远比头部美系网络小。"),
        _T_ETH],
       [("AmateurTV 官方支持 SplitCam 这类外部编码器吗？", "支持 — Model Panel 在 Broadcast Settings 下提供 External Encoder 选项，走标准 RTMP，OBS、SplitCam、vMix 等都能接入。"),
        ("我的 AmateurTV stream key 在哪里？", "Model Panel → Broadcast Settings → External Encoder — URL 和 stream key 都在这里，复制两者到 SplitCam 的自定义 RTMP 字段。该 key 与账号绑定。"),
        ("AmateurTV 用什么比特率？", "标准 cam 画质即可 — 推 1920×1080、30 fps、3,500–6,000 Kbps、关键帧 2 秒。先用 SplitCam 自带的速度测试跑一遍。"),
        ("SplitCam 在 AmateurTV 上免费吗？", "是 — SplitCam 完全免费，无水印，无时间限制。AmateurTV 的 External Encoder 选项也免费开启。")],
       steps=[
           ("下载并安装 SplitCam", "SplitCam 是适用于 Windows 和 macOS 的免费直播软件 — 无需注册、无需信用卡、无水印。它就是把您的画面推送到 AmateurTV 的编码器。"),
           ("构建您的场景", "在 SplitCam 中添加网络摄像头。叠加叠加层、文字、第二个摄像头或手机、美颜滤镜或 AI 背景。面向 AmateurTV 的西语观众，叠加层文字直接用西语。"),
           ("获取 AmateurTV URL 和 stream key", "登录 AmateurTV 模特账号，打开 <strong>Model Panel</strong>，进入 <strong>Broadcast Settings → External Encoder</strong>。页面会显示服务器 URL 和专属 stream key。复制两者。"),
           ("将 SplitCam 接入 AmateurTV", "打开 SplitCam 的 <strong>Stream Settings</strong>，把 AmateurTV 的 URL 和 stream key 粘贴到自定义 RTMP 字段。比特率设为 3,500–6,000 Kbps、1920×1080、30 fps、关键帧 2 秒。先跑一次自带的速度测试。"),
           ("点击 Go Live", "在 SplitCam 按 <strong>Go Live</strong>，然后在 AmateurTV 的 Model Panel 切到在线状态。约 10 秒内信号即抵达网络。后续开播只需一键 — 打开 SplitCam，Go Live。"),
       ]),
    _p("camster", "Camster",
       "如何使用 SplitCam 在 Camster 直播 — Model Hub 外部编码器",
       "使用免费 SplitCam 在 Camster 直播 — Model Hub 外部编码器、老牌中端 cam 平台、多机位场景和叠加层。无水印，无需注册。",
       "camster 直播, camster.com obs, camster 外部编码器, camster rtmp, camster stream key, camster model hub",
       '如何使用 SplitCam 在 <span class="accent">Camster</span> 直播',
       "Camster 直播",
       "Camster 的 Model Hub 外部编码器设置。",
       "Camster 是一家老牌中端 cam 平台 — 体量小于 Chaturbate 或 LiveJasmin，但拥有忠诚的会员群和公平的分成。默认的 Model Hub 浏览器直播工具可用，但同时开放了标准的 <strong>External Encoder</strong> 通道 — 免费 <strong style='color:var(--text)'>SplitCam</strong> 接入这里，让您用多机位场景、叠加层和滤镜做出浏览器工具做不到的画面。",
       "使用 SplitCam 在 Camster 直播：安装 SplitCam，构建场景，在 Model Hub 打开 <em>Broadcast Settings → External Encoder</em>，复制服务器 URL 和 stream key，粘贴到 SplitCam，Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>在 Model Hub 获取 URL 和 stream key。</li><li>粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "登录 Camster 模特账号，打开 <strong>Model Hub</strong>，导航到 <strong>Broadcast Settings → External Encoder</strong>。页面会显示与账号绑定的服务器 URL 和 stream key — 复制两者到 SplitCam 的自定义 RTMP 字段。该 key 与账号绑定，请像密码一样保管。",
       [("中端意味着竞争更小", "Camster 流量稳定，但主播总量远少于头部网络 — 只要场景做得用心、排播稳定，更容易上首页。"),
        ("浏览器直播 vs 外部编码器", "默认浏览器直播是单信号源；通过 External Encoder 接入 SplitCam 才能解锁多机位场景、叠加层、美颜滤镜和 AI 背景。"),
        ("分成公平，结算稳定", "Camster 的分成在中端档位里属于公道水平 — 不是行业最高，但每月按时结算，关于打款延迟的模特投诉非常少。"),
        _T_ETH],
       [("Camster 官方支持 SplitCam 这类外部编码器吗？", "支持 — Model Hub 在 Broadcast Settings 下提供 External Encoder 选项，标准 RTMP 服务器 URL 和 stream key，OBS、SplitCam 等编码器都能接入。"),
        ("我的 Camster stream key 在哪里？", "Model Hub → Broadcast Settings → External Encoder — URL 和 stream key 都在这里。两者都复制到 SplitCam 的自定义 RTMP 字段。"),
        ("Camster 用什么比特率？", "标准 cam 画质即可 — 推 1920×1080、30 fps、3,500–6,000 Kbps、关键帧 2 秒。先用 SplitCam 自带的速度测试跑一遍。"),
        ("SplitCam 在 Camster 上免费吗？", "是 — SplitCam 完全免费，无水印，无时间限制。Camster 的 External Encoder 选项也免费开启。")],
       steps=[
           ("下载并安装 SplitCam", "SplitCam 是适用于 Windows 和 macOS 的免费直播软件 — 无需注册、无需信用卡、无水印。"),
           ("构建您的场景", "在 SplitCam 中添加网络摄像头。叠加叠加层、文字、第二个摄像头或手机、美颜滤镜或 AI 背景 — 全部实时应用。"),
           ("获取 Camster URL 和 stream key", "登录 Camster 模特账号，打开 <strong>Model Hub</strong>，进入 <strong>Broadcast Settings → External Encoder</strong>。页面会显示服务器 URL 和专属 stream key。复制两者。"),
           ("将 SplitCam 接入 Camster", "打开 SplitCam 的 <strong>Stream Settings</strong>，把 Camster 的 URL 和 stream key 粘贴到自定义 RTMP 字段。比特率设为 3,500–6,000 Kbps、1920×1080、30 fps、关键帧 2 秒。先跑一次自带的速度测试。"),
           ("点击 Go Live", "在 SplitCam 按 <strong>Go Live</strong>，然后在 Camster 的 Model Hub 切到在线状态。约 10 秒内信号即抵达 Camster。"),
       ]),
    _p("camversity", "Camversity",
       "如何使用 SplitCam 在 Camversity 直播 — Performer Dashboard 外部编码器",
       "使用免费 SplitCam 在 Camversity 直播 — Performer Dashboard 外部编码器、对主播友好的成长型 cam 平台、多机位场景。无水印，无需注册。",
       "camversity 直播, camversity obs, camversity 外部编码器, camversity rtmp, camversity stream key, camversity performer",
       '如何使用 SplitCam 在 <span class="accent">Camversity</span> 直播',
       "Camversity 直播",
       "Camversity 的 Performer Dashboard 外部编码器设置。",
       "Camversity 是一家正在成长的独立 cam 平台 — 主打对主播友好的工具，分成抽成比老牌网络更低。默认的 Performer Dashboard 浏览器直播工具可用，但同时开放了标准的 <strong>External Encoder</strong> 通道 — 免费 <strong style='color:var(--text)'>SplitCam</strong> 接入这里，让您用多机位场景、叠加层和滤镜直播。",
       "使用 SplitCam 在 Camversity 直播：安装 SplitCam，构建场景，在 Performer Dashboard 打开 <em>Stream Settings → External Encoder</em>，复制服务器 URL 和 stream key，粘贴到 SplitCam，Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>在 Performer Dashboard 获取 URL 和 stream key。</li><li>粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "登录 Camversity 主播账号，打开 <strong>Performer Dashboard</strong>，导航到 <strong>Stream Settings → External Encoder</strong>。页面会显示与账号绑定的服务器 URL 和 stream key — 复制两者到 SplitCam 的自定义 RTMP 字段。新账号需要先完成标准身份认证才能开播。",
       [("分成对主播友好", "Camversity 的分成比老牌网络更倾向主播 — 如果您正处于 cam 生涯初期，值得拿出来跟主平台对比一下。"),
        ("入驻比 Docler 系更轻", "Camversity 的认证比 LiveJasmin 48–72 小时的审核快得多，但仍然合规（不会出现随便、未经认证的模特）。是非常合适的中间档。"),
        ("做场景，不只是开摄像头", "Camversity 默认的 Performer Dashboard 浏览器直播只能用单信号源。通过 External Encoder 接入 SplitCam，才能解锁多机位、叠加层和美颜滤镜。"),
        _T_ETH],
       [("Camversity 官方支持 SplitCam 这类外部编码器吗？", "支持 — Performer Dashboard 在 Stream Settings 下提供 External Encoder 选项，标准 RTMP 服务器 URL 和 stream key，OBS、SplitCam、vMix 等都能接入。"),
        ("我的 Camversity stream key 在哪里？", "Performer Dashboard → Stream Settings → External Encoder — URL 和 stream key 都在这里。"),
        ("Camversity 用什么比特率？", "推 1920×1080、30 fps、3,500–6,000 Kbps、关键帧 2 秒。先用 SplitCam 自带的速度测试跑一遍。"),
        ("SplitCam 在 Camversity 上免费吗？", "是 — SplitCam 完全免费，无水印，无时间限制。Camversity 的 External Encoder 选项也免费开启。")],
       steps=[
           ("下载并安装 SplitCam", "SplitCam 是适用于 Windows 和 macOS 的免费直播软件 — 无需注册、无需信用卡、无水印。"),
           ("构建您的场景", "在 SplitCam 中添加网络摄像头。叠加叠加层、文字、第二个摄像头或手机、美颜滤镜或 AI 背景。"),
           ("获取 Camversity URL 和 stream key", "登录 Camversity 主播账号，打开 <strong>Performer Dashboard</strong>，进入 <strong>Stream Settings → External Encoder</strong>。页面会显示服务器 URL 和专属 stream key。复制两者。"),
           ("将 SplitCam 接入 Camversity", "打开 SplitCam 的 <strong>Stream Settings</strong>，把 Camversity 的 URL 和 stream key 粘贴到自定义 RTMP 字段。比特率设为 3,500–6,000 Kbps、1920×1080、30 fps、关键帧 2 秒。"),
           ("点击 Go Live", "在 SplitCam 按 <strong>Go Live</strong>，然后在 Performer Dashboard 切到在线状态。约 10 秒内信号即抵达 Camversity。"),
       ]),
    _p("skyprivate", "SkyPrivate",
       "如何使用 SplitCam 在 SkyPrivate 接单 — 基于 Skype 的按分钟私密视频通话",
       "用免费 SplitCam 作为虚拟摄像头玩 SkyPrivate — 按分钟计费的 Skype 私密视频通话、多机位场景、美颜滤镜。无水印，无需注册。",
       "skyprivate, sky private cam, skype 私密视频, skyprivate splitcam, skyprivate 虚拟摄像头, 按分钟付费 cam",
       '如何使用 SplitCam 在 <span class="accent">SkyPrivate</span> 接单',
       "SplitCam × SkyPrivate",
       "为 SkyPrivate 的 Skype 视频通话做虚拟摄像头设置。",
       "SkyPrivate 是一家走差异化路线的 cam 平台 — 它不用 RTMP 直播，而是通过 <strong>Skype 做按分钟计费的私密视频通话</strong>来变现。客户在 SkyPrivate 平台下单付费，真正的视频通话走 Skype 通道。免费 <strong style='color:var(--text)'>SplitCam</strong> 在这里以<strong>虚拟摄像头</strong>的身份接入：先在 SplitCam 搭好场景，再在 Skype 里把摄像头切到 SplitCam，然后接听 SkyPrivate 派来的付费通话。",
       "用 SplitCam 跑 SkyPrivate：安装 SplitCam，搭好场景，安装 Skype 和 SkyPrivate 插件，在 Skype 的 <em>Video Settings</em> 把摄像头和麦克风都设为 SplitCam，然后接听 SkyPrivate 的付费通话 — Skype 会把您的合成画面传给客户。"
       "<ol><li>安装 SplitCam。</li><li>在 SplitCam 搭好场景。</li><li>装 Skype + SkyPrivate 插件。</li><li>在 Skype 把摄像头设为 SplitCam。</li><li>接听通话。</li></ol>",
       "SkyPrivate 不走 RTMP 也没有 stream key — 它把 Skype 当作视频通道，再叠加一层按分钟计费的插件。先装好 Skype，再装 SkyPrivate 的浏览器或桌面插件，然后打开 Skype 的 <strong>Settings → Audio &amp; Video → Camera</strong>，把摄像头从普通网络摄像头切换到 <strong>SplitCam</strong>。SplitCam 合成出的画面（叠加层、多机位、美颜滤镜）就成了 SkyPrivate 客户在 Skype 里看到的内容。",
       [("不用 RTMP — 走虚拟摄像头", "别找服务器 URL 或 stream key。SkyPrivate 跑在 Skype 上，Skype 只把 SplitCam 当作一个普通摄像头。先在 SplitCam 搭好场景，再在 Skype 的摄像头设置里选 SplitCam。"),
        ("麦克风也设成 SplitCam", "在 Skype 的 Audio 设置里把麦克风也切到 SplitCam — 这样降噪、混音和片头音乐都能传给客户。"),
        ("先用 Skype 测试通话练手", "正式接第一通付费 SkyPrivate 通话之前，先用 Skype 的免费测试通话（Echo / Sound Test Service）确认 SplitCam 是当前摄像头，画面构图也对。"),
        _T_TEST],
       [("SkyPrivate 用 RTMP 或 stream key 吗？", "都不用。SkyPrivate 只负责下单和计费，真正的视频走 Skype。您不需要 RTMP 服务器 URL，也不需要 stream key — 在 Skype 里把摄像头设为 SplitCam 就够了。"),
        ("怎么在 Skype 里给 SkyPrivate 选 SplitCam？", "打开 Skype 的 Settings → Audio &amp; Video → Camera，从列表里选 SplitCam。麦克风也照做。这样 SkyPrivate 派来的通话会作为普通 Skype 通话进来，摄像头画面就是您在 SplitCam 里合成的内容。"),
        ("能在 SkyPrivate 上用叠加层和美颜吗？", "可以 — 在 SplitCam 场景里做好就行。Skype 只接收合成完成的单路画面，所以 SplitCam 里搞的所有东西（叠加层、美颜、AI 背景、多机位场景）SkyPrivate 客户都看得到。"),
        ("SplitCam 在 SkyPrivate 上免费吗？", "免费 — SplitCam 完全免费、无水印、无时间限制。作为 Skype 通话的虚拟摄像头，不会给通话加任何费用或品牌水印。")],
       steps=[
           ("安装 SplitCam", "SplitCam 在 Windows 和 macOS 上完全免费 — 无需注册、无需信用卡、无水印。在 SkyPrivate 的流程里，它扮演 Skype 能识别的<strong>虚拟摄像头</strong>。"),
           ("在 SplitCam 里搭好场景", "打开 SplitCam，用 <strong>Media Layers +</strong> 添加摄像头，再叠加叠加层、文字、美颜滤镜或 AI 背景。这个合成画面就是 Skype 最终交付给 SkyPrivate 客户的内容。"),
           ("装 Skype 和 SkyPrivate 插件", "在同一台电脑装好 Skype 登录，再按 SkyPrivate 的指引装 SkyPrivate 插件 / 桌面端。插件负责 SkyPrivate 侧的按分钟计费。"),
           ("把 Skype 的摄像头和麦克风切到 SplitCam", "在 Skype 里打开 <strong>Settings → Audio &amp; Video</strong>。把 <strong>Camera</strong> 设为 <strong>SplitCam</strong>，<strong>Microphone</strong> 也设为 <strong>SplitCam</strong>。再用 Skype 测试通话（Echo / Sound Test Service）跑一遍，确认画面和声音都正常。"),
           ("接 SkyPrivate 通话", "SkyPrivate 客户下单后会以 Skype 通话的形式进来 — 接听即可。客户看到的就是您在 SplitCam 里合成的画面，SkyPrivate 按分钟计费。通话中想改画面，直接在 SplitCam 里改 — Skype 会实时跟着变。"),
       ]),
    _p("manyvids", "ManyVids",
       "如何使用 SplitCam 在 MV Live（ManyVids）直播 — Creator Studio 设置",
       "使用免费 SplitCam 在 ManyVids 的 MV Live 直播 — Creator Studio 外部编码器、OnlyFans 风格的创作者经济、多机位场景。无水印，无需注册。",
       "manyvids 直播, mv live, manyvids 直播 broadcast, manyvids obs, mv live external encoder, manyvids stream key, manyvids 创作者",
       '如何使用 SplitCam 在 <span class="accent">MV Live</span> 直播',
       "MV Live 直播",
       "ManyVids MV Live 的 Creator Studio 外部编码器设置。",
       "ManyVids 是创作者经济型平台 — 卖片、定制视频、粉丝俱乐部订阅，再加上直播产品 <strong>MV Live</strong>。Creator Studio 自带的浏览器直播工具能用，但它同时开放了标准的 <strong>External Encoder</strong> 通道 — 免费 <strong style='color:var(--text)'>SplitCam</strong> 接入这里，让您在这个对创作者友好的平台上用多机位场景、叠加层和滤镜直播。",
       "用 SplitCam 在 MV Live 直播：安装 SplitCam，搭好场景，在 Creator Studio 打开 <em>MV Live → Broadcast Settings → External Encoder</em>，复制服务器 URL 和 stream key，粘贴到 SplitCam，Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>在 Creator Studio 取 URL 和 stream key。</li><li>粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "登录 ManyVids 创作者账号，打开 <strong>Creator Studio</strong>，进入 <strong>MV Live → Broadcast Settings → External Encoder</strong>。页面会显示与账号绑定的 <strong>服务器 URL</strong> 和 <strong>stream key</strong> — 复制两者到 SplitCam 的自定义 RTMP 字段。账号需要完成完整的实名认证（身份证 + 税务）才能解锁 MV Live。",
       [("不只是直播，是创作者经济", "ManyVids 不是纯 cam 平台 — MV Live 只是其中一条收入线，跟卖片、定制视频、粉丝俱乐部订阅并列。把直播当成给其他变现产品引流的入口。"),
        ("MV Live 内部的代币打赏", "MV Live 直播间里有自己的代币打赏体系。可以参考 Chaturbate / Stripchat 的玩法做目标菜单和奖励触发器 — 在 ManyVids 现有粉丝群里转化率很不错。"),
        ("浏览器 vs 外部编码器", "Creator Studio 自带的浏览器直播工具只能单机位。通过 External Encoder 接入 SplitCam，才能解锁多机位场景、叠加层和滤镜。"),
        _T_ETH],
       [("MV Live（ManyVids）支持 SplitCam 这种外部编码器吗？", "支持 — Creator Studio 的 MV Live 板块在 Broadcast Settings 下有 External Encoder 选项。标准 RTMP 服务器 URL 和 stream key，OBS、SplitCam、vMix 都能接入。"),
        ("我的 MV Live stream key 在哪里？", "Creator Studio → MV Live → Broadcast Settings → External Encoder。服务器 URL 和 stream key 都在这里 — 两者都复制到 SplitCam 的自定义 RTMP 字段。"),
        ("MV Live 用什么比特率？", "推 1920×1080、30 fps、3,500–6,000 Kbps、关键帧 2 秒。先用 SplitCam 自带的速度测试跑一遍。"),
        ("SplitCam 在 MV Live 上免费吗？", "免费 — SplitCam 完全免费，无水印，无时间限制。ManyVids 在 Creator Studio 里开放的外部编码器选项也免费。")],
       steps=[
           ("下载并安装 SplitCam", "SplitCam 是适用于 Windows 和 macOS 的免费直播软件 — 无需注册、无需信用卡、无水印。"),
           ("搭好场景", "打开 SplitCam 添加摄像头。叠加叠加层、文字、第二个摄像头或手机、美颜滤镜或 AI 背景 — 给 MV Live 的目标揭晓和奖励触发器搭舞台再合适不过。"),
           ("取 MV Live 的 URL 和 stream key", "登录 ManyVids 创作者账号，打开 <strong>Creator Studio</strong>，进入 <strong>MV Live → Broadcast Settings → External Encoder</strong>。页面会显示 <strong>服务器 URL</strong> 和专属 <strong>stream key</strong>。复制两者。"),
           ("把 SplitCam 接到 MV Live", "在 SplitCam 打开 <strong>Stream Settings</strong>，把 MV Live 的服务器 URL 和 stream key 粘贴到自定义 RTMP 字段。比特率设为 3,500–6,000 Kbps、1920×1080、30 fps、关键帧 2 秒。"),
           ("点击 Go Live", "在 SplitCam 按 <strong>Go Live</strong>，然后在 Creator Studio 启动 MV Live 直播。约 10 秒内信号就抵达 MV Live 观众端。"),
       ]),
    _p("fansly", "Fansly",
       "如何使用 SplitCam 在 Fansly Live 直播 — Creator Dashboard 外部编码器",
       "使用免费 SplitCam 在 Fansly Live 直播 — Creator Dashboard 外部编码器、OnlyFans 的直接竞争对手、多机位场景、美颜滤镜。无水印，无需注册。",
       "fansly 直播, fansly live, fansly broadcast, fansly obs, fansly external encoder, fansly rtmp, fansly stream key, fansly 创作者",
       '如何使用 SplitCam 在 <span class="accent">Fansly Live</span> 直播',
       "Fansly 直播",
       "Fansly 的 Creator Dashboard 外部编码器设置。",
       "Fansly 是 OnlyFans 的直接竞争对手，内容尺度更宽，创作者数量也在持续增长 — 订阅、按次付费内容外加直播产品 <strong>Fansly Live</strong>。自带的浏览器直播工具可用，但 <strong>Creator Dashboard</strong> 同时开放标准的 <strong>External Encoder</strong> 通道 — 免费 <strong style='color:var(--text)'>SplitCam</strong> 接入这里，让您用多机位场景、叠加层和滤镜直播给订阅用户。",
       "用 SplitCam 在 Fansly Live 直播：安装 SplitCam，搭好场景，在 Creator Dashboard 打开 <em>Live → Broadcast Settings → External Encoder</em>，复制服务器 URL 和 stream key，粘贴到 SplitCam，Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>在 Creator Dashboard 取 URL 和 stream key。</li><li>粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "登录 Fansly 创作者账号，打开 <strong>Creator Dashboard</strong>，进入 <strong>Live → Broadcast Settings → External Encoder</strong>。页面会显示与账号绑定的 <strong>服务器 URL</strong> 和 <strong>stream key</strong> — 复制两者到 SplitCam 的自定义 RTMP 字段。创作者账号要先完成身份认证，Fansly Live 才会开放。",
       [("订阅制粉丝群优先", "Fansly 的观众池基于订阅 — 看到您直播的，是每个月已经在付钱的人。要做能奖励忠诚度的内容（专属 Q&amp;A、幕后花絮、定制打赏目标），别一味追公屏热闹的指标。"),
        ("订阅之外还有打赏", "Fansly Live 在基础订阅之外还支持直播间打赏。对成熟创作者来说，订阅 + 打赏的组合收入往往跑赢纯 cam 平台的纯打赏模式。"),
        ("浏览器直播 vs 外部编码器", "默认浏览器直播只能单信号源。通过 External Encoder 接入 SplitCam，才能解锁多机位、叠加层、美颜滤镜和 AI 背景 — 让画面质感配得上订阅内容的价位。"),
        _T_ETH],
       [("Fansly Live 支持 SplitCam 这种外部编码器吗？", "支持 — Creator Dashboard 的 Live 板块在 Broadcast Settings 下提供 External Encoder 选项。标准 RTMP 服务器 URL 和 stream key，OBS、SplitCam、vMix 都能接入。"),
        ("我的 Fansly stream key 在哪里？", "Creator Dashboard → Live → Broadcast Settings → External Encoder。服务器 URL 和 stream key 都在这里。两者都复制到 SplitCam 的自定义 RTMP 字段。"),
        ("Fansly Live 用什么比特率？", "推 1920×1080、30 fps、3,500–6,000 Kbps、关键帧 2 秒。先用 SplitCam 自带的速度测试跑一遍。"),
        ("SplitCam 在 Fansly 上免费吗？", "免费 — SplitCam 完全免费，无水印，无时间限制。Fansly 在 Creator Dashboard 里开放的外部编码器选项也免费。")],
       steps=[
           ("下载并安装 SplitCam", "SplitCam 是适用于 Windows 和 macOS 的免费直播软件 — 无需注册、无需信用卡、无水印。"),
           ("搭好场景", "打开 SplitCam 添加摄像头。叠加叠加层、文字、第二个摄像头或手机、美颜滤镜或 AI 背景 — 精致的场景才撑得起付费订阅用户的预期。"),
           ("取 Fansly 的 URL 和 stream key", "登录 Fansly 创作者账号，打开 <strong>Creator Dashboard</strong>，进入 <strong>Live → Broadcast Settings → External Encoder</strong>。页面会显示 <strong>服务器 URL</strong> 和专属 <strong>stream key</strong>。复制两者。"),
           ("把 SplitCam 接到 Fansly", "在 SplitCam 打开 <strong>Stream Settings</strong>，把 Fansly 的服务器 URL 和 stream key 粘贴到自定义 RTMP 字段。比特率设为 3,500–6,000 Kbps、1920×1080、30 fps、关键帧 2 秒。"),
           ("点击 Go Live", "在 SplitCam 按 <strong>Go Live</strong>，然后在 Creator Dashboard 启动 Fansly Live 直播。约 10 秒内信号就抵达您的 Fansly 订阅者。"),
       ]),
    _p("ifriends", "iFriends",
       "如何使用 SplitCam 在 iFriends 直播 — Model Center 外部编码器",
       "使用免费 SplitCam 在 iFriends 直播 — Model Center 外部编码器、长期独立 cam 网络、多机位场景。无水印，无需注册。",
       "ifriends 直播, ifriends obs, ifriends external encoder, ifriends rtmp, ifriends stream key, ifriends model center, ifriends.net",
       '如何使用 SplitCam 在 <span class="accent">iFriends</span> 直播',
       "iFriends 直播",
       "iFriends 成熟 Model Center 的外部编码器设置。",
       "iFriends（WebPower 旗下）是运营时间最长的独立 cam 网络之一 — 盈利稳定，用户黏性高，自带的 Model Center 比浏览器直播器普及前就已经成型。平台从 Model Center 开放了标准的 <strong>外部编码器</strong> 通道，免费 <strong style='color:var(--text)'>SplitCam</strong> 接入这里 — 在这个老牌网络上用现代多机位场景、叠加层和滤镜直播。",
       "用 SplitCam 在 iFriends 直播：安装 SplitCam，搭好场景，在 Model Center 打开 <em>Broadcast Settings → External Encoder</em>，复制服务器 URL 和 stream key，粘贴到 SplitCam，Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>在 Model Center 取 URL 和 stream key。</li><li>粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "登录 iFriends 模特账号，打开 <strong>Model Center</strong>，进入 <strong>Broadcast Settings → External Encoder</strong>。页面会显示与账号绑定的 <strong>服务器 URL</strong> 和 <strong>stream key</strong> — 复制两者到 SplitCam 的自定义 RTMP 字段。iFriends 对新模特账号的审核较为严格但流程正规；通过审核后，外部编码器选项就一直可用。",
       [("长尾受众、成熟网络", "iFriends 从上世纪 90 年代末就在运营，用户黏性很高 — 很多观众是长期订阅会员，不是过路客。对成熟模特来说收入稳定，新人增长会慢一些。"),
        ("浏览器直播器 vs 外部编码器", "iFriends 自带的浏览器直播器是多机位 UX 普及前的产物。改用 SplitCam 通过 External Encoder 接入，是一次明显升级 — 多机位场景、叠加层和美颜滤镜，旧工具都做不到。"),
        ("结算稳定，意外少", "iFriends 母公司 WebPower 几十年来一直按时给模特结款 — 结算周期比新派加密结算平台慢一些，但翻车的故事极少。"),
        _T_ETH],
       [("iFriends 官方支持 SplitCam 这种外部编码器吗？", "支持 — Model Center 的 Broadcast Settings 下提供 External Encoder 选项。标准 RTMP 服务器 URL 和 stream key，账号通过审核后 OBS、SplitCam、vMix 都能接入。"),
        ("我的 iFriends stream key 在哪里？", "Model Center → Broadcast Settings → External Encoder。服务器 URL 和 stream key 都在这里 — 两者都复制到 SplitCam 的自定义 RTMP 字段。"),
        ("iFriends 用什么比特率？", "推 1920×1080、30 fps、3,500–6,000 Kbps、关键帧 2 秒。先用 SplitCam 自带的速度测试跑一遍。"),
        ("SplitCam 在 iFriends 上免费吗？", "免费 — SplitCam 完全免费，无水印，无时间限制。iFriends 在 Model Center 里开放的外部编码器选项也免费。")],
       steps=[
           ("下载并安装 SplitCam", "SplitCam 是适用于 Windows 和 macOS 的免费直播软件 — 无需注册、无需信用卡、无水印。"),
           ("搭好场景", "打开 SplitCam 添加摄像头。叠加叠加层、文字、第二个摄像头或手机、美颜滤镜或 AI 背景 — 在这个老牌网络上，精致的现代场景特别能脱颖而出。"),
           ("取 iFriends 的 URL 和 stream key", "登录 iFriends 模特账号，打开 <strong>Model Center</strong>，进入 <strong>Broadcast Settings → External Encoder</strong>。页面会显示 <strong>服务器 URL</strong> 和专属 <strong>stream key</strong>。复制两者。"),
           ("把 SplitCam 接到 iFriends", "在 SplitCam 打开 <strong>Stream Settings</strong>，把 iFriends 的服务器 URL 和 stream key 粘贴到自定义 RTMP 字段。比特率设为 3,500–6,000 Kbps、1920×1080、30 fps、关键帧 2 秒。"),
           ("点击 Go Live", "在 SplitCam 按 <strong>Go Live</strong>，然后在 iFriends Model Center 上线。约 10 秒内信号就抵达网络。"),
       ]),
    _p("babestation", "Babestation",
       "如何使用 SplitCam 在 Babestation 直播 — 英国 cam 网络设置",
       "使用免费 SplitCam 在 Babestation 直播 — Performer Hub 外部编码器、英国成人电视 / cam 网络、多机位场景、叠加层。无水印，无需注册。",
       "babestation 直播, babestation cam, babestation obs, babestation external encoder, babestation rtmp, babestation performer, uk cam network",
       '如何使用 SplitCam 在 <span class="accent">Babestation</span> 直播',
       "Babestation 直播",
       "Babestation 英国 Performer Hub 的外部编码器设置。",
       "Babestation 是英国头部的成人电视 / cam 网络 — 电视频道 + 直播 cam 的混合形态，cam 信号来自登录 Performer Hub 的主播。平台从 Performer Hub 开放标准的 <strong>外部编码器</strong> 通道，免费 <strong style='color:var(--text)'>SplitCam</strong> 接入这里 — 独立英国主播可以用多机位场景、叠加层和美颜滤镜直播，画质突破 Babestation 自带电视演播室风格直播器的上限。",
       "用 SplitCam 在 Babestation 直播：安装 SplitCam，搭好场景，在 Performer Hub 打开 <em>Broadcast Settings → External Encoder</em>，复制服务器 URL 和 stream key，粘贴到 SplitCam，Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>在 Performer Hub 取 URL 和 stream key。</li><li>粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "登录 Babestation 主播账号，打开 <strong>Performer Hub</strong>，进入 <strong>Broadcast Settings → External Encoder</strong>。页面会显示与账号绑定的 <strong>服务器 URL</strong> 和 <strong>stream key</strong> — 复制两者到 SplitCam 的自定义 RTMP 字段。Babestation 的英国主播入驻流程包含按英国年龄验证法规执行的 ID 认证。",
       [("英国优先的受众和档期", "Babestation 主力流量在英国晚间 / 通宵（GMT/BST）。如果您在别的时区，按英国深夜档播出明显比按本地黄金档转化更好。"),
        ("观众期待电视演播室质感", "Babestation 品牌绑定的是电视频道 — 观众对场景和打光的期待，比一般 cam 直播更挑剔。SplitCam 的场景能力（叠加层、品牌文字、AI 背景）正好对得上平台的精致调性。"),
        ("独立主播 vs 演播室主播", "Babestation 同时接英国演播室和独立主播。通过 External Encoder 接入的独立主播，按和演播室同样的结算模型分成。"),
        _T_ETH],
       [("Babestation 支持 SplitCam 这种外部编码器吗？", "支持 — Performer Hub 的 Broadcast Settings 下提供 External Encoder 选项。标准 RTMP 服务器 URL 和 stream key，主播完成认证后 OBS、SplitCam、vMix 都能接入。"),
        ("我的 Babestation stream key 在哪里？", "Performer Hub → Broadcast Settings → External Encoder。服务器 URL 和 stream key 都在这里 — 两者都复制到 SplitCam 的自定义 RTMP 字段。"),
        ("Babestation 用什么比特率？", "推 1920×1080、30 fps、3,500–6,000 Kbps、关键帧 2 秒。英国宽带上传普遍不错，但先用 SplitCam 自带的速度测试跑一遍。"),
        ("SplitCam 在 Babestation 上免费吗？", "免费 — SplitCam 完全免费，无水印，无时间限制。Babestation 在 Performer Hub 里开放的外部编码器选项也免费。")],
       steps=[
           ("下载并安装 SplitCam", "SplitCam 是适用于 Windows 和 macOS 的免费直播软件 — 无需注册、无需信用卡、无水印。"),
           ("搭好场景", "打开 SplitCam 添加摄像头。叠加叠加层、文字、第二个摄像头或手机、美颜滤镜或 AI 背景 — 对齐 Babestation 电视演播室的制作质感，才能脱颖而出。"),
           ("取 Babestation 的 URL 和 stream key", "登录 Babestation 主播账号，打开 <strong>Performer Hub</strong>，进入 <strong>Broadcast Settings → External Encoder</strong>。页面会显示 <strong>服务器 URL</strong> 和专属 <strong>stream key</strong>。复制两者。"),
           ("把 SplitCam 接到 Babestation", "在 SplitCam 打开 <strong>Stream Settings</strong>，把 Babestation 的服务器 URL 和 stream key 粘贴到自定义 RTMP 字段。比特率设为 3,500–6,000 Kbps、1920×1080、30 fps、关键帧 2 秒。"),
           ("点击 Go Live", "在 SplitCam 按 <strong>Go Live</strong>，然后在 Performer Hub 上线。约 10 秒内信号就抵达 Babestation 的英国观众。"),
       ]),
    _p("adultwork", "AdultWork",
       "如何使用 SplitCam 在 AdultWork 直播 — Members Area 外部编码器",
       "使用免费 SplitCam 在 AdultWork 直播 — Members Area 外部编码器、英国成人服务市场附带 cam 功能、多机位场景。无水印，无需注册。",
       "adultwork 直播, adultwork cam, adultwork obs, adultwork external encoder, adultwork rtmp, adultwork webcam, uk cam",
       '如何使用 SplitCam 在 <span class="accent">AdultWork</span> 直播',
       "AdultWork 直播",
       "AdultWork 英国 Members Area cam 功能的外部编码器设置。",
       "AdultWork 是老牌的英国成人服务市场 — 主业是陪伴预约、相册 / 视频销售、电话服务，附带直播 <strong>webcam 功能</strong>。平台从 Members Area 开放标准的 <strong>外部编码器</strong> 通道，免费 <strong style='color:var(--text)'>SplitCam</strong> 接入这里 — 独立英国主播可以用多机位场景、叠加层和滤镜，叠加一条直播 cam 收入线。",
       "用 SplitCam 在 AdultWork 直播：安装 SplitCam，搭好场景，在 Members Area 打开 <em>Members → Broadcasting → External Encoder</em>，复制服务器 URL 和 stream key，粘贴到 SplitCam，Go Live。"
       "<ol><li>安装 SplitCam。</li><li>添加摄像头 + 场景。</li><li>在 Members Area 取 URL 和 stream key。</li><li>粘贴到 SplitCam。</li><li>按 Go Live。</li></ol>",
       "登录 AdultWork 主播账号，打开 <strong>Members Area</strong>，进入 <strong>Members → Broadcasting → External Encoder</strong>。页面会显示与账号绑定的 <strong>服务器 URL</strong> 和 <strong>stream key</strong> — 复制两者到 SplitCam 的自定义 RTMP 字段。开通直播 cam 功能必须完成认证，覆盖英国年龄验证合规要求。",
       [("从 AdultWork 其他业务交叉引流", "AdultWork 的优势在于现成的客户池 — 观众可能已经在订您的相册 / 视频 / 电话服务。把直播当作让没体验过 cam 的老客户进入直播间的入口，比追陌生人更划算。"),
        ("入口在 Members Area", "别在公开站找直播器 — 主播侧的所有功能都在 Members Area 里。直播设置、结算、内容管理全部在那里。"),
        ("以英国为主，结算面向国际", "流量主体是英国 / 欧盟。结算支持国际，走标准银行转账 / 电子钱包，平台上周结较为常见。"),
        _T_ETH],
       [("AdultWork 支持 SplitCam 这种外部编码器吗？", "支持 — Members Area 的 Broadcasting 下提供 External Encoder 选项。标准 RTMP 服务器 URL 和 stream key，主播完成认证后 OBS、SplitCam、vMix 都能接入。"),
        ("我的 AdultWork stream key 在哪里？", "Members Area → Members → Broadcasting → External Encoder。服务器 URL 和 stream key 都在这里 — 两者都复制到 SplitCam 的自定义 RTMP 字段。"),
        ("AdultWork 用什么比特率？", "推 1920×1080、30 fps、3,500–6,000 Kbps、关键帧 2 秒。先用 SplitCam 自带的速度测试跑一遍。"),
        ("SplitCam 在 AdultWork 上免费吗？", "免费 — SplitCam 完全免费，无水印，无时间限制。AdultWork 在 Members Area 里开放的外部编码器选项也免费。")],
       steps=[
           ("下载并安装 SplitCam", "SplitCam 是适用于 Windows 和 macOS 的免费直播软件 — 无需注册、无需信用卡、无水印。"),
           ("搭好场景", "打开 SplitCam 添加摄像头。叠加叠加层、文字、第二个摄像头或手机、美颜滤镜或 AI 背景 — 用叠加层在直播中宣传您在 AdultWork 上的其他内容 / 电话服务，做交叉引流。"),
           ("取 AdultWork 的 URL 和 stream key", "登录 AdultWork 主播账号，打开 <strong>Members Area</strong>，进入 <strong>Members → Broadcasting → External Encoder</strong>。页面会显示 <strong>服务器 URL</strong> 和专属 <strong>stream key</strong>。复制两者。"),
           ("把 SplitCam 接到 AdultWork", "在 SplitCam 打开 <strong>Stream Settings</strong>，把 AdultWork 的服务器 URL 和 stream key 粘贴到自定义 RTMP 字段。比特率设为 3,500–6,000 Kbps、1920×1080、30 fps、关键帧 2 秒。"),
           ("点击 Go Live", "在 SplitCam 按 <strong>Go Live</strong>，然后在 Members Area 上线。约 10 秒内信号就抵达 AdultWork 观众端。"),
       ]),
]
